mapnik 3.0.13
Homebrew/homebrew-core pull request #10004
Opened 2017-02-15 13:27 UTC by SrihariThalla

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2017-02-15 16:17 UTC, MikeMcQuaid requested changes

2017-02-15 16:17 UTC, MikeMcQuaid commented on Formula/mapnik.rb
>    revision 3
Please remove this line, thanks!

2017-02-15 16:33 UTC, SrihariThalla commented on Formula/mapnik.rb
>    revision 3
Done with amended commit!

2017-02-18 09:56 UTC, nijikon commented
You are awesome, thanks for your contribution! :tada:

2017-02-18 09:57 UTC, closed without merging