git-quick-stats 1.0.1 (new formula)
Homebrew/homebrew-core pull request #10011
Opened 2017-02-15 20:24 UTC by arzzen

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Allow user to install [git-quick-stats](https://github.com/arzzen/git-quick-stats/)

2017-02-18 22:37 UTC, dunn commented on Formula/git-quick-stats.rb
> +    system "false"
You'll need a test here, please!

2017-02-19 19:11 UTC, arzzen commented on Formula/git-quick-stats.rb
> +    system "false"
i fixed it

2017-02-19 19:35 UTC, dunn commented on Formula/git-quick-stats.rb
> +    assert File.exist?("#{bin}/git-quick-stats")
You can create a git repository in the temporary directory that the test runs in; see e.g., [`blackbox.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/blackbox.rb)

2017-02-20 19:24 UTC, arzzen commented on Formula/git-quick-stats.rb
> +    assert File.exist?("#{bin}/git-quick-stats")
#dunn updated

2017-02-20 21:30 UTC, MikeMcQuaid requested changes

2017-02-20 21:30 UTC, MikeMcQuaid commented on Formula/git-quick-stats.rb
> +    assert File.exist?("#{bin}/git-quick-stats")
Can remove this line.

2017-02-20 21:30 UTC, MikeMcQuaid commented on Formula/git-quick-stats.rb
> +    assert_match /All branches \(sorted by most recent commit\)/, shell_output("#{bin}/git-quick-stats branchesByDate").strip
Make the first argument a string so `(` doesn't need escaped. A newline before `shell_output` so it's <= 80 characters. Skip the `.strip`

2017-02-20 21:30 UTC, MikeMcQuaid commented on Formula/git-quick-stats.rb
> +    assert_match /^Invalid argument/, shell_output("#{bin}/git-quick-stats command").strip
Remove the `.strip`.

2017-02-21 18:16 UTC, arzzen commented on Formula/git-quick-stats.rb
> +    assert_match /^Invalid argument/, shell_output("#{bin}/git-quick-stats command").strip
@MikeMcQuaid done

2017-02-21 18:16 UTC, arzzen commented on Formula/git-quick-stats.rb
> +    assert_match /All branches \(sorted by most recent commit\)/, shell_output("#{bin}/git-quick-stats branchesByDate").strip
done

2017-02-21 18:16 UTC, arzzen commented on Formula/git-quick-stats.rb
> +    assert File.exist?("#{bin}/git-quick-stats")
done

2017-02-21 18:51 UTC, arzzen commented
@MikeMcQuaid done

2017-02-21 18:54 UTC, MikeMcQuaid approved these changes

2017-02-21 18:54 UTC, merged

2017-02-21 18:54 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!