gauge 0.8.0
Homebrew/homebrew-core pull request #10032
Opened 2017-02-16 12:14 UTC by kashishm

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-17 20:01 UTC, JCount requested changes
Please also update the `gauge_screenshot` `go_resource` to the most recent revision. Thanks.

2017-02-17 20:01 UTC, JCount commented on Formula/gauge.rb
> +  url "https://github.com/getgauge/gauge/archive/v0.8.0.1.tar.gz"
Please update the version numbers in your PR (commit message and PR title) to accurately reflect the exact version being built.

2017-02-18 07:56 UTC, ilovezfs commented on Formula/gauge.rb
> +    assert_match version.to_s[0, 5], shell_output("#{bin}/gauge -v")
this is a bit unusual. what was the problem?

2017-02-18 08:05 UTC, kashishm commented on Formula/gauge.rb
> +    assert_match version.to_s[0, 5], shell_output("#{bin}/gauge -v")
`gauge -v` shows version in the format `MAJOR.MINOR.PATCH` which is `0.8.0` but the version in this tag is `0.8.0.1`. So, I am using this to match `0.8.0.1` with `0.8.0`(`MAJOR.MINOR.PATCH`).

2017-02-18 19:48 UTC, JCount approved these changes

2017-02-18 20:20 UTC, closed without merging

2017-02-18 20:21 UTC, JCount commented
Thank you for your contribution, @kashishm!