New formula dhall-json
Homebrew/homebrew-core pull request #10091
Opened 2017-02-17 23:20 UTC by newhoggy

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-17 23:22 UTC, newhoggy commented
I have this problem:

```
10:20 $ brew audit --strict dhall-json
==> Installing or updating 'rubocop' gem
Fetching: ast-2.3.0.gem (100%)
Successfully installed ast-2.3.0
Fetching: parser-2.4.0.0.gem (100%)
Error: no implicit conversion of nil into String
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/installer.rb:171:in `check_executable_overwrite'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/installer.rb:384:in `block in generate_bin'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/installer.rb:371:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/installer.rb:371:in `generate_bin'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/installer.rb:231:in `install'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency_installer.rb:379:in `block in install'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `each_with_index'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `install'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/commands/install_command.rb:166:in `block in execute'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/commands/install_command.rb:158:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/commands/install_command.rb:158:in `execute'
/usr/local/Homebrew/Library/Homebrew/utils.rb:212:in `install_gem_setup_path!'
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:50:in `check_style_impl'
/usr/local/Homebrew/Library/Homebrew/cmd/style.rb:45:in `check_style_json'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:70:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

2017-02-17 23:50 UTC, newhoggy commented
```
(java-1.8.0 ghc-8.0.2) ✔ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core [new-formula-dhall-json|✚ 1]
10:39 $ brew install --build-from-source dhall-json
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Using the sandbox
==> Downloading https://hackage.haskell.org/package/dhall-json-1.0.0/dhall-json-1.0.0.tar.gz
Already downloaded: /Users/jky/Library/Caches/Homebrew/dhall-json-1.0.0.tar.gz
==> cabal sandbox init
==> cabal update
==> cabal install --jobs=8 --max-backjumps=100000 --only-dependencies
==> cabal install --jobs=8 --max-backjumps=100000 --prefix=/usr/local/Cellar/dhall-json/1.0.0
🍺  /usr/local/Cellar/dhall-json/1.0.0: 6 files, 70.5M, built in 9 minutes 14 seconds
```

2017-02-17 23:52 UTC, newhoggy commented
How do I create a `test` section that runs:

```echo 1 | dhall-to-json``` and asserts exit code 1?

2017-02-18 00:13 UTC, newhoggy commented
Installing rubocop manually doesn't help either:

```
11:08 $ gem install rubocop
Successfully installed parser-2.4.0.0
Fetching: unicode-display_width-1.1.3.gem (100%)
Successfully installed unicode-display_width-1.1.3
Fetching: rubocop-0.47.1.gem (100%)
Successfully installed rubocop-0.47.1
Parsing documentation for parser-2.4.0.0
Installing ri documentation for parser-2.4.0.0
Parsing documentation for unicode-display_width-1.1.3
Installing ri documentation for unicode-display_width-1.1.3
Parsing documentation for rubocop-0.47.1
Installing ri documentation for rubocop-0.47.1
Done installing documentation for parser, unicode-display_width, rubocop after 25 seconds
3 gems installed
```

2017-02-20 12:17 UTC, MikeMcQuaid requested changes

2017-02-20 12:17 UTC, MikeMcQuaid commented on Formula/dhall-json.rb
> +  end
Remove this, it'll be added when we pull this.

2017-02-20 12:17 UTC, MikeMcQuaid commented on Formula/dhall-json.rb
> +    assert_match "1", shell_output("./testing.sh")
`assert_match "1", pipe_output("dhall-to-json", "1", 0)` can replace everything else in the test.

2017-02-20 12:18 UTC, MikeMcQuaid commented
> gem install rubocop

Run `gem install rubocop --user`. If that still fails there's some local issues you have with your Ruby installation.

2017-02-20 21:06 UTC, newhoggy commented
Wow:

```
08:05 $ rubocop --version
/Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/ext/parser.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0022 p:-17579486705692 s:0101 e:000100 TOP    [FINISH]
c:0021 p:---- s:0099 e:000098 CFUNC  :require
c:0020 p:0115 s:0095 e:000094 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0019 p:0009 s:0085 e:000084 CLASS  /Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/ext.rb:13
c:0018 p:0011 s:0083 e:000082 CLASS  /Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/ext.rb:12
c:0017 p:0057 s:0081 e:000080 TOP    /Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/ext.rb:9 [FINISH]
c:0016 p:---- s:0079 e:000078 CFUNC  :require
c:0015 p:0115 s:0075 e:000074 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0014 p:0019 s:0065 e:000064 CLASS  /Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json.rb:58
c:0013 p:0017 s:0063 e:000062 TOP    /Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json.rb:54 [FINISH]
c:0012 p:---- s:0061 e:000060 CFUNC  :require
c:0011 p:0115 s:0057 e:000056 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0010 p:0007 s:0047 e:000046 TOP    /Users/jky/.rvm/gems/ruby-2.1.5/gems/rubocop-0.47.1/lib/rubocop/formatter/json_formatter.rb:3 [FINISH]
c:0009 p:---- s:0045 e:000044 CFUNC  :require
c:0008 p:0115 s:0041 e:000040 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0007 p:3535 s:0031 e:000030 TOP    /Users/jky/.rvm/gems/ruby-2.1.5/gems/rubocop-0.47.1/lib/rubocop.rb:459 [FINISH]
c:0006 p:---- s:0029 e:000028 CFUNC  :require
c:0005 p:0115 s:0025 e:000024 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0004 p:0038 s:0015 e:000014 TOP    /Users/jky/.rvm/gems/ruby-2.1.5/gems/rubocop-0.47.1/bin/rubocop:6 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0118 s:0006 E:001848 EVAL   /Users/jky/.rvm/gems/ruby-2.1.5/bin/rubocop:23 [FINISH]
c:0001 p:0000 s:0002 E:001c58 TOP    [FINISH]

/Users/jky/.rvm/gems/ruby-2.1.5/bin/rubocop:23:in `<main>'
/Users/jky/.rvm/gems/ruby-2.1.5/bin/rubocop:23:in `load'
/Users/jky/.rvm/gems/ruby-2.1.5/gems/rubocop-0.47.1/bin/rubocop:6:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/jky/.rvm/gems/ruby-2.1.5/gems/rubocop-0.47.1/lib/rubocop.rb:459:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/jky/.rvm/gems/ruby-2.1.5/gems/rubocop-0.47.1/lib/rubocop/formatter/json_formatter.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json.rb:54:in `<top (required)>'
/Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json.rb:58:in `<module:JSON>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/ext.rb:9:in `<top (required)>'
/Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/ext.rb:12:in `<module:JSON>'
/Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/ext.rb:13:in `<module:Ext>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------

* Loaded script: /Users/jky/.rvm/gems/ruby-2.1.5/bin/rubocop

* Loaded features:

    0 enumerator.so
    1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/enc/encdb.bundle
    2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/enc/trans/transdb.bundle
    3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb
    4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/compatibility.rb
    5 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/defaults.rb
    6 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/deprecate.rb
    7 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/errors.rb
    8 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb
    9 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/requirement.rb
   10 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/platform.rb
   11 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb
   12 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/exceptions.rb
   13 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
   14 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb
   15 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb
   16 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
   17 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb
   18 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb
   19 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/path_support.rb
   20 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb
   21 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/racc/cparse.bundle
   22 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/racc/parser.rb
   23 /Users/jky/.rvm/gems/ruby-2.1.5/gems/ast-2.3.0/lib/ast/node.rb
   24 /Users/jky/.rvm/gems/ruby-2.1.5/gems/ast-2.3.0/lib/ast/processor/mixin.rb
   25 /Users/jky/.rvm/gems/ruby-2.1.5/gems/ast-2.3.0/lib/ast/processor.rb
   26 /Users/jky/.rvm/gems/ruby-2.1.5/gems/ast-2.3.0/lib/ast/sexp.rb
   27 /Users/jky/.rvm/gems/ruby-2.1.5/gems/ast-2.3.0/lib/ast.rb
   28 /Users/jky/.rvm/gems/ruby-2.1.5/gems/parser-2.4.0.0/lib/parser/version.rb
   29 /Users/jky/.rvm/gems/ruby-2.1.5/gems/parser-2.4.0.0/lib/parser/messages.rb
   30 /Users/jky/.rvm/gems/ruby-2.1.5/gems/parser-2.4.0.0/lib/parser/ast/node.rb
   31 /Users/jky/.rvm/gems/ruby-2.1.5/gems/parser- [...]

2017-02-20 21:16 UTC, newhoggy commented
PR has been updated as per review comments.  Unfortunately, I remain unable to run `rubocop`.

2017-02-20 21:31 UTC, MikeMcQuaid commented
`rm -rf /Users/jky/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/` and/or stop using RVM for running `rubocop`.

2017-02-21 00:30 UTC, newhoggy commented
Cool!

```
11:29 $ brew audit --strict dhall-json
==> Installing or updating 'rubocop' gem
Fetching: rubocop-0.47.1.gem (100%)
Successfully installed rubocop-0.47.1
1 gem installed
dhall-json:
  * Description shouldn't start with an indefinite article (A)
  * fully scope test pipe_output calls e.g. pipe_output "#{bin}/dhall-to-json"
Error: 2 problems in 1 formula
```

2017-02-21 01:22 UTC, newhoggy commented
Fixed according to audit.

2017-02-25 22:06 UTC, fxcoudert commented
On the testbot, the audit fails with:

```
Error: 2 problems in 1 formula
dhall-json:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
  * GitHub repository too new (<30 days old)
```

We also generally prefer that packages be submitted by someone other than their primary maintainer - it gives us an indication that a community will be keeping the package alive.

Maybe it would be a better fit to host this formula in a [personal tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md)?

2017-02-27 03:44 UTC, newhoggy commented
I'm not the primary maintainer of `dhall-json`.  The primary maintainer of this project is here: https://github.com/Gabriel439/ and his project is here: https://github.com/Gabriel439/Haskell-Dhall-Library

2017-02-27 03:46 UTC, newhoggy commented
I have already set up a personal tap: https://github.com/haskell-works/homebrew-haskell-works

I was not aware of the Github requirements at the time I set up this PR.

2017-02-27 08:21 UTC, MikeMcQuaid approved these changes

2017-02-27 08:21 UTC, MikeMcQuaid commented
I'm fine with accepting this given that, thanks 👍

2017-03-06 23:37 UTC, dunn commented
@BrewTestBot test this please

2017-03-12 10:17 UTC, closed without merging

2017-03-12 10:17 UTC, fxcoudert commented
Thanks a lot @newhoggy for your contribution to Homebrew!

2017-03-12 10:20 UTC, newhoggy commented
Thanks Everyone!

2017-03-14 21:02 UTC, newhoggy commented
I had a question.  How do I add bash completion support a command line tool with a brew formula?

I can install it from the command line with:

```
source <(dhall-to-json --bash-completion-script `which dhall-to-json`)
```

2017-03-14 21:09 UTC, dunn commented
It should be similar to how [`pandoc.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pandoc.rb#L27) and [`hugo.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/hugo.rb#L25-L27) do it; take a look at those and see if it works for this formula.

2017-03-15 12:01 UTC, newhoggy commented
Fantastic!  Thanks!