inlets: repo got removed
Homebrew/homebrew-core pull request #101111
Opened 2022-05-08 18:38 UTC by chenrui333

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-05-08 21:16 UTC, iMichka requested changes
I think we can disable this now. The formula has been deprecated for almost 1 year. By disabling it we give it one more year to live before being deleted.

2022-05-08 22:26 UTC, fxcoudert submitted a review, later dismissed

2022-05-09 07:15 UTC, SMillerDev commented on Formula/inlets.rb
> +  deprecate! date: "2022-05-08", because: :repo_removed
```suggestion
  disable! date: "2022-05-08", because: :repo_removed
```

2022-05-09 13:03 UTC, fxcoudert approved these changes

2022-05-09 13:04 UTC, iMichka approved these changes

2022-05-09 13:20 UTC, SMillerDev approved these changes

2022-05-09 14:05 UTC, closed without merging