operator-sdk: update formula
Homebrew/homebrew-core pull request #101238
Opened 2022-05-10 13:16 UTC by everettraven

This updates the operator-sdk formula's Go dependency and tests.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-05-10 13:16 UTC, everettraven commented
/cc @SMillerDev

2022-05-10 13:21 UTC, SMillerDev approved these changes, later dismissed

2022-05-10 15:06 UTC, Bo98 requested changes
Can you add `revision 1` so users will get this update? LGTM otherwise.

2022-05-10 15:29 UTC, everettraven commented
> Can you add `revision 1` so users will get this update? LGTM otherwise.

Should be resolved in commit https://github.com/Homebrew/homebrew-core/pull/101238/commits/58c4dec351da35e7dcb3e7e6e5e0ecb79fd8cd44

2022-05-11 02:26 UTC, Bo98 approved these changes

2022-05-11 07:53 UTC, SMillerDev approved these changes

2022-05-12 00:17 UTC, closed without merging