mupdf: add linux-only flag
Homebrew/homebrew-core pull request #101359
Opened 2022-05-12 16:41 UTC by vzhd1701

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

I am trying to build a python app that depends on [PyMuPDF](https://github.com/pymupdf/PyMuPDF) which requires `mupdf` to compile.
It compiles OK on Mac, but on Linux the linker fails with `can not be used when making a shared object; recompile with -fPIC` error. You can see it in the [build log](https://github.com/vzhd1701/homebrew-tap/runs/6409706183) for my package.

The problem goes away after proposed change in `mupdf` install script.

2022-05-12 21:12 UTC, iMichka requested changes
>  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libmupdf-third.a(jbig2_huffman.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC

Looking at the logs, it looks it tries to link against the .a static library, and this is why it is asking for `-fPIC`.

Could you try to add `shared=yes` to the make step to build shared libraries, thus avoiding the addition of the `-fPIC` flag.

2022-05-13 09:56 UTC, vzhd1701 commented
> Could you try to add `shared=yes` to the make step to build shared libraries, thus avoiding the addition of the `-fPIC` flag.

This flag turns `mupdf` into a runtime dependency, while I think it is expected that python package should be linked statically. Although I guess there is not much difference when packaging with homebrew.

Also with this flag the build does not produce `libmupdf-third.so` which is required by `PyMuPDF`. There is a [workaround](https://github.com/pymupdf/PyMuPDF/issues/1396#issuecomment-968185583) which suggests making a symbolic link for `libmupdf` that will make it compile. Which means I also need to add this to make it work
```
lib_ext = OS.mac? ? "dylib" : "so"
lib.install_symlink lib/"libmupdf.#{lib_ext}" => "libmupdf-third.#{lib_ext}"
```

What do you say? Should I add `shared=yes` and the symlink or will you accept my suggestion for a flag?
I've made a [minimal test formula](https://github.com/vzhd1701/homebrew-tap/blob/037953419fbd48482797beefcb8ff9a5bd4ed040/Formula/testmupdf.rb) if you want to test this.

2022-05-13 12:29 UTC, SMillerDev commented
`shared=yes` sounds good, and you can use `lib.install_symlink lib/shared_library("libmupdf") => shared_library("libmupdf-third")`

2022-05-15 19:56 UTC, iMichka commented
Can you bump the revision so that we ship the new files to everyone? Just add `revision 1` to the formula.

2022-05-16 06:27 UTC, vzhd1701 commented
Got some strange 401 errors

2022-05-22 09:12 UTC, vzhd1701 commented
Is there any problems that should be fixed for the merge?

2022-05-22 09:29 UTC, iMichka approved these changes
All good, thanks. I forgot to review this PR.

2022-05-22 10:05 UTC, closed without merging