gitlab-ci-multi-runner: add service plist
Homebrew/homebrew-core pull request #10150
Opened 2017-02-20 14:54 UTC by michalkosmowski

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Adds plist to gitlab-ci-multi-runner formula.

**Q:** Is there any better way of injecting user's home path?
**Q:** Any tips to make an alias for this service? `brew services start gitlab-ci-multi-runner` is really long.

2017-02-20 22:40 UTC, MikeMcQuaid requested changes

2017-02-20 22:40 UTC, MikeMcQuaid commented on Formula/gitlab-ci-multi-runner.rb
> +  plist_options :startup => true, :manual => "gitlab-ci-multi-runner start"
Drop the `:startup => true`

2017-02-20 22:40 UTC, MikeMcQuaid commented on Formula/gitlab-ci-multi-runner.rb
> +          <string>#{File.expand_path("~")}</string>
It may just be worth using `ENV["HOME"]`

2017-02-20 22:40 UTC, MikeMcQuaid commented on Formula/gitlab-ci-multi-runner.rb
> +          <string>#{File.expand_path("~")}/.gitlab-runner/config.toml</string>
What if this file doesn't exist?

2017-02-21 09:29 UTC, michalkosmowski commented on Formula/gitlab-ci-multi-runner.rb
> +          <string>#{File.expand_path("~")}/.gitlab-runner/config.toml</string>
The runner works without the config file, but cannot connect to Gitlab. It retries to load the config file every ~1s (based on the logs). 

That config file is a result of `gitlab-ci-multi-runner register` where the user passes a token, so I think we should be good here.

2017-02-21 10:26 UTC, MikeMcQuaid commented on Formula/gitlab-ci-multi-runner.rb
> +          <string>#{File.expand_path("~")}/.gitlab-runner/config.toml</string>
We'll need to figure out a way to make it clearer that this requires configuration before the plist can be used. To me that makes it a bad plist candidate, personally.

2017-02-21 10:42 UTC, michalkosmowski commented on Formula/gitlab-ci-multi-runner.rb
> +          <string>#{File.expand_path("~")}/.gitlab-runner/config.toml</string>
I see your point. On the other hand I'm not sure if anyone will miss their docs about it:
https://docs.gitlab.com/ce/ci/runners/README.html#creating-and-registering-a-runner
Technically the plist can be used, the service works on your machine, it just doesn't connect further to gitlab.com.

Anyway, i'm just scratching my itch 😉

2017-02-28 09:24 UTC, michalkosmowski commented
Hey @MikeMcQuaid any chances to merge this in?

2017-03-03 13:21 UTC, MikeMcQuaid approved these changes

2017-03-03 13:22 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-03-03 13:22 UTC, merged

2017-03-03 13:22 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!