python-runtimeonly: add keg-only formula for runtime-only Python interpreter
Homebrew/homebrew-core pull request #101751
Opened 2022-05-17 08:07 UTC by XuehaiPan

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

The file `python-runtimeonly.rb` is modified from `python@3.10.rb`. The `pip` / `setuptools` / `wheel` packages are removed.

See

- discussion https://github.com/orgs/Homebrew/discussions/3274
- PR #87075

2022-05-17 08:23 UTC, SMillerDev requested changes
Like I expressed in the discussion, I don't see a benefit from this formula. You're just moving the problem from `python@3.x` to the `python-runtime` formula. This formula fixes none of the issues you brought forth.

2022-05-17 08:39 UTC, XuehaiPan commented
> Like I expressed in the discussion, I don't see a benefit from this formula.

Any formula without PyPI packages now can depend on the runtime-only one rather than `python@3.x`. It makes our dependency tree cleaner. We can figure out which formulae truly need `python@3.x` and others are not (only need a Python interpreter).

There are too many formulae depending on `python@3.x` and the dependency tree is messed up together.

```
A                
|
+- B
|  |
|  +- C
|     |
|     +- python@3.9
+- D
|  |
|  +- E
|     |
|     +- python@3.9
...
```

Suppose formula `E` does not support `python@3.9` for the upstream issue. It will block the migration process for formulae `B` and `C`. Further blocks us to have `python@3` to be `python@3.10`.

2022-05-17 09:36 UTC, SMillerDev commented
> Since python provides some sort of backward compatibility, I don't think changing python-runtime's underlying version will be a big problem.

Then why is it proving to be such a big problem for the current versions of the formula. It has the same compatibility.

2022-05-17 09:51 UTC, XuehaiPan commented
> Then why is it proving to be such a big problem for the current versions of the formula. It has the same compatibility.

The alternatives for this PR:

1. Have a virtual formula `python@any`, or namely requirement. But I don't think it's an easy job and hard to test.
2. Update `brew audit` and support semantic `depends_on "python@3.10" => :runtimeonly`.

------

The migration problem for us is now there are two separated big dependency trees `TreeA` and `TreeB` have the same node `python@3.9`. All formulae in `union(TreeA, TreeB)` need to be migrated together when changing `python@3.9` to `python@3.10`.

2022-05-18 05:42 UTC, XuehaiPan commented
Closed in favor of splitting `glib` into two separated formulae.

2022-05-18 05:42 UTC, closed without merging