kpcli 3.7
Homebrew/homebrew-core pull request #101944
Opened 2022-05-19 22:39 UTC by Porkepix

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

2022-05-20 06:41 UTC, iMichka requested changes
Some perl resources can be updated

2022-05-21 21:27 UTC, chenrui333 commented
```
  Error: An exception occurred within a child process:
    ResourceMissingError: kpcli does not define resource "Term::Readline::Gnu"
```

2022-05-22 06:57 UTC, dawidd6 approved these changes

2022-05-22 09:30 UTC, iMichka approved these changes

2022-05-22 10:05 UTC, closed without merging