libcouchbase 2.7.2
Homebrew/homebrew-core pull request #10200
Opened 2017-02-21 20:29 UTC by mnunberg

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-25 18:08 UTC, fxcoudert requested changes

2017-02-25 18:08 UTC, fxcoudert commented on Formula/libcouchbase.rb
>    revision 1
The `revision` line should go.

2017-02-25 19:58 UTC, fxcoudert commented on Formula/libcouchbase.rb
> -  revision 1
Great. If you can squash those two commits together, it will be ready to merge.

2017-02-25 19:59 UTC, mnunberg commented
I was hoping GH's UI would allow squash :/ - doing it locally.

2017-02-25 22:27 UTC, fxcoudert approved these changes

2017-02-26 00:43 UTC, closed without merging

2017-02-26 00:44 UTC, fxcoudert commented
Thanks @mnunberg for your contribution!