Bazel 0.3.2.
Homebrew/homebrew-core pull request #10217
Opened 2017-02-22 04:52 UTC by benjyw

This is a copy of the main Bazel formula as it was at 0.3.2. The only changes are reordering the `url`, `sha256` and `head`, in order to pass `brew audit --strict`.

This formula is needed because the main Bazel formula is currently up to 0.4.4, but various repos (or past commits in those repos) will not build with 0.4.4 and require this earlier version.

2017-02-25 22:45 UTC, fxcoudert requested changes

2017-02-25 22:45 UTC, fxcoudert commented on Formula/bazel@0.3.2.rb
> +  end
The `bottle do` section will be introduced when the PR is merged

2017-02-25 22:45 UTC, fxcoudert commented on Formula/bazel@0.3.2.rb
> +
The formula would conflict with unversioned `bazel`, and thus need `keg_only :versioned_formula`

2017-02-25 22:47 UTC, fxcoudert commented
Do we want to maintain a versioned formula? Nothing in homebrew depends on `bazel` currently, so it is hard to estimate the need for this version specifically…

2017-02-26 09:42 UTC, MikeMcQuaid commented
> various repos (or past commits in those repos) will not build with 0.4.4 and require this earlier versio

Can you list these, please? Thanks!

2017-02-27 01:06 UTC, benjyw reviewed
The motivating example for me is Kythe (https://github.com/google/kythe).  The most recent release is v0.0.26, which requires Bazel 0.3.2 and doesn't build under 0.4 (current HEAD in that repo does build with 0.4, but there is no release that does).

Likewise, it appears that versions of TensorFlow (https://github.com/tensorflow/tensorflow/) prior to the recent v1.0.0 release (e.g., v0.12.0) require Bazel 0.3.2.

There aren't many repos out there using Bazel, the only examples I know of are Google open-source projects.

If you think this isn't useful enough to justify being in core, I can create my own tap for bazel-related formulae.

2017-03-05 23:53 UTC, fxcoudert commented
A personal tap is probably better. The formula otherwise looks good, with just one minor style issue flagged up by audit:

  * `keg_only` (line 10) should be put before `depends_on` (line 9)

2017-03-06 01:48 UTC, benjyw commented
Sounds good, I've put a tap up here:

https://github.com/benjyw/homebrew-bazel

Will close this pull request. Thanks!

2017-03-06 01:48 UTC, closed without merging