scriptcs-0.17.1
Homebrew/homebrew-core pull request #10223
Opened 2017-02-22 09:08 UTC by glennblock

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-25 21:27 UTC, fxcoudert requested changes

2017-02-25 21:27 UTC, fxcoudert commented on Formula/scriptcs.rb
The formula has `depends_on "mono" => :recommended` but it cannot build at all without `mono` (it says `mozroots: command not found`). Please turn that into a hard dependency.

2017-02-25 21:37 UTC, glennblock commented on Formula/scriptcs.rb
OK, no problem.

2017-02-25 21:43 UTC, glennblock commented on Formula/scriptcs.rb
I have changed it to `:run` is that correct?

2017-02-25 21:54 UTC, fxcoudert commented on Formula/scriptcs.rb
Just `depends_on "mono"`. And can you please squash your commits into one? With commit message `scriptcs 0.17.1`, that would be perfect! Many thanks.

2017-02-25 21:55 UTC, glennblock commented on Formula/scriptcs.rb
Sure!

2017-02-25 22:03 UTC, glennblock commented on Formula/scriptcs.rb
Done!

2017-02-25 22:03 UTC, glennblock commented on Formula/scriptcs.rb
oops wait

2017-02-25 22:05 UTC, glennblock commented on Formula/scriptcs.rb
Ok, now it should be really done.

2017-02-25 22:08 UTC, fxcoudert approved these changes

2017-02-25 22:15 UTC, glennblock commented
👍
On Sat, Feb 25, 2017 at 2:08 PM FX Coudert <notifications@github.com> wrote:

> *@fxcoudert* approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-core/pull/10223#pullrequestreview-23868137>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAInRHFs36wGRXuiRZmLfozSzyQDEHYlks5rgKZhgaJpZM4MIYIY>
> .
>

2017-02-26 10:39 UTC, closed without merging

2017-02-26 10:39 UTC, fxcoudert commented
Thanks @glennblock for your contribution!