vnu 20170206
Homebrew/homebrew-core pull request #10257
Opened 2017-02-23 03:52 UTC by ymyzk

Created with `brew bump-formula-pr`.

2017-02-25 18:28 UTC, fxcoudert requested changes

2017-02-25 18:28 UTC, fxcoudert commented on Formula/vnu.rb
> +  sha256 "e859b26b9532b4d1a5cb5c3bc873c85dc7a64c05ef7cb3f98ef040690d95609b"
The webpage says it requires Java 8, so this should be in the formula

2017-02-26 20:19 UTC, fxcoudert commented on Formula/vnu.rb
> +  sha256 "e859b26b9532b4d1a5cb5c3bc873c85dc7a64c05ef7cb3f98ef040690d95609b"
Also: why do we number versions by date, when they have perfectly fine version numbers (17.2.1)?

2017-02-26 21:02 UTC, nijikon commented
@fxcoudert lets see what will happen, this might be cause there was some bogus version in the past.

2017-02-26 21:21 UTC, fxcoudert commented
@nijikon we can force the version to be explicitly `17.2.1` if we need, I was just wondering why using a date instead of the version number.

It might need a `version_scheme 1`?

2017-02-27 06:14 UTC, nijikon commented
/cc @ilovezfs

2017-02-27 06:22 UTC, ilovezfs commented
https://github.com/validator/validator/releases

The headline for the release version used to be the date. We can either continue that tradition, and make it "20170206" or switch to 17.2.1 and bump the version_scheme. The latter is probably better since it can be derived from the url automatically.

2017-02-27 22:54 UTC, fxcoudert commented
```== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vnu.rb ==
C:  8:  1: Trailing whitespace detected.

vnu:
  * stable version should not decrease (from 20170130 to 17.2.1)
```

2017-02-27 23:40 UTC, closed without merging

2017-02-27 23:40 UTC, fxcoudert commented
Thanks @ymyzk for your contribution!

2017-02-28 01:12 UTC, ymyzk commented
Thanks for fixing!