jsoncpp build update to cmake
Homebrew/homebrew-core pull request #103386
Opened 2022-06-10 18:18 UTC by adorostkar

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
JsonCpp previously was built with `meson` which does not include cmake config files in the build. With this PR the build system is switched to `cmake which is more useful in case the library should be used by an application for a build.

2022-06-12 15:17 UTC, carlocab requested changes
Building with CMake is [documented as deprecated](https://github.com/open-source-parsers/jsoncpp/wiki/Building#building-and-testing-with-cmake), so I don't think we want to switch the build system here.

Meson is also their primary build system of choice in their CI, so I think we'll want to stick to that.

2022-06-12 19:10 UTC, adorostkar commented
Not making with cmake makes the library less useful doesn't it? I can't use find_package(jsoncpp) in my other projects if it is not build with cmake to include the config files.

2022-06-12 19:14 UTC, SMillerDev commented
You should probably file that issue upstream then. If upstream doesn't want to support CMake I don't think we should use it.

2022-06-13 03:10 UTC, carlocab commented
> Not making with cmake makes the library less useful doesn't it?

The library may become less useful for users who use CMake. On the other hand, `jsoncpp` becomes less useful for all users if it becomes broken or unmaintainable because we're using an unsupported build system.

2022-06-13 03:25 UTC, Bo98 commented
It is possible for upstream to add this to the Meson system: https://mesonbuild.com/CMake-module.html#cmake-configuration-files

2022-07-24 05:32 UTC, carlocab commented
Passing on this. Sorry!

2022-07-24 05:32 UTC, closed without merging