Add Python 3 support to protobuf
Homebrew/homebrew-core pull request #10347
Opened 2017-02-25 21:57 UTC by Noctem

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Optionally build the protobuf package for Python 3, also update setuptools and appdirs.

2017-02-26 09:47 UTC, MikeMcQuaid requested changes

2017-02-26 09:47 UTC, MikeMcQuaid commented on Formula/protobuf.rb
> +    pyinstall("python3") if build.with? "python3"
Use `Language::Python.each_python(build) do |python, python_version|` or `python_versions.each` over some array instead of creating a new function.

2017-03-05 18:38 UTC, fxcoudert commented
This might need a `revision` bump due to the updated resources.

2017-03-28 22:53 UTC, bfontaine commented
Ping on the comments above?

2017-03-30 03:19 UTC, Noctem commented
So is a revision bump actually needed? I can add it if it is.

2017-03-30 08:48 UTC, fxcoudert commented
Yes, please add the revision bump and squash the commits.

2017-04-01 18:31 UTC, closed without merging

2017-04-01 18:31 UTC, dunn commented
Thanks! Merged as 5cb2a3ff831eceeb694930180468f66035302125.

2017-04-04 07:28 UTC, Noctem commented
FYI: the *.pth* file seems to trigger this bug when `import`ing pip: pypa/pip#4216

Changing it to just the path (instead of importing and using `site`) seems to fix it, but I don't know off the top of my head if that has other effects. Apparently an upcoming pip release will fix the bug, so I guess intervention probably isn't necessary here.