Snapcast 0.0.10 (new formula)
Homebrew/homebrew-core pull request #10421
Opened 2017-02-27 22:22 UTC by vibbix

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Add's the "snapclient" and "snapserver" aliases too.

2017-03-01 09:15 UTC, fxcoudert requested changes

2017-03-01 09:15 UTC, fxcoudert commented on Aliases/snapclient
> +../Formula/snapcast.rb
The project is called Snapcast, there is no ambiguity. I don't think we want aliases for `snapclient` and `snapserver`.

2017-03-01 09:15 UTC, fxcoudert commented on Formula/snapcast.rb
> +class Snapcast < Formula
The commit message should have `snapcast` in lowercase

2017-03-01 09:15 UTC, fxcoudert commented on Formula/snapcast.rb
> +  version "0.0.10"
The version number is wrong. Please let Homebrew autodetect the version anyway.

2017-03-01 09:15 UTC, fxcoudert commented on Formula/snapcast.rb
> +  revision 1
A new formula should not have a `revision`.

2017-03-01 09:15 UTC, fxcoudert commented on Formula/snapcast.rb
> +      system "git", "clone", "--depth", "1", "git://git.xiph.org/tremor.git", "externals/tremor"
Do not download libraries and other resources. Please use other homebrew formulas as dependencies when they exist, or use `resource` blocks for released versions of the dependencies.

2017-03-01 09:15 UTC, fxcoudert commented on Formula/snapcast.rb
> +      system "git", "submodule", "update", "--depth", "1", "--init", "--recursive"
Do not run `git` in the `install` block.

2017-03-01 09:15 UTC, fxcoudert commented on Formula/snapcast.rb
> +    mkdir_p bin
Does the snapcast makefile not have an `install` target that we could use?

2017-03-01 09:15 UTC, fxcoudert commented on Formula/snapcast.rb
> +    If you get a message that says "illegal hardware instruction  snapclient",
Has this bug been reported upstream? If so, link to it in a comment, so we know to remove it in a future update.

2017-03-01 14:31 UTC, vibbix commented on Formula/snapcast.rb
> +    mkdir_p bin
It does, but it attempts to install a .plist and will fail without root privileges.

2017-03-10 23:06 UTC, bfontaine requested changes

2017-03-10 23:06 UTC, bfontaine commented on Formula/snapcast.rb
> +    mkdir_p bin
You don’t need to `mkdir_p bin`; `bin.install` takes care of that.

2017-03-10 23:06 UTC, bfontaine commented on Formula/snapcast.rb
> +    cp_r "client/snapclient.1", man
Please use `man1.install "client/snapclient.1"` instead of `cp_r` or `cp`. Install `*.1` stuff under `man1`; not `man`.

2017-03-10 23:06 UTC, bfontaine commented on Formula/snapcast.rb
> +    cp_r "server/debian/snapserver.plist", prefix
Please use `prefix.install …` instead of `cp_r …, prefix`.

2017-03-10 23:06 UTC, bfontaine commented on Formula/snapcast.rb
> +    man1.install Dir["#{man}/*.1"]
You don’t need this line if you install everything in `man1` in the first place.

2017-03-10 23:06 UTC, bfontaine commented on Formula/snapcast.rb
> +    ]
Please inline the arguments instead of creating an array; it’s not necessary here.

2017-03-28 22:55 UTC, bfontaine commented
Ping?

2017-03-30 03:00 UTC, vibbix commented
I've been a bit busy with school, so I haven't found the time to get it working quite yet. On top of that, I have to readapt the script for the latest release. I have a working build on my computer that I haven't pushed out yet while I make sure it conforms w/ all the projects code standards.

2017-03-30 08:00 UTC, bfontaine commented
@vibbix No worries; everyone have a life outside of Homebrew :smile: I just wanted to make sure we don’t keep a PR open forever if nobody’s working on it.

2017-04-29 08:55 UTC, languitar commented
I'd also be happy if snapcast got into brew. Any way I can help here?

2017-04-29 09:04 UTC, fxcoudert commented
You can help addressing the review comments, by pushing a commit or opening a new pull request.

2017-04-29 14:06 UTC, languitar commented
Ok, seems without submodules there is currently no proper way to bundle this as https://github.com/badaix/jsonrpcpp (an upstream dependency) is not release yes. I have created an issue for this: https://github.com/badaix/jsonrpcpp/issues/2

2017-05-02 11:43 UTC, closed without merging