llvm: Symlink OpenMP header/libs to separate directory
Homebrew/homebrew-core pull request #10456
Opened 2017-03-01 00:22 UTC by aw1621107

This allows other formulae to use omp.h and libomp.dylib without pulling
in other libraries installed with LLVM that conflict with system ones
(e.g. libc++.dylib)

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

For [PR #2234 at Homebrew/brew](https://github.com/Homebrew/brew/pull/2234).

2017-03-01 03:53 UTC, DomT4 commented on Formula/llvm.rb
> +      (lib/"libomp").install_symlink lib/"#{libomp_dylib}"
The use of `install_symlink` here should make the `mkdir` above redundant.

2017-03-01 08:44 UTC, MikeMcQuaid commented on Formula/llvm.rb
> +    ["libgomp.dylib", "libiomp5.dylib", "libomp.dylib"].each { |libomp_dylib|
Check `brew style`: https://bot.brew.sh/job/Homebrew%20Core/17250/version=sierra/testReport/junit/brew-test-bot/sierra/style_llvm/

I'd also use just `|dylib|` here.

2017-03-01 08:44 UTC, MikeMcQuaid commented on Formula/llvm.rb
> +    # Install symlinks for omp.h/libomp so they can be used in other formulae
`# Install symlinks for OpenMP header and libraries so they can be used by superenv`

2017-03-01 14:43 UTC, ilovezfs commented
I'm not sure I understand why this isn't an upstream bug if we think this is necessary.

2017-03-01 20:39 UTC, aw1621107 commented on Formula/llvm.rb
> +    ["libgomp.dylib", "libiomp5.dylib", "libomp.dylib"].each { |libomp_dylib|
Should `lib/"#{dylib}"` be replaced with `lib/dylib.to_s`, or does `dylib.to_s` need parentheses?

2017-03-01 20:43 UTC, aw1621107 commented
@ilovezfs Sorry, I'm not quite sure what you're getting at. Could you elaborate?

2017-03-01 20:47 UTC, MikeMcQuaid commented on Formula/llvm.rb
> +    ["libgomp.dylib", "libiomp5.dylib", "libomp.dylib"].each { |libomp_dylib|
`lib/dylib` works without the `.to_s` as these are strings as-is.

2017-03-01 20:47 UTC, MikeMcQuaid commented
@ilovezfs I think so long as we build and install libc++ but want to keep using our own one: it's not their bug.

2017-03-01 21:57 UTC, aw1621107 commented on Formula/llvm.rb
> +    ["libgomp.dylib", "libiomp5.dylib", "libomp.dylib"].each { |libomp_dylib|
Oh, ok. Fixed!

2017-03-02 16:01 UTC, ilovezfs commented
Sorry but doing this looks like a mistake to me.

2017-03-02 16:04 UTC, ilovezfs requested changes
I don't think we should be making changes to the llvm formula to support superenv. This should be handled in superenv itself if it's necessary.

2017-03-02 18:56 UTC, MikeMcQuaid commented
> I don't think we should be making changes to the llvm formula to support superenv. This should be handled in superenv itself if it's necessary.

@ilovezfs How? You can't add a library or include directory path without opening up everything else in that directory (which we don't want to do as we don't want to use the libc++ there).

2017-03-03 00:45 UTC, ilovezfs commented
If you have "-L#{MacOS.sdk_path}/usr/lib -L/usr/local/opt/llvm/lib" it should prefer the brew libc++.

2017-03-05 10:27 UTC, MikeMcQuaid commented
> If you have "-L#{MacOS.sdk_path}/usr/lib -L/usr/local/opt/llvm/lib" it should prefer the Xcode libc++.

:+1: to that approach. @aw1621107 it may be worth checking the ordering in superenv and seeing if that behaviour is as expected.

2017-03-05 17:11 UTC, aw1621107 commented
Is that behavior one we can count on to not change in the future?

2017-03-06 08:53 UTC, MikeMcQuaid commented
Yes.

2017-03-06 19:57 UTC, aw1621107 commented
Alright, I'll see what I can do.

2017-10-22 18:50 UTC, JCount commented
Pruning this due to the lack of a response and activity in general. Please comment if you would like to reopen and address the needed changes.

2017-10-22 18:50 UTC, closed without merging