vlang 0.3
Homebrew/homebrew-core pull request #104791
Opened 2022-06-30 11:49 UTC by Porkepix

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

2022-06-30 13:16 UTC, carlocab commented on Formula/vlang.rb
>    # NOTE: Keep this in sync with V compiler below when updating
The `resource` probably needs updating.

2022-06-30 15:52 UTC, gromgit requested changes

2022-06-30 17:17 UTC, gromgit commented on Formula/vlang.rb
>    end
Ah, it's pulling HEAD. Never mind then.

2022-06-30 17:29 UTC, carlocab commented on Formula/vlang.rb
>    end
We could pretty easily mimic what the `Makefile` does while keeping the resource, though.

2022-07-01 03:11 UTC, gromgit commented on Formula/vlang.rb
>    end
In that case...
```
	$(CC) $(CFLAGS) -std=gnu11 -w -o v1 vc/v.c -lm -lexecinfo -lpthread $(LDFLAGS)
```
@Porkepix , try adding `-lexecinfo` and `-lpthread` to the resource build.

The rest looks like a rebuild of `v` (which `v self` also does), and an "is `tcc` present?" advisory script (which is pointless for CI).

2022-07-01 07:28 UTC, carlocab commented on Formula/vlang.rb
>    end
Actually, it looks like `v` is being built with itself twice. is that what `v self` does?

2022-07-01 09:03 UTC, gromgit commented on Formula/vlang.rb
>    end
Based on https://github.com/vlang/v/blob/d679146a8003be6dc21f5b677753fd1e7403faa3/cmd/tools/vself.v, it seems `v self` only rebuilds itself once. I'm guessing that the Makefile double-build is just meant to test their `-no-parallel` flag, not sure if it's worth bothering about.

2022-07-01 09:24 UTC, carlocab commented on Formula/vlang.rb
>    end
This is actually a known pattern for optimising compiler builds, so I suspect that's what they're doing here.

See https://llvm.org/docs/AdvancedBuilds.html for an example.

2022-07-01 12:24 UTC, carlocab commented on Formula/vlang.rb
> +      bootstrap_libs.insert(1, "-lexecinfo") unless OS.mac?
```suggestion
```

2022-07-04 02:51 UTC, carlocab commented on Formula/vlang.rb
>    end
Actually, I just realised that we should be looking at the [`GNUMakefile`](https://github.com/vlang/v/blob/master/GNUmakefile), and not the `Makefile`. It, however, seems to do [a similar thing](https://github.com/vlang/v/blob/584c03512027c2c526e3825e3b83f04063960707/GNUmakefile#L120-L122):

```make
fresh_vc:
	rm -rf $(VC)
	$(GITFASTCLONE) $(VCREPO) $(VC)
```

2022-07-04 03:39 UTC, carlocab commented on Formula/vlang.rb
> +    (buildpath/"thirdparty/tcc/tcc.exe").write_exec_script ENV.cc
Looks like this doesn't work. Should we just add the `tccbin` resource here? I feel like there should be a way not to have to...

2022-07-25 10:59 UTC, harens commented
Hi 👋 I've been maintaining weekly builds of V over at MacPorts for a while now. A lot of commits have gone into getting it to build successfully and reproducibly, so I thought you might find our annotated [build script](https://github.com/macports/macports-ports/blob/master/lang/vlang/Portfile) and macOS 11 arm [log file](https://build.macports.org/builders/ports-11_arm64-builder/builds/61481/steps/install-port/logs/stdio) useful.

> Vlang needs libgc.a from TCC by default.

The issue is that V hard codes a lot of prefixes by default. I understand that Homebrew is much more strict on patches than MacPorts, but you mind find my set of [patches](https://github.com/macports/macports-ports/tree/master/lang/vlang/files) useful. I hope it helps.

2022-07-25 11:32 UTC, carlocab commented
Thanks for dropping by, @harens. That does help a lot.

2022-10-26 09:32 UTC, eelcocramer reviewed
Never mind. It seems that my build script after installation is not able to build v code.

2022-11-17 15:47 UTC, chenrui333 commented
vlang 0.3.2 is avail, I am gonna give that a shot in my local today.

2022-11-22 04:32 UTC, closed without merging

2022-12-27 02:27 UTC, chenrui333 commented
#119181