Shellshare
Homebrew/homebrew-core pull request #10518
Opened 2017-03-02 12:35 UTC by arthar360

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-02 13:35 UTC, fxcoudert commented on Formula/shellshare.rb
> +  desc "LIVE TERMINAL BROADCAST"
Don't write in all uppercase please

2017-03-02 13:37 UTC, fxcoudert submitted a review, later dismissed

2017-03-02 13:37 UTC, fxcoudert commented on Formula/shellshare.rb
> +  homepage "http://shellshare.net"
Audit says `  * The URL http://shellshare.net could use HTTPS rather than HTTP`

2017-03-02 13:37 UTC, fxcoudert commented on Formula/shellshare.rb
> +  test do
Please provide some testing of the functionality.

2017-03-02 13:37 UTC, fxcoudert commented on Formula/shellshare.rb
> +  def install
Please list requirements, such as Python (`depends_on :python if MacOS.version <= :snow_leopard`).

2017-03-02 14:02 UTC, arthar360 reviewed
Removed upper cases, Added dependencies and tests.

2017-03-02 18:55 UTC, MikeMcQuaid requested changes

2017-03-02 18:55 UTC, MikeMcQuaid commented on Formula/shellshare.rb
> +  sha256 "72bd49928982611ae44aac4a308dc6054d9c8ebad87644bd5eb68ff0bb704ce3"
Add a space between this line and the next.

2017-03-02 18:55 UTC, MikeMcQuaid commented on Formula/shellshare.rb
> +  depends_on :python
Add a space between this line and the next.

2017-03-02 18:55 UTC, MikeMcQuaid commented on Formula/shellshare.rb
> +  end
Add a space between this line and the next.

2017-03-02 19:30 UTC, arthar360 commented
Done. Please have a look.

2017-03-03 05:07 UTC, arthar360 reviewed
Added spaces between lines

2017-03-03 13:25 UTC, MikeMcQuaid requested changes

2017-03-03 13:25 UTC, MikeMcQuaid commented on Formula/shellshare.rb
> +  depends_on :python
Use `depends_on :python if MacOS.version <= :snow_leopard` to just depend on Python 2.7.

2017-03-03 13:25 UTC, MikeMcQuaid commented on Formula/shellshare.rb
> +  depends_on :python
Add `bottle :unneeded` above this with a line space before and after.

2017-03-03 13:46 UTC, vitorbaptista commented on Formula/shellshare.rb
> +  sha256 "72bd49928982611ae44aac4a308dc6054d9c8ebad87644bd5eb68ff0bb704ce3"
I just released version 1.0.1, so please use that instead: https://github.com/vitorbaptista/shellshare/releases/tag/v1.0.1

2017-03-03 17:37 UTC, arthar360 reviewed
Added bottle :unneeded and MacOS.version <= :snow_leopard for Python 2.7. @vitorbaptista : Updated to v1.0.1

2017-03-04 08:51 UTC, MikeMcQuaid approved these changes

2017-03-04 08:51 UTC, merged

2017-03-04 08:51 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-03-04 11:04 UTC, arthar360 commented
Thank you @MikeMcQuaid :)

2017-03-04 11:17 UTC, pwalsh commented
Very happy to see shellshare added!