riemann-client: deprecate
Homebrew/homebrew-core pull request #105468
Opened 2022-07-09 17:05 UTC by chenrui333

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

deprecate the formula as repo got removed.

2022-07-10 08:50 UTC, iMichka requested changes
`collectd` still depends on `riemann-client`. We need to find a solution for it first before deprecating.

2022-07-11 14:16 UTC, chenrui333 commented
> `collectd` still depends on `riemann-client`. We need to find a solution for it first before deprecating.

I think we should deprecate `collectd` as well.

2022-07-21 01:11 UTC, cho-m commented
Ref: https://github.com/algernon/

> Repositories are being migrated to my own [Gitea instance](https://git.madhouse-project.org/algernon), you'll find them there. Below is a non-exhaustive list of my things that used to be hosted on GitHub, but no longer are:
> 
> - [riemann-c-client](https://git.madhouse-project.org/algernon/riemann-c-client)

2022-07-21 16:37 UTC, cho-m commented on Formula/riemann-client.rb
>    homepage "https://github.com/algernon/riemann-c-client"
```suggestion
  homepage "https://git.madhouse-project.org/algernon/riemann-c-client"
```

2022-07-21 16:38 UTC, cho-m commented on Formula/riemann-client.rb
> +  head "https://git.madhouse-project.org/algernon/riemann-c-client.git", branch: "master"
```suggestion
  head "https://git.madhouse-project.org/algernon/riemann-c-client.git", branch: "main"
```

2022-08-10 10:19 UTC, SMillerDev approved these changes

2022-08-11 21:01 UTC, iMichka approved these changes

2022-08-11 21:05 UTC, closed without merging