git 2.37.1
Homebrew/homebrew-core pull request #105656
Opened 2022-07-12 18:41 UTC by owine

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

2022-07-12 19:57 UTC, SMillerDev submitted a review, later dismissed

2022-07-12 20:12 UTC, SMillerDev approved these changes, later dismissed

2022-07-13 05:22 UTC, carlocab requested changes
The `git` documentation `resource`s can be updated.

2022-07-13 08:41 UTC, carlocab approved these changes

2022-07-13 13:18 UTC, closed without merging