postgresql@95: import from homebrew/versions.
Homebrew/homebrew-core pull request #10620
Opened 2017-03-05 21:47 UTC by alanorth

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Import PostgreSQL 9.5.5 from homebrew/versions. After that we can bump version to 9.5.6 and close the [corresponding version bump in homebrew/versions](https://github.com/Homebrew/homebrew-versions/pull/1533).

2017-03-06 09:00 UTC, MikeMcQuaid commented
Could you also import `postgresql94.rb` too? Thanks!

2017-03-06 09:40 UTC, SrihariThalla commented on Formula/postgresql@95.rb
> +  url "https://ftp.postgresql.org/pub/source/v9.5.5/postgresql-9.5.5.tar.bz2"
Can you update to `9.5.6`? Thanks!

2017-03-06 12:54 UTC, alanorth commented on Formula/postgresql@95.rb
> +  url "https://ftp.postgresql.org/pub/source/v9.5.5/postgresql-9.5.5.tar.bz2"
I was [planning on updating to 9.5.6](https://github.com/Homebrew/homebrew-versions/pull/1533) when I saw that homebrew-versions is deprecated. I was going move postgresql95 here first, then update after. What do you think, @MikeMcQuaid?

2017-03-06 13:09 UTC, alanorth commented
@MikeMcQuaid I imported `postgresql94.rb` as `postgresql@94.rb` as you requested.

2017-03-06 15:01 UTC, MikeMcQuaid commented on Formula/postgresql@95.rb
> +  url "https://ftp.postgresql.org/pub/source/v9.5.5/postgresql-9.5.5.tar.bz2"
Ideally it's worth just doing both in a single PR, I think, but feel free to 👎 that.

2017-03-06 15:31 UTC, alanorth commented on Formula/postgresql@95.rb
> +  url "https://ftp.postgresql.org/pub/source/v9.5.5/postgresql-9.5.5.tar.bz2"
I've just bumped the version of `postgresql@95` to 9.5.6 and added it to this pull request.

2017-03-06 17:54 UTC, MikeMcQuaid commented
Some CI failures: https://bot.brew.sh/job/Homebrew%20Core/17569/version=sierra/testReport/

2017-03-08 09:28 UTC, alanorth reviewed
@JCount the post-installation help now gives this cryptic message:

```
To have launchd start postgresql@95 now and restart at login:
  brew services start postgresql@95
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /opt/brew/var/Formulary::FormulaNamespaceed575915b5ab63d58c0ac7d92c6c6b95::PostgresqlAT95 start
```

2017-03-08 09:32 UTC, MikeMcQuaid requested changes

2017-03-08 09:32 UTC, MikeMcQuaid commented on Formula/postgresql@95.rb
> +  plist_options :manual => "pg_ctl -D #{HOMEBREW_PREFIX}/var/#{name} start"
Don't use `name` here; just hardcode it.

2017-03-08 09:32 UTC, MikeMcQuaid commented on Formula/postgresql@94.rb
> +  patch :DATA
I think `ENV.append_to_cflags "-D_XOPEN_SOURCE"` should work instead.

2017-03-08 09:32 UTC, MikeMcQuaid commented on Formula/postgresql@94.rb
> +  patch :DATA
(also, while you're making that change, the same thing on `postgres-xc` would be great if you've got a chance!)

2017-03-08 19:35 UTC, JCount commented
This version of `postgresql@95` that I pushed to the repository was basically me taking an ax and butchering the code until it would compile and "work" as a `keg_only :versioned_formula`. I myself have never actually used the software for anything, so any testing/feedback from people who actually do would be extremely helpful.

2017-03-08 19:47 UTC, JCount commented on Formula/postgresql@95.rb
> +  plist_options :manual => "pg_ctl -D #{HOMEBREW_PREFIX}/var/#{name} start"
Should I hardcode it within the plist itself as well?

2017-03-08 20:57 UTC, alanorth commented
@JCount and initially I was only porting it from homebrew/versions, I didn't know it would be such a complicated change! I have no idea what it needs now. 😄

2017-03-08 21:42 UTC, JCount commented
@alanorth I think it is getting close to being done with the addition of these latest commits I pushed. 😌

2017-03-10 03:14 UTC, JCount commented
@MikeMcQuaid Do you want to look this over? If you think it is good, we probably can get this merged.

2017-03-10 14:34 UTC, MikeMcQuaid approved these changes

2017-03-10 17:40 UTC, JCount commented
The forumla names need to be changed to `postgresql@9.4` and `postgresql@9.5`, and the formula contents updated to reflect this, before this PR can be merged.

2017-03-10 17:43 UTC, JCount requested changes
The forumla names need to be changed to postgresql@9.4 and postgresql@9.5, and the formula contents updated to reflect this, before this PR can be merged.

2017-03-11 02:55 UTC, JCount approved these changes

2017-03-11 06:50 UTC, closed without merging

2017-03-11 06:53 UTC, JCount commented
@alanorth Thanks a lot for you contribution to Homebrew, and especially your patience in getting this merged. 🎊