urh 1.5.8 (new formula)
Homebrew/homebrew-core pull request #10663
Opened 2017-03-07 02:33 UTC by davidhubbard

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This formula could support `librtlsdr` but there is no formula for it.

2017-03-07 08:32 UTC, fxcoudert commented
@BrewTestBot test this please

2017-03-08 20:47 UTC, davidhubbard commented
It looks like @BrewTestBot is not going to test this?

2017-03-12 22:01 UTC, fxcoudert requested changes

2017-03-12 22:01 UTC, fxcoudert commented on Formula/urh.rb
> +    url "https://files.pythonhosted.org/packages/d9/c8/8c7a2ab8ec108ba9ab9a4762c5a0d67c283d41b13b5ce46be81fdcae3656/psutil-5.0.1.tar.gz"
Latest `psutil` version is 5.2.0, could you update?

2017-03-13 17:39 UTC, davidhubbard commented on Formula/urh.rb
> +    url "https://files.pythonhosted.org/packages/d9/c8/8c7a2ab8ec108ba9ab9a4762c5a0d67c283d41b13b5ce46be81fdcae3656/psutil-5.0.1.tar.gz"
Done. Also updated urh to latest and added new dependency to pyzmq.

2017-03-14 00:18 UTC, fxcoudert approved these changes

2017-03-14 00:25 UTC, closed without merging