percona-server: enable pam plugin
Homebrew/homebrew-core pull request #10666
Opened 2017-03-07 06:03 UTC by solomonty

Fixes https://github.com/Homebrew/legacy-homebrew/issues/41789

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-07 06:03 UTC, solomonty commented
There is another open PR for this formula. What is the process?

2017-03-07 08:45 UTC, fxcoudert requested changes

2017-03-07 08:45 UTC, fxcoudert commented on Formula/percona-server.rb
> -    # PAM plugin is Linux-only at the moment
Can you, in the PR (not in the formula) give a link that confirms PAM works for macOS now? (release notes or something like that)

2017-03-07 08:45 UTC, fxcoudert commented on Formula/percona-server.rb
>      ]
Add a `revision 1` line at the end of the `homepage`/`url`/`sha256` block.

2017-03-15 04:09 UTC, solomonty commented on Formula/percona-server.rb
> -    # PAM plugin is Linux-only at the moment
The purpose of this PR is to add the `dialog.so` plugin so the `mysql` command line and other programs like `Sequel Pro` and `MySQLWorkbench` can use it.

```
MySQL said: Authentication plugin 'dialog' cannot be loaded: dlopen(/usr/local/lib/plugin/dialog.so, 2): image not found
```

The Percona PAM authentication plugins for MySQL are not built unless `WITH_PAM` is set.

2017-03-15 04:15 UTC, solomonty commented on Formula/percona-server.rb
>      ]
Done

2017-03-15 08:39 UTC, fxcoudert requested changes

2017-03-15 08:39 UTC, fxcoudert commented on Formula/percona-server.rb
> +      "#include <stdlib.h>\n#include <../strings/my_stpnmov.c>"
What is the bug you are fixing? Has it been reported upstream and are they integrating the patch there? Add a comment giving link and saying that the `inreplace` can be removed for next version.

2017-03-15 15:37 UTC, solomonty commented on Formula/percona-server.rb
> +      "#include <stdlib.h>\n#include <../strings/my_stpnmov.c>"
I reported the bug to Percona.

https://bugs.launchpad.net/percona-server/+bug/1671357

2017-03-15 20:05 UTC, solomonty commented
Is there a mechanism to force a rebuild in Jenkins? The sierra build failed trying to download boost.

```
Error: 1 problem in 1 formula
percona-server:
  * Stable resource "boost": The URL https://downloads.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.bz2 is not reachable
```

2017-03-15 23:52 UTC, fxcoudert requested changes

2017-03-15 23:52 UTC, fxcoudert commented on Formula/percona-server.rb
> +      "#include <stdlib.h>\n#include <../strings/my_stpnmov.c>"
Add a comment giving link and saying that the inreplace can be removed for next version.

2017-03-16 01:44 UTC, solomonty commented on Formula/percona-server.rb
> +      "#include <stdlib.h>\n#include <../strings/my_stpnmov.c>"
Added the comments.

2017-03-16 06:51 UTC, solomonty commented
Comments with links added

2017-03-16 20:56 UTC, fxcoudert commented
So far I don't see movement from upstream on that bug report. Machomebrew only carries patches that have been approved or applied upstream. We'll wait to see if they act.

2017-03-22 05:02 UTC, solomonty commented
I did not see that in the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) or in the [Formula Cookbook](http://docs.brew.sh/Formula-Cookbook.html). @DomT4 did request a PR to fix this in the referenced issue.

2017-03-27 02:20 UTC, solomonty commented
rebased

2017-05-17 17:50 UTC, closed without merging