rush-parellel 0.4.2 (new formula)
Homebrew/homebrew-core pull request #106770
Opened 2022-07-28 20:57 UTC by apcamargo

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-08-01 19:33 UTC, SMillerDev commented on Formula/rush-parallel.rb
> +    system "go", "build", "-o", "rush"
```suggestion
    system "go", "build", *std_go_args(output: bin/"rush")
```

2022-08-04 06:27 UTC, SMillerDev requested changes

2022-08-04 06:27 UTC, SMillerDev commented on Formula/rush-parallel.rb
> +    system "go", "mod", "tidy"
These should not be ran here, they should be fixed upstream.

2022-08-05 15:48 UTC, carlocab commented on Formula/rush-parallel.rb
> +    shell_output("seq 1 4 | #{bin}/rush -k 'echo 0{}'")
```suggestion
    assert_equal <<~EOS, pipe_output("#{bin}/rush -k 'echo 0{}'", (1..4).to_a.join("\n"))
      01
      02
      03
      04
    EOS
```

2022-08-08 09:00 UTC, SMillerDev approved these changes

2022-08-08 18:31 UTC, apcamargo commented
Thanks @SMillerDev! Do I need to do something to get this PR merged?

2022-08-13 19:52 UTC, closed without merging