update rancher-cli.rb to build Rancher CLI v0.5.0
Homebrew/homebrew-core pull request #10692
Opened 2017-03-07 17:46 UTC by cmosetick

update rancher-cli.rb to build Rancher CLI v0.5.0

2017-03-07 17:48 UTC, fxcoudert requested changes

2017-03-07 17:48 UTC, fxcoudert commented on Formula/rancher-cli.rb
> +    sha256 "c126fd29834e3f99de7262eb455d3c318cb8d1f602c13f702023d38a9059fbb1" => :yosemite
Please do not change the `bottle` block. This is taken care of when the PR is merged.

2017-03-08 09:38 UTC, nijikon commented
You are awesome, thanks for your contribution! :tada:

2017-03-08 09:39 UTC, nijikon commented
Had a problem with pulling this so created a new one #10766

2017-03-08 09:39 UTC, closed without merging