Update DCMTK to the newest snapshot
Homebrew/homebrew-core pull request #10803
Opened 2017-03-09 11:55 UTC by waldyrious

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The audit does not pass:
```
$ brew audit --strict dcmtk
dcmtk:
  * Stable: version 3.6.1_20170228 should not end with an underline and a number
```

But this is expected, since the snapshots are currently being used as stable version, which is indicated in the comment immediately above the diff.

2017-03-10 12:30 UTC, fxcoudert requested changes

2017-03-10 12:30 UTC, fxcoudert commented on Formula/dcmtk.rb
> +  version "3.6.1_20170228"
Per Homebrew policy, please use `3.6.1-20170228` in `version` line (with the hyphen, even if it does not match the URL above).

2017-03-10 12:36 UTC, waldyrious commented on Formula/dcmtk.rb
> +  version "3.6.1_20170228"
Oh, so that's how you make it pass the audit :) can I add a comment so others don't overlook this?

2017-03-10 12:42 UTC, fxcoudert commented on Formula/dcmtk.rb
> +  version "3.6.1_20170228"
It was already that way (see before your change), so I think it's self-explanatory.

2017-03-10 16:22 UTC, waldyrious commented on Formula/dcmtk.rb
> +  version "3.6.1_20170228"
That's my point exactly -- just like I missed the subtle difference, others could in the future as well. I'll just add to the existing comment above this block.

2017-03-12 14:26 UTC, dunn commented
Thanks! Merged as 486ab1458277f68dded9dcd691895fea828bf761.

2017-03-12 14:27 UTC, closed without merging