telegraf 1.23.4
Homebrew/homebrew-core pull request #108197
Opened 2022-08-16 18:53 UTC by chenrui333

Created by `brew bump`

---

Created with `brew bump-formula-pr`.

2022-08-16 20:27 UTC, iMichka requested changes
Let's wait until this is marked as a stable release.

2022-08-17 13:39 UTC, chenrui333 commented
yeah, not quite stable, let's give it some time.

2022-08-17 20:38 UTC, iMichka submitted a review, later dismissed
Looks like it's now a stable release.

2022-08-19 07:02 UTC, SMillerDev approved these changes

2022-08-19 07:06 UTC, closed without merging