initial ctop formula
Homebrew/homebrew-core pull request #10846
Opened 2017-03-10 10:48 UTC by avelino

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

https://github.com/bcicen/ctop/issues/5

2017-03-10 18:04 UTC, bfontaine commented
For the future pull-requests please [follow our guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) and use the commit format `ctop 0.4.1 (new formula)`. Thanks!

2017-03-10 18:06 UTC, bfontaine requested changes

2017-03-10 18:06 UTC, bfontaine commented on Formula/ctop.rb
> +  url "https://github.com/bcicen/ctop/releases/download/v0.4.1/ctop-0.4.1-darwin-amd64"
We need to build from source here.

2017-03-10 18:06 UTC, bfontaine commented on Formula/ctop.rb
> +    bin.install "ctop"
Don’t use `mv` + `bin.install`. See my comment on your other PR: https://github.com/Homebrew/homebrew-core/pull/10847#discussion_r105453276

2017-03-11 10:59 UTC, bfontaine commented on Formula/ctop.rb
> +    bin.install "ctop"
You can merge this line and the one above by using `system "go", "build", "-o", bin/"ctop"`.

2017-03-11 10:59 UTC, bfontaine approved these changes

2017-03-11 20:18 UTC, avelino commented
Awaiting project solve that problem to send update for homebrew: https://github.com/bcicen/ctop/issues/33

PR on ctop to fixed problem: https://github.com/bcicen/ctop/pull/34 (awaiting approval)

2017-03-12 10:01 UTC, fxcoudert commented
```
  * `bottle modifier` (line 8) should be put before `depends_on` (line 7)
  * C: 7: col 14: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
```

2017-03-13 08:43 UTC, bfontaine commented on Formula/ctop.rb
> +  url "https://github.com/bcicen/ctop/archive/v0.4.1-deps.tar.gz"
This `-deps` confuses the version parser; please add the version below this line using `version "0.4.1"`.

```
Error: 1 problem in 1 formula
ctop:
  * Stable: version (deps) is set to a string without a digit
```

2017-03-13 10:56 UTC, avelino commented
@bcicen pls

2017-03-13 11:33 UTC, bcicen commented
@avelino - as @bfontaine's comment suggests, all you need to do is insert `version "0.4.1"` below line 4 in the current formula

2017-03-13 14:13 UTC, avelino commented
@bcicen 
Formula:
```
class Ctop < Formula
  desc "Top-like interface for container metrics"
  homepage "https://bcicen.github.io/ctop/"
  version "0.4.1"
  url "https://github.com/bcicen/ctop/archive/v0.4.1-deps.tar.gz"
  sha256 "bc10b774dad0bc7ef0be41bcfb36c774fc28dafa789b2f43f1ecdb5b75390867"

  depends_on "go" => :build
  depends_on "glide" => :build

  def install
    ENV["GOPATH"] = buildpath
    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"
    dir = buildpath/"src/github.com/bcicen/ctop"
    dir.install Dir["*"]
    cd dir do
      system "glide", "install"
      system "go", "build", "-o", bin/"ctop"
    end
  end

  test do
    system "#{bin}/ctop", "-v"
  end
end
```

Error:
```
$ brew install --build-from-source Formula/ctop.rb
==> Downloading https://github.com/bcicen/ctop/archive/v0.4.1-deps.tar.gz
Already downloaded: /Users/avelino/Library/Caches/Homebrew/ctop-0.4.1.tar.gz
==> glide install
Last 15 lines from /Users/avelino/Library/Logs/Homebrew/ctop/01.glide:
2017-03-13 11:11:42 -0300

glide
install

[ERROR] Failed to find glide.yaml file in directory tree: Cannot resolve parent of /

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
initial ctop formula https://github.com/Homebrew/homebrew-core/pull/10846
```

2017-03-13 22:21 UTC, avelino commented
@bcicen Will generate new release?

2017-03-13 23:28 UTC, bcicen commented
@avelino you need to clear your local cache before testing the brew install again to fetch the correct version:
```bash
rm -rvf /Users/avelino/Library/Caches/Homebrew/ctop*
```

2017-03-14 00:53 UTC, bcicen commented
@avelino version needs to be on line 5, below url. Test error:
```* `url` (line 5) should be put before `version` (line 4)```

2017-03-15 08:35 UTC, fxcoudert commented
Thanks @avelino for your contribution to Homebrew!

2017-03-15 08:35 UTC, closed without merging