gdbm 1.13
Homebrew/homebrew-core pull request #10903
Opened 2017-03-11 17:33 UTC by chdiza

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?

-----

The new `configure` flag is a workaround for what I believe is a newly-introduced bug.  The new version of `gdbm` "enhances" the enclosed `gdbmtool` to use `readline` functionality.  The problem (I think) is that upstream's detection of readline on macOS is broken.  Without the new flag, building fails with:
```
libtool: link: clang -g -O2 -o .libs/gdbm_load gdbm_load.o  ./libgdbmapp.a
./.libs/libgdbm.dylib -ldbm
Undefined symbols for architecture x86_64:
  "_history_list", referenced from:
      _input_history_handler in input-rl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
make[3]: *** [gdbmtool] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
This happens outside of HB also.  (My hunch: their `configure` script thinks readline is present even if it isn't.)

I've reported this upstream, via email (since they appear to have no obviously functioning public bug tracker).

The version bump contains more than just the enhancement of `gdbmtool`, so I thought it was worth making a PR here.  If they fix the bug, we can remove the flag later.

2017-03-11 17:36 UTC, chdiza commented
BTW, the new flag doesn't eliminate any functionality that *was* present in the previous version (1.12), as far as I know.

We could alternatively introduce an optional (or non-optional) `depends_on "readline"` here, but I'd rather wait to see what upstream says and add that later if need be.

2017-03-12 09:59 UTC, fxcoudert requested changes

2017-03-12 09:59 UTC, fxcoudert commented on Formula/gdbm.rb
> +      --without-readline
Please add a comment there + link to issue reported upstream

2017-03-12 15:01 UTC, chdiza commented on Formula/gdbm.rb
> +      --without-readline
I'll add a comment, but there is no link for the issue because I reported it via email.

2017-03-12 22:07 UTC, closed without merging

2017-03-12 22:07 UTC, fxcoudert commented
Thanks @chdiza for your contribution!