unzip: add -I/-O charset switches for non-unicode
Homebrew/homebrew-core pull request #109131
Opened 2022-08-29 03:57 UTC by vit9696

This change switches to the latest patch set from Ubuntu, which allows
decoding archives with various kinds of 8-bit ASCII charsets.
Changes to CFLAGS, NO_WORKING_ISPRINT in particular, are needed
for proper output during extraction and also come from Ubuntu.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-08-29 08:50 UTC, carlocab requested changes

2022-08-29 08:50 UTC, carlocab commented on Formula/unzip.rb
> -  end
Please don't touch the `bottle` block.

2022-08-29 08:50 UTC, carlocab commented on Formula/unzip.rb
> +            "D_USE_BZ2=-DUSE_BZIP2", "L_BZ2=-lbz2", "macosx"]
Let's not change the layout of this array.

2022-08-29 11:08 UTC, vit9696 commented
@carlocab, done, thanks.

2022-08-29 12:59 UTC, carlocab commented on Formula/unzip.rb
> +      "macosx",
```suggestion
    loc_macros = %w[
      -DLARGE_FILE_SUPPORT
      -DUNICODE_SUPPORT
      -DUNICODE_WCHAR
      -DUTF8_MAYBE_NATIVE
      -DNO_WORKING_ISPRINT
    ]
    args = %w[
      CC=#{ENV.cc}
      LOC=#{loc_macros.join(" ")}
      D_USE_BZ2=-DUSE_BZIP2
      L_BZ2=-lbz2
      macosx
```
Can we also add a comment on what the macros we're enabling do? Why do we want to enable them?

2022-08-29 13:56 UTC, carlocab commented on Formula/unzip.rb
> +      "macosx",
> Can we also add a comment on what the macros we're enabling do? Why do we want to enable them?

This part of my last review is not yet resolved.

2022-08-29 14:02 UTC, vit9696 commented on Formula/unzip.rb
> +      "macosx",
Yeah, was squashing in the meanwhile. GitHub is unfortunately rather broken, and does not allow me to commit suggestions and make edits to files altogether. Should be good now.

2022-08-29 20:12 UTC, vit9696 commented
@carlocab, CI failure is caused by 6 hour timeout and is not related to the change introduced by this commit. The changes are ready on my side.

2022-08-30 03:01 UTC, carlocab approved these changes
Thanks!

2022-08-31 07:12 UTC, closed without merging