python@3.10: depend on libnsl on Linux
Homebrew/homebrew-core pull request #109106
Opened 2022-08-28 18:46 UTC by danielnachun

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-08-29 18:45 UTC, carlocab requested changes
This introduces a circular dependency in the Linux dep tree. See #109167.

2022-08-30 06:08 UTC, carlocab commented
Running CI when the self-hosted Linux runner is needed but not available usually isn't a good idea.

The self-hosted runner can fail to start ([example](https://github.com/Homebrew/homebrew-core/actions/runs/2943674665/attempts/1)), and then we'd need to re-run all the Intel runners in order to restart the self-hosted one.

2022-08-31 00:59 UTC, danielnachun commented
Fortunately the self-hosted runner had no issues.  There were only test 2 failures on Linux, and neither of them are related to this PR.  I think this is ready to go.

2022-08-31 07:52 UTC, SMillerDev approved these changes

2022-08-31 10:22 UTC, carlocab approved these changes

2022-08-31 16:44 UTC, closed without merging