Tfenv formula
Homebrew/homebrew-core pull request #10922
Opened 2017-03-11 19:21 UTC by pyro2927

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR adds a Formula for [tfenv](https://github.com/kamatama41/tfenv).  Checklist above has been completed.

2017-03-12 09:57 UTC, fxcoudert commented
The test does not pass as the exit code is 1. And could you make the test do something more useful than outputting help?

2017-03-12 17:52 UTC, pyro2927 commented
@fxcoudert, the other pieces of functionality involve hitting an API to return results. Is it safe to make the assumptions that tests will be run with an active internet connection?

2017-03-12 20:07 UTC, bfontaine commented
> Is it safe to make the assumptions that tests will be run with an active internet connection?

Yes.

2017-03-12 23:11 UTC, fxcoudert requested changes
Please squash together the commits related to the same file

2017-03-12 23:11 UTC, fxcoudert commented on Formula/tfenv.rb
> +  conflicts_with "terraform", :because => "tfenv symlinks terraform binaries"
Please modify `terraform.rb` to add the conflict there too?

2017-03-13 08:44 UTC, bfontaine commented on Formula/tfenv.rb
> +    shell_output("#{bin}/tfenv list-remote")
Please use  `system bin/"tfenv", "list-remote"` if capturing the output is not necessary.

2017-03-13 19:35 UTC, pyro2927 commented on Formula/tfenv.rb
> +  conflicts_with "terraform", :because => "tfenv symlinks terraform binaries"
Conflict added to `terraform.rb` as well.

2017-03-13 19:35 UTC, pyro2927 commented on Formula/tfenv.rb
> +    shell_output("#{bin}/tfenv list-remote")
Updated.

2017-03-13 19:38 UTC, pyro2927 commented
@fxcoudert and @bfontaine The requested changes have been made.

2017-03-14 00:27 UTC, fxcoudert approved these changes

2017-03-14 00:28 UTC, fxcoudert commented
Can you make the changes into two commits, one with commit message `tfenv 0.4.1 (new formula)` and the other one with `terraform: add conflict with tfenv`? Thanks

2017-03-14 03:19 UTC, pyro2927 commented
Commits updated.

2017-03-14 22:56 UTC, fxcoudert commented
Nearly there… please amend to fix the following audit errors:

```
tfenv:
  * File should end with a newline
  * C: 19: col 4: Final newline missing.
```

2017-03-15 00:25 UTC, pyro2927 commented
My mistake, looks like my text editor automatically stripped the newline endings, sorry about that.

2017-03-15 08:24 UTC, merged

2017-03-15 08:24 UTC, fxcoudert commented
Thanks @pyro2927 for your contribution to Homebrew!