y2j 1.1.1 (new formula)
Homebrew/homebrew-core pull request #10927
Opened 2017-03-11 23:16 UTC by trinitronx

- Added new formula: `y2j`
- Uses python virtualenv to provide runtime dependency on PyYAML
- Uses optional dependency on docker for running on a system with only docker.

Closes wildducktheories/y2j#4

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-12 20:05 UTC, bfontaine requested changes

2017-03-12 20:05 UTC, bfontaine commented on Formula/y2j.rb
> +    end
You can `venv.pip_install resources` instead.

2017-03-12 20:05 UTC, bfontaine commented on Formula/y2j.rb
> +                               "#!/usr/bin/env bash\nexport PYTHONPATH=#{venv_site_packages_path}:$PYTHONPATH"
You can do so in the formula: `ENV["PYTHONPATH"] = …`.

2017-03-12 20:05 UTC, bfontaine commented on Formula/y2j.rb
> +    end
Use `(buildpath/"install_y2j.sh").write install_script`.

2017-03-12 20:05 UTC, bfontaine commented on Formula/y2j.rb
> +    bin.install "y2j.sh", "y2j", "j2y", "yq"
Use `#{bin}` for the `install_script` so you can remove this line.

2017-03-28 21:49 UTC, ahmetb commented
@trinitronx thanks for contributing, please consider following up on the review comments.

2017-04-08 14:12 UTC, fxcoudert commented
Will be closing this one for now, as it seems inactive… please consider reopening once review comments are addressed.

2017-04-08 14:12 UTC, closed without merging

2017-04-12 18:47 UTC, trinitronx commented on Formula/y2j.rb
> +    bin.install "y2j.sh", "y2j", "j2y", "yq"
Not sure I understand what you mean on this one.  It looked like `#{bin}` just was an expansion of `#{prefix}/bin` which would be the formula's `bin` directory.

The problem here was that "`install_y2j.sh`" placed these as symlinks to the main `y2j.sh` script which lives in the upstream project's source repo as checked out by the `install_y2j.sh` script.  As such, the real bash script executable in this case is `y2j.sh` which is going to be located under something like: `/usr/local/Cellar/y2j/<version e.g.: 1.2.3>/y2j.sh`

It was my understanding that the usage of `bin.install` was meant for this use case.  That is: placing & setting the execute bit for executables such that they are [placed into the formula's `bin` dir][1] (e.g.: `/usr/local/Cellar/y2j/<version e.g.: 1.2.3>/bin/`).

[1]: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#bininstall-foo

2017-04-12 18:50 UTC, trinitronx commented on Formula/y2j.rb
> +                               "#!/usr/bin/env bash\nexport PYTHONPATH=#{venv_site_packages_path}:$PYTHONPATH"
wouldn't this only affect the runtime of the `brew install y2j` ruby script that is executed?  What do you mean by "in the formula"?  The need here was to ensure that the `y2j.sh` script environment uses the homebrew managed python virtualenv.  So my thought was:  just force a shebang line & `PYTHONPATH` variable set as a shim inside the `y2j.sh` script to set it for this tool.

2017-04-12 19:34 UTC, trinitronx commented
@fxcoudert: I can't seem to re-open this issue

2017-04-17 14:46 UTC, trinitronx commented
@bfontaine, @fxcoudert : I've made the changes requested and added this to a new Pull Request #12532 because I'm unable to re-open this.