crowdin 2.0.11 (new formula)
Homebrew/homebrew-core pull request #11036
Opened 2017-03-13 14:47 UTC by ihor-popyk

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-13 16:01 UTC, fxcoudert requested changes

2017-03-13 16:01 UTC, fxcoudert commented on FORMULA/crowdin.rb
> +
This needs a `depends_on :java` (or `depends_on :java => "1.8+"` if there is a minimum version requirement).

2017-03-13 16:01 UTC, fxcoudert commented on FORMULA/crowdin.rb
> +
Add a `bottle :unneeded` line

2017-03-13 16:01 UTC, fxcoudert commented on FORMULA/crowdin.rb
> +    system "alias", "crowdin=\"'java -jar #{bin}/crowdin-cli.jar'\" >> ~/.bash_profile"
Do not modify the user's config files (`.bashrc` and `.bash_profile`). You can write a wrapper script, like the `scm-manager.rb` does for `scm-cli-client`.

2017-03-13 16:01 UTC, fxcoudert commented on FORMULA/crowdin.rb
> +    system "java", "-jar", "#{bin}/crowdin-cli.jar"
What is that testing? What is the expected output and return code?

2017-03-13 16:01 UTC, fxcoudert commented on FORMULA/crowdin.rb
> +  desc "Crowdin-CLI is a command-line tool that allows to manage your resources"
Reword the description to be `Command-line tool that allows to manage your resources`

2017-03-13 16:52 UTC, ihor-popyk commented on FORMULA/crowdin.rb
> +    system "java", "-jar", "#{bin}/crowdin-cli.jar"
It just runs help command and expects general help information

2017-03-13 16:53 UTC, fxcoudert commented on FORMULA/crowdin.rb
> +    system "java", "-jar", "#{bin}/crowdin-cli.jar"
Can we do a test that does something “useful”/representative of real use?

2017-03-13 17:07 UTC, ihor-popyk commented on FORMULA/crowdin.rb
> +  desc "Crowdin-CLI is a command-line tool that allows to manage your resources"
done

2017-03-13 17:08 UTC, ihor-popyk commented on FORMULA/crowdin.rb
> +
done

2017-03-13 17:08 UTC, ihor-popyk commented on FORMULA/crowdin.rb
> +
done

2017-03-13 17:08 UTC, ihor-popyk commented on FORMULA/crowdin.rb
> +    system "alias", "crowdin=\"'java -jar #{bin}/crowdin-cli.jar'\" >> ~/.bash_profile"
done

2017-03-13 17:10 UTC, ihor-popyk commented on FORMULA/crowdin.rb
> +    system "java", "-jar", "#{bin}/crowdin-cli.jar"
This is a simple test to ensure that the program is installed and working correctly. The next version will add more tests.

2017-03-14 00:16 UTC, fxcoudert approved these changes

2017-03-14 00:16 UTC, merged

2017-03-14 00:17 UTC, fxcoudert commented
Thanks @ihor-popyk for your contribution to Homebrew!