Added elasticsearch@5.0.2.
Homebrew/homebrew-core pull request #11048
Opened 2017-03-13 19:19 UTC by ygale

This is an exact copy of the formula for elasticsearch 5.2.2, currently the latest on homebrew, except modified to install a recent previous version of Elasticsearch. This version of elasticsearch is the one currently supported by [bloodhound](https://hackage.haskell.org/package/bloodhound), an elasticsearch bindings library for Haskell, so it would be nice to have this version in homebrew.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

Note that `brew test` requires elasticsearch to be running already on localhost. I assume that is the case for existing elasticsearch formulas as well.

Also note that elasticsearch will not run (and therefore `brew test` will fail) if there is existing data in `/usr/local/var/elasticsearch` created by a previous `brew install` of a different version of elasticsearch, since elasticsearch data files are version-specific. This probably ought to be managed automatically by `brew link`, but it is not. That also appears to be the case for the existing formulas.

-----

2017-03-14 00:28 UTC, neutric reviewed
@ygale: Thanks for your contribution to Homebrew! I commented in a few places, but it is probably wise to wait with changes until other maintainers chime in as I am not sure that this meets the criteria for [acceptable versioned formulae](https://github.com/Homebrew/brew/blob/master/docs/Versions.md#acceptable-versioned-formulae).

2017-03-14 00:28 UTC, neutric commented on formula_renames.json
> +  "elasticsearch502": "elasticsearch@5.0.2",
This is not necessary as you are not renaming a formula previously called 'elasticsearch502'.

2017-03-14 00:28 UTC, neutric commented on Formula/elasticsearch@5.0.2.rb
> +
The `head` block is not needed, one would use the main `elasticsearch` formula to build from head.

2017-03-14 00:28 UTC, neutric commented on Formula/elasticsearch@5.0.2.rb
> +
See above comments on `head`.

2017-03-14 09:27 UTC, fxcoudert commented
Why do we want to maintain a specific 5.0.2 versioned formula?

2017-03-14 09:50 UTC, ilovezfs commented
@fxcoudert https://github.com/Homebrew/brew/blob/master/docs/Versions.md

Specific patch versions are not acceptable, as specified in the docs.

Since the current version of elasticsearch is 5.2.2, that means this would need to be named `elasticsearch@5.0` (even though it would use the 5.0.2 tarball).

2017-03-14 09:59 UTC, fxcoudert commented
But the, is elastic search 5.0 _“used by a large number of people and still supported by their upstream projects”_? (which is the criterion for inclusion of versioned formulas)

2017-03-14 10:03 UTC, ilovezfs commented
@fxcoudert indeed. But: https://github.com/Homebrew/homebrew-core/pull/9814. So :man_shrugging:

2017-03-14 10:48 UTC, neutric commented
@ygale We'll wait and see what @MikeMcQuaid has to say. Should this get a thumbs down, consider hosting this formula in a [personal tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

2017-03-14 12:30 UTC, MikeMcQuaid requested changes

2017-03-14 12:30 UTC, MikeMcQuaid commented on Formula/elasticsearch@5.0.2.rb
> +class ElasticsearchAT502 < Formula
`ElasticsearchAT50` and the file named `elasticsearch@5.0`

2017-03-14 12:31 UTC, MikeMcQuaid commented
> This version of elasticsearch is the one currently supported by bloodhound, an elasticsearch bindings library for Haskell, so it would be nice to have this version in homebrew.

When you say "currently supported" does Bloodhound fail to work with the latest formula version?

2017-03-14 15:49 UTC, ilovezfs commented
@jasontedor what is upstream's policy regarding which prior version(s) of the software are or are not supported?

2017-03-21 00:07 UTC, jasontedor commented
> what is upstream's policy regarding which prior version(s) of the software are or are not supported?

We support this, but we do not maintain it (except for critical security patches). Does that make sense? Effectively what this means is that we encourage users to be on the latest maintained release (currently 5.2.2). There are some bad bugs in 5.0.2 (I know of at least two), I'd prefer that we keep it simple and only provide latest.

2017-03-21 01:32 UTC, ilovezfs commented
@jasontedor thanks for that. Just to make sure you have all the facts, there are currently elasticsearch 1.7.x, elasticsearch 2.3.x, and elasticsearch 2.4.x formulae in homebrew.

2017-03-21 01:53 UTC, jasontedor commented
We can remove 2.3.x. I'll open a PR for this.

2017-03-21 01:56 UTC, jasontedor commented
And 1.7, that is also EOL.

To be clear, we still maintain and support 2.4.x, and we support 2.3.x but do not maintain it (except for critical security patches).

2017-03-21 02:19 UTC, ilovezfs commented
@jasontedor thanks. So if I'm following, there are

maintained, supported, current: 5.2.x
maintained, supported, not current: 2.4.x
unmaintained, supported, not current: 2.3.x, 5.0.x
unsupported, unmaintained, and EOL: 1.7

2017-03-21 02:57 UTC, jasontedor commented
Correct, with one small addition: there is also 5.1.x which is unmaintained, supported, and not correct. Perhaps:

5.2.x: maintained, supported, current (until 5.3.0 is released)
all prior 5.x are unmaintained, supported, current
2.4.x: maintained, supported. not current
all prior 2.x are unmaintained, supported, not current
all prior 1.x and 0.x are EOL

2017-03-21 02:57 UTC, jasontedor commented
I opened #11361.

2017-03-23 10:50 UTC, fxcoudert commented
Thanks @jasontedor for commenting, closing this PR accordingly.

2017-03-23 10:50 UTC, closed without merging