Add the formula for biogeme
Homebrew/homebrew-core pull request #11079
Opened 2017-03-14 14:24 UTC by michelbierlaire

- [YES] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [YES] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [YES] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [YES] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-14 15:05 UTC, bfontaine requested changes

2017-03-14 15:05 UTC, bfontaine commented on Formula/biogeme.rb
> +    (testpath/"minimal.py").write("from biogeme import *\nrowIterator('obsIter')\nBIOGEME_OBJECT.SIMULATE = Enumerate({'Test':1},'obsIter')")
Please use `<<-EOS.undent` if the content is too long to fit on one line:

```rb
(testpath/"minimal.py").write <<-EOS.undent
  from biogeme import *
  rowIterator('obsIter')
  # ...
EOS
```

2017-03-14 15:05 UTC, bfontaine commented on Formula/biogeme.rb
> +    # executables being tested: `system "#{bin}/program", "do", "something"`.
Please remove these comments.

2017-03-14 15:05 UTC, bfontaine commented on Formula/biogeme.rb
> +  option "with-bison", "Install also Bison Biogeme"
Is there a reason not to install it?

2017-03-14 15:07 UTC, bfontaine commented
> [YES] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?

The guidelines include our preferred commit message format for new formulae:

> * `git commit` with message formatted `foo 2.3.4 (new formula)`

In this case it should be `biogeme 2.5 (new formula)`.

2017-03-14 16:40 UTC, michelbierlaire commented
I think that I have been able to change and commit the message. Is it OK now? Thanks.

2017-03-14 16:41 UTC, michelbierlaire commented on Formula/biogeme.rb
> +  option "with-bison", "Install also Bison Biogeme"
Yes. It is a version that will be abandoned in the near future.

2017-03-14 16:41 UTC, michelbierlaire commented on Formula/biogeme.rb
> +    # executables being tested: `system "#{bin}/program", "do", "something"`.
Done.

2017-03-14 17:06 UTC, michelbierlaire commented on Formula/biogeme.rb
> +    (testpath/"minimal.py").write("from biogeme import *\nrowIterator('obsIter')\nBIOGEME_OBJECT.SIMULATE = Enumerate({'Test':1},'obsIter')")
Done.

2017-03-14 23:03 UTC, bfontaine approved these changes

2017-03-14 23:06 UTC, bfontaine requested changes

2017-03-14 23:06 UTC, bfontaine commented on Formula/biogeme.rb
> +    EOS
Please indent each file content by two spaces:

```rb
# before
(testpath/"minimal.dat").write <<-EOS.undent
TEST
1
EOS

# after
(testpath/"minimal.dat").write <<-EOS.undent
  TEST
  1
EOS
```

2017-03-14 23:09 UTC, bfontaine commented on Formula/biogeme.rb
> +  option "with-bison", "Install also Bison Biogeme"
So… is there a reason to install it? :D 
We try to limit the number of options provided by a formula to its minimum. I’m just checking if this option is necessary.

2017-03-15 06:21 UTC, michelbierlaire commented on Formula/biogeme.rb
> +  option "with-bison", "Install also Bison Biogeme"
Good point. I have removed all options.

2017-03-15 06:22 UTC, michelbierlaire commented on Formula/biogeme.rb
> +    EOS
Done.

2017-03-15 08:40 UTC, bfontaine approved these changes

2017-03-15 08:41 UTC, bfontaine commented on Formula/biogeme.rb
> +    system "./configure", *args
Now that this array is always the same, you can inline the arguments:
```rb
system "./configure", "--prefix=#{prefix}",
                      "--enable-python",
                      "--enable-bison",
                      "--enable-gui"
```

2017-03-15 08:52 UTC, michelbierlaire commented on Formula/biogeme.rb
> +    system "./configure", *args
Done.

2017-03-15 08:58 UTC, michelbierlaire commented
Merci beaucoup ! Je comprends pourquoi homebrew fonctionne si bien. Le processus de review est très sérieux. Bravo.

2017-03-15 08:58 UTC, michelbierlaire commented
It is my first contribution to github. Do I need to take any other action, now that the added formula has been approved?

2017-03-15 09:10 UTC, fxcoudert commented
@michelbierlaire merci !

Ideally, you would now squash all your commits into a single one, with message `biogeme 2.5 (new formula)`. Then we can merge it.

2017-03-15 09:28 UTC, michelbierlaire commented
I am not sure to understand what you mean by "squash all your commits". When I try to commit again, it says "nothing to commit, working tree clean"

2017-03-15 09:30 UTC, fxcoudert commented
I meant rebase your branch's history so that instead of 6 commits, there is only 1. This makes less work for us to merge into a single commit. But I will take care of that now.

2017-03-15 09:31 UTC, closed without merging

2017-03-15 09:31 UTC, fxcoudert commented
Thanks @michelbierlaire for your contribution to Homebrew! We look forward to you contributing again.

2017-03-15 16:19 UTC, bfontaine commented
Thanks @fxcoudert for merging this :smiley: