s2n build both shared+static
Homebrew/homebrew-core pull request #111181
Opened 2022-09-20 05:23 UTC by armanbilge

Modeled on existing cmake-based formulas e.g. cpu_features and libomp.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-09-20 08:07 UTC, SMillerDev commented
Why would we want static libraries here?

2022-09-20 08:13 UTC, armanbilge commented
So that they can be used to create statically linked binaries.

Or at the very least, for the same argument that several other Formulas install both dynamic and static libraries.

2022-09-20 08:28 UTC, armanbilge commented
If it helps, here's 9 other cmake-based formula that do more or less exactly what I've done here. This is not even including countless other non-cmake based formula. Unless there is a reason that s2n should be treated differently?

<details>

https://github.com/Homebrew/homebrew-core/blob/80de8443530ffcf703fb3c0394ce3d6295acf0f9/Formula/avrdude.rb#L61-L67

https://github.com/Homebrew/homebrew-core/blob/80de8443530ffcf703fb3c0394ce3d6295acf0f9/Formula/cpu_features.rb#L19-L29

https://github.com/Homebrew/homebrew-core/blob/80de8443530ffcf703fb3c0394ce3d6295acf0f9/Formula/dcmtk.rb#L43-L52

https://github.com/Homebrew/homebrew-core/blob/80de8443530ffcf703fb3c0394ce3d6295acf0f9/Formula/folly.rb#L55-L66

https://github.com/Homebrew/homebrew-core/blob/80de8443530ffcf703fb3c0394ce3d6295acf0f9/Formula/libomp.rb#L35-L43

https://github.com/Homebrew/homebrew-core/blob/80de8443530ffcf703fb3c0394ce3d6295acf0f9/Formula/minizip-ng.rb#L34-L45

https://github.com/Homebrew/homebrew-core/blob/80de8443530ffcf703fb3c0394ce3d6295acf0f9/Formula/minuit2.rb#L25-L34

https://github.com/Homebrew/homebrew-core/blob/80de8443530ffcf703fb3c0394ce3d6295acf0f9/Formula/s2geometry.rb#L42-L50

https://github.com/Homebrew/homebrew-core/blob/80de8443530ffcf703fb3c0394ce3d6295acf0f9/Formula/tbb.rb#L41-L52

</details>

2022-09-20 08:41 UTC, SMillerDev commented
Prior art is never an argument for homebrew Formula since the standards are ever evolving and with 6,5K packages backporting all decisions is rarely feasible.

Now onto the actual issue, static libraries are the preferred standard for all package managers that I know of, since they avoid duplication and make it feasible to package software in smaller chunks. What would this particular static library improve for users?

2022-09-20 08:55 UTC, armanbilge commented
> Prior art is never an argument for homebrew Formula since the standards are ever evolving and with 6,5K packages backporting all decisions is rarely feasible.

Fair enough.

---

> Now onto the actual issue, static libraries are the preferred standard for all package managers that I know of, since they avoid duplication and make it feasible to package software in smaller chunks.

I assume you mean dynamic libraries are preferred.

> What would this particular static library improve for users?

It would make it possible for users to build self-contained binaries for applications using s2n. This makes deployment much more straightforward e.g. to containers in the cloud.

2022-09-20 09:01 UTC, SMillerDev commented
> I assume you mean dynamic libraries are preferred.

You're right, words are difficult sometimes.

> It would make it possible for users to build self-contained binaries for applications using s2n. This makes deployment much more straightforward e.g. to containers in the cloud.

That's not really a goal of homebrew as far as I am aware, but I'll leave this for other maintainers.

2022-09-20 09:07 UTC, armanbilge commented
> That's not really a goal of homebrew as far as I am aware, but I'll leave this for other maintainers.

Yes, I did a search and read-through some other recent PRs mentioning static libs and now I am less sure about this myself.

As an alternative: would you be open to accepting this under a user-enabled opt-in? I remember some formula having these, are they still a thing?

2022-09-20 09:13 UTC, SMillerDev commented
Nope, we got rid of user options in 2018 because they would regularly break.

2022-10-03 12:39 UTC, fxcoudert approved these changes, later dismissed

2022-10-03 12:40 UTC, fxcoudert commented
Let's accept this, it doubles the build time, but 1. the build is fast, 2. the install procedure is really simple.

2022-10-03 12:46 UTC, SMillerDev requested changes

2022-10-03 12:46 UTC, SMillerDev commented on Formula/s2n.rb
> +    system "cmake", "--install", "build/static"
Let's make the shared library the default then by having it overwrite the static parts:
```suggestion
    system "cmake", "-S", ".", "-B", "build/static", *std_cmake_args, "-DBUILD_SHARED_LIBS=OFF"
    system "cmake", "--build", "build/static"
    system "cmake", "--install", "build/static"

    system "cmake", "-S", ".", "-B", "build/shared", *std_cmake_args, "-DBUILD_SHARED_LIBS=ON"
    system "cmake", "--build", "build/shared"
    system "cmake", "--install", "build/shared"
```

2022-10-03 12:57 UTC, SMillerDev approved these changes

2022-10-03 15:06 UTC, closed without merging