mono 4.8.0.520
Homebrew/homebrew-core pull request #11119
Opened 2017-03-15 21:52 UTC by neutric

Created with `brew bump-formula-pr`.

2017-03-15 23:46 UTC, fxcoudert requested changes

2017-03-15 23:46 UTC, fxcoudert commented on Formula/mono.rb
> +  url "https://download.mono-project.com/sources/mono/mono-4.8.0.520.tar.bz2"
fsharp has a 4.1.0.2 version, please update the `resource "fsharp"` block

2017-03-16 18:31 UTC, neutric commented on Formula/mono.rb
> +  url "https://download.mono-project.com/sources/mono/mono-4.8.0.520.tar.bz2"
Done, thanks for checking!

2017-03-16 19:54 UTC, fxcoudert approved these changes

2017-03-16 22:42 UTC, fxcoudert commented
SHA256 issue:

```
==> Downloading https://github.com/phildawes/racer/archive/2.0.6.tar.gz
==> Downloading from https://codeload.github.com/phildawes/racer/tar.gz/2.0.6
Warning: Resource racer reports different SHA256: f6cc46e0f87e01448943e1406bdd7d548ed41dc149b1f3cf6ddb5cfcc8b24448
Downloaded to: /Users/brew/Library/Caches/Homebrew/rust--racer-2.0.6.tar.gz
SHA256: a9704478f72037e76d4d3702fe39b3c50597bde35dac1a11bf8034de87bbdc70
```

and please remove the `revision 1` line.

2017-03-16 22:44 UTC, closed without merging