Add zxing-cpp formula
Homebrew/homebrew-core pull request #11152
Opened 2017-03-16 14:44 UTC by mjbshaw

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Adds the ZXing C++ port to Homebrew. The C++ port was deprecated and removed from the main ZXing project after v2.3.0, and its development has moved to a new repo ([see details here](https://github.com/zxing/zxing#zxing-based-third-party-open-source-projects)).

2017-03-16 20:50 UTC, fxcoudert requested changes

2017-03-16 20:50 UTC, fxcoudert commented on Formula/zxing-cpp.rb
> +      if build.stable?
Isn't there a `make install` for stable?

2017-03-16 20:50 UTC, fxcoudert commented on Formula/zxing-cpp.rb
> +        lib.install "libzxing.a"
Can we build a shared library instead of static?

2017-03-16 20:50 UTC, fxcoudert commented on Formula/zxing-cpp.rb
> +    system bin/"zxing"
Please include a test that actually does something. Consider installing a test image for that.

2017-03-18 16:27 UTC, mjbshaw reviewed
I added a proper test.

2017-03-18 16:27 UTC, mjbshaw commented on Formula/zxing-cpp.rb
> +    system bin/"zxing"
Done.

2017-03-18 21:23 UTC, kriansa commented on Formula/zxing-cpp.rb
> +      if build.stable?
@mjbshaw I believe you made a typo on **install** (not _intall_)

2017-03-18 22:51 UTC, mjbshaw commented on Formula/zxing-cpp.rb
> +      if build.stable?
Oops, that command had a typo. But it really doesn't have `make install`:

```
$ make install
make: *** No rule to make target `install'.  Stop.
$ grep install Makefile
# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall
# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast
```

2017-03-20 01:26 UTC, dunn commented on Formula/zxing-cpp.rb
> +      if build.stable?
Could you ask the developers if they'll add one?

2017-03-20 04:23 UTC, mjbshaw commented on Formula/zxing-cpp.rb
> +      if build.stable?
I don't think that would work, given that [the C++ port was deleted in 2013](https://github.com/zxing/zxing/commit/4856e86a46a5836d7ea793a78bea5637c85fe7c6#diff-ac731f2fedd74089d1149d83620eeb92) from the main repo. [zxing-cpp](https://github.com/glassechidna/zxing-cpp) forked that code, and is the unofficial-official active C++ zxing repo (but with no releases, currently).

I know it's a sorry state of affairs, but it's one that is common to barcode/QR decoding libraries, and unfortunately what C++ developers have to work with for the time being.

2017-03-21 21:06 UTC, fxcoudert commented
Thanks @mjbshaw for your contribution to Homebrew!

2017-03-21 21:06 UTC, closed without merging