gcc: Add glibc.opt_lib to the library search path
Homebrew/homebrew-core pull request #111830
Opened 2022-09-27 22:18 UTC by sjackman

When brewed `glibc` is installed, add `glibc.opt_lib` to the library search path in `specs`.
It's not necessary to rebuild bottles, because this PR affects only `post_install`.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

2022-09-27 22:56 UTC, danielnachun commented
Do we also need the RPATH for the `glibc` opt lib to be added to the spec file as well?  Right now we are only adding the RPATH for HOMEBREW_PREFIX/lib which will no longer contain symlinks for brewed `glibc` itself, but I can't recall if using the right `glibc` at runtime is already taken care of by `--dynamic-linker`.

2022-09-27 23:41 UTC, sjackman commented
> Do we also need the `RPATH` for the glibc opt lib to be added to the spec file as well?

No, because `/home/linuxbrew/.linuxbrew/opt/glibc/lib` is in `~/.linuxbrew/etc/ld.so.conf`.

```console
$ cat ~/.linuxbrew/etc/ld.so.conf
# This file is generated by Homebrew. Do not modify.
/home/linuxbrew/.linuxbrew/opt/glibc/lib  # ensure Homebrew Glibc always comes first
include /home/linuxbrew/.linuxbrew/etc/ld.so.conf.d/*.conf
```

2022-09-28 00:15 UTC, carlocab commented
GCC will fail to build on Monterey due to Xcode 14.

2022-09-28 00:44 UTC, carlocab approved these changes

2022-09-28 04:00 UTC, carlocab requested changes
`brew postinstall gcc` is broken on `ubuntu-22.04`: https://github.com/carlocab/workflow-test/actions/runs/3140633147/jobs/5102234567#step:8:8

It does fix some things on `ubuntu-18.04` and `ubuntu-20.04` though.

2022-09-28 05:07 UTC, sjackman commented
> `brew postinstall gcc` is broken on `ubuntu-22.04`: https://github.com/carlocab/workflow-test/actions/runs/3140633147/jobs/5102234567#step:8:8

I'm not able to reproduce this failure in Docker. 

```console
$ docker run -it --rm homebrew/brew
$ cd ~/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
$ git fetch https://github.com/homebrew/homebrew-core pull/111830/head:pr111830
$ git switch 111830
$ brew install gcc
…
==> Postinstalling gcc
==> Creating the GCC specs file: /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bi
$ ~/.linuxbrew/Cellar/gcc/12.2.0/bin/gcc-12 -print-libgcc-file-name
/home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../lib/gcc/current/gcc/x86_64-pc-linux-gnu/12/libgcc.a
```

https://github.com/carlocab/workflow-test/actions/runs/3140633147/jobs/5102234567#step:8:8
Ah, I see. In this test, brewed `gcc` is not installed, and `brew postinstall gcc` does not check that `gcc` is installed, so `~/.linuxbrew/Cellar/gcc/12.2.0/bin/gcc-12 -print-libgcc-file-name`, because brewed `gcc` is not installed.

2022-09-28 05:08 UTC, carlocab commented
Good catch; my mistake.

2022-09-28 05:38 UTC, carlocab approved these changes
Ok, this looks good. There are still some [`brew test` failures](https://github.com/carlocab/workflow-test/actions/runs/3141044231) on 18.04 and 20.04 (`llvm`, `glib`), but I believe those were failing even without this change.

2022-09-28 05:40 UTC, danielnachun approved these changes

2022-09-28 05:47 UTC, carlocab commented
> Ok, this looks good. There are still some [`brew test` failures](https://github.com/carlocab/workflow-test/actions/runs/3141044231) on 18.04 and 20.04 (`llvm`, `glib`), but I believe those were failing even without this change.

Running `brew link --force glibc` fixes `brew test glib`. It does not fix `brew test llvm`. Neither does `brew link --force binutils`, even when done with `brew link --force glibc`. https://github.com/carlocab/workflow-test/actions/runs/3141094044/jobs/5103161082

2022-09-28 12:30 UTC, MikeMcQuaid approved these changes

2022-09-28 12:31 UTC, MikeMcQuaid commented
> There are still some [`brew test` failures](https://github.com/carlocab/workflow-test/actions/runs/3141044231) on 18.04 and 20.04 (`llvm`, `glib`), but I believe those were failing even without this change.

I think we should aim to have a 18.04 CI job for at least `gcc`/`glibc`/`llvm` sooner rather than later here.

2022-09-28 16:06 UTC, merged