aha: fix manpage install
Homebrew/homebrew-core pull request #11208
Opened 2017-03-17 15:46 UTC by eddieantonio

Aha's [Makefile] treats `MANDIR` as a relative path from `PREFIX` rather
than an absolute path as given by `man` in `Formula#install`. Changed to
using the expected [manpage prefix].

[Makefile]: https://github.com/theZiz/aha/blob/4df28c96900b73a7073635184673ea631297e27a/Makefile#L20-L21
[manpage prefix]: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#manuals

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-18 12:20 UTC, fxcoudert submitted a review, later dismissed
Please add a `revision 1` line after the `sha256`

2017-03-18 12:24 UTC, ilovezfs requested changes
I'd prefer we get this fixed upstream so that `MANDIR` works as expected.

2017-03-18 12:26 UTC, ilovezfs commented
```
diff --git a/Makefile b/Makefile
index 854433f..174fb09 100644
--- a/Makefile
+++ b/Makefile
@@ -2,7 +2,7 @@
 
 PREFIX?=/usr/local
 
-MANDIR?=man
+MANDIR?=$(PREFIX)/share/man
 BINMODE?=0755
 MANMODE?=644
 
@@ -17,5 +17,5 @@ clean:
 install: aha
 	install -d $(DESTDIR)$(PREFIX)/bin
 	install -m $(BINMODE) aha $(DESTDIR)$(PREFIX)/bin
-	install -d $(DESTDIR)$(PREFIX)/$(MANDIR)/man1
-	install -m $(MANMODE) aha.1 $(DESTDIR)$(PREFIX)/$(MANDIR)/man1
+	install -d $(DESTDIR)$(MANDIR)/man1
+	install -m $(MANMODE) aha.1 $(DESTDIR)$(MANDIR)/man1
```
Something like this is what I have in mind.

2017-03-18 17:02 UTC, eddieantonio commented
I believe changing upstream will create issues in _other_ package managers and operating systems. See theZiz/aha#15. Hence, I propose ignoring the `make install` target, and for revision 1 of this version, simply using `bin.install ...` and `man1.install ...` explicitly.

2017-03-18 17:23 UTC, ilovezfs commented
Any such issues would be bugs in those other package managers.

https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

Take a look at `mandir` and `datarootdir`.

2017-03-28 10:55 UTC, ilovezfs commented
@eddieantonio 0.4.10.6 is out now if you want to refresh this :)

2017-03-28 14:52 UTC, eddieantonio commented
@ilovezfs done!

2017-03-28 16:37 UTC, ilovezfs approved these changes

2017-03-28 16:41 UTC, closed without merging

2017-03-28 16:42 UTC, ilovezfs commented
@eddieantonio Thanks for the PR and the excellent work with upstream!