goenv 1.0.0
Homebrew/homebrew-core pull request #11222
Opened 2017-03-18 02:31 UTC by syndbg

Changes (last is most recent):

* syndbg/goenv@e11de94
* syndbg/goenv@ce93f67

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Folow-up of  11220

2017-03-18 02:32 UTC, syndbg commented
`audit` does not pass since I change to SemVer

2017-03-18 11:59 UTC, fxcoudert requested changes

2017-03-18 11:59 UTC, fxcoudert commented on Formula/goenv.rb
> +  sha256 "5eac938fc76951e6d3a618bc2ba0832524c5b583dcaeda73be74b9315bf18e0c"
Add a line with `version_scheme 1` after the `sha256` line

2017-03-18 16:24 UTC, syndbg commented on Formula/goenv.rb
> +  sha256 "5eac938fc76951e6d3a618bc2ba0832524c5b583dcaeda73be74b9315bf18e0c"
Added, but `audit` is still not happy.

2017-03-19 12:06 UTC, fxcoudert approved these changes

2017-03-19 12:06 UTC, fxcoudert commented on Formula/goenv.rb
> +  sha256 "5eac938fc76951e6d3a618bc2ba0832524c5b583dcaeda73be74b9315bf18e0c"
Actually an `audit` bug…

2017-03-19 12:06 UTC, merged

2017-03-19 12:06 UTC, fxcoudert commented
Thanks @syndbg for your contribution to Homebrew!

2017-03-19 12:17 UTC, syndbg commented
@fxcoudert My pleasure. Thanks for the help!