Add python, OpenCV and python2 support to libfreenect
Homebrew/homebrew-core pull request #11249
Opened 2017-03-18 18:46 UTC by xionglingfeng

Add options to compile libfreenect with OpenCV and Python

2017-03-19 04:29 UTC, tdsmith requested changes

2017-03-19 04:29 UTC, tdsmith commented on Formula/libfreenect.rb
> +  depends_on "opencv3" if build.with? "opencv3"
These should look like `depends_on "homebrew/science/opencv" => :optional`

2017-03-19 04:29 UTC, tdsmith commented on Formula/libfreenect.rb
> +  depends_on "python3" if build.with? "python3"
These should look like `depends_on :python3 => :optional`.

If this just builds extension modules, just always build the python 2 modules and don't declare a :python dependency.

2017-03-19 04:29 UTC, tdsmith commented on Formula/libfreenect.rb
> +  option "with-python3", "Build with Python 3 support"
Please remove all of the `option` calls (including `:universal`, unless there's a really compelling use case?); the `depends_on... => :optional` syntax does this for you.

2017-03-19 04:33 UTC, tdsmith commented
Thanks for the PR! Please let me know if you have any questions about the changes I requested.

2017-05-05 23:03 UTC, fxcoudert commented
Closing this PR for now, as it has not been updated in response to review comments. Please reopen when addressing the comments.

2017-05-05 23:03 UTC, closed without merging