ecasound: update homepage
Homebrew/homebrew-core pull request #112664
Opened 2022-10-08 20:46 UTC by chenrui333

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Currently, the livecheck failed, but also the homepage is not accessible. 
While searching online I found this new site (`https://nosignal.fi/ecasound/`), it looks like is the new site for the project, with mirrors matching with the artifact that we use. Thus, updating the homepage and livecheck to point to the new one.

2022-10-10 07:19 UTC, SMillerDev requested changes
Is there any confirmation or other packager using this?

2022-11-03 04:00 UTC, cho-m commented
Looks like it was listed as an official site based on archived copies of original site. Original site listed 3 mirrors with main release note/etc links pointing to EU mirror while stable download URL is hosted on US mirror.

In 2013, the EU mirror changed, e.g.
- https://web.archive.org/web/20130713041440/http://eca.cx:80/ecasound/
    > mirrors: [eca.cx](https://web.archive.org/web/20130713041440/http://eca.cx/ecasound/index.php) (eu) / [seul.org](https://web.archive.org/web/20130713041440/http://ecasound.seul.org/ecasound/index.php) (us) / [sourceforge.net](https://web.archive.org/web/20130713041440/http://ecasound.sourceforge.net/ecasound/index.php) (us)
- https://web.archive.org/web/20130818221221/http://www.eca.cx/ecasound/
    > mirrors: [nosignal.fi](https://web.archive.org/web/20130818221221/http://nosignal.fi/ecasound/index.php) (eu) / [seul.org](https://web.archive.org/web/20130818221221/http://ecasound.seul.org/ecasound/index.php) (us) / [sourceforge.net](https://web.archive.org/web/20130818221221/http://ecasound.sourceforge.net/ecasound/index.php) (us)

2022-11-03 13:12 UTC, SMillerDev commented
I don't think a mirror surviving is the same as being an official successor.

2022-11-07 02:31 UTC, cho-m commented
> I don't think a mirror surviving is the same as being an official successor.

The fact that all the URLs in release notes point to nosignal.fi sounds like an official successor.

Release notes for 2.9.1 from original site https://web.archive.org/web/20211130030720/http://www.eca.cx/ecasound/relnotes/ecasound_v2_9_1_relnotes.txt

```
Full list of changes is available at:
 - http://nosignal.fi/ecasound/history.php

...

6. Links and files
------------------
   
Web site (and mirrors):
        http://nosignal.fi/ecasound (fi)
        http://ecasound.seul.org (us)
        http://ecasound.sourceforge.net (us)

Source package:
        http://nosignal.fi/ecasound/download.php     
        ecasound-2.9.1.tar.gz, md5sum:
        13c7be1e4eddc0bbf3792dc17777e465

List of distributions with maintained Ecasound support:
        See http://nosignal.fi/ecasound/download.php
```

Compared to v2.9.0 release notes https://web.archive.org/web/20220122050109/http://www.eca.cx/ecasound/relnotes/ecasound_v2_9_0_relnotes.txt
```
Full list of changes is available at:
 - http://www.eca.cx/ecasound/history.php

...

6. Links and files
------------------
   
Web site (and mirrors):
        http://eca.cx/ecasound (fi)
        http://ecasound.seul.org (us)
        http://ecasound.sourceforge.net (us)

Source package:
        http://eca.cx/ecasound/download.php     
        ecasound-2.9.0.tar.gz, md5sum:
        05e7d4664cdf4c7a138c098e9506a551

List of distributions with maintained Ecasound support:
        See http://eca.cx/ecasound/download.php
```

2022-11-23 22:31 UTC, jonchang commented
Fixed by #112900

2022-11-23 22:31 UTC, closed without merging