ytarchive 0.3.1 (new formula)
Homebrew/homebrew-core pull request #112813
Opened 2022-10-10 22:34 UTC by DaniruKun

This adds a new Go-based formula for archiving live or upcoming YT livestreams.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-10-11 06:42 UTC, dawidd6 commented on Formula/ytarchive.rb
> +    system "go", "build", *std_go_args(ldflags: "-s -w"), "-o", bin/"ytarchive"
```suggestion
    system "go", "build", *std_go_args(ldflags: "-s -w")
```

This is already included in `std_go_args`.

2022-10-11 21:32 UTC, carlocab requested changes

2022-10-12 08:30 UTC, DaniruKun commented on Formula/ytarchive.rb
> +  url "https://github.com/Kethsar/ytarchive/archive/refs/tags/latest.tar.gz"
the issue is that the maintainer only ever published a single tag called `latest`, so I don't know how to get around this nicely.

2022-10-12 09:25 UTC, SMillerDev commented on Formula/ytarchive.rb
> +  url "https://github.com/Kethsar/ytarchive/archive/refs/tags/latest.tar.gz"
Then it's not suited for inclusion in Homebrew/core

2022-10-12 13:45 UTC, closed without merging