python@3.7: deprecate on 2023-06-27 (end-of-life)
Homebrew/homebrew-core pull request #114522
Opened 2022-11-02 07:32 UTC by cho-m

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-11-02 08:21 UTC, SMillerDev commented on Formula/python@3.7.rb
> +  deprecate! date: "2023-06-27", because: :deprecated_upstream
It's already deprecated and in security mode
```suggestion
  disable! date: "2023-06-27", because: :deprecated_upstream
```

2022-11-03 19:45 UTC, iMichka requested changes
Need to check the status of `gradio` and `ansible@2.8` first, which both use `python@3.7`

2022-11-03 19:47 UTC, cho-m commented
> Need to check the status of `gradio` and `ansible@2.8` first, which both use `python@3.7`

Both are disabled and will automatically be removed before `python@3.7` is removed.

2022-11-03 19:47 UTC, iMichka approved these changes

2022-11-03 19:49 UTC, Porkepix commented
> Need to check the status of `gradio` and `ansible@2.8` first, which both use `python@3.7`

Gradio isn't maintained anymore as it's replaced by https://gitlab.gnome.org/World/Shortwave a complete rewrite in Rust.
Ansible 2.8 support have ended for now quite a long time (and several versions after that one actually, Ansible only support current release and one or two older releases).

2022-11-03 20:04 UTC, closed without merging