juju-wait 2.5.0 (new formula)
Homebrew/homebrew-core pull request #11472
Opened 2017-03-22 15:00 UTC by battlemidget

Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-22 17:22 UTC, bfontaine requested changes

2017-03-22 17:22 UTC, bfontaine commented on Formula/juju-wait.rb
> +  desc "juju-wait, Juju plugin for waiting for deployments to settle."
Please don’t include the formula name in its description.

2017-03-22 17:22 UTC, bfontaine commented on Formula/juju-wait.rb
> +  end
Please remove this block; our bot will handle that.

2017-03-22 17:22 UTC, bfontaine commented on Formula/juju-wait.rb
> +    system "#{bin}/juju-wait", "--version"
Can’t we write a test that does something more substantial than e.g. `--help` or `--version`?

2017-03-22 17:25 UTC, battlemidget commented on Formula/juju-wait.rb
> +    system "#{bin}/juju-wait", "--version"
Unfortunatley, we need an existing juju environment already deployed which would include bootstrapping to a public cloud an deploying a service to test this plugin.

2017-03-22 17:28 UTC, battlemidget commented on Formula/juju-wait.rb
> +  end
sorry, I should've asked, do you the entire bottle -> end block removed?

2017-03-22 18:17 UTC, bfontaine approved these changes

2017-03-22 18:52 UTC, battlemidget commented
Not sure why the build failed now? Is that a known issue with the bottle block being removed?

2017-03-23 08:58 UTC, bfontaine commented
```
FATAL: Could not checkout 07fc9253f54e6d6304b73e62c7a2127091f3f8d4
hudson.plugins.git.GitException: Could not checkout 07fc9253f54e6d6304b73e62c7a2127091f3f8d4
```
It was just a transient error; it’s all green now :smiley:

2017-03-23 09:14 UTC, fxcoudert commented
Thanks @battlemidget for your contribution to Homebrew!

2017-03-23 09:14 UTC, closed without merging