fzy 0.8 (new formula)
Homebrew/homebrew-core pull request #11513
Opened 2017-03-23 15:44 UTC by sbdchd

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
homepage: https://github.com/jhawthorn/fzy

2017-03-23 16:19 UTC, bfontaine requested changes

2017-03-23 16:19 UTC, bfontaine commented on Formula/fzy.rb
> +    system "#{bin}/fzy", "--help"
Please write a test that does something more substantial than `--help`.

2017-03-23 16:19 UTC, bfontaine commented on Formula/fzy.rb
> +    man.install "fzy.1"
This should go in `man1`. Why doesn’t the `make install` step take care of that?

2017-03-23 19:00 UTC, sbdchd commented
@bfontaine I have updated the formula with a new test.

2017-03-23 19:55 UTC, bfontaine commented on Formula/fzy.rb
> +    assert_match /Must be integer in range 3/, stderr.read
You can use `shell_output`:
```ruby
assert_match "Must be integer in range 3", shell_output("#{bin}/fzy -l 0")
```

2017-03-23 20:00 UTC, sbdchd commented on Formula/fzy.rb
> +    assert_match /Must be integer in range 3/, stderr.read
That doesn't seem to work as `fzy` is sending data via stderr

2017-03-23 20:11 UTC, bfontaine commented on Formula/fzy.rb
> +    assert_match /Must be integer in range 3/, stderr.read
Sorry; add `2>&1` at the end.

2017-03-23 20:32 UTC, sbdchd commented on Formula/fzy.rb
> +    assert_match /Must be integer in range 3/, stderr.read
```rb
assert_match "Must be integer in range 3", shell_output("#{bin}/fzy -l 0 2>&1")
```
The above assertion doesn't work with my setup.

Is there a straightforward way to debug the comparison?

2017-03-24 13:04 UTC, sbdchd commented
@bfontaine updated with your test suggestion

2017-03-24 14:09 UTC, bfontaine approved these changes

2017-03-25 14:45 UTC, closed without merging

2017-03-25 14:46 UTC, fxcoudert commented
Thanks @sbdchd for your contribution to Homebrew!