cookiecutter: python 3.11
Homebrew/homebrew-core pull request #115574
Opened 2022-11-12 13:12 UTC by singingwolfboy

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-11-13 19:03 UTC, fxcoudert requested changes
We will need one commit per formula

2022-11-13 19:03 UTC, fxcoudert commented on Formula/molecule.rb
> +    # %w[cookiecutter jsonschema].each do |package_name|
Why not `jsonschema`? Also, we do not keep old code as comments, but rather a short explanation.

2022-11-14 11:23 UTC, singingwolfboy commented
I changed `molecule` to no longer depend on `jsonschema`, in order to make this change separately from [the long list of formulae that depend on `jsonschema`](https://github.com/Homebrew/homebrew-core/pull/114924#issuecomment-1304931703). We can re-add the dependency once `jsonschema` and friends have migrated to `python@3.11`.

2022-11-14 13:01 UTC, fxcoudert approved these changes

2022-11-14 13:21 UTC, closed without merging