httpflow 0.0.3 (new formula)
Homebrew/homebrew-core pull request #11608
Opened 2017-03-26 16:53 UTC by six-ddc

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-27 09:06 UTC, bfontaine requested changes

2017-03-27 09:06 UTC, bfontaine commented on Formula/httpflow.rb
> +    ]
Please inline the arguments instead of creating an array.

2017-03-27 09:06 UTC, bfontaine commented on Formula/httpflow.rb
> +    system "#{bin}/httpflow", "-h"
Can’t we write a test that does something more substantial than `-v`/`-h`?

2017-03-27 09:06 UTC, bfontaine commented on Formula/httpflow.rb
> +  head "https://github.com/six-ddc/httpflow.git", :branch => "master"
Please remove `, :branch => "master"`, it’s the default.

2017-03-27 10:17 UTC, six-ddc commented on Formula/httpflow.rb
> +  head "https://github.com/six-ddc/httpflow.git", :branch => "master"
OK, Thanks.

2017-03-27 10:17 UTC, six-ddc commented on Formula/httpflow.rb
> +    ]
OK, Thanks.

2017-03-27 10:24 UTC, six-ddc commented on Formula/httpflow.rb
> +    system "#{bin}/httpflow", "-h"
It's not easy, because this require root permission to register network interface.

2017-03-30 00:18 UTC, six-ddc commented
@bfontaine Thanks for the review, I updated it.

2017-03-30 08:01 UTC, bfontaine approved these changes

2017-03-30 09:17 UTC, fxcoudert commented
Many thanks @six-ddc for your contribution to Homebrew!

2017-03-30 09:17 UTC, closed without merging