Apache Flex Formula
Homebrew/homebrew-core pull request #11603
Opened 2017-03-26 12:29 UTC by mshubhankar

**Added Formula for Apache-Flex**
The name of the formula needs to be changed and tests need to be added. 
It is passing brew audit and executing on my macbook running Sierra.
Ref : #11590 

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-26 19:28 UTC, Stellarspace commented
The check failed?

```log
  * A `test do` test block should be added
  * Description is too long. "name: desc" should be less than 80 characters.
    Length is calculated as apache-flex-sdk-installer + desc. (currently 104)
  * C: 31: col 5: Inconsistent indentation detected.
  * W: 32: col 7: Useless assignment to variable - `s`.```

2017-03-26 19:45 UTC, Mactastic1-5 requested changes
The url given to the download is an older version, use 4.16.0 and get the sha256 for it. There's supposed to be an s after line 36. Where did the download url for playerglobal.swc go? Shorten the description, fix the indentation and add a test block.

2017-03-26 20:04 UTC, Stellarspace commented
I just realized that they only offer the 3.2.0 source.

These are the following dependencies:
    - The AIR SDK
    - Adobe Flash Player playerglobal.swc
    - SWFObject
    - Open Source Media Framework (OSMF)

I don't know if you want to add them to it or not.

2017-03-27 12:40 UTC, mshubhankar commented
If I add the download url for playerglobal.swc go , brew audit says the following error-
 `stable resource "flash-playerglobal": version 25.0 is redundant with version scanned from URL`

This is probably because the download url contains the version 2 times in string. How to handle this ?

2017-03-27 13:58 UTC, Stellarspace commented
@mshubhankar No idea

2017-03-28 06:20 UTC, mshubhankar commented
I have made all the changes. Now brew audit --strict is running successfully. But the version string and url string do not match. If I am trying to match them , 
`stable resource "flash-playerglobal": version 25.0 is redundant with version scanned from URL`

this error is coming up . Need Help @MikeMcQuaid

2017-03-28 14:40 UTC, MikeMcQuaid requested changes

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +  url "http://mirror.fibergrid.in/apache/flex/installer/3.2/apache-flex-sdk-installer-3.2.0-src.tar.gz"
Is this built from source or a binary?

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +  version "3.2.1"
Why does it say 3.2.0 in the URL?

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +  option "with-playerglobal", "Installs PlayerGlobal.swc"
What does this do?

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +    version "25.1"
Why does it say `25_0` in the URL?

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +    Dir["*"].each { |file| cp_r file, File.join(prefix, File.basename(file)) }
`prefix.install Dir["*"]`

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +      resource("flash-playerglobal").fetch
Use `resource("flash-playerglobal").stage`

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +      inreplace prefix/"frameworks/flex-config.xml", "/<target-player>11.1<\/target-player>/", "<target-player>25.0</target-player>"
Can you please submit this patch to the upstream developers of this project and add a link to the upstream patch submission and explanation of why the patch is needed in a comment in the formula file. Thanks!

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +      (prefix/"framework/libs/player/25.0").mkpath
This is unnecessary; this path will be created. You also use `framework` in one place and `frameworks` in the other.

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +      export PATH=$(brew --prefix apache-flex-sdk)/bin:$PATH
This is unnecessary; it'll be linked by default.

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +      export FLEX_HOME=$(brew --prefix apache-flex-sdk)
This should be done automatically using a wrapper script rather than requiring the user to do it.

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +      ln -s $(brew --prefix apache-flex-sdk)/ant/lib/flexTasks.jar ~/.ant/lib
Why is this needed?

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +        export PLAYERGLOBAL_HOME=$(brew --prefix apache-flex-sdk)/frameworks/libs/player
This should be done automatically using a wrapper script rather than requiring the user to do it.

2017-03-28 14:40 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +    system bin/"mxmlc"
This test doesn't work: https://bot.brew.sh/job/Homebrew%20Core/19482/version=sierra/testReport/junit/brew-test-bot/sierra/test_apache_flex_sdk/

2017-03-28 19:01 UTC, Stellarspace commented on Formula/apache-flex-sdk.rb
> +  url "http://mirror.fibergrid.in/apache/flex/installer/3.2/apache-flex-sdk-installer-3.2.0-src.tar.gz"
I just realized that the source indicated is the installer, not the source or the binary.
The URL should be from here: https://flex.apache.org/download-source.html
or here: https://flex.apache.org/download-binaries.html
Version: 4.16

2017-03-28 19:02 UTC, Stellarspace commented on Formula/apache-flex-sdk.rb
> +  version "3.2.1"
It's the installer.

2017-03-28 19:03 UTC, Stellarspace commented on Formula/apache-flex-sdk.rb
> +  option "with-playerglobal", "Installs PlayerGlobal.swc"
I don't know what it does, but it says that it's required by the SDK as other things are required as well.
```
Note: the installer downloads other files besides the Apache Flex SDK. These files are needed for the proper functioning of the SDK. The required TLF and the OSMF frameworks, as well as the optional Embedded Font Libraries and Utilities and BlazeDS are mentioned separately in the installer application. The other non-Apache files downloaded by the installer are:

Adobe AIR SDK
PlayerGlobal.swc
SWFObject.js
```

2017-03-28 19:04 UTC, Stellarspace commented on Formula/apache-flex-sdk.rb
> +    version "25.1"
That's how Adobe made it, I don't think it's version 25.1 though.

2017-03-28 19:11 UTC, Stellarspace commented
The formula should be redone using https://cwiki.apache.org/confluence/display/FLEX/Installation+help#Installationhelp-Ant-basedinstaller and http://flex.apache.org/download-binaries.html in mind.

2017-03-28 19:55 UTC, Stellarspace commented
```bash
brew install wget
brew install ant
wget http://mirror.cogentco.com/pub/apache/flex/4.16.0/binaries/apache-flex-sdk-4.16.0-bin.tar.gz
tar zxvf apache-flex-sdk-4.16.0-bin.tar.gz
cd apache-flex-sdk-4.16.0-bin
ant -f installer.xml
y
y
y
mkdir -p frameworks/libs/player/11.1/
wget http://download.macromedia.com/get/flashplayer/updaters/11/playerglobal11_1.swc -O frameworks/libs/player/11.1/playerglobal.swc
bin/mxmlc
# For some reason I get the following error: Error: unable to open '{playerglobalHome}/11.1/playerglobal.swc'
```

2017-03-28 22:53 UTC, Stellarspace commented
I would like to point out that building with ant, downloads and installs the following:
Apache Flex SDK
Adobe Air SDK
Adobe Flash Player playerglobal.swc
These are all required!

I think the formula should use the Ant installation route, but how would it edit the XML file to fix the error?

2017-03-30 05:00 UTC, Stellarspace commented
```bash
$ brew install npm
$ npm install flexjs -g
```
This works too!

2017-03-30 19:13 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +  option "with-playerglobal", "Installs PlayerGlobal.swc"
Let's make it default or figure out a better option name that helps you decide whether you need it or not.

2017-03-30 19:13 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +  url "http://mirror.fibergrid.in/apache/flex/installer/3.2/apache-flex-sdk-installer-3.2.0-src.tar.gz"
This needs to be built from source unless it's Java or C#.

2017-03-30 19:13 UTC, MikeMcQuaid commented
@Stellarspace Feel free to open your own competing PR, if you like.

2017-03-31 07:34 UTC, mshubhankar commented on Formula/apache-flex-sdk.rb
> +    version "25.1"
I wanted to make it 25.0  . This error started to come up . 
`stable resource "flash-playerglobal": version 25.0 is redundant with version scanned from URL`

2017-03-31 08:00 UTC, MikeMcQuaid commented on Formula/apache-flex-sdk.rb
> +    version "25.1"
That means `version "25.0"` is unnecessary so can be omitted

2017-05-26 20:51 UTC, ilovezfs commented
@mshubhankar thanks for the pull request. Feel free to re-open when the requested changes have been made.

2017-05-26 20:51 UTC, closed without merging