libetpan: 1.7.2
Homebrew/homebrew-core pull request #11645
Opened 2017-03-27 10:22 UTC by yurikoles

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-28 09:06 UTC, fxcoudert requested changes

2017-03-28 09:06 UTC, fxcoudert commented on Formula/libetpan.rb
> +
Remove empty line 1

2017-03-28 09:06 UTC, fxcoudert commented on Formula/libetpan.rb
> +  desc "Mail library is to provide a portable, efficient framework."
No period at the end of `desc`.
The sentence should be reworked, maybe _“Portable mail library handling several protocols”_?

2017-03-28 09:06 UTC, fxcoudert commented on Formula/libetpan.rb
> +    system "#{bin}/libetpan-config", "--version"
The standard test for C libraries is to compile a simple source code and link it against the library.

2017-03-28 12:55 UTC, yurikoles commented on Formula/libetpan.rb
> +    system "#{bin}/libetpan-config", "--version"
There is a test directory inside source tree. I'm not sure how to use it.

2017-03-28 17:25 UTC, yurikoles commented
Is there a way how to use test dir for test of this keg?

2017-03-28 20:38 UTC, fxcoudert commented on Formula/libetpan.rb
> +    system "#{bin}/libetpan-config", "--version"
Don't retain the test directory, just include a short example (up to 10 lines) in C inside the `test` block of the formula. Look, for example, at how `zita-convolver.rb` does this.

2017-03-28 20:43 UTC, yurikoles commented
@fxcoudert I'm not sure how to do it, since most tests require a real email account and server setup.

2017-03-29 15:27 UTC, yurikoles commented
@MikeMcQuaid please merge.

2017-03-30 09:02 UTC, fxcoudert commented
We will need a test for this. If we cannot have a run test, they at least compile some C code and link it with the library to check that things are alright. Possibly print the version number from this C code and check it.

2017-03-30 11:00 UTC, yurikoles commented
@fxcoudert done

2017-03-30 11:02 UTC, ilovezfs commented
No release since May of last year. Is this actually maintained?

2017-03-30 11:26 UTC, yurikoles commented
@ilovezfs there was commits a week ago https://github.com/dinhviethoa/libetpan/commits/master

Nevertheless this formula is required by claws-mail which I plan to introduce after merge of this formulae.

2017-03-30 11:38 UTC, fxcoudert approved these changes

2017-03-30 11:53 UTC, closed without merging

2017-03-30 12:51 UTC, fxcoudert commented
Thanks @yurikoles for your contribution to Homebrew!

2017-03-30 12:52 UTC, yurikoles commented
@fxcoudert you welcome.
But why test doesn't print version to stdout?

2017-03-30 14:55 UTC, bfontaine commented
@yurikoles It would if you used `brew test --verbose libetpan` :wink: