shfmt 1.2.0 (new formula)
Homebrew/homebrew-core pull request #11655
Opened 2017-03-27 13:58 UTC by deiga

Adds formula to download and build shfmt with GNU Go

2017-03-27 14:34 UTC, bfontaine requested changes

2017-03-27 14:34 UTC, bfontaine commented on Formula/shfmt.rb
> +    version = "1.2.0"
You can remove this line, the `version` is already guessed from the formula URL.

2017-03-27 14:34 UTC, bfontaine commented on Formula/shfmt.rb
> +    ENV["GOPATH"] = buildpath/".."
Don’t try to do stuff outside of the `buildpath`.

2017-03-27 14:34 UTC, bfontaine commented on Formula/shfmt.rb
> +    mkdir_p buildpath/"../src/github.com/mvdan"
Use `(buildpath/"foo").mkpath` instead of `mkdir_p buildpath/"foo"`.

2017-03-27 14:34 UTC, bfontaine commented on Formula/shfmt.rb
> +    mv buildpath/"../sh-#{version}", buildpath/"../src/github.com/mvdan/sh"
Use `(buildpath/"../src/github.com/mvdan/sh").install "../sh-#{version}"` instead (with the correct path).

2017-03-27 14:34 UTC, bfontaine commented on Formula/shfmt.rb
> +    mkdir buildpath/"sh-#{version}" # so cleanup doesn't fail
Again, use `.mkpath` instead of `mkdir`.

2017-03-27 14:34 UTC, bfontaine commented on Formula/shfmt.rb
> +      bin.install "shfmt"
Use `system "go", "build", ..., "-o", "#{bin}/shfmt"` to avoid this line.

2017-03-27 14:34 UTC, bfontaine commented on Formula/shfmt.rb
> +    touch "shfmt-test-empty"
You can create a minimal test file with e.g. `(testpath/"test").write "echo foo"`.

2017-03-27 14:34 UTC, bfontaine commented on Formula/shfmt.rb
> +  depends_on "go" => :build
Please leave one blank line above that one.

2017-03-27 16:38 UTC, bfontaine commented on Formula/shfmt.rb
> +    (buildpath/"src/github.com/mvdan/sh").install buildpath/"syntax"
You should be able to merge all lines above except the `ENV` one into that one:
```ruby
(buildpath/"src/github.com/mvdan/sh").install "*"
```

`.install` automatically create the missing directories.

2017-03-28 06:13 UTC, deiga commented on Formula/shfmt.rb
> +    (buildpath/"src/github.com/mvdan/sh").install buildpath/"syntax"
@bfontaine `.install` can't locate anything with `"*"`

2017-03-28 07:41 UTC, bfontaine commented on Formula/shfmt.rb
> +    (buildpath/"src/github.com/mvdan/sh").install buildpath/"syntax"
Sorry I meant `Dir["*"]`.

2017-03-28 11:53 UTC, mvdan commented
Also see @focusauru's existing formula

2017-03-28 12:39 UTC, deiga commented
@bfontaine Everything should be good now.
@mvdan I saw and decided that this is popular enough to be inside homebrew-core

This way it also get's some better maintenance

2017-03-28 13:11 UTC, bfontaine approved these changes

2017-03-28 14:45 UTC, focusaurus commented
Would be great to get this into homebrew core! FYI I've updated my tap to v1.2.0.

2017-03-28 20:24 UTC, closed without merging

2017-03-28 20:24 UTC, fxcoudert commented
Thanks @deiga for your contribution!