jvm-mon 0.3 (new formula)
Homebrew/homebrew-core pull request #11661
Opened 2017-03-27 16:17 UTC by ajermakovics

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-27 16:38 UTC, fxcoudert requested changes

2017-03-27 16:38 UTC, fxcoudert commented on Formula/jvm-mon.rb
> +    system "false"
Nope :(
We'll need a test.

2017-03-27 16:41 UTC, bfontaine commented on Formula/jvm-mon.rb
> +    bin.install_symlink libexec/"bin"/"jvm-mon"
You can use `libexec/"bin/jvm-mon"`

2017-03-27 16:41 UTC, bfontaine requested changes

2017-03-27 16:41 UTC, bfontaine commented on Formula/jvm-mon.rb
> +  desc "Console based JVM monitoring"
"Console based" -> "Console-based"

2017-03-27 16:59 UTC, fxcoudert commented
```
==> echo q | /usr/local/Cellar/jvm-mon/0.3/bin/jvm-mon
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalStateException: J2V8 native library not loaded
	at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:195)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:149)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:125)
	at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:58)
	at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:45)
	at JvmMon.<clinit>(JvmMon.java:18)
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
	no j2v8_macosx_x86_64 in java.library.path

	at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:75)
	at com.eclipsesource.v8.V8.load(V8.java:71)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:145)
	... 4 more
Error: jvm-mon: failed
```

2017-03-27 17:05 UTC, ajermakovics commented on Formula/jvm-mon.rb
> +  desc "Console based JVM monitoring"
Thanks! Fixed

2017-03-27 17:06 UTC, ajermakovics commented on Formula/jvm-mon.rb
> +    system "false"
Fair enough:) Added

2017-03-27 17:08 UTC, ajermakovics commented
@fxcoudert Thanks! Looks like some path issue although the same command works locally. Any way to run this locally for debugging? Tried `brew test jvm-mon --verbose` but that also works

2017-03-27 17:44 UTC, bfontaine approved these changes

2017-03-27 19:53 UTC, ajermakovics commented
@fxcoudert Fixed

2017-03-28 08:02 UTC, fxcoudert approved these changes

2017-03-30 13:03 UTC, merged

2017-03-30 13:04 UTC, fxcoudert commented
Thanks @ajermakovics for your contribution to Homebrew!