Bump cmake 3.25.1
Homebrew/homebrew-core pull request #116973
Opened 2022-11-30 15:25 UTC by ZhongRuoyu

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-11-30 18:10 UTC, fxcoudert approved these changes

2022-11-30 20:25 UTC, ZhongRuoyu commented
`brew test --retry --verbose seal` failed on Ubuntu.

I tried `brew install --include-test seal && brew test seal` on two different Intel machines, using the same Docker image `homebrew/ubuntu22.04`. Surprisingly, one failed even without the `cmake` upgrade, while the other worked fine.

A manual test produced the following. Note the "Illegal instruction" error at the end.

```
linuxbrew@bf88e5404c7f:~/seal-test$ bin/sealexamples
Microsoft SEAL version: 4.0.0
+---------------------------------------------------------+
| The following examples should be executed while reading |
| comments in associated files in native/examples/.       |
+---------------------------------------------------------+
| Examples                   | Source Files               |
+----------------------------+----------------------------+
| 1. BFV Basics              | 1_bfv_basics.cpp           |
| 2. Encoders                | 2_encoders.cpp             |
| 3. Levels                  | 3_levels.cpp               |
| 4. BGV Basics              | 4_bgv_basics.cpp           |
| 5. CKKS Basics             | 5_ckks_basics.cpp          |
| 6. Rotation                | 6_rotation.cpp             |
| 7. Serialization           | 7_serialization.cpp        |
| 8. Performance Test        | 8_performance.cpp          |
+----------------------------+----------------------------+
[      0 MB] Total allocation from the memory pool

> Run example (1 ~ 8) or exit (0): 1

+-------------------------------------+
|         Example: BFV Basics         |
+-------------------------------------+
Line 132 --> Set encryption parameters and print
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 4096
|   coeff_modulus size: 109 (36 + 36 + 37) bits
|   plain_modulus: 1024
\
Parameter validation (success): valid

~~~~~~ A naive way to calculate 4(x^2+1)(x+1)^2. ~~~~~~
Illegal instruction
```

IIUC, that was because CI runner did not understand certain instructions that worked on the machine where the bottle was built. A clean build `brew install -s seal` worked fine on both machines.

`brew config` output, for reference:

<details>
<summary> On the machine that failed when poured <code>seal</code> from bottle </summary>
<pre>HOMEBREW_VERSION: 3.6.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 747829334b4bb3ab0d67a4c8bd9f4bf78c491c49
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b4496ce1caf8f5f0ff34d18723e5ea274108af88
Core tap last commit: 19 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: hexa-core 64-bit skylake
Clang: N/A
Git: 2.38.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.49-linuxkit x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
</pre>
</details>

<details>
<summary> On the machine that passed the test </summary>
<pre>HOMEBREW_VERSION: 3.6.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 747829334b4bb3ab0d67a4c8bd9f4bf78c491c49
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b4496ce1caf8f5f0ff34d18723e5ea274108af88
Core tap last commit: 19 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit icelake
Clang: N/A
Git: 2.38.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.49-linuxkit x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
</pre>
</details>

They only differ in `HOMEBREW_MAKE_JOBS` and `CPU`.

Related discussion: microsoft/SEAL#432

2022-11-30 21:16 UTC, fxcoudert requested changes, later dismissed
This will need to be rebased and rebuilt now that https://github.com/Homebrew/homebrew-core/pull/113569 has been merged.

2022-12-01 21:37 UTC, chenrui333 commented
still seal test failure on linux build

2022-12-01 22:32 UTC, chenrui333 approved these changes

2022-12-01 22:52 UTC, closed without merging