docker-machine: remove `deprecate` comment
Homebrew/homebrew-core pull request #117033
Opened 2022-12-01 03:27 UTC by chenrui333

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

As gitlab is actively maintaining the fork, I think it is good to remove the `deprecate` comment

2022-12-01 03:31 UTC, carlocab commented
Related: https://github.com/Homebrew/homebrew-core/issues/106902#issuecomment-1203562880

2022-12-01 07:18 UTC, SMillerDev commented
Gitlab sees it as deprecated though. I disagree with this.

2022-12-01 09:02 UTC, SMillerDev requested changes
I think we should deprecate the dependents too

2022-12-02 14:54 UTC, chenrui333 commented
I see, I will also raise a gitlab issue before further pursuing this. (in terms of maintenance commitment)

For the dependents, I agree, most of them are not being actively maintained.

2022-12-10 03:49 UTC, chenrui333 commented
Gonna close this for now. Thanks folks!

2022-12-10 03:49 UTC, closed without merging