latex2html: add "test do" block
Homebrew/homebrew-core pull request #11712
Opened 2017-03-28 03:59 UTC by raza15

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Adding a ``` test do ``` block in the formula ```latex2html```

2017-03-28 07:42 UTC, bfontaine commented
Can’t we write a test that does something more substantial than e.g. printing the version or the help?

2017-03-28 20:32 UTC, fxcoudert commented
Idea for a test: create a file `test.tex` with one line `\textbf{it works!}`.
Run `latex2html test.tex`.
Check that this creates a file named `test/test.html` which contains `it works!`.

2017-03-28 20:49 UTC, raza15 commented
@fxcoudert already done that. Will be pushing changes in a while

2017-03-28 21:14 UTC, raza15 commented
@bfontaine @fxcoudert added non-trivial tests too. Let me know if you like it!

2017-03-28 22:43 UTC, bfontaine requested changes

2017-03-28 22:43 UTC, bfontaine commented on Formula/latex2html.rb
> +    system "#{bin}/latex2html", "--help"
You can remove those now that there’s a non-trivial test below.

2017-03-28 22:43 UTC, bfontaine commented on Formula/latex2html.rb
> +    # Non-Trivial Test
Please remove this comment.

2017-03-28 22:43 UTC, bfontaine commented on Formula/latex2html.rb
> +    test_file.close
You can create a file with the following code:
```ruby
(testpath/"test.tex").write <<-EOS.undent
  \documentclass{article}
  ...
EOS

2017-03-28 22:43 UTC, bfontaine commented on Formula/latex2html.rb
> +    # Now, goes to that html file and checks the content
You can’t assume `nokogiri` is installed. The `assert_match` above is sufficient; thanks!

2017-03-28 22:49 UTC, raza15 commented on Formula/latex2html.rb
> +    test_file.close
when i was creating a file with this code, it was giving error that ``` invalid unicode escape \usepackage ```. Do u want me to do it anyway?

2017-03-28 22:50 UTC, bfontaine commented on Formula/latex2html.rb
> +    test_file.close
You’ll have to double every backslack like so:
(testpath/"test.tex").write <<-EOS.undent
  \\documentclass{article}
  \\usepackage{...}
  ...
EOS

2017-03-28 23:19 UTC, raza15 commented on Formula/latex2html.rb
> +    test_file.close
Great. Thanks!

2017-03-28 23:23 UTC, raza15 commented
@bfontaine made all the changes you requested.

2017-03-29 08:39 UTC, merged

2017-03-29 08:40 UTC, fxcoudert commented
Thanks @raza15 for your contribution to Homebrew!