terraform-docs 0.1.0 (new formula)
Homebrew/homebrew-core pull request #11768
Opened 2017-03-29 03:46 UTC by jacobwgillespie

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR adds the `terraform-docs` CLI tool from https://github.com/segmentio/terraform-docs. 🎉

2017-03-29 13:14 UTC, bfontaine requested changes

2017-03-29 13:14 UTC, bfontaine commented on Formula/terraform-docs.rb
> +      bin.install "terraform-docs"
Please use `system "go", "build", "-o", "#{bin}/terraform-docs"` so you can remove this line.

2017-03-29 13:14 UTC, bfontaine commented on Formula/terraform-docs.rb
> +    minimal.write <<-EOS.undent
You probably don’t need to create a variable if you use it once:
```ruby
(testpath/"main.tf").write <<-EOS.undent
  ...
```

2017-03-29 14:37 UTC, jacobwgillespie commented
Good catches, updated.

2017-03-29 15:59 UTC, bfontaine approved these changes

2017-03-30 09:14 UTC, fxcoudert commented
Thanks a lot @jacobwgillespie for your contribution to Homebrew!

2017-03-30 09:14 UTC, closed without merging