xmlsectool 2.0.0 (new formula)
Homebrew/homebrew-core pull request #11812
Opened 2017-03-29 16:48 UTC by gvarisco

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-29 17:03 UTC, bfontaine requested changes

2017-03-29 17:03 UTC, bfontaine commented on Formula/xmlsectool.rb
> +  desc "Download, check well-formedness, schema validity, and signature of an XML document. It can also create enveloped signatures of an XML document."
Please shorten this description; it should fit in 80 characters.

2017-03-29 17:03 UTC, bfontaine commented on Formula/xmlsectool.rb
> +  url "https://shibboleth.net/downloads/tools/xmlsectool/latest/xmlsectool-2.0.0-bin.zip"
We need to build from source here.

2017-03-29 17:03 UTC, bfontaine commented on Formula/xmlsectool.rb
> +    # Install files
Please remove these comments.

2017-03-29 17:03 UTC, bfontaine commented on Formula/xmlsectool.rb
> +  end
This doesn’t seem Homebrew-specific.

2017-03-29 17:08 UTC, gvarisco commented on Formula/xmlsectool.rb
> +  desc "Download, check well-formedness, schema validity, and signature of an XML document. It can also create enveloped signatures of an XML document."
I saw the jenkins' output. Fixed.

2017-03-29 17:08 UTC, gvarisco commented on Formula/xmlsectool.rb
> +    # Install files
I saw the jenkins' output. Fixed.

And comments removed.

2017-03-29 17:09 UTC, gvarisco commented on Formula/xmlsectool.rb
> +  end
Removed. I added it as seen in other formulas. sorry! :)

2017-03-29 17:17 UTC, gvarisco commented
@bfontaine thanks for the review. In order to build it from source ( git://git.shibboleth.net/xmlsectool.git ), what about the other dependencies (JARs)? How shall we build them? I'm talking about:
`└── libexec
    ├── lib
    │   ├── bcprov-jdk15on-1.53.jar
    │   ├── commons-codec-1.10.jar
    │   ├── cryptacular-1.0.jar
    │   ├── guava-18.0.jar
    │   ├── httpclient-4.3.6.jar
    │   ├── httpcore-4.3.3.jar
    │   ├── java-support-7.2.0.jar
    │   ├── jcl-over-slf4j-1.7.12.jar
    │   ├── jcommander-1.48.jar
    │   ├── joda-time-2.9.jar
    │   ├── jsr305-3.0.1.jar
    │   ├── logback-classic-1.1.3.jar
    │   ├── logback-core-1.1.3.jar
    │   ├── opensaml-core-3.2.0.jar
    │   ├── opensaml-messaging-api-3.2.0.jar
    │   ├── opensaml-security-api-3.2.0.jar
    │   ├── opensaml-security-impl-3.2.0.jar
    │   ├── opensaml-xmlsec-api-3.2.0.jar
    │   ├── opensaml-xmlsec-impl-3.2.0.jar
    │   ├── slf4j-api-1.7.12.jar
    │   ├── stax-api-1.0-2.jar
    │   ├── stax2-api-3.1.4.jar
    │   ├── woodstox-core-asl-4.4.1.jar
    │   ├── xmlsec-2.0.5.jar
    │   └── xmlsectool-2.0.0.jar`

2017-03-29 17:21 UTC, MikeMcQuaid commented
@gvarisco Java doesn't need to be built from source but any native code does. This looks like it should be fine.

2017-03-30 08:01 UTC, bfontaine approved these changes

2017-03-30 15:23 UTC, gvarisco commented
awesome, thanks @bfontaine and @MikeMcQuaid for the prompt review! We should be good to go, I believe.

2017-03-30 15:52 UTC, bfontaine commented on Formula/xmlsectool.rb
> +  desc "Download, check well-formedness, schema validity, and signature of an XML document. It can also create enveloped signatures of an XML document."
Seems like it’s still too long :)
```
Error: 1 problem in 1 formula
xmlsectool:
  * Description is too long. "name: desc" should be less than 80 characters.
    Length is calculated as xmlsectool + desc. (currently 85)
```

2017-03-30 15:53 UTC, bfontaine commented
The test is failing: https://bot.brew.sh/job/Homebrew%20Core/19607/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_xmlsectool/

```
==> /usr/local/Cellar/xmlsectool/2.0.0/bin/xmlsectool --listBlacklist
ERROR: JAVA_HOME environment variable is not set.
Error: xmlsectool: failed
Failed executing: /usr/local/Cellar/xmlsectool/2.0.0/bin/xmlsectool --listBlacklist
...
```

2017-03-30 15:55 UTC, gvarisco commented on Formula/xmlsectool.rb
> +  desc "Download, check well-formedness, schema validity, and signature of an XML document. It can also create enveloped signatures of an XML document."
haha, I've missed the "xmlsectool + desc" part.. Fixing it now.

2017-03-30 17:16 UTC, gvarisco commented
hey @bfontaine - saw it. I probably need your advice here :) 

"**/usr/local/Cellar/xmlsectool/2.0.0/bin/xmlsectool --listBlacklist**" works correctly once JAVA_HOME is set. 

`
$  /usr/local/Cellar/xmlsectool/2.0.0/bin/xmlsectool --listBlacklist
Digest algorithm blacklist:
   http://www.w3.org/2000/09/xmldsig#sha1
   http://www.w3.org/2001/04/xmldsig-more#md5

Signature algorithm blacklist:
   http://www.w3.org/2000/09/xmldsig#rsa-sha1
   http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1
   http://www.w3.org/2001/04/xmldsig-more#rsa-md5
`

I've added `ENV["JAVA_HOME"] = `/usr/libexec/java_home`.chomp` to the tests, but not sure if it is enough (as it still fails on my side, unless I set the JAVA_HOME variable). Is there any preferred way to have it set correctly?

2017-03-30 17:18 UTC, gvarisco commented on Formula/xmlsectool.rb
> +  desc "Download, check well-formedness, schema validity, and signature of an XML document. It can also create enveloped signatures of an XML document."
should be OK now.

2017-03-30 19:18 UTC, MikeMcQuaid commented
> Is there any preferred way to have it set correctly?

Write a wrapper script which sets the variable. `grep` to see usage of `write_env_script` and `env_script_all_files`

2017-03-31 13:40 UTC, gvarisco commented
@MikeMcQuaid oh, thanks for the heads up! Should be good now.

2017-04-01 18:41 UTC, dunn commented on Formula/xmlsectool.rb
> +    rm_rf "doc"
Why remove this, out of curiosity?

2017-04-02 09:14 UTC, gvarisco commented on Formula/xmlsectool.rb
> +    rm_rf "doc"
It only contains:
````
├── LICENSE.txt
├── xmlsectool.patch
└── xmlsectool.spec
```
nothing relevant to copy over.

2017-04-02 14:19 UTC, dunn commented on Formula/xmlsectool.rb
> +    rm_rf "doc"
Couldn't hurt to `prefix.install "doc/LICENSE.TXT"` (we have an `#install_metafiles` method that does it automatically if it's in the directory root).

2017-04-03 06:11 UTC, gvarisco commented on Formula/xmlsectool.rb
> +    rm_rf "doc"
@dunn OK! Just added it.

2017-04-03 07:02 UTC, closed without merging

2017-04-03 07:03 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-04-03 07:03 UTC, MikeMcQuaid commented
(fixed up unneeded additional metafiles installation in e42971f32d)