[WIP]new formulae: claws-mail
Homebrew/homebrew-core pull request #11838
Opened 2017-03-30 12:38 UTC by yurikoles

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
It can't find `<gdk/gdkx.h>`
<details><summary> brew install claws-mail error</summary>

```
$ brew install claws-mail 
Updating Homebrew...
==> Using the sandbox
==> Downloading http://www.claws-mail.org/download.php?file=releases/claws-mail-3.15.0.tar.xz
Already downloaded: /Users/yurikoles/Library/Caches/Homebrew/claws-mail-3.15.0.tar.xz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/claws-mail/3.15.0
==> make install
Last 15 lines from /Users/yurikoles/Library/Logs/Homebrew/claws-mail/02.make:
#include <gdk/gdkx.h>
         ^
1 error generated.
make[5]: *** [x11/libcmnpgtkhotkey_la-tomboykeybinder.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
x11/eggaccelerators.c:24:10: fatal error: 'gdk/gdkx.h' file not found
#include <gdk/gdkx.h>
         ^
1 error generated.
make[5]: *** [x11/libcmnpgtkhotkey_la-eggaccelerators.lo] Error 1
make[4]: *** [install-recursive] Error 1
make[3]: *** [install-recursive] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

READ THIS: http://docs.brew.sh/Troubleshooting.html</details>

2017-04-14 15:06 UTC, yurikoles commented
@Homebrew/maintainers - why there is no `<gdk/gdkx.h`

2017-04-28 20:41 UTC, yurikoles commented
bump?

2017-04-30 13:05 UTC, MikeMcQuaid requested changes

2017-04-30 13:05 UTC, MikeMcQuaid commented on Formula/claws-mail.rb
> +# PLEASE REMOVE ALL GENERATED COMMENTS BEFORE SUBMITTING YOUR PULL REQUEST!
> PLEASE REMOVE ALL GENERATED COMMENTS BEFORE SUBMITTING YOUR PULL REQUEST!

2017-04-30 13:05 UTC, MikeMcQuaid commented on Formula/claws-mail.rb
> +  depends_on :x11 # if your formula requires any X11/XQuartz components
Can this be made to work at all without X11?

2017-04-30 13:05 UTC, MikeMcQuaid commented on Formula/claws-mail.rb
> +  head 'http://git.claws-mail.org/readonly/claws.git'
Double quotes

2017-04-30 13:05 UTC, MikeMcQuaid commented on Formula/claws-mail.rb
> +    system "true"
Write a proper test.

2017-04-30 13:06 UTC, MikeMcQuaid commented
@yurikoles Don't know, sorry. Sounds like a missing dependency or missing configure option.

2017-04-30 15:48 UTC, closed without merging