thrift@0.9 0.9.3 (new formula)
Homebrew/homebrew-core pull request #11855
Opened 2017-03-30 19:23 UTC by fernandomora

* Based on https://github.com/Homebrew/homebrew-core/blob/74063d85f4da579d02e34d8770756273707aec0b/Formula/thrift.rb

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-30 19:56 UTC, fernandomora commented
Automated build gives the following error:
```Error: 1 problem in 1 formula
thrift@0.9:
  * Dependency 'bison' may be unnecessary as it is provided by macOS; try to build this formula without it.```

But building the formula without `bison` dependency fails since build process fails with:
```checking for bison version >= 2.5... no
configure: error: Bison version 2.5 or higher must be installed on the system!```

How could tell brew bot to skip that check in the automated build?

2017-03-30 20:01 UTC, MikeMcQuaid commented
> How could tell brew bot to skip that check in the automated build?

@fernandomora You can ignore it, we'll merge regardless. Thanks for checking ❤️

2017-04-01 18:25 UTC, dunn commented
The test is failing, though:
```
==> /usr/local/Cellar/thrift@0.9/0.9.3/bin/thrift --version
Error: thrift@0.9: failed
<1> expected but was
<0>.
```
(A more thorough test would be nice, too!)

2017-04-03 11:32 UTC, fernandomora commented
Sorry, I fixed the test, it should work now
```
$ brew test thrift@0.9
Testing thrift@0.9
==> Using the sandbox
==> /usr/local/Cellar/thrift@0.9/0.9.3/bin/thrift --version
==> /usr/local/Cellar/thrift@0.9/0.9.3/bin/thrift --version
```

2017-04-03 11:40 UTC, fernandomora commented
@dunn Regarding the test, I'm following what the old thrift090 formula was doing and what the Thrift documentation suggests: http://thrift-tutorial.readthedocs.io/en/latest/installation.html#verify-installation
I think It should be enough, but I'm open to any suggestion to perform a simple but more thorough test.

2017-04-07 17:55 UTC, neutric commented on Formula/thrift@0.9.rb
> +    assert_match /0\.9\.3/, shell_output("#{bin}/thrift --version", 0)
Why not combine this to `assert_match "Thrift version #{version}", shell_output("#{bin}/thrift --version", 0)`?

2017-04-07 17:56 UTC, neutric commented on Formula/thrift@0.9.rb
> +    exclusions = ["--without-ruby", "--disable-tests", "--without-php_extension"]
The above two lines can go as stable is all there is now.

2017-04-07 17:56 UTC, neutric commented on Formula/thrift@0.9.rb
> +
The above two lines can go as stable is all there is now.

2017-04-07 17:59 UTC, neutric requested changes

2017-04-07 17:59 UTC, neutric commented on Formula/thrift@0.9.rb
> +
The above two lines can go as stable is all there is now.

2017-04-07 17:59 UTC, neutric commented on Formula/thrift@0.9.rb
> +    assert_match /0\.9\.3/, shell_output("#{bin}/thrift --version", 0)
Why not combine this to `assert_match "Thrift version #{version}", shell_output("#{bin}/thrift --version", 0)`?

2017-05-02 14:22 UTC, fxcoudert commented
We do we need yet another versioned formula for this?

2017-05-17 12:29 UTC, fxcoudert commented
I don't think there is a real use case made for a versioned formula here, closing the PR.

2017-05-17 12:29 UTC, closed without merging