Fast
Homebrew/homebrew-core pull request #11913
Opened 2017-03-31 22:13 UTC by yijunyu

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-03-31 23:06 UTC, bfontaine requested changes

2017-03-31 23:06 UTC, bfontaine commented on Formula/srcml.rb
> +# PLEASE REMOVE ALL GENERATED COMMENTS BEFORE SUBMITTING YOUR PULL REQUEST!
As stated: please remove these comments.

2017-03-31 23:06 UTC, bfontaine commented on Formula/fast.rb
> +    system "true"
We need a test here.

2017-03-31 23:06 UTC, bfontaine commented on Formula/fast.rb
> +  version "0.0.2"
Why is this 0.0.2 here but 0.0.1 in the URL?

2017-03-31 23:06 UTC, bfontaine commented on Formula/srcml.rb
> +  desc "srcML - an infrastructure for the exploration, analysis, and manipulation of source code"
Please remove the formula name from its description.

2017-03-31 23:06 UTC, bfontaine commented on Formula/srcml.rb
> +  url "http://131.123.42.38/lmcrs/beta/srcML-src.tar.gz"
We need a versioned URL here.

2017-03-31 23:06 UTC, bfontaine commented on Formula/srcml.rb
> +#  end
Please remove these comments.

2017-03-31 23:06 UTC, bfontaine commented on Formula/srcml.rb
> +    #system "cmake", "-DINSTALL_PREFIX=/usr/local/Cellar/srcml/0.9.5", "-G", "Unix Makefiles", *std_cmake_args
Please remove this comment.

2017-03-31 23:06 UTC, bfontaine commented on Formula/srcml.rb
> +    system "true"
We need a test here too.

2017-03-31 23:06 UTC, bfontaine commented on Formula/srcml.rb
> +  patch :DATA
Please submit this patch upstream and add a link to the upstream issue report in a comment.

2017-03-31 23:10 UTC, bfontaine commented
This appears to be a self-submission of a relatively new and not well-known project. You can [maintain a formula in your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) and re-submit it again here once it’s popular/mature enough.
It’s also easier to review if you make one pull-request per new formula and label each one "`<formula name> <version> (new formula)`", e.g. "`fast 0.0.1 (new formula)`". Thanks!

2017-03-31 23:10 UTC, closed without merging

2017-04-01 15:46 UTC, yijunyu commented
Thank you for the comments, I will try a new tap then, thank you for taking a look at it, which has been a lot of learning experience for me. When we get more users I will then ask your help again.