kitchen-sync: add options to build with MariaDB or MariaDB 10.0
Homebrew/homebrew-core pull request #11915
Opened 2017-04-01 01:27 UTC by kuahyeow

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-17 12:32 UTC, fxcoudert requested changes

2017-05-17 12:32 UTC, fxcoudert commented on Formula/kitchen-sync.rb
Move to `depends_on "yaml-cpp"` without option

2017-05-17 21:58 UTC, soundasleep commented
+1 yes please

2017-05-17 22:00 UTC, ilovezfs commented
You can already use the :mysql require with mariadb.

2017-05-17 22:00 UTC, closed without merging

2017-05-18 07:15 UTC, kuahyeow commented
Oh, I see. TIL !