discount: enabled shared libraries
Homebrew/homebrew-core pull request #119389
Opened 2022-12-30 06:50 UTC by danielnachun

`pdfpc` fails to build on Linux because `discount` is missing both the `pkg-config` files and shared libraries needed for it to be found and linked by `pdfpc`: https://github.com/Homebrew/homebrew-core/pull/118911.

This PR will fix this by enabling the `pkg-config` files and shared libraries.  The idiosyncratic build system for `discount` tries to invoke `ldconfig` on Linux which fails because doing so requires root access, so a Homebrew-specific workaround is needed to disable this behavior by calling `true` instead of `ldconfig`.

2022-12-30 07:05 UTC, dawidd6 approved these changes, later dismissed

2022-12-30 07:50 UTC, SMillerDev commented
Could you report this root requirement as an issue upstream?

2022-12-30 12:52 UTC, fxcoudert requested changes
I see there is a version [2.2.7b](https://www.pell.portland.or.us/~orc/Code/discount/discount-2.2.7b.tar.bz2), could we update?

2022-12-30 12:52 UTC, fxcoudert commented on Formula/discount.rb
> +    inreplace "librarian.sh", "/sbin/ldconfig", "true" if OS.linux?
We should not modify the scripts. If it is an upstream bug, they can fix it. If it is the behavior upstream thinks desirable, we should keep it.

2022-12-31 01:29 UTC, chenrui333 commented
trying out discount 2.2.7b

2022-12-31 11:05 UTC, fxcoudert commented
1. `discount: Formula version newer than livecheck`
2. I still think we should not patch the script: if upstream thinks it's necessary to call a root utility, there is probably a good reason. Or it should be raised for them to fix.

2022-12-31 16:38 UTC, chenrui333 commented
> 1. discount: Formula version newer than livecheck

yeah, I can help with that.

2023-01-03 03:55 UTC, danielnachun commented
I've got an update for this - it turns out that `pdfpc` will build fine if we just add the `--pkg-config` flag (which doesn't require any patching) but not the `--shared` flag.  While using the shared library is preferable, it is not necessary for now, and I've updated the PR so that it adds the missing `pkg-config` files so that dependents can find the static library.

> I still think we should not patch the script: if upstream thinks it's necessary to call a root utility, there is probably a good reason. Or it should be raised for them to fix

Before merging this I'd like to open an issue on the upstream GitHub that I will link in a comment in the formula explaining this problem.  This is a fairly unusual situation in which the upstream build script manually invokes `ldconfig` to rebuild `ld.so.cache`.  On modern Linux distros this is only done by the host package manager (i.e. `apt`, `yum`, etc.), and in Homebrew, we rely on RPATH to find libraries rather than `ld.so.cache`.   Manually invoking it like they do in their build script could actually cause breakage and I suspect they did not understand that there are better ways to find the shared library than messing with `ldconfig`.

2023-01-03 04:33 UTC, danielnachun commented
I opened the issue upstream and added the comment - this should be ready to merge when CI is done.

2023-01-03 09:01 UTC, SMillerDev approved these changes

2023-01-03 21:45 UTC, iMichka approved these changes

2023-01-04 22:08 UTC, fxcoudert approved these changes

2023-01-04 22:09 UTC, closed without merging