arabica: fix addition of test do block
Homebrew/homebrew-core pull request #11994
Opened 2017-04-03 12:17 UTC by Tanya-Jain

- [y] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [y] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [y] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [n] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-03 14:14 UTC, fxcoudert requested changes

2017-04-03 14:14 UTC, fxcoudert commented on Formula/arabica.rb
> +    system bin/"arabica", "-o"
```
==> /usr/local/Cellar/arabica/20160214/bin/arabica -o
Failed to execute: /usr/local/Cellar/arabica/20160214/bin/arabica
Error: arabica: failed
```

2017-04-03 14:14 UTC, fxcoudert commented on Formula/arabica.rb
> +    (testpath/"test.file").write("writing some test file, if you need to\n")
Don't.

2017-04-03 14:14 UTC, fxcoudert commented on Formula/arabica.rb
> +
`C: 31:  1: Trailing whitespace detected.`

2017-04-11 03:33 UTC, dunn commented
Ping on the above comments!

2017-04-23 14:43 UTC, fxcoudert commented
No response, closing this PR for now.

2017-04-23 14:43 UTC, closed without merging