new blitz repository for head
Homebrew/homebrew-core pull request #12014
Opened 2017-04-04 01:49 UTC by bhelenbr

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

blitz has moved to a git repository which is more up to date than the mercurial repository.  I have only changed the repository name and removed the requirement for hg

2017-04-04 07:05 UTC, fxcoudert commented
Is it really the same project? Because the one on github seems to have a 1.0 release which is not the case of the sourceforge project. (And the Github repo is nowhere mentioned on the SF website.)

2017-04-04 11:04 UTC, bhelenbr commented
Yes.  It is the same project. The github repository is up-to-date.  (I have submitted bug fixes to it.)   The mercurial one is not used and does not have the most recent bug fixes.

Brian Helenbrook
Paynter-Krigman Endowed Professor in Engineering Science Simulation
Mechanical and Aeronautical Engineering Department
357 CAMP
Clarkson University
Potsdam, NY 13699-5725

work: 315-268-2204
fax: 315-268-6695



> On Apr 4, 2017, at 3:05 AM, FX Coudert <notifications@github.com> wrote:
> 
> Is it really the same project? Because the one on github seems to have a 1.0 release which is not the case of the sourceforge project. (And the Github repo is nowhere mentioned on the SF website.)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/Homebrew/homebrew-core/pull/12014#issuecomment-291412922>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ANcjV0wDXhAYmXchP-EsMNiPiwAwq7rQks5rseupgaJpZM4MyS3h>.
>

2017-04-04 14:18 UTC, bfontaine requested changes

2017-04-04 14:18 UTC, bfontaine commented on Formula/blitz.rb
> +    url "https://github.com/blitzpp/blitz.git", :using => :git
You can drop the `, :using => :git`; it’s the default.

2017-04-04 14:34 UTC, bfontaine approved these changes

2017-04-23 10:05 UTC, merged

2017-04-23 10:05 UTC, fxcoudert commented
Thanks @bhelenbr for the pull request!