tag: fix missing manual
Homebrew/homebrew-core pull request #12036
Opened 2017-04-04 12:51 UTC by cesarandreu

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Added missing manual entry.

2017-04-04 13:00 UTC, MikeMcQuaid requested changes

2017-04-04 13:00 UTC, MikeMcQuaid commented on Formula/tag.rb
> +    man1.install "Tag/tag.1"
Let's try to figure out how to use `make install` instead which will avoid future omissions: https://github.com/jdberry/tag/blob/master/Makefile#L36

2017-04-11 03:33 UTC, dunn commented on Formula/tag.rb
> +    man1.install "Tag/tag.1"
Ping on this.

2017-04-23 14:35 UTC, fxcoudert commented
Closing for now, please reopen once the issue was reported/fixed upstream.

2017-04-23 14:35 UTC, closed without merging