mame & rom-tools 0.184
Homebrew/homebrew-core pull request #12146
Opened 2017-04-06 13:53 UTC by mbcoguno

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
* Add missing dependency.
* Add Xcode 8.3 trick.

2017-04-23 14:24 UTC, fxcoudert requested changes

2017-04-23 14:24 UTC, fxcoudert commented on Formula/mame.rb
> +  depends_on "jpeg"
Please do not shuffle existing dependencies

2017-04-23 14:24 UTC, fxcoudert commented on Formula/mame.rb
>    # Needs GCC 4.9 or newer
Update the comment

2017-04-23 14:24 UTC, fxcoudert commented on Formula/mame.rb
> +    ENV.O2 if DevelopmentTools.clang_build_version == 802
Why is it a *partial* solution? And please add link to issue report

2017-04-29 00:46 UTC, dunn commented
Thanks so much!

2017-04-29 00:46 UTC, closed without merging