haxe: fixed --HEAD
Homebrew/homebrew-core pull request #12156
Opened 2017-04-06 17:46 UTC by andyli

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Updated the haxe formula to adapt recent changes in upstream.
The usage of opam is borrowed from other ocaml-based formulae, e.g. https://github.com/Homebrew/homebrew-core/blob/master/Formula/coccinelle.rb

2017-04-11 03:49 UTC, kevinresol commented
Any updates on this? 
Currently homebrew fails to install haxe --HEAD

2017-04-20 07:31 UTC, andyli commented
What's holding this PR back?

2017-04-20 07:34 UTC, ilovezfs requested changes

2017-04-20 07:34 UTC, ilovezfs commented on Formula/haxe.rb
> +  depends_on "opam" => :build if build.head?
This should be moved into a `head do` block

2017-04-20 07:37 UTC, ilovezfs commented
otherwise looks good
```
==> Summary
🍺  /usr/local/Cellar/haxe/HEAD-c8e43d3: 2,333 files, 19MB, built in 1 minute 2 seconds
iMac-TMP:~ joe$ brew test haxe
Testing haxe
==> Using the sandbox
==> /usr/local/Cellar/haxe/HEAD-c8e43d3/bin/haxe -v Std
==> /usr/local/Cellar/haxe/HEAD-c8e43d3/bin/haxelib version
```

2017-04-20 07:51 UTC, ilovezfs approved these changes

2017-04-20 09:00 UTC, merged

2017-04-20 09:00 UTC, ilovezfs commented
Thanks @andyli :rocket: