rizin: put plugins into the regular folder
Homebrew/homebrew-core pull request #121678
Opened 2023-01-27 15:59 UTC by ret2libc

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Right now plugins don't work with homebrew-rizin because the rizin_plugins is just the part after the `--prefix` and not an absolute path. Is there any particular reason to have plugins in another directory?

If there is, we may need to adjust the behaviour in rizin upstream.

2023-01-28 17:17 UTC, chenrui333 commented
@ebmmy do you mind also reviewing this PR? Thanks!

2023-01-28 17:17 UTC, chenrui333 reviewed
LGTM

2023-01-29 16:24 UTC, SMillerDev requested changes
I'm guessing this was done to prevent updates from removing the plugins so this doesn't seem like a good fix.

2023-01-29 20:51 UTC, ret2libc commented
Got it, makes sense. I will work upstream to fix this.

2023-02-27 00:02 UTC, closed without merging