go 1.8.1
Homebrew/homebrew-core pull request #12201
Opened 2017-04-07 18:05 UTC by mblair

Created with `brew bump-formula-pr`.

2017-04-07 18:12 UTC, neutric requested changes

2017-04-07 18:12 UTC, neutric commented on Formula/go.rb
> -    mirror "https://fossies.org/linux/misc/go1.8.src.tar.gz"
Please update the mirror URL as if it is already valid.

2017-04-07 18:16 UTC, mblair commented on Formula/go.rb
> -    mirror "https://fossies.org/linux/misc/go1.8.src.tar.gz"
Done! I also removed the no-longer-necessary patching.

2017-04-07 18:17 UTC, neutric commented
Wow, you are fast. I was just going to point out the patches removed in #12202. :)

2017-04-07 18:30 UTC, neutric approved these changes

2017-04-07 18:52 UTC, cblecker commented
you may also need to bump the revision of the godep formula in a separate commit

2017-04-07 22:25 UTC, mblair commented
@cblecker like [so](abce495e7d2ac0ef198f59cdfa82f5c10b50d378)?

2017-04-07 22:29 UTC, cblecker commented
@mblair yup, that should pass tests when CI kicks in

2017-04-07 22:53 UTC, DomT4 commented
@ilovezfs I got fed up with `godep` and did some poking. It's hardcoding the Cellar path to `go` about a billion times because `go` itself does the same thing, which is presumably getting passed down the chain. I think if we did:

```diff
diff --git a/Formula/go.rb b/Formula/go.rb
index cacb9e4c15..b39f193c7a 100644
--- a/Formula/go.rb
+++ b/Formula/go.rb
@@ -94,6 +94,14 @@ class Go < Formula
         bin.install_symlink libexec/"bin/godoc"
       end
     end
+
+    %W[
+      #{libexec}/pkg/bootstrap/src/bootstrap/cmd/internal/obj/zbootstrap.go
+      #{libexec}/src/cmd/internal/obj/zbootstrap.go
+      #{libexec}/src/runtime/internal/sys/zversion.go
+    ].each do |file|
+      inreplace file, libexec, opt_libexec
+    end
   end
 
   def caveats; <<-EOS.undent
```
That would solve the having to bump `godep` every single time `go` gets touched. I'm pretty sure `runtime` is the one that gets imported widely, so an even smaller `inreplace` job might work.

2017-04-08 00:53 UTC, mblair commented
@DomT4 should I apply that patch to this PR?

2017-04-08 01:11 UTC, ilovezfs commented
>@DomT4 should I apply that patch to this PR?

No.

2017-04-08 01:13 UTC, DomT4 commented
It's a significant change, no point attaching it to something that people are desperate to get merged.

2017-04-08 01:19 UTC, ilovezfs commented
@DomT4 yeah I'm aware that's the cause. I think we may want to just point the relevant go variables (probably GOROOT in this case) at the opt_prefix during the `go` build. This may require some `brew` back end change as well since the opt link doesn't exist during the build currently, and attempting to create it is a sandbox violation.

2017-04-08 01:30 UTC, DomT4 commented
> (probably GOROOT in this case)

Yes, indeed. It's being hardcoded as `defaultGOROOT`.

> This may require some brew back end change as well since the opt link doesn't exist during the build currently, and attempting to create it is a sandbox violation.

Yeah, that's what I was effectively trying to avoid with this suggestion. It's something that can be implemented purely on the formula side of things rather than trying to push through likely controversial design changes to `brew` itself.

2017-04-08 01:32 UTC, ilovezfs commented
I'd rather it be fixed properly than with inreplace regardless of controversy.

2017-04-08 01:33 UTC, DomT4 commented
Alright. I'll graciously leave that one down to you 😉.

2017-04-08 01:33 UTC, ilovezfs commented
In any case, CI appears to be toast due to this Jenkinsfile pipeline stuff, so people will just need to be patient here.

2017-04-08 03:47 UTC, ilovezfs commented
@BrewTestBot test this please

2017-04-08 04:15 UTC, closed without merging

2017-04-08 04:15 UTC, ilovezfs commented
Shipped! Thanks for the PR @mblair

2017-04-09 14:00 UTC, ilovezfs commented
@DomT4 I think this works:
```
iMac-TMP:homebrew-core joe$ git diff -- Formula/go.rb
diff --git a/Formula/go.rb b/Formula/go.rb
index 3ddc8debf0..ff79f8309b 100644
--- a/Formula/go.rb
+++ b/Formula/go.rb
@@ -47,7 +47,7 @@ class Go < Formula
     ENV["GOROOT_BOOTSTRAP"] = buildpath/"gobootstrap"
 
     cd "src" do
-      ENV["GOROOT_FINAL"] = libexec
+      ENV["GOROOT_FINAL"] = opt_libexec
       ENV["GOOS"]         = "darwin"
       ENV["CGO_ENABLED"]  = "0" if build.without?("cgo")
       system "./make.bash", "--no-clean"
```
with
```
diff --git a/Library/Homebrew/formula_installer.rb b/Library/Homebrew/formula_installer.rb
index 017be51dc..fad755bdf 100644
--- a/Library/Homebrew/formula_installer.rb
+++ b/Library/Homebrew/formula_installer.rb
@@ -660,6 +660,9 @@ class FormulaInstaller
 
     Sandbox.print_sandbox_message if Sandbox.formula?(formula)
 
+    formula.prefix.mkpath
+    Keg.new(formula.prefix).optlink
+
     Utils.safe_fork do
       # Invalidate the current sudo timestamp in case a build script calls sudo
       system "/usr/bin/sudo", "-k"
@@ -687,6 +690,7 @@ class FormulaInstaller
   rescue Exception
     ignore_interrupts do
       # any exceptions must leave us with nothing installed
+      Keg.new(formula.prefix).remove_opt_record
       formula.update_head_version
       formula.prefix.rmtree if formula.prefix.directory?
       formula.rack.rmdir_if_possible
```

2017-04-09 14:10 UTC, DomT4 commented
@ilovezfs Yes, that looks like it should work. Haven't tested it but the idea looks good.

Theoretically that would possibly also allow configuring things with the prefix set to `opt_prefix` instead of `prefix`, resolving some of the complaints that Homebrew `pkgconfig` files almost always point to a versioned `Cellar` rather than a broader persistent directory.

2017-04-09 14:13 UTC, ilovezfs commented
Yes, although I think we'd want to limit that from being applied outside of the particular cases that need it otherwise invoking other versions of a formula through their full Cellar path will end up using things from the opt-linked version, which would be a shame.