sc-im 0.5.0 (new formula)
Homebrew/homebrew-core pull request #12260
Opened 2017-04-09 20:22 UTC by jez

- [x] Have you followed the [guidelines for
  contributing][guidelines]?
- [x] Have you checked that there aren't other open [pull
  requests][pulls] for the same formula update/change?
- [x] Have you built your formula locally with `brew install
  --build-from-source <formula>`, where `<formula>` is the name of the
  formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing
  `brew install <formula>`)?

[guidelines]: https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md
[pulls]: https://github.com/Homebrew/homebrew-core/pulls

- - -

One thing to note is that `sc-im` doesn't pass this check:

```
❯ brew audit --new-formula sc-im
sc-im:
  * Dependency 'ncurses' may be unnecessary as it is provided by macOS; try to build this formula without it.
  * Dependency 'ncurses' may be unnecessary as it is provided by macOS; try to build this formula without it.
Error: 2 problems in 1 formula
```

When I built it against the macOS default ncurses, there were some
visual glitches where the screen wouldn't always reflow correctly. I'm
not sure if I'm supposed to silence this error by modifying the formula
somehow, or if it's fine as it is.

2017-04-09 20:50 UTC, bfontaine commented on Formula/sc-im.rb
> +    end
You can use `system "make", "-C", "src", …` and avoid this `cd "src" do` block.

2017-04-09 21:06 UTC, jez commented on Formula/sc-im.rb
> +    end
I actually looked into what Homebrew's preference was regarding using a `cd` block vs a `-C` flag. Based on some rough grepping, it seemed like `cd` was used about twice as often as `-C` when calling `make` more than once in that directory.

I'm fine changing it, but I thought the way it's written currently was more idiomatic Homebrew and more readable.

2017-04-09 21:31 UTC, neutric requested changes

2017-04-09 21:31 UTC, neutric commented on Formula/sc-im.rb
> +  head "https://github.com/andmarti1424/sc-im.git"
This needs a `, :branch => "freeze"` appended.

2017-04-09 21:52 UTC, jez commented on Formula/sc-im.rb
> +  head "https://github.com/andmarti1424/sc-im.git"
Good catch; should be fixed now.

2017-04-09 22:33 UTC, bfontaine commented on Formula/sc-im.rb
> +    end
cc @MikeMcQuaid for thought here.

2017-04-10 00:16 UTC, jez commented
Hmm, I'm having some issues with the tests. It's saying something like "Device not configured". `brew audit sc-im` works for me locally.

I have a hunch that it's related to the fact that `scim` is designed to only be run interactively. There's no `--version` or `--help` option that just runs and quits right after.

I have two ideas:

- Are there any other formulas that are interactive-only that I could use as a reference to design a test block?
- Would it be possible to omit the test, or check instead for the existence of the binary, instead of actually running it?

2017-04-16 03:41 UTC, dunn commented
Some formulae like [`ne.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ne.rb) use `script` to fake a TTY; for providing input other formulae use `Open3`: [`euler-py.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/euler-py.rb)

2017-05-11 10:58 UTC, claui commented
@jez The `scim` binary [accepts a script from standard input](https://github.com/jez/homebrew-core/pull/1/files#diff-866c4a23cfb68fb183dbcdb1d60b94d2R20).  
To inject it, we have `Homebrew::Assertions#pipe_output`.

I have updated the test accordingly, and [double-parked a small PR](https://github.com/jez/homebrew-core/pull/1) which can be merged into this one.

2017-05-11 15:51 UTC, jez commented
Oh cool; I'll take a look at it then.

Know that I'm quite busy for the next week and a half (final exams and
graduation!) but I'll try to sneak in some time for it.
On Thu, May 11, 2017 at 6:58 AM Claudia <notifications@github.com> wrote:

> @jez <https://github.com/jez> The scim binary accepts a script from
> standard input
> <https://github.com/jez/homebrew-core/pull/1/files#diff-866c4a23cfb68fb183dbcdb1d60b94d2R20>
> .
> To inject it, we have Homebrew::Assertions#pipe_output.
>
> I have updated the test accordingly, and double-parked a small PR
> <https://github.com/jez/homebrew-core/pull/1> which can be merged into
> this one.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-core/pull/12260#issuecomment-300755609>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFSaVNzzVNppmXAY5xVGOBtc8d7RukX2ks5r4unWgaJpZM4M4I9H>
> .
>

2017-05-14 15:05 UTC, MikeMcQuaid commented on Formula/sc-im.rb
> +    end
I'm fine with either.

2017-05-17 12:37 UTC, fxcoudert commented
@BrewTestBot test this please

2017-05-17 12:38 UTC, fxcoudert commented
And 👍 to merging @claui 's PR for the test, it's exactly what we need

2017-05-30 05:33 UTC, jez commented
I'm no longer using this program. Someone who is still using sc-im might want to recreate this PR with passing tests, but for now I'm signing off.

2017-05-30 05:33 UTC, closed without merging