binutils: Ship libiberty
Homebrew/homebrew-core pull request #123201
Opened 2023-02-14 14:14 UTC by FlyGoat

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Some background:

libbfd.a shipped with binutils references symbols from libiberty. So homebrew's binutils libraries are useless without libiberty, causing `backward-cpp` failed to build.

I read #92138 where we end up concluding that libiberty shoudn't be shipped as a standalone library or as a part of GCC, but I think in this case we should really consider to ship it with binutils.

As per Debian's document page:

```
 This library shouldn't be used by other software, but unfortunately already is. There is no guaranty for a stable library API, and no shared library is provided. 
```
In reality there are some software depending on system libiberty to build.

I also invetigated how other Linux distros handle libiberty:

- Debian/Ubuntu: Ship as standalone static libiberty (https://packages.debian.org/sid/amd64/libiberty-dev/filelist)
- Fedora/RedHat: Ship headers and static libiberty with binutils (http://rpmfind.net/linux/rpm2html/search.php?query=bundled(libiberty))
- ArchLinux: Ship headers and static libiberty with binutils (https://archlinux.org/packages/core/x86_64/binutils/)
- Alpine: Ship headers and static libiberty with binutils  (https://pkgs.alpinelinux.org/contents?branch=edge&name=binutils&arch=x86&repo=main)

It makes sense to ship libiberty with binutils.

2023-02-14 14:42 UTC, SMillerDev requested changes
If GCC developers say it shouldn't be shipped I don't think we should ship it because other distros did not heed the warning.

2023-02-14 19:18 UTC, FlyGoat commented
Well the reality is applications linking statically to libbfd.a will need libiberty at the same version of binutils.

Bundling libiberty with other softwares (in my case it's backward-cpp) will cause even bigger issues due to ABI instability of libiberty. That's why other distros choose to ship libiberty as a static library.

If I interpreted libiberty's document properly https://gcc.gnu.org/onlinedocs/libiberty/Using.html#Using , provide a system libiberty is not discouraged and it is proven useful.

2023-02-15 09:53 UTC, carlocab commented
Do you have any other examples of applications that link statically with `libbfd`? Why does backward-cpp need to link with `libbfd`?

2023-02-15 13:00 UTC, fxcoudert commented
We're going to have a problem because a lot of GNU projects contain `libiberty`: binutils (and we have several binutils variants in homebrew), gcc (we also have several), etc. In addition to following upstream advice, shipping libiberty creates potential conflicts between formulas.

Have you considered reporting the issue to binutils, so that they include the necessary symbols from libiberty inside libbfd? That would make the most sense, if they consider that libbfd is a static library that is shipped by default.

2023-02-15 13:08 UTC, FlyGoat commented
> Do you have any other examples of applications that link statically with `libbfd`? Why does backward-cpp need to link with `libbfd`?

Don't have other example for now but libbfd is a part of binutils public API.
However it's API isn't stable so it's usually provided as a static library.

2023-02-15 13:15 UTC, FlyGoat commented
> We're going to have a problem because a lot of GNU projects contain `libiberty`: binutils (and we have several binutils variants in homebrew), gcc (we also have several), etc. In addition to following upstream advice, shipping libiberty creates potential conflicts between formulas.
> 
> Have you considered reporting the issue to binutils, so that they include the necessary symbols from libiberty inside libbfd? That would make the most sense, if they consider that libbfd is a static library that is shipped by default.

Including libiberty symbols to libbfd can cause problems for applications that have bundled libiberty.

binutils's libiberty is only shipped as a static library, so if we can make sure that there is only one libiberty in system then everything is fine. Other GNU tools are free to choose over bundled libiberty or system libiberty. Other distros are doing so for years.

Given that binutils is not necessarily a part of homebrew's toolchain perhaps ship a static libiberty as a standalone package makes more sense.

2023-03-16 14:18 UTC, closed without merging