Libsndfile-cmake
Homebrew/homebrew-core pull request #123663
Opened 2023-02-19 08:05 UTC by FtZPetruska

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Switch the buildsystem from autotools to CMake.

Doing this installs CMake config/targets so downstream projects can consume the library more easily without depending on pkg-config.

2023-02-19 14:25 UTC, SMillerDev requested changes
I think that'll be pretty disruptive for downstream projects using pkg-config. Is there a way to provide both?

2023-02-19 16:24 UTC, FtZPetruska commented
> I think that'll be pretty disruptive for downstream projects using pkg-config. Is there a way to provide both?

Yes! The .pc file is still installed using CMake: `"-DINSTALL_PKGCONFIG_MODULE=ON"`. Only the `libdir` field is changed but remains functionally identical:
- Currently
```
prefix=/opt/homebrew/Cellar/libsndfile/1.2.0
exec_prefix=${prefix}
libdir=/opt/homebrew/Cellar/libsndfile/1.2.0/lib
includedir=${prefix}/include

Name: sndfile
Description: A library for reading and writing audio files
Requires:
Requires.private: flac ogg vorbis vorbisenc opus libmpg123
Version: 1.2.0
Libs: -L${libdir} -lsndfile
Libs.private: -lmp3lame
Cflags: -I${includedir}
```
- With this PR
```
prefix=/opt/homebrew/Cellar/libsndfile/1.2.0_1
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: sndfile
Description: A library for reading and writing audio files
Requires:
Requires.private: flac ogg vorbis vorbisenc opus libmpg123
Version: 1.2.0
Libs: -L${libdir} -lsndfile
Libs.private: -lmp3lame
Cflags: -I${includedir}
```

2023-02-25 03:25 UTC, p-linnane commented
Rerunning now that `qt` has been rebottled on Big Sur Intel.

2023-02-25 14:56 UTC, SMillerDev approved these changes

2023-02-25 15:12 UTC, closed without merging