pass 1.7.1
Homebrew/homebrew-core pull request #12381
Opened 2017-04-13 10:26 UTC by zx2c4

This is a trivial version bump.

2017-04-21 22:24 UTC, ClashTheBunny commented
The checks seemed like they failed because GitHub didn't respond.  Wasn't GitHub having issues then?  Could we just run this again?

2017-04-23 14:20 UTC, fxcoudert requested changes

2017-04-23 14:20 UTC, fxcoudert commented on Formula/pass.rb
> -    rebuild 1
Please do not touch the `bottle` block

2017-05-07 01:43 UTC, closed without merging

2017-05-07 01:43 UTC, ilovezfs commented
@zx2c4 Thanks for your contribution to Homebrew