Add formula to install immortal
Homebrew/homebrew-core pull request #12388
Opened 2017-04-13 12:37 UTC by rollbrettler

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-19 15:24 UTC, nbari requested changes

2017-04-19 15:24 UTC, nbari commented on Formula/immortal.rb
> +      :tag => "0.13.1",
new version 0.13.2

2017-04-19 15:24 UTC, nbari commented on Formula/immortal.rb
> +      :revision => "8ec87531e9f5d2ce1ec64e76c8bbae5dc58feecf"
new revision: 7dbcf52fa0d68c11051d5f2b621202aded3242fe

2017-04-27 08:09 UTC, fxcoudert commented
Thanks @rollbrettler for your contribution to Homebrew!

2017-04-27 08:09 UTC, closed without merging