Historian formula
Homebrew/homebrew-core pull request #12407
Opened 2017-04-13 20:20 UTC by kudakeru

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-13 20:41 UTC, bfontaine requested changes

2017-04-13 20:41 UTC, bfontaine commented on Formula/historian.rb
> +  url "https://files.jakemcknight.com/historian-0.1.tar.gz"
We need an official/tagged release from upstream here.

2017-04-13 20:43 UTC, bfontaine commented on Formula/historian.rb
> +    system "/usr/local/bin/hist", "version"
Don’t hardcode the path; some people don’t have Homebrew under `/usr/local`. Use `system bin/"hist"`. Also, can’t we write a test that does something more substantial than that? You could create a dummy `.bash_history` then use `hist` to import it.

2017-04-15 04:12 UTC, kudakeru commented
@bfontaine Thanks for the suggestions. The formula now uses the tagged release from its repo, and has a much better test.

2017-04-15 12:48 UTC, bfontaine commented
Thanks! However you can’t add a test file to Homebrew like so. You have to write it in the test block, like so:
```ruby
test do
  (testpath/".bash_history").write <<-EOS.undent
    your file
    content
    goes here
  EOS

  # ... your test ...
end
```

2017-04-15 21:47 UTC, bfontaine approved these changes

2017-04-15 21:48 UTC, bfontaine commented on .bash_history
> +brew update
Please remove this whole `.bash_history` file; it’s not needed.

2017-04-16 19:00 UTC, kudakeru commented on .bash_history
> +brew update
Ah, my mistake. Fixed now.

2017-04-16 19:18 UTC, bfontaine commented
@BrewTestBot test this please.

2017-04-19 01:28 UTC, tdsmith commented
Thanks @kudakeru for your contribution, and thanks @bfontaine for shepherding it through!

2017-04-19 01:28 UTC, closed without merging