nicotine-plus 1.4.1 (new formula)
Homebrew/homebrew-core pull request #12400
Opened 2017-04-13 16:54 UTC by ibrokemypie

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-20 04:37 UTC, ibrokemypie commented
Been a week, any update on this? Anything I need to do?

2017-04-20 10:06 UTC, bfontaine requested changes

2017-04-20 10:06 UTC, bfontaine commented on formula/nicotine-plus.rb
> +  desc "is a graphical client for the SoulSeek peer-to-peer system."
Please don’t start the description with `is`: `"Graphical client for the SoulSeek peer-to-peer system"`.

2017-04-20 10:06 UTC, bfontaine commented on formula/nicotine-plus.rb
> +  depends_on :python if MacOS.version <= :snow_leopard
Please leave a blank line above this one.

2017-04-20 10:07 UTC, bfontaine commented on formula/nicotine-plus.rb
> +  depends_on "miniupnpc" => :optional
Why would someone not build with these dependencies?

2017-04-20 23:28 UTC, ibrokemypie commented on formula/nicotine-plus.rb
> +  depends_on "miniupnpc" => :optional
If they simply do not need them it reduces the bloat

2017-04-23 06:43 UTC, ibrokemypie commented on formula/nicotine-plus.rb
> +  depends_on "miniupnpc" => :optional
would you like me to make them recommended or required?

2017-04-29 00:45 UTC, dunn commented on formula/nicotine-plus.rb
> +    system "#{bin}/nicotine", "--help"
Is it possible to have the tests check more of the functionality?

2017-04-29 03:02 UTC, ibrokemypie commented on formula/nicotine-plus.rb
> +    system "#{bin}/nicotine", "--help"
no really sure what else I can test, similarly to the qmmp one, this one spawns a gtk window with any other options, so will always fail

2017-04-30 16:43 UTC, dunn commented
The bottle isn't building since you added this as `formula/nicotine-plus.rb` instead of `Formula/nicotine-plus.rb` (notice the case difference).

Are you able to fix that on your end?

2017-04-30 16:52 UTC, ilovezfs commented
@ibrokemypie I have fixed it for you. Just so we have a better idea of how this happened: is your local directory actually named `formula` not `Formula`?

2017-04-30 17:11 UTC, closed without merging