nginx 1.12.0
Homebrew/homebrew-core pull request #12416
Opened 2017-04-14 04:34 UTC by JLHwung

Created with `brew bump-formula-pr`.

2017-04-25 16:43 UTC, bfontaine requested changes

2017-04-25 16:43 UTC, bfontaine commented on Formula/nginx.rb
>    end
Please remove this whole block; `devel` is useless if it’s the same version as `stable`.

2017-04-26 03:13 UTC, JLHwung commented on Formula/nginx.rb
>    end
@ilovezfs Will there be any side effects if the whole `devel` block is removed?

2017-04-26 03:16 UTC, JLHwung commented on Formula/nginx.rb
>    end
Thank you for your helpful advice. However, as nginx 1.13.0 as released, I prefer to update to 1.13.0 for devel.

2017-04-26 07:39 UTC, bfontaine approved these changes

2017-04-26 13:07 UTC, closed without merging

2017-04-26 13:09 UTC, JCount commented
@JLHwung Thank you for your contribution to Homebrew! 🏆

2017-04-26 15:21 UTC, JLHwung commented
You are very welcome.