fstar: fix issue with path to standard library
Homebrew/homebrew-core pull request #12447
Opened 2017-04-15 00:23 UTC by s-zanella

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

- Fixes an issue where fstar cannot discover the path to its standard library (https://github.com/FStarLang/FStar/issues/951)
- Updated description to match the one in homepage
- Bumped to revision 1
- Updated test not to depend on Z3 (which is only recommended)

2017-04-16 12:39 UTC, bfontaine requested changes

2017-04-16 12:39 UTC, bfontaine commented on Formula/fstar.rb
> +    system "echo '#!/bin/sh\n#{bin}/_fstar.exe --fstar_home #{prefix} $@\n' >fstar.exe"
Use Ruby instead:
```ruby
(bin/"fstar.exe").write <<-EOS.undent
  #!/bin/sh
  ....
EOS
```

2017-04-16 18:21 UTC, s-zanella commented on Formula/fstar.rb
> +    system "echo '#!/bin/sh\n#{bin}/_fstar.exe --fstar_home #{prefix} $@\n' >fstar.exe"
Thanks! Fixed it to use Ruby instead.

2017-04-16 19:16 UTC, bfontaine commented on Formula/fstar.rb
> +    bin.install "bin/fstar.exe" => "_fstar.exe"
Does it make sense to keep this under `bin/`?

2017-04-16 19:16 UTC, bfontaine approved these changes

2017-04-16 20:37 UTC, s-zanella commented on Formula/fstar.rb
> +    bin.install "bin/fstar.exe" => "_fstar.exe"
That keeps it in `bin/`, doesn't it? 
I end up with two files in `#{bin}`: the fstar executable in `#{bin}/_fstar.exe` and the script that the formula writes to `#{bin}/fstar.exe`.

2017-04-16 20:55 UTC, bfontaine commented on Formula/fstar.rb
> +    bin.install "bin/fstar.exe" => "_fstar.exe"
Yep; I mean is there a reason to keep `_fstar.exe` in `bin/` if we already have `fstar.exe`? We could put it under e.g. `libexec/` instead.

2017-04-16 21:23 UTC, s-zanella commented on Formula/fstar.rb
> +    bin.install "bin/fstar.exe" => "_fstar.exe"
Sorry, I misunderstood your first comment.
I updated the formula to put the `fstar.exe` executable in `libexec/bin/fstar.exe` and the wrapper script in `bin/fstar.exe`.

2017-04-17 10:51 UTC, bfontaine commented
Thank you for your contribution to Homebrew, @s-zanella! 🎉

2017-04-17 10:52 UTC, closed without merging

2017-04-17 20:20 UTC, beurdouche commented
@s-zanella Great ! Thanks Santiago ;)