`bandcamp-dl 0.0.7-09 (new formula)
Homebrew/homebrew-core pull request #12443
Opened 2017-04-14 17:10 UTC by ibrokemypie

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-14 20:48 UTC, bfontaine requested changes

2017-04-14 20:48 UTC, bfontaine commented on Formula/bandcamp-dl.rb
> +    system "#{bin}/bandcamp-dl", "--version"
Please write a test that does something more substantial than printing the version. You could e.g. download a small album then assert the files exist.

2017-04-15 02:00 UTC, ibrokemypie commented on Formula/bandcamp-dl.rb
> +    system "#{bin}/bandcamp-dl", "--version"
Have pushed new tests that make sure both artist+album and url parsing work correctly, and the files exist.

2017-04-15 12:50 UTC, bfontaine commented on Formula/bandcamp-dl.rb
> +    system "[", "-e", "iamsleepless/rivulets/01\ -\ rivulets.mp3", "]"
Please use Ruby instead:
```ruby
assert File.exist?("iamsleepless/rivulets/01 - rivulets.mp3")
```

2017-04-20 23:27 UTC, ibrokemypie commented on Formula/bandcamp-dl.rb
> +    system "[", "-e", "iamsleepless/rivulets/01\ -\ rivulets.mp3", "]"
have done

2017-04-21 18:33 UTC, bfontaine approved these changes

2017-04-27 20:04 UTC, fxcoudert commented
The version was incorrectly detected as `09` instead of `0.0.7-09` (which is, I have to say, a weird version scheme).

2017-04-27 23:03 UTC, ibrokemypie commented
has been fixed

2017-04-28 11:20 UTC, fxcoudert commented
Thanks @ibrokemypie for your contribution to Homebrew! We look forward to other pull requests from you in the future :)

2017-04-28 11:20 UTC, closed without merging