x3270: Make X11 dependency optional
Homebrew/homebrew-core pull request #12508
Opened 2017-04-16 19:09 UTC by ronmrdechai

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-17 14:28 UTC, MikeMcQuaid requested changes

2017-04-17 14:28 UTC, MikeMcQuaid commented on Formula/x3270.rb
> +  depends_on :x11 => :recommended
This should be `:optional`

2017-04-21 17:45 UTC, MikeMcQuaid commented on Formula/x3270.rb
> +  option "without-x11", "Exclude x3270 (X11-based version)"
Probably wants flipped to `with-x11` now, sorry, should have noted that last time.

2017-04-21 18:56 UTC, ronmrdechai commented on Formula/x3270.rb
> +  option "without-x11", "Exclude x3270 (X11-based version)"
If do that a build without arguments will fail (`brew install x3270`), an argument must be supplied. Is that okay?

2017-04-22 11:18 UTC, MikeMcQuaid commented on Formula/x3270.rb
> +  option "without-x11", "Exclude x3270 (X11-based version)"
> Also, the name should probably be with-x3270 then, and if so, how do I bind a dependency to an option?

You can't, unfortunately. This is a limitation of our dependency system.

Go for:
`option "with-x11", "Include x3270 (X11-based version)"`

2017-04-22 14:29 UTC, MikeMcQuaid commented
Install seems to be failing now: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/427/version=sierra/testReport/junit/brew-test-bot/sierra/install_x3270/

2017-04-22 14:51 UTC, ronmrdechai commented
Yes that's the issue with making X11 opt-in. The configure script has nothing to build (actually the issue is with a missing X11 dependency, but never mind that for now), so I'm not really sure what it's doing.
Making one of the build options opt-out and the others opt-in fixes this. This is more of an issue with the way this package's configure script works than anything.
Enabling X11 by default seems like the right thing to do as the package's name is x3270 and the X-based binary is named `x3270`, other binaries are named `c3270`, `s3280`, etc. What do you think?

2017-04-22 15:00 UTC, MikeMcQuaid commented
Ah, I see now what you meant earlier, sorry! I think enabling everything that doesn't require a dependency/requirement (i.e. everything except X11) would be good if possible otherwise picking either the console or ncurses one would be good. Thoughts?

2017-04-22 15:17 UTC, ronmrdechai commented
Seems right to me.

2017-04-22 15:29 UTC, MikeMcQuaid commented
Will need to adjust the `test do` accordingly for a default binary. Also, squash commits by running `brew update; git checkout $YOUR_BRANCH; git rebase --interactive origin/master` and then mark each commit other than the first as `squash` or `fixup` then `git push -f`. Thanks!

2017-04-22 15:41 UTC, ronmrdechai commented
Done, thank you.

2017-04-23 20:00 UTC, MikeMcQuaid approved these changes

2017-04-23 20:05 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-04-23 20:06 UTC, closed without merging