qcli 0.8 (new formula)
Homebrew/homebrew-core pull request #12527
Opened 2017-04-17 14:05 UTC by dericed

- [ X ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ X ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-17 14:26 UTC, bfontaine requested changes

2017-04-17 14:26 UTC, bfontaine commented on Formula/qcli.rb
> +    ENV["PATH"] = "#{path}:#{HOMEBREW_PREFIX}/bin"
Why do you need to modify the `PATH`?

2017-04-17 14:26 UTC, bfontaine commented on Formula/qcli.rb
> +      cd "../qctools-cli"
Please use `cd do` blocks instead of going back and forth.

2017-04-17 14:26 UTC, bfontaine commented on Formula/qcli.rb
> +  depends_on "ffmpeg"
Is `ffmpeg` needed outside of the test?

2017-04-17 14:28 UTC, dericed commented on Formula/qcli.rb
> +  depends_on "ffmpeg"
Yes, it builds off ffmpeg.

2017-04-17 14:32 UTC, dericed commented on Formula/qcli.rb
> +      cd "../qctools-cli"
I simplified the cd'ing, rebased to squash, and push --force.

2017-04-17 14:34 UTC, dericed commented on Formula/qcli.rb
> +    ENV["PATH"] = "#{path}:#{HOMEBREW_PREFIX}/bin"
Sorry, this may have been left in from testing. I removed the 2 path setting lines and it still seems to build okay.

2017-04-17 14:35 UTC, dericed commented
Thanks. I've updated the patch according to @bfontaine's comments. It's ready for another look.

2017-04-29 00:28 UTC, dunn commented on Formula/qcli.rb
> +  depends_on "ffmpeg"
If it's not needed at runtime, you can do `depends_on "ffmpeg" => :build`.

2017-04-29 00:29 UTC, dunn commented on Formula/qcli.rb
> +  desc "report audiovisual metrics via libavfilter"
Could you capitalize `Report` please?

2017-04-29 13:42 UTC, bfontaine approved these changes

2017-05-02 10:02 UTC, fxcoudert commented
Thanks @dericed for your contribution to Homebrew!

2017-05-02 10:03 UTC, closed without merging