freetype: fails with clang build 1000
Homebrew/homebrew-core pull request #125422
Opened 2023-03-12 02:01 UTC by whitslack

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Freetype fails to build with Apple Clang 10.0.0 (build 1000) because the compiler doesn't understand `attribute ((fallthrough))`. Adding a suitable `fails_with` block to the formula allows Homebrew to select another compiler to build Freetype successfully.

2023-03-12 14:44 UTC, gromgit commented on Formula/freetype.rb
> +    build 1000
```suggestion
    build 1100
```
`freetype` build fails on Mojave too, but succeeds on Catalina, so might as well `fails_with` on Mojave clang.

2023-03-12 14:45 UTC, gromgit requested changes
I test-built `freetype` on Mojave and Catalina, and found the same error in the former, so might as well cover that too.

2023-03-12 22:15 UTC, Bo98 commented
Looks like it should work fine with Clang 9 though.

I think we should apply these two patches instead:

https://gitlab.freedesktop.org/freetype/freetype/-/commit/2257f9abf6e12daf7c3e1bfe28fa88de85e45785
https://gitlab.freedesktop.org/freetype/freetype/-/commit/d874ffa96ccad7dd122cdc369a284d171e221809

2023-03-12 22:24 UTC, whitslack commented
> I think we should apply these two patches instead

LGTM. That's getting well outside my familiarity with Homebrew and Ruby, though, so someone else would have to implement that.

2023-03-15 15:11 UTC, ZhongRuoyu commented
Huh. After #124287, another `freetype` build coincides with a GitHub registry accident.

2023-03-17 08:43 UTC, ZhongRuoyu approved these changes
Merging as all CI failures were due to the registry accident.

2023-03-17 08:44 UTC, merged