Port mongodb@2.6 from versions repo
Homebrew/homebrew-core pull request #12584
Opened 2017-04-18 02:54 UTC by jeffheifetz

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-18 02:54 UTC, jeffheifetz commented
Ported https://github.com/Homebrew/homebrew-versions/pull/1510

2017-04-18 06:47 UTC, MikeMcQuaid commented on Formula/mongodb@2.6.rb
> +  option "with-boost", "Compile using installed boost, not the version shipped with mongodb"
Let's remove this option.

2017-04-18 06:47 UTC, MikeMcQuaid commented on Formula/mongodb@2.6.rb
> +  depends_on "openssl" => :optional
What happens if this isn't enabled?

2017-04-18 15:06 UTC, jeffheifetz commented on Formula/mongodb@2.6.rb
> +  depends_on "openssl" => :optional
I honestly don't know

2017-04-18 16:47 UTC, jeffheifetz commented on Formula/mongodb@2.6.rb
> +  depends_on "openssl" => :optional
It still worked when I tested it locally

2017-04-20 16:16 UTC, MikeMcQuaid requested changes

2017-04-20 16:16 UTC, MikeMcQuaid commented on Formula/mongodb@2.6.rb
> +  depends_on "openssl" => :optional
Let's make this always-on (remove the `:optional`).

2017-04-20 16:16 UTC, MikeMcQuaid commented on Formula/mongodb@2.6.rb
> +  depends_on "boost" => :optional
Remove this line.

2017-04-20 16:16 UTC, MikeMcQuaid commented
Couple more changes and this should be good to 🚢

2017-04-24 02:57 UTC, jeffheifetz commented on Formula/mongodb@2.6.rb
> +  depends_on "boost" => :optional
Sorry should have removed this the first time

2017-04-24 02:58 UTC, jeffheifetz commented
Thanks so much @MikeMcQuaid

2017-04-24 07:54 UTC, MikeMcQuaid approved these changes

2017-04-24 09:23 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-04-24 09:24 UTC, closed without merging