Install zsh-completions formula in the standard hombrew zsh_completio…
Homebrew/homebrew-core pull request #126586
Opened 2023-03-24 22:15 UTC by griano

…ns dir

The standard zsh completion folder if $(brew --prefix)/share/zsh/site-functions. Therfefore it is prefferable to install using zsh_completion.install See https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh

- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2023-03-25 04:51 UTC, carlocab requested changes
I agree that this is a better place to put it, but making this change now will break the start-up scripts of users who use `/bin/zsh`.

2023-03-25 18:36 UTC, griano commented
> I agree that this is a better place to put it, but making this change now will break the start-up scripts of users who use `/bin/zsh`.

I am not sure what you mean. These are the standard `$fpath`s:
```bash
$ /bin/zsh -f -c 'print -l $fpath'
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/5.8.1/functions
```
This formula is currently installing files in none of these, but rather in
```bash
$(brew --prefix)/share/zsh-completions
```
So, for completions to work, the user needs to modify ``.zshrc`` either way.
Arguable current users that have modified the profile according to old instruction would have to change it.

What about if we copy to both places?

2023-03-25 18:48 UTC, carlocab commented
If I am on an M1 Mac, and I previously installed this formula, then I would have added something like
```
/opt/homebrew/share/zsh-completions
```
to my `FPATH`.

With this change, I will need to adjust my `.zshrc` (or `.zprofile`, etc) to add
```
/opt/homebrew/share/zsh/site-functions
```
to my `FPATH` instead. Without this change, my `.zshrc` is now broken by this PR.

2023-03-26 06:57 UTC, cho-m commented
Also, `zsh-completions` can have conflicts with completions already provided by formulae.

From quick glance, one example is `tmuxinator` (https://github.com/zsh-users/zsh-completions/blob/0.34.0/src/_tmuxinator):
https://github.com/Homebrew/homebrew-core/blob/58282e8dbef6d79d6ad08a90dd9b7b854047fa3b/Formula/tmuxinator.rb#L54

Not too unusual when upstream project adds completion support on a new release.

This can cause users more issues if the formula fails to link after upgrade. 

By using separate locations, users can choose to prioritize the 3rd party completions in `$(brew --prefix)/share/zsh-completions` or 1st party completions in `$(brew --prefix)/share/zsh/site-functions`.

2023-03-26 16:50 UTC, closed without merging