flint-checker 0.0.4 (new formula)
Homebrew/homebrew-core pull request #12701
Opened 2017-04-20 20:31 UTC by mvitz

Add a new formula to install flint (https://github.com/pengwynn/flint).

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This formula name conflicts with `homebrew/science/flint` but I'm not sure which other name to choose.

2017-04-25 08:10 UTC, bfontaine requested changes

2017-04-25 08:10 UTC, bfontaine commented on Formula/flint.rb
> +    assert_match version.to_s, shell_output("#{bin}/flint --version", 0)
Please write a test that does something more substantial than e.g. `--version` or `--help`.

2017-04-25 20:32 UTC, mvitz commented on Formula/flint.rb
> +    assert_match version.to_s, shell_output("#{bin}/flint --version", 0)
I added tests for error, warning and success case.

2017-04-26 07:40 UTC, bfontaine commented on Formula/flint.rb
> +    assert_match version.to_s, shell_output("#{bin}/flint --version", 0)
Thanks!

2017-04-26 07:40 UTC, bfontaine approved these changes

2017-04-28 10:32 UTC, fxcoudert commented
`  * Formula name conflicts with homebrew/science/flint`

2017-04-28 10:36 UTC, mvitz commented
I mentioned this in my first comment ;-)

Is there any strategy to resolve such name conflicts in a generic way? I have no idea which name to choose.

2017-04-28 11:48 UTC, fxcoudert commented
There is a strategy: if the name is taken, you need another one. I suggest `flint-checker`, for example.

2017-04-28 11:49 UTC, mvitz commented
Argh. Good idea. Sometimes the solution is to near to see.

Have the commit messages and the PR title to be updated as well?

2017-04-28 12:01 UTC, fxcoudert commented
PR title, formula file name and class name, commit message. And please squash all commits into a single one.

2017-04-29 19:13 UTC, mvitz commented
Renamed everything to flint-checker.

2017-05-02 09:53 UTC, fxcoudert commented
Thanks @mvitz for the pull request!

2017-05-02 09:53 UTC, closed without merging