Update frege-reply sha256
Homebrew/homebrew-core pull request #12714
Opened 2017-04-21 06:55 UTC by akilegaspi

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-21 08:57 UTC, neutric commented
Thanks for your first contribution to Homebrew, @akilegaspi! We'll however need to know why the file has changed before taking further action. Has the fact that the checksum changed been reported upstream yet? If not, please do so, and post a link to the issue here.

2017-04-21 11:41 UTC, neutric commented
Filed an [issue](https://github.com/Frege/frege-repl/issues/51) upstream.

2017-04-22 14:53 UTC, akilegaspi commented
Hi @neutric, I haven't actually reported it upstream but I just noticed that I wasn't able to install the frege-repl properly so I decided to double check if it were really a file change or not.

2017-04-24 03:29 UTC, akilegaspi commented
Hi @neutric, I just checked out the commits since the release of the package and I realized that Frege REPL is actually a snapshot of the master every compile so it is reasonable that the Frege REPL's SHA256 will change because there was a new merge to master on April 18, 2017.

2017-04-24 06:50 UTC, neutric commented
And updating the snapshot in place / reusing the tag is not good as it leads to breakage for everyone relying on checksums.

2017-05-01 05:25 UTC, neutric commented
Upstream [confirmed the change](https://github.com/Frege/frege-repl/issues/51#issuecomment-298257943).

2017-05-01 06:33 UTC, neutric commented on Formula/frege-repl.rb
> +  sha256 "2ca5f13bc5efaf8515381e8cdf99b4d4017264a462a30366a873cb54cc4f4640"
Please add `revision 1` on a new line right underneath `sha256` and then this is good to go.

2017-05-01 06:34 UTC, neutric requested changes

2017-05-01 06:34 UTC, neutric commented on Formula/frege-repl.rb
> +  sha256 "2ca5f13bc5efaf8515381e8cdf99b4d4017264a462a30366a873cb54cc4f4640"
Please add `revision 1` on a new line right underneath `sha256` and then this is good to go.

2017-05-02 09:55 UTC, merged

2017-05-02 09:55 UTC, fxcoudert commented
Thanks @akilegaspi for your contribution to Homebrew!