update kafkacat to 1.3.1
Homebrew/homebrew-core pull request #12713
Opened 2017-04-21 06:54 UTC by yannick

has a few new features (e.g. timestamps)

2017-04-21 08:48 UTC, neutric requested changes

2017-04-21 08:48 UTC, neutric commented on Formula/kafkacat.rb
> +
Please remove the above empty line.

2017-04-21 09:47 UTC, neutric commented
And while you are at it, please squash the commits and change the commit topic to `kafkacat 1.3.1`. Thanks!

2017-04-22 07:22 UTC, yannick commented
@neutric done

2017-04-22 08:11 UTC, closed without merging

2017-04-22 08:12 UTC, neutric commented
@yannick Awesome, thanks for your contribution to Homebrew! 🍌