Add C14 formula
Homebrew/homebrew-core pull request #12729
Opened 2017-04-21 15:51 UTC by edouardb

Add Online [C14](https://www.online.net/en/c14) [CLI](github.com/online-net/c14-cli) formula

2017-04-21 15:51 UTC, Solvik commented
👍

2017-04-23 10:41 UTC, fxcoudert requested changes

2017-04-23 10:41 UTC, fxcoudert commented on Formula/c14.rb
> +class C14 < Formula
Given the project name, the formula should be `c14-cli`

2017-04-23 10:41 UTC, fxcoudert commented on Formula/c14.rb
> +  end
Remove the `bottle` block, it will be added when merging.

2017-04-26 01:51 UTC, DomT4 commented on Formula/c14-cli.rb
> +    system "go", "build", "-o", "#{bin}/c14", "-v", "-ldflags", "-X  github.com/online-net/c14-cli/pkg/version.GITCOMMIT=homebrew", "github.com/online-net/c14-cli/cmd/c14/"
[This kind of style](https://github.com/Homebrew/homebrew-core/blob/0c14c6c7685c44e8771b1d3f2732cccb66dcfd75/Formula/wellington.rb#L37-L39) is a nicer format to read than one extremely long line FWIW.

2017-04-27 15:32 UTC, DomT4 approved these changes

2017-05-02 09:54 UTC, fxcoudert approved these changes

2017-05-02 09:59 UTC, fxcoudert commented
Thanks @edouardb for your contribution to Homebrew!

2017-05-02 09:59 UTC, closed without merging