audacious 3.8.2 (new formula)
Homebrew/homebrew-core pull request #12771
Opened 2017-04-22 16:46 UTC by ibrokemypie

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-22 19:35 UTC, bfontaine requested changes

2017-04-22 19:35 UTC, bfontaine commented on Formula/audacious.rb
> +    system "false"
Please write a test.

2017-04-22 19:35 UTC, bfontaine commented on Formula/audacious.rb
> +      ENV.prepend "PKG_CONFIG_PATH", "#{lib}/pkgconfig:"
Use `ENV.prepend_path "PKG_CONFIG_PATH", "#{lib}/pkgconfig"` instead.

2017-04-26 11:17 UTC, ibrokemypie commented
any ideas why head wont build? seems like the same environment variables arent being set. I opened a thread with more detail over here https://discourse.brew.sh/t/formula-fails-with-head-but-succeeds-with-the-same-content-without-head/718/4

2017-04-26 16:01 UTC, bfontaine requested changes

2017-04-26 16:01 UTC, bfontaine commented on Formula/audacious.rb
> +    system "true"
You can remove this line now.

2017-04-26 16:01 UTC, bfontaine commented on Formula/audacious.rb
> +  option "with-app", "Build .app"
We don’t build `.app` files in Homebrew. Use Homebrew Cask for that.

2017-04-27 01:14 UTC, ibrokemypie commented on Formula/audacious.rb
> +  option "with-app", "Build .app"
cask does not support building from source, which is the only options as there are no .apps provided from upstream

2017-04-27 08:13 UTC, bfontaine commented on Formula/audacious.rb
> +  option "with-app", "Build .app"
True. Still, please remove this option. Quoting from our ["Acceptable Formulae" guidelines](http://docs.brew.sh/Acceptable-Formulae.html):

> Don’t make your formula build an .app (native macOS Application); we don’t want those things in Homebrew (but Homebrew Cask does). Make it build a command-line tool or a library.

2017-05-16 21:45 UTC, fxcoudert commented
Description says *“based on GTK+”* but it's actually built with Qt?

2017-05-17 00:18 UTC, ibrokemypie commented
By default and originally it is a GTK app, however the QT build works better on macOS, which is why it builds with QT in this formula

2017-05-17 09:06 UTC, bfontaine approved these changes

2017-05-17 10:18 UTC, closed without merging

2017-05-17 10:19 UTC, fxcoudert commented
Thanks @ibrokemypie for the pull request, this has now been committed!

2017-05-23 14:19 UTC, ilovezfs commented
The test doesn't work, and hangs until the test block itself times out after 5 minutes, and even then a process is left running permanently. (I just manually killed more than 12 of them on the CI nodes.)

It seems the test never worked including in the original CI (https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1478/version=sierra/testReport/junit/brew-test-bot/sierra/test_audacious/).

As a stop-gap I'm at least temporarily switching this over to a simple test in https://github.com/Homebrew/homebrew-core/pull/13852 rather than removing the formula, but it would be good to get a non-trivial test working at some point.