ansible-lint: add package formula
Homebrew/homebrew-core pull request #12806
Opened 2017-04-23 21:20 UTC by Nklya

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This PR adds ansible-lint package formula.
ansible-lint checks playbooks for practices and behaviour that could potentially be improved.
Repository: https://github.com/willthames/ansible-lint

-----
Previously, i tried to add ansible-lint into ansible package, but it was rejected, so i made separate package. https://github.com/Homebrew/homebrew-core/pull/12197

2017-04-25 10:59 UTC, tgagor commented
+1 for this work

2017-04-25 12:25 UTC, bfontaine requested changes

2017-04-25 12:25 UTC, bfontaine commented on Formula/ansible-lint.rb
> +    system "#{bin}/ansible-lint", "--version"
Please write a test that does something more substantial than e.g. `--version` or `--help`. You could write a simple playbook and check it for errors. Please ask if you need help.

2017-04-25 17:32 UTC, bfontaine commented on Formula/ansible-lint.rb
> +    system bin/"ansible-lint", '-v',testpath/"playbook.yml"
Please use double-quotes everywhere: `system bin/"ansible-lint", "-v", testpath/"playbook.yml"`

2017-04-25 17:38 UTC, Nklya commented
I've add tests and fix quotes. 
Actually, "-v" option is not needed.

2017-04-26 07:41 UTC, bfontaine approved these changes

2017-04-28 10:33 UTC, fxcoudert commented
Thanks @Nklya for contributing this new formula to Homebrew! We look forward to seeing other pull requests from you :)

2017-04-28 10:33 UTC, closed without merging

2017-04-28 11:11 UTC, Nklya commented
Thanks @bfontaine and @fxcoudert for reviewing and approval.