Add qmmp
Homebrew/homebrew-core pull request #12830
Opened 2017-04-24 14:40 UTC by ibrokemypie

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-25 08:09 UTC, bfontaine requested changes

2017-04-25 08:09 UTC, bfontaine commented on Formula/qmmp.rb
> +  end
Use `head "http://svn.code.sf.net/p/qmmp-dev/code/branches/qmmp-1.2/"` at the top of the file instead.

2017-04-29 00:47 UTC, dunn commented on Formula/qmmp.rb
> +    system bin/"qmmp", "--version"
It'd be nice to have a test that checks more of the program's functionality.

2017-04-29 01:28 UTC, ibrokemypie commented on Formula/qmmp.rb
> +    system bin/"qmmp", "--version"
at the moment it seems that all other commands require spawning a qt window, which will always fail on the buildbot

2017-04-29 02:18 UTC, dunn commented on Formula/qmmp.rb
> +    system bin/"qmmp", "--version"
Gotcha, thanks!

2017-04-29 02:28 UTC, dunn commented
Merged as 5f7c78e540c77475615913e193351e78227c49d2.

2017-04-29 02:28 UTC, closed without merging