mono-libgdiplus 4.2
Homebrew/homebrew-core pull request #12862
Opened 2017-04-25 12:11 UTC by qmfrederik

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

libgdiplus is the library used by Mono for its graphics. It is a missing dependency for the Mono formula. 

Previous efforts to get this into brew have stalled because the upstream repository did not contain a fix which allowed bypassing the dependency libgdiplus has on X11. This was fixed a while ago (mono/libgdiplus#46), so all should be good now to get this into homebrew.

Let me know if you need anything else.

See also #4202 (@medains), Homebrew/legacy-homebrew#45404 (@haf)

2017-04-26 12:56 UTC, ilovezfs submitted a review, later dismissed
@qmfrederik a new tag would be good. I see 4.2 is from sixteen months ago, and the url you're proposing `https://github.com/mono/libgdiplus/archive/910ba3a126d2639861fb7feb3f12941526e99be8.tar.gz` is the head revision, not 4.2.

2017-04-27 08:15 UTC, bfontaine requested changes

2017-04-27 08:15 UTC, bfontaine commented on Formula/mono-libgdiplus.rb
> +  desc "C-based implementation of GDI+ API http://www.mono-project.com/"
Please remove that URL from the description.

2017-04-27 17:39 UTC, qmfrederik commented on Formula/mono-libgdiplus.rb
> +  desc "C-based implementation of GDI+ API http://www.mono-project.com/"
Done!

2017-04-27 17:42 UTC, qmfrederik commented
@ilovezfs Yes, the build I'm proposing is a fairly recent comment; it's essentially 4.2 plus the patch required to make lbigdiplus compile on macOS without x11.

In other words, up to 910ba3a126d2639861fb7feb3f12941526e99be8, all the changes in libgdiplus which are not part of 4.2 are related to this.

2017-04-27 21:31 UTC, bfontaine approved these changes

2017-05-12 17:05 UTC, qmfrederik commented
@ilovezfs So, we just got a new tag in the repo - 5.4. I update title & formula to point to release 5.4

Does that address your feedback?

2017-05-14 14:31 UTC, haf commented
This would be nice to get merged.

2017-05-16 19:50 UTC, qmfrederik commented
@bfontaine @ilovezfs Can either of you give me a bit more information related to the build error:

```
Error: Operation not permitted - /usr/local/Cellar/automake/1.15/share/automake-1.15/COPYING
```

I'm not sure where it comes from or how to fix it?

2017-05-16 20:01 UTC, ilovezfs commented
```
diff --git a/Formula/mono-libgdiplus.rb b/Formula/mono-libgdiplus.rb
index 632fea5..cf835cb 100644
--- a/Formula/mono-libgdiplus.rb
+++ b/Formula/mono-libgdiplus.rb
@@ -21,12 +21,13 @@ class MonoLibgdiplus < Formula
   depends_on "giflib"
 
   def install
-    system "./autogen.sh", "--disable-debug",
-                           "--disable-dependency-tracking",
-                           "--disable-silent-rules",
-                           "--without-x11",
-                           "--disable-tests",
-                           "--prefix=#{prefix}"
+    system "autoreconf", "-fiv"
+    system "./configure", "--disable-debug",
+                          "--disable-dependency-tracking",
+                          "--disable-silent-rules",
+                          "--without-x11",
+                          "--disable-tests",
+                          "--prefix=#{prefix}"
     system "make"
     cd "tests" do
       system "make", "testbits"
iMac-TMP:homebrew-core joe$ 
```

2017-05-16 20:17 UTC, qmfrederik commented
@ilovezfs Thanks! Build looks green now - are we good to have this merged?

2017-05-17 17:49 UTC, haf commented
Trying the patch out (probably not a problem of the patch/PR itself):


```
System.EntryPointNotFoundException: GetQDGlobalsThePort
  at (wrapper managed-to-native) System.Drawing.MacSupport:GetQDGlobalsThePort ()
  at System.Drawing.MacSupport.GetCGContextForView (System.IntPtr handle) [0x00039] in /private/tmp/mono-20170420-53906-63nc7r/mono-4.8.1/mcs/class/System.Drawing/System.Drawing/macFunctions.cs:89
  at System.Drawing.Graphics.FromHwnd (System.IntPtr hwnd) [0x0004d] in /private/tmp/mono-20170420-53906-63nc7r/mono-4.8.1/mcs/class/System.Drawing/System.Drawing/Graphics.cs:1718
  at PdfSharp.Drawing.XGraphics..ctor (System.Drawing.Graphics gfx, PdfSharp.Drawing.XSize size, PdfSharp.Drawing.XGraphicsUnit pageUnit, PdfSharp.Drawing.XPageDirection pageDirection) [0x00009] in <2a80a7aa909f4f4394d33f68c6061743>:0
  at PdfSharp.Drawing.XGraphics.CreateMeasureContext (PdfSharp.Drawing.XSize size, PdfSharp.Drawing.XGraphicsUnit pageUnit, PdfSharp.Drawing.XPageDirection pageDirection) [0x00002] in <2a80a7aa909f4f4394d33f68c6061743>:0
```

2017-05-17 18:51 UTC, qmfrederik commented
@haf It's best to raise these issues outside of Homebrew because they are not related but may delay this PR being accepted.

To your issues:

* macOS: That declaration is looking for a function named `GetQDGlobalsThePort` in `Carbon.framework`. This was removed in [OS X v10.7](https://developer.apple.com/library/content/releasenotes/General/MacOSXLionAPIDiffs/ApplicationServices.html). So it's an upstream mono issue, not a `libgdiplus` issue
* Ubuntu: I'm guessing you're running on a headless system (no X server running); but (upstream) libgdiplus has a dependency on an X server on Linux. You can use xvfb on Linux and use something like `xvfb-run`. This should work.

2017-05-18 09:03 UTC, closed without merging

2017-05-18 09:04 UTC, fxcoudert commented
Thanks @qmfrederik and everyone who contributed to this PR! It is a very nice addition to Homebrew