Update fibjs to v0.36.0
Homebrew/homebrew-core pull request #128702
Opened 2023-04-18 18:35 UTC by xicilion

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2023-04-18 18:42 UTC, carlocab requested changes

2023-04-18 18:42 UTC, carlocab commented on Formula/fibjs.rb
> -  sha256 "938e148064413c381d9e900e9160dc02a1d68376dfae681ba288fe2fbb8924de"
Please update the checksum; don't just remove it.

2023-04-18 19:22 UTC, xicilion commented
Can we replace ubuntu in the CI with 20.04, or just skip the CI for Linux?

2023-04-18 19:29 UTC, xicilion commented
There is also another way to implement docker compilation by specifying linux parameters to the build script.
The shell script looks like this:
```
bash build release linux
```
But I don't know how to change the rb.

2023-04-22 06:59 UTC, xicilion commented
When will this request be merged, please?

2023-04-22 17:24 UTC, SMillerDev commented
When it stops modifying the bottle block for one

2023-04-23 14:36 UTC, xicilion commented
What does that mean, does it mean I need to manually fill the checksum generated by the ci back into the bottle?

2023-04-23 18:14 UTC, SMillerDev commented
No, it means you should not modify the bottle block manually. And we won't merge the review as long as it does.

2023-04-23 19:46 UTC, xicilion commented
If so, I want to remove the linux bottle and add the arm bottle, how do I do that?

2023-04-24 07:18 UTC, SMillerDev commented
> If so, I want to remove the linux bottle and add the arm bottle, how do I do that?

You don't, if it builds and tests successfully there will be a bottle

2023-04-24 08:06 UTC, SMillerDev commented
It seems to be building a bunch of vendored versions of Homebrew formulae, it really shouldn't do that.

2023-04-24 20:34 UTC, xicilion commented
Finally, I changed the compilation options to pass the CI for Linux.

2023-04-27 06:57 UTC, xicilion commented
Please review this pr to see if it can be merged.

2023-04-28 14:36 UTC, SMillerDev submitted a review, later dismissed

2023-05-03 08:19 UTC, xicilion commented
still not merged.

2023-05-03 10:03 UTC, carlocab approved these changes, later dismissed

2023-05-03 10:05 UTC, xicilion commented
Thanks a lot.

2023-05-03 14:51 UTC, carlocab commented
Huh, guess this needs another review since I pushed to this.

2023-05-03 15:36 UTC, carlocab commented
Merge workflow doesn't like my earlier review requesting changes even if I later approved. Will need to fix that.

2023-05-03 18:03 UTC, closed without merging