cdecl 3.0.1 (updated formula)
Homebrew/homebrew-core pull request #12871
Opened 2017-04-25 15:16 UTC by paul-j-lucas

Cdecl hasn't seen a major update since 1996.  This all-new version updates it
to support C through C11 and C++ through C++14 and greatly improves error
messages.

- [ X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-25 16:02 UTC, bfontaine commented
We need an actual release from upstream here.

2017-04-25 16:03 UTC, bfontaine requested changes

2017-04-25 16:03 UTC, bfontaine commented on Formula/cdecl.rb
> -  end
Please don’t remove this block; our bot will take care of it.

2017-04-25 16:03 UTC, bfontaine commented on Formula/cdecl.rb
> +    ENV.deparallelize # must ensure parser.h builds first
Please report this to upstream.

2017-04-25 22:14 UTC, paul-j-lucas commented on Formula/cdecl.rb
> -  end
I put it back.

2017-04-26 12:34 UTC, ilovezfs commented
@paul-j-lucas thank you for this pull request. Unfortunately, we cannot accept this as an update to the existing formula until you've gotten the changes upstreamed, nor can we accept this as a new formula as it doesn't pass the notability audit:
```
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```
Please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead.

2017-04-26 12:34 UTC, closed without merging

2017-04-26 15:18 UTC, paul-j-lucas commented
If, by upsteam, you mean the cdecl-blocks repo, that's pretty much abandonware. The only change that author did was add support for Apple's "blocks" syntax. He's not the original author. There are many cdecl repos on github: I just picked his as a starting point.

What does a codebase's github "notability" have to do with anything? The original code has been around 30+ years. So you'd rather keep the long-outdated version that doesn't support either modern C or C++ in Homebrew? How does that best serve users?