libidn@2 2.0.2 (new formula)
Homebrew/homebrew-core pull request #12885
Opened 2017-04-25 21:43 UTC by DomT4

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

New formula for `libidn@2`, which is now stable upstream.

`libidn@2` includes compatibility functions for other projects but I think the way to be most Homebrew-friendly is to introduce this as a new formula for now & migrate things across it as possible rather than inreplacing a bunch of projects to use the correct header:

> This library is backwards (API) compatible with the libidn library. Replacing the idna.h header with idn2.h into a program is sufficient to switch the application from IDNA2003 to IDNA2008 as supported by this library.

2017-04-25 22:48 UTC, DomT4 commented
Ah, the classic `osc` testing failure 😒.

2017-04-26 09:02 UTC, ilovezfs commented
I'm :-1: on using versioned formulae for new versions.

2017-04-26 09:05 UTC, ilovezfs requested changes
This should be recast as an ordinary version upgrade for the main libidn formula, or deferred until that becomes feasible.

2017-04-26 14:30 UTC, DomT4 commented
> I'm 👎 on using versioned formulae for new versions.

How do you feel about flipping it and this becoming `libidn` & adding a `libidn@1` formula then? That would seem more in line with how Homebrew has handled breaking updates so far.

2017-04-26 14:50 UTC, ilovezfs commented
I'd prefer to avoid libidn@1 if possible. Have you tried just upgrading it?

2017-04-26 14:57 UTC, DomT4 commented
No, but the entire header structure changed, as well as the library versioning, so best case scenario everything needs a revision, worst case scenario almost everything needs `inreplace`-ing to use the right unified header & reported upstream.

I mean, I can do it that way, because slowly as we're discovering `libidn2` is becoming expected upstream, but this way felt more Homebrewish so I started here.

2017-04-26 15:10 UTC, MikeMcQuaid commented
Agreed about trying an update and falling back to a libidn@1 formula if that's not possible and falling back again to a libidn@2 formula if the vast majority of formulae are on libidn@1 vs. 2.

2017-04-26 15:14 UTC, ilovezfs commented
"This library is backwards (API) compatible with the libidn library.
Replacing the idna.h header with idn2.h into a program is
sufficient to switch the application from IDNA2003 to IDNA2008 as supported
by this library."

2017-04-26 19:12 UTC, DomT4 commented
Of the mandatory stuff:

* freediameter - Fixed with some `inreplace`-ing, reported upstream.
* getdns - Needs `stringprep`, which seems to have been dropped???
* git-annex
* hesiod
* knot
*  lftp
* libswiften
* loudmouth
* mcabber
* monotone
* pidgin
* skipfish

Will keep testing. Anything without an explanation hasn't been checked yet.

2017-04-27 01:42 UTC, ilovezfs commented
>getdns - Needs stringprep, which seems to have been dropped???

mind asking libidn2 upstream what the deal is there?

2017-04-27 01:48 UTC, ilovezfs commented
>git-annex - Builds without any issue, but unsure it's actually using libidn. Removing it locally doesn't obviously break anything.

Possible it's not finding it. @joeyh is there something we need to do to get git-annex to use libidn/libidn2?

2017-04-27 11:36 UTC, joeyh commented
ilovezfs wrote:
>     git-annex - Builds without any issue, but unsure it's actually using
>     libidn. Removing it locally doesn't obviously break anything.
> 
> Possible it's not finding it. @joeyh is there something we need to do to get
> git-annex to use libidn/libidn2?

That was needed for the xmpp support, which was removed from git-annex
recently. You also no longer need gnutls installed to build git-annex.

-- 
see shy jo

2017-04-27 11:51 UTC, ilovezfs commented
@joeyh Thanks for the help!

2017-04-27 19:04 UTC, DomT4 commented
> mind asking libidn2 upstream what the deal is there?

https://gitlab.com/libidn/libidn2/issues/28

2017-05-01 12:43 UTC, ilovezfs commented
@DomT4 looks like upstream responded

2017-05-01 13:01 UTC, DomT4 commented
Aye, I saw.

The reply was impressively detailed & I'll leave a thanks for that shortly, but somewhat threw me in terms of realising some of the I guess not non-standard but nonetheless less simple `libidn` usage from the `1.x` branch is a fair bit more work than swapping out headers & library linkage.

Not planning to give it up but it certainly gave me an appreciation this may be more involved than the upstream `README` initially made me think 😄.

2017-05-01 13:20 UTC, ilovezfs commented
@DomT4 What's more, it seems your inquiry triggered some upstream commits. Neat!

2017-05-24 14:03 UTC, DomT4 commented
@probot-stale[bot] Complicated but not yet dead.

2017-05-24 14:04 UTC, ilovezfs commented
I love how you talk to the :robot:

2017-05-24 14:05 UTC, DomT4 commented
It's the easiest way to get it to drop the `stale` label without simply rebasing, force pushing & having the test-bot do a pointless run 😅

2017-05-24 14:06 UTC, ilovezfs commented
Now it will leave you alone.

2017-05-24 14:10 UTC, DomT4 commented
Cool, thanks 🙇.

This is something I'm still paying attention to, but with upstream adding more advice on how to transition to `libidn2`, other upstreams seemingly completely ignoring patches I've sent so far & not wanting to spend all the time I have for FOSS on this things have slowed a fair bit.

2017-05-24 14:17 UTC, ilovezfs commented
Maybe vendor it into the two (curl and wget) that can't use version 1 and call it a day?

2017-05-24 14:20 UTC, ilovezfs commented
If you prefer to close both PRs, I'm also fine with that if you want to move on from this.

2017-05-24 14:20 UTC, DomT4 commented
> Maybe vendor it into the two (curl and wget) that can't use version 1 and call it a day?

Yeah, maybe that's not a bad way to go for now to be fair. I guess we could always come back to this in 3/4/5/6 months, or as more upstreams migrate & make vendoring unpleasantly heavy to maintain for folks.

2017-05-24 14:30 UTC, ilovezfs commented
Do you think a significant number of users would actually want to `brew install libidn@2` for their own purposes?

2017-05-24 14:36 UTC, DomT4 commented
At this point I wouldn't say it has the same testing appeal in a Homebrew context as `openssl@1.1` did & does. It could be useful to some I'm sure, but building `libidn2` from source is a pretty quick & simple process compared to OpenSSL.

2017-05-24 14:40 UTC, ilovezfs commented
Vendoring seems fine to me then, but we can always revisit libidn@2 later if there are users asking for it.

2017-05-24 16:54 UTC, DomT4 commented
https://github.com/Homebrew/homebrew-core/pull/13899

2017-06-02 16:50 UTC, closed without merging