libgr 0.72.2
Homebrew/homebrew-core pull request #129172
Opened 2023-04-24 09:31 UTC by ZhongRuoyu

Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre></pre>
</details>

2023-04-24 10:52 UTC, chenrui333 approved these changes

2023-04-24 10:57 UTC, ZhongRuoyu commented
```
Error: You are trying to merge a pull request that conflicts with a long running build in:
{
  "Homebrew/homebrew-core/pull/118902": [
    "Formula/libgr.rb"
  ]
}
```

#118902

2023-04-24 11:29 UTC, carlocab commented
> :warning: Bottle publish [failed](https://github.com/Homebrew/homebrew-core/actions/runs/4785532045). CC @carlocab

Thanks, saw it the first time

2023-04-25 14:31 UTC, carlocab requested changes, later dismissed

2023-04-25 14:31 UTC, carlocab commented on Formula/libgr.rb
>    revision 1
This needs to be removed. Not even sure if the built bottles still work/make sense.

2023-04-26 04:55 UTC, carlocab approved these changes

2023-04-26 05:11 UTC, merged