Split fstrm 0.3.2 into separate bottle
Homebrew/homebrew-core pull request #12949
Opened 2017-04-27 14:57 UTC by oerdnj

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-27 15:37 UTC, DomT4 requested changes

2017-04-27 15:37 UTC, DomT4 commented on Formula/fstrm.rb
> +  stable do
Don't need a `stable do` block unless you're doing something special in it, like a `stable`-only resource or dependency.

2017-04-27 15:37 UTC, DomT4 commented on Formula/fstrm.rb
> +  bottle do
CI does this. You can remove this block.

2017-04-27 15:37 UTC, DomT4 commented on Formula/knot.rb
> +    rebuild 1
Likewise here, don't mess with the bottles.

2017-04-27 15:37 UTC, DomT4 commented on Formula/knot.rb
> +
Whitespace be here 👻

2017-04-27 15:46 UTC, oerdnj commented
@DomT4 Thanks for the review, all comments should be resolved.

2017-04-27 15:48 UTC, oerdnj commented
JFTR The reason for the split is that fstrm can be used in other projects that support dnstap:
- knot-resolver
- unbound
- (?)bind

2017-04-27 19:25 UTC, fxcoudert commented
Thanks @oerdnj for your contribution to Homebrew!

2017-04-27 19:25 UTC, closed without merging

2017-04-29 11:32 UTC, ilovezfs commented
@fxcoudert I'm not sure what went wrong here, but the knot bottle doesn't have the knot config file (`.bottle/etc/knot.conf`). Hence https://github.com/Homebrew/homebrew-core/pull/13025.