ck 0.6.0 (new formula)
Homebrew/homebrew-core pull request #12968
Opened 2017-04-27 21:00 UTC by elthariel

Concurrent Kit is used to add multi-threading support to the Crystal
language runtime. It'll soon be required to build crystal, hence this PR.

Signed-off-by: Julien 'Lta' BALLET <contact@lta.io>

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-27 21:26 UTC, elthariel commented
Should I rebase once I'm done, or you're going to 'Squash and merge' ?

2017-04-27 22:02 UTC, elthariel commented
I've disabled `make check` which doesn't seem to like the Jenkins env. What kind of executors is in use ?

2017-04-27 22:30 UTC, fxcoudert requested changes
Once changes are made, please squash all commits into one. Thanks!

2017-04-27 22:30 UTC, fxcoudert commented on Formula/ck.rb
> +    system "./configure", "--prefix=#{prefix}"
Does the `configure` script support `--disable-dependency-tracking`? If so, add it.

2017-04-27 22:30 UTC, fxcoudert commented on Formula/ck.rb
> +    # system "make", "-C", "regressions", "check"
Comment and commented-out line can be removed

2017-04-28 11:01 UTC, elthariel commented on Formula/ck.rb
> +    system "./configure", "--prefix=#{prefix}"
No it's not supported. This is not an autotools build system, it's an homemade one

2017-04-28 11:44 UTC, fxcoudert approved these changes

2017-04-28 11:45 UTC, closed without merging

2017-04-28 11:45 UTC, fxcoudert commented
Thanks @elthariel for the pull request!