immortal: fixed formula to enable passing version on compile time
Homebrew/homebrew-core pull request #12972
Opened 2017-04-27 23:06 UTC by nbari

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-28 16:13 UTC, DomT4 commented on Formula/immortal.rb
> +      system "go", "get", "-u", "gopkg.in/yaml.v2"
Formulae should not run `go get` directly. You wanna look for `go_resource`s.

2017-04-28 16:15 UTC, nbari commented on Formula/immortal.rb
> +      system "go", "get", "-u", "gopkg.in/yaml.v2"
Will take a look and update the request, thanks

2017-04-28 20:29 UTC, nbari commented on Formula/immortal.rb
> +      system "go", "get", "-u", "gopkg.in/yaml.v2"
Should be fixed, could you please check.

2017-04-30 03:21 UTC, DomT4 reviewed
It's probably worth bumping the revision as well if this was missing resources & causing issues at run?

2017-04-30 03:21 UTC, DomT4 commented on Formula/immortal.rb
> +      bin.install "immortal"
This is _probably_ just about short enough to turn into an array:
```ruby
bin.install %w[immortal immortalctl immortaldir]
```

2017-04-30 03:21 UTC, DomT4 commented on Formula/immortal.rb
> +      man8.install "man/immortal.8"
Are there any `.8` manpages we're not installing here? If we're installing everything anyway:
```ruby
man8.install Dir["man/*"]
```
or:
```ruby
man8.install Dir["man/*.8"]
```

2017-05-01 13:04 UTC, DomT4 commented
> Regarding the version is there a way to dump/create a build version so that it won't interfere with the application itself?

I think what you're asking for is basically `revision`? Presuming you mean to force a new update without changing the upstream version or what version is passed to the build variable?

2017-05-01 13:08 UTC, nbari commented
Exactly, how should I add a `revision`, could you please give me a hint?

should I just add it after `head`, for example:

```
class Immortal < Formula
  desc "OS agnostic (*nix) cross-platform supervisor"
  homepage "https://immortal.run/"
  url "https://github.com/immortal/immortal/archive/0.13.2.tar.gz"
  sha256 "f34674720828c984ef34df33b75b614fabe81e4fd50eb152746a33a273daa4f9"
  head "https://github.com/immortal/immortal.git"
  revision 2

   ...
```

2017-05-01 13:09 UTC, DomT4 commented
```diff
diff --git a/Formula/immortal.rb b/Formula/immortal.rb
index 9ee7daebf6..0dee21fc50 100644
--- a/Formula/immortal.rb
+++ b/Formula/immortal.rb
@@ -3,6 +3,8 @@ class Immortal < Formula
   homepage "https://immortal.run/"
   url "https://github.com/immortal/immortal/archive/0.13.2.tar.gz"
   sha256 "f34674720828c984ef34df33b75b614fabe81e4fd50eb152746a33a273daa4f9"
+  revision 1
+
   head "https://github.com/immortal/immortal.git"
 
   bottle do
```

2017-05-01 13:16 UTC, nbari commented
Done, many thanks 👍

2017-05-02 02:33 UTC, DomT4 commented
@ilovezfs This is probably alright if you're happy. Guess what the `Makefile` was running! 😓😭

2017-05-02 09:06 UTC, nbari commented
I like more this approach since looks/behave more like the FreeBSD port in terms that download the specific resources and don't delegate all to the Makefile, also for some reason the Makefile was not properly setting the version and seems that with this changes the version is now passed.

So from my side, I would like to keep this last version if is ok for you guys.

2017-05-02 17:31 UTC, DomT4 commented
Yeah, my comment was an endorsement of the change essentially.

Homebrew's policy is to not let projects run `go get` either themselves or from the formula, but since people don't have the time/memory/whatever to manually check every `Makefile` used in every `go` project sometimes these things slip through the net.

2017-05-02 17:31 UTC, DomT4 approved these changes

2017-05-04 10:33 UTC, bfontaine requested changes

2017-05-04 10:33 UTC, bfontaine commented on Formula/immortal.rb
> +      system "go", "build", "-ldflags", ldflags, "-o", "immortaldir", "cmd/immortaldir/main.go"
Use `system "go", "build", "-ldflags", ldflags, "-o" "#{bin}/immortal", …` (same with other binaries) so you can remove the `bin.install` step below.

2017-05-04 13:32 UTC, nbari commented on Formula/immortal.rb
> +      system "go", "build", "-ldflags", ldflags, "-o", "immortaldir", "cmd/immortaldir/main.go"
@bfontaine done, please check.

2017-05-04 13:33 UTC, DomT4 commented on Formula/immortal.rb
> +      system "go", "build", "-ldflags", ldflags, "-o", "immortaldir", "cmd/immortaldir/main.go"
@bfontaine Can't believe I forgot that, nicely spotted!

2017-05-04 14:07 UTC, nbari commented on Formula/immortal.rb
> +      system "go", "build", "-ldflags", ldflags, "-o", "immortaldir", "cmd/immortaldir/main.go"
I accidentally,  pull force to my master, any idea how to recover the pull request?

2017-05-04 15:42 UTC, nbari commented
Reopening after accidentally closing it

2017-05-04 15:50 UTC, bfontaine commented on Formula/immortal.rb
> +      system "go", "build", "-ldflags", ldflags, "-o", "immortaldir", "cmd/immortaldir/main.go"
What do you mean by "pull force to my master"? What command(s) did you run?

2017-05-04 15:54 UTC, nbari commented on Formula/immortal.rb
> +      system "go", "build", "-ldflags", ldflags, "-o", "immortaldir", "cmd/immortaldir/main.go"
I did a 

    git push nbari +master 

That removed the pull request, I just recover it but will try to clean all the commits, sorry for this inconvenience.

2017-05-04 16:08 UTC, nbari commented on Formula/immortal.rb
> +      system "go", "build", "-ldflags", ldflags, "-o", "immortaldir", "cmd/immortaldir/main.go"
@bfontaine Fixed, now before breaking it again, how to do a proper squash ? or can you do it when you merge the PR?

Thanks in advance.

2017-05-04 16:34 UTC, nbari commented on Formula/immortal.rb
> +      system "go", "build", "-ldflags", ldflags, "-o", "immortaldir", "cmd/immortaldir/main.go"
@bfontaine Hi, I was available to squash :) seems to be all now ok.

2017-05-04 22:00 UTC, bfontaine commented on Formula/immortal.rb
> +      system "go", "build", "-ldflags", ldflags, "-o", "immortaldir", "cmd/immortaldir/main.go"
Sorry I wasn’t in front of my computer but everything seems ok now :)

2017-05-05 18:12 UTC, nbari commented
@bfontaine how to put in "green" the Changes requested option?

2017-05-05 18:22 UTC, bfontaine approved these changes

2017-05-05 18:22 UTC, bfontaine commented
Done :)

2017-05-08 17:58 UTC, closed without merging