Update j2objc formula to follow formula rules
Homebrew/homebrew-core pull request #12982
Opened 2017-04-28 09:09 UTC by ralic

J2ObjC is an open-source command-line tool from Google that translates Java source code to Objective-C for the iOS (iPhone/iPad) platform. This tool enables Java source to be part of an iOS application's build, as no editing of the generated files is necessary.
It takes very long to build from source, so the default option shall be prebuilt. (1.6GB)
https://github.com/google/j2objc

- [v ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ v] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ v] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-04-28 10:36 UTC, fxcoudert commented
Why does the title say "update j2objc" when it is a new formula?
There is a problem with the sha-256 sum.

```
  * C: 33: col 1: Incorrect indentation detected (column 0 instead of 4).
  * Stable: Use GitHub tarballs rather than zipballs (url is https://github.com/google/j2objc/archive/1.3.1.zip).
```

2017-04-28 16:10 UTC, DomT4 commented
> Why does the title say "update j2objc" when it is a new formula?

There used to be a `j2objc` formula in `devel-only`, which I thought had been migrated to core when `devel-only` was deprecated, but I guess it must have got lost somewhere along the lines. I'd presume op still has a local copy installed or something ❓

2017-04-28 16:12 UTC, DomT4 commented on Formula/j2objc.rb
> +## TODO Prebuilt version, to be updated for build from source
Homebrew doesn't care too much about this for Java stuff. I planned to switch it over one day but I'm not sure it's worth the hassle, personally.

2017-04-28 16:12 UTC, DomT4 commented on Formula/j2objc.rb
> +  def shim_script(target)
Should be able to do something like this instead: https://github.com/Homebrew/homebrew-core/commit/a753bdca89177d120df006f18d0064b3fd3304d5

2017-04-28 16:18 UTC, ilovezfs commented
It was removed in https://github.com/Homebrew/homebrew-devel-only/pull/61.

2017-04-28 16:25 UTC, DomT4 commented
Ah, thanks. I hadn't kept much of an eye on the taps since I left, doing so was quite therapeutic 😆.

I think `devel-only` suffered a fair bit from its inherent identity crisis given `devel` also existed here, sometimes as stable versions, so its defining mission was blurred considerably more than say `x11` or `versions`. I regretted creating the tap fairly quickly because of that confusion 😅.

2017-04-28 16:32 UTC, bfontaine requested changes

2017-04-28 16:32 UTC, bfontaine commented on Formula/j2objc.rb
> +#             http://www.rubydoc.info/github/Homebrew/brew/master/Formula
Please remove these comments.

2017-04-28 16:32 UTC, bfontaine commented on Formula/j2objc.rb
> +    # system "false"
Please write a test.

2017-04-28 16:32 UTC, bfontaine commented on Formula/j2objc.rb
> +# system "make", "install"
Please remove these comments.

2017-04-28 16:32 UTC, bfontaine commented on Formula/j2objc.rb
> +    "#{libexec}/#{target}" "$@"
Indent the content by two spaces:
```ruby
<<-EOS.undent
  your content
  goes here
EOS
```

2017-05-01 12:27 UTC, ralic commented
Will create another pull request once have j2objc pre-built zip file uploaded to cloud storage. It's about 971MB.

2017-05-01 12:27 UTC, closed without merging

2017-05-01 12:57 UTC, DomT4 commented
> It's about 971MB.

Sounds about right. The old install I had hanging around which I'd forgotten about clocked in a touch over 1GB when I removed it, so.