plantuml 1.2017.12
Homebrew/homebrew-core pull request #13013
Opened 2017-04-28 23:58 UTC by sugavaneshb

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)? Yes
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change? Yes
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting? Yes
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)? Yes
-----

I tried running `brew bump-formula-pr --strict` using the necessary parameters as described in  [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md), I was unable to upgrade that way with the following message,
```
Error: You probably need to bump this formula manually since changing the
version from 8059 to 1.2017.12 would be a downgrade.
```
So, I bumped it manually and I followed the rest of checklist.

2017-04-29 06:21 UTC, neutric requested changes

2017-04-29 06:21 UTC, neutric commented on Formula/plantuml.rb
Please add `version_scheme 1`, for more info see [version scheme changes](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#version-scheme-changes) in the docs.

2017-04-29 06:21 UTC, neutric commented on Formula/plantuml.rb
> +  homepage "http://plantuml.com/"
Use https, please.

2017-04-29 15:00 UTC, DomT4 commented
Fixes https://github.com/Homebrew/homebrew-core/issues/13022 when merged.

2017-05-02 02:09 UTC, sugavaneshb commented on Formula/plantuml.rb
> +  homepage "http://plantuml.com/"
Fixed it. Note that it still redirects to http site.

2017-05-02 02:10 UTC, sugavaneshb commented on Formula/plantuml.rb
Done. Thanks for pointing to the wiki as well. I wasn't aware of this.

2017-05-02 03:01 UTC, neutric approved these changes

2017-05-02 03:01 UTC, merged

2017-05-02 03:03 UTC, neutric commented
Thanks for your first contribution to Homebrew, @sugavaneshb! 👍

2017-05-02 03:05 UTC, neutric commented
@DomT4 Thanks for the bookkeeping! :D