Fail2ban: v0.9.6
Homebrew/homebrew-core pull request #13027
Opened 2017-04-29 13:09 UTC by andrewying

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

Upgrade fail2ban to v0.9.6

2017-05-06 08:09 UTC, andrewying commented
Hey! Just wondering if there'll be any updates - is any changes needed?

2017-05-09 08:07 UTC, fxcoudert requested changes
The `caveats` talks about Mountain Lion, and macOS 10.4 and 10.5. Please link to updated doc

2017-05-09 08:07 UTC, fxcoudert commented on Formula/fail2ban.rb
> +  depends_on :python
This should probably be `depends_on :python if MacOS.version <= :snow_leopard`

2017-05-09 08:07 UTC, fxcoudert commented on Formula/fail2ban.rb
> +    system bin/"fail2ban-client", "-h"
Could we do a better test?

2017-06-28 09:49 UTC, closed without merging