already fixed a few remaining issues with the formula
Homebrew/homebrew-core pull request #13023
Opened 2017-04-29 06:16 UTC by yijunyu

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-01 11:09 UTC, bfontaine requested changes

2017-05-01 11:09 UTC, bfontaine commented on Formula/srcml.rb
> +  end
Please remove this block; our bot will take care of it.

2017-05-01 11:09 UTC, bfontaine commented on Formula/srcml.rb
> +  patch :DATA
Please submit this patch to upstream.

2017-05-01 11:09 UTC, bfontaine commented on Formula/srcml.rb
> +int
Please use `<<-EOS.undent` above and indent this line.

2017-05-01 11:09 UTC, bfontaine commented on Formula/srcml.rb
> +    exec "#{bin}/srcml", "Hello.java", "-o", "/dev/null"
Use `system`, not `exec`.

2017-05-09 14:26 UTC, dunn commented
Any update?

2017-05-26 20:32 UTC, ilovezfs commented
@yijunyu Thanks for the PR. Feel free to re-open once the requested changes have been made.

2017-05-26 20:32 UTC, closed without merging