Switch to more recent DUTI fork
Homebrew/homebrew-core pull request #13147
Opened 2017-05-02 05:20 UTC by jorvi

https://github.com/moretension/duti hasn't been updated in three years. Not only is https://github.com/russellhancox/duti more active, switching to this fork also allows us to drop the autoconf dependency and the custom patch for 10.11+ :)

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
  * Stable: Use versioned rather than branch tarballs for stable checksums. - I have no control over the repo, and the versioned branches are all out of date.
  * Commented-out dep "cmake" => :build - No idea why this warning is being thrown out. I removed Cmake from my system and all the install and all tests go just fine.

-----

2017-05-02 06:08 UTC, neutric requested changes
I reviewed your changes but haven't been maintainer long enough to be able to comment on switching forks. You might want to wait with changes until you hear from more experienced maintainers. Pinging the ever so helpful @ilovezfs. :)

2017-05-02 06:08 UTC, neutric commented on Formula/duti.rb
> +    man1.install "duti.1"
Why not utilize the Makefile: `system "make", "install", "BINDIR=#{bin}", "MANDIR=#{man1}"`?

2017-05-02 06:08 UTC, neutric commented on Formula/duti.rb
> +  url "https://github.com/russellhancox/duti/archive/master.tar.gz"
We need a tagged version to avoid breakage down the line. Please submit an issue upstream asking them to tag a new version.

2017-05-02 06:08 UTC, neutric commented on Formula/duti.rb
> +
Please remove.

2017-05-02 06:52 UTC, ilovezfs commented
It's unusual to switch to a fork unless the fork has effectively become upstream by becoming significantly more notable on GitHub than the original repository, as measured by watchers, stars, issue counts, PR counts, commit frequency, etc. In this case, the fork has 1 watcher, 0 stars, and issues disabled, so it's not really in the cards at this point.

@jorvi That said, if there are useful commits in the fork, I'd encourage you to try to get them upstreamed into the main repository, even if it currently appears to be dormant.

2017-05-02 06:52 UTC, closed without merging

2017-05-02 06:56 UTC, MikeMcQuaid commented
> @jorvi That said, if there are useful commits in the fork, I'd encourage you to try to get them upstreamed into the main repository, even if it currently appears to be dormant.

@jorvi Alternatively, if you can get the existing main repository to bless the fork as the new, canonical source in the README: that works too.

2017-05-02 07:51 UTC, neutric commented
Thanks for your feedback, guys!

2017-05-02 16:21 UTC, jorvi commented
Thanks! @MikeMcQuaid there's actually two forks that are interesting, the one I mentioned and https://github.com/nivekkagicom/duti, which has some extra functionality. Would it be cool with you/Homebrew if I merged the two, made a 1.7.1 branch, and got blessing from the main repository?
I use DUTI in my dotfiles so I'd be happy to maintain both DUTI and the Homebrew formula.

2017-06-19 20:18 UTC, jorvi commented on Formula/duti.rb
> +    man1.install "duti.1"
That doesn't work, you simply end up with an empty directory in the Cellar

2017-06-19 20:19 UTC, jorvi commented
@neutric @MikeMcQuaid 

Sorry for the late response. I've tried to contact the original repo in several ways, but as said in #2840, Upstream is dead, the guy hasn't been on GitHub in 3 years neither has he updated the project. The fork I originally pointed to also does not respond.
Since I use this tool myself, I'm happy to maintain both the binary and the formula.
I've updated the formula with the correct SHA256. I've made a new version on the repo, as requested.
Again, as said in #2840, this tool sees a reasonable amount of use, so it'd be kind of sad to put it down..

2017-06-23 15:32 UTC, MikeMcQuaid commented
> there is an active fork now, so it'd be kind of sad to put it down..

We need to have the active fork be blessed by upstream, sorry.

2017-06-23 15:38 UTC, jorvi commented
@MikeMcQuaid 
But there is no way to do that if the owner of upstream **hasn't been on GitHub for over 3 years, nor does he have any point of contact**. You guys already removed DUTI, and here presents itself an option to keep a moderately popular tool active. Please see the reason in this.. or we can roll with the extremely kafkaesque solution of me renaming the tool to `UTIlizer` or `UTID` or whatever and asking for this new tool to be included on Homebrew.

2017-06-23 16:39 UTC, MikeMcQuaid commented
> extremely kafkaesque solution of me renaming the tool to UTIlizer or UTID

When people `brew install duti` they expect the canonical version be installed. If you want a long-running fork that doesn't have upstream blessing: it needs a new name.