goad 1.4.0 (new formula)
Homebrew/homebrew-core pull request #13162
Opened 2017-05-02 14:29 UTC by gserra-olx

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-02 21:03 UTC, bfontaine requested changes

2017-05-02 21:03 UTC, bfontaine commented on Formula/goad.rb
> +  url "https://github.com/goadapp/goad.git"
We need a tag here. You can should be able to use the tarball at https://github.com/goadapp/goad/archive/v1.4.0.tar.gz and remove the `version` below; Homebrew will guess it from the URL.

2017-05-02 21:03 UTC, bfontaine commented on Formula/goad.rb
> +    ENV.prepend_create_path "PATH", buildpath/"bin"
Do we really need this?

2017-05-03 12:56 UTC, cwaltken-edrans commented on Formula/goad.rb
> +    ENV.prepend_create_path "PATH", buildpath/"bin"
Right now this line is not obsolete because we rely on `go-bindata` in the build process.

2017-05-05 11:43 UTC, gserra-olx commented
@bfontaine , @cwaltken-edrans  applied all the changes you requested, I just forgot to tag our repo

is there a way to re-kick the build process?

2017-05-05 12:58 UTC, gserra-olx commented
@bfontaine seems we made it. Can u have a look, please?

2017-05-05 15:15 UTC, bfontaine approved these changes

2017-05-05 22:20 UTC, closed without merging

2017-05-05 22:20 UTC, fxcoudert commented
Thanks @gserra-olx for your contribution to Homebrew!

2017-05-08 09:27 UTC, gserra-olx commented
our pleasure @fxcoudert ;)