Fixes launchctl service for mpd
Homebrew/homebrew-core pull request #13203
Opened 2017-05-03 14:22 UTC by ibrokemypie

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-16 21:25 UTC, fxcoudert commented
What is this trying to fix?

2017-05-31 00:45 UTC, ibrokemypie commented
launchctl simply wasnt launching mpd without this

2017-06-24 18:40 UTC, dunn commented on Formula/mpd.rb
> +    ohai "When launching as a service with a non-standard config location, append '<string>$mpdconfigpath</string>' before the closing array tag in ~/Library/LaunchAgents/#{homebrew.mxcl.mpd}.plist"
If this is Homebrew-specific information, it should be in the `caveats`.  Otherwise let's remove it.

2017-09-17 18:23 UTC, ilovezfs commented
@BrewTestBot test this please

2017-09-17 20:01 UTC, ilovezfs commented
@BrewTestBot test this please

2017-09-24 17:20 UTC, JCount commented
@BrewTestBot test this please

2017-09-24 17:50 UTC, JCount requested changes
@ibrokemypie How is `$mpdconfigpath` defined? Namely, is it something we could simply add to the current default plist and set to a generic default (or not define), or could we even dynamically define this key somehow?

2017-10-07 05:08 UTC, ilovezfs commented
@ibrokemypie we can re-open when @JCount's question has been answered! Thanks for the PR.

2017-10-07 05:08 UTC, closed without merging