make: add gnubin and gnuman files
Homebrew/homebrew-core pull request #13236
Opened 2017-05-04 16:50 UTC by robsonpeixoto

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-08 14:53 UTC, JCount requested changes
Could you also add `revision 1` to the formula below the sha256 hash? Thanks.

2017-05-08 14:53 UTC, JCount commented on Formula/make.rb
> +        PATH="#{opt_libexec}/gnubin:$PATH"
Inserting a newline before this line makes the terminal output more readable

2017-05-08 14:53 UTC, JCount commented on Formula/make.rb
> +        MANPATH="#{opt_libexec}/gnuman:$MANPATH"
Insert a newline before this line as well.

2017-05-08 14:53 UTC, JCount commented on Formula/make.rb
> +    if build.without? "default-names" then <<-EOS.undent
Changing this to:
```
    if build.without? "default-names"
      <<-EOS.undent
```
matches `findutils`. (This is a bit of an attempt to create order out of the chaos that has come to be through maintainer inconsistency throughout the years, 🙂) (Feel free to ignore this one 😄)

2017-05-09 00:36 UTC, robsonpeixoto commented on Formula/make.rb
> +    if build.without? "default-names" then <<-EOS.undent
Done in 2f84eb40da8d6113a9271a40c137448182f5fa50
A shameless copy from `findutils` =D

2017-05-09 02:33 UTC, JCount approved these changes

2017-05-09 02:41 UTC, closed without merging

2017-05-09 02:41 UTC, JCount commented
@robsonpeixoto Thank you for your contribution to Homebrew!! 🎉

2017-05-09 03:21 UTC, robsonpeixoto commented
Thanks @JCount