pilosa 0.3.1 (new formula)
Homebrew/homebrew-core pull request #13251
Opened 2017-05-04 18:46 UTC by bgyss

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-04 23:04 UTC, neutric requested changes

2017-05-04 23:04 UTC, neutric commented on Formula/pilosa.rb
> +  url "https://github.com/pilosa/pilosa/releases/download/v0.3.1/pilosa-v0.3.1-darwin-amd64.tar.gz"
No binaries please, we build from source.

2017-05-04 23:04 UTC, neutric commented on Formula/pilosa.rb
> +    system "#{bin}/pilosa", "--help"
We prefer not to test `version` or `help output unless nothing else is available.

2017-05-08 09:30 UTC, rakkesh commented
@bgyss thanks for introducing this formula to `Homebrew`. While you are working on this PR, you could add a functional `test do` block,

```rb
test do
    begin
      server = fork do
      exec "#{bin}/pilosa", "server"
      end
      sleep 0.5
      # Test that the response is from webdis
      assert_match(/^Welcome. Pilosa is running.*/, shell_output("curl localhost:10101"))
    ensure
      Process.kill "TERM", server
      Process.wait server
    end
  end
```

Also, a `plist` for launching it as a service.,

```xml
  def plist; <<-EOS.undent
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>Label</key>
        <string>#{plist_name}</string>
        <key>ProgramArguments</key>
        <array>
            <string>#{bin}/pilosa</string>
            <string>server</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <dict>
            <key>SuccessfulExit</key>
            <false/>
        </dict>
        <key>WorkingDirectory</key>
        <string>#{var}</string>
      </dict>
    </plist>
    EOS
  end
```
and manually,

```rb
plist_options :manual => "pilosa server"
```

2017-05-08 13:50 UTC, bgyss commented
@rakkesh no problem, I'll add your requests and update the PR later today.

2017-05-08 14:47 UTC, bgyss commented on Formula/pilosa.rb
> +  url "https://github.com/pilosa/pilosa/releases/download/v0.3.1/pilosa-v0.3.1-darwin-amd64.tar.gz"
Updated.

2017-05-08 14:47 UTC, bgyss commented on Formula/pilosa.rb
> +    system "#{bin}/pilosa", "--help"
Updated again in subsequent commit.

2017-05-08 17:14 UTC, bgyss reviewed
Please review at earliest convenience.

Thanks.

2017-05-08 17:53 UTC, fxcoudert approved these changes

2017-05-10 14:44 UTC, bgyss commented
@neutric would it be possible to review the requested changes to get this merged? Thanks.

2017-05-11 02:20 UTC, dunn commented on Formula/pilosa.rb
> +           "-X github.com/pilosa/pilosa/cmd.Version=#{version} -X github.com/pilosa/pilosa/cmd.BuildTime=#{ts}",
Why is it necessary to specify the build-time?  We're slowly working towards reproducible builds so if this isn't necessary I'd rather remove it.

2017-05-11 02:27 UTC, bgyss commented on Formula/pilosa.rb
> +           "-X github.com/pilosa/pilosa/cmd.Version=#{version} -X github.com/pilosa/pilosa/cmd.BuildTime=#{ts}",
@dunn it's not necessary but it is printed out when the command is run with '--help' and is specified in the Makefile itself.

Example printout from the pilosa command:

```
 ~/src/ pilosa --help
Pilosa is a fast index to turbocharge your database.

This binary contains Pilosa itself, as well as common
tools for administering pilosa, importing/exporting data,
backing up, and more. Complete documentation is available
at https://www.pilosa.com/docs/

Version: 0.3.1
Build Time: 2017-05-08T14:19:27+0000
...
```

I tried to keep everything as close to the build procedure that the maintainers themselves set up.

2017-05-11 06:39 UTC, rakkesh commented on Formula/pilosa.rb
> +  url "https://github.com/pilosa/pilosa/archive/v0.3.1.tar.gz"
There is a new release available, https://github.com/pilosa/pilosa/releases/tag/v0.3.2.

2017-05-11 06:40 UTC, rakkesh commented on Formula/pilosa.rb
> +  url "https://github.com/pilosa/pilosa/archive/v0.3.1.tar.gz"
This [release](https://github.com/pilosa/pilosa/releases/tag/v0.3.2) just adds Docker support.

2017-05-11 17:50 UTC, bgyss commented on Formula/pilosa.rb
> +  url "https://github.com/pilosa/pilosa/archive/v0.3.1.tar.gz"
@rakkesh I'm going to bump it because it's good to stay current - will update the title and everything else after I'm done.

2017-05-11 18:55 UTC, DomT4 commented on Formula/pilosa.rb
> +            <string>#{bin}/pilosa</string>
`opt_bin`.....

2017-05-11 18:55 UTC, DomT4 commented on Formula/pilosa.rb
> +      assert_match(/^Welcome. Pilosa is running.*/, shell_output("curl localhost:10101"))
A string rather than a regex will work just fine here.

2017-05-11 20:12 UTC, dunn commented on Formula/pilosa.rb
> +           "-X github.com/pilosa/pilosa/cmd.Version=#{version} -X github.com/pilosa/pilosa/cmd.BuildTime=#{ts}",
If it's not necessary, please remove it, thanks!

2017-05-11 21:08 UTC, bgyss commented on Formula/pilosa.rb
> +           "-X github.com/pilosa/pilosa/cmd.Version=#{version} -X github.com/pilosa/pilosa/cmd.BuildTime=#{ts}",
@dunn this is done in https://github.com/Homebrew/homebrew-core/pull/13251/commits/2cfa622c11f1c29782e30b0d7f9c3620a500c3f1

CLI printout looks like this now:

```
Pilosa is a fast index to turbocharge your database.

This binary contains Pilosa itself, as well as common
tools for administering pilosa, importing/exporting data,
backing up, and more. Complete documentation is available
at https://www.pilosa.com/docs/

Version: 0.3.2
Build Time: not recorded
```

2017-05-11 21:11 UTC, dunn commented on Formula/pilosa.rb
> +           "-X github.com/pilosa/pilosa/cmd.Version=#{version} -X github.com/pilosa/pilosa/cmd.BuildTime=#{ts}",
That's fine, thanks!

2017-05-11 21:45 UTC, dunn commented
Thanks for all your work on this! Merged as 7557c2e30b45b76b5ca693680604f36c9a3a7fae.

2017-05-11 21:46 UTC, closed without merging