apache-flink 1.2.1
Homebrew/homebrew-core pull request #13283
Opened 2017-05-05 18:47 UTC by mbode

Created with `brew bump-formula-pr`.

2017-05-05 22:12 UTC, fxcoudert requested changes

2017-05-05 22:12 UTC, fxcoudert commented on Formula/apache-flink.rb
>    bottle :unneeded
After the `bottle` line, this formula needs a `depends_on :java` line (if any Java version is fine) or `depends_on :java => "1.7+"` (if there is a minimum version of, for example, Java 7)

2017-05-06 09:43 UTC, mbode commented on Formula/apache-flink.rb
>    bottle :unneeded
Ok, done. Do you want me to squash the commits or keep the version upgrade and the fix separate?

2017-05-06 22:37 UTC, fxcoudert approved these changes

2017-05-06 22:37 UTC, merged

2017-05-06 22:37 UTC, fxcoudert commented
Thanks for the pull request and the changes!