abseil: Use the minimum C++ standard supported
Homebrew/homebrew-core pull request #133008
Opened 2023-06-06 22:45 UTC by adamnovak

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This changes the Abseil build to build for the minimum C++ standard that Abseil supports. Abseil is now forward but not backward-compatible, so this should be compatible with the most C++ standards for downstream applications.

2023-06-06 22:48 UTC, adamnovak commented
It's not clear to me yet how to build this manually from a Github branch, instead of from edits made via `brew tap` and `brew edit`. I'll keep trying to see if I can get Brew to run my modified formula for me.

2023-06-07 03:56 UTC, carlocab requested changes
I'm sympathetic with the desire to use an older C++ standard here; using C++17 makes things rather difficult for dependent software.

However, doing this will break dependents like `or-tools`. You can check this for yourself by building `or-tools` from source after making this change. But CC @Mizux in case there are workarounds for this.

If you need a version of Protobuf that doesn't require C++17, please use `protobuf@21`.

2023-06-09 08:16 UTC, carlocab commented
I don't think there's a way to do this without breaking dependents such as `or-tools` that use/need C++17. Therefore, closing.

If there is a workaround for the above, please open a new pull request that implements it.

2023-06-09 08:16 UTC, closed without merging

2023-06-10 07:33 UTC, carlocab commented
This is not currently supported, and I'm not sure doing so would be very useful since it would be Homebrew-specific.

If there were a standard way to do it used by other package managers then that would be a different story.

However, I think you can use CMake to inspect the properties of targets provided by Abseil to determine the C++ standard they were compiled with.