dcos-cli 0.5.1 (new formula)
Homebrew/homebrew-core pull request #13378
Opened 2017-05-09 00:03 UTC by msabramo

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Formula for [dcos-cli](https://github.com/dcos/dcos-cli)

Cc: @tamarrow

2017-05-09 07:39 UTC, fxcoudert requested changes

2017-05-09 07:39 UTC, fxcoudert commented on Formula/dcos-cli.rb
> +  url "https://downloads.dcos.io/binaries/cli/darwin/x86-64/0.5.1/dcos"
No binaries, in Homebrew we build from source.

2017-05-09 07:39 UTC, fxcoudert commented on Formula/dcos-cli.rb
> +  depends_on :arch => :x86_64
And once you build from source, this won't be needed.

2017-05-09 07:39 UTC, fxcoudert commented on Formula/dcos-cli.rb
> +  bottle :unneeded
Remove that line, after building from source :)

2017-05-09 07:39 UTC, fxcoudert commented on Formula/dcos-cli.rb
> +    system bin/"dcos", "--version"
Could we do a stronger test?

2017-05-09 07:39 UTC, fxcoudert commented on Formula/dcos-cli.rb
> +  desc "The command-line for your datacenter!"
No `!`

2017-05-09 12:41 UTC, bfontaine commented on Formula/dcos-cli.rb
> +  desc "The command-line for your datacenter!"
`"Cross-platform command line utility to manage DC/OS clusters"` would be more helpful.

2017-05-09 12:42 UTC, bfontaine commented on Formula/dcos-cli.rb
> +  homepage "https://github.com/dcos/dcos-cli"
You may want to use https://dcos.io/docs/1.9/cli/ instead of the GitHub repo.

2017-05-10 00:33 UTC, msabramo commented on Formula/dcos-cli.rb
> +  url "https://downloads.dcos.io/binaries/cli/darwin/x86-64/0.5.1/dcos"
Switched to building from source in 44855949c5.

2017-05-10 00:34 UTC, msabramo commented on Formula/dcos-cli.rb
> +  bottle :unneeded
Done.

2017-05-10 00:34 UTC, msabramo commented on Formula/dcos-cli.rb
> +  depends_on :arch => :x86_64
OK.

2017-05-10 00:34 UTC, msabramo commented
Switched to building from source in 44855949c5.

2017-05-10 00:54 UTC, msabramo commented on Formula/dcos-cli.rb
> +    system bin/"dcos", "--version"
Stronger test in fa76f64919.

2017-05-10 00:55 UTC, msabramo commented on Formula/dcos-cli.rb
> +  homepage "https://github.com/dcos/dcos-cli"
Okay, done in 9206e6cd056c9fbba31ff78c5ef08c0b7fbebb90.

2017-05-10 00:55 UTC, msabramo commented on Formula/dcos-cli.rb
> +  desc "The command-line for your datacenter!"
Okay, done in 9206e6cd056c9fbba31ff78c5ef08c0b7fbebb90.

2017-05-11 02:06 UTC, dunn commented on Formula/dcos-cli.rb
> +  homepage "https://dcos.io/docs/1.9/cli/"
Is there an unversioned URL for the CLI page (i.e., without the `1.9`)?

2017-05-11 02:07 UTC, dunn commented on Formula/dcos-cli.rb
> +  homepage "https://dcos.io/docs/1.9/cli/"
I guess https://dcos.io/docs/latest/usage/cli/ should work.

2017-05-11 02:09 UTC, dunn commented on Formula/dcos-cli.rb
> +  head "git@github.com:dcos/dcos-cli.git"
Use `https` for the Git URL too.

2017-05-11 02:09 UTC, dunn commented on Formula/dcos-cli.rb
> +    assert_match "dcos \[options\] \[\<command\>\] \[\<args\>...\]", shell_output("#{bin}/dcos --help")
Any chance of a test that exercises more of the functionality?

2017-05-11 02:37 UTC, msabramo commented on Formula/dcos-cli.rb
> +    assert_match "dcos \[options\] \[\<command\>\] \[\<args\>...\]", shell_output("#{bin}/dcos --help")
Did you have something in mind? Most of the functionality depends on having a DC/OS cluster, so there's probably not very much that we can do.

2017-05-11 02:45 UTC, msabramo commented on Formula/dcos-cli.rb
> +  homepage "https://dcos.io/docs/1.9/cli/"
Cool. See 0476cdbc83.

2017-05-11 02:45 UTC, msabramo commented on Formula/dcos-cli.rb
> +  head "git@github.com:dcos/dcos-cli.git"
Cool. See 0476cdbc83.

2017-05-11 20:21 UTC, dunn commented
@fxcoudert I'm happy if you're happy.

2017-05-17 04:56 UTC, msabramo commented
@fxcoudert: Any more comments on this one?

2017-05-17 09:41 UTC, fxcoudert approved these changes

2017-05-17 09:44 UTC, fxcoudert commented
Thanks @msabramo for the pull request!

2017-05-17 09:44 UTC, closed without merging