conda-lock 2.1.0
Homebrew/homebrew-core pull request #133963
Opened 2023-06-16 17:34 UTC by dtrodrigues

Created with `brew bump-formula-pr`.

2023-06-16 17:51 UTC, SMillerDev approved these changes

2023-06-16 17:51 UTC, SMillerDev requested changes, later dismissed
Actually

2023-06-16 17:51 UTC, SMillerDev commented on Formula/conda-lock.rb
> +
Should use the formula

2023-06-16 17:51 UTC, SMillerDev commented on Formula/conda-lock.rb
> +  end
Should use the formula

2023-06-17 16:39 UTC, chenrui333 approved these changes

2023-06-17 16:58 UTC, merged