bash-git-prompt: update caveat to reflect online docs
Homebrew/homebrew-core pull request #13429
Opened 2017-05-10 15:09 UTC by samiam

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-11 10:07 UTC, fxcoudert requested changes

2017-05-11 10:07 UTC, fxcoudert commented on Formula/bash-git-prompt.rb
> -      if [ -f #{HOMEBREW_PREFIX}/share/gitprompt.sh ]; then
Please don't replace `#{HOMEBREW_PREFIX}` with `$(brew --prefix)`

2017-05-11 18:44 UTC, samiam commented
I've changed back to using #{HOMEBREW_PREFIX} without quotes.
I presume HOMEBREW_PREFIX won't have a space in it.
Otherwise, I'll need to quote it.  Your call.

2017-05-13 18:08 UTC, fxcoudert approved these changes

2017-05-13 18:14 UTC, merged