testssl: Fix checksum for v2.8.tar.gz
Homebrew/homebrew-core pull request #13492
Opened 2017-05-11 20:36 UTC by leonklingele

Don't know where @jap got the incorrect checksum from.
Maybe upstream did a new v2.8 release?

2017-05-11 20:40 UTC, jap commented
Looks like it - https://github.com/drwetter/testssl.sh/commits/2.8 show a commit having been done yesterday to the 2.8 branch. Weird that this is not offered as 2.8.1.

2017-05-12 06:10 UTC, ilovezfs commented
@drwetter https://github.com/Homebrew/brew/pull/2601 is specifically intended to catch and prevent updates like this from sailing through since they necessitate checking with upstream if they've been hacked, and requesting a new version be released. For a full explanation of why we want to avoid retagging, see https://github.com/Homebrew/homebrew-core/pull/7239#issuecomment-263063089

2017-05-12 06:30 UTC, drwetter commented
okay, still on a learning curve wrt ``git``.

I understand some of the reasons but the argument of being hacked is highly questionable -- if somebody hacks my account and release a 2.8.0.1 that's ok then, right? It's like having the garage and porch door open to your house and you close the open window.  Ok, maybe I am exaggerating a bit... ;-)

2017-05-12 06:34 UTC, ilovezfs commented
@drwetter https://github.com/caskroom/homebrew-cask/pull/33354

2017-05-16 10:37 UTC, leonklingele commented
Can this be merged now? Did you do the re-release @drwetter ?

2017-05-16 10:45 UTC, drwetter commented
Yes * 2

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

Am 16. Mai 2017, 12:37, um 12:37, leonklingele <notifications@github.com> schrieb:
>Can this be merged now? Did you do the re-release @drwetter ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Homebrew/homebrew-core/pull/13492#issuecomment-301743042

2017-05-18 14:33 UTC, fxcoudert commented
So we've confirmed that the SHA sum change is legit. Next time, @drwetter please release a new minor version instead of updating an already-released version.

2017-05-18 14:33 UTC, fxcoudert requested changes

2017-05-18 14:33 UTC, fxcoudert commented on Formula/testssl.rb
Please insert `revision 1` line after the `sha256`

2017-05-19 15:42 UTC, leonklingele commented on Formula/testssl.rb
Updated.

2017-05-19 15:47 UTC, fxcoudert approved these changes

2017-05-19 15:48 UTC, merged