conjure-up-2.2-beta4
Homebrew/homebrew-core pull request #13491
Opened 2017-05-11 20:19 UTC by battlemidget

This brings in improvements utilizing an asyncio library for Juju, better error
handling and logging.

Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Additionally, ran:
`brew test conjure-up.rb --devel` (for 2.2-beta4)
`brew test conjure-up.rb` (for 2.1.5)

2017-05-11 20:20 UTC, battlemidget commented
@fxcoudert feel free to throw something at me if I'm still missing steps

2017-05-13 17:03 UTC, fxcoudert commented
As you are updating resources, this needs to be a revision for stable.

2017-05-13 17:55 UTC, fxcoudert requested changes

2017-05-13 17:55 UTC, fxcoudert commented on Formula/conjure-up.rb
> +  resource "python-dateutil" do
Are these new resources needed? If so they should go in the `devel` block

2017-05-25 13:07 UTC, ilovezfs commented
Passing on this for now but feel free to reopen if the requested changes have been made.

2017-05-25 13:07 UTC, closed without merging

2017-05-25 13:09 UTC, battlemidget commented
Thanks, we're going to wait for Juju 2.2 GA before doing another PR for conjure-up

2017-05-25 13:10 UTC, ilovezfs commented
@battlemidget Sounds good! Thanks :)

2017-08-03 14:55 UTC, brettdh commented
@battlemidget any updates on this?

2017-08-03 15:20 UTC, battlemidget commented
@brettdh Hey Brett, sorry it is a result of not enough time in the day. I'll try to get to this build today