allure 2.0.1 (new formula)
Homebrew/homebrew-core pull request #13614
Opened 2017-05-16 12:21 UTC by eroshenkoam

2017-05-16 17:38 UTC, fxcoudert requested changes
Please squash to get a single-commit PR

2017-05-16 17:38 UTC, fxcoudert commented on Formula/allure.rb
> +
Will need `bottle :unneeded` line

2017-05-16 17:38 UTC, fxcoudert commented on Formula/allure.rb
> +  url "https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.0.1/allure-2.0.1.tgz"
Could we use the github release tarball?

2017-05-16 17:38 UTC, fxcoudert commented on Formula/allure.rb
> +  homepage "https://github.com/allure-framework"
Maybe `https://github.com/allure-framework/allure2` makes more sense as a homepage?

2017-05-16 17:38 UTC, fxcoudert commented on Formula/allure.rb
> +    system "#{bin}/allure", "--help"
We want a test that does a little bit more than output the help :)

2017-05-17 05:27 UTC, eroshenkoam commented on Formula/allure.rb
> +  homepage "https://github.com/allure-framework"
done

2017-05-17 05:30 UTC, eroshenkoam commented on Formula/allure.rb
> +
done

2017-05-17 05:30 UTC, eroshenkoam commented on Formula/allure.rb
> +    system "#{bin}/allure", "--help"
done

2017-05-17 05:30 UTC, eroshenkoam commented on Formula/allure.rb
> +  url "https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.0.1/allure-2.0.1.tgz"
We are prefer using bintray. It's bad place for binaries?

2017-05-17 09:42 UTC, fxcoudert approved these changes

2017-05-17 09:44 UTC, merged