tcptraceroute: pcap_version fix for 10.12.4+
Homebrew/homebrew-core pull request #13628
Opened 2017-05-16 19:36 UTC by cblecker

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Integrates a fix for libpcap linking in 10.12.4+, and introduces a test so we can tell when things break. Test can't be more complex than just a usage however, as executing the tool's function requires root.

2017-05-16 19:37 UTC, cblecker commented
This also crosses off a line of https://github.com/Homebrew/homebrew-core/issues/11898 :)

2017-05-16 19:38 UTC, ilovezfs commented
yay!

2017-05-17 09:30 UTC, fxcoudert requested changes

2017-05-17 09:30 UTC, fxcoudert commented on Formula/tcptraceroute.rb
> +    output = shell_output("#{bin}/tcptraceroute --help 2>&1", 1)
We probably want an actual test, maybe pinging a known host like 8.8.8.8?

2017-05-17 09:32 UTC, cblecker commented on Formula/tcptraceroute.rb
> +    output = shell_output("#{bin}/tcptraceroute --help 2>&1", 1)
Is there a safe way to invoke sudo in the test sandbox? tcptraceroute requires sudo to actually conduct a trace.

2017-05-17 09:39 UTC, fxcoudert commented on Formula/tcptraceroute.rb
> +    output = shell_output("#{bin}/tcptraceroute --help 2>&1", 1)
No, no `sudo` in tests…

2017-05-17 09:45 UTC, fxcoudert approved these changes

2017-05-17 09:48 UTC, closed without merging

2017-05-17 09:50 UTC, fxcoudert commented
Thanks @cblecker for the patch!