homebank 5.1.5
Homebrew/homebrew-core pull request #13657
Opened 2017-05-17 15:41 UTC by AAS

Created with `brew bump-formula-pr`.

2017-05-17 15:56 UTC, fxcoudert requested changes

2017-05-17 15:56 UTC, fxcoudert commented on Formula/homebank.rb
> +  version "5.1.5"
Please remove the `version` line, which is unnecessary.

2017-05-17 15:59 UTC, fxcoudert commented
FYI: I've reported the fact that `install-sh` is not executable as a bug to upstream https://bugs.launchpad.net/homebank/+bug/1691506

2017-05-17 16:17 UTC, AAS commented
I've removed version line as requested.

2017-05-17 22:56 UTC, fxcoudert approved these changes

2017-05-18 07:32 UTC, closed without merging

2017-05-18 07:32 UTC, fxcoudert commented
Thank you @AAS for the pull request!