warp 0.0.3
Homebrew/homebrew-core pull request #13677
Opened 2017-05-18 04:04 UTC by spolu

Created manually following:
- [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [Formula Cookbook](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md)

2017-05-18 04:28 UTC, spolu commented
Looking like a transient failure... will try to push a different sha to trigger a rebuild.

2017-05-18 15:07 UTC, fxcoudert requested changes

2017-05-18 15:07 UTC, fxcoudert commented on Formula/warp.rb
> +    :revision => "8a04cd7c95973e168a9bf2d2db6522574302164d"
We prefer a `.tar.gz` (e.g. https://github.com/spolu/warp/archive/v0.0.3.tar.gz) to a git tag

2017-05-18 15:07 UTC, fxcoudert commented on Formula/warp.rb
> +    system bin/"warp", "help"
Can we do a test that does more than just output the help?

2017-05-18 15:21 UTC, spolu commented on Formula/warp.rb
> +    :revision => "8a04cd7c95973e168a9bf2d2db6522574302164d"
I'll update that 👍

2017-05-18 15:22 UTC, spolu commented on Formula/warp.rb
> +    system bin/"warp", "help"
So ~anything else would rely on our servers being up and responding. Which is fine, if you think that's better?

2017-05-18 15:30 UTC, spolu commented
@fxcoudert PTAL

2017-05-18 15:46 UTC, bfontaine commented on Formula/warp.rb
> +    system bin/"warp", "help"
It’s fine.

2017-05-18 15:46 UTC, bfontaine commented on Formula/warp.rb
> +    ENV["GOHOME"] = buildpath
Why do you need to set `GOBIN` and `GOHOME`?

2017-05-18 15:48 UTC, spolu commented on Formula/warp.rb
> +    ENV["GOHOME"] = buildpath
To be perfectly honest I cargo-culted these ones, let me try to remove them

2017-05-18 15:52 UTC, spolu commented on Formula/warp.rb
> +    system bin/"warp", "help"
@bfontaine fine as in preferable to have a more complex test that relies on our server or fine as in the current state is OK?

2017-05-18 16:37 UTC, fxcoudert commented on Formula/warp.rb
> +    system bin/"warp", "help"
> preferable to have a more complex test that relies on our server

that

2017-05-18 18:33 UTC, spolu commented on Formula/warp.rb
> +    system bin/"warp", "help"
Sounds good! I'll work towards that. Thanks!

2017-05-19 15:57 UTC, spolu commented
r? @fxcoudert @bfontaine PTAL

Tests updated with a more meaningful test. Success means that warp is able to put the local terminal in raw mode and prepare everything for a session and attempts to connect to a random inexistent warp ID and exits properly with the expected error coming from the server.

2017-05-19 16:14 UTC, fxcoudert commented
Test is failing on CI:

```
==> /usr/local/Cellar/warp/0.0.3/bin/warp connect test-vhhwmvprwlmdyoqi
Error: warp: failed
Expected /\[Error\] Received warp_unknown/ to match "Connected to warp: test-vhhwmvprwlmdyoqi\n[Error] Not running in a terminal.\n".
```

can you update the test to match that message too?

2017-05-19 23:50 UTC, spolu commented
@fxcoudert oops. Fixed!

2017-05-20 18:35 UTC, fxcoudert approved these changes

2017-05-20 18:38 UTC, fxcoudert commented
Thanks @spolu for your contribution to Homebrew!

2017-05-20 18:38 UTC, closed without merging

2017-05-20 19:31 UTC, spolu commented
\o/