Import zeromq 4.1 from homebrew/versions
Homebrew/homebrew-core pull request #13696
Opened 2017-05-18 17:20 UTC by fvioz

Import formula zeromq 4.1 from homebrew/versions.  Latest version has some issues with ruby projects like https://github.com/chuckremes/ffi-rzmq-core/issues/15, 

This allow those users stay this this version until compatibility is added.

2017-05-18 20:19 UTC, fxcoudert commented
We already have `zeromq` (which is currently 4.2), `zeromq@3.2` and `zeromq@4.0` (all of which see already very little use, like 1–2% of the latest version). The goal of having versioned formulas is not to support every version released, but to allow some support for a prior version when many users or our own software depends on it.

Right now, I don't think there is a demonstrated need for yet another versioned zeromq formula.

2017-05-18 20:19 UTC, fxcoudert commented
Also, I don't see that homebrew-versions did ever have a `zeromq41` formula, so I don't see how this is an import from homebrew-versions.

2017-05-19 07:47 UTC, fvioz commented
@fxcoudert My bad I fix the homebrew-versions, about this formula for ruby users https://rubygems.org/gems/ffi-rzmq-core only the version 4.1.x works, currently there is no support for 4.2 the latest.

2017-05-19 08:21 UTC, fxcoudert commented
> only the version 4.1.x works, currently there is no support for 4.2 the latest

I guess this is an upstream decision they made, we cannot support every possible version… as I said, we already have 3.2 and 4.0

2017-05-19 08:39 UTC, MikeMcQuaid approved these changes
I'm OK with this given it's a listed version on their site: http://zeromq.org/intro:get-the-software

2017-05-19 08:46 UTC, fxcoudert commented on formula_renames.json
> +  "zeromq41": "zeromq@4.1"
This is incorrect, it is not a migration or formula rename as far as I can see…

2017-05-19 08:47 UTC, fxcoudert commented on Formula/zeromq@4.1.rb
> +    system "./autogen.sh" if build.head?
There is no head option here

2017-05-19 21:52 UTC, JCount commented on Formula/zeromq@4.1.rb
> +  deprecated_option "with-pgm" => "with-libpgm"
A new formulae shouldn't have, or need, `deprecated_option` mappings as their purpose is to provide backwards compatibility with prior installations of that same formula.

2017-05-20 18:35 UTC, fxcoudert requested changes

2017-05-20 18:35 UTC, fxcoudert commented on Formula/zeromq@4.1.rb
> +  end
No `bottle` block for a new formula: these are added automatically when we merge.

2017-05-22 08:34 UTC, fxcoudert approved these changes

2017-05-22 16:31 UTC, closed without merging

2017-05-22 16:31 UTC, JCount commented
Thank you very much for your first contribution to Homebrew, @fvioz!! 🎊