Update
Homebrew/homebrew-core pull request #13717
Opened 2017-05-19 08:34 UTC by jonmcadam

Updating to latest Jmeter version 3.2

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-19 08:51 UTC, fxcoudert submitted a review, later dismissed

2017-05-19 08:51 UTC, fxcoudert commented on Formula/jmeter.rb
>    sha256 "e697a17ef47f645c81f02c8f98f56400e2a182fa580904d329a0d277935edeec"
Update SHA-256 sum

2017-05-19 08:58 UTC, jonmcadam commented on Formula/jmeter.rb
>    sha256 "e697a17ef47f645c81f02c8f98f56400e2a182fa580904d329a0d277935edeec"
Apologies, not sure where to get that?

2017-05-19 09:19 UTC, ilovezfs submitted a review, later dismissed

2017-05-19 09:19 UTC, ilovezfs commented on Formula/jmeter.rb
> +  url "http://apache.mirror.anlx.net/jmeter/binaries/apache-jmeter-3.2.tgz"
Please keep the original URL, other than the version change.

2017-05-19 09:32 UTC, ilovezfs commented
Are there updates for the plugins?

2017-05-19 09:46 UTC, jonmcadam commented
Not that I am aware of

2017-05-22 10:07 UTC, fxcoudert requested changes
> JMeter requires a fully compliant JVM 8

(from upstream website) so please add a `depends_on :java => "1.8+"` line.

Also, please remove the `bottle` block and replace it with a `bottle :unneeded` line.

2017-05-25 10:28 UTC, closed without merging

2017-05-25 10:28 UTC, ilovezfs commented
@jonmcadam Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-05-25 10:29 UTC, ilovezfs commented
@fxcoudert you're welcome to make those changes in a separate PR.