pycodestyle 2.2.0 (new formula)
Homebrew/homebrew-core pull request #13991
Opened 2017-05-27 18:02 UTC by straxhaber

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-28 06:20 UTC, ilovezfs requested changes
Test is failing https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2047/version=sierra/testReport/junit/brew-test-bot/sierra/test_pycodestyle/

2017-05-28 11:34 UTC, bfontaine requested changes

2017-05-28 11:34 UTC, bfontaine commented on Formula/pycodestyle.rb
> +    system "#{bin}/testsuite/test_all.py"
The `test` block is here to check everything’s got installed and is running correctly; not to run the project’s test suite.

2017-06-13 21:39 UTC, JCount commented
@straxhaber Ping on this

2017-06-14 22:36 UTC, straxhaber commented
I have made changes to the formula that fix the issue. How should I go about submitting it? Do I just push a second commit on top of this one, or is there something else I should do?

2017-06-14 22:41 UTC, JCount commented
@straxhaber For now, just pushing the second commit to your branch is probably best.

2017-06-14 23:52 UTC, straxhaber commented
How is it now? Did I do the correct thing?

2017-06-14 23:53 UTC, straxhaber commented
oops, one sec -- I need to fix it

2017-06-15 08:12 UTC, bfontaine requested changes

2017-06-15 08:12 UTC, bfontaine commented on Formula/pycodestyle.rb
> +    system "#{bin}/pycodestyle.py", "--help"
Please write a test that does something more substantial than e.g. `--help` or `--version`. You could write a dummy Python file and assert its output on it. Something like so:
```ruby
(testpath/"dummy.py").write <<-EOS.undent
  print("hello I'm a Python file")
  # ...
EOS

assert_equal "...expected output...",
    shell_output("#{bin}/pycodestyle.py ... dummy.py")
```

2017-06-16 01:11 UTC, straxhaber commented
How's that?

2017-06-16 08:06 UTC, bfontaine approved these changes

2017-06-16 17:14 UTC, straxhaber commented
@ilovezfs just waiting on your approval. Is there anything else I should change/fix?

2017-06-16 17:53 UTC, ilovezfs requested changes
I'd also like to see the test block test for a style violation. Thanks!

2017-06-16 17:53 UTC, ilovezfs commented on Formula/pycodestyle.rb
> +    bin.install "pycodestyle.py"
```
bin.install "pycodestyle.py" => "pycodestyle"
```

2017-06-16 19:01 UTC, straxhaber commented
@ilovezfs How's that?

2017-06-16 19:02 UTC, straxhaber commented
Also, @ilovezfs @bfontaine would you rather I keep submitting additional commits or squash and force push? If the former, should I make the commit message the standardized format as I have been or make more meaningful commit messages?

2017-06-16 19:44 UTC, bfontaine commented
@straxhaber It’d be great if you could squash into one commit with the standardized format and force-push, thanks 😃

2017-06-16 20:11 UTC, straxhaber commented
@bfontaine @ilovezfs squashed!

2017-06-21 13:49 UTC, ilovezfs approved these changes

2017-06-21 13:51 UTC, closed without merging

2017-06-21 13:52 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @straxhaber! Without people like you submitting PRs we couldn't run this project. You rock!

2017-06-21 15:27 UTC, straxhaber commented
@ilovezfs! Thanks!