codelimit 0.6.0
Homebrew/homebrew-core pull request #139950
Opened 2023-08-19 16:19 UTC by robvanderleek

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2023-08-19 16:59 UTC, p-linnane requested changes

2023-08-19 16:59 UTC, p-linnane commented on Formula/c/codelimit.rb
> +
```suggestion
license "ISC"

```

2023-08-19 16:59 UTC, p-linnane commented on Formula/c/codelimit.rb
> +
```suggestion

```

2023-08-19 16:59 UTC, p-linnane commented on Formula/c/codelimit.rb
> +
The bottle block will be generated by our workflows if this PR is accepted.

2023-08-19 16:59 UTC, p-linnane commented on Formula/c/codelimit.rb
> +
```suggestion

```

2023-08-19 16:59 UTC, p-linnane commented on Formula/c/codelimit.rb
> +
```suggestion

```

2023-08-19 16:59 UTC, p-linnane commented on Formula/c/codelimit.rb
> +
```suggestion

```

2023-08-19 16:59 UTC, p-linnane commented on Formula/c/codelimit.rb
> +
```suggestion

```

2023-08-19 16:59 UTC, p-linnane commented on Formula/c/codelimit.rb
> +    virtualenv_create(libexec, "python3")
```suggestion

```

2023-08-19 16:59 UTC, p-linnane commented on Formula/c/codelimit.rb
> +  depends_on "python3"
```suggestion
  depends_on "python-certifi"
  depends_on "python-typing-extensions"
  depends_on "pygments"
  depends_on "python@3.11"
  depends_on "six"
```

2023-08-19 16:59 UTC, p-linnane commented on Formula/c/codelimit.rb
We'll need to add this to `pypi_formula_mappings.json` as well for the excluded resources.

2023-08-19 17:14 UTC, robvanderleek commented on Formula/c/codelimit.rb
> +  depends_on "python3"
I've added these dependencies.

2023-08-19 17:14 UTC, robvanderleek commented on Formula/c/codelimit.rb
I've added the excluded resources.

2023-08-19 17:16 UTC, p-linnane commented on Formula/c/codelimit.rb
Thanks. Can you please squash all the commits into one with the message `codelimit 0.6.0 (new formula)`?

2023-08-19 17:41 UTC, p-linnane commented
Thanks for the PR. Running `brew style --fix codelimit` once more should fix the last style error. Once that's done, can you please squash all the commits into one with the message `codelimit 0.6.0 (new formula)`?

2023-08-19 23:27 UTC, robvanderleek commented
> Thanks for the PR. Running `brew style --fix codelimit` once more should fix the last style error. Once that's done, can you please squash all the commits into one with the message `codelimit 0.6.0 (new formula)`?

I've squashed all commits 🙂  Thanks for the support.

2023-08-23 21:21 UTC, robvanderleek commented
Hi @p-linnane 

Is there any open review issue holding this PR back? Or will it be merged eventually?

2023-08-23 21:42 UTC, p-linnane approved these changes

2023-08-23 21:45 UTC, p-linnane commented
My mistake, I thought this finished running. Let me fix that.

2023-08-23 21:46 UTC, p-linnane commented
Also for future reference, branches from organizations cause issues with our merge process. Please open them from normal forks instead.

2023-08-23 22:10 UTC, p-linnane commented
@carlocab Can you take a look here? Not sure why the replacement workflow says this isn't mergable.

2023-08-24 08:18 UTC, robvanderleek commented
It seems I can't enable "Allow edits from maintainers" for this PR anymore. It was created from a [GH org fork](https://github.com/getcodelimit/homebrew-core). Let me know if I can help, no problem to open a new PR from a user fork if needed.

Thanks for all the support.

2023-08-25 16:22 UTC, p-linnane commented
If you can open a new PR from a user fork we can probably get this merged today.

2023-08-25 21:43 UTC, robvanderleek commented
Hi @p-linnane 

I've opened a PR from my own (user) fork: https://github.com/Homebrew/homebrew-core/pull/140506

KR, Rob

2023-08-25 22:26 UTC, closed without merging