ect 0.7 (new formula)
Homebrew/homebrew-core pull request #13993
Opened 2017-05-27 19:28 UTC by dave-atx

Efficient Compression Tool (or ECT) is a fast C++ file optimizer. It
supports PNG, JPEG, GZIP and ZIP files. It uses a combination of zopfli
and optipng to optimize images.

2017-05-27 19:39 UTC, dave-atx commented
@fhanau FYI

2017-05-28 06:17 UTC, ilovezfs requested changes

2017-05-28 06:17 UTC, ilovezfs commented on Formula/ect.rb
> +    cd "src" do
```
system "make", "-C", "src"
```

2017-05-28 06:17 UTC, ilovezfs commented on Formula/ect.rb
> +    bin.install "ECT"
Is there no `make install` target? If so, we should use that. If not, you'll need to request one upstream.

2017-05-28 06:17 UTC, ilovezfs commented on Formula/ect.rb
> +    ENV.deparallelize
Why is this needed? It will need to build without this and be fixed upstream before we can accept the formula.

2017-05-28 06:17 UTC, ilovezfs commented on Formula/ect.rb
> +    system "#{bin}/ECT", test_fixtures("test.png")
The test should validate this actually did something other than exit 0.

2017-05-28 07:28 UTC, fhanau commented on Formula/ect.rb
> +    bin.install "ECT"
@ilovezfs I think you're right. As a the author of ECT and a homebrew user myself, I think it's best if I make this software more installation-friendly (e. g. add make install, parallel build) and release a new version before it is added to homebrew.

2017-05-28 07:45 UTC, ilovezfs commented on Formula/ect.rb
> +    bin.install "ECT"
@fhanau cool thanks :heart:

2017-05-28 17:38 UTC, closed without merging