sbom-tool 1.5.1
Homebrew/homebrew-core pull request #140108
Opened 2023-08-21 22:46 UTC by chenrui333

Created by `brew bump`

---

Created with `brew bump-formula-pr`.

2023-08-22 00:33 UTC, ZhongRuoyu reviewed
Not marked as the latest release yet: https://github.com/microsoft/sbom-tool/releases

2023-08-22 07:56 UTC, SMillerDev requested changes, later dismissed

2023-08-22 07:56 UTC, SMillerDev commented on Formula/s/sbom-tool.rb
Needs a livecheck

2023-08-22 21:11 UTC, chenrui333 commented on Formula/s/sbom-tool.rb
livecheck :alert: :D

2023-08-24 04:19 UTC, chenrui333 commented
logged an upstream issue about the release status, microsoft/sbom-tool#321

2023-08-26 16:37 UTC, chenrui333 commented
now it is the latest release, and the checksum stays the same

2023-08-26 16:44 UTC, ZhongRuoyu approved these changes

2023-08-26 20:27 UTC, p-linnane approved these changes

2023-08-28 14:08 UTC, merged