fop 2.2
Homebrew/homebrew-core pull request #14025
Opened 2017-05-28 20:48 UTC by DomT4

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-28 23:25 UTC, dunn commented on Formula/fop.rb
> +    executable.chmod 0555
Huh, why does it need to be set to this?

2017-05-28 23:33 UTC, DomT4 commented on Formula/fop.rb
> +    executable.chmod 0555
Presume upstream screwed up the permissions on the shell script in this release, given it worked fine before.

2017-05-29 00:54 UTC, dunn commented on Formula/fop.rb
> +    executable.chmod 0555
I would expect `0755`, though.

2017-05-29 00:56 UTC, DomT4 commented on Formula/fop.rb
> +    executable.chmod 0555
Homebrew fixes to [0555 I believe](https://github.com/Homebrew/brew/blob/c9c7f462d37500549127efba96c7a25e5c70de4a/Library/Homebrew/cleaner.rb#L102-L105)?

2017-05-29 01:00 UTC, DomT4 commented on Formula/fop.rb
> +    executable.chmod 0555
```
gstat -c "%a %n" /usr/local/opt/openssl/bin/openssl
555 /usr/local/opt/openssl/bin/openssl

gstat -c "%a %n" /usr/local/opt/botan/bin/botan
555 /usr/local/opt/botan/bin/botan
```
etc. I know `0755` tends to be used in formulae but I got the impression Homebrew corrected to `0555` behind the scenes.

2017-05-29 04:14 UTC, dunn commented on Formula/fop.rb
> +    executable.chmod 0555
TIL!

2017-05-29 05:20 UTC, ilovezfs requested changes
Let's get the permissions fixed upstream before merging this.

2017-05-29 14:44 UTC, DomT4 commented
I mean that's your choice but... https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-5661 😓.

2017-05-29 19:07 UTC, JCount commented
https://issues.apache.org/jira/browse/FOP-2708

2017-05-29 19:08 UTC, DomT4 commented
Thanks @JCount, appreciate you taking the time 🙇. Was on my list but wanted to tidy up the couple things I highlighted in Mike's Rubocop PR in core first before I forgot those, heh.

2017-05-30 17:28 UTC, ilovezfs approved these changes

2017-05-30 18:06 UTC, closed without merging

2017-05-30 18:07 UTC, JCount commented
no more :ant:

2017-05-30 18:10 UTC, DomT4 commented
Thanks!