asdf 0.3.0 (new formula)
Homebrew/homebrew-core pull request #14058
Opened 2017-05-29 19:28 UTC by vicendominguez

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-30 10:39 UTC, vicendominguez commented
😢 asdf keeps that structure..... any idea?

2017-06-03 15:08 UTC, dunn commented on Formula/asdf.rb
> +    #########################################
Don't add these lines.  Keep it concise, like [`bash-preexec.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bash-preexec.rb).

2017-06-03 15:09 UTC, dunn commented
I wonder if this formula should be named `asdf-vm`, to avoid confusion with https://common-lisp.net/project/asdf/

2017-06-03 15:39 UTC, vicendominguez commented on Formula/asdf.rb
> +    #########################################
@dunn Just to make sure I understand correctly, are you speaking about the `######` lines?

2017-06-03 15:41 UTC, vicendominguez commented
Hey @dunn thx for answering......

On the last comment, I don't have any problem to change the name but my main concern, because I don't know the other project, is if we are using the same binary name......any idea?

2017-06-03 16:15 UTC, dunn commented on Formula/asdf.rb
> +    #########################################
Yeah, the caveats should just be the two lines of text.

2017-06-03 16:19 UTC, dunn commented
> I don't have any problem to change the name but my main concern, because I don't know the other project, is if we are using the same binary name......any idea?

No, that ASDF isn't in Homebrew.  At first I thought this was a PR to add _it_, since it's also a dependency management tool.  But I don't think it will ever be in Homebrew, and it's probably not as well-known as I think.  So on second thought you can leave the name of this formula as-is.

2017-06-03 16:26 UTC, vicendominguez commented
👆 Ok Alex, thanks for your help, here we have the correct caveat lines....(I hope)

2017-06-03 19:25 UTC, dunn requested changes

2017-06-03 19:25 UTC, dunn commented on Formula/asdf.rb
> +  depends_on "coreutils" => :run
These don't all have to be `:run`; that's only used for dependencies that are normally build-time-only, like automake, autoconf, and libtool.

2017-06-03 19:26 UTC, dunn commented
There's an audit failure too:
```
Error: 1 problem in 1 formula
asdf:
  * Non-executables were installed to "/usr/local/opt/asdf/bin"
    The offending files are:
      /usr/local/opt/asdf/bin/private
```
Can that be installed somewhere else, like `libexec`?

2017-06-03 20:03 UTC, vicendominguez commented on Formula/asdf.rb
> +  depends_on "coreutils" => :run
Hello again @dunn,

As you saw, asdf is a version manager which uses some plugins to control the version of the software you want, that version of the software and those plugins requires a build process. I am only following their recommendation, in the [README](https://github.com/asdf-vm/asdf/blob/master/README.md) you can read:

```
For most plugins, it is good if you have installed the following packages OR their equivalent on your OS

OS X: Install these via homebrew coreutils automake autoconf openssl libyaml readline libxslt libtool unixodbc
```

coreutils, automake,  libtool.... are coming from there 😅 . Removing them you will break the main feature imo.... I can not tell something else... what is your recommendation?

2017-06-03 21:20 UTC, dunn commented on Formula/asdf.rb
> +  depends_on "coreutils" => :run
I mean you can change it to this:
```ruby
  depends_on "autoconf" => :run
  depends_on "automake" => :run
  depends_on "libtool" => :run

  depends_on "coreutils"
  depends_on "libyaml"
  depends_on "openssl"
  depends_on "readline"
  depends_on "unixodbc"

2017-06-03 21:33 UTC, vicendominguez commented on Formula/asdf.rb
> +  depends_on "coreutils" => :run
got it 👍

2017-06-03 23:02 UTC, vicendominguez commented
hey @dunn , all changes done :) In this moment tests are failing but I don't know why

2017-06-03 23:30 UTC, dunn commented
```
Error: 2 problems in 1 formula
asdf:
  * Dir["bin/private"] is unnecessary; just use "bin/private"
  * "#{prefix}/lib" should be "#{lib}"

2017-06-04 07:14 UTC, vicendominguez commented
🎉  GREEN! 👆

2017-06-04 15:02 UTC, dunn approved these changes

2017-06-04 15:05 UTC, closed without merging

2017-06-04 15:05 UTC, dunn commented
Thanks for contributing to Homebrew!  Merged this as 37954ce7325f848f5867b9e320a8e91895d7d619.