pyenv 2.3.35
Homebrew/homebrew-core pull request #140603
Opened 2023-08-27 08:40 UTC by dnhn

Created by `brew bump`

-----

Created with `brew bump-formula-pr`.

2023-08-27 09:55 UTC, ZhongRuoyu submitted a review, later dismissed

2023-08-27 09:58 UTC, ZhongRuoyu requested changes

2023-08-27 09:58 UTC, ZhongRuoyu commented on Formula/p/pyenv.rb
> +  url "https://github.com/pyenv/pyenv/archive/refs/tags/v2.3.35.tar.gz"
It seems that upstream mistakenly tagged `v2.3.35` while it should be `v2.3.25`.

2023-08-27 10:05 UTC, closed without merging

2023-08-28 01:22 UTC, chenrui333 commented
https://github.com/pyenv/pyenv/issues/2766

2023-08-29 08:52 UTC, anton-petrov commented
wrong tag removed