git-branchless 0.8.0
Homebrew/homebrew-core pull request #140742
Opened 2023-08-29 04:01 UTC by chenrui333

Created by `brew bump`

---

Created with `brew bump-formula-pr`.

2023-08-29 04:20 UTC, chenrui333 commented
https://github.com/arxanas/git-branchless/releases

2023-08-30 07:39 UTC, SMillerDev requested changes, later dismissed
We should add a livecheck if they have pre-releases

2023-08-30 22:45 UTC, chenrui333 commented
pivot the PR to do the livecheck stuff.

2023-08-31 03:27 UTC, samford approved these changes

2023-08-31 03:42 UTC, merged