Add new Formula, Grakn.ai
Homebrew/homebrew-core pull request #14116
Opened 2017-05-31 16:32 UTC by merqurio

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-05-31 16:40 UTC, merqurio commented
working on the rubocop problem... not sure why is failing

2017-06-01 09:26 UTC, MikeMcQuaid requested changes

2017-06-01 09:26 UTC, MikeMcQuaid commented on Formula/grakn.rb
> +    # Set where the executable is
You can remove all these comments, they are self-explanatory, thanks!

2017-06-01 09:26 UTC, MikeMcQuaid commented on Formula/grakn.rb
> +    assert_match /Engine has stopped\nCassandra has stopped/i, shell_output("#{bin}/grakn.sh status", 0)
The `0` second argument is unnecessary as it's the default. Shorten the regex or split this onto two lines so it fits in 80 characters. Thanks!

2017-06-01 09:26 UTC, MikeMcQuaid commented on Formula/grakn.rb
> +  end
You can remove all these caveats as they are mostly not Homebrew specific, thanks!

2017-06-01 13:21 UTC, merqurio commented
Thanks for the suggestions @MikeMcQuaid, should be ok now.

2017-06-02 14:56 UTC, MikeMcQuaid approved these changes

2017-06-02 15:04 UTC, merged

2017-06-02 15:04 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!