libmypaint 1.3.0
Homebrew/homebrew-core pull request #14277
Opened 2017-06-05 20:26 UTC by blackwarthog

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-06-08 07:10 UTC, ilovezfs requested changes

2017-06-08 07:10 UTC, ilovezfs commented on Formula/libmypaint.rb
> +    ENV.deparallelize
Why is this needed? Please open an issue upstream reporting this.

2017-06-08 07:10 UTC, ilovezfs commented on Formula/libmypaint.rb
> +    system "./autogen.sh" if build.head?
Please remove this since there's no `head` spec in the formula.

2017-06-08 19:05 UTC, blackwarthog commented on Formula/libmypaint.rb
> +    system "./autogen.sh" if build.head?
done

2017-06-08 19:06 UTC, blackwarthog commented on Formula/libmypaint.rb
> +    ENV.deparallelize
it's my mistake. i've removed this line already

2017-06-08 19:06 UTC, blackwarthog commented
fixed

2017-06-10 15:02 UTC, dunn commented on Formula/libmypaint.rb
> +  homepage "https://github.com/json-c/json-c/wiki"
Why is this the homepage? Shouldn't it be http://mypaint.org?

2017-06-10 19:03 UTC, blackwarthog commented on Formula/libmypaint.rb
> +  homepage "https://github.com/json-c/json-c/wiki"
oops

2017-06-10 19:05 UTC, blackwarthog commented on Formula/libmypaint.rb
> +  homepage "https://github.com/json-c/json-c/wiki"
i've replaced link to https://github.com/mypaint/libmypaint/wiki because http;//mypaint.org contains too little information about libmypaint

2017-06-10 19:06 UTC, blackwarthog commented
fixed again

2017-06-10 21:59 UTC, dunn commented
Cool, I'm happy if @ilovezfs is.

2017-06-11 18:18 UTC, ilovezfs approved these changes

2017-06-12 01:54 UTC, closed without merging

2017-06-12 01:54 UTC, dunn commented
Thanks! Merged as 159a7d57d9544d666dbb7cc614e7fa85de13f87f.