migrate 3.0.1 (new formula)
Homebrew/homebrew-core pull request #14297
Opened 2017-06-06 08:18 UTC by mkozjak

Signed-off-by: mkozjak <kozjakm1@gmail.com>

- [✓] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [✓] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [✓] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [✓] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

```migrate``` is a Golang command line interface tool for the https://github.com/mattes/migrate library.

It pulls source from the stable release tarball, uses brew go to install from source, and installs the migrate binary to /usr/local/bin/ via formula's ```bin.install``` function.

Resolves mattes/migrate#156.

2017-06-08 07:07 UTC, ilovezfs requested changes

2017-06-08 07:07 UTC, ilovezfs commented on Formula/migrate.rb
> +    url "https://github.com/lib/pq.git",
Please open an issue upstream requesting that this be vendored.

2017-06-08 07:07 UTC, ilovezfs commented on Formula/migrate.rb
> +    system bin/"migrate", "-version"
We'll need a test that exercises the software's functionality here.

2017-06-25 17:33 UTC, JCount commented
@mkozjak Any news here?

2017-06-25 18:02 UTC, mkozjak commented
@JCount will be done soon! Goose v2.0.0 is out and that will ease the task at hand pretty much. :)

2017-06-25 23:47 UTC, JCount commented
@mkozjak Thanks for the response.

2017-06-26 14:21 UTC, JCount commented
Closing this for now, as the OP is no longer using this software and thinks that it currently isn't appropriate for a brew formula.

2017-06-26 14:21 UTC, closed without merging