mpd: add option --with-libao
Homebrew/homebrew-core pull request #14309
Opened 2017-06-06 16:42 UTC by Hamuko

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This change allows compiling MPD with libao support. The reason for this is that the default CoreAudio output plugin for MPD hasn't been maintained for a long time and can work quite poorly, as it did for me. MacPorts maintainers have switched their MPD installations to libao a few years ago, so now Homebrew would also have the same option.

https://trac.macports.org/ticket/46325
https://trac.macports.org/ticket/46861

2017-06-07 08:20 UTC, ilovezfs requested changes

2017-06-07 08:20 UTC, ilovezfs commented on Formula/mpd.rb
> +  option "with-libao", "Build with libao support"
This description is added automatically because you have `depends_on "libao" => :optional` below. So this line can be removed.

2017-06-07 09:53 UTC, Hamuko commented
Fixed.

2017-06-08 06:41 UTC, ilovezfs approved these changes

2017-06-08 06:42 UTC, merged

2017-06-08 06:42 UTC, ilovezfs commented
Thanks for the pull request @Hamuko :+1:

2018-03-07 15:35 UTC, jsheltonwilson commented
So I am a complete novice but I am trying to get my mpd to stop stuttering, where do I add this into the  mpd.rb?

2018-03-07 15:36 UTC, Hamuko commented
You don't have to add it to mpd.rb. Just run `brew install mpd --with-libao`.

2018-03-07 15:41 UTC, jsheltonwilson commented
should I uninstall my previous download of mpd first or will it just add the libao support to my existing version? thanks for such a quick reply.

2018-03-07 15:43 UTC, Hamuko commented
Either uninstall the previous installation and install, or use `brew reinstall mpd --with-libao`. At least I think that should work. If the reinstall command doesn't work, uninstall your current version of MPD and then run the install.

2018-03-07 15:48 UTC, jsheltonwilson commented
The reinstall command worked but produced three errors, I think I will just uninstall my version of mpd and then reinstall. Thanks so much for the help!