bach 0.0.10 (new formula)
Homebrew/homebrew-core pull request #14314
Opened 2017-06-06 18:47 UTC by fabiob

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-06-06 18:49 UTC, fabiob commented
@compose @codepope

2017-06-10 14:36 UTC, dunn commented on Formula/bach.rb
> +  url "https://github.com/compose/bach/releases/download/0.0.10/bach_Darwin_x86_64.tar.gz"
This needs to be compiled from source.

2017-06-10 20:49 UTC, fabiob commented on Formula/bach.rb
> +  url "https://github.com/compose/bach/releases/download/0.0.10/bach_Darwin_x86_64.tar.gz"
I've updated the formula so it builds from source.

2017-06-10 21:55 UTC, dunn commented on Formula/bach.rb
> +  url "https://github.com/compose/bach.git", :tag => "0.0.10"
If there aren't submodules or anything requiring a clone, we prefer the tarball: https://github.com/compose/bach/archive/0.0.10.tar.gz

If we do need to fetch it with git, add a `revision` as well so we can catch if it's re-tagged.

2017-06-25 17:35 UTC, JCount commented
@fabiob Any progress with this?

2017-06-27 12:09 UTC, ilovezfs requested changes

2017-06-27 12:09 UTC, ilovezfs commented on Formula/bach.rb
> +    rm_rf "vendor" # fix for https://github.com/compose/bach/issues/13
We'll need to wait for a new release that has a fully up to date vendor directory.

2017-07-31 15:21 UTC, ilovezfs commented
@fabiob there is now a [0.1.0 release](https://github.com/compose/bach/releases/tag/0.1.0) if you'd like to refresh this!

2017-08-20 18:56 UTC, ilovezfs commented
@fabiob thanks for opening this. I'm going to close it for now since it's for an outdated version, but please feel free to open a new PR for 0.1.0 if you'd still like to see this added to Homebrew.

2017-08-20 18:56 UTC, closed without merging