overmind 1.0.4 (new formula)
Homebrew/homebrew-core pull request #14508
Opened 2017-06-12 08:46 UTC by demiazz

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-06-12 14:11 UTC, ilovezfs requested changes

2017-06-12 14:11 UTC, ilovezfs commented on Formula/overmind.rb
> +    system "#{bin}/overmind", "--version"
This will need to be a test that verifies the functionality of the software.

2017-06-12 14:11 UTC, ilovezfs commented on Formula/overmind.rb
> +    (buildpath/"src/github.com/DarthSim/overmind/").install Dir["*"]
```
(buildpath/"src/github.com/DarthSim/overmind").install buildpath.children

2017-06-12 14:11 UTC, ilovezfs commented on Formula/overmind.rb
> +  depends_on "go" => :build
Build-time deps should be above other deps.

2017-06-12 14:11 UTC, ilovezfs commented on Formula/overmind.rb
> +
Please delete this blank line.

2017-06-12 16:59 UTC, ilovezfs commented on Formula/overmind.rb
> +    (testpath/"Procfile").write("test: echo 'test message'")
You could also add an assert above this for what happens when Procfile doesn't exist.

2017-06-12 23:54 UTC, ilovezfs approved these changes

2017-06-12 23:55 UTC, closed without merging

2017-06-12 23:55 UTC, ilovezfs commented
Thanks for the new formula @demiazz!

2017-06-13 07:12 UTC, demiazz commented
Thanks for Homebrew and review!