docker2aci v0.16.0 (new formula)
Homebrew/homebrew-core pull request #14526
Opened 2017-06-12 15:40 UTC by bcg62

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-06-12 16:25 UTC, bfontaine commented on Formula/docker2aci.rb
> +    ENV["GOARCH"] = MacOS.prefer_64_bit? ? "amd64" : "386"
You probably don’t need to set these two variables since we’re not doing cross-compilation here.

2017-06-12 16:25 UTC, bfontaine requested changes

2017-06-12 16:25 UTC, bfontaine commented on Formula/docker2aci.rb
> +    ln_s buildpath/"src", buildpath / "src/github.com/appc/docker2aci"
Please remove spaces before and after `/`: `buildpath/"src/github.com/appc/docker2aci"`.

2017-06-12 18:59 UTC, bcg62 commented
@bfontaine fixed

2017-06-12 22:21 UTC, bfontaine commented on Formula/docker2aci.rb
> +    ENV["GOROOT"] = Formula["go"].opt_libexec
Is that one needed?

2017-06-13 12:33 UTC, bcg62 commented on Formula/docker2aci.rb
> +    ENV["GOROOT"] = Formula["go"].opt_libexec
@bfontaine removed.

2017-06-13 14:00 UTC, bfontaine approved these changes

2017-06-13 14:02 UTC, ilovezfs requested changes

2017-06-13 14:02 UTC, ilovezfs commented on Formula/docker2aci.rb
> +    cd "src/github.com/appc/docker2aci" do
This `cd` is not needed.

2017-06-13 14:11 UTC, ilovezfs commented on Formula/docker2aci.rb
> +    cd "src/github.com/appc/docker2aci" do
```
  def install
    ENV["GOPATH"] = buildpath
    (buildpath/"src/github.com/appc").mkpath
    ln_s buildpath, buildpath/"src/github.com/appc/docker2aci"
    system "go", "build", "-o", bin/"docker2aci", "-ldflags",
           "-X github.com/appc/docker2aci/lib.Version=#{version}", 
           "github.com/appc/docker2aci"
  end
```

2017-06-16 21:44 UTC, bcg62 commented
@ilovezfs fixed up

2017-06-21 13:25 UTC, bcg62 commented
@ilovezfs this look ok to merge now?

2017-06-24 18:37 UTC, dunn commented
@BrewTestBot test this please

2017-06-24 19:01 UTC, closed without merging

2017-06-24 19:01 UTC, dunn commented
Looks good, thanks! Merged as ee2a60b0c50bdc9518ca7fda97eb0f137b21e9ce.