fabric 1.13.2_1
Homebrew/homebrew-core pull request #14530
Opened 2017-06-12 18:12 UTC by ploxiln

with significant update to (vendored for homebrew) paramiko 2.2.0
also remove some apparently un-needed vendored dependencies

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

paramiko 2.2.0 has some fixes that interest me, and also adds support for ed25519 host keys and auth keys.

The "apparently un-needed vendored dependencies" were introduced in 5e8b75508c56c704c3a26c2bbe5b485b62d782f9 while replacing "setuptools". I'm not sure under which circumstances these were needing - the formula works for me without them. I'm fine with putting them back if it turns out they really are needed for some setups.

2017-06-13 10:20 UTC, ilovezfs commented
@ploxiln Regarding setuptools see https://setuptools.readthedocs.io/en/latest/history.html#v36-0-0

2017-06-13 16:56 UTC, ploxiln commented
Hmm I see. Anyway, setuptools itself was no longer in the list of resources installed. And, setuptools is used, by the system python in this case, before any of the resources are installed:

```
==> Upgrading 1 outdated package, with result:
fabric 1.13.2_1
==> Upgrading fabric 
==> Using the sandbox
==> Downloading https://github.com/fabric/fabric/archive/1.13.2.tar.gz
Already downloaded: /Users/pierce/Library/Caches/Homebrew/fabric-1.13.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/5c/79/5dae7494b9f5ed061cff9a8ab8d6e1f02db352f3facf907d9eb614fb80e9/virtualenv-15.0.2.tar.gz
Already downloaded: /Users/pierce/Library/Caches/Homebrew/fabric--homebrew-virtualenv-15.0.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/fabric--homebrew-virtualenv-20170612-65310-1b1712y/target --single-version-externally-managed --r
==> python -s /tmp/fabric--homebrew-virtualenv-20170612-65310-1b1712y/target/bin/virtualenv -p python /usr/local/Cellar/fabric/1.13.2_1/libexec
...
```

And, virtualenv, installed for/by `virtualenv_install_with_resources` vendors its own setuptools, and so (presumably) all of that vendored setuptools dependencies as well: https://github.com/pypa/virtualenv/tree/master/virtualenv_support

So it seems like installing setuptools and/or its dependencies inside the virtualenv has not been needed for a while. (And setuptools has not been installed in the virtualenv since 5e8b75508c56c704c3a26c2bbe5b485b62d782f9, and now this PR removes just its (apparently temporary) dependencies, and it still seems to work with the system python.)

2017-06-13 17:34 UTC, ploxiln commented
... hold off merging though, a bug was discovered in paramiko-2.2.0 related to ed25519 host keys

2017-06-13 17:37 UTC, ilovezfs requested changes
what he said

2017-06-13 20:59 UTC, ploxiln commented
updated to use paramiko-2.2.1 and ready-to-go IMHO

2017-06-16 15:44 UTC, ploxiln commented
friendly ping

2017-06-16 15:53 UTC, ilovezfs commented
Thanks for the ping!

2017-06-16 15:54 UTC, ilovezfs approved these changes

2017-06-16 15:54 UTC, ilovezfs commented
@BrewTestBot test this please

2017-06-16 16:12 UTC, closed without merging

2017-06-16 16:12 UTC, ilovezfs commented
Thanks for the PR @ploxiln! :sparkler:

2017-06-16 17:00 UTC, ploxiln commented
thank you for maintaining Homebrew, @ilovezfs :)

2017-06-16 17:28 UTC, ilovezfs commented
You're welcome!