apng2gif 1.8 (new formula)
Homebrew/homebrew-core pull request #14582
Opened 2017-06-14 08:12 UTC by passerbyid

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Add `apng2gif`, a tool to convert APNG animations into animated GIF format.

2017-06-14 14:14 UTC, ilovezfs commented on Formula/apng2gif.rb
> +    inreplace "Makefile", "gcc", ENV.cc
superenv takes care of this automatically

2017-06-14 14:14 UTC, ilovezfs commented on Formula/apng2gif.rb
> +    inreplace "Makefile", "-s", ""
It seems to build without this. Why do you think it is needed?

2017-06-14 14:20 UTC, ilovezfs commented on Formula/apng2gif.rb
> +    system bin/"apng2gif", testpath/"test.png"
```
 assert_predicate testpath/"test.gif", :exist?, "Failed to create test.gif"
```

2017-06-15 03:17 UTC, passerbyid commented on Formula/apng2gif.rb
> +    inreplace "Makefile", "gcc", ENV.cc
So, should I remove it?
This line was imitate by [typespeed.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/typespeed.rb)

2017-06-15 03:19 UTC, passerbyid commented on Formula/apng2gif.rb
> +    inreplace "Makefile", "-s", ""
ld(1) Manual say:

```
-s Completely strip the output, including removing the symbol table. This file format variant is no longer supported. This option is obsolete
```
And [test failed](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2998/version=yosemite/testReport/brew-test-bot/yosemite/install_apng2gif/) when with `-s` (only in yosemite)

```
==> make
gcc -Wall -pedantic -O2 -o apng2gif apng2gif.cpp -s -lstdc++ -lm -lpng -lz
ld: internal error: atom not found in symbolIndex(__ZN5Image4freeEv) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1
```

So I thought that I should remove it, and [test passed](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/3000/version=yosemite/testReport/brew-test-bot/yosemite/install_apng2gif/) after that.

```
==> make
clang -Wall -pedantic -O2 -o apng2gif apng2gif.cpp  -lstdc++ -lm -lpng -lz
==> Cleaning
```

Did I miss something?

2017-06-15 03:24 UTC, passerbyid commented on Formula/apng2gif.rb
> +    system bin/"apng2gif", testpath/"test.png"
Got it.

2017-06-15 08:10 UTC, ilovezfs commented on Formula/apng2gif.rb
> +    inreplace "Makefile", "gcc", ENV.cc
Yes, please remove it.

2017-06-15 08:11 UTC, ilovezfs requested changes

2017-06-15 08:11 UTC, ilovezfs commented on Formula/apng2gif.rb
> +    inreplace "Makefile", "-s", ""
This will need to be reported and fixed upstream in that case, as we don't want to be patching the Makefile of a brand new formula.

2017-06-15 18:36 UTC, passerbyid commented on Formula/apng2gif.rb
> +    inreplace "Makefile", "-s", ""
Got it.

2017-07-09 19:16 UTC, JCount commented
@ilovezfs What're your current thoughts here?

2017-07-31 15:23 UTC, ilovezfs approved these changes

2017-07-31 16:06 UTC, closed without merging

2017-07-31 16:06 UTC, JCount commented
@passerbyid Thank you for your contribution to Homebrew!! 🎆