iamy 2.0.0 (new formula)
Homebrew/homebrew-core pull request #14665
Opened 2017-06-16 16:33 UTC by orien

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-06-16 17:54 UTC, ilovezfs requested changes

2017-06-16 17:54 UTC, ilovezfs commented on Formula/iamy.rb
> +    system bin/"iamy", "--help"
This will need to be a test that verifies the functionality of the software.

2017-06-17 02:01 UTC, orien commented on Formula/iamy.rb
> +    system bin/"iamy", "--help"
I agree. However it is troublesome. The tool has two commands: `pull` and `push`. `pull` connects to an AWS account and writes the current IAM configuration to a YAML representation. Conversely, `push` loads IAM configuration from YAML files and applies it to an AWS account. These operations cannot be exercised without credentials to an active AWS account. Further, I cannot see any automated tests in the source repository.

@ilovezfs What do you suggest in this case?

2017-06-17 10:04 UTC, ilovezfs commented on Formula/iamy.rb
> +    system bin/"iamy", "--help"
Something like this should be OK:
```
    output = shell_output("#{bin}/iamy pull 2>&1", 1)
    assert_match "Can't determine the AWS account", output
```

2017-06-17 10:26 UTC, orien commented on Formula/iamy.rb
> +    system bin/"iamy", "--help"
Thanks @ilovezfs. Will do.

2017-06-17 10:30 UTC, orien commented on Formula/iamy.rb
> +    system bin/"iamy", "--help"
Although this will fail for users that have AWS credentials set in their environment.

2017-06-17 10:31 UTC, ilovezfs commented on Formula/iamy.rb
> +    system bin/"iamy", "--help"
You can unset them.
```
ENV.delete "AWS_ACCESS_KEY"
ENV.delete "AWS_SECRET_KEY"
```
is probably sufficient.

2017-06-17 10:42 UTC, orien commented on Formula/iamy.rb
> +    system bin/"iamy", "--help"
Thanks @ilovezfs. Your recommendation has been applied.

2017-06-17 10:50 UTC, ilovezfs approved these changes

2017-06-17 11:22 UTC, closed without merging

2017-06-17 11:23 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @orien! Without people like you submitting PRs we couldn't run this project. You rock!