uipathcli 1.0.87 (new formula)
Homebrew/homebrew-core pull request #147075
Opened 2023-09-29 10:08 UTC by constantinmuraru

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2023-09-29 19:49 UTC, p-linnane requested changes

2023-09-29 19:49 UTC, p-linnane commented on Formula/u/uipathcli.rb
> +      revision: "17a981bebaa7095ff2b3afd3231223fceb69b8ed"
Are we abl to use a tarball instead of checking out the tag?

2023-10-03 17:51 UTC, p-linnane commented on Formula/u/uipathcli.rb
> +    etc.install "uipath-definitions"
This is something you will need to ask upstream to support, since they have the path hardcoded.

2023-10-03 18:01 UTC, constantinmuraru commented on Formula/u/uipathcli.rb
> +    etc.install "uipath-definitions"
Yeah, I'm working at Uipath. We can make the necessary change to not have it hard coded. The question is what would be the best approach to change it to.

We tried a couple of approaches:
1. Look for the jsons in the home folder. However, I couldn't find any other formula copying files to the home folder, when doing `brew install`. Nor was I able to make it work:
```
    target_dir = File.expand_path("~/.uipath/definitions")
    
    FileUtils.mkdir_p(target_dir)
    FileUtils.cp_r("definitions", target_dir)
    FileUtils.chown_R(ENV["USER"], nil, target_dir)
```

2. Look for the jsons by [resolving the symlink](https://github.com/UiPath/uipathcli/pull/94) that brew does.
```
uipath
Error reading definition files from folder '/opt/homebrew/Cellar/uipathcli/1.0.1/bin/definitions': open /opt/homebrew/Cellar/uipathcli/1.0.1/bin/definitions: no such file or directory
➜  ~ ls -l /opt/homebrew/Cellar/uipathcli/1.0.1/
total 56
-rw-r--r--  1 constantin.muraru  admin    926 Oct  3 15:57 INSTALL_RECEIPT.json
-rw-r--r--  1 constantin.muraru  staff   1058 Sep 29 13:37 LICENSE
-rw-r--r--  1 constantin.muraru  staff  20142 Oct  3 15:54 README.md
drwxr-xr-x  3 constantin.muraru  admin     96 Oct  3 15:57 bin
drwxr-xr-x  6 constantin.muraru  staff    192 Sep 29 13:37 definitions
```

3. Set up a `UIPATH_DEFINITIONS_PATH` env var. This was the initial approach in the formula, but wasn't so friendly.

2023-10-05 08:24 UTC, SMillerDev commented on Formula/u/uipathcli.rb
> +    etc.install "uipath-definitions"
Why not just install them in the standard UNIX location for configuration (`.etc`) or other pkg files (`.pkgshare`)

2023-10-05 11:17 UTC, constantinmuraru commented on Formula/u/uipathcli.rb
> +    etc.install "uipath-definitions"
thanks. we ended up embedding the configurations in the executable, which eliminates the problem.

2023-11-03 00:23 UTC, closed without merging