goose 1.0.0 (new formula)
Homebrew/homebrew-core pull request #14724
Opened 2017-06-19 12:29 UTC by mkozjak

Signed-off-by: Mario Kozjak <kozjakm1@gmail.com>

- [✓] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [✓] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [✓] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [✓] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

```goose``` is a Golang command line interface tool for the https://github.com/pressly/goose library.

It pulls source from the stable release tarball, uses brew go to install from source, and installs the migrate binary to /usr/local/bin/ via formula's ```bin.install``` function.

Resolves pressly/goose#42.

2017-06-19 12:48 UTC, ilovezfs requested changes
In new formulae, we generally want to avoid `go_resource` blocks. Please file an issue upstream requesting use of a Go vendor directory or one of the various Go vendoring tools.

2017-06-19 12:58 UTC, mkozjak commented
@ilovezfs: I guess a good example is the 'hugo' formula? I believe the dependency should then have a 'vendor' directory with a vendor.json file in it when the vendoring tool is govendor...

2017-06-19 13:00 UTC, ilovezfs commented
`flint-checker` is a good example for the basic Go vendor directory. Take a look at https://github.com/pengwynn/flint/issues/46.

2017-06-19 13:08 UTC, mkozjak commented
Created an issue. Let's hope for the best. :)

2017-06-19 13:08 UTC, ilovezfs commented
Thanks @mkozjak!

2017-06-20 16:28 UTC, mkozjak commented
@ilovezfs Somehow this got closed while I was syncing with upstream. Can you, please, reopen? Or should I create a new issue?

2017-06-20 16:29 UTC, ilovezfs commented
It got closed because it had 0 diff to master.

2017-06-20 16:30 UTC, mkozjak commented
Thanks! Now we only wait for ```dep```.

2017-06-20 16:32 UTC, ilovezfs commented
```
require "language/go"

class Goose < Formula
  desc "Go Language's command-line interface for database migrations"
  homepage "https://github.com/pressly/goose"
  url "https://github.com/pressly/goose/archive/v1.0.tar.gz"
  sha256 "d1b84411dcb5abc211d52de65f1eeaa9ea4a1eeaee0400b3380d9d24e1dc8b1b"
  head "https://github.com/pressly/goose.git"

  depends_on "go" => :build

  go_resource "github.com/golang/dep" do
    url "https://github.com/golang/dep.git",
        :revision => "c79b048e07eccf76d323d4c2e88d7c6d72ea735f"
  end

  def install
    ENV["GOPATH"] = buildpath

    (buildpath/"src/github.com/pressly/goose").install buildpath.children
    Language::Go.stage_deps resources, buildpath/"src"

    cd "src/github.com/golang/dep" do
      system "go", "install", "github.com/golang/dep/cmd/dep"
    end
    ENV.append_path "PATH", buildpath/"bin"

    cd "src/github.com/pressly/goose" do
      system "dep", "ensure"
      system "go", "build", "-o", "goose", "github.com/pressly/goose/cmd/goose"
      bin.install "goose"
    end
  end

  test do
    system bin/"goose", "sqlite3", "./foo.db", "status", "create"
  end
end
```

2017-06-20 16:33 UTC, ilovezfs commented
But it only works for `--HEAD`

2017-06-20 16:45 UTC, ilovezfs commented
And this gets it using the Homebrew cache if we want to pursue that at some point.
```
    ENV["GOPATH"] = buildpath
    go_cache = HOMEBREW_CACHE/"go_cache/#{name}/dep"
    go_cache.mkpath

    (buildpath/"src/github.com/pressly/goose").install buildpath.children
    Language::Go.stage_deps resources, buildpath/"src"

    (buildpath/"pkg").install_symlink go_cache
```

2017-06-20 16:45 UTC, mkozjak commented
Should I compile it all now and push?

2017-06-20 16:47 UTC, ilovezfs commented
@mkozjak let's see whether upstream is willing to create a new tag now or not so we know how to proceed.

2017-06-20 17:07 UTC, VojtechVitek commented
@ilovezfs @mkozjak I will be releasing v2.0 later this week. Can you hold off for a bit?

2017-06-20 17:08 UTC, ilovezfs commented
@VojtechVitek not a problem. We've got it working with `dep`: https://github.com/Homebrew/homebrew-core/pull/14724#issuecomment-309815183

So whenever you're ready.

2017-06-25 18:17 UTC, mkozjak commented
@ilovezfs Goose v2.0.0 is here. Should we proceed? Pushed formula updates which use ```dep``` (without caching support for now).

2017-06-25 21:20 UTC, dunn commented on Formula/goose.rb
> +    ENV.append_path "PATH", buildpath/"bin"
Instead of changing the path, below just do `system buildpath/"bin/dep", "ensure"`.

2017-06-25 21:33 UTC, mkozjak commented on Formula/goose.rb
> +    ENV.append_path "PATH", buildpath/"bin"
Done!

2017-07-21 09:36 UTC, closed without merging

2017-07-21 09:37 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @mkozjak! Without people like you submitting PRs we couldn't run this project. You rock!

2017-07-21 10:04 UTC, mkozjak commented
@ilovezfs And thank you for giving so much time, effort and positive energy in such an amazing project like this one!

2017-07-21 14:07 UTC, VojtechVitek commented
Well done guys!