nvidia-docker 1.0.1 (new formula)
Homebrew/homebrew-core pull request #14799
Opened 2017-06-21 06:32 UTC by cybertk

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-06-21 08:23 UTC, bfontaine requested changes

2017-06-21 08:23 UTC, bfontaine commented on Formula/nvidia-docker.rb
> +  patch :p1, :DATA
Please report this bug to upstream

2017-06-21 08:23 UTC, bfontaine commented on Formula/nvidia-docker.rb
> +    cd("go/src/github.com/nvidia/nvidia-docker/src/nvidia-docker") do
Nitpick: you can drop the parentheses.

2017-06-21 08:23 UTC, bfontaine commented on Formula/nvidia-docker.rb
> +    system "#{bin}/nvidia-docker", "version"
Can’t we write a test that does something more substantial than e.g. `help`  or `version`?

2017-06-21 08:38 UTC, ilovezfs commented on Formula/nvidia-docker.rb
> +  patch :p1, :DATA
The patch will need to be accepted upstream before this can be merged.

2017-07-13 03:06 UTC, cybertk commented on Formula/nvidia-docker.rb
> +  patch :p1, :DATA
This is not a bug, it's a customization for supporting macOS.

2017-07-13 03:30 UTC, cybertk commented on Formula/nvidia-docker.rb
> +    system "#{bin}/nvidia-docker", "version"
That requires a workable docker-engine, how to prepare this in test?

2017-07-31 15:48 UTC, ilovezfs requested changes

2017-07-31 15:48 UTC, ilovezfs commented on Formula/nvidia-docker.rb
> +require File.expand_path("../Requirements/cuda_requirement", __FILE__)
What is this referring to? I don't think we have any such requirement.

2017-07-31 15:48 UTC, ilovezfs commented on Formula/nvidia-docker.rb
> +  patch :p1, :DATA
New formulae need to build without patching. Has this been reported upstream?

2017-08-22 15:10 UTC, fxcoudert commented
Given lack of feedback, and despite the bots fighting each other… I am closing this for now. Please open a new pull request when the feedback is taken into account, and the formula builds.

2017-08-22 15:10 UTC, closed without merging