minishift 1.1.0 (new formula)
Homebrew/homebrew-core pull request #14819
Opened 2017-06-21 16:49 UTC by gastaldi

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-06-21 17:34 UTC, maxim-belkin commented
@gastaldi if this formula is added to Homebrew/core, we'll port it to Linuxbrew/core (with proper modifications).

2017-06-21 17:37 UTC, gastaldi commented
@maxim-belkin Excellent. 

I have provided a PR in https://github.com/Linuxbrew/homebrew-core/pull/3011 too with this changes specific to Linux. Feel free to close it if that is not needed atm

2017-06-21 17:42 UTC, gastaldi commented
It seems that it already exists as a Cask file. IMHO I think minishift should be available as a Formula, since it does not have any GUI to be a Cask (and also Casks are macOS only). 
The perfect approach would be to delete the Cask file, but I am not sure if that is allowed?

2017-06-21 22:11 UTC, commitay commented
> The perfect approach would be to delete the Cask file

https://github.com/caskroom/homebrew-cask/pull/35760

2017-06-21 22:17 UTC, gastaldi commented
Thanks @commitay

2017-06-22 00:06 UTC, commitay commented
> IMHO I think minishift should be available as a Formula, since it does not have any GUI to be a Cask (and also Casks are macOS only).

@gastaldi From a previous PR to `homebrew-core` for `minishift` https://github.com/Homebrew/homebrew-core/issues/4531,  it was added to cask because it is distributed as a pre-built binary.

2017-06-23 19:57 UTC, gastaldi commented
@commitay from the https://github.com/Homebrew/homebrew-core/pull/2417 comments, it seems that it was because in previous versions it depended on minikube and docker, which I believe is not the case anymore

2017-06-24 08:46 UTC, ilovezfs requested changes
The formula would need to build the software from source. Is that now possible without needing a Docker container?

2017-06-24 14:39 UTC, gastaldi commented
@ilovezfs Why is building from source a requirement? The formula works as it is now.

For example, the jboss-forge formula provides a distribution ZIP file with the binary JARs and doesn't build from sources.

2017-06-24 14:41 UTC, ilovezfs commented
@gastaldi this is a matter of policy that applies to everything in Homebrew.

2017-06-24 14:44 UTC, ilovezfs commented
>For example, the jboss-forge formula provides a distribution ZIP file with the binary JARs and doesn't build from sources.

Yes, for cross-platform binaries such as Java jar files and Mono exe files there is a specific exception.

2017-06-24 14:46 UTC, ilovezfs commented
@gastaldi see the documentation here: https://github.com/Homebrew/brew/blob/c541b3867ac7612cdfa3c7b8626367bea3e8f3ec/docs/Acceptable-Formulae.md#we-dont-like-binary-formulae

2017-06-24 14:48 UTC, gastaldi commented
Thanks for the explanation. I'll try to adjust it to follow https://docs.openshift.org/latest/minishift/developing/developing.html#build-minishift-binary then, but my Ruby knowledge is somewhat limited, so I appreciate any help if possible :)

2017-06-24 15:20 UTC, ilovezfs commented
@gastaldi it will need a better test, but this should get you started:
```
require "language/go"

class Minishift < Formula
  desc "Runs a single-node OpenShift cluster inside a VM"
  homepage "https://minishift.io/"
  url "https://github.com/minishift/minishift/archive/v1.1.0.tar.gz"
  sha256 "67cca4ec4767f2609eadb05f2fe3322592a070319caad2e3c477acbf68e0bff0"

  depends_on "go" => :build
  depends_on "glide" => :build

  go_resource "github.com/jteeuwen/go-bindata" do
    url "https://github.com/jteeuwen/go-bindata.git",
        :revision => "a0ff2567cfb70903282db057e799fd826784d41d"
  end

  def install
    ENV["GOPATH"] = buildpath
    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"

    (buildpath/"src/github.com/minishift/minishift").install buildpath.children
    ENV.prepend_create_path "PATH", buildpath/"bin"
    Language::Go.stage_deps resources, buildpath/"src"

    cd "src/github.com/jteeuwen/go-bindata/go-bindata" do
      system "go", "install"
    end

    cd "src/github.com/minishift/minishift" do
      system "make", "V=1"
      prefix.install_metafiles
    end

    bin.install "bin/minishift"
  end

  test do
    assert_equal "minishift v#{version}\n", shell_output("#{bin}/minishift version")
  end
end
```

2017-06-26 03:59 UTC, gastaldi commented
So I came with this Formula: 
```
require "language/go"

class Minishift < Formula
  version "1.1.0"
  sha256 "67cca4ec4767f2609eadb05f2fe3322592a070319caad2e3c477acbf68e0bff0"

  desc "Runs a single-node OpenShift cluster inside a VM"
  homepage "https://minishift.io/"
  url "https://github.com/minishift/minishift/archive/v#{version}.tar.gz"

  depends_on "go" => :build
  depends_on "glide" => :build

  go_resource "github.com/jteeuwen/go-bindata" do
    url "https://github.com/jteeuwen/go-bindata.git",
        :revision => "a0ff2567cfb70903282db057e799fd826784d41d"
  end

  def install
    ENV["GOPATH"] = buildpath
    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"

    (buildpath/"src/github.com/minishift/minishift").install buildpath.children
    ENV.prepend_create_path "PATH", buildpath/"bin"
    Language::Go.stage_deps resources, buildpath/"src"

    cd "src/github.com/jteeuwen/go-bindata/go-bindata" do
      system "go", "install"
    end

    cd "src/github.com/minishift/minishift" do
      system "make"
      prefix.install_metafiles
    end

    bin.install "bin/minishift"
  end

  test do
    assert_equal "minishift v#{version}\n", shell_output("#{bin}/minishift version")
  end
end
```

But unfortunately I get a build error that I don't understand what's going on (The minishift build works fine if I follow the steps defined in https://docs.openshift.org/latest/minishift/developing/developing.html#build-minishift-binary): 

```
➜  Formula git:(minishift) ✗ brew install --build-from-source minishift.rb             
==> Downloading https://github.com/minishift/minishift/archive/v1.1.0.tar.gz
Already downloaded: /home/ggastald/.cache/Homebrew/minishift-1.1.0.tar.gz
==> Cloning https://github.com/jteeuwen/go-bindata.git
Updating /home/ggastald/.cache/Homebrew/minishift--github.com-jteeuwen-go-bindata--git
==> Checking out revision a0ff2567cfb70903282db057e799fd826784d41d
==> go install
==> make
Last 15 lines from /home/ggastald/.cache/Homebrew/Logs/minishift/02.make:
/usr/share/rubygems/rubygems/path_support.rb:83:in `default_path': undefined method `+' for nil:NilClass (NoMethodError)
	from /usr/share/rubygems/rubygems/path_support.rb:75:in `path='
	from /usr/share/rubygems/rubygems/path_support.rb:35:in `initialize'
	from /usr/share/rubygems/rubygems.rb:329:in `new'
	from /usr/share/rubygems/rubygems.rb:329:in `paths'
	from /usr/share/rubygems/rubygems.rb:352:in `path'
	from /usr/share/rubygems/rubygems/specification.rb:979:in `dirs'
	from /usr/share/rubygems/rubygems/specification.rb:831:in `stubs'
	from /usr/share/rubygems/rubygems/specification.rb:1036:in `find_by_path'
	from /usr/share/rubygems/rubygems.rb:189:in `try_activate'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:40:in `require'
	from <internal:gem_prelude>:6:in `<internal:gem_prelude>'
Makefile:56: recipe for target '/tmp/minishift-20170626-24138-8k0ikd/minishift-1.1.0/bin/minishift' failed
make: *** [/tmp/minishift-20170626-24138-8k0ikd/minishift-1.1.0/bin/minishift] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
minishift 1.1.0 https://github.com/Linuxbrew/homebrew-core/pull/3011

```

2017-06-26 04:19 UTC, rwhogg commented
> Do not report this issue to Homebrew/brew or Homebrew/core!

I looked at the three Jenkins builds, and from what I saw they all built correctly and only failed for audit reasons. So this may just be an error specific to Linuxbrew, in which case we* can deal with it there at the time this formula is merged into Linuxbrew.

* "We" in this context meaning you and the Linuxbrew team

2017-06-26 04:28 UTC, gastaldi commented
@maxim-belkin any idea why that fails in Linuxbrew?

2017-06-26 04:34 UTC, gastaldi commented
@rwhogg Thanks, I fixed the audit issues in a new commit and I hope it's OK now.

2017-06-27 11:59 UTC, ilovezfs requested changes
We'll need to sort out the name collision with the Cask. Are they the same software?

2017-06-27 11:59 UTC, ilovezfs commented on Formula/minishift.rb
> +  version "1.1.0"
This line should be removed.

2017-06-27 11:59 UTC, ilovezfs commented on Formula/minishift.rb
> +    assert_equal "minishift v#{version}\n", shell_output("#{bin}/minishift version")
We'll need a test that exercises and verifies the functionality of the software once installed.

2017-06-27 14:41 UTC, gastaldi commented on Formula/minishift.rb
> +    assert_equal "minishift v#{version}\n", shell_output("#{bin}/minishift version")
Yes, they are the same software. There is even a PR removing it once this PR is merged: https://github.com/caskroom/homebrew-cask/pull/35760

2017-06-27 14:42 UTC, gastaldi commented on Formula/minishift.rb
> +  version "1.1.0"
The version value is used in the tests. Is it still set even if I don't specify it?

2017-06-27 14:42 UTC, gastaldi commented
Yes, they are the same software. There is even a PR removing it once this PR is merged: caskroom/homebrew-cask#35760

2017-06-27 14:43 UTC, ilovezfs commented
>Yes, they are the same software. There is even a PR removing it once this PR is merged: caskroom/homebrew-cask#35760

Cool.

2017-06-27 14:44 UTC, ilovezfs commented on Formula/minishift.rb
> +  version "1.1.0"
Yeah. See the audit error about its being redundant since it was already determined to be the same value from the URL.

2017-08-20 18:30 UTC, ilovezfs requested changes
Please refresh this with 1.4.1

2017-08-21 03:56 UTC, gastaldi commented
Minishift now has its own update mechanism through `minishift update`, therefore I think it's fine to close this PR. Thanks for the help!

2017-08-21 03:56 UTC, closed without merging

2017-08-25 13:00 UTC, gbraad commented
@gastaldi This PR is abandoned, and Cask will stay in place?
If so, we will try to automate the process of pushing a changed cask when we cut a new release.

See: https://github.com/minishift/minishift/issues/1012

2017-08-25 13:07 UTC, gastaldi commented
@gbraad yes, I think that's fine. I was using `minishift update` instead