libgsm 1.0.16
Homebrew/homebrew-core pull request #14858
Opened 2017-06-23 01:33 UTC by s172262

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2017-06-24 07:49 UTC, ilovezfs requested changes

2017-06-24 07:49 UTC, ilovezfs commented on Formula/libgsm.rb
> +    inreplace "Makefile", "libgsm.1.0.13.dylib", "libgsm.1.0.16.dylib"
We'll need this reported upstream and a new release tarball will likely be needed.

2017-06-24 13:50 UTC, s172262 commented on Formula/libgsm.rb
> +    inreplace "Makefile", "libgsm.1.0.13.dylib", "libgsm.1.0.16.dylib"
Original Makefile by upstream don't have string of "libgsm.1.0.13.dylib".
It was written by the Patch. And Upstream said that They won't provide _dylib_.

2017-07-03 11:00 UTC, ilovezfs requested changes

2017-07-03 11:00 UTC, ilovezfs commented on Formula/libgsm.rb
> +    inreplace "Makefile", "libgsm.1.0.13.dylib", "libgsm.1.0.16.dylib"
>And Upstream said that they won't provide dylib.

Do you have a reference for this? That may be sufficient reason to remove this from Homebrew.

>Original Makefile by upstream don't have string of "libgsm.1.0.13.dylib".
It was written by the Patch.

The patch should be updated accordingly and submitted to https://github.com/Homebrew/formula-patches.

2017-07-26 10:23 UTC, ilovezfs commented
@s172262 any update here?

2017-07-31 16:17 UTC, ilovezfs commented
@s172262 thanks for this PR. Please feel free to reopen it when the review feedback has been addressed.

2017-07-31 16:17 UTC, closed without merging