tokei 6.0.1 (new formula)
Homebrew/homebrew-core pull request #14894
Opened 2017-06-23 21:57 UTC by myrrlyn

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Add a formula for the `tokei` tool, as it appears to not have one.

I made a mistake on my first commit, and I'm not sure how to squash them here on GitHub; my apologies.

2017-06-24 07:36 UTC, ilovezfs requested changes

2017-06-24 07:36 UTC, ilovezfs commented on Formula/tokei.rb
> +  url "https://github.com/Aaronepower/tokei/releases/download/v6.0.1/tokei-v6.0.1-x86_64-apple-darwin.tar.gz"
We'll need to build this from source.

2017-06-25 21:28 UTC, dunn commented on Formula/tokei.rb
> +    (testpath/"lib.rs").write <<-EOS
Use `EOS.undent` and indent the Rust code by two spaces.

2017-06-25 23:15 UTC, myrrlyn commented on Formula/tokei.rb
> +    (testpath/"lib.rs").write <<-EOS
Indent the heredoc by two from the parent level, or use two-space indentation in the code block?

2017-06-28 02:10 UTC, dunn commented
Thank you for contributing to Homebrew! Merged as 1141ce59108ddffe82ba4f3b5f9440671212dd0a.

2017-06-28 02:10 UTC, closed without merging