pdfpc 4.0.6 (new formula)
Homebrew/homebrew-core pull request #14906
Opened 2017-06-24 10:34 UTC by SWW13

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

```
$ brew audit --new-formula pdfpc
pdfpc:
  * GitHub fork (not canonical repository)
  * New formulae should not require patches to build. Patches should be submitted and accepted upstream first.
```

Notes:
- https://github.com/pdfpc/pdfpc is the currently maintained fork, upstream and upstream of upstream are no longer maintained for more than two years.
- Patch is already in HEAD, but not in the newest release.

-----

2017-06-25 06:11 UTC, ilovezfs requested changes
>Patch is already in HEAD, but not in the newest release.

Please create an issue upstream requesting a new release.

2017-06-25 06:12 UTC, ilovezfs requested changes

2017-06-25 06:12 UTC, ilovezfs commented on Formula/pdfpc.rb
> +    system "#{bin}/pdfpc", "--version"
We'll need a test here that exercises and verifies the functionality of the software once it's installed.

2017-06-25 06:13 UTC, ilovezfs requested changes

2017-06-25 06:13 UTC, ilovezfs commented on Formula/pdfpc.rb
> +  depends_on "librsvg"
Please sort the non-build dependencies and remove the poppler duplicate.

2017-06-25 10:38 UTC, SWW13 commented
> Please create an issue upstream requesting a new release.

Done, waiting for upstream: https://github.com/pdfpc/pdfpc/issues/246

2017-06-25 10:38 UTC, SWW13 commented on Formula/pdfpc.rb
> +  depends_on "librsvg"
Done.

2017-06-25 10:48 UTC, SWW13 commented on Formula/pdfpc.rb
> +    system "#{bin}/pdfpc", "--version"
Oh, forgot to mention that: `pdfpc` opens a pdf in one or two a presentation window(s).

I have no idea how to test this without user input.

```ruby
system "#{bin}/pdfpc", "sample.pdf"
```
Will just open `pdfpc`, show the presentation and wait for user input.

```ruby
require "open3"
Open3.popen3("#{bin}/pdfpc", "sample.pdf") do |stdin, stdout, _|
  stdin.write("q") # q is the default shortcut to quit
end
```
I've tried that, but `pdfpc` does not read input from stdin.

Any idea how to send input to an window?
I thought about sending a signal, but haven't tried that yet.

2017-06-25 13:08 UTC, ilovezfs commented
@SWW13 looks like upstream has accommodated the request 🎉

2017-06-25 14:05 UTC, SWW13 commented
Updated to 4.0.7 and removed patch.

2017-06-25 14:11 UTC, ilovezfs commented on Formula/pdfpc.rb
> +    system "#{bin}/pdfpc", "--version"
I was trying to test this locally but am seeing a weird error about dbus. Is this supposed to link to dbus and isn't?

2017-06-25 14:36 UTC, SWW13 commented on Formula/pdfpc.rb
> +    system "#{bin}/pdfpc", "--version"
Strange, I don't have dbus installed and the CMakeLists.txt don't list any dbus dependency nor does the README mention dbus .

However `pdfpc` provides an dbus interface (https://github.com/pdfpc/pdfpc/blob/969b1672d557c67254b994102ceed482ffd7c6b5/man/pdfpc.in#L442).

2017-07-08 10:40 UTC, fxcoudert commented
@BrewTestBot test this please

2017-07-08 10:44 UTC, ilovezfs commented
@fxcoudert note that the dbus problem is a warning not a hard error, so CI isn't going to reflect it.

2017-09-28 20:42 UTC, JCount commented
@BrewTestBot test this please

2017-10-07 05:16 UTC, ilovezfs commented
@BrewTestBot test this please

2017-10-07 06:44 UTC, closed without merging

2017-10-07 06:44 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @SWW13! Without people like you submitting PRs we couldn't run this project. You rock!

2017-10-09 07:35 UTC, davidfokkema commented
Many thanks for this! But: why exactly are the movies turned off?

2017-10-09 07:47 UTC, ilovezfs commented
@davidfokkema dunno. Have you tried building with them on?

2017-10-09 08:07 UTC, davidfokkema commented
@ilovezfs I've just tried to do that. It (at least) needs gstreamermm, which has no bottle for High Sierra because it fails to compile (I've tried). It is tracked in #18493. So, no movies for now...