Update ntop to work with mariadb
Homebrew/homebrew-core pull request #15000
Opened 2017-06-27 13:27 UTC by BenjaminHCCarr

This is the patch suggested by @ilovezfs to fix this error in Homebrew/homebrew-core#1427:
https://github.com/Homebrew/homebrew-core/issues/14278#issuecomment-306396602

install and works fine!

---

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [X] Does your build pass `brew style --strict <formula>`?
-----

This would close: Homebrew/homebrew-core#1427

2017-06-29 20:22 UTC, BenjaminHCCarr commented
This is working with the `--with-mariadb` flag which was broken:
```
tyr:~/Code/git/Mine/homebrew-tap/Formula (master) benc$ brew info ./ntopng
ntopng: stable 3.0 (bottled), HEAD
Next generation version of the original ntop
http://www.ntop.org/products/ntop/
/usr/local/Cellar/ntopng/3.0 (444 files, 12.1MB) *
  Built from source on 2017-06-27 at 09:20:10 with: --with-mariadb
From: /Users/benc/Code/git/Mine/homebrew-tap/Formula/ntopng.rb
```

This was noted in Homebrew/homebrew-core#14278

2017-07-09 10:00 UTC, fxcoudert requested changes
Looks good, apart from the whitespace

2017-07-09 10:00 UTC, fxcoudert commented on Formula/ntopng.rb
> +      (buildpath / "nDPI").install Dir["*"]
Remove this whitespace change

2017-07-09 10:02 UTC, ilovezfs commented
This actually need to be reported to `mariadb` before we start hacking around it.

2017-07-09 12:54 UTC, ilovezfs commented
OK it's been reported
https://lists.launchpad.net/maria-developers/msg10792.html
https://lists.launchpad.net/maria-developers/msg10793.html
https://jira.mariadb.org/browse/MDEV-13270

According to https://jira.mariadb.org/browse/MDEV-13270 it was fixed, so we should actually try to patch mariadb with the upstream fix.

2017-07-09 12:58 UTC, ilovezfs commented
Fix is here: https://github.com/MariaDB/mariadb-connector-c/commit/3f356c0598ad4785e9b4eff23e03fd662a701070

2017-07-09 13:14 UTC, closed without merging

2017-07-09 13:39 UTC, ilovezfs commented
This should be fixed now if you `brew update && brew upgrade`

2017-07-12 20:19 UTC, BenjaminHCCarr commented
Thanks @ilovezfs you wrote the patch, it simply worked for me, and I was not hearing a fix coming from upstream, so I PR'ed your patch against the code.

Glad they fixed their configuration bug.