Add bashunit
Homebrew/homebrew-core pull request #150207
Opened 2023-10-08 20:48 UTC by Chemaclass

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with 
    `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source bashunit`?
- [x] Is your test running fine `brew test bashunit`?
- [x] Does your build pass `brew audit --strict bashunit`?
    If this is a new formula, does it pass `brew audit --new bashunit`?

<img width="1092" alt="Screenshot 2023-10-08 at 22 46 18" src="https://github.com/Homebrew/homebrew-core/assets/5256287/06ba4fa2-64bb-42c4-b424-a70649497198">

2023-10-08 22:03 UTC, chenrui333 commented
@Chemaclass thanks for your first PR to homebrew-core, can you amend your commit as the PR title. Thanks!

2023-10-08 22:03 UTC, chenrui333 approved these changes

2023-10-08 23:45 UTC, chenrui333 approved these changes

2023-10-09 01:31 UTC, p-linnane requested changes

2023-10-09 01:31 UTC, p-linnane commented on Formula/b/bashunit.rb
> +  sha256 "0216d2c1e49ce0dd8303d01c076d24a5cb3fd54fd94634216887c6edbaf4a2f6"
```suggestion
  url "https://github.com/TypedDevs/bashunit/archive/refs/tags/0.8.0.tar.gz"
  sha256 "9aeeb9b0b5ee410bd6e40fbd4fda479ef2ffe9e1de21f750b3c279fa06e40ef3"
```

2023-10-09 02:52 UTC, chenrui333 commented
Since this is shell script, we can just use the consolidated one in the release artifact, it is pretty much the same as the one in the tarball file.

2023-10-09 02:57 UTC, p-linnane approved these changes

2023-10-09 03:20 UTC, merged