Drafter 3.2.7 - API Blueprint document parser (new formula)
Homebrew/homebrew-core pull request #15053
Opened 2017-06-28 12:05 UTC by vassilevsky

2017-07-03 10:14 UTC, ilovezfs requested changes

2017-07-03 10:14 UTC, ilovezfs commented on Formula/drafter.rb
> +    bin.install "bin/drafter"
Is there a `make install`?

2017-07-03 10:14 UTC, ilovezfs commented on Formula/drafter.rb
> +    system bin/"drafter", "--help"
This should be a test that exercises, and verifies, the software's functionality once installed.

2017-07-26 10:24 UTC, ilovezfs commented
@vassilevsky any update here?

2017-07-31 16:09 UTC, ilovezfs commented
Thanks for the PR @vassilevsky! Please feel free to reopen a PR for this when it's using the `make install` target and has a test that exercises and verifies the functionality of the software.

2017-07-31 16:09 UTC, closed without merging

2017-10-08 12:45 UTC, Kyslik commented
Anything new on this?

https://github.com/apiaryio/drafter#install