nexttrace 1.2.3
Homebrew/homebrew-core pull request #150910
Opened 2023-10-14 17:27 UTC by chenrui333

Created by `brew bump`

---

Created with `brew bump-formula-pr`.

2023-10-14 18:08 UTC, Bo98 commented
`prefered` -> `preferred` in the test

2023-10-14 21:08 UTC, iMichka commented
Not the latest release: https://github.com/nxtrace/NTrace-core/releases

2023-10-15 10:24 UTC, SMillerDev requested changes
Needs a better livecheck

2023-10-15 13:27 UTC, SMillerDev approved these changes

2023-10-15 13:32 UTC, merged