feat: add azion 1.5.1 (new formula)
Homebrew/homebrew-core pull request #152254
Opened 2023-10-24 13:59 UTC by PatrickMenoti

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

2023-10-24 15:23 UTC, p-linnane requested changes
Everything in homebrew-core must build from source. We are not able to accept pre-built binaries like this.

2023-10-24 18:19 UTC, PatrickMenoti commented
> Everything in homebrew-core must build from source. We are not able to accept pre-built binaries like this.

Working on it!

2023-10-24 20:44 UTC, p-linnane commented
I've rewritten the formula to use a more standard `go` build process.

2023-10-24 20:46 UTC, PatrickMenoti commented
> I've rewritten the formula to use a more standard `go` build process.

May I edit your re-write to add the other LDFLAGS we use in this project?

2023-10-24 20:47 UTC, p-linnane commented
> May I edit your re-write to add the other LDFLAGS we use in this project?

Go for it. Please just squash the commits into one with the same message that I used.

2023-10-24 20:51 UTC, p-linnane commented
Looks like this does not actually meet our notability criteria:
```
Full audit azion-cli --online --new-formula output
  azion-cli
    * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

2023-10-24 21:15 UTC, marcusgrando commented
👍 💯

2023-10-24 22:18 UTC, LucasGeneroso commented
+ 1

2023-10-24 23:25 UTC, chenrui333 approved these changes

2023-10-24 23:37 UTC, p-linnane approved these changes

2023-10-24 23:38 UTC, p-linnane commented
We can waive the notability check since it seems there are a good number of people who want this included.

2023-10-24 23:47 UTC, merged

2023-10-25 14:09 UTC, PatrickMenoti commented
> We can waive the notability check since it seems there are a good number of people who want this included.

I noticed that you changed the name from azion to azion-cli. Why is that? 
I was hoping to be able to install it by running: brew install azion

2023-10-25 15:35 UTC, p-linnane commented
> I noticed that you changed the name from azion to azion-cli. Why is that? I was hoping to be able to install it by running: brew install azion

To match the repo name, and distinguish it from whatever the platform/service it interacts with is.

2023-10-25 17:33 UTC, chenrui333 commented on Formula/a/azion-cli.rb
> +class AzionCli < Formula
if you are not sure about this name, maybe you should ask first?

https://github.com/Homebrew/homebrew-core/pull/152353