makensis: Add optional support for large strings
Homebrew/homebrew-core pull request #15331
Opened 2017-07-06 08:38 UTC by rhwood

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Adds optional support to create the ["Large Strings" special build](http://nsis.sourceforge.net/Special_Builds#Large_strings) for the current version of makensis.

2017-07-08 09:21 UTC, ilovezfs requested changes
please do not change whitespace in the patch

2017-07-08 09:32 UTC, fxcoudert commented
Would there be any downside to making this the default? `makensis` is not very widely used, so it may make sense to avoid having options there if we can

2017-07-09 09:43 UTC, rhwood commented
@ilovezfs I've fixed the patch. Sorry about missing that in the original submission.

@fxcoudert The only reason not to make large-strings the default is that the upstream does not make it the default either. Other than that, I have no objection to making large-strings the default. What is the policy on deviating from upstream?

2017-07-09 09:49 UTC, fxcoudert commented
@BrewTestBot test this please

@rhwood we do it if we have users for whom the option is useful, if the option introduces no new dependency and there is no drawback or incompatibility for other users

2017-07-09 09:52 UTC, rhwood commented
@fxcoudert Thanks! I'll make it default to large strings, allowing users to specify ```--without-long-strings```, but it might take a week since I'm traveling without regular Internet access.

2017-07-09 09:53 UTC, ilovezfs commented
I think we should leave it optional unless we're planning to get upstream to change the default.

2017-07-09 09:54 UTC, ilovezfs requested changes

2017-07-09 09:54 UTC, ilovezfs commented on Formula/makensis.rb
> +      scons "NSIS_MAX_STRLEN=8192", "STRIP=0", "ZLIB_W32=#{@zlib_path}", "SKIPUTILS=NSIS Menu", "makensis"
This is quite repetitive. It would be good to streamline this with an `args` array.

2017-07-09 09:58 UTC, ilovezfs commented
That said, @rhwood please open an issue upstream requesting that the default be changed so that we at least have the hope of not carrying a new option indefinitely.

2017-07-15 20:21 UTC, rhwood commented
Upstream issue to not need this option is https://sourceforge.net/p/nsis/feature-requests/542/

2017-07-31 10:06 UTC, rhwood commented
@ilovezfs Are the changes you requested appropriately addressed?

2017-08-07 22:21 UTC, rhwood commented
I've tested that 5523fef builds and runs as expected and added some comments in 334fa9d. Is this ready to merge?

2017-08-07 22:25 UTC, vszakats commented
In newly added comment please change this URL:
`http://nsis.sourceforge.net/Special_Builds#Large_strings`
to this:
`https://nsis.sourceforge.io/Special_Builds#Large_strings`

2017-08-07 22:29 UTC, vszakats approved these changes

2017-08-07 22:29 UTC, vszakats commented on Formula/makensis.rb
> +  # From http://nsis.sourceforge.net/Special_Builds#Large_strings
Request above is still pending. Could you take a look at it?

2017-08-07 22:29 UTC, vszakats commented
Thank you!

2017-08-08 16:04 UTC, rhwood commented
I misread the line number in the build report. Sorry about that.

2017-08-08 16:38 UTC, merged

2017-08-08 16:38 UTC, fxcoudert commented
Thanks @rhwood for your contribution to Homebrew!

2017-08-09 10:15 UTC, idleberg commented
@rhwood Have you considered letting the user specify the string length?

**Example**

```bash
 # default of 8192 bytes
brew install makensis --with-large-strings

# custom string length
brew install makensis --with-large-strings=16384
```

This might also require a change of the wording (of the option) to communicate this better, I don't know.

2017-08-09 10:18 UTC, rhwood commented
I had not; I made makensis installed with the ```--with-large-strings``` argument match the large-strings special build [distributed by NSIS](http://nsis.sourceforge.net/Special_Builds#Large_strings).

2017-08-09 10:21 UTC, idleberg commented
I don't want to overcomplicate things. I don't think many people would use this, but I remember seeing questions regarding this on the NSIS forum. Let's see what the maintainers think.

2017-08-09 15:23 UTC, fxcoudert commented
Let's keep a single option, matching the NSIS build.