huggingface-cli 0.19.0
Homebrew/homebrew-core pull request #153654
Opened 2023-11-08 14:05 UTC by dnhn

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

2023-11-08 14:06 UTC, chenrui333 commented on Formula/h/huggingface-cli.rb
>    revision 1
```suggestion
```

2023-11-08 14:06 UTC, chenrui333 commented on Formula/h/huggingface-cli.rb
resources also need updates.

2023-11-08 15:24 UTC, chenrui333 requested changes
`$ brew update-python-resources huggingface-cli`

2023-11-08 15:38 UTC, dnhn commented
> `$ brew update-python-resources huggingface-cli`

This fails on my end. Please assist with this step.

2023-11-08 18:43 UTC, chenrui333 commented
> > `$ brew update-python-resources huggingface-cli`
> 
> This fails on my end. Please assist with this step.

can you post the logs?

2023-11-08 18:44 UTC, chenrui333 approved these changes

2023-11-08 19:30 UTC, merged

2023-11-09 16:37 UTC, dnhn commented
> > > `$ brew update-python-resources huggingface-cli`
> > 
> > 
> > This fails on my end. Please assist with this step.
> 
> can you post the logs? (you might also need to have to run `brew update`)

Here is the log:
```
==> Retrieving PyPI dependencies for "huggingface-hub"...
Error: Unable to determine dependencies for "huggingface-hub" because of a failure when running
`/usr/local/Cellar/python@3.11/3.11.6_1/bin/python3 -m pip install -q --dry-run --ignore-installed --report=/dev/stdout huggingface-hub`.
Please update the resources manually.
```