mysql-connector-odbc 5.3.8 (new formula)
Homebrew/homebrew-core pull request #15360
Opened 2017-07-06 22:27 UTC by OmgLag

Added CMake-based build process for MySQL ODBC connector. So far it
only supports static linking against MySQL client & OpenSSL libraries.

This formula is meant for unixodbc users only. The pre-built drivers
available from MySQL are meant to work with libiodbc, so users can
just download those if they work with iODBC.

2017-07-09 15:05 UTC, bfontaine requested changes

2017-07-09 15:05 UTC, bfontaine commented on Formula/mysql-connector-odbc.rb
> +    # Use separate invocations of make to build in the right order:
Please report these issues to upstream.

2017-07-09 22:14 UTC, DomT4 commented on Formula/mysql-connector-odbc.rb
> +    ssl_libs = "#{Formula["openssl"].opt_lib}/libssl.a "
Static linking of SSL libraries is a grim grim thing.

2017-07-10 02:54 UTC, OmgLag commented
Thanks for the feedback!

@bfontaine I'll report the issue, but for the time being, I think it's acceptable to build it this way. Using no-parallel would also work, but this solution still allows building it in parallel. If that's unacceptable, I will wait until it is resolved upstream and then update to the newer version. Please let me know!

@DomT4 Very true. I've switched it over to using the shared libraries for mysqlclient and openssl. Hopefully it's a little less grim...

2017-07-10 08:04 UTC, bfontaine commented
Upstream should at least be aware of the issue.

2017-07-10 14:27 UTC, ilovezfs requested changes
Please report the parallelization issue upstream, as that's a bug that will block inclusion of this formula in Homebrew core. Another option is not to run the tests, but that will also apparently require a change upstream since you said there's no way to disable the tests currently.

2017-08-12 13:33 UTC, closed without merging