qtrn 0.3 (new version)
Homebrew/homebrew-core pull request #15362
Opened 2017-07-07 00:55 UTC by ackleymi

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-07-07 12:03 UTC, bfontaine commented
The commit message should be "`qtrn 0.3 (new formula)`".

2017-07-07 12:04 UTC, bfontaine requested changes

2017-07-07 12:04 UTC, bfontaine commented on Formula/qtrn.rb
> +      bin.install "build/qtrn"
Use `system "go", "build", "-o", bin/"qtrn", ...` to avoid this line.

2017-07-07 17:45 UTC, ackleymi commented on Formula/qtrn.rb
> +      bin.install "build/qtrn"
@bfontaine is there any way to avoid the repo popularity check from brew audit? Thats the failing check.

2017-07-07 18:08 UTC, bfontaine commented on Formula/qtrn.rb
> +      bin.install "build/qtrn"
No, there’s no way. Ultimately it’s the maintainers’ decision to accept or reject new formulae but `brew audit` automates the basic checks. In your case this is a self-submission of a relatively new and not well-known project (3 stars on GitHub) so it doesn’t meet the [requirements](https://docs.brew.sh/Acceptable-Formulae.html#niche-or-self-submitted-stuff) to get in Homebrew core. You can, however, maintain a formula [in your own tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html) and re-submit it here once it gets more popular.

2017-07-08 09:20 UTC, fxcoudert commented
Closing as per @bfontaine's comment.

2017-07-08 09:20 UTC, closed without merging