zsh-history-enquirer 1.3.0 (new formula)
Homebrew/homebrew-core pull request #154416
Opened 2023-11-15 17:30 UTC by danielbayley

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2023-11-15 17:34 UTC, p-linnane requested changes

2023-11-15 17:34 UTC, p-linnane commented on Formula/zsh-history-enquirer.rb
> +    depends_on "expect" => :test
```suggestion

```

2023-11-15 17:34 UTC, p-linnane commented on Formula/zsh-history-enquirer.rb
> +    depends_on "expect" => :test
This is covered by `uses_from_macos` above.

2023-11-15 17:35 UTC, p-linnane commented on Formula/zsh-history-enquirer.rb
> +    depends_on "expect" => :test
You will need to move this into the `z` directory and also change your commit message to `zsh-history-enquirer 1.3.0 (new formula)`.

2023-11-15 17:38 UTC, p-linnane commented
You will need to move this into the `z` directory and squash the commits into one with the message `zsh-history-enquirer 1.3.0 (new formula)`.

2023-11-15 17:43 UTC, danielbayley commented
> You will need to move this into the `z` directory and squash the commits into one with the message `zsh-history-enquirer 1.3.0 (new formula)`.

@p-linnane Done.

2023-11-22 05:09 UTC, chenrui333 commented
I can take a look at the linux build failure tomorrow

2023-11-23 17:03 UTC, chenrui333 commented
```
/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh:fc:13: no such event: 1
    at makeError$1 (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:1236:11)
    at handlePromise (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:2150:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async history (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:2315:24)
    at async Promise.all (index 1)
    at async searchHistory (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:6027:30) {
  shortMessage: 'Command failed with exit code 1: /home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh',
  command: '/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh',
  escapedCommand: '"/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh:fc:13: no such event: 1',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
runner@fv-az1393-545:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core$ zsh-history-enquirer
Error: Command failed with exit code 1: /home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh
/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh:fc:13: no such event: 1
    at makeError$1 (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:1236:11)
    at handlePromise (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:2150:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async history (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:2315:24)
    at async Promise.all (index 1)
    at async searchHistory (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:6027:30) {
  shortMessage: 'Command failed with exit code 1: /home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh',
  command: '/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh',
  escapedCommand: '"/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh:fc:13: no such event: 1',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

2023-11-23 19:28 UTC, danielbayley commented
> ```
> runner@fv-az1393-545:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core$ zsh-history-enquirer
> Error: Command failed with exit code 1: /home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh
> /home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh:fc:13: no such event: 1
>     at makeError$1 (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:1236:11)
>     at handlePromise (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:2150:26)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async history (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:2315:24)
>     at async Promise.all (index 1)
>     at async searchHistory (/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/index.js:6027:30) {
>   shortMessage: 'Command failed with exit code 1: /home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh',
>   command: '/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh',
>   escapedCommand: '"/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh"',
>   exitCode: 1,
>   signal: undefined,
>   signalDescription: undefined,
>   stdout: '',
>   stderr: '/home/linuxbrew/.linuxbrew/Cellar/zsh-history-enquirer/1.3.0/libexec/lib/node_modules/zsh-history-enquirer/dist/history.zsh:fc:13: no such event: 1',
>   failed: true,
>   timedOut: false,
>   isCanceled: false,
>   killed: false
> }
> ```

cc: @zthxxx, as I don’t have a Linux VM set up, or the bandwidth to test…

2023-11-23 19:31 UTC, chenrui333 commented
you can just use either codespace or  linux action runner + tmate like what I did in here, https://github.com/chenrui333/github-action-test/blob/main/.github/workflows/brew-debug.yml#L49-L67

2023-11-26 22:05 UTC, chenrui333 commented
@danielbayley can you just file an upstream linux build issue report and we can do `depends_on :macos` for only building bottles for macos for now.

2023-11-27 10:42 UTC, danielbayley commented
> @danielbayley can you just file an upstream linux build issue report and we can do `depends_on :macos` for only building bottles for macos for now.

@chenrui333 Sure, filed here: https://github.com/zthxxx/zsh-history-enquirer/issues/73.

2023-11-30 05:34 UTC, zthxxx commented
> `depends_on :macos`

It can run exactly under Linux Zsh; I also use it on all of my servers.

2023-12-04 15:40 UTC, danielbayley commented
> It can run exactly under Linux Zsh; I also use it on all of my servers.
> 
> I noticed that the CI has failed due to the _unit-test_. Is that the problem with the test scripts?

@zthxxx Sounds like it must be. Maybe you want to look into getting it working with `brew test` on your local Linux setup?

2023-12-27 12:48 UTC, danielbayley commented
> It can run exactly under Linux Zsh; I also use it on all of my servers.
> 
> I noticed that the CI has failed due to the _unit-test_. Is that the problem with the test scripts?

@zthxxx Sounds like it must be. Maybe you want to look into getting it working with `brew test` on your local Linux setup?

2024-01-17 15:17 UTC, danielbayley commented
> It can run exactly under Linux Zsh; I also use it on all of my servers.
> 
> I noticed that the CI has failed due to the _unit-test_. Is that the problem with the test scripts?

@zthxxx Sounds like it must be. Maybe you want to look into getting it working with `brew test` on your local Linux setup?

2024-02-08 00:37 UTC, danielbayley commented
> It can run exactly under Linux Zsh; I also use it on all of my servers.
> 
> I noticed that the CI has failed due to the _unit-test_. Is that the problem with the test scripts?

@zthxxx Sounds like it must be. Maybe you want to look into getting it working with `brew test` on your local Linux setup?

2024-02-29 15:01 UTC, danielbayley commented
> It can run exactly under Linux Zsh; I also use it on all of my servers.
> 
> I noticed that the CI has failed due to the _unit-test_. Is that the problem with the test scripts?

@zthxxx Sounds like it must be. Maybe you want to look into getting it working with `brew test` on your local Linux setup?

2024-03-21 23:53 UTC, danielbayley commented
> It can run exactly under Linux Zsh; I also use it on all of my servers.
> 
> I noticed that the CI has failed due to the _unit-test_. Is that the problem with the test scripts?

@zthxxx Sounds like it must be. Maybe you want to look into getting it working with `brew test` on your local Linux setup?

2024-04-01 13:40 UTC, cho-m commented
Tried some things out but still failing in CI.

In local Linux container, adjusting match seemed to help as arrow symbol was rendering differently.

Also, when manually running with `^R`, command would fail without some basic ZSH history configs. However, I don't think this would impact existing test, but added fake `.zshrc` to try out.

Remaining things would be CI specific settings (perhaps `TERM` settings and so on).

2024-04-23 08:51 UTC, danielbayley commented
> It can run exactly under Linux Zsh; I also use it on all of my servers.
> 
> I noticed that the CI has failed due to the _unit-test_. Is that the problem with the test scripts?

@zthxxx Sounds like it must be. Maybe you want to look into getting it working with `brew test` on your local Linux setup?

2024-04-24 10:37 UTC, zthxxx commented
@danielbayley  I'm really sorry about this. A few months ago, I have tried to solve testing on this, but I failed due to I'm not familiar with Ruby or how Homebrew tests running. 😢

2024-06-07 23:11 UTC, closed without merging