python-magic 0.4.27 (new formula)
Homebrew/homebrew-core pull request #155219
Opened 2023-11-23 00:27 UTC by chenrui333

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2023-11-23 12:45 UTC, singingwolfboy requested changes

2023-11-23 12:45 UTC, singingwolfboy commented on Formula/p/python-magic.rb
> +  homepage "https://github.com/lxml/lxml"
Please update the homepage.

2023-11-23 12:45 UTC, singingwolfboy commented on Formula/p/python-magic.rb
> +  depends_on "python@3.12" => [:build, :test]
Needs a dependency on `libmagic`

2023-11-23 14:39 UTC, chenrui333 commented on Formula/p/python-magic.rb
> +  homepage "https://github.com/lxml/lxml"
make sense! 😅

2023-11-23 14:39 UTC, chenrui333 commented on Formula/p/python-magic.rb
> +  depends_on "python@3.12" => [:build, :test]
just added 👍

2023-11-23 19:13 UTC, p-linnane approved these changes

2023-11-24 08:23 UTC, singingwolfboy approved these changes

2023-11-24 13:45 UTC, merged