echidna, medusa: replace truffle with hardhat for test
Homebrew/homebrew-core pull request #156152
Opened 2023-12-01 22:43 UTC by chenrui333

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

relates to #156022

2023-12-01 22:52 UTC, p-linnane requested changes

2023-12-01 22:57 UTC, chenrui333 commented on Formula/e/echidna.rb
> +  # hardhat only support TLS node versions
good catch :)

2023-12-01 22:57 UTC, chenrui333 commented on Formula/m/medusa.rb
> +  # hardhat only support TLS node versions
agree :)

2023-12-02 01:05 UTC, chenrui333 commented
`clang: error: the clang compiler does not support '-march=nehalem'`

failed on intel builds.

2023-12-14 02:44 UTC, closed without merging

2023-12-14 02:44 UTC, chenrui333 commented
closing for now.