[WIP]add dps-8m: 1.0
Homebrew/homebrew-core pull request #15694
Opened 2017-07-17 09:37 UTC by yurikoles

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Please help me figure-out how to use native `cd` method. 
Also, there is problem with `test`, since binary is interactive-only.

2017-07-17 10:33 UTC, ilovezfs commented
>Please help me figure-out how to use native cd method.

`cd "foo"` but you can just use `system "make", "-C"

>Also, there is problem with test, since binary is interactive-only.

You can use `IO.popen` or an `expect` script.

2017-07-17 10:45 UTC, yurikoles commented
>`cd "foo"` but you can just use `system "make", "-C"`

I have make error in both cases.

>You can use `IO.popen` or an `expect` script.

Please give me a relevant example.

2017-07-17 10:56 UTC, ilovezfs commented
>I have make error in both cases.

This is because it's not needed. You're already in the correct directory at the beginning of the install method.

>Please give me a relevant example.

buku, firebase-cli, fsw

2017-07-17 10:58 UTC, ilovezfs requested changes

2017-07-17 10:58 UTC, ilovezfs commented on Formula/dps8m.rb
> +  depends_on "libuv" => :build
This is not just a build-time dependency so `=> :build` needs to be removed.

2017-07-17 10:58 UTC, ilovezfs commented on Formula/dps8m.rb
> +    system "cd", "src"
not needed

2017-07-17 10:58 UTC, ilovezfs commented on Formula/dps8m.rb
> +    mkdir prefix.to_s + "/bin"
`bin.mkpath`

This is a bug that needs to be reported upstream.

2017-07-17 11:34 UTC, yurikoles commented
@ilovezfs up & rebase. I'm not sure about test, please verify is it correct.

2017-07-17 11:41 UTC, ilovezfs requested changes

2017-07-17 11:41 UTC, ilovezfs commented on Formula/dps8m.rb
> +    bin.mkpath
This is a bug that needs to be reported upstream with a link to the report here.

2017-07-17 11:41 UTC, ilovezfs commented on Formula/dps8m.rb
> +    (testpath/"test.exp").write <<-EOS.unindent.undent
```
  (testpath/"test.exp").write <<-EOS.undent
```

2017-07-17 11:41 UTC, ilovezfs commented on Formula/dps8m.rb
> +      expect "DPS8/M emulator (git b7a50ffc)
The git commit (b7a50ffc) will change every release so that's not something you'll want to expect.

2017-07-17 11:41 UTC, ilovezfs commented on Formula/dps8m.rb
> +              DPS8M system session id is 70486
The session id will change every run so that's not something you'll want to expect.

2017-07-17 11:41 UTC, ilovezfs commented on Formula/dps8m.rb
> +              DPS8M simulator V4.0-0 Beta        git commit id: c420925a"
The git commit id and version will change so that's not something you'll want to expect.

2017-07-17 11:46 UTC, yurikoles commented on Formula/dps8m.rb
> +    bin.mkpath
I had requested access to tickets on sf.net, it's locked for all by default.

2017-07-17 11:48 UTC, yurikoles commented
@ilovezfs how to ignore variadic test in expect?

2017-07-18 07:48 UTC, yurikoles commented
@ilovezfs ping? Please help me figure out how to ignore some text in expect.

2017-07-23 18:00 UTC, yurikoles commented
bump

2017-07-23 18:31 UTC, yurikoles commented
@ilovezfs as I see now the Jenkins is happy with the formula. Why don't we just left the current tests since they are working well?

2017-08-04 06:55 UTC, yurikoles commented on Formula/dps8m.rb
> +    bin.mkpath
@ilovezfs The bug was reported upstream https://sourceforge.net/p/dps8m/mailman/message/35960505/

2017-08-04 06:56 UTC, yurikoles commented on Formula/dps8m.rb
> +              DPS8M simulator V4.0-0 Beta        git commit id: c420925a"
They seems to be kept same every time I test current version.

2017-08-04 06:56 UTC, yurikoles commented
@fxcoudert please look at this formula.

2017-08-04 07:18 UTC, fxcoudert commented on Formula/dps8m.rb
> +              DPS8M simulator V4.0-0 Beta        git commit id: c420925a"
Please remove the version and git commit id from the pattern matching. It will make future updates easier.

2017-08-04 16:10 UTC, yurikoles commented on Formula/dps8m.rb
> +              DPS8M simulator V4.0-0 Beta        git commit id: c420925a"
@fxcoudert please give me an example of such skip syntax

2017-08-12 12:45 UTC, yurikoles commented
@fxcoudert how to skip some lines in `expect`?

2017-10-01 17:08 UTC, yurikoles commented
@ilovezfs please merge

2017-11-11 14:02 UTC, ilovezfs approved these changes

2017-11-11 14:02 UTC, closed without merging

2017-11-11 14:03 UTC, ilovezfs commented
Thanks @yurikoles! Shipped.