jhiccup: fix broken url
Homebrew/homebrew-core pull request #15735
Opened 2017-07-18 18:02 UTC by vszakats

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-07-19 15:55 UTC, fxcoudert requested changes

2017-07-19 15:55 UTC, fxcoudert commented on Formula/jhiccup.rb
> +  homepage "http://www.jhiccup.com/"
This is now a redirect to `https://www.azul.com/products/open-source-tools/jhiccup-performance-measurement-tool/`

2017-07-19 15:57 UTC, vszakats commented on Formula/jhiccup.rb
> +  homepage "http://www.jhiccup.com/"
Noticed, but opted to leave it as-is. Will update now.

2017-07-19 20:43 UTC, vszakats commented on Formula/jhiccup.rb
> +  homepage "http://www.jhiccup.com/"
I've committed (+ squashed) the requested change.

2017-07-20 08:39 UTC, merged

2017-07-20 08:40 UTC, fxcoudert commented
Thanks @vszakats for your contribution!