Add caveats
Homebrew/homebrew-core pull request #15753
Opened 2017-07-19 07:33 UTC by HazCod

Add installation caveat so users know how to start using this package.

2017-07-20 08:38 UTC, fxcoudert requested changes

2017-07-20 08:38 UTC, fxcoudert commented on Formula/lesspipe.rb
> +      export LESSOPEN="|/usr/local/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1
- The first line is not really useful
- Are the instructions Homebrew-specific?
- Please do not hardcode `/usr/local/bin` but use `HOMEBREW_PREFIX` in caveats

2017-07-20 08:39 UTC, fxcoudert commented on Formula/lesspipe.rb
> +      export LESSOPEN="|/usr/local/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1
`  * C: 36: col 1: Trailing whitespace detected.`

2017-07-21 09:27 UTC, fxcoudert requested changes

2017-07-21 09:27 UTC, fxcoudert commented on Formula/lesspipe.rb
> +      export LESSOPEN="|$(brew --prefix)/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1
Our current practice for caveats is to use `#{HOMEBREW_PREFIX}` and not `$(brew --prefix)`

2017-07-21 09:31 UTC, ilovezfs commented on Formula/lesspipe.rb
> +      Append the following to your .bash_profile/.bashrc:
This should use `#{shell_profile}`

2017-07-22 11:25 UTC, HazCod commented on Formula/lesspipe.rb
> +      export LESSOPEN="|$(brew --prefix)/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1
How so? $HOMEBREW_PREFIX is not a global variable.

2017-07-22 12:35 UTC, fxcoudert commented on Formula/lesspipe.rb
> +      export LESSOPEN="|$(brew --prefix)/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1
As an example look at the caveats for `zsh-navigation-tools.rb`

2017-07-24 07:27 UTC, fxcoudert approved these changes

2017-07-24 07:28 UTC, merged

2017-07-24 07:28 UTC, fxcoudert commented
Thanks @HazCod for your contribution to Homebrew! We look forward to seeing you here again :)

2017-07-24 07:30 UTC, HazCod commented
It was a tough one, but we'll get there!