afl-plus-plus 4.09c (new formula)
Homebrew/homebrew-core pull request #158414
Opened 2023-12-28 00:55 UTC by pthariensflame

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

2023-12-28 01:48 UTC, pthariensflame commented
How do I resolve this audit?

2023-12-28 09:40 UTC, pthariensflame commented
Kind of stumped now.

2023-12-28 12:22 UTC, SMillerDev commented
Do you know where the symbol should come from ?
```console
  cc1: error: cannot load plugin ./afl-gcc-pass.so: ./afl-gcc-pass.so: undefined symbol: _ZNK6frange6acceptERK14vrange_visitor

```

2024-02-07 06:58 UTC, pthariensflame commented
Let's see if this works?

2024-03-05 04:35 UTC, pthariensflame commented
Ah, can this be marked as "in-progress"?
I'll loop back to this in a week or less.

2024-03-10 06:24 UTC, pthariensflame commented
This is extremely frustrating.  It builds, tests, and audits perfectly cleanly on my local machine, and yet the CI machine that's supposed to be that exact same environment isn't happy.  Why is audit complaining here and not for me?  Why does the Linux build fail *during fetch*?

2024-03-10 08:41 UTC, SMillerDev commented
Do you use docker locally for this?

2024-03-10 16:42 UTC, pthariensflame commented
> Do you use docker locally for this?

No, I build it in macOS.

2024-03-10 22:26 UTC, SMillerDev commented
Somehow I thought it was about Linux. For macOS it seems weird it's building `.so` libraries to begin with. Maybe there is some configuration that needs to be told it's on macOS?

2024-03-28 08:20 UTC, fxcoudert requested changes

2024-03-28 08:20 UTC, fxcoudert commented on Formula/a/afl-plus-plus.rb
> +  patch :DATA
This patch should be submitted, reviewed and (at least) accepted by upstream before we ship it.

2024-03-28 08:20 UTC, fxcoudert commented on Formula/a/afl-plus-plus.rb
> +      revision: "775861ea94d00672c9e868db329073afd699b994"
Could it build from a tarball instead?

2024-04-26 00:10 UTC, closed without merging