mesa-glu 9.0.3
Homebrew/homebrew-core pull request #158984
Opened 2024-01-04 14:43 UTC by timsutton

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2024-01-04 19:08 UTC, p-linnane requested changes

2024-01-04 19:08 UTC, p-linnane commented on Formula/m/mesa-glu.rb
> +    end
```suggestion
    system "meson", "setup", "build", "-Dgl_provider=gl", *std_meson_args
    system "meson", "compile", "-C", "build", "--verbose"
    system "meson", "install", "-C", "build"
```

2024-01-04 19:40 UTC, p-linnane approved these changes
The `head` block can be removed and we can add it as a line up top. Let's do that in a followup syntax PR so that we don't have to churn CI again.

2024-01-04 22:58 UTC, merged

2024-01-05 03:34 UTC, timsutton commented
> The `head` block can be removed and we can add it as a line up top. Let's do that in a followup syntax PR so that we don't have to churn CI again.

Updated in https://github.com/Homebrew/homebrew-core/pull/159034!