anyenv (new formula)
Homebrew/homebrew-core pull request #15912
Opened 2017-07-22 16:16 UTC by yuhki50

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-07-24 14:01 UTC, bfontaine commented on Formula/anyenv.rb
> +  option "without-completions", "Disable bash/fish/zsh completions"
Why would someone want that option?

2017-07-30 23:30 UTC, JCount requested changes
For this to be considered as a potential new formula, it would need to be based on an upstream release that the developer(s) deem to be stable.

2017-07-31 09:48 UTC, ilovezfs commented
@BrewTestBot test this please

2017-08-22 13:52 UTC, ilovezfs commented
@yuhki50 thanks for the PR! Please feel free to open a new PR if there's upstream (https://github.com/riywo/anyenv/) creates a tagged version that we can build from.

2017-08-22 13:52 UTC, closed without merging