helm-ls 0.0.9 (new formula)
Homebrew/homebrew-core pull request #159441
Opened 2024-01-09 19:48 UTC by qvalentin

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2024-01-09 20:33 UTC, p-linnane requested changes
Thanks for your submission. I have a few changes I'd like to see prior to merging, as well as the addition of another functional test.

2024-01-09 20:33 UTC, p-linnane commented on Formula/h/helm-ls.rb
> +      revision: "5dbde8a5d83a7cd3c21e55e8150100a2f7dd462e"
```suggestion
  url "https://github.com/mrjosh/helm-ls/archive/refs/tags/v0.0.9.tar.gz"
  sha256 "cef59537d2335c9821a2d60628bcf40451a137b9f5b38b3991d1914c3f4ec191"
```

2024-01-09 20:33 UTC, p-linnane commented on Formula/h/helm-ls.rb
> +      revision: "5dbde8a5d83a7cd3c21e55e8150100a2f7dd462e"
Let's use a tarball to avoid having to clone the repo.

2024-01-09 20:33 UTC, p-linnane commented on Formula/h/helm-ls.rb
> +    bin.install "bin/helm_ls"
```suggestion
    ldflags = %W[
      -X main.Version=#{version}
      -X main.CompiledBy=#{tap.user}
      -X main.GitCommit=#{tap.user}
      -X main.BuildTime=#{time.iso8601}
    ]
    system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"helm_ls")
```

2024-01-09 20:33 UTC, p-linnane commented on Formula/h/helm-ls.rb
> +    system bin/"helm_ls", "version"
```suggestion
    assert_match version.to_s, shell_output(bin/"helm_ls version")
```

2024-01-09 20:33 UTC, p-linnane commented on Formula/h/helm-ls.rb
> +    system bin/"helm_ls", "version"
We will need an additional test that exercises some functionality of the software. Versions or help checks rarely fail even if there are compilation issues. In this case it's worth keeping to ensure the ldflags are set correctly.

2024-01-11 20:38 UTC, qvalentin commented
Thanks for the suggestions.

2024-01-12 03:59 UTC, chenrui333 commented on Formula/h/helm-ls.rb
> +              "uri": "file://#{cwd}"
```suggestion
    json = <<~JSON
      {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "initialize",
        "params": {
          "workspaceFolders": [
            {
              "uri": "file://#{testpath}"
```

2024-01-12 04:00 UTC, chenrui333 commented on Formula/h/helm-ls.rb
> +    require 'open3'
some style issue
```suggestion
    require "open3"
```

2024-01-13 08:59 UTC, SMillerDev approved these changes

2024-01-13 16:10 UTC, p-linnane approved these changes

2024-01-13 16:23 UTC, merged