zls: use `ReleaseSafe` instead of `ReleaseFast`
Homebrew/homebrew-core pull request #159734
Opened 2024-01-12 06:45 UTC by chenrui333

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- fast-release - slow compilation, fully optimized runtime performance, safety checks off
- safe-release - slow compilation, fully optimized runtime performance, safety checks on

relates to https://github.com/ziglang/zig/issues/288

2024-01-12 07:37 UTC, carlocab commented on Formula/z/zls.rb
> +    args = %W[--prefix #{prefix} -Doptimize=ReleaseSafe]
Seems nicer to keep `ReleaseFast` unless users report problems with it.

2024-01-12 07:47 UTC, SMillerDev requested changes
> relates to ziglang/zig#288

That's from 7 years ago with no relevance to Homebrew though. What are we doing this for?

2024-01-12 13:24 UTC, chenrui333 commented
> > relates to [ziglang/zig#288](https://github.com/ziglang/zig/issues/288)
> 
> That's from 7 years ago with no relevance to Homebrew though. What are we doing this for?

Oh, that is just saying the fact this option has been existing for quite some time.

2024-01-12 13:28 UTC, chenrui333 commented
also upstream is using releasesafe for their release builds though.

- https://github.com/zigtools/zls/blob/master/README.md?plain=1#L36
- https://github.com/zigtools/zls/blob/f726e9e6c9a3fc016e67e4b18e33443e7d562704/flake.nix#L44
- https://github.com/zigtools/zls/blob/f726e9e6c9a3fc016e67e4b18e33443e7d562704/.github/workflows/main.yml#L66

2024-01-12 15:07 UTC, SMillerDev commented
Is it also the default?

2024-01-12 15:39 UTC, chenrui333 commented
> Is it also the default?

right now it is not the default in the build.zig

2024-01-12 16:45 UTC, chenrui333 commented
I think one of the reasons is that `std.builtin.Mode` is not just for release build but also debug build.

2024-01-16 05:48 UTC, carlocab commented
> Is it also the default?

The default is always debug, IIUC.

2024-01-23 04:19 UTC, chenrui333 commented
gonna close it for now, we can revisit it later.

2024-01-23 04:19 UTC, closed without merging