sccache 0.2.0 (new formula)
Homebrew/homebrew-core pull request #16041
Opened 2017-07-25 20:13 UTC by alex

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-07-25 20:31 UTC, ilovezfs requested changes

2017-07-25 20:31 UTC, ilovezfs commented on Formula/sccache.rb
> +    system "#{bin}/sccache", "--help"
should be a test for functionality

2017-07-25 20:33 UTC, alex commented on Formula/sccache.rb
> +    system "#{bin}/sccache", "--help"
Would you prefer a test which invoked `sccache -s` (displaying stats) or one which compiled a C file?

2017-07-25 20:35 UTC, ilovezfs commented on Formula/sccache.rb
> +    system "#{bin}/sccache", "--help"
The latter.

2017-07-25 20:40 UTC, ilovezfs commented on Formula/sccache.rb
> +    assert_equal "Hello, world!\n", `./hello-c`
```
    assert_equal "Hello, world!", shell_output("./hello-c").chomp
```

2017-07-25 21:07 UTC, ilovezfs commented
@BrewTestBot test this please

2017-07-25 21:07 UTC, ilovezfs approved these changes

2017-07-25 21:56 UTC, indygreg commented on Formula/sccache.rb
> +    system "cargo", "build", "--release"
Since someone will inevitably request support, should we add `--features=all` so S3 and Redis support is enabled?

2017-07-26 08:32 UTC, ilovezfs commented on Formula/sccache.rb
> +    system "cargo", "build", "--release"
Why isn't it the upstream default?

2017-07-26 13:16 UTC, luser commented on Formula/sccache.rb
> +    system "cargo", "build", "--release"
Because it makes builds slower and adds to the binary size. sccache CI does build with `--features=all` so that all the code is tested.

2017-07-26 13:17 UTC, ilovezfs commented on Formula/sccache.rb
> +    system "cargo", "build", "--release"
:+1: to `--features=all` in that case

2017-07-26 13:18 UTC, luser commented on Formula/sccache.rb
> +    system "#{bin}/sccache", "--help"
You could run `cargo test --release` if you were so inclined, which does include tests in which it invokes a compiler:
https://github.com/mozilla/sccache/blob/6267caf603d5a06e8a4b9391ffa02f6125e5ba9b/src/test/system.rs#L117

2017-07-26 13:19 UTC, ilovezfs commented on Formula/sccache.rb
> +    system "#{bin}/sccache", "--help"
`cargo` isn't available in the test block since `rust` is `=> :build` time only

2017-07-26 13:27 UTC, ilovezfs commented on Formula/sccache.rb
> +    system "cargo", "build", "--release", "--features", "all"
does this work or does it have to be `--features=all`?

2017-07-26 13:38 UTC, alex commented on Formula/sccache.rb
> +    system "cargo", "build", "--release", "--features", "all"
This works fine.

2017-07-26 13:39 UTC, ilovezfs approved these changes

2017-07-26 13:47 UTC, closed without merging

2017-07-26 13:47 UTC, ilovezfs commented
Thanks for the :new: formula @alex!