ice 3.7.0
Homebrew/homebrew-core pull request #16040
Opened 2017-07-25 19:48 UTC by externl

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-07-26 14:15 UTC, fxcoudert commented
```        == /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ice.rb ==
C: 24: 24: Space inside square brackets detected.
C: 28:  1: Extra empty line detected at method body beginning.
C: 37: 38: Only use parentheses for ternary expressions with complex conditions.
C: 37: 51: Prefer double-quoted strings inside interpolations.
C: 37: 66: Prefer double-quoted strings inside interpolations.
C: 37: 94: Prefer double-quoted strings inside interpolations.
C: 39: 32: Only use parentheses for ternary expressions with complex conditions.
C: 39: 48: Prefer double-quoted strings inside interpolations.
C: 39: 74: Prefer double-quoted strings inside interpolations.
C: 39:105: Prefer double-quoted strings inside interpolations.
C: 40:  7: Put a comma after the last item of a multiline array.
C: 40: 36: Only use parentheses for ternary expressions with complex conditions.
C: 40: 49: Prefer double-quoted strings inside interpolations.
C: 40: 59: Prefer double-quoted strings inside interpolations.
C: 40: 80: Prefer double-quoted strings inside interpolations.
```

2017-07-26 14:16 UTC, externl commented
I'll fix. Why didn't my audit show this?

2017-07-29 12:01 UTC, ilovezfs commented on Formula/ice.rb
> +    system "xcrun", "clang++", "-DICE_CPP11_MAPPING", "-std=c++11", "-c", "-I#{include}", "-I.", "Hello.cpp"
Using `xcrun make` in formulae will avoid superenv, which isn't permissible.

2017-07-29 12:03 UTC, ilovezfs requested changes

2017-07-29 12:03 UTC, ilovezfs commented on Formula/ice.rb
> +    system "xcrun", "clang++", "-DICE_CPP11_MAPPING", "-std=c++11", "-c", "-I#{include}", "-I.", "Hello.cpp"
We should not use `xcrun` in the `test do` block.

2017-07-31 14:04 UTC, externl commented on Formula/ice.rb
> +    system "xcrun", "clang++", "-DICE_CPP11_MAPPING", "-std=c++11", "-c", "-I#{include}", "-I.", "Hello.cpp"
What do you propose as an alternative?  `xcrun` handles linking with frameworks and is quite convenient.

2017-07-31 16:11 UTC, externl commented on Formula/ice.rb
> +    system "xcrun", "clang++", "-DICE_CPP11_MAPPING", "-std=c++11", "-c", "-I#{include}", "-I.", "Hello.cpp"
@ilovezfs, or is the issue with using compilers in general inside the test block?

2017-07-31 16:37 UTC, ilovezfs commented on Formula/ice.rb
> +    system "xcrun", "clang++", "-DICE_CPP11_MAPPING", "-std=c++11", "-c", "-I#{include}", "-I.", "Hello.cpp"
ENV.cc and ENV.cxx

2017-07-31 16:48 UTC, ilovezfs commented on Formula/ice.rb
> +    system "xcrun", "clang++", "-DICE_CPP11_MAPPING", "-std=c++11", "-c", "-I#{include}", "-I.", "Hello.cpp"
ENV.cc and ENV.cxx

2017-07-31 19:12 UTC, externl commented on Formula/ice.rb
> +    system "xcrun", "clang++", "-DICE_CPP11_MAPPING", "-std=c++11", "-c", "-I#{include}", "-I.", "Hello.cpp"
Can I use `system `xcrun`, ENV.cxx, ...` Otherwise I still have to call `xcrun` to find the sdk location.

2017-07-31 19:23 UTC, externl commented on Formula/ice.rb
> +    system "xcrun", "clang++", "-DICE_CPP11_MAPPING", "-std=c++11", "-c", "-I#{include}", "-I.", "Hello.cpp"
I've updated the test. The first part uses just `ENV.cxx`. The second part uses `xcrun` plus `ENV.cxx`. `xcrun` is required to correctly location the macosx sdk location, which is what's being tested.

2017-08-01 14:52 UTC, externl commented on Formula/ice.rb
> +    system "xcrun", "clang++", "-DICE_CPP11_MAPPING", "-std=c++11", "-c", "-I#{include}", "-I.", "Hello.cpp"
@ilovezfs Is this okay with you?

2017-08-04 16:03 UTC, externl commented on Formula/ice.rb
> +    system "xcrun", "clang++", "-DICE_CPP11_MAPPING", "-std=c++11", "-c", "-I#{include}", "-I.", "Hello.cpp"
@ilovezfs The other option is to remove this part of this test, which I would rather not have to do as it's testing the SDK

2017-08-05 03:52 UTC, JCount commented on Formula/ice.rb
> +    system "xcrun", "clang++", "-DICE_CPP11_MAPPING", "-std=c++11", "-c", "-I#{include}", "-I.", "Hello.cpp"
Why is it necessary for testing the SDK that is built? Specifically, why is it not enough to compile against and test `ice`'s SDK in a more standard manner?

2017-08-07 14:28 UTC, externl commented
I've fixed the test.

2017-08-13 09:57 UTC, fxcoudert commented
Thanks @externl for the pull request!

2017-08-13 09:57 UTC, closed without merging

2017-08-14 09:06 UTC, rleigh-codelibre commented
Have you considered making Ice a versioned package?  The current strategy to completely replace the old version is a world breaking change for end users, who can't update their codebases overnight.  This completely breaks packages which were using Ice 3.6.  Now homebrew supports versioning, would it be possible to have `ice` with `ice@3.7` and `ice@3.6` to allow for some measure of stability and continuity of Ice support on MacOS X?

Thanks,
Roger

2017-08-14 09:11 UTC, ilovezfs commented
@rleigh-codelibre we could consider it, but given ice had 157 install-on-request events in the last month, it may not meet our guidelines for [acceptable versioned formulae](https://github.com/Homebrew/brew/blob/master/docs/Versions.md#acceptable-versioned-formulae). Are you aware of upstream's `ice36` formula? https://github.com/zeroc-ice/homebrew-tap

2017-08-14 09:51 UTC, rleigh-codelibre commented
I wasn't aware, thanks for the pointer!