gradle 4.0.2
Homebrew/homebrew-core pull request #16107
Opened 2017-07-27 11:25 UTC by seanjreilly

Created with `brew bump-formula-pr`.

2017-07-27 12:17 UTC, fxcoudert requested changes

2017-07-27 12:17 UTC, fxcoudert commented on Formula/gradle.rb
> +  url "https://services.gradle.org/distributions/gradle-4.0.2-bin.zip"
Needs the `all` package, not only binaries

2017-07-27 14:57 UTC, seanjreilly commented
If we require the all package, not just the binaries, then shouldn't there be a test that fails when somebody bumps the formula without using -all? All of the tests passed when I used `brew bump-formula-pr`, so it wasn't obvious that I was doing the wrong thing.

2017-07-27 14:58 UTC, seanjreilly commented on Formula/gradle.rb
> +  url "https://services.gradle.org/distributions/gradle-4.0.2-bin.zip"
Unfortunately, this change isn't sufficient. The sha256 hash is different between the two versions of the binary.

2017-07-28 12:28 UTC, seanjreilly commented
@fxcoudert I've rebased with the url change you requested, plus the SHA change that is needed for it to work. Can this be merged now?

Also, if we require the all package, not just the binaries, then shouldn't there be a test that fails when somebody bumps the formula without using -all? All of the tests passed when I used brew bump-formula-pr, so it wasn't obvious that I was doing the wrong thing.

2017-07-28 12:30 UTC, fxcoudert commented
I think the all package is required when using `--with-all`, which is not on by default and thus not tested.

Thanks for updating the PR!

2017-07-28 12:30 UTC, fxcoudert approved these changes

2017-07-28 12:31 UTC, merged

2017-07-28 12:55 UTC, seanjreilly commented
If it's required for something, shouldn't it be tested? This is likely to keep happening otherwise.

2017-07-28 14:54 UTC, indrajitr commented on Formula/gradle.rb
> -  end
devel build should be retained. Raised #16168 for that.