qtkeychain 0.8.0 (new formula)
Homebrew/homebrew-core pull request #16117
Opened 2017-07-27 16:06 UTC by guruz

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-07-28 09:30 UTC, bfontaine requested changes

2017-07-28 09:30 UTC, bfontaine commented on Formula/qtkeychain.rb
> +    assert '#{bin}/testclient 2>&1 | grep account'
Use `assert_match "account", shell_output("#{bin}/testclient 2>&1")` instead.

2017-07-28 09:30 UTC, bfontaine commented on Formula/qtkeychain.rb
> +  depends_on 'cmake' => :build
Use double quotes everywhere.

2017-07-28 09:30 UTC, bfontaine commented on Formula/qtkeychain.rb
> +    # system "#{bin}/testclient", "delete","__qtkeychaintest"
You can remove these comments.

2017-07-28 09:30 UTC, bfontaine commented on Formula/qtkeychain.rb
> +    bin.install "testclient"
Why is this not installed by `make install`?

2017-07-31 08:31 UTC, guruz commented on Formula/qtkeychain.rb
> +    bin.install "testclient"
i guess it's only for development. i only install it to be able to run the brew test. suggestions?

2017-07-31 08:32 UTC, guruz commented on Formula/qtkeychain.rb
> +  depends_on 'cmake' => :build
thanks for review, i'll try to fix later today

2017-07-31 09:49 UTC, ilovezfs commented
@BrewTestBot test this please

2017-08-22 13:58 UTC, ilovezfs commented
@guruz thanks for the PR. Please feel free to open a new one once feedback has been addressed.

2017-08-22 13:58 UTC, closed without merging