pumba 0.4.4 (new formula)
Homebrew/homebrew-core pull request #16112
Opened 2017-07-27 13:32 UTC by alexei-led

Pumba chaos testing tool for Docker: emulate container failures and network problems.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

It's a replacement for [PR 15332](https://github.com/Homebrew/homebrew-core/pull/15332), I've closed previous PR (messed with rebase command) and open a new clean PR with a single file and single commit.

2017-08-02 07:55 UTC, alexei-led commented
@fxcoudert @ilovezfs any feedback?

2017-08-02 10:01 UTC, ilovezfs requested changes

2017-08-02 10:01 UTC, ilovezfs commented on Formula/pumba.rb
> +    shell_output("#{bin}/pumba rm test-container", 0)
This needs to use the software and assert something that shows it worked properly. See `faas-cli` and `jose` for examples. Also, the `, 0` is already the default.

2017-08-03 08:14 UTC, alexei-led commented
By the way, I think that my package is tested much better than many already existing packages. Most of `go` packages on Homebrew just print `help` or `version`. See: `dockviz`, `influxdb`, `ironcli` and others.

2017-08-03 08:17 UTC, alexei-led commented
Anyway, there is no way to run Docker in TestBot. Any ideas? 
My app requires Docker to properly work, so if the BuildBot cannot run Docker I cannot run my wonderful tests!
So, if you have no objections or ideas how to fix tests, I will get back to printing `--version` as many others packages do.

2017-08-03 08:40 UTC, ilovezfs commented
@alexei-led the fact that there are formulae in core that have help or version tests does not change the fact that we now have a higher standard for the test blocks in new formulae.

There are in fact hundreds of formulae with no test block at all (see https://github.com/Homebrew/homebrew-core/issues/11898), which is also completely irrelevant.

2017-08-03 10:26 UTC, alexei-led commented
@ilovezfs So, what is the suggestion? How can I run tests, if BuildBot does not support running Docker?
My app works with Docker - no Docker == no Tests! If it's not possible to run Docker in Jenkins, I cannot do anything here. Sorry.

2017-08-03 14:11 UTC, ilovezfs commented
You can either mock the test sufficiently (see the test in `faas-cli`), or assert that it fails in an expected way (see the tests in `twine-pypi`, `nvm`, and `firebase-cli`).

2017-08-03 14:23 UTC, alexei-led commented
@ilovezfs OK, I've looked at samples. Not helpful at all. It's not possible to mock daemon listening to unix socket and working with gRPC protocol (which is what Docker is) using simple output files.
Pumba uses Docker SDK and connects to Docker daemon over TCP or using Unix socket `/var/lib/docker.sock`. So, in order to check basic functionality I need real running Docker daemon in test environment, or some kind of Mock that can reply to gRPC protocl (binary protocol) over socket or TCP (need to open TCP port for this).
I think it's not possible in Jenkins and very complex to create such mockup in Ruby (I did not find anything even close).

Do you have other suggestions how to test program that works with Docker API?

2017-08-03 14:24 UTC, ilovezfs commented
>or assert that it fails in an expected way (see the tests in twine-pypi, nvm, and firebase-cli).

2017-08-03 14:36 UTC, alexei-led commented
OK I will try to run negative test

2017-08-03 14:37 UTC, ilovezfs commented on Formula/pumba.rb
> +    output = pipe_output("#{bin}/pumba rm test-container 2>&1")
Is the exit code predictable here? If so we can use

```
shell_output("#{bin}/pumba rm test-container 2>&1", whatever_the_expected_non-zero_exit_code_is)
```

2017-08-03 14:37 UTC, ilovezfs commented on Formula/pumba.rb
>      output = shell_output("#{bin}/pumba --version")
you can remove the version check test.

2017-08-03 14:39 UTC, alexei-led commented on Formula/pumba.rb
> +    output = pipe_output("#{bin}/pumba rm test-container 2>&1")
the error code is 0, should I add 0?

2017-08-03 14:39 UTC, alexei-led commented on Formula/pumba.rb
>      output = shell_output("#{bin}/pumba --version")
will do

2017-08-03 14:40 UTC, ilovezfs commented on Formula/pumba.rb
> +    output = pipe_output("#{bin}/pumba rm test-container 2>&1")
0 is the default asserted by shell_output, but it's kind of surprising for the exit code to be 0 if the command failed. Why is that?

2017-08-03 14:49 UTC, alexei-led commented
@ilovezfs build passed, anything else, I should fix?

2017-08-03 14:51 UTC, alexei-led commented on Formula/pumba.rb
> +    output = pipe_output("#{bin}/pumba rm test-container 2>&1")
This is current behavior, I will consider to change it in next release and will add a check to validate error code.

2017-08-03 14:55 UTC, ilovezfs commented on Formula/pumba.rb
> +    output = pipe_output("#{bin}/pumba rm test-container 2>&1")
>This is current behavior, I will consider to change it in next release and will add a check to validate error code.

Thanks.

2017-08-03 14:58 UTC, alexei-led commented on Formula/pumba.rb
> +    output = pipe_output("#{bin}/pumba rm test-container 2>&1")
Anything else, that I should fix for now?

2017-08-03 14:59 UTC, ilovezfs commented on Formula/pumba.rb
> +  # Docker can be installed manually
this comment can be removed

2017-08-03 15:00 UTC, ilovezfs commented on Formula/pumba.rb
> +      system "go", "build", "-o", bin/"pumba", "-ldflags", "-X main.Version=#{version}"
```
      system "go", "build", "-o", bin/"pumba", "-ldflags",
             "-X main.Version=#{version}"
```

2017-08-03 15:12 UTC, ilovezfs approved these changes

2017-08-03 15:13 UTC, ilovezfs commented
@alexei-led do you mind squashing this down to 1 commit? Thanks!

2017-08-03 15:23 UTC, alexei-led commented
squashed into single commit

2017-08-03 16:15 UTC, closed without merging

2017-08-03 16:15 UTC, ilovezfs commented
@alexei-led Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!