nodebrew: fix setup_dirs
Homebrew/homebrew-core pull request #16174
Opened 2017-07-28 20:35 UTC by mecca831

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Can't run setup_dirs as part of the install process, as it's creating
directory under a temp folder

See: https://github.com/Homebrew/homebrew-core/pull/13881

2017-07-31 13:48 UTC, ilovezfs requested changes

2017-07-31 13:48 UTC, ilovezfs commented on Formula/nodebrew.rb
> +      nodebrew setup_dirs
```
#{opt_bin}/nodebrew setup_dirs
```

2017-07-31 21:08 UTC, mecca831 commented on Formula/nodebrew.rb
> +      nodebrew setup_dirs
Updated.

2017-08-02 06:17 UTC, ilovezfs approved these changes

2017-08-02 06:18 UTC, merged

2017-08-02 06:19 UTC, ilovezfs commented
@mecca831 Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!