telnet 54.50.1 (new formula)
Homebrew/homebrew-core pull request #16208
Opened 2017-07-29 22:45 UTC by byss

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Apple did remove telnet from macOS High Sierra, so here are telnet (& libtelnet) built from Apple sources.

2017-07-29 23:31 UTC, fxcoudert commented
Not sure what libtelnet would be used for. And I don't see it on my Sierra machine.

If we want to provide a telnet client, shouldn't we rather package [`inetutils`](https://www.gnu.org/software/inetutils/) for example?

2017-07-30 02:22 UTC, byss commented
@fxcoudert Yeah, libtelnet's only use is to be statically linked with final telnet binary, I suppose. I'd merge these formulas.

Inetutils's telnet provides nearly the same functionality as BSD/Apple version, so I don't see why any implementation should be preferred over another.

2017-07-30 03:24 UTC, DomT4 commented
> Inetutils's telnet provides nearly the same functionality as BSD/Apple version, so I don't see why any implementation should be preferred over another.

Well, for one, Apple's `telnet` will over time, if not rather rapidly, stop receiving updates & it's not like historically `telnet` tools have proven immune from vulnerabilities.

2017-07-31 05:01 UTC, ilovezfs commented
Until there are CVEs with Apple's version that are unpatched (not likely for a while, since it 10.12 support will still be around for a couple years), I don't think it's a problem for us to package it.

I also don't think there's anything wrong with offering multiple telnet clients such as inetutils and the FreeBSD version alongside the Apple version.

2017-07-31 05:04 UTC, ilovezfs requested changes

2017-07-31 05:04 UTC, ilovezfs commented on Formula/telnet.rb
> +  depends_on :macos => :high_sierra
I think we want
```
keg_only :provided_pre_high_sierra
```
instead.

2017-07-31 05:04 UTC, ilovezfs commented on Formula/telnet.rb
> +  depends_on :xcode => :build
Is there a minimum required for it to build successfully?

2017-07-31 09:48 UTC, ilovezfs commented
@BrewTestBot test this please

2017-07-31 14:56 UTC, DomT4 commented
> Until there are CVEs with Apple's version that are unpatched (not likely for a while, since 10.12 support will still be around for a couple years), I don't think it's a problem for us to package it.

Aye, that's fair enough.

2017-07-31 14:58 UTC, DomT4 commented on Formula/telnet.rb
> +      libtelnet_dst = buildpath / "telnet.tproj" / "build" / "Products"
`buildpath/"telnet.tproj/build/Products"`

2017-07-31 14:58 UTC, DomT4 commented on Formula/telnet.rb
> +      libtelnet_dst.install("build/Release/libtelnet.a")
Don't need the `()` here or below.

2017-07-31 14:58 UTC, DomT4 commented on Formula/telnet.rb
> +    system "make", "-C", "telnet.tproj", "OBJROOT=build/Intermediates", "SYMROOT=build/Products", "DSTROOT=build/Archive", "CFLAGS=$(CC_Flags) -isystembuild/Products/", "LDFLAGS=$(LD_Flags) -Lbuild/P
Try to wrap this to ~80 characters for the sake of readability.

2017-07-31 14:58 UTC, DomT4 commented on Formula/telnet.rb
> +    output = shell_output("(sleep 2; echo 'quit') | telnet towel.blinkenlights.nl", 1)
Can use `pipe_output` here, and you'll want to use `#{bin}/telnet` rather than simply `telnet`.

2017-07-31 15:18 UTC, byss commented on Formula/telnet.rb
> +  depends_on :xcode => :build
I am pretty sure that any more or less modern Xcode version would suffice:

- Sources are practically unchanged after 2008.
- `.xcodeproj` of `libtelnet` does not seem to have any outstanding build settings.
- `telnet.tproj/Makefile` also does not contain anything suspicious.

So yeah, I think we are pretty safe to assume that Xcode version does not make much of a difference.

2017-08-01 17:42 UTC, JasonCoal approved these changes

2017-08-01 17:46 UTC, fxcoudert commented
Test fails because:

```$ telnet towel.blinkenlights.nl </dev/null
Trying 94.142.241.111...
Connected to towel.blinkenlights.nl.
Escape character is '^]'.
Connection closed by foreign host.
```

2017-08-01 17:47 UTC, DomT4 commented on Formula/telnet.rb
> +  depends_on :xcode => :build
Should be a blank line between the `keg_only` and `depends_on`. Very minor nit, but.

2017-08-01 17:48 UTC, DomT4 commented on Formula/telnet.rb
> +    output = shell_output("MANPAGER='head -n 2' man telnet")
Probably don't need the latter test here. Doesn't add anything to the stronger one above, IMO.

2017-08-01 18:25 UTC, byss commented
> Test fails 

Unfortunately, yes. The reason it does so is that `telnet` receives `quit` command just after its launch and not with slight delay intended in the original version of the test:

```ruby
output = shell_output("(sleep 2; echo 'quit') | telnet towel.blinkenlights.nl", 1)
```

I just can't think up a solution using `pipe_output` as per @DomT4's [suggestion](https://github.com/Homebrew/homebrew-core/pull/16208/files/da7ecc10a55a2b9912f2e58b03d6ec51a28d0287#diff-e056ee4d1945909229f9cdf2d1086d64). Any ideas?

2017-08-02 03:28 UTC, DomT4 commented
```ruby
  test do
    IO.popen("#{bin}/telnet 'towel.blinkenlights.nl'", "w+") do |pipe|
      sleep 2
      pipe.puts "quit\n"
      pipe.close_write
      assert_match "So long And Thanks for all the fish", pipe.read
    end
  end
```

2017-08-03 06:29 UTC, ilovezfs commented on Formula/telnet.rb
> +  desc "Apple telnet built from macOS 10.12.4 sources"
Maybe just `User interface to the TELNET protocol` as it's described in the man page

2017-08-07 10:07 UTC, byss commented on Formula/telnet.rb
> +  desc "Apple telnet built from macOS 10.12.4 sources"
> I also don't think there's anything wrong with offering multiple telnet clients such as inetutils and the FreeBSD version alongside the Apple version.

I've looked at several man pages, and they all have quite similar `telnet` description. Shouldn't formula description indicate precisely differences from other hypothetical formulas? Or, we may consider using both descriptions (something like `User interface to the TELNET protocol (built from macOS 10.12.4 source)`)?

https://linux.die.net/man/1/telnet
http://www-it.desy.de/cgi-bin/man-cgi?telnet+1
https://www.freebsd.org/cgi/man.cgi?telnet

2017-08-12 12:20 UTC, ilovezfs commented on Formula/telnet.rb
> +  desc "Apple telnet built from macOS 10.12.4 sources"
Let's avoid hard-coding the version number in the description but you can mention the sources are from Sierra.

2017-08-13 13:26 UTC, byss commented on Formula/telnet.rb
> +  desc "Apple telnet built from macOS 10.12.4 sources"
Sounds reasonable.

2017-08-13 19:52 UTC, ilovezfs commented
The test is failing.
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6518/version=sierra/console

2017-08-13 20:39 UTC, DomT4 commented
Hmm. That test has passed CI repeatedly before now. Maybe just a hiccup?

2017-08-13 20:48 UTC, ilovezfs commented
@DomT4 probably so.

2017-08-14 06:46 UTC, ilovezfs commented
Tried again. Died again.

2017-08-14 19:07 UTC, byss commented
It seems that the original StarWars server isn't going to be revived any time soon, but there's another still working (BOFH excuses). I'll update the test, but it seems that I should probably develop a better one that doesn't need any third-party servers, build and run bundled `telnetd`, for example.

2017-08-16 07:53 UTC, byss commented
That's strange, test is woking fine on my local machine.

2017-08-20 16:18 UTC, ilovezfs commented
Any luck figuring out the problem?

2017-08-22 15:34 UTC, ilovezfs commented
@byss ping

2017-08-22 19:27 UTC, byss commented
I'm not exactly proud of my solution, but the test is now green and has not become completely useless, so I call it a victory. Anyway, building and using `telnetd` from these same sources still looks like a much more reliable and straightforward solution. I'll try to find some time to implement it... some day, I hope.

2017-08-22 19:36 UTC, ilovezfs approved these changes

2017-08-22 19:39 UTC, closed without merging

2017-08-22 19:39 UTC, ilovezfs commented
>Anyway, building and using telnetd from these same sources still looks like a much more reliable and straightforward solution. I'll try to find some time to implement it... some day, I hope.

That would be great!

Thanks for your first contribution to Homebrew @byss! Without people like you submitting PRs we couldn't run this project. You rock!

2017-08-22 19:53 UTC, byss commented
Thanks, it was actually quite a lot of fun along with some interesting experience! :)

2017-09-26 04:35 UTC, ylluminate commented
Has anyone pursued getting FreeBSD `telnet` and `ftp` working on macOS as a sound and future-proofed fix?

2017-09-26 04:37 UTC, ilovezfs commented
@ylluminate only other effort I'm aware of is https://github.com/theeternalsw0rd/telnet-macos which seems stagnant.

2017-09-26 04:40 UTC, ylluminate commented
Interesting, thanks @ilovezfs. With the current choice of Apple in this area and given problems with [some things](https://emacs.stackexchange.com/questions/35747/making-dired-work-with-ftp-on-os-x-10-13) that rely on these BSD utils, it would seem prudent to have a solid up-to-date fork repo OR just an extraction of the FBSD variants.

2017-09-26 04:44 UTC, ilovezfs commented
@ylluminate the main problem with these things is that if there's a bug, it will be difficult to report to FreeBSD as if they were upstream for macOS unless the bug also happens to affect FreeBSD. So we really need a project that is explicitly upstream for a macOS telnet.

2017-09-26 04:50 UTC, ylluminate commented
I see what you're saying, but... if only... :\ 

The way Apple is moving, it's apparently like they are saying "well, this door doesn't have [secure enough] locks, so let's just take the door away altogether."  If it were isolated enough it would probably be satisfactory since these are predominantly client tools vs services.

2017-09-26 04:57 UTC, ilovezfs commented
@ylluminate we also have an inetutils formula which has
```
$ ls -1  /usr/local/Cellar/inetutils/1.9.4/libexec/gnubin/
dnsdomainname
ftp
hostname
ifconfig
logger
ping
ping6
rcp
rexec
rlogin
rsh
talk
telnet
tftp
traceroute
whois
```
so between that and the `telnet` formula, it should be OK for a while :)

2017-09-26 05:04 UTC, ylluminarious commented
@ilovezfs The only problem with the GNU `inetutils` formula is that they don't seem to work quite right on OS X. Understandably so; they are rarely, if ever, used on anything but Linux.

@ylluminate linked to [a question on StackExchange which I posted](https://emacs.stackexchange.com/questions/35747/making-dired-work-with-ftp-on-os-x-10-13) that goes into some more detail about these differences (as it relates specifically to `ftp`). I presume that there may be problems with the other utils as well.

2017-09-26 05:07 UTC, ilovezfs commented
@ylluminarious you may want to report those things to `inetutils` upstream.

2017-09-26 05:11 UTC, ylluminarious commented
@ilovezfs That's not a bad idea... the only thing that made me hesitant to do that is that they may not be interested in problems relating to non-Linux systems (and depending on who the maintainers are, they may have a disdain for "non-free" systems).

But if that becomes the best course of action, I suppose I'll try it anyway.

2017-09-26 05:13 UTC, ilovezfs commented
@ylluminarious the GNU world is generally pretty tolerant of macOS these days. I wouldn't be shy.

2017-09-26 05:16 UTC, ylluminarious commented
@ilovezfs Alright, I'll give it a shot.

If it turns out that they are uninterested in fixing OS X problems, I think that @ylluminate's ideas regarding using FreeBSD tools should probably be considered more seriously.

2017-09-26 05:18 UTC, ilovezfs commented
>regarding using FreeBSD tools should probably be considered more seriously

Someone needs to start a project that is upstream for those tools on macOS if it comes to that.

2017-10-11 07:32 UTC, ylluminarious commented
@ilovezfs Well, I reported a bug on [`bug-inetutils`,](http://lists.gnu.org/archive/html/bug-inetutils/2017-09/msg00000.html) but it's been 2 weeks and no answer. Not to mention that `inetutils` doesn't appear very active right now and its latest release was in 2015.

Anyway, since I'm having no luck with `inetutils` I've decided to go ahead and bite the bullet and make formulas for Apple's missing tools. My PR is available [here,](https://github.com/Homebrew/homebrew-core/pull/19296) feedback is appreciated.