wxmac: fix compilation on High Sierra
Homebrew/homebrew-core pull request #16479
Opened 2017-08-07 09:51 UTC by fxcoudert

Revisiting the need to patch `wxmac`, in a separate PR:

- fix was accepted and will be applied upstream
- fix is simple (one `CFLAGS` addition)… we have plenty of formulas that fiddle with `CFLAGS`
- `wxmac` had 63,260 installs in the last 100 days, 95% as a dependency (erlang being the main user)

Yes, it's unfortunate upstream is not willing to cut a new release for High Sierra. But the risks here are pretty limited and the fix self-contained. And I'd be willing to deal with fallout 😉

2017-08-07 09:53 UTC, ilovezfs submitted a review, later dismissed
.

2017-08-07 12:03 UTC, fxcoudert commented
I disagree: the patch is well within the standards of what we're used to accept. I do not think we ought to use users' discontent to put pressure on upstream to cut releases, when the fix is easy, well understood, low risk.

2017-08-10 11:46 UTC, ilovezfs requested changes

2017-08-10 11:46 UTC, ilovezfs commented on Formula/wxmac.rb
> +  patch :DATA
Let's use a `patch do` block with your commit.

```
    patch do
      url "https://github.com/wxWidgets/wxWidgets/commit/9a610eadcfe.patch?full_index=1"
      sha256 "b445ddf1331b8ec21790b7e3fe3ac6059a2548002e7cbb9bf22b597baf32e3bf"
    end
```

2017-08-10 11:49 UTC, ilovezfs commented on Formula/wxmac.rb
> +  patch :DATA
Also, is the patch needed for devel or should it be in `stable do`?

2017-08-10 11:57 UTC, fxcoudert commented on Formula/wxmac.rb
> +  patch :DATA
I didn't think the commit would have the regenerated file, but it does!

Patch can be included on devel, it doesn't hurt.

2017-08-10 16:57 UTC, merged