mimic 1.2.0.2 (new formula)
Homebrew/homebrew-core pull request #16480
Opened 2017-08-07 10:38 UTC by cbarcenas

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is a formula for [Mimic](https://mimic.mycroft.ai/), the TTS engine used by the [Mycroft](https://mycroft.ai/) AI assistant project.

The formula passes `brew audit --strict`, but fails `brew audit --strict --new-formula` due to one error:
```
mimic:
  * Dependency 'icu4c' may be unnecessary as it is provided by macOS; try to build this formula without it.
Error: 1 problem in 1 formula
```

I tried to build the formula without the without the `icu4c` keg-only dependency, but it failed to compile; so, please consider it for inclusion despite the audit output.

Although a partial implementation of ICU is provided by OS X, it does not include all functionality and does not include headers required to compile against the Apple-distributed version of the library. (It may even be worth removing this warning entirely from `brew audit --new-formula`?)

2017-08-07 16:31 UTC, fxcoudert requested changes

2017-08-07 16:31 UTC, fxcoudert commented on Formula/mimic.rb
> +    system "make", "check"
We don't run testsuites or checks except for security software. Please remove this line.

2017-08-07 16:31 UTC, fxcoudert commented on Formula/mimic.rb
> +    system bin/"mimic", "-t", "Hello, Homebrew!", testpath/"test.wav"
`testpath/` is I think unnecessary here

2017-08-07 16:31 UTC, fxcoudert commented on Formula/mimic.rb
> +  desc "Mycroft's TTS engine, based on CMU's Flite (Festival Lite)"
I don't understand this description at all (not knowing what TTS or CMU are. Please use plain English :)

2017-08-07 19:01 UTC, cbarcenas commented
Pushed up a new branch containing your requested changes. Thanks for the feedback!

2017-08-18 14:11 UTC, cbarcenas commented
Bump. :)

2017-08-20 03:48 UTC, JCount commented
@BrewTestBot test this please

2017-08-22 15:28 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @cbarcenas! Without people like you submitting PRs we couldn't run this project. You rock!

2017-08-22 15:29 UTC, closed without merging