Bump version and inject SHA into version ldflags.
Homebrew/homebrew-core pull request #16523
Opened 2017-08-08 11:14 UTC by alexellis

Signed-off-by: Alex Ellis <alexellis2@gmail.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-08-08 11:16 UTC, alexellis commented
Hi, this was previously handled by @johnmccabe .. I'm wanting to bump the version and to match the new version of the CLI which injects a version / SHA at build-time.

2017-08-08 13:43 UTC, alexellis commented
Ping @ilovezfs

2017-08-08 15:04 UTC, ilovezfs commented
@alexellis I think you'll want to build from the tag instead of the tarball if the git commit needs to be in there. The SHA-256 of the source archive tarball is the not the same thing as a commit hash. You can take a look at the `docker` formula and the `gitlab-ci-multi-runner` formula for examples.

2017-08-08 15:09 UTC, alexellis commented
Thanks for the comment. By downloading the src tarball we don't have any sort of Git access, correct? At the moment I'm mainly looking at putting a unique ID into the CLI built by brew. The Git Commit ID would be better.

2017-08-08 15:31 UTC, ilovezfs commented
These lines:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker.rb#L4-L6
https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker.rb#L31-L35

2017-08-08 15:46 UTC, alexellis commented
@ilovezfs this now matches the build process via https://github.com/alexellis/faas-cli/blob/master/Dockerfile.redist

2017-08-08 15:47 UTC, ilovezfs commented on Formula/faas-cli.rb
> +    :tag => "0.4.5",
The `:` should be directly under the `"`.

2017-08-08 15:48 UTC, ilovezfs commented on Formula/faas-cli.rb
> +    :revision => "e9c738f9a2833980a1bfc0102b3dfdf0cce2684a"
The `:` should be directly under the `:`

2017-08-08 15:49 UTC, ilovezfs commented on Formula/faas-cli.rb
> +      system "go", "build", "-ldflags", ldflags, "-a", "-installsuffix", "cgo", "-o", bin/"faas-cli"
```
      system "go", "build", "-ldflags", "-X main.GitCommit=#{commit}", "-a",
             "-installsuffix", "cgo", "-o", bin/"faas-cli"
```

2017-08-08 15:49 UTC, ilovezfs commented on Formula/faas-cli.rb
> +      system "go", "build", "-ldflags", ldflags, "-a", "-installsuffix", "cgo", "-o", bin/"faas-cli"
why `-cgo`?

2017-08-08 15:53 UTC, alexellis commented on Formula/faas-cli.rb
> +      system "go", "build", "-ldflags", ldflags, "-a", "-installsuffix", "cgo", "-o", bin/"faas-cli"
It's so it matches the build in the repository.

2017-08-08 15:54 UTC, alexellis commented on Formula/faas-cli.rb
> +    :revision => "e9c738f9a2833980a1bfc0102b3dfdf0cce2684a"
What do you mean?

2017-08-08 15:54 UTC, ilovezfs commented on Formula/faas-cli.rb
> +      system "go", "build", "-ldflags", ldflags, "-a", "-installsuffix", "cgo", "-o", bin/"faas-cli"
ok

2017-08-08 15:57 UTC, ilovezfs commented on Formula/faas-cli.rb
> +    :revision => "e9c738f9a2833980a1bfc0102b3dfdf0cce2684a"
```
  url "https://github.com/alexellis/faas-cli.git",
    :tag => "0.4.5",
    :revision => "e9c738f9a2833980a1bfc0102b3dfdf0cce2684a"
```
vs.
```
  url "https://github.com/alexellis/faas-cli.git",
      :tag => "0.4.5",
      :revision => "e9c738f9a2833980a1bfc0102b3dfdf0cce2684a"
```

2017-08-08 15:58 UTC, ilovezfs commented on Formula/faas-cli.rb
> +      system "go", "build", "-ldflags", ldflags, "-a", "-installsuffix", "cgo", "-o", bin/"faas-cli"
So just the style change then:
```
      system "go", "build", "-ldflags", "-X main.GitCommit=#{commit}", "-a",
             "-installsuffix", "cgo", "-o", bin/"faas-cli"
```

2017-08-08 16:22 UTC, alexellis commented on Formula/faas-cli.rb
> +      system "go", "build", "-ldflags", ldflags, "-a", "-installsuffix", "cgo", "-o", bin/"faas-cli"
I can't see a difference, what did you change?

2017-08-08 16:22 UTC, alexellis commented on Formula/faas-cli.rb
> +    :revision => "e9c738f9a2833980a1bfc0102b3dfdf0cce2684a"
I can't see a difference unless you mean the whitespace?

2017-08-08 16:24 UTC, alexellis commented on Formula/faas-cli.rb
> +      system "go", "build", "-ldflags", ldflags, "-a", "-installsuffix", "cgo", "-o", bin/"faas-cli"
You mean you want me to wrap the string?

2017-08-08 16:27 UTC, alexellis commented
I think we're all good for the Git changeover and your style feedback now. Are you OK to have it merged?

2017-08-08 17:28 UTC, ilovezfs commented on Formula/faas-cli.rb
> +      system "go", "build", "-ldflags", ldflags, "-a", "-installsuffix", "cgo", "-o", bin/"faas-cli"
I inlined the flag and made sure it didn't go passed the eightieth column.

2017-08-08 17:31 UTC, ilovezfs approved these changes

2017-08-09 08:28 UTC, ilovezfs requested changes
Is this supposed to be for 0.4.5 or 0.6.0?

2017-08-09 08:37 UTC, alexellis commented
It's for 0.4.5 - thanks for picking that up I've updated the title.

2017-08-09 08:38 UTC, ilovezfs approved these changes

2017-08-09 09:07 UTC, closed without merging

2017-08-09 09:30 UTC, ilovezfs commented
@alexellis Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!