xmrig 2.2.1
Homebrew/homebrew-core pull request #16576
Opened 2017-08-09 12:39 UTC by rtau

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-08-09 15:40 UTC, fxcoudert requested changes

2017-08-09 15:40 UTC, fxcoudert commented on Formula/xmrig.rb
> +  desc ""
Description missing

2017-08-09 15:40 UTC, fxcoudert commented on Formula/xmrig.rb
> +  url "https://github.com/xmrig/xmrig.git", :tag => "v2.2.1", :revision => "92d787c817dfa92ca38e36f634195f31ff7d40c3"
We prefer building from source tarball (`https://github.com/xmrig/xmrig/archive/v2.2.1.tar.gz`) than git tag

2017-08-09 15:40 UTC, fxcoudert commented on Formula/xmrig.rb
> +    system "cmake", "..", "-DCMAKE_BUILD_TYPE=Release", "-DUV_LIBRARY=/usr/local/opt/libuv/lib/libuv.a", *std_cmake_args
For path to static libuv, please use: `#{Formula["libuv"].opt_lib}/libuv.a`

2017-08-09 15:40 UTC, fxcoudert commented on Formula/xmrig.rb
> +    Dir.mkdir("build")
`mkdir "build" do`

2017-08-09 15:40 UTC, fxcoudert commented on Formula/xmrig.rb
> +    bin.install "xmrig"
No `make install`? Nothing other than the `xmrig` binary to install? Man pages, etc.?

2017-08-09 15:40 UTC, fxcoudert commented on Formula/xmrig.rb
> +    system "#{bin}/xmrig", "-V"
We need a test that does something, no just output version number

2017-08-22 15:04 UTC, ilovezfs commented
@rtau thanks for the pull request. Please feel free to open a new one when the feedback has been addressed.

2017-08-22 15:04 UTC, closed without merging