workflows/autobump: stop running on workflow updates
Homebrew/homebrew-core pull request #167020
Opened 2024-03-24 01:47 UTC by cho-m

The original reason for this in #129465 was for @BrewTestBot's fork but I don't think this behavior is needed our current workflows. We may need to reconsider if we change the approach in future.

Fixes #164661

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2024-03-24 03:29 UTC, ZhongRuoyu approved these changes

2024-03-24 08:13 UTC, SMillerDev requested changes, later dismissed
We should still try to run it if we change it

2024-03-24 16:47 UTC, cho-m commented
> We should still try to run it if we change it

Do you mean running on modifications of `.github/workflows/autobump.yml`?

2024-03-24 17:22 UTC, SMillerDev commented
Yeah, otherwise it'll take a while before we figure out we broke it

2024-03-24 18:43 UTC, cho-m commented
Okay. Should be fine to run on those as we aren't modifying this workflow that often after splitting out the bump list into a separate file.

2024-03-24 19:12 UTC, MikeMcQuaid approved these changes

2024-03-24 19:13 UTC, MikeMcQuaid commented
Thanks again @cho-m!

2024-03-25 07:02 UTC, SMillerDev approved these changes

2024-03-25 08:43 UTC, merged