rage 0.10.0 (new formula)
Homebrew/homebrew-core pull request #168200
Opened 2024-04-06 13:00 UTC by pavelzw

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2024-04-06 14:57 UTC, chenrui333 commented on Formula/r/rage.rb
> +    # \n because of https://github.com/str4d/rage/issues/484
👍

2024-04-06 14:57 UTC, chenrui333 approved these changes

2024-04-06 19:38 UTC, SMillerDev commented on Formula/r/rage.rb
> +  end
Please don't use a separate function for this, since it makes the formula harder to read.

2024-04-07 06:49 UTC, ZhongRuoyu requested changes

2024-04-07 07:43 UTC, ZhongRuoyu approved these changes
Thanks!

2024-04-07 13:12 UTC, chenrui333 approved these changes

2024-04-07 13:19 UTC, merged