luaver 1.1.0
Homebrew/homebrew-core pull request #16839
Opened 2017-08-15 21:23 UTC by JaredSartin

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Updates to latest luaver with zsh support

2017-08-15 22:13 UTC, JaredSartin commented
Meant ruby - not rails... #longday

2017-08-15 22:14 UTC, JaredSartin commented
For visibility:
```
jared•~» brew test --verbose luaver                                                                                                                                                                                                [15:05:20]
Testing luaver
/usr/bin/sandbox-exec -f /tmp/homebrew20170815-23820-wqfmiu.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/luaver.rb --verbose
==> . /usr/local/Cellar/luaver/1.1.0/bin/luaver && luaver install 5.3.3 < /dev/null
Error: luaver: failed
Failed executing: . /usr/local/Cellar/luaver/1.1.0/bin/luaver && luaver install 5.3.3 < /dev/null
/usr/local/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/luaver.rb:28:in `block (3 levels) in <class:Luaver>'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/std.rb:76:in `deparallelize'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/luaver.rb:28:in `block (2 levels) in <class:Luaver>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/luaver.rb:27:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/luaver.rb:27:in `block in <class:Luaver>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:834:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

2017-08-15 22:34 UTC, DhavalKapil commented
`luaver`'s install script no longer sources the profile. I'm not versed with homebrew. Can that be the reason for failing tests?

2017-08-15 22:53 UTC, JaredSartin commented
@DhavalKapil maybe... I will revisit the tests

2017-08-15 23:00 UTC, JaredSartin commented
@DhavalKapil got it closer - see next commit:

```
==>  lua-5.3.3 successfully installed. Do you want to switch to this version? [Y/n]:
==> /usr/local/Cellar/luaver/1.1.0/bin/luaver use 5.3.3 && lua -v
==>  Switching to lua-5.3.3
==>  Successfully switched to lua-5.3.3
sh: lua: command not found
```

2017-08-16 09:04 UTC, ilovezfs requested changes

2017-08-16 09:04 UTC, ilovezfs commented on Formula/luaver.rb
> +      ENV.deparallelize
Why is this set unconditionally and no longer scoped to just the installs?

2017-08-16 09:04 UTC, ilovezfs commented on Formula/luaver.rb
> +    url "https://github.com/DhavalKapil/luaver/archive/v1.1.0.tar.gz"
The url and checksum should be moved above head and the `stable do ... end` removed.

2017-08-16 17:51 UTC, JaredSartin commented on Formula/luaver.rb
> +    url "https://github.com/DhavalKapil/luaver/archive/v1.1.0.tar.gz"
Can do

2017-08-16 17:51 UTC, JaredSartin commented on Formula/luaver.rb
> +      ENV.deparallelize
Looks like a leftover of the broken build, will fix

2017-08-16 21:34 UTC, merged

2017-08-16 21:36 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @JaredSartin! Without people like you submitting PRs we couldn't run this project. You rock!