cling 0.4 (new formula)
Homebrew/homebrew-core pull request #16841
Opened 2017-08-15 22:38 UTC by AndrewSB

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

I'm having some trouble getting this to build, this might be WIP

2017-08-20 03:56 UTC, JCount commented
Why isn't this using the main repository at https://github.com/root-project/cling?

2017-08-21 20:27 UTC, AndrewSB commented
thats a great question, I didn't realize it wasn't @vgvassilev's project. I'll change it soon :)

2017-08-22 06:16 UTC, vgvassilev commented
Yeah, both repos are auto synced with the true main repo https://github.com/root-project/root :). Either one should be fine.

2017-08-22 14:24 UTC, fxcoudert requested changes

2017-08-22 14:24 UTC, fxcoudert commented on Formula/cling.rb
> +# PLEASE REMOVE ALL GENERATED COMMENTS BEFORE SUBMITTING YOUR PULL REQUEST!
I am sure you will understand that reading in your pull request the comment saying `+# PLEASE REMOVE ALL GENERATED COMMENTS BEFORE SUBMITTING YOUR PULL REQUEST!` does nothing to persuade us that the formula will follow Homebrew's rules for new formulas…

2017-08-22 14:24 UTC, fxcoudert commented on Formula/cling.rb
> +  homepage "https://rawgit.com/vgvassilev/cling/master/www/index.html"
Use the official ROOT webpage https://root.cern.ch/cling

2017-08-22 14:24 UTC, fxcoudert commented on Formula/cling.rb
> +  url "https://github.com/vgvassilev/cling/archive/v0.4.tar.gz"
Please install from official sources

2017-08-22 14:24 UTC, fxcoudert commented on Formula/cling.rb
> +    url "https://github.com/vgvassilev/cling/archive/v0.4.tar.gz"
Please install from official sources

2017-08-22 14:24 UTC, fxcoudert commented on Formula/cling.rb
> +    url "https://github.com/vgvassilev/clang.git", :using => :git, :tag => "cling-patches-r302975", :revision => "1d3611b352ada6e8fc8dd41631bd17495f37b258"
Please install from official sources

2017-08-22 14:24 UTC, fxcoudert commented on Formula/cling.rb
> +    system "#{bin}/cling", "-v"
We need a test that actually does something

2017-08-22 14:25 UTC, fxcoudert commented
```
Error: cling-patches-r302975 tag should be 1d3611b352ada6e8fc8dd41631bd17495f37b258
but is actually 280204113c744b685279a4c458cbdfff95a6a829
```

```
cling:
  * C: 21: col 13: sha256 should be 64 characters
  * Dependency 'llvm' may be unnecessary as it is provided by macOS; try to build this formula without it.
  * Please remove default template comments
  * Please remove default template comments
```

2017-09-10 11:13 UTC, closed without merging