frugal 2.8.1 (new formula)
Homebrew/homebrew-core pull request #16922
Opened 2017-08-17 21:55 UTC by charliestrawn-wf

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-08-20 16:03 UTC, ilovezfs requested changes

2017-08-20 16:03 UTC, ilovezfs commented on Formula/frugal.rb
> +    system "#{bin}/frugal", "--gen", "py", testpath/"test.frugal"
Does this generate a specific file with certain contents? We should verify it exists and has the correct contents if so.

2017-08-20 16:03 UTC, ilovezfs commented on Formula/frugal.rb
> +  desc "Thrift on steroids."
Please add a bit more description, and no final period.

2017-08-20 16:03 UTC, ilovezfs commented on Formula/frugal.rb
> +    dir.install buildpath.children
```
    (buildpath/"src/github.com/Workiva/frugal").install buildpath.children
```
since it doesn't go passed the eightieth column.

2017-08-20 22:34 UTC, charliestrawn-wf commented
Thanks! This is my first homebrew formula, and I'm very grateful for the feedback.

2017-08-22 14:40 UTC, ilovezfs requested changes

2017-08-22 14:40 UTC, ilovezfs commented on Formula/frugal.rb
> +    assertion = output.include? "type Test float64"
```
  test do
    (testpath/"test.frugal").write("typedef double Test")
    system "#{bin}/frugal", "--gen", "go", testpath/"test.frugal"
    assert_match "type Test float64", (testpath/"gen-go/test/f_types.go").read
  end
```

2017-08-22 14:42 UTC, ilovezfs commented on Formula/frugal.rb
> +    assertion = output.include? "type Test float64"
and looks like it can be `"test.frugal"` instead of `testpath/"test.frugal"`

2017-08-22 20:10 UTC, ilovezfs approved these changes

2017-08-22 20:11 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @charliestrawn-wf! Without people like you submitting PRs we couldn't run this project. You rock!

2017-08-22 20:11 UTC, closed without merging

2017-08-22 20:47 UTC, charliestrawn-wf commented
Thanks @ilovezfs! Did you mean to close instead of merge this?