s3deploy 1.0.8 (new formula)
Homebrew/homebrew-core pull request #16943
Opened 2017-08-18 11:24 UTC by bep

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-08-18 12:52 UTC, tchajed requested changes
Thanks for your contribution to Homebrew!

It looks like the test for this formula is failing. Once you've fixed it, you can test locally with `brew test s3deploy`. (The contributing guidelines don't mention this for new formulae but it is a requirement for the continuous integration - sorry!)

2017-08-18 12:52 UTC, tchajed commented on Formula/s3deploy.rb
> +    system "#{bin}/goreleaser", "-h"
Did you mean to test `s3deploy` here?

2017-08-18 13:01 UTC, bep commented on Formula/s3deploy.rb
> +    system "#{bin}/goreleaser", "-h"
Oh, sorry ... Copy and paste error ... I will fix.

2017-08-18 16:02 UTC, ilovezfs requested changes

2017-08-18 16:02 UTC, ilovezfs commented on Formula/s3deploy.rb
> +  url "https://github.com/bep/s3deploy/releases/download/v1.0.8/s3deploy_1.0.8_macOS-64bit.tar.gz"
This needs to be built from source.

2017-08-22 14:27 UTC, ilovezfs commented
Feel free to open a new PR once this is actually building from source.

2017-08-22 14:27 UTC, closed without merging