mesa 24.0.5
Homebrew/homebrew-core pull request #169515
Opened 2024-04-19 12:08 UTC by chenrui333

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2024-04-19 20:05 UTC, fxcoudert approved these changes

2024-04-20 08:30 UTC, fxcoudert requested changes
Please hold for https://github.com/Homebrew/homebrew-core/pull/165206

2024-04-20 13:12 UTC, chenrui333 commented
move to draft 👍

2024-04-23 07:41 UTC, fxcoudert approved these changes

2024-04-23 07:42 UTC, fxcoudert requested changes

2024-04-23 07:42 UTC, fxcoudert commented on Formula/m/mesa.rb
>    revision 1
```suggestion
```

2024-04-23 22:14 UTC, fxcoudert approved these changes

2024-04-24 02:28 UTC, merged