sqlcipher 3.4.1 ← upstream patch for CVE-2017-10989
Homebrew/homebrew-core pull request #16961
Opened 2017-08-18 18:39 UTC by justinclift

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
  * Nope.  It whinges about a missing test case.  I'm not up for creating one atm (way too brain fried). :smile:

2017-08-18 18:45 UTC, justinclift commented
This is an upstream - SQLite - patch to fix CVE-2017-10989, which SQLCipher inherited from SQLite.  Hard coded it here, but it wouldn't be hard to point the formula at [the upstream patch](https://sqlite.org/src/info/66de6f4a) directly if that's better.

This patch is included in SQLite 3.20.0, which SQLCipher haven't yet rebased on.  They're planning on getting this done, but it might take a few weeks.

More details for CVE-2017-10989: https://www.cvedetails.com/cve/CVE-2017-10989/

The CVE doesn't seem like a high-urgency, super bad thing, this is more just me being a bit safety conscious, just in case. :smile:

2017-08-18 18:47 UTC, justinclift commented
Gah, forgot to `git add` the patch depth fix before pushing.  Now done. :smile:

2017-08-18 19:20 UTC, justinclift commented
> Yes, please point it at the patch directly ...

No worries.  Will push an update in a min.

> Do you have a reference for this?

Good point, it was private email.  But, @sjlombardo (SQLCipher team) should be able to confirm. :smile:

2017-08-18 19:30 UTC, justinclift commented
Updated the patch to pull directly from the upstream SQLite repo.

2017-08-19 14:19 UTC, JCount requested changes
@justinclift Could you add a `revision 1` line to the formula directly after the `sha256` line, and also change the commit message to something like `sqlcipher: add upstream sqlite patch for CVE-2017-10989`, thanks. Also, does the patch still apply correctly during a `HEAD` build?

2017-08-19 14:36 UTC, justinclift commented
> Could you add a revision 1 line to the formula directly after the sha256 line, and also change the commit message to something like sqlcipher: add upstream sqlite patch for CVE-2017-10989

Done.


> ... does the patch still apply correctly during a HEAD build?

Interesting thought.  Just tried it now, and yep that seems good too:

```
$ brew install sqlcipher --with-fts --HEAD
==> Cloning https://github.com/sqlcipher/sqlcipher.git
Cloning into '/Users/jc/Library/Caches/Homebrew/sqlcipher--git'...
remote: Counting objects: 1595, done.
remote: Compressing objects: 100% (1537/1537), done.
remote: Total 1595 (delta 101), reused 846 (delta 50), pack-reused 0
Receiving objects: 100% (1595/1595), 13.70 MiB | 3.58 MiB/s, done.
Resolving deltas: 100% (101/101), done.
==> Checking out branch master
==> Downloading https://sqlite.org/src/vpatch?from=0db20efe201736b3&to=66de6f4a9504ec26
Already downloaded: /Users/jc/Library/Caches/Homebrew/sqlcipher--patch-41d0570cbf80429e556e612acd5eeddcff0e586264a6bcb80bd5a27abc9159a2
==> Patching
==> Applying vpatch
patching file ext/rtree/rtree.c
Hunk #1 succeeded at 3207 (offset -228 lines).
patching file ext/rtree/rtreeA.test
==> ./configure --prefix=/usr/local/Cellar/sqlcipher/HEAD-df092f0_1 --enable-tempstore=yes --with-crypto-lib=/usr/local/opt/openssl --enable-load-extension --disable-tcl CFLAGS
==> make
==> make install
🍺  /usr/local/Cellar/sqlcipher/HEAD-df092f0_1: 12 files, 2.5MB, built in 1 minute 9 seconds
```

It'll obviously break when the SQLCipher repo rebases onto SQLite 3.20.x, as the patch is already in SQLite, but it'll be an easy fix when that happens. :smile:

2017-08-19 14:58 UTC, JCount approved these changes

2017-08-19 15:01 UTC, closed without merging

2017-08-19 15:01 UTC, JCount commented
Thank you for your contribution to Homebrew, @justinclift!! 😄

2017-08-19 15:26 UTC, justinclift commented
No worries. :smile: