qshell 2.1.3 (new formula)
Homebrew/homebrew-core pull request #17086
Opened 2017-08-22 05:08 UTC by jemygraw

2017-08-22 08:38 UTC, bfontaine requested changes

2017-08-22 08:38 UTC, bfontaine commented on Formula/qshell.rb
> +    system "qshell" "help"
You missed a comma between `"qshell"` and `"help"`. Also, use `bin/"qshell"` instead.

2017-08-22 08:38 UTC, bfontaine commented on Formula/qshell.rb
> +  desc "Qiniu Cloud Resource Management Tool "
Trailing space here.

2017-08-22 08:38 UTC, bfontaine commented on Formula/qshell.rb
> +  url "https://dn-devtools.qbox.me/qshell-2.1.3.tar.gz"
We need to build from source here.

2017-08-22 08:38 UTC, bfontaine commented on Formula/qshell.rb
> +    system "make", "install"
There’s no Makefile there.

2017-08-22 13:53 UTC, fxcoudert commented
**[Homebrew formulas must build from source](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md)**

2017-08-22 13:53 UTC, closed without merging

2017-08-23 06:32 UTC, jemygraw commented on Formula/qshell.rb
> +  url "https://dn-devtools.qbox.me/qshell-2.1.3.tar.gz"
if i want to publish a binary executable file, is there any docs i can refer to? many thanks

2017-08-23 08:49 UTC, bfontaine commented on Formula/qshell.rb
> +  url "https://dn-devtools.qbox.me/qshell-2.1.3.tar.gz"
The [same docs](https://docs.brew.sh/Formula-Cookbook.html) as other formulae work here too, but you’ll have to host the formula in [your own tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html) as Homebrew disallow pre-built binaries in the official taps.

In your case the only thing you need to change (beside the syntax issue in the `test do` block) is the `install` method:

```ruby
def install
  bin.install "qshell"
end
```