kconf 2.0.0
Homebrew/homebrew-core pull request #170850
Opened 2024-05-05 04:33 UTC by particledecay

Adding the formula for the [kconf](https://github.com/particledecay/kconf) tool, for managing multiple Kubernetes files. This is my first Homebrew formula and [someone requested this be in Homebrew](https://github.com/particledecay/kconf/issues/50), so I'm happy to make any changes if I got this wrong.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2024-05-05 04:49 UTC, p-linnane requested changes
Thanks for the PR @particledecay. We normally do not allow self-submissions from software authors, but I'm willing to make an exception here since I can see the value of distributing `kconf`.

I've provided a few suggestions to align this with our usual syntax and standards. Please let me know if you have any concerns.

2024-05-05 04:49 UTC, p-linnane commented on Formula/k/kconf.rb
> +  desc "Manage multiple kubeconfigs easily"
```suggestion
  desc "CLI for managing multiple kubeconfigs"
```

2024-05-05 04:49 UTC, p-linnane commented on Formula/k/kconf.rb
> +
```suggestion
head "https://github.com/particledecay/kconf.git", branch: "main"

```

2024-05-05 04:49 UTC, p-linnane commented on Formula/k/kconf.rb
> +    system "go", "build", "-ldflags", "-s -w -X github.com/particledecay/kconf/build.Version=#{version} -X github.com/particledecay/kconf/build.Commit=b1261a8-homebrew -X github.com/particledecay/kco
```suggestion
    ldflags = %W[
      -s -w
      -X github.com/particledecay/kconf/build.Version=#{version}
      -X github.com/particledecay/kconf/build.Commit=Homebrew
      -X github.com/particledecay/kconf/build.Date=#{time.iso8601}"
    ]

    system "go", "build", *std_go_args(ldflags:)

    generate_completions_from_executable(bin/"kconf", "completion")
```

2024-05-05 04:49 UTC, p-linnane commented on Formula/k/kconf.rb
> +    assert_match(/SHA:.*homebrew$/, shell_output("#{bin}/kconf -v version"))
```suggestion
    assert_match version.to_s, shell_output(bin/"kconf version")

    output = shell_output(bin/"kconf namespace homebrew 2>&1", 1)
    expected = "you must first set a current context before setting a preferred namespace"
    assert_match expected, output
```

2024-05-06 03:27 UTC, p-linnane approved these changes

2024-05-06 04:10 UTC, chenrui333 approved these changes

2024-05-06 04:10 UTC, chenrui333 commented
@particledecay, thanks for your first contribution to homebrew-core!!! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

2024-05-06 04:17 UTC, merged