ISSUE_TEMPLATE: firm up language
Homebrew/homebrew-core pull request #17152
Opened 2017-08-23 17:01 UTC by MikeMcQuaid

Try to be even clearer that we need you to read this.

2017-08-23 17:21 UTC, WesWedding requested changes
"If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again."

This particular sentence has an issue:
 "If you do not read fill out" seems like a typo.  Maybe it was supposed be "If you do not fill out"? Or "if you do not read/fill out"

Alternate wording might be "Repeated failure to use the issue template will result in a block from the Homebrew issue queue."  Sounds almost like legalese and extra scary!

2017-08-23 17:57 UTC, chdiza commented on .github/ISSUE_TEMPLATE.md
> +
"ever submitting"

2017-08-24 02:55 UTC, DomT4 commented
Please note this is not disagreement with this PR, because lord I have not forgotten how frustrating handling issues with almost zero basic information was, but I think it will always be the case that people retain that behaviour even if Homebrew suggests it might chuck them into the ocean without a lifejacket for doing so. I hope this decreases the prevalence but I fear otherwise 😭.

2017-08-24 09:51 UTC, vszakats commented on .github/ISSUE_TEMPLATE.md
> +To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Issues created requesting a new/updated formulae will be closed
"To get a new formula into" -> ~"To get formula changes into"

2017-08-24 10:48 UTC, MikeMcQuaid commented
> Please note this is not disagreement with this PR, because lord I have not forgotten how frustrating handling issues with almost zero basic information was, but I think it will always be the case that people retain that behaviour even if Homebrew suggests it might chuck them into the ocean without a lifejacket for doing so.

Yup, I agree. Going beyond this, though, requires GitHub to do stuff (and this is something I'm advocating for internally).

2017-08-24 10:48 UTC, merged

2017-08-24 10:48 UTC, MikeMcQuaid commented
Thanks for the review everyone 🎉