Explicity allow the use of CMake FetchContent in Solidity formula
Homebrew/homebrew-core pull request #172338
Opened 2024-05-21 16:26 UTC by r0qs

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Since https://github.com/Homebrew/brew/pull/17075, CMake `FetchContent` is disabled by default . This made our formula to crash: https://github.com/Homebrew/homebrew-core/actions/runs/9175554982/job/25228895627?pr=172324. 

This PR fix that by explicitly enabling it back.

See: https://github.com/Homebrew/brew/issues/17187#issuecomment-2118903462 for context.

2024-05-21 16:29 UTC, SMillerDev commented
What does it need to download?

2024-05-21 16:31 UTC, r0qs commented
> What does it need to download?

Build dependencies like: `fmtlib` (https://github.com/ethereum/solidity/blob/8a97fa7a1db1ec509221ead6fea6802c684ee887/CMakeLists.txt#L53)

2024-05-21 16:34 UTC, carlocab commented
This should use Homebrew `fmt`. https://docs.brew.sh/Acceptable-Formulae#stuff-that-requires-vendored-versions-of-homebrew-formulae

2024-05-21 16:38 UTC, SMillerDev requested changes
It seems this is breaking for the exact reason we introduced this change. Upstream is vendoring formulae. Please adjust the formula to use the Homebrew versions.

2024-05-22 07:11 UTC, SMillerDev commented
> The mechanism to skip or not system libraries was only added in the recent Solidity release (i.e. 0.8.26, as you can see here: https://github.com/ethereum/solidity/commit/b60ed2b96a6b00b2d23a2dd9caf98173527fc38f). However the PR that bump the formula version is failing because of the fetch content restriction: https://github.com/Homebrew/homebrew-core/pull/172324).

Why not just make a PR that bumps the version and uses the Homebrew dependencies in the process?

2024-05-22 11:21 UTC, r0qs commented
> > The mechanism to skip or not system libraries was only added in the recent Solidity release (i.e. 0.8.26, as you can see here: [ethereum/solidity@b60ed2b](https://github.com/ethereum/solidity/commit/b60ed2b96a6b00b2d23a2dd9caf98173527fc38f)). However the PR that bump the formula version is failing because of the fetch content restriction: #172324).
> 
> Why not just make a PR that bumps the version and uses the Homebrew dependencies in the process?

Sure, we can try to do that in https://github.com/Homebrew/homebrew-core/pull/172324, so I will be closing this PR.

Does homebrew allow us to use specific versions of those dependencies? Sorry to ask that, but I'm no a macOS user and I don't use homebrew other than in our CI, so I'm not sure if I can specify a formula version with the `depends_on`, can I?

I'm asking this because we depends on specific version of those dependencies, for instance:
 - fmtlib version `9.1.0`
 - nlohmann-json version `3.11.3`
 - range-v3 version `0.12.0`

2024-05-22 11:21 UTC, closed without merging

2024-05-22 14:39 UTC, SMillerDev commented
No, the reasoning why that is unsupported is included in the docs for it: https://docs.brew.sh/Acceptable-Formulae#stuff-that-requires-vendored-versions-of-homebrew-formulae

2024-05-23 13:39 UTC, matheusaaguiar commented
Isn't that too restrictive? I mean, sometimes it is difficult and time consuming to update every dependency every time there is a new version. Sometimes, there is third-party functionality that was deprecated and cannot be readily replaced/re-worked. Other times, we just want to use more stable/audited software and that means fixing a specific version.
Why not implement what was suggested here by CMake maintainer?
Also, from the docs, `Increasingly, though: this can be (too) hard. Homebrew’s primary mission is to be useful rather than ideologically pure. If we cannot package something without using vendored upstream versions: so be it; better to have packaged software in Homebrew than not.`

Don't get me wrong, not trying to be confrontational, just raising some questions/arguments.
Thanks.

2024-05-24 16:09 UTC, carlocab commented
> Why not implement what was suggested [here](https://github.com/Homebrew/brew/pull/17075#issuecomment-2087634394) by CMake maintainer? 

We have implemented it. See:

https://github.com/Homebrew/brew/pull/17075#issuecomment-2095662455
https://github.com/Homebrew/brew/pull/17310

2024-05-24 21:11 UTC, matheusaaguiar commented
> We have implemented it. See:
> 
> [Homebrew/brew#17075 (comment)](https://github.com/Homebrew/brew/pull/17075#issuecomment-2095662455) [Homebrew/brew#17310](https://github.com/Homebrew/brew/pull/17310)

Ah, my bad, I didn't see that one.