marathon 1.0.1 (new formula)
Homebrew/homebrew-core pull request #17266
Opened 2017-08-26 15:06 UTC by orta

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Adds Marathon: https://github.com/JohnSundell/Marathon

2017-08-26 17:09 UTC, orta commented
Ah dang, I thought that linter error was just me setting up my local dev env wrong. Interesting, will discuss  with the maintainers about naming.

2017-08-26 21:09 UTC, orta commented
Awesome, we're green 👍

2017-08-27 10:05 UTC, ilovezfs requested changes

2017-08-27 10:05 UTC, ilovezfs commented on Formula/marathon-swift.rb
> +    ENV["SDKROOT"] = MacOS.sdk_path
This is set automatically.

2017-08-27 10:05 UTC, ilovezfs commented on Formula/marathon-swift.rb
> +  desc "Makes it easy to write, run and manage your Swift scripts 🏃"
Let's leave out the emoji

2017-08-27 10:05 UTC, ilovezfs commented on Formula/marathon-swift.rb
> +    bin.install ".build/release/marathon"
Please request a `make install` upstream.

2017-08-27 10:05 UTC, ilovezfs commented on Formula/marathon-swift.rb
> +    system "#{bin}/marathon", "help"
This needs to be a test that exercises and verifies the functionality of the software once installed.

2017-08-27 23:57 UTC, orta commented
@ilovezfs - do you know if there's anything unique about the Sierra and using the `install` command? I've  tried building out a make command for installing the app that calls:

```sh
PREFIX?=/usr/local
INSTALL_NAME = marathon

# [...]

install_bin:
	mkdir -p $(PREFIX)/bin
	mv .build/Release/Marathon .build/Release/$(INSTALL_NAME)
	/usr/bin/install -s -m 0755 .build/Release/$(INSTALL_NAME) $(PREFIX)/bin
```

But it only fails on Sierra, and when I tried using `cp` it was the same story. This is my first time making cask / using Makefiles for system setup, so am I missing something simple?

2017-08-29 12:11 UTC, orta commented
@ilovezfs this is now green 👍

2017-08-30 19:43 UTC, orta commented
Polite Poke

2017-08-31 10:46 UTC, ilovezfs approved these changes

2017-08-31 13:23 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew @orta! Without people like you submitting PRs we couldn't run this project. You rock!

2017-08-31 13:23 UTC, closed without merging

2017-08-31 13:46 UTC, orta commented
No - you rock - thanks!

2017-08-31 14:08 UTC, JohnSundell commented
@orta @ilovezfs you both rock 🎸 Thanks a lot for this!