cortexso 0.5.0-37
Homebrew/homebrew-core pull request #180461
Opened 2024-08-08 06:16 UTC by hiento09

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2024-08-14 04:03 UTC, branchvincent requested changes
Thanks for the PR! A few comments

2024-08-14 04:12 UTC, branchvincent commented on Formula/c/cortexso.rb
> +  depends_on "yarn"
```suggestion
  depends_on "yarn" => :build
```

2024-08-15 02:54 UTC, hiento09 commented on Formula/c/cortexso.rb
> +    depends_on xcode: :build
Hi, on my machine, if I remove Xcode, the build fails, but if I include Xcode, the build succeeds.
Command: `brew install --build-from-source ./Formula/c/cortexso.rb --verbose`

2024-08-15 02:55 UTC, hiento09 commented on Formula/c/cortexso.rb
> +    # Remove build dependencies
Got you, I am handling it in our `package.json` now, thank you for your suggestion.

2024-08-15 02:57 UTC, branchvincent commented on Formula/c/cortexso.rb
> +    depends_on xcode: :build
What's the error that you see? We can try removing it and CI will let us know

2024-08-15 03:03 UTC, hiento09 commented on Formula/c/cortexso.rb
> +    depends_on xcode: :build
Ok, let me try to remove and run it on CI now

2024-08-15 03:15 UTC, hiento09 commented on Formula/c/cortexso.rb
> +    depends_on xcode: :build
https://github.com/Homebrew/homebrew-core/actions/runs/10398092233/job/28794944122?pr=180461 you can check the error here @branchvincent , I got similar error locally

2024-08-15 06:57 UTC, closed without merging

2024-08-15 07:10 UTC, hiento09 commented on Formula/c/cortexso.rb
> +    # Remove build dependencies
Hey @branchvincent.
Sorry for the inconvenience, I have bumped the version of our package to resolve this issue and renamed the branch while creating a new PR. Please review the new PR here https://github.com/Homebrew/homebrew-core/pull/181250

2024-08-17 14:00 UTC, chenrui333 commented
```
  npm info run cortex-cpp@0.5.0-36 install { code: 1, signal: null }
  npm verbose stack Error: command failed
  npm verbose stack     at promiseSpawn (/opt/homebrew/Cellar/node/22.6.0/libexec/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
  npm verbose stack     at spawnWithShell (/opt/homebrew/Cellar/node/22.6.0/libexec/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
  npm verbose stack     at promiseSpawn (/opt/homebrew/Cellar/node/22.6.0/libexec/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
  npm verbose stack     at runScriptPkg (/opt/homebrew/Cellar/node/22.6.0/libexec/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
  npm verbose stack     at runScript (/opt/homebrew/Cellar/node/22.6.0/libexec/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
  npm verbose stack     at /opt/homebrew/Cellar/node/22.6.0/libexec/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
  npm verbose stack     at run (/opt/homebrew/Cellar/node/22.6.0/libexec/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
  npm verbose stack     at /opt/homebrew/Cellar/node/22.6.0/libexec/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
  npm verbose stack     at new Promise (<anonymous>)
  npm verbose stack     at callLimit (/opt/homebrew/Cellar/node/22.6.0/libexec/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
  npm verbose pkgid cortex-cpp@0.5.0-36
  npm error code 1
  npm error path /opt/homebrew/Cellar/cortexso/0.5.0-37/libexec/lib/node_modules/cortexso/node_modules/cortex-cpp
  npm error command failed
  npm error command sh -c prebuild-install --runtime napi --backend cmake-js --config Release || yarn rebuild
```