raxml: import from homebrew/science
Homebrew/homebrew-core pull request #18522
Opened 2017-09-25 08:37 UTC by jonchang

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/Homebrew/homebrew-science/pull/6346

* removed Linux-specific mpi builds
* made the test smaller (but still effective)
* removed fortran dependency hack introduced in https://github.com/Homebrew/homebrew-science/pull/3896 since we aren't importing gubbins
* removed `revision 1` line to pass audit

2017-09-25 09:31 UTC, ilovezfs requested changes
This will need a proper

```
./configure --prefix=#{prefix}
make install
```
installation procedure and should not need to rely on the `Hardware::CPU` DSL or `bin.install`, let alone need to clean preexisting object files.

2017-09-27 09:49 UTC, ilovezfs commented
@BrewTestBot test this please

2017-09-27 19:48 UTC, jonchang commented
Ok, how about a compromise, where we unconditionally build just the SSE3 version. This avoids using `Hardware::CPU` and cleaning object files and permits maximum compatibility, as all Macs that can run El Capitan support SSE3 instructions, according to [this page](https://support.apple.com/kb/sp728?locale=en_US) and [this page](https://en.wikipedia.org/wiki/List_of_Macintosh_models_grouped_by_CPU_type#Core). Any users who want AVX+ instructions will have to build it themselves (but they're likely to have done so already anyway).

2017-09-27 22:57 UTC, ilovezfs commented
We have to build from source, so the object files should not be there to begin with. The prospects for including this do not look good.

2017-09-27 23:27 UTC, jonchang commented
It is built from source, and the object files are only created by the Makefile. 

Sent from my iPhone

> On Sep 27, 2017, at 3:57 PM, ilovezfs <notifications@github.com> wrote:
> 
> We have to build from source, so the object files should not be there to begin with. The prospects for including this do not look good.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-09-27 23:31 UTC, ilovezfs commented
Ah, OK. We still need a `make install` target here, and it should abide by the bottle hardware setting which is core2.

2017-09-28 01:42 UTC, jonchang commented
Respectfully, I disagree, as a significant fraction of formulae in homebrew/core use `bin.install`:

```
 $ cd `brew --repo homebrew/core`/Formula
 $ rg bin.install -l | wc -l
    1098
 $ find . | wc -l
    4367
```

The makefile doesn't set the `march` flag so I think we'll be in the clear on that front.

2017-09-28 02:11 UTC, ilovezfs commented
@jonchang this is the same standard we apply to all new formulae. We can close this out if you'd like to host it elsewhere.

2017-10-07 05:41 UTC, ilovezfs requested changes
What's the status on getting a `make install` here?

2017-10-09 23:27 UTC, jonchang commented
I'll talk to upstream about it.

2017-10-31 19:10 UTC, ilovezfs commented
@stale take a :snowflake: :pill:, buddy.

2017-11-11 15:52 UTC, ilovezfs commented on Formula/raxml.rb
> +  def make_clean(makefile)
formulae should avoid using functions

2017-11-23 14:56 UTC, ilovezfs commented
Feel free to re-open when this is using `make install` and not using functions. Thanks, @jonchang

2017-11-23 14:56 UTC, closed without merging