Apply libgda patches to work with XCode 9
Homebrew/homebrew-core pull request #18628
Opened 2017-09-27 15:48 UTC by bai

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes libgda builds on XCode 9 / High Sierra

TODO: Update patch URLs when https://github.com/Homebrew/formula-patches/pull/191 is merged.

2017-09-27 16:38 UTC, ilovezfs requested changes
What is the status of these patches upstream? I'd like to see a new release instead of this.

2017-09-27 16:40 UTC, bai commented
Latest libgda released in June 2015 per https://github.com/GNOME/libgda/releases

FWIW debian maintainers also decided to apply patches instead of making an upstream release.

2017-09-27 16:42 UTC, ilovezfs commented
Debian is not relevant. What is the status of the patches in the libgda project and why is there no new release from them? Are they merged in the libgda source tree?

CC @tschoonj

2017-09-28 10:18 UTC, tschoonj commented
The first two patches appear to be coming from the official repo. The last patch seems to be new on the other hand. Does libgda compile without it?

2017-09-28 10:20 UTC, bai commented
@tschoonj Unfortunately it does not compile without last patch due to changed mysql headers location.

2017-09-29 11:26 UTC, fxcoudert commented
Hi @bai, many thanks for your contribution. I've merged the two "upstream" patches together and committed them, since I had them already committed to `formula-patches` in a separate PR. I apologize for not having seen yours first.

At least on our CI machines, that gets libgda compiling again.

Regarding the mysql patch, can you clarify a bit: what is its role / what issue does it fix (given that libgda compiles against sqlite, not mysql, as far as I can see)? what is it status (has it been reported upstream, accepted, committed?)

2017-09-30 15:08 UTC, bai commented
@fxcoudert Please feel free to ignore last patch. I double-checked and it turns out you need it only when you use libgda's mysql provider (autodetected when you have mysql installed).

I'm going to update this PR with new patch URLs and will remove MySQL patch as well.

2017-10-01 17:29 UTC, fxcoudert commented
Thanks again @bai. Closing this pull request, as patches have been merged in and the formula now builds on 10.13 (and includes a bottle on that OS version).

2017-10-01 17:29 UTC, closed without merging