netcdf: add option --with-static
Homebrew/homebrew-core pull request #18854
Opened 2017-10-02 16:50 UTC by jeroen

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
-----

Adds an option to produce static library of netcdf instead of a dynamic library. We really need this to build our application. No side effects on standard installation. Thank you for considering.

2017-10-02 19:21 UTC, DomT4 commented on Formula/netcdf.rb
> -    common_args = std_cmake_args << "-DBUILD_SHARED_LIBS=ON"
```ruby
common_args = std_cmake_args

if build.with? "static"
  common_args << "-DBUILD_SHARED_LIBS=OFF"
else
  common_args << "-DBUILD_SHARED_LIBS=ON"
end
```

2017-10-02 19:21 UTC, DomT4 commented on Formula/netcdf.rb
> +    if build.without? "static"
Non-default options don't get tested, so this is a bit pointless IMO.

2017-10-02 21:15 UTC, jeroen commented
@DomT4 Thank you. I have removed the redundant condition from the test now.

2017-10-02 21:17 UTC, ilovezfs commented
Rather than an option. Let's just build both. See `snappy`.

2017-10-02 21:18 UTC, ilovezfs requested changes
both please

2017-10-03 12:42 UTC, jeroen commented
OK it took some work I finally got this to work. 

For whatever reason we cannot just call `make install` twice because running `make install` on this lib will invoke `make uninstall` first. Therefore on the second run we manually install the static file.

2017-10-07 06:02 UTC, ilovezfs requested changes
>For some reason we cannot just call make install twice because running the second make install will uninstall the first one. Therefore we just manually lib.install the static libs.

This needs to be reported upstream

2017-10-07 12:06 UTC, jeroen commented
ok

2017-10-12 08:29 UTC, jeroen commented
This works fine as is. I don't think upstream intends on changing this behavior.

2017-10-12 08:39 UTC, ilovezfs commented
Did you report it?

2017-10-12 08:41 UTC, jeroen commented
https://github.com/Unidata/netcdf-c/issues/496

2017-10-12 08:49 UTC, ilovezfs commented
@jeroen yeah it would be cool if they can support doing both at once in a single `make install`, but, at minimum, if they are going to require us to call `make install` twice, the second `make install` shouldn't wipe out the libraries from the first `make install`.

2017-10-12 09:07 UTC, jeroen commented
Right, I will address this to upstream as well so that they can have a look at it the next time they are revising the cmake configuration. 

However it may be a while until they have a chance to look at this, and then more time until the next release. Is there any chance we can move forward with this PR in the mean time? The current code seems like the obvious solution to add static libs to the build?

2017-10-12 09:09 UTC, ilovezfs approved these changes

2017-10-12 09:10 UTC, ilovezfs commented
@BrewTestBot test this please

2017-10-12 09:44 UTC, jeroen commented
thanks!

2017-10-16 21:14 UTC, jeroen commented
Merge? 🚀

2017-10-17 19:31 UTC, ilovezfs approved these changes

2017-10-17 19:57 UTC, ilovezfs commented
Thanks again @jeroen! :white_check_mark:

2017-10-17 19:58 UTC, closed without merging