pldebugger 1.0
Homebrew/homebrew-core pull request #19114
Opened 2017-10-06 16:06 UTC by felixbuenemann

Bump pldebugger to the v1.0 tag, which points to the revision "ca1041dc3db6f516899be669dc6fbfd6339f8168" and is required for
compatibility with postgres 10.0.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-10-06 16:07 UTC, felixbuenemann commented
This is a related to the postgres 10.0 PR #19062.

2017-10-07 06:30 UTC, ilovezfs commented
@BrewTestBot test this please

2017-10-07 09:06 UTC, ilovezfs requested changes
>Bump pldebugger to the v1.0 tag

We should use `:tag =>` + `:revision =>` in the url

2017-10-07 11:56 UTC, felixbuenemann commented
@ilovezfs But a tag is not immutable, and git sources do not have a sha256 checksum, so how do you ensure integrity in that case?

2017-10-07 11:57 UTC, ilovezfs commented
>a tag is not immutable

Are they known to retag?

2017-10-07 11:58 UTC, ilovezfs commented
To be clear, we need something like this: https://github.com/Homebrew/homebrew-core/blob/master/Formula/osquery.rb#L5-L7

2017-10-07 11:58 UTC, felixbuenemann commented
No, but I thought the reason for using ˋ:revisionˋ was integrity. I have no problems with switching to a tag ifvthat is notbthe goal.

2017-10-07 12:00 UTC, felixbuenemann commented
Ah, using both tag and revision is fine.

2017-10-07 13:12 UTC, felixbuenemann commented
@ilovezfs I've added `:tag` and removed the now redundant `version "1.0"` in 80e0816.

2017-10-07 15:41 UTC, ilovezfs approved these changes

2017-10-07 15:42 UTC, closed without merging

2017-10-07 15:42 UTC, ilovezfs commented
Thanks @felixbuenemann!