postgresql-latest 17 (new formula)
Homebrew/homebrew-core pull request #192392
Opened 2024-09-30 17:33 UTC by cho-m

Concept idea. Also was originally writing symlinks and now trying out a `PG_VERSION` environment variable kind of like how java tools use `JAVA_HOME`.

---

We had some requests to automatically provide binaries on PATH; however, there are problems for users who may not be familiar with the behavior of PostgreSQL data migrations.

This meta formula provides the symlinks for advanced users who are aware of limitations and want to track latest PostgreSQL.

2024-09-30 18:28 UTC, cho-m commented on Formula/p/postgresql-latest.rb
> +  url "https://ftp.postgresql.org/pub/source/v17.0/postgresql-17.0.tar.bz2", using: :nounzip
Given this isn't used, can probably reduce download size by using one of the checksum files, e.g.
```suggestion
  url "https://ftp.postgresql.org/pub/source/v17.0/postgresql-17.0.tar.bz2.md5"
```

2024-10-01 09:25 UTC, carlocab approved these changes
Nice idea!

2024-10-01 09:38 UTC, MikeMcQuaid requested changes
Nice idea but: I think we should continue with:
- `brew install postgresql`: always installs the latest version and we should aim to make upgrades smoother
- `brew install postgresql@14` installs a specific version (which may be the latest today but will then "sit" on the older version after we add that formula)

If we want to do something more like this: I think the logic should mostly live in Homebrew/brew and not in individual formulae like this and we shouldn't introduce a new `-latest` paradigm.

Sorry!

2024-10-01 13:06 UTC, closed without merging

2024-10-01 13:31 UTC, MikeMcQuaid commented
I believe doing `brew install` of a versioned, key-only formula will automatically link it if there's no other versions installed.

2024-10-01 13:51 UTC, cho-m commented
> I believe doing `brew install` of a versioned, key-only formula will automatically link it if there's no other versions installed.

It didn't work for me when I tried it. Needed an extra `brew link <versioned-formula>`. Mainly seems to not need `--force`.