vcprompt: fixed the source issue by using tar.gz from the github rele…
Homebrew/homebrew-core pull request #193191
Opened 2024-10-08 10:58 UTC by xakep8

…ase.

this fix is a part of issue #139929.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

this fix is part of issue #139929 and fixes source issue for vcprompt by using a tar.gz from github release

2024-10-08 12:09 UTC, chenrui333 commented on Formula/v/vcprompt.rb
>    end
you can probably remove this

2024-10-08 12:18 UTC, SMillerDev requested changes

2024-10-08 12:18 UTC, SMillerDev commented on Formula/v/vcprompt.rb
> +  sha256 "6fd44d453c59efcfb9e01e6fe3a47573d32a64b81a89c19df7bee84f12a2c5be"
Arch uses https://github.com/powerman/vcprompt for this, and everyone else uses the old URL. How did you get this new source?

2024-10-09 07:59 UTC, SMillerDev approved these changes
Thanks @xakep8  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

2024-10-09 16:52 UTC, p-linnane approved these changes

2024-10-09 16:56 UTC, merged