Add pysphere python module - required for vsphere_guest core ansible …
Homebrew/homebrew-core pull request #19763
Opened 2017-10-23 16:48 UTC by sdhughes1

…module

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
The pysphere python module is required for a few VMware-related bundled ansible modules, including vsphere_guest. This PR adds the pysphere module to the resource list.

2017-10-24 11:03 UTC, ilovezfs requested changes
please note this up here https://github.com/sdhughes1/homebrew-core/blob/ab3431a80952605cc4f2b5a8e8af6baa869cbf0a/Formula/ansible.rb#L22-L39

2017-10-24 15:18 UTC, ilovezfs submitted a review, later dismissed

2017-10-24 15:20 UTC, ilovezfs commented
@sdhughes1 it looks like your GitHub account and the email address in your commits are not associated with each other. That means that the contributor statistics cannot credit your commits to you. It would be great if you could fix that so that those stats are correct and so that you don't appear as a "First-time GitHub contributor" on every PR.

2017-10-26 08:37 UTC, ilovezfs requested changes
It looks like this project is no longer maintained. See https://github.com/argos83/pysphere.

The maintainer of the old project suggests using the official VMware Python bindings instead. Can those be used with Ansible? It looks like they're here: https://github.com/vmware/pyvmomi

2017-10-26 15:17 UTC, sdhughes1 commented
Indeed. Some older, but still maintained, Ansible modules require pysphere, and some newer ones utilize pyvmomi. The newer modules sometimes don't have the full functionality of the old modules, but I expect that to change over time. Once the ansible project stops including those modules within Ansible core, we could remove the pysphere module from the Homebrew package. The python requirements are documented in the latest ansible documentation:

http://docs.ansible.com/ansible/latest/vsphere_guest_module.html (old pysphere module)
http://docs.ansible.com/ansible/latest/vmware_guest_module.html (new pyvmomi module)

Should I modify this PR to also include the pyvmomi module for completeness, or open a new one?

2017-10-27 15:18 UTC, ilovezfs commented
>Should I modify this PR to also include the pyvmomi module for completeness

Sure.

2017-10-27 15:19 UTC, ilovezfs commented
>Should I modify this PR to also include the pyvmomi module for completeness

To be clear, though, is ansible actually using that for anything?

2017-10-27 15:19 UTC, ilovezfs approved these changes

2017-10-27 15:20 UTC, ilovezfs commented
@BrewTestBot test this please

2017-10-27 16:11 UTC, sdhughes1 commented
Yes, there are a few ansible modules in the active code train that require pysphere.

https://github.com/ansible/ansible/blob/be821845e206a8dd0a6a7f7a814e70f5edd3b039/lib/ansible/modules/cloud/vmware/vsphere_guest.py#L305

2017-10-27 16:46 UTC, closed without merging

2017-10-27 16:46 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @sdhughes1! Without people like you submitting PRs we couldn't run this project. You rock!