coccinelle: add a test
Homebrew/homebrew-core pull request #19772
Opened 2017-10-24 02:53 UTC by Moisan

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Add a test to coccinelle. Related to #11898.

2017-10-24 11:33 UTC, ilovezfs requested changes

2017-10-24 11:33 UTC, ilovezfs commented on Formula/coccinelle.rb
> +    share.install ["demos/simple.cocci", "demos/simple.c"]
should use pkgshare

2017-10-24 11:33 UTC, ilovezfs commented on Formula/coccinelle.rb
> +  revision 2
this is a small enough change not to warrant a revision bump because the existing installations aren't actually broken

2017-10-24 15:01 UTC, ilovezfs commented on Formula/coccinelle.rb
> +    system "#{bin}/spatch", "-sp_file", "#{pkgshare}/simple.cocci", "#{pkgshare}/simple.c", "-o", "new_simple.c"
Please wrap split this into two lines so it doesn't go passed the eightieth column like this:
```
    system "#{bin}/spatch", "-sp_file", "#{pkgshare}/simple.cocci",
                            "#{pkgshare}/simple.c", "-o", "new_simple.c"
```

2017-10-24 15:02 UTC, ilovezfs commented on Formula/coccinelle.rb
> +    pkgshare.install ["demos/simple.cocci", "demos/simple.c"]
you don't need the array

2017-10-24 16:00 UTC, ilovezfs commented on Formula/coccinelle.rb
> +    correct_output = <<~EOS
use `expected` instead of `correct_output`

2017-10-24 16:00 UTC, ilovezfs commented on Formula/coccinelle.rb
> +    assert_equal correct_output, File.read(testpath/"new_simple.c")
Use `(testpath/"new_simple.c").read`

2017-10-24 16:01 UTC, ilovezfs commented
@Moisan a couple more nits noted above, and then could you please squash this down to one commit? Thanks!

2017-10-24 16:01 UTC, ilovezfs approved these changes

2017-10-25 01:59 UTC, woodruffw commented
Thanks @Moisan!

2017-10-25 01:59 UTC, closed without merging