shibboleth-idp 3.3.2 (new formula)
Homebrew/homebrew-core pull request #20120
Opened 2017-10-31 20:51 UTC by rkhmelichek

New formula for the Shibboleth Identity Provider (IDP).

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-11-01 03:38 UTC, woodruffw requested changes

2017-11-01 03:38 UTC, woodruffw commented on Formula/shibboleth-idp.rb
> +  test do
We require new formulae in homebrew-core to have a more substantive test than just `version` or `help`.

2017-11-01 03:38 UTC, woodruffw commented on Formula/shibboleth-idp.rb
> +    # Remove Windows scripts
You can delete this comment and the comment below; the lines are pretty self-explanatory.

2017-11-01 03:38 UTC, woodruffw commented on Formula/shibboleth-idp.rb
> +    libexec.install Dir["*"]
I'm not that familiar with shibboleth, but does it expect everything to be installed in `libexec`? Are there executables that should also be installed/linked to `bin`, for example?

2017-11-01 03:38 UTC, woodruffw commented
Thanks for the formula @rkhmelichek! I've left some review notes above.

2017-11-05 17:38 UTC, rkhmelichek commented
Thanks for reviewing @woodruffw - I removed the comments.

The Shibboleth IDP package is meant to be used to build a war file that can then be deployed into a Tomcat or Jetty server.

Typical usage would be something like this:
```bash
export JAVA_HOME=$(/usr/libexec/java_home)
/usr/local/opt/shibboleth-idp/libexec/bin/build.sh -Didp.target.dir=/usr/local/opt/shibboleth-idp/libexec
```

And the resulting war file will be here:
`/usr/local/opt/shibboleth-idp/libexec/war/idp.war`

I tried to make that into a test, but unfortunately, the ant script that builds the war writes a log file into the Cellar `/usr/local/Cellar/shibboleth-idp/3.3.2/libexec/idp_ant.log`. And the brew test harness complains that the Cellar is read only. It wasn't possible to change the location of the log file or stop the logging without changing the ant script.

Let me know if you have suggestions on how to make this work.

2017-11-07 00:25 UTC, DomT4 commented on Formula/shibboleth-idp.rb
> +    ENV["JAVA_HOME"] = `/usr/libexec/java_home`.chomp
You should be writing a wrapper script so this isn't necessary. Search `write_jar_script` for examples.

2017-11-09 15:42 UTC, ilovezfs commented
@BrewTestBot test this please

2017-11-10 00:28 UTC, ilovezfs commented
@BrewTestBot test this please

2017-12-01 18:26 UTC, ilovezfs commented
What's the status here @rkhmelichek?

2017-12-01 18:26 UTC, ilovezfs commented
@BrewTestBot test this please

2017-12-14 11:32 UTC, ilovezfs commented
Please feel free to reopen when the feedback has been addressed. Thanks for the PR @rkhmelichek!

2017-12-14 11:32 UTC, closed without merging