New Formula: Clingo
Homebrew/homebrew-core pull request #20185
Opened 2017-11-02 18:58 UTC by domoritz

Formula written by @dariusf. This formula can replace the existing gringo formula (which should be deprecated).

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-11-02 19:17 UTC, domoritz commented
I coulnd't find how to deprecate a formula.

2017-11-03 08:14 UTC, MikeMcQuaid requested changes

2017-11-03 08:14 UTC, MikeMcQuaid commented on Formula/clingo.rb
> +  url "https://github.com/potassco/clingo/releases/download/v5.2.1/clingo-5.2.1-macos-10.9.tar.gz"
This doesn't look like it is built from source. Is it?

2017-11-03 08:14 UTC, MikeMcQuaid commented on Formula/clingo.rb
> +    assert_match version.to_s, shell_output("#{bin}/clingo --version | head -n 1 | cut -d ' ' -f 3")
Remove the ` | head -n 1 | cut -d ' ' -f 3"` and `assert_match` will still match.

2017-11-03 08:33 UTC, ilovezfs commented
Please feel free to reopen when you have it building from source.

2017-11-03 08:33 UTC, closed without merging

2017-11-03 13:40 UTC, domoritz commented
> Please feel free to reopen when you have it building from source.

Thanks for the feedback. I wasn't sure whether that's a strict requirement. I'll also delete the gringo formula in the same pr as suggested.

2017-11-03 13:41 UTC, ilovezfs commented
@domoritz you're welcome :)

2017-11-04 22:07 UTC, domoritz commented
New PR is ar https://github.com/Homebrew/homebrew-core/pull/20281.