pinboard-notes-backup 1.0.3 (new formula)
Homebrew/homebrew-core pull request #20307
Opened 2017-11-05 20:17 UTC by bdesham

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2017-11-09 14:22 UTC, ilovezfs commented
@BrewTestBot test this please

2017-11-10 00:22 UTC, ilovezfs commented
@BrewTestBot test this please

2017-11-14 06:37 UTC, bdesham commented
The build succeeded the second time! 🙂

2017-12-01 18:34 UTC, ilovezfs commented on Formula/pinboard-notes-backup.rb
> +  # A real test would require hard-coding a Pinboard API key here, which would
You can assert an expected failure of some kind instead, or mock the server (see faas-cli)

2017-12-01 18:34 UTC, ilovezfs requested changes
The test needs to exercise and verify the functionality of the software.

2017-12-01 21:18 UTC, bdesham commented
I don’t think it’s possible to mock the server, since the hostname is hardcoded into the executable. I changed the test to make sure that the program exits with the correct code if the command-line arguments are invalid.

2017-12-13 18:42 UTC, bdesham commented
It doesn’t seem to be super clear in GitHub’s interface but I have pushed an updated version (and it has passed the CI checks).

2017-12-14 13:04 UTC, ilovezfs approved these changes

2017-12-14 14:59 UTC, closed without merging

2017-12-14 14:59 UTC, fxcoudert commented
Congratulations @bdesham  on your first contribution to Homebrew! We look forward to seeing you again, for example with updates to this formula, or with suggestions on others :)