Survex 1.2.32 (new formula)
Homebrew/homebrew-core pull request #20395
Opened 2017-11-08 03:54 UTC by RobDeBagel

- [] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-11-09 06:41 UTC, ilovezfs commented
@BrewTestBot test this please

2017-11-09 14:18 UTC, ilovezfs commented
@BrewTestBot test this please

2017-11-09 22:41 UTC, RobDeBagel commented
@ilovezfs the error for El Capitan is:
'/var/folders/kw/j7f63hdn1lj39702nh90xm9w0000gp/T/jenkins187866456339062361.sh: line 3: brew: command not found' 

Am I missing something or is this a problem with the test itself?

2017-11-10 00:22 UTC, ilovezfs commented
@BrewTestBot test this please

2017-12-02 09:13 UTC, RobDeBagel commented
Hi, Is there something else I need to do here. Should I assume lack of action is a rejection of this pull request?

2017-12-02 14:47 UTC, ilovezfs commented
we're just a bit busy.

2017-12-14 14:17 UTC, fxcoudert requested changes
Thanks for contributing the formula… it seems like the software is not really ready for inclusion, so I'd suggest you coordinate with upstream (via bug reports or other ways) to make it simpler to install, then we can include it.

2017-12-14 14:17 UTC, fxcoudert commented on Formula/survex.rb
> +  depends_on "gettext" => :build
Build dep goes first, then others in alphabetical order

2017-12-14 14:17 UTC, fxcoudert commented on Formula/survex.rb
> +    ["src/cavern.c", "src/aven.cc"].each { |f| inreplace f, /pj_set_finder\(msg_proj_finder\)/, "" }
This needs to be fixed in the upstream project. We try to minimise the patching done in Homebrew.

2017-12-14 14:17 UTC, fxcoudert commented on Formula/survex.rb
> +    inreplace "src/message.c", /#ifdef MACOSX_BUNDLE/, "#if 0"
This also needs to be addressed upstream: this should be configurable by command-line option, not patching of source file.

2017-12-14 14:17 UTC, fxcoudert commented on Formula/survex.rb
> +    mkdir_p ["Aven.app/Contents/MacOS", "Aven.app/Contents/Resources"]
Same here: the package should be built from a makefile or a script, but we're not going to populate it ourselves in the formula. This is too fragile, likely to break at any point.

2017-12-14 14:17 UTC, fxcoudert commented on Formula/survex.rb
> +    # Create MacOS resource icons
Same here.

2017-12-14 14:17 UTC, fxcoudert commented on Formula/survex.rb
> +    # Remove unnecessary shared resources
If not needed, why are they created and installed?

2017-12-14 14:17 UTC, fxcoudert commented on Formula/survex.rb
> +    File.open(testpath/"test.pos", "r") { |f| assert_equal f.read, pos }
This is a very nice test! Thanks… not so many people write good tests

2017-12-14 15:55 UTC, fxcoudert commented
Actually, seeing that there is much to change upstream before we can update and accept this formula, I am going to close it for now. But we would very much welcome an update in the future when issues are fixed!

2017-12-14 15:55 UTC, closed without merging