simg2img 1.0.0 (new formula)
Homebrew/homebrew-core pull request #20498
Opened 2017-11-10 10:46 UTC by John-K

This adds a new formula for the simg2img project which provides tools for converting between raw disk images and Android sparse images.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-11-10 17:05 UTC, John-K commented
I think the buildbot had an internal problem, can someone with permissions re-kick this test?

2017-11-10 17:16 UTC, ilovezfs requested changes

2017-11-10 17:16 UTC, ilovezfs commented on Formula/simg2img.rb
> +    bin.install %w[simg2img simg2simg img2simg append2simg]
This will need to use `make install`

2017-11-10 17:16 UTC, ilovezfs commented on Formula/simg2img.rb
> +  sha256 "5e93661135cad56117db5523a3bb0edd73fe9e31802bbfa3b1f165bc89fdb3ef"
```
url "https://github.com/anestisb/android-simg2img.git"
```

2017-11-10 17:17 UTC, John-K commented
Sadly this project has no install target

On Fri, Nov 10, 2017 at 9:16 AM ilovezfs <notifications@github.com> wrote:

> *@ilovezfs* requested changes on this pull request.
> ------------------------------
>
> In Formula/simg2img.rb
> <https://github.com/Homebrew/homebrew-core/pull/20498#discussion_r150291612>
> :
>
> > @@ -0,0 +1,26 @@
> +class Simg2img < Formula
> +  desc "Tool to convert Android sparse images to raw images and back"
> +  homepage "https://github.com/anestisb/android-simg2img"
> +  url "https://github.com/anestisb/android-simg2img/archive/1.0.0.tar.gz"
> +  sha256 "5e93661135cad56117db5523a3bb0edd73fe9e31802bbfa3b1f165bc89fdb3ef"
> +
> +  head do
> +    url "https://github.com/anestisb/android-simg2img"
> +  end
> +
> +  def install
> +    system "make", "sparse"
> +    system "make", "all"
> +    bin.install %w[simg2img simg2simg img2simg append2simg]
>
> This will need to use make install
> ------------------------------
>
> In Formula/simg2img.rb
> <https://github.com/Homebrew/homebrew-core/pull/20498#discussion_r150291660>
> :
>
> > @@ -0,0 +1,26 @@
> +class Simg2img < Formula
> +  desc "Tool to convert Android sparse images to raw images and back"
> +  homepage "https://github.com/anestisb/android-simg2img"
> +  url "https://github.com/anestisb/android-simg2img/archive/1.0.0.tar.gz"
> +  sha256 "5e93661135cad56117db5523a3bb0edd73fe9e31802bbfa3b1f165bc89fdb3ef"
>
> url "https://github.com/anestisb/android-simg2img.git"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-core/pull/20498#pullrequestreview-75825220>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAYpVi-7cuxQ9GONOI_vt_-eo5lssZzhks5s1IUAgaJpZM4QZYYt>
> .
>

2017-11-10 17:18 UTC, ilovezfs commented
You'll need to ask them to add one.

2017-11-10 19:29 UTC, DomT4 commented on Formula/simg2img.rb
> +  head do
Don't need this block. Just `head ""https://github.com/anestisb/android-simg2img.git"` under the `sha256` line above.

2017-11-11 05:41 UTC, John-K commented
Opened https://github.com/anestisb/android-simg2img/pull/11

2017-11-11 06:12 UTC, ilovezfs commented on Formula/simg2img.rb
> +  head "https://github.com/anestisb/android-simg2img"
needs .git at the end. see comment above.

2017-11-11 10:40 UTC, ilovezfs commented
I've opened https://github.com/anestisb/android-simg2img/pull/12 to make the separate `make sparse` step unnecessary :)

2017-11-11 11:01 UTC, ilovezfs commented on Formula/simg2img.rb
> +    assert(File.size?("512k-zeros.img") == 524288, "Could not create 512k-zeros.img with 512KiB of zeros")
```
    assert_equal 524288, (testpath/"512k-zeros.img").size?,
                 "Could not create 512k-zeros.img with 512KiB of zeros"
    system bin/"img2simg", "512k-zeros.img", "512k-zeros.simg"
    assert_equal 44, (testpath/"512k-zeros.simg").size?,
                 "Converting 512KiB of zeros did not result in a 44 byte simg"
    system bin/"simg2img", "512k-zeros.simg", "new-512k-zeros.img"
    assert_equal 524288, (testpath/"new-512k-zeros.img").size?,
                 "Converting a 44 byte simg does not result in 512KiB"
```

2017-11-11 13:31 UTC, ilovezfs commented on Formula/simg2img.rb
> +    system "make", "sparse"
if you update to 1.1.1 then this line can be dropped

2017-11-12 07:02 UTC, ilovezfs approved these changes

2017-11-12 21:13 UTC, ilovezfs commented
Thanks for the :new: formula @John-K!

2017-11-12 21:13 UTC, closed without merging