logstash 6.0.0
Homebrew/homebrew-core pull request #20637
Opened 2017-11-14 16:47 UTC by jasontedor

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-11-14 16:48 UTC, jasontedor commented
Please note the logstash@5.6 formula in this PR is simply a rename of the existing formula to 5.6; as that formula is already accepted into this repository, logstash@5.6 should not need a review here.

2017-11-15 11:21 UTC, ilovezfs requested changes
Please make the addition of logstash@5.6 a separate commit with the commit subject `logstash@5.6 5.6.4 (new formula)`

2017-11-15 11:46 UTC, ilovezfs commented
The versioned formula needs to be `keg_only :versioned_formula`

2017-11-15 14:22 UTC, jasontedor commented
This is split into two commits now as requested.

2017-11-15 14:53 UTC, ilovezfs commented on Formula/logstash@5.6.rb
> +  bottle :unneeded
blank line under this please

2017-11-15 15:20 UTC, jasontedor commented on Formula/logstash@5.6.rb
> +  bottle :unneeded
I pushed.

2017-11-15 15:21 UTC, ilovezfs approved these changes

2017-11-15 15:24 UTC, merged

2017-11-15 15:25 UTC, ilovezfs commented
Thanks again @jasontedor! :fireworks:

2017-11-15 19:16 UTC, jasontedor commented
Awesome, thanks. 🎉