elasticsearch 6.0.0
Homebrew/homebrew-core pull request #20639
Opened 2017-11-14 16:53 UTC by jasontedor

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-11-14 16:54 UTC, jasontedor commented
Please note the elasticsearch@5.6 formula in this PR is simply a rename of the existing formula to 5.6; as that formula is already accepted into this repository, elasticsearch@5.6 should not need a review here.

2017-11-15 11:39 UTC, ilovezfs requested changes
Please make the addition of elasticsearch@5.6 a separate commit with the commit subject `elasticsearch@5.6 5.6.4 (new formula)`

2017-11-15 11:40 UTC, ilovezfs commented on Formula/elasticsearch.rb
> +    bin.install libexec/"bin/elasticsearch", libexec/"bin/elasticsearch-keystore", libexec/"bin/elasticsearch-plugin", libexec/"bin/elasticsearch-translog"
would be good to avoid going passed the eightieth column

2017-11-15 11:41 UTC, ilovezfs commented
The versioned formula needs to be `keg_only :versioned_formula`

2017-11-15 14:20 UTC, jasontedor commented
This is split into two commits now and I have made the other requested changes.

2017-11-15 14:45 UTC, merged

2017-11-15 14:46 UTC, ilovezfs commented
Thanks @jasontedor! :balloon:

2017-11-15 14:47 UTC, jasontedor commented
Thanks @ilovezfs!