auditbeat 6.0.0 (new formula)
Homebrew/homebrew-core pull request #20630
Opened 2017-11-14 16:33 UTC by jasontedor

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-11-14 19:12 UTC, jasontedor commented
```
18:18:30 Error: 2 problems in 1 formula
18:18:30 auditbeat:
18:18:30   * New formulae should not require patches to build. Patches should be submitted and accepted upstream first.
18:18:30   * New formulae should not require patches to build. Patches should be submitted and accepted upstream first.
```

The default configuration file that upstream ships with enables features that are not compatible with macOS so these need to be disabled, hence the patch here. Can we please whitelist this being patched?

2017-11-14 19:26 UTC, ilovezfs commented
It would be far preferable to get a compatible config file into the tarball :)

2017-11-14 20:58 UTC, jasontedor commented
I can look into that but that needs to be a follow-up, for now this is what we have for 6.0.0. 😇

2017-11-14 21:03 UTC, ilovezfs commented
you'll need to use `inreplace` instead of a patch

2017-11-14 22:19 UTC, jasontedor commented
@ilovezfs Why? This is much easier to write and a lot clearer.

2017-11-15 03:52 UTC, ilovezfs commented
https://github.com/Homebrew/brew/blob/d450b2fec793232226ae09db825a2ad8dab1becc/docs/Formula-Cookbook.md#inreplace

>inreplace should be used instead of patches when patching something that will never be accepted upstream

Also, new formulae cannot have patches.

2017-11-15 11:50 UTC, ilovezfs requested changes
This should use a resource block and `setup_install_args` instead of the virtualenv DSL.

2017-11-15 13:18 UTC, ilovezfs commented
```
# Sets up the virtual python environment
.PHONY: python-env
python-env:
        @test -d $(PYTHON_ENV) || virtualenv $(VIRTUALENV_PARAMS) $(PYTHON_ENV)
        @$(PYTHON_ENV)/bin/pip install -q --upgrade pip autopep8 six
```
That will fetch binary wheels.

2017-11-15 13:55 UTC, ilovezfs commented
`pip install --no-binary :all:` will prevent that.

2017-12-01 04:26 UTC, ilovezfs commented
what's the status here?

2017-12-31 16:30 UTC, jasontedor commented
@ilovezfs I have updated this PR; when you have a chance would you please review again?

2017-12-31 16:33 UTC, ilovezfs commented on Formula/auditbeat.rb
> +        -path.home #{prefix}/libexec \
#{libexec}

2017-12-31 16:33 UTC, ilovezfs commented on Formula/auditbeat.rb
> +
no blank line

2017-12-31 16:34 UTC, ilovezfs commented on Formula/auditbeat.rb
> +      s = (testpath/"auditbeat/auditbeat").read.chomp
why chomp if we're not using `assert_equal`?

2017-12-31 16:35 UTC, ilovezfs approved these changes
minor stuff but :+1:

2018-01-01 13:40 UTC, jasontedor commented
Thanks. I pushed a commit addressing your feedback.

2018-01-02 11:46 UTC, ilovezfs commented
Thanks for the :new: formula @jasontedor! :ship:d

2018-01-02 11:47 UTC, closed without merging

2018-01-02 14:56 UTC, jasontedor commented
Thanks @ilovezfs!