rsync-time-backup v1.1.5 (new formula)
Homebrew/homebrew-core pull request #21065
Opened 2017-11-26 18:07 UTC by laurent22

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2017-12-12 17:34 UTC, BenjaminHCCarr commented
I am on El Capitan still and use `hln` for Hard Links as 10.11 didn't ship with `ln` for hard linls only `ln -s` support. This may explain some inconsistencies noted in laurent22/rsync-time-backup#46

What OS version are you testing on? 10.13 with APFS may support Hardlinks out of the box.

You may need to add a minimum OS version of hardlinks were added in Sierra|HighSierra, as HFS+ on 10.11.x doesn't support them natively.

```
benc$ brew info hardlink
hardlink: stable 0.3.0 (bottled)
Replace file copies using hardlinks
https://jak-linux.org/projects/hardlink/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/hardlink.rb
==> Dependencies
Build: pkg-config ✔
Required: gnu-getopt ✘, pcre ✔
```

The hardlink fomula: (https://github.com/Homebrew/homebrew-core/blob/master/Formula/hardlink.rb)

2017-12-12 17:39 UTC, BenjaminHCCarr commented
Okay, now I am more confused:
The code calls for symlinks:
https://github.com/laurent22/rsync-time-backup/blob/master/rsync_tmbackup.sh#L139-L141

But the Readme clearly says you are using Hardlinks:
https://github.com/laurent22/rsync-time-backup/blob/master/README.md#L32

but then references symlinks:
https://github.com/laurent22/rsync-time-backup/blob/master/README.md#L42

2017-12-12 17:40 UTC, ilovezfs commented
No idea what you mean @BenjaminHCCarr. HFS+ has support for directory hard links going all the way back to 10.5. Support for directory hard links does not exist in APFS. `ln` is unrelated.

2017-12-12 17:43 UTC, laurent22 commented
@BenjaminHCCarr, the script uses hardlinks via the rsync flag `--hard-links`. There are places in the script where soft links are used too, but not for the backup itself;

2017-12-13 15:09 UTC, fxcoudert requested changes

2017-12-13 15:09 UTC, fxcoudert commented on Formula/rsync-time-backup.rb
> +
We need `bottle :unneeded`

2017-12-15 08:58 UTC, laurent22 commented
@fxcoudert, I've added `bottle: uneeded`

2017-12-15 09:01 UTC, fxcoudert approved these changes

2017-12-15 09:12 UTC, ilovezfs commented
```
rsync-time-backup:
  * C: 6: col 1: Trailing whitespace detected.
```

2017-12-15 09:14 UTC, laurent22 commented
Sorry about that, I've removed the trailing space

2017-12-15 09:16 UTC, ilovezfs approved these changes

2017-12-15 09:47 UTC, merged

2017-12-15 09:47 UTC, ilovezfs commented
Thanks again @laurent22!