howdoi 1.1.10 (new formula)
Homebrew/homebrew-core pull request #21077
Opened 2017-11-27 06:42 UTC by emanresusername

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
could only test on linuxbrew fork, but [sounds like it worked on mac](https://github.com/gleitz/howdoi/pull/174#issuecomment-347066482) (although this was modified according to the audit, so not exactly the same)

2017-11-27 07:15 UTC, emanresusername commented
not sure what's up with the sierra build? :confused:

2017-11-27 08:33 UTC, ilovezfs commented
It's an lxml bug. Set SDKROOT and you should be OK. See

e15fcfc201d7be432073a04daaf2d515c13c214c
7794a60224ba202a91b025fe3ab6666ada2461c3

2017-12-18 16:24 UTC, emanresusername commented
Un-stale-ify

2018-01-27 06:51 UTC, vinyldarkscratch commented
@BrewTestBot test this please

2018-01-27 06:59 UTC, vinyldarkscratch commented
Seems that `howdoi` has its own tap and formula, with lots of updates (version number and URL).  Test bot isn't liking the current URL in this PR anymore.  Can you grab the formula from https://raw.githubusercontent.com/gleitz/howdoi/master/howdoi.rb real quick?

2018-01-27 10:41 UTC, vinyldarkscratch commented
Thank you!

2018-01-27 10:47 UTC, queengooborg requested changes

2018-01-27 10:47 UTC, vinyldarkscratch commented on Formula/howdoi.rb
> +  url 'https://pypi.python.org/packages/67/e0/18ca30a65aeed25c6d6fe7171d71601b3a772bf0b7b8235b9e98d3cb889e/howdoi-1.1.12.tar.gz'
The audit is saying that this line should read exactly like:

`url "https://files.pythonhosted.org/packages/67/e0/18ca30a65aeed25c6d6fe7171d71601b3a772bf0b7b8235b9e98d3cb889e/howdoi-1.1.12.tar.gz"`

2018-01-27 10:47 UTC, vinyldarkscratch commented on Formula/howdoi.rb
> +  depends_on :python if MacOS.version <= :snow_leopard
Can you replace `:python` with `python`?

2018-01-27 10:48 UTC, queengooborg requested changes

2018-01-27 10:48 UTC, vinyldarkscratch commented on Formula/howdoi.rb
> +  sha256 'c8676cea5155a8bb3d996f3555942e2726029338c606e36ed32775717a5e7bac'
Oops, missed one: can you replace the single quotes with double quotes?

2018-01-27 21:01 UTC, vinyldarkscratch commented
@emanresusername The URL that you’ve currently got redirects to `https://files.pythonhosted.org/packages/67/e0/18ca30a65aeed25c6d6fe7171d71601b3a772bf0b7b8235b9e98d3cb889e/howdoi-1.1.12.tar.gz` — can you set the URL to this, please?

2018-01-27 21:30 UTC, queengooborg approved these changes
Looks all good now -- thank you, @emanresusername!

2018-01-28 00:18 UTC, vinyldarkscratch commented
@ilovezfs Ready for merge?

2018-02-09 15:21 UTC, ilovezfs approved these changes

2018-02-09 15:28 UTC, ilovezfs commented
Thanks for the :new: formula @emanresusername!

2018-02-09 15:29 UTC, closed without merging