open-scene-graph: fix compatibility with collada-dom 2.4
Homebrew/homebrew-core pull request #21099
Opened 2017-11-27 15:27 UTC by jcarpent

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-11-27 17:03 UTC, jcarpent commented
@ilovezfs I really do understand what is wrong with this PR. Maybe, you can help me on this bug?
The idea is to make this Formula compatible with the installation of the osg-dae plug-in.

2017-11-27 17:38 UTC, ilovezfs commented
try `ENV["SDKROOT"] = MacOS.sdk_path`

2017-11-27 18:13 UTC, jcarpent commented
@ilovezfs Thanks for your quick reply.

2017-11-27 20:51 UTC, jcarpent commented
It perfectly works.

2017-12-13 16:36 UTC, fxcoudert requested changes

2017-12-13 16:36 UTC, fxcoudert commented on Formula/open-scene-graph.rb
> +      if Formula["collada-dom"].version >= "2.4"
No conditional, we don't support older versions.

2018-01-05 16:09 UTC, jcarpent commented
@fxcoudert I fixed the requested changes.

2018-01-07 08:56 UTC, merged

2018-01-07 08:57 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @jcarpent! Without people like you submitting PRs we couldn't run this project. You rock!