visidata 0.98.1 (new formula)
Homebrew/homebrew-core pull request #21577
Opened 2017-12-11 22:35 UTC by anjakefala

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-12-21 13:18 UTC, anjakefala commented
A new version had been released since I had opened the PR, so I attempted to update the formula, but I am not really certain why the build has failed. I did not see these errors on my sierra OS and I do not completely understand them.

2018-01-11 15:59 UTC, anjakefala commented
Oh, it seems like you are deprecating the 'depends_on :python3'?

I have not heard anything, so I ended up [building a tap here](https://github.com/saulpw/homebrew-vd) to host the formula. 

If you can provide any feedback on the formula, it would be appreciated. I can help you update the python-formula documentation.

2018-02-02 17:05 UTC, anjakefala commented
ping @ilovezfs, is it possible to get an update on whether to close the PR, whether you need more information or if you would like me to wait longer?

2018-02-02 18:16 UTC, ilovezfs requested changes

2018-02-02 18:16 UTC, ilovezfs commented on Formula/visidata.rb
> +      (lib/"python#{version}/site-packages/homebrew-visidata-bundle.pth").write "#{bundle_path}\n"
I don't think we should be doing this. As a rule, Homebrew packages Python applications not Python libraries, so exposing the libraries here doesn't make sense.

2018-02-02 18:16 UTC, ilovezfs commented on Formula/visidata.rb
> +    system "#{libexec}/bin/python3", "-c", "import visidata"
The test should exercise and verify the functionality of `vd`.

2018-02-02 18:16 UTC, ilovezfs commented on Formula/visidata.rb
> +  head "https://github.com/saulpw/visidata.git"
would rather we not include HEAD

2018-02-02 18:16 UTC, ilovezfs commented on Formula/visidata.rb
> +  homepage "http://visidata.org"
trailing slash

2018-02-07 01:53 UTC, anjakefala commented
I updated the formula based on your requests. The good news is that the test seems to be functional. ^^; I will investigate the failures.

2018-02-07 02:25 UTC, anjakefala commented
The failures are due to the fact that VisiData, since VisiData was running headless it tried to check whether something was piped in through stdin (which it was not).

Code updates will be required for VisiData in order for it to run in headless mode in this scenario.

2018-02-25 00:54 UTC, anjakefala commented
We have decided that, since there is not a reliable way to fix this issue for the homebrew tests, to continue to just maintain our own tap.

Closing PR.

2018-02-25 00:54 UTC, closed without merging