par2 0.8.0 (adds OpenMP support)
Homebrew/homebrew-core pull request #21760
Opened 2017-12-15 14:23 UTC by outlyer

* Upgrade to new upstream version
* Optional support for new higher performance OpenMP multi-threading via LLVM build

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-12-15 14:54 UTC, fxcoudert requested changes

2017-12-15 14:54 UTC, fxcoudert commented on Formula/par2.rb
> -  end
Do not touch the bottle block. It is automatically updated upon merging.

2017-12-15 14:54 UTC, fxcoudert commented on Formula/par2.rb
> +  depends_on "llvm" => [:build, :optional]
We shouldn't depend on `llvm`, but use: `option "with-openmp", "Compile with OpenMP support"` and `needs :openmp if build.with? "openmp"` which handles it automatically. See for example how `imagemagick` does it.

2017-12-16 19:55 UTC, outlyer commented
@fxcoudert I've added the changes you requested.

2017-12-16 20:53 UTC, fxcoudert commented on Formula/par2.rb
> +      ENV["CXX"] = "#{Formula["llvm"].opt_bin}/clang++"
No, we support OpenMP in other ways, such as using GCC as a compiler. So this formula should not hardcode anything specific to llvm.

The configure script uses `AC_OPENMP`, so OpenMP should be automatically detected and used if available.

2018-01-07 09:10 UTC, ilovezfs commented
Going to pass on adding an `openmp` option as we generally only add it when required. Thanks for the PR nonetheless @outlyer.

2018-01-07 09:10 UTC, closed without merging