wangle 2017.12.25.00 (new formula)
Homebrew/homebrew-core pull request #22153
Opened 2017-12-26 22:45 UTC by alebcay

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-12-28 12:38 UTC, DomT4 commented on Formula/wangle.rb
> +    Dir.chdir("wangle")
`cd "wangle" do`

2017-12-28 14:54 UTC, alebcay commented
Requested changes have been implemented.

2018-01-01 00:18 UTC, stephengroat commented on Formula/wangle.rb
> +
maybe add a link to `head` with `head "https://github.com/facebook/wangle"`?

2018-01-01 12:15 UTC, ilovezfs commented
@BrewTestBot test this please

2018-01-02 10:50 UTC, ilovezfs requested changes

2018-01-02 10:50 UTC, ilovezfs commented on Formula/wangle.rb
> +    (testpath/"EchoServer.cpp").write <<~EOS
let's fetch this and the other heredocs as resources

2018-01-02 10:50 UTC, ilovezfs commented on Formula/wangle.rb
> +                    "-I#{Formula["gflags"].include}",
opt_include not include, opt_lib not lib

2018-01-02 10:50 UTC, ilovezfs commented on Formula/wangle.rb
> +                    "-lgflags", "-lglog", "-lcrypto", "-lssl", "-lfolly", "-lwangle",
probably want a `-L#{lib}` and `-I#{include}`

2018-01-02 10:50 UTC, ilovezfs commented on Formula/wangle.rb
> +                    "-o", "EchoClient"
we should actually execute the test program and assert that it does something

2018-01-03 14:51 UTC, ilovezfs commented
@BrewTestBot test this please

2018-01-04 05:49 UTC, ilovezfs commented
@BrewTestBot test this please

2018-01-04 11:47 UTC, ilovezfs commented
@alebcay ping :)

2018-02-01 12:07 UTC, closed without merging