gforth: fix emacs support & add testing
Homebrew/homebrew-core pull request #22267
Opened 2017-12-30 20:32 UTC by ylluminarious

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

These changes make it so that Gforth has its Emacs support installed. It also makes it so that it compiles the Elisp file with a more recent version of Emacs than the system Emacs, if possible. Furthermore, I added a test to this formula which it did not have until now. The test just sees whether the interpreter can evaluate `1 + 1` (which is `1 1 +` in Forth) and then exits.

2018-01-02 09:57 UTC, ilovezfs requested changes
Let's require Homebrew's emacs here, non-optionally, and call it a day.

Note `#{bin}/emacs` doesn't point at `/usr/local/bin/emacs` but points at `/usr/local/Cellar/gforth/0.7.3/bin/emacs`, which presumably doesn't even exist. Did you test this? It shouldn't work as written since you didn't use `#{Formula["emacs"].opt_bin}/emacs`.

2018-01-02 18:15 UTC, ylluminarious commented
@ilovezfs I did test this, but I use Cocoa Emacs and I forgot what `bin` actually meant. I'll go ahead and change the formula as you desire and post another comment here once I do.

2018-01-08 23:09 UTC, ylluminarious commented
@ilovezfs I changed the formula as you requested and I also squashed my changes into the same commit. Please let me know if anything else is needed.

2018-01-22 05:41 UTC, ylluminarious commented
@ilovezfs Are the changes still pending your review or are they no good?

2018-01-22 05:43 UTC, ilovezfs commented
@ylluminarious still pending. I'm working on https://github.com/Homebrew/brew/pull/3714 at the moment but I'll try to take look later today.

2018-01-22 05:44 UTC, ylluminarious commented
@ilovezfs No problem, just wondering. Thanks for updating me.

2018-01-22 08:12 UTC, ilovezfs requested changes

2018-01-22 08:12 UTC, ilovezfs commented on Formula/gforth.rb
>      system "make", "install"
```
    elisp.mkpath
    system "make", "install", "emacssitelispdir=#{elisp}"
```

2018-01-22 08:12 UTC, ilovezfs commented on Formula/gforth.rb
> +    elisp.install "gforth.el"
don't need to do this manually

2018-01-22 08:12 UTC, ilovezfs commented on Formula/gforth.rb
> +  def caveats
don't need the caveat. if you're building from source and not pouring the bottle, you should expect build time dependencies you may not want to keep

2018-01-22 08:12 UTC, ilovezfs commented on Formula/gforth.rb
> +    assert_match "2", shell_output("#{bin}/gforth -e '1 1 + . bye'", 0)
0 is the default and we can use assert_equal
```
   assert_equal "2 ", shell_output("#{bin}/gforth -e '1 1 + . bye'")
```

2018-01-22 08:12 UTC, ilovezfs commented on Formula/gforth.rb
> +  depends_on "emacs" => :build
build deps before run deps

2018-01-22 08:12 UTC, ilovezfs commented on Formula/gforth.rb
> +    system "make", "EMACS=#{HOMEBREW_PREFIX}/bin/emacs"
```
    system "make", "EMACS=#{Formula["emacs"].opt_bin}/emacs"
```

2018-01-22 19:42 UTC, ylluminarious commented
@ilovezfs Ok, I changed as per your requests again. I also squashed it again so that it is hopefully it is adequate.

2018-01-31 00:20 UTC, ylluminarious commented
@ilovezfs Friendly ping... anything else need to be done here?

2018-02-09 13:46 UTC, ilovezfs approved these changes

2018-02-09 13:46 UTC, ilovezfs commented
@BrewTestBot test this please

2018-02-09 13:50 UTC, ilovezfs commented
@BrewTestBot test this please

2018-02-09 14:08 UTC, ilovezfs commented
Super work here @ylluminarious! Thanks again!

2018-02-09 14:08 UTC, closed without merging

2018-02-09 15:39 UTC, ylluminarious commented
@ilovezfs Thank you!