smlnj 110.82
Homebrew/homebrew-core pull request #22577
Opened 2018-01-08 15:47 UTC by chmaynard

New version released on October 16, 2017.
See https://www.smlnj.org/dist/working/110.82/110.82-README.html

No build or audit issues with my updated formula for 110.82. However, ```brew test``` emits this message:

    $ brew test smlnj
    Testing smlnj
    ==> /Users/craig/brew/Cellar/smlnj/110.82/bin/ml-nlffigen

2018-01-08 16:20 UTC, chmaynard commented
Another issue, the REPL still has the old version number.

    $ sml
    Standard ML of New Jersey v110.81 [built: Mon Jan  8 09:19:31 2018]

2018-01-09 10:39 UTC, queengooborg requested changes
The brew test bot is expecting a different SHA256 for a few different resources.  Can you update them?

2018-01-09 10:39 UTC, vinyldarkscratch commented on Formula/smlnj.rb
>      sha256 "5168f96600e0e97b533582519b51e607345b454733277051c505d86165ef532e"
Can you update this SHA256?

2018-01-09 10:39 UTC, vinyldarkscratch commented on Formula/smlnj.rb
>      sha256 "5bdc9fe2fa20ea6b108e54725dac3933b5dbc68e43b818b4af2b99f49178a7ee"
And this one?

2018-01-09 10:39 UTC, vinyldarkscratch commented on Formula/smlnj.rb
>      sha256 "061e0eff80ea0e51aded9e9ab97d7cc1fefd014d8b4f147db2c79bbdc6bce896"
Also this one?

2018-01-09 10:39 UTC, vinyldarkscratch commented on Formula/smlnj.rb
>      sha256 "3ecdd0e21a2563569526cd7c1d9073506bfebf976c94c7e4821920c3a475a4b4"
And here?

2018-01-09 10:39 UTC, vinyldarkscratch commented on Formula/smlnj.rb
>      sha256 "fcdc749ec587f271880aeea356189cbf48761eedca5478ea811afce4302ae2a6"
And here?

2018-01-09 10:39 UTC, vinyldarkscratch commented on Formula/smlnj.rb
>      sha256 "91949f33578be7e3e9160401fc86ca8932fc127335be98ab70b1614d42baa747"
And here?

2018-01-09 10:39 UTC, vinyldarkscratch commented on Formula/smlnj.rb
>      sha256 "6b7caa5038f1a80107d7b141299749271c63ad2b665bd66d76cf857a69b67159"
Here as well?

2018-01-09 10:39 UTC, vinyldarkscratch commented on Formula/smlnj.rb
>      sha256 "31dda7e04a3a3d83b518c5e2e17094e2f386449957bfb2878dd4d5053fe3c395"
And finally, here?

2018-01-09 19:02 UTC, chmaynard commented
I'm withdrawing this PR and starting over. Sorry for the noise.

2018-01-09 19:02 UTC, closed without merging