Jenkins
Homebrew/homebrew-core pull request #22671
Opened 2018-01-10 00:56 UTC by ryenus

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Java 8 is required since Jenkins 2.54 and Jenkins LTS 2.60.1, however Java 9 is not supported yet, see:
- https://jenkins.io/blog/2017/04/10/jenkins-has-upgraded-to-java-8/
- https://jenkins.io/doc/upgrade-guide/2.60/
- https://issues.jenkins-ci.org/browse/JENKINS-40689

In case one have both java 8 and java 9 installed, it's necessary to specify which java version to use for Jenkins.

Please note this requires an improved version of `bin.write_jar_script`, see:  https://github.com/Homebrew/brew/pull/3656.

2018-01-10 01:10 UTC, vinyldarkscratch commented
The test bot seems to be failing due to it not having that improved version of `bin.write_jar_script`.  @DomT4 has a response for you on the pull request for Brew itself that you should look at?

2018-01-10 09:05 UTC, ryenus commented
@vinyldarkscratch thank you and you're right, so I responded. Let's wait for @DomT4 to decide.

And I wish there could be a way to tell the bot to hold and wait until the other PR is merged first :D

2018-01-10 09:06 UTC, vinyldarkscratch commented
@ryenus Actually, there's a nice little phrase you can say to trigger a build right on the spot:
"@ BrewTestBot test this please" (without the space between the @ and the username, of course)

That'll tell the test bot to start building right away.  :wink:

2018-01-10 09:19 UTC, ryenus commented
@vinyldarkscratch not exactly what I want but surely that sounds nice!

So we can tell the bot to test again when the time is right, that's cool! I'm glad to know this. BTW, do we really need to be that polite to a bot? 😃 Sounds like it must be a kind bot.

2018-01-10 09:21 UTC, vinyldarkscratch commented
Haha, it definitely is -- considering it's working so hard to test our formulas, and build the bottles we need, we've gotta give it some 💜 and kindness for sure!

2018-01-10 21:43 UTC, DomT4 commented
> Let's wait for @DomT4 to decide.

To be clear on this front, I'm powerless these days. My self-chosen "role" is more or less to drift in & out of the project providing advice/past experience where I can, but I have no formal power to yay/nay anything.

> "@ BrewTestBot test this please"

Doesn't work unless the bot knows you have that power, I'm afraid 😉.

2018-01-10 21:45 UTC, vinyldarkscratch commented
Really?  @DomT4, I'm able to ask the test bot to test things...guess I have the power!  😈

2018-01-10 21:51 UTC, DomT4 commented
Unless things have changed behind-the-scenes, it used to need to know you had the "right" to call it, otherwise it'd just blank ya 🙈.

2018-02-14 14:44 UTC, ilovezfs commented
@apjanke any thoughts here?

2018-02-14 14:59 UTC, apjanke requested changes
`write_jar_script` needs to use the named-parameter calling form.

Aside from that, this seems to me like the right thing to do.

2018-02-14 14:59 UTC, apjanke commented on Formula/jenkins-lts.rb
> +    bin.write_jar_script libexec/"jenkins.war", "jenkins-lts", "", "1.8"
Correct/more readable calling form:
```
bin.write_jar_script libexec/"jenkins.war", "jenkins-lts", :java_version => "1.8"
```

2018-02-14 14:59 UTC, apjanke commented on Formula/jenkins-lts.rb
> +    bin.write_jar_script libexec/"jenkins-cli.jar", "jenkins-lts-cli", "", "1.8"
bin.write_jar_script libexec/"jenkins-cli.jar", "jenkins-lts-cli", :java_version => "1.8"

2018-02-14 14:59 UTC, apjanke commented on Formula/jenkins.rb
> +    bin.write_jar_script libexec/"jenkins.war", "jenkins", "", "1.8"
bin.write_jar_script libexec/"jenkins.war", "jenkins", :java_version => "1.8"

2018-02-14 14:59 UTC, apjanke commented on Formula/jenkins.rb
> +    bin.write_jar_script libexec/"jenkins-cli.jar", "jenkins-cli", "", "1.8"
bin.write_jar_script libexec/"jenkins-cli.jar", "jenkins-cli", :java_version => "1.8"

2018-02-14 15:32 UTC, ilovezfs requested changes
@ryenus please address @apjanke's feedback when you have a chance!

2018-02-20 04:27 UTC, ryenus commented
@apjanke @ilovezfs yeah, I agree that using named parameter is better here, thanks!

2018-02-20 08:12 UTC, ilovezfs submitted a review, later dismissed
must wait for brew 1.5.5

2018-03-17 13:58 UTC, fxcoudert commented
@BrewTestBot test this please

2018-03-17 14:13 UTC, fxcoudert commented
@ryenus can you push an update, so that the pull request has 2 commits, with one commit per formula? thanks!

2018-03-19 07:12 UTC, ryenus commented
@fxcoudert done!

@ilovezfs thanks so much for helping move this forward!

2018-03-19 11:56 UTC, fxcoudert commented
Thanks @ryenus !

2018-03-19 11:56 UTC, closed without merging