draco 1.2.4 (new formula)
Homebrew/homebrew-core pull request #22714
Opened 2018-01-10 17:37 UTC by hobu

Initial support for Google Draco, a C++ point cloud and mesh compression library. https://github.com/google/draco

Checklist
-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-01-21 20:13 UTC, hobu commented
Should I expect this package to make it into homebrew-core, or should I submit it to another tap? If so, can you please suggest where it might be appropriate?

2018-02-14 13:49 UTC, fxcoudert requested changes

2018-02-14 13:49 UTC, fxcoudert commented on Formula/draco.rb
> +      system "cmake", "..", *args
Let's not enable tests please (we only do that for security software). Thus:

`system "cmake", "..", * std_cmake_args`

2018-02-14 13:49 UTC, fxcoudert commented on Formula/draco.rb
> +    shell_output("#{bin}/draco_encoder --help", 255)
We will need a test that actually exercises the software's functionality.

2018-02-14 13:49 UTC, fxcoudert commented on Formula/draco.rb
> +  url "https://github.com/google/draco/archive/1.2.4.tar.gz"
Sorry it took long to review… please update to latest version, 1.2.5

2018-02-14 15:10 UTC, fxcoudert commented
We will need a test that actually exercises the software's functionality.

2018-02-14 15:11 UTC, hobu commented
> We will need a test that actually exercises the software's functionality.

I wasn't sure what to do here. It's just a support library.

2018-02-14 16:15 UTC, fxcoudert commented
Does it include a source example or test file that we could install (in `pkgshare`), then compile and run as a test? Otherwise, we can include a very simple C file (see for example what we do in `gmp`).

2018-03-11 15:47 UTC, fxcoudert commented
Thanks @hobu for the pull request!

2018-03-11 15:48 UTC, fxcoudert approved these changes

2018-03-11 15:49 UTC, closed without merging