postgis: add --with-protobuf option for protobuf support
Homebrew/homebrew-core pull request #22801
Opened 2018-01-12 22:42 UTC by afrith

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

PostGIS 2.4 added the [`ST_AsMVT` function](https://postgis.net/docs/ST_AsMVT.html), but this function fails in the the default Homebrew PostGIS build, because it requires protobuf support which is not built in. This PR adds a `--with-protobuf` option to the formula which enables protobuf support.

2018-01-13 09:42 UTC, ilovezfs requested changes
```
depends_on "protobuf-c" => :optional
```
and option name is `with-protobuf-c`

2018-01-13 12:07 UTC, afrith commented
I have pushed the changes as requested.

2018-01-13 17:26 UTC, ilovezfs submitted a review, later dismissed

2018-01-13 17:29 UTC, ilovezfs commented
You can still add a customized description for the option

```
option "with-protobuf-c", "Enables the wizbang feature"
```

2018-01-14 15:50 UTC, ilovezfs approved these changes

2018-01-14 15:51 UTC, merged

2018-01-14 15:52 UTC, ilovezfs commented
Thanks again for your first contribution to Homebrew, @afrith! Without people like you submitting PRs we couldn't run this project. You rock!