Added KrakenD API Gateway formula
Homebrew/homebrew-core pull request #23425
Opened 2018-01-29 09:22 UTC by alombarte

Hello, reopening #23131 as we have reached the 20 needed watchers.

---
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

http://www.krakend.io

Thank you!
-----

2018-01-29 10:02 UTC, alombarte commented
The KrakenD project is in the URL https://github.com/devopsfaith/krakend/ and has all the stars, forks and watchers required. Nevertheless we haven a different repository with the builder to let the users compile the binary themselves is in https://github.com/devopsfaith/krakend-ce/.

Looks like Jenkins is checking the `krakend-ce` repository instead of `krakend`. We created this repo to not distribute binaries (as you prefer compilation over binary placement).

Thanks

2018-01-29 12:41 UTC, vinyldarkscratch commented
To whoever reviews this for pulling: install from source and strict audit passed on my local machine as well.  So, the only apparent issue is the noteable repository check, which as @alombarte says, is checking the wrong one.

2018-01-29 13:21 UTC, ilovezfs requested changes

2018-01-29 13:21 UTC, ilovezfs commented on Formula/krakend.rb
> +    system "#{bin}/krakend", "--help"
This needs to be a functionality test

2018-01-29 17:07 UTC, alombarte commented
@ilovezfs I added an assert in the test function to ensure binary is able to run and show the expected version. Nevertheless the previous line you requested to change has been taken from numerous `homebrew-core` formula. As a suggestion maybe this could be included in the website documentation.

Thanks for your time

2018-02-01 14:47 UTC, ilovezfs commented
@alombarte a test for functionality means specifically not a `--help` or `--version` test. What you see in old formulae is irrelevant, as we have much higher standards these days for new formulae. For good examples, see `dep`, `faas-cli`, and `jose`.

2018-02-02 15:12 UTC, ilovezfs commented
```
  * C: 23: col 1: Use 2 spaces for indentation in a heredoc by using `<<~` instead of `<<~`.
  * C: 38: col 1: Use 2 spaces for indentation in a heredoc by using `<<~` instead of `<<~`.
  * C: 44: col 4: Inconsistent indentation detected.
  * C: 46: col 1: Extra blank line detected.
  * C: 47: col 4: Inconsistent indentation detected.
  * C: 48: col 1: Use 2 spaces for indentation in a heredoc by using `<<~` instead of `<<~`.
```

2018-02-02 16:53 UTC, ilovezfs approved these changes

2018-02-02 16:59 UTC, closed without merging

2018-02-02 17:01 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @alombarte! Without people like you submitting PRs we couldn't run this project. You rock! :white_check_mark:

2018-02-02 18:16 UTC, alombarte commented
Thank you @ilovezfs , but I see the issue closed without merging to master. Is this expected?

2018-02-02 18:28 UTC, ilovezfs commented
scroll up.

<img width="530" alt="screen shot 2018-02-02 at 10 28 31 am" src="https://user-images.githubusercontent.com/5268928/35748709-d868b4ae-0846-11e8-86e4-c8ce0536b979.png">