Shelltestrunner formula added.
Homebrew/homebrew-core pull request #23459
Opened 2018-01-30 07:23 UTC by taavi-valjaots

- [ok] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ok] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ok] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ok] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-01-30 17:06 UTC, ilovezfs requested changes

2018-01-30 17:06 UTC, ilovezfs commented on Formula/shelltestrunner.rb
> +  url "https://github.com/simonmichael/shelltestrunner/archive/1.9.tar.gz"
let's use the Hackage tarball

2018-01-31 08:29 UTC, taavi-valjaots commented
Fixes implemented.

I'm a little bit confused how are the bottles built? I know that `brew bottle formula` builds the bottle but how to make it available? Should I do something or is it done by brew maintainers?

2018-02-01 03:11 UTC, woodruffw commented
> I'm a little bit confused how are the bottles built? I know that brew bottle formula builds the bottle but how to make it available? Should I do something or is it done by brew maintainers?

Our CI and bots take care of the bottle-building and formula-patching process -- you don't need to do anything with respect to that 🙂.

2018-02-01 12:52 UTC, ilovezfs approved these changes

2018-02-01 13:08 UTC, closed without merging

2018-02-01 13:08 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @taavi-valjaots! Without people like you submitting PRs we couldn't run this project. You rock!