Add hexer
Homebrew/homebrew-core pull request #23644
Opened 2018-02-03 22:18 UTC by mabrowning

Hexer is a LGPL C++ library that provides some classes for generating hexbin density surfaces and multipolygon boundaries for large point sets.

Simple cmake project with 1 dependency (gdal)

I'm starting to add all the dependencies needed to build [OpenDroneMap](opendronemap.org) natively. This library is needed to build a plugin for the `pdal` package (pull request forthcoming).

- [👍] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [👍] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [👍] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [👍] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-02-03 22:32 UTC, mabrowning commented
Build failed because github repo doesn't have 50 stars... currently at 42. However, this is a dependency for [OpenDroneMap](https://github.com/OpenDroneMap/OpenDroneMap/), which has hundreds of stars, forks, and follows.

2018-02-05 08:37 UTC, fxcoudert commented
@mabrowning Do you have plans to submit OpenDroneMap as a formula shortly?

2018-02-05 15:14 UTC, mabrowning commented
@fxcoudert I am, although there are quite a few packages I'll need to formulated, and I'll need to work out how best to get all the python dependencies available from pip installed.

For reference, I'll be submitting or extending:
pdal (to include this hexer plugin)
[OpenGV](https://github.com/paulinus/opengv/)
[OpenSfM](https://github.com/mapillary/OpenSfM/)
[ecto](https://github.com/plasmodic/ecto) a python work queue framework - although this may be better distributed through pypi
[OpenDroneMap](https://github.com/OpenDroneMap/OpenDroneMap)

in roughly that dependency order. Alternatively, I could package all of these up as private dependencies in the OpenDroneMap formula, but I think OpenSfM (which depends on OpenGV) does have wider appeal.

2018-02-05 15:54 UTC, mabrowning commented
I should clarify. OpenDroneMap calls a series of executables to perform much of its work. One of those is `pdal`, which homebrew has a package for. However, `pdal` is setup as a series of (optional) plugins, and OpenDroneMap makes use of a plugin which the homebrew package doesn't include. This `hexer` package is necessary so that we can modify the `pdal` package to include the `hexbin` plugin for pdal (see [pdal-add-hexbin](https://github.com/mabrowning/homebrew-core/tree/pdal-add-hexbin) which I have not submitted yet as it depends on this package).

2018-02-05 16:07 UTC, fxcoudert commented
Some of these seem quite low usage in themselves… and some don't even have released versions, which is going to be a problem for Homebrew. Another option, as you said, would be to vendor them as private dependencies inside your final formula.

2018-02-05 16:33 UTC, mabrowning commented
I agree, especially after looking at a few other small-time packages that OpenDroneMap makes use of. The reason I'm starting with hexer is that is requires modification of an existing homebrew package. All others can be achieved as vender dependencies inside of OpenDroneMap. 

However, I do think that OpenSfM would be generally useful to many more users than even OpenDroneMap. That package is widely used and versioned.

2018-02-07 10:51 UTC, fxcoudert requested changes

2018-02-07 10:51 UTC, fxcoudert commented on Formula/hexer.rb
> +  depends_on "cmake" => :build
Empty line before that

2018-02-07 10:51 UTC, fxcoudert commented on Formula/hexer.rb
> +  def install
Empty line before that

2018-02-07 10:51 UTC, fxcoudert commented on Formula/hexer.rb
> +  test do
Empty line before that

2018-02-07 10:51 UTC, fxcoudert commented on Formula/hexer.rb
> +    system bin/"curse", "-c", "hex", "-i", "fake_file"
Can we check the output? Or perform some operation on a real file, and check that it works?

2018-02-07 10:51 UTC, fxcoudert commented
Please squash all changes to be made in a single commit, with message `hexer 1.4.0 (new formula)`

2018-03-09 15:29 UTC, closed without merging