posh 0.13.1 (new formula)
Homebrew/homebrew-core pull request #23778
Opened 2018-02-07 00:02 UTC by dbkaplun

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-02-07 10:19 UTC, fxcoudert approved these changes

2018-02-08 11:17 UTC, ilovezfs requested changes

2018-02-08 11:17 UTC, ilovezfs commented on Formula/posh.rb
> +  head "https://salsa.debian.org/clint/posh.git"
I'd leave this out

2018-02-08 11:17 UTC, ilovezfs commented on Formula/posh.rb
> +    system "automake", "--add-missing"
use autoreconf -fiv instead of the separate commands

2018-02-08 11:17 UTC, ilovezfs commented on Formula/posh.rb
> +    system "./configure", "--disable-debug",
```
configure: WARNING: unrecognized options: --disable-debug
```

2018-02-09 01:00 UTC, dbkaplun commented
@ilovezfs ready for review

cc @woodruffw

2018-02-09 12:57 UTC, ilovezfs approved these changes

2018-02-09 13:12 UTC, closed without merging