urdfdom_headers 1.0.0 (new formula)
Homebrew/homebrew-core pull request #23901
Opened 2018-02-09 18:41 UTC by jslee02

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`urdfdom_headers` is the URDF (U-Robot Description Format) headers provides core data structure headers for URDF.

Repo: https://github.com/ros/urdfdom_headers

2018-02-09 19:04 UTC, woodruffw commented on Formula/urdfdom_headers.rb
> +  desc "Headers for URDF parsers "
Trailing space in the `desc`.

2018-02-10 17:36 UTC, fxcoudert approved these changes

2018-02-10 17:43 UTC, fxcoudert requested changes
Pretty much the same feedback as `console_bridge`, see there :)

2018-02-11 15:34 UTC, fxcoudert approved these changes

2018-02-11 15:34 UTC, fxcoudert commented
Great!

2018-02-11 15:35 UTC, closed without merging