sbt@0.13 0.13.17
Homebrew/homebrew-core pull request #23917
Opened 2018-02-09 23:25 UTC by eed3si9n

Bumps up sbt@0.13 to the latest maintenance release 0.13.17.
Also this changes installs it as `bin/sbt0` so we can use it side by side with sbt 1.x.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2018-02-10 08:49 UTC, fxcoudert requested changes
OK for the version bump.

👎 to removing `keg_only` and installing it under a different name. That's not how we want to handle these versioned formulas.

2018-02-10 09:10 UTC, fxcoudert commented
We could remove `keg_only` if there is an official build option to add suffix to program names. We won't patch them in Homebrew, however.

2018-02-12 16:02 UTC, eed3si9n commented
ok. I'll drop `sbt@0.13: Install as bin/"sbt0"` then.

2018-02-13 12:27 UTC, fxcoudert commented
Thanks @eed3si9n!

2018-02-13 12:28 UTC, fxcoudert approved these changes

2018-02-13 12:28 UTC, closed without merging