grv 0.1.2 (new formula)
Homebrew/homebrew-core pull request #23910
Opened 2018-02-09 21:54 UTC by rgburke

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
GRV is a terminal interface for viewing git repositories

2018-02-11 15:59 UTC, fxcoudert requested changes

2018-02-11 15:59 UTC, fxcoudert commented on Formula/grv.rb
> +  depends_on "cmake" => :build
alphabetical order among build deps

2018-02-11 15:59 UTC, fxcoudert commented on Formula/grv.rb
> +    assert_match version.to_s, shell_output("#{bin}/grv -version")
We need a test that does a bit more than output version number.

2018-02-11 18:10 UTC, rgburke commented
@fxcoudert Thank you for the review and the feedback. I have corrected the order of the build deps and improved the test.

2018-02-11 18:10 UTC, DomT4 commented on Formula/grv.rb
> +      bin.install "grv"
You'll likely need to add a `prefix.install_metafiles` line here.

This ensures things like `README`, `LICENSE` and `CHANGELOG` where available are installed into the prefix. Normally Homebrew handles this automatically with a little magic, but when you relocate the entire contents of the `buildpath` to another directory for the install process as is common with `go`-using formulae that logic falls on its face & it needs a little manual nudging. It's a known issue.

2018-02-11 18:11 UTC, DomT4 commented on Formula/grv.rb
> +    system "echo '<grv-exit>' | #{bin}/grv -logLevel DEBUG"
Use `pipe_output()` for this.

2018-02-13 12:29 UTC, fxcoudert approved these changes

2018-02-13 12:31 UTC, fxcoudert commented
Thanks @rgburke for the pull request, and congrats on your first contribution to Homebrew!

2018-02-13 12:32 UTC, closed without merging