hss 1.6 (new formula)
Homebrew/homebrew-core pull request #24016
Opened 2018-02-12 06:11 UTC by six-ddc

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-02-12 10:14 UTC, fxcoudert requested changes

2018-02-12 10:14 UTC, fxcoudert commented on Formula/hss.rb
> +    system "#{bin}/hss", "-v"
This is unnecessary.

2018-02-12 10:14 UTC, fxcoudert commented on Formula/hss.rb
> +    system "#{bin}/hss", "-H", "127.0.0.1", "-u", "root", "command ls"
Could we check the output to make sure that we get `Permission denied`? And possibly include a user other than `root` (e.g. `toto123`)

2018-02-12 14:19 UTC, six-ddc commented on Formula/hss.rb
> +    system "#{bin}/hss", "-v"
get

2018-02-13 14:48 UTC, fxcoudert requested changes

2018-02-13 14:48 UTC, fxcoudert commented on Formula/hss.rb
> +  desc "Interactive parallel ssh client featuring autocomplete and asynchronous"
`Interactive parallel ssh client` seems enough

2018-02-13 14:48 UTC, fxcoudert commented on Formula/hss.rb
> +  head "https://github.com/six-ddc/hss.git"
Remove head please

2018-02-13 14:48 UTC, fxcoudert commented on Formula/hss.rb
> +        exec "#{bin}/hss", "-H", "-p 9527 127.0.0.1", "-u", "root", "true", :out => hss_write
Wrap this line to 80

2018-02-13 14:48 UTC, fxcoudert commented on Formula/hss.rb
> +        exec "nc", "-4l", "9527", :out => nc_write
Let's not hardcode the port. You can get a valid port number this way:

```
    require "socket"

    server = TCPServer.new(0)
    port = server.addr[1]
    server.close
```

2018-02-27 14:35 UTC, six-ddc commented
PTAL @fxcoudert , Thanks

2018-03-01 15:08 UTC, fxcoudert commented
Thanks @six-ddc for the pull request!

2018-03-01 15:09 UTC, closed without merging