libsbol v2.3.0.0
Homebrew/homebrew-core pull request #24102
Opened 2018-02-14 07:25 UTC by bbartley

- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-02-14 08:24 UTC, fxcoudert requested changes

2018-02-14 08:24 UTC, fxcoudert commented on Formula/libsbol.rb
> +    if ENV.compiler == :gcc
The case for `:gcc` (with the extra `"-Wl,-rpath=#{HOMEBREW_PREFIX}/lib,-rpath=#{lib}"`) should not be necessary. The compiler should know where it find its own runtime libraries.

2018-02-14 08:24 UTC, fxcoudert commented on Formula/libsbol.rb
> +      system ENV.cc, "test.cpp", "-o", "test", "-std=c++11", "-I/System/Library/Frameworks/Python.framework/Headers", "-I#{HOMEBREW_PREFIX}/include/curl", "-I#{HOMEBREW_PREFIX}/include", \
- `ENV.cxx`
- Remove `-lc++`
- Why does it do `-I#{HOMEBREW_PREFIX}/include/curl` when it doesn't depend on Homebrew curl? Likely remove
- `-I#{Formula["raptor"].opt_include}/raptor2`
- Remove `-I#{HOMEBREW_PREFIX}/include` and include specific packages' include (like raptor)
- `-I#{include}/sbol` should probably be `-I#{include}`, and the test adapted to include `<sbol/sbol.h>`?
- `-L#{HOMEBREW_PREFIX}/lib`: nope

2018-02-15 00:47 UTC, bbartley commented
Hi FX,

Thanks for the comments.  I implemented your recommendations except for:

- Remove -I#{HOMEBREW_PREFIX}/include and include specific packages' include (like raptor)
- -I#{Formula["raptor"].opt_include}/raptor2

The pattern -I#{Formula["raptor"].opt_include}/raptor2 results in "error: 'raptor2.h' file not found with <angled> include; use "quotes" instead".  (The source code uses #include <raptor2.h>) The pattern -I#{HOMEBREW_PREFIX}/include/raptor2 compiles with no problem.

Thanks!
Bryan

2018-02-15 07:52 UTC, fxcoudert commented
There is no reason that `-I#{Formula["raptor"].opt_include}/raptor2` shouldn't work, and it does indeed work for me locally. Can you re-test? It may be a problem with your local setup.

2018-02-15 11:12 UTC, fxcoudert approved these changes

2018-02-15 15:28 UTC, fxcoudert commented
Thanks @bbartley for the pull request!

2018-02-15 15:29 UTC, closed without merging