icemon 3.1.0 (new formula)
Homebrew/homebrew-core pull request #24139
Opened 2018-02-14 18:36 UTC by Sean-Der

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2018-02-15 08:58 UTC, fxcoudert commented
```
Undefined symbols for architecture x86_64:
  "_lzo1x_1_compress", referenced from:
      MsgChannel::writecompressed(unsigned char const*, unsigned long, unsigned long&) in libicecc.a(libicecc_la-comm.o)
  "_lzo1x_decompress", referenced from:
      MsgChannel::readcompressed(unsigned char**, unsigned long&, unsigned long&) in libicecc.a(libicecc_la-comm.o)
```

2018-02-15 08:58 UTC, fxcoudert commented on Formula/icemon.rb
> +  revision 1
No revision line

2018-02-15 08:59 UTC, fxcoudert commented on Formula/icemon.rb
> +  depends_on "icecream"
Alphabetical ordering among non-build deps

2018-02-15 08:59 UTC, fxcoudert requested changes

2018-02-15 08:59 UTC, fxcoudert commented on Formula/icemon.rb
> +end
This will need a functional test, in a `test do` block

2018-02-22 19:48 UTC, Sean-Der commented
@fxcoudert all green! thanks for the review

2018-02-26 01:08 UTC, Sean-Der commented
Hey @fxcoudert @ilovezfs anything else I need to do, no rush though!

thanks

2018-03-01 03:39 UTC, DomT4 commented on Formula/icemon.rb
> +    args = std_cmake_args
Just inline this below since you're not adding extra arguments.

2018-03-01 15:07 UTC, fxcoudert commented on Formula/icemon.rb
> +    system "make"
Can this be combined into a single `make install` line?

2018-03-02 22:06 UTC, Sean-Der commented
@BrewTestBot test this please

2018-03-03 15:28 UTC, fxcoudert approved these changes

2018-03-03 15:28 UTC, fxcoudert commented
Thanks @Sean-Der for the pull request and congrats on your first contribution to Homebrew!

2018-03-03 15:29 UTC, closed without merging