Update libswiften formula
Homebrew/homebrew-core pull request #24526
Opened 2018-02-25 18:22 UTC by vitalyster

* added devel build (4.0rc5)
* HEAD build is dropped because it produces incorrect version header

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-02-25 20:10 UTC, fxcoudert requested changes

2018-02-25 20:10 UTC, fxcoudert commented on Formula/libswiften.rb
> +  end
`sha256` missing here

2018-02-26 12:12 UTC, vitalyster commented
Fixed. Why it didn't catched by audit checks?

2018-02-26 14:09 UTC, fxcoudert approved these changes

2018-02-26 14:09 UTC, merged

2018-02-26 14:10 UTC, fxcoudert commented
Not sure exactly… thanks for the pull request!