Add vitess formula
Homebrew/homebrew-core pull request #24562
Opened 2018-02-26 15:05 UTC by arthurnn

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
### What is Vitess?
Vitess is a proxy on top of MySQL built by YouTube to add a sharding framework as well as other features on top of MySQL.
See http://vitess.io for more.

### What is in here?
This adds a formula to install vitess binaries.
Note 1: for now, I am pointing to a branch I have, until we figure out how we can vendor the libs into the project. see https://github.com/youtube/vitess/pull/3678
Note 2: Most of Vitess' users build it from Master, that's why I picked the latest SHA there. The latest version is 2.1.1 which is old. Soon we will release version 3. Once that gets released we can bump it here. Is it OK for now to run out of master?

### Which dependencies Vitess need?
It is a go project, so it needs Go to compile it.

cc @sougou
review @MikeMcQuaid

2018-02-26 15:11 UTC, MikeMcQuaid requested changes

2018-02-26 15:11 UTC, MikeMcQuaid commented on Formula/vitess.rb
> +  head "https://github.com/arthurnn/vitess.git"
Will need to wait until we have an official upstream tag before this gets merged but can review here before that.

2018-02-26 15:20 UTC, MikeMcQuaid commented on Formula/vitess.rb
> +  head "https://github.com/arthurnn/vitess.git"
Only CI failures relate to that too: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19280/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/audit_vitess___online___new_formula/

2018-02-26 15:20 UTC, MikeMcQuaid commented
> Is it OK for now to run out of master?

No, unfortunately this will need to be a stable, tagged release before we can include it into this Homebrew repository.

2018-03-01 14:55 UTC, fxcoudert commented
> for now, I am pointing to a branch I have, until we figure out how we can vendor the libs into the project

We will need to be able to compile from the main repo, not a fork.

2018-03-22 23:26 UTC, closed without merging