nest: migrate to homebrew/core
Homebrew/homebrew-core pull request #24908
Opened 2018-03-06 09:55 UTC by tammoippen

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Reopening #21561, as the upstream PR (https://github.com/nest/nest-simulator/pull/872) is now merged. (Sorry for the inconvenience of another PR - I messed up my fork.)

2018-03-06 12:03 UTC, tammoippen commented
Failure is because of `brew audit nest --online --new-formula`, as `patches` are required for building nest 2.14.0, as discussed here https://github.com/Homebrew/homebrew-core/pull/21561#issuecomment-351337535.

2018-03-27 13:42 UTC, tammoippen commented
Is there something blocking this PR?

2018-04-11 08:57 UTC, fxcoudert requested changes

2018-04-11 08:57 UTC, fxcoudert commented on Formula/nest.rb
> +  bottle do
No bottle block

2018-04-11 08:57 UTC, fxcoudert commented on Formula/nest.rb
> +  patch do
😢 patches… can upstream make a new release?

2018-04-11 08:57 UTC, fxcoudert commented on Formula/nest.rb
> +  option "with-python", "Build Python3 bindings (PyNEST) instead of Python2 bindings."
Let's choose a python version, and build it with no options. I recommend moving to python3.

2018-04-11 08:57 UTC, fxcoudert commented on Formula/nest.rb
> +  resource "Cython" do
We have formulas for python, numpy, scipy. Can we use those?

2018-05-24 09:49 UTC, fxcoudert commented
Thanks @tammoippen, I am going to close this pull request for now, but we'll be very happy to consider an updated PR that addresses the review comments and uses the next version of nest!

2018-05-24 09:49 UTC, closed without merging