jthread 1.3.3 (new formula)
Homebrew/homebrew-core pull request #25063
Opened 2018-03-09 18:26 UTC by njh

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The main reason for adding jthread to Homebrew, is so that I can also raise a PR for [JRTPLIB](https://github.com/j0r1/JRTPLIB) which depends upon the jthread library.

Note that `brew audit --strict` does not pass, because of passing a string with spaces into `system`, which is used in the test. The reason I have done this, is because one of the arguments is itself a string with spaces in it - so must be parsed by the shell.

I looked at doing this instead:
```ruby
libs = `pkg-config --libs jthread`.chomp.split
```

But it start getting complex/unreliable compared with just passing a single string to `system`.

Pointers to a better way of doing this would be very welcome.

2018-03-10 10:54 UTC, fxcoudert requested changes

2018-03-10 10:54 UTC, fxcoudert commented on Formula/jthread.rb
> +    libs = `pkg-config --libs jthread`.chomp
`pkg-config` is a build dep, so it's not there anymore for the test block. Just expand to the necessary arguments (`-I#{include} -L#{lib} -ljthread` or something like that)

2018-03-10 10:54 UTC, fxcoudert commented on Formula/jthread.rb
> +    system "#{ENV.cxx} test.cpp -o test #{libs} #{cflags}"
Once you've removed the temporary variables above, just separate the arguments here. See how `libogg` is doing it.

2018-03-17 17:37 UTC, njh commented
Thank you very much.

I thought it was good to invoke pkg-config to ensure that it was working correctly.

But specifying the linker parameters directly should work fine.

I will update the PR.

2018-03-18 21:59 UTC, fxcoudert approved these changes

2018-03-22 20:15 UTC, fxcoudert commented
@BrewTestBot test this please

2018-03-22 20:51 UTC, fxcoudert commented
Thanks @njh for your contribution to Homebrew!

2018-03-22 20:52 UTC, closed without merging