aws-es-proxy 0.8 (new formula)
Homebrew/homebrew-core pull request #25496
Opened 2018-03-20 06:24 UTC by dlackty

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2018-03-24 11:46 UTC, fxcoudert requested changes

2018-03-24 11:46 UTC, fxcoudert commented on Formula/aws-es-proxy.rb
> +  head "https://github.com/abutaha/aws-es-proxy.git"
No head for new formulas

2018-03-24 11:46 UTC, fxcoudert commented on Formula/aws-es-proxy.rb
> +      bin.install "aws-es-proxy"
No man, no doc?

2018-03-24 17:22 UTC, dlackty commented on Formula/aws-es-proxy.rb
> +  head "https://github.com/abutaha/aws-es-proxy.git"
Removed.

2018-03-24 21:29 UTC, fxcoudert approved these changes

2018-04-10 09:05 UTC, fxcoudert commented
@BrewTestBot test this please

2018-04-10 09:10 UTC, fxcoudert commented
@BrewTestBot test this please

2018-04-10 09:17 UTC, fxcoudert commented
Thanks @dlackty for the pull request!

2018-04-10 09:19 UTC, closed without merging

2018-04-10 09:44 UTC, dlackty commented
Thanks @fxcoudert and you mahjong avatar is cool!