Add apache-arrow-glib formula
Homebrew/homebrew-core pull request #25505
Opened 2018-03-20 10:29 UTC by itume

- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This pull request is Based on https://github.com/Homebrew/homebrew-core/pull/18590
I made some revisions, please check it out.

2018-03-20 10:40 UTC, tschoonj commented
The `gobject-introspection` should be `:build`. This will break the test though... probably better to just check for the presence of the `.typelib` and `.gir` files.

2018-03-20 10:45 UTC, tschoonj commented
You could also rewrite the test to compile and run a small test program that uses the C glib bindings (not the GObject Introspection bindings).

For inspiration have a look at e.g. `gtk+3`. Your test should be shorter though.

2018-03-20 12:11 UTC, itume commented
I try to fix test referencing gtk+3.rb. thank you for your code review.

2018-04-05 14:49 UTC, itume commented
>The gobject-introspection should be :build.
I think run-time dependency is more better. Because typical use of this library is using Apache Arrow via script language, such as Ruby. Would it be acceptable?

2018-04-05 15:00 UTC, tschoonj commented
No, over the past two weeks I have removed `gobject-introspection` everywhere as run-time dependency and kept it build-time only. Mainly to speed up building and testing on Jenkins, and because not everybody needs it anyway. This way the gir files get built, but if the user needs to use them, it is up to him/her to install the appropriate gir bindings for the language from where they need to be used. (e.g. `pygobject3`). Note that even the gir bindings won't always depend on `gobject-introspection`

2018-04-05 15:05 UTC, tschoonj requested changes

2018-04-05 15:05 UTC, tschoonj commented on Formula/apache-arrow-glib.rb
> +        GArrowArray *array;
Please put in a call to a method from the library. We need this to test for linker issues.

For example:

```c
GArrowNullArray *array = garrow_null_array_new(10);
```

2018-04-05 15:05 UTC, tschoonj commented on Formula/apache-arrow-glib.rb
> +  depends_on "gobject-introspection"
As mentioned before, please make `gobject-introspection` `:build`

2018-04-07 06:53 UTC, tschoonj approved these changes

2018-04-07 06:53 UTC, tschoonj commented
Thanks for your changes. Looks ready to merge to me

2018-04-10 05:52 UTC, closed without merging

2018-04-10 05:52 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @itume! Without people like you submitting PRs we couldn't run this project. You rock!