yara formula - add dotnet module option
Homebrew/homebrew-core pull request #25589
Opened 2018-03-21 14:22 UTC by nyx0

- [ x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I wasn't sure for this one, I let you decide which one is ok for you :)
`option "with-enable-dotnet"`
or
`option "with-dotnet"`

2018-03-24 13:06 UTC, fxcoudert requested changes

2018-03-24 13:06 UTC, fxcoudert commented on Formula/yara.rb
> +  option "with-enable-dotnet"
Given that it doesn't require an extra dependency, please make it default (with no option)

2018-03-24 15:53 UTC, nyx0 commented
good point! done :)

2018-03-24 21:23 UTC, fxcoudert requested changes

2018-03-25 09:22 UTC, fxcoudert approved these changes

2018-03-25 09:24 UTC, closed without merging