stellar-core: 9.2.0 (fix commit hash for tag)
Homebrew/homebrew-core pull request #25716
Opened 2018-03-25 02:58 UTC by superstructor

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Prior to this fix I get the following error trying to upgrade `stellar-core` to `9.2.0` via build from source:

```
==> Cloning https://github.com/stellar/stellar-core.git
Updating /Users/isaac/Library/Caches/Homebrew/stellar-core--git
==> Checking out tag v9.2.0
Error: v9.2.0 tag should be a8b6a9dcb6550ce652dc9f81bc92a28be7c9baf8
but is actually 7561c1d53366ec79b908de533726269e08474f77
```

With this fix I have verified that build from source completes successfully and `7561c1d53366ec79b908de533726269e08474f77` is the correct `v9.2.0` commit hash.

Thanks.

2018-03-25 09:18 UTC, fxcoudert commented
And 9.2.0 is still marked as pre-release. https://github.com/stellar/stellar-core/issues/1626

2018-03-27 14:09 UTC, fxcoudert requested changes

2018-03-27 14:09 UTC, fxcoudert commented on Formula/stellar-core.rb
>    head "https://github.com/stellar/stellar-core.git"
We will need a `revision 1` line before `head` please

2018-03-29 12:16 UTC, ilovezfs approved these changes

2018-03-29 13:31 UTC, fxcoudert approved these changes

2018-03-29 13:36 UTC, ilovezfs commented
Thanks @superstructor!

2018-03-29 13:36 UTC, closed without merging

2018-03-29 15:03 UTC, ilovezfs commented
@superstructor when you have a chance, please make sure your isaac AT xlm email that you're using for commits is associated with your GitHub account so that the contributor stats and search work properly. Thanks!

2018-03-29 19:54 UTC, superstructor commented
@ilovezfs @fxcoudert 

Thanks and apologies for the slow reply as I was on an international flight.

I have now associated the xlm email with my GitHub account.