dbus: Warn about Qt issues in a custom prefix
Homebrew/homebrew-core pull request #25715
Opened 2018-03-24 23:39 UTC by easyaspi314

Standard installations of Qt will not be able to find the dbus server if libdbus-1.dylib is not in /usr/local/lib, and it causes a rather confusing error message or crash.

If this isn't the case, a QDBus application will crash on `QDBusAbstractInterface::callWithArgumentList`, and running the `qdbus` command will throw `org.freedesktop.DBus.Error.Disconnected`.

Simply symlinking libdbus-1.dylib to /usr/local/lib appears to solve the problem.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-03-25 09:21 UTC, fxcoudert commented
Has this been reported upstream? Can we link to a description of the bug in Qt database?

2018-03-25 13:34 UTC, easyaspi314 commented
It hasn't been reported upstream, but I think this is not an issue Qt can fix.

2018-03-25 13:35 UTC, easyaspi314 commented
Whoops, misclick.

2018-03-25 16:58 UTC, fxcoudert commented
> It hasn't been reported upstream

Please report it upstream, and add a link here to the bug report

> I think this is not an issue Qt can fix

Qt works with lots of its libraries outside of `/usr/local` so there is absolutely no reason for it to require `libdbus` to be in a hardcoded path. It is definitely a bug.

2018-03-25 20:38 UTC, easyaspi314 commented
OK, so I experimented, and /usr/local/ is not hardcoded. It simply searches the `DYLD_LIBRARY_PATH`.

```
~ ❯❯❯ `brew --prefix qt`/bin/qdbus
Could not connect to D-Bus server: org.freedesktop.DBus.Error.Disconnected: Not connected to D-Bus server
~ ❯❯❯ export DYLD_LIBRARY_PATH="/Users/easyaspi/homebrew/opt/dbus/lib:$DYLD_LIBRARY_PATH"
~ ❯❯❯ `brew --prefix qt`/bin/qdbus
:1.12
org.freedesktop.DBus
```

2018-03-25 22:52 UTC, ilovezfs commented
There's no bug here. This is by design. We build `qt` with `-dbus-runtime` instead of `-dbus-linked` so that people can use `DYLD_LIBRARY_PATH` rather than recompiling qt. If you use the default prefix, setting `DYLD_LIBRARY_PATH` isn't needed since `/usr/local/lib` is in the default `DYLD_LIBRARY_PATH` path. Please see https://github.com/Homebrew/homebrew-core/pull/9232.

2018-03-25 22:55 UTC, easyaspi314 commented
So answer this. 

Why does Qt build from source if you don't have the default prefix? If I `--force-bottle` it and edit qt.conf, it appears to work fine.

2018-03-26 00:03 UTC, ilovezfs commented
You can run
```
brew install --build-bottle qt
brew bottle --debug --verbose qt
```
and it will show why.

2018-03-29 13:49 UTC, ilovezfs requested changes
Let's make `dbus` a hard dependency for `qt` and switch to `-dbus-linked`. We'll also need to bump the revision.

2018-04-26 20:52 UTC, closed without merging