mint 0.7.1 (new formula)
Homebrew/homebrew-core pull request #25734
Opened 2018-03-25 10:36 UTC by Lutzifer

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-03-25 17:00 UTC, fxcoudert requested changes

2018-03-25 17:00 UTC, fxcoudert commented on Formula/mint.rb
> +  depends_on :xcode
Looks to me like this requires Xcode 9 (or later), but only at build time. If so, the correct idiom is:

`depends_on :xcode => ["9.0", :build]`

2018-03-25 17:00 UTC, fxcoudert commented on Formula/mint.rb
> +  head "https://github.com/yonaskolb/Mint.git"
No head for new formulas

2018-03-25 17:00 UTC, fxcoudert commented on Formula/mint.rb
> +    system "#{bin}/mint"
We need a test that exercises the functionality of the software.

2018-03-25 18:58 UTC, Lutzifer commented
@fxcoudert Thanks for the fast feedback, I hope it now is as requested.

2018-03-28 11:49 UTC, fxcoudert submitted a review, later dismissed

2018-03-28 11:49 UTC, fxcoudert commented
Thanks @Lutzifer for your contribution to Homebrew!

2018-03-28 12:24 UTC, Lutzifer commented
We can revisit "testing by building" when https://github.com/yonaskolb/Mint/issues/46 is implemented.

2018-03-28 12:56 UTC, fxcoudert approved these changes

2018-03-28 13:50 UTC, Lutzifer commented
@fxcoudert thx for the support!

2018-03-28 16:03 UTC, fxcoudert commented
@BrewTestBot test this please

2018-03-28 17:40 UTC, closed without merging