php@5.6 5.6.34 (new formula)
Homebrew/homebrew-core pull request #25913
Opened 2018-03-29 10:48 UTC by SMillerDev

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Preliminary PR, it doesn't even build yet

2018-03-29 15:39 UTC, ilovezfs commented
@kabel @javian any thoughts here?

2018-03-29 17:38 UTC, kabel requested changes
Should we also add mcrypt here? It's also pretty high on the analytics.

2018-03-29 17:38 UTC, kabel commented on Formula/php@5.6.rb
> +      --with-tidy
Remove tidy

2018-03-29 23:10 UTC, ilovezfs commented
>Should we also add mcrypt here? It's also pretty high on the analytics.

yup

2018-03-31 01:43 UTC, kabel commented on Formula/php@5.6.rb
> +  url "https://php.net/get/php-5.6.34.tar.xz/from/this/mirror"
5.6.35 out now

2018-03-31 06:03 UTC, javian commented on Formula/php@5.6.rb
> +      --with-mysqli=mysqlnd
Can you also add `--with-mysql=mysqlnd` to enable the old mysql extension ?

2018-03-31 12:29 UTC, ilovezfs commented on formula_renames.json
> +  "php56": "php@5.6",
should be in alphabetical order

2018-03-31 23:15 UTC, kabel approved these changes

2018-04-01 04:12 UTC, closed without merging

2018-04-01 04:14 UTC, ilovezfs commented
Thanks again @SMillerDev! 🚀