kaitai-struct-compiler: use shipped launch wrapper
Homebrew/homebrew-core pull request #25967
Opened 2018-03-30 14:59 UTC by fridtjof

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-03-30 15:07 UTC, Adsada2205 approved these changes

2018-03-31 21:31 UTC, fridtjof commented
Here we go; Bintray was broken yesterday. Should be ready to merge now

2018-04-21 22:28 UTC, fridtjof commented
Can someone please look at this? My changes were approved, but never merged - the current recipe breaks a related tool on macOS using Homebrew as can be seen in the issue referenced

2018-05-08 12:15 UTC, GreyCat commented
This is still applicable and important change. Someone with commit rights to this repo, please merge in?

2018-05-16 09:32 UTC, fridtjof commented
As you can see [here](https://github.com/orgs/kaitai-io/people), @GreyCat is one of the main authors of the kaitai project (which includes both kaitai-struct-compiler and kaitai-struct-visualizer, which is relevant to this PR). He approved this change/fix, so can you please merge this?

2018-05-28 15:29 UTC, fridtjof commented
@Adsada2205 you approved this PR on Mar 30, can you merge it, please? I'd really appreciate it :)

2018-05-28 15:35 UTC, ilovezfs requested changes

2018-05-28 15:35 UTC, ilovezfs commented on Formula/kaitai-struct-compiler.rb
> +    inreplace bin/"kaitai-struct-compiler", /^declare -r lib_dir=.*$/, "declare -r lib_dir='#{libexec}'"
Why is the inreplace necessary? If we install kaitai-struct-compiler in `libexec/bin`, and then add a symlink in `bin` is the `inreplace` still needed?

2018-06-18 13:48 UTC, ilovezfs commented on Formula/kaitai-struct-compiler.rb
> +    inreplace bin/"kaitai-struct-compiler", /^declare -r lib_dir=.*$/, "declare -r lib_dir='#{libexec}'"
@fridtjof ping

2018-06-18 13:51 UTC, fridtjof reviewed
> Would lib.install Dir["lib/*"] work for this? I could not find documentation on this.

Would this work, like bin.install works?

Edit: oh snap, i hit the wrong reply button

2018-06-18 13:54 UTC, ilovezfs commented
Probably `libexec.install Dir["*"]` is what you want, followed by symlinking into `bin`.

2018-06-18 14:07 UTC, fridtjof commented
Like this? I tested it, and it works

2018-06-18 14:08 UTC, ilovezfs commented
yup. much better!

2018-06-18 14:08 UTC, ilovezfs approved these changes

2018-06-18 15:02 UTC, merged

2018-06-18 15:02 UTC, ilovezfs commented
Thanks again @fridtjof!