keepkey-agent 0.9.0 (new formula)
Homebrew/homebrew-core pull request #26258
Opened 2018-04-06 13:47 UTC by menteb

A hardware SSH and GPG agent for KeepKey. Thanks to Keepkey Agent SSH Agent administrators can now install this OpenSSH compatible agent easily and enjoy passwordless and secure authentication to their servers.

- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-04-07 06:19 UTC, ilovezfs requested changes
Can you explain the formula name please? The upstream repository is named "trezor-agent"

2018-04-07 10:41 UTC, menteb commented
Sure, it's part of that repository. See https://github.com/romanz/trezor-agent/blob/master/doc/INSTALL.md 

I already created the trezor-agent formula for Homebrew.

2018-04-28 22:07 UTC, menteb commented
No silly bot, this is open for review!

2018-04-28 22:16 UTC, cerebralmisfire reviewed
It's part of the trezor-agent repository, different binary.

2018-05-15 08:25 UTC, cerebralmisfire reviewed
@ilovezfs, can this move forward?

2018-05-24 10:04 UTC, ilovezfs approved these changes

2018-05-24 10:04 UTC, ilovezfs commented
@BrewTestBot test this please

2018-05-24 10:30 UTC, ilovezfs commented
Looks like the branch was deleted here, so I've opened https://github.com/Homebrew/homebrew-core/pull/28228
 as a replacement.

2018-05-24 10:30 UTC, closed without merging

2018-05-24 10:56 UTC, cerebralmisfire reviewed
Cheers

2018-05-24 10:58 UTC, ilovezfs commented
@menteb You're welcome. https://github.com/Homebrew/homebrew-core/pull/28228 shipped! Thanks for your contribution to Homebrew and sorry for the delay! Let me know if you see any problems with it. I dropped the libusb dep and tweaked the python resources to match `pip3 install keepkey_agent`