checkbashisms: replace hardcoded hashbang with env
Homebrew/homebrew-core pull request #26290
Opened 2018-04-07 10:31 UTC by Alhadis

## Checklist

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] ~~Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?~~ [Not necessary](https://github.com/Homebrew/homebrew-core/blob/1f9ba958e21dce9673b932cfc1f55dd155f0df69/Formula/checkbashisms.rb#L10), but confirmed by reinstalling and checking executable's source.
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

## Description

This PR fixes the interpreter directive of the `checkbashisms` script to use `env`, rather than a hardcoded path to `/usr/bin/perl`. This enables the Homebrew-installed version of Perl to be used instead of the system's version.

Running the system's version of Perl will cause breakage at startup if the user's installed Perl with compiled XS code:

~~~
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/johngardner/perl5/lib/perl5/darwin-thread-multi-2level/auto/Cwd/Cwd.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/johngardner/perl5/lib/perl5/darwin-thread-multi-2level/auto/Cwd/Cwd.bundle
  Expected in: flat namespace

Abort trap: 6
~~~

This can be solved by unsetting the `PERL5LIB` variable, which is set by code recommended by Homebrew's [caveat notes](https://github.com/Homebrew/homebrew-core/blob/1f9ba958e21dce9673b932cfc1f55dd155f0df69/Formula/perl.rb#L67-L75) for `perl`:

> By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.
>
> You can set that up like this:
>
> ~~~shell
> PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
> echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> ~/.bash_profile
> ~~~

I doubt upstream would be interested in accepting this fix, because the script is part of a tool-suite for Debian package maintainers. Ubuntu packages are installed to `/usr/bin` by default (not `/usr/local/bin` like macOS), which makes the fix redundant at best. At worst, it could introduce complications if maintainers are tinkering with the `env` utility, or doing something funky with `perl` binaries.

## Sidenote

Since the issue with installing modules with X codes technically affects every formula with hardcoded Perl hashbangs, it might be worth reviewing how many other formulae are affected by this.

2018-04-07 10:36 UTC, ilovezfs requested changes
In general, we actually prefer specific shebangs over anything-goes shebangs. @DomT4 any thoughts here on an alternative fix that lets us still stick with system Perl?

2018-04-07 10:39 UTC, Alhadis commented
> In general, we actually prefer specific shebangs over anything-goes shebangs.

Why? By convention, all `perl` executables use `#!/usr/bin/env perl` as a directive, and using hardcoded paths is generally considered bad practice.

2018-04-07 10:41 UTC, ilovezfs commented
So that packages are less likely to be broken by variations in the users' environments.

2018-04-07 10:45 UTC, Alhadis commented
In the case of packages which install other packages (in this case, Perl and CPAN modules), I think the risk of breakage is much higher – particularly when compiled, dynamically-linked code is involved...

2018-04-07 19:46 UTC, DomT4 commented
> This enables the Homebrew-installed version of Perl to be used instead of the system's version.

As a general rule we want to avoid this as broadly as possible. Unlike `python` there's no solid reason to start _absolutely_ forcing the use of Homebrew's `perl`, and over time the hassle that using the hashbang `#!/usr/bin/env perl` would cause leads down that path for the sake of sanity IMO. An alternative would be making our `perl` `keg_only` again but we've ruled that one out repeatedly.

> @DomT4 any thoughts here on an alternative fix that lets us still stick with system Perl?

I'll look into it. Might well be tomorrow at this point before I get the chance.

2018-04-08 15:57 UTC, DomT4 commented
A potential alternative: https://github.com/Homebrew/homebrew-core/pull/26319

2018-04-09 07:53 UTC, closed without merging

2018-04-09 07:54 UTC, ilovezfs commented
Thanks for the PR @Alhadis! I've merged #26319 which should handle this if you want to test it's OK now.