deark 1.4.5 (new formula)
Homebrew/homebrew-core pull request #26698
Opened 2018-04-16 21:09 UTC by jkap

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-04-16 21:17 UTC, jkap commented
I'm assuming GitHub is interpreting this as a binary because of how I have the test written (base64 gzip file that `deark` then parses). Is there a better way to handle this test? Wasn't sure what examples I should check for.

2018-04-16 23:51 UTC, woodruffw commented
> I'm assuming GitHub is interpreting this as a binary because of how I have the test written (base64 gzip file that deark then parses)

Yeah, that's *very* weird. Could you try formatting the testfile write like this?

```ruby
(testpath/"test.gz").write ::Base64.decode64 <<~EOS
  H4sICFwa1VoAA3Rlc3QgZmlsZS50eHQAY/BgSGXIAcJ8Bh0GBQYPIJ0LFEliKAKS5QyKAG68muMgAAAA
EOS
```

We use that style in `postgis`, which makes me think that this has happened before :slightly_smiling_face:

2018-04-16 23:54 UTC, woodruffw commented
Oh, it's because there are a whole bunch of ASCII NULs in the string you're comparing to:

![](https://thing-in-itself.net/u/xcZRsbOOGAg.png)

Those should probably be escaped as `\x00`.

2018-04-17 00:06 UTC, jkap commented
Looks like killing the null characters fixed it, not sure how I missed that before (or how they even got in there)

2018-04-17 00:12 UTC, woodruffw requested changes
Two small nits, but otherwise looks good!

2018-04-17 00:12 UTC, woodruffw commented on Formula/deark.rb
> +    file == "Hello, Homebrew!\n"
The `test` block runs assertions, so this should be:

```ruby
assert_match "Hello, Homebrew!", file
```

2018-04-17 00:12 UTC, woodruffw commented on Formula/deark.rb
> +    (testpath/"test.gz").write(Base64.decode64(<<~EOS
The syntax in https://github.com/Homebrew/homebrew-core/pull/26698#issuecomment-381785290 might be preferable, to avoid those dangling parens.

2018-04-17 15:41 UTC, woodruffw approved these changes

2018-04-17 15:45 UTC, woodruffw commented
Thanks @jkap, and congratulations on your first Homebrew PR! :tada:

2018-04-17 15:45 UTC, closed without merging