wine: remove screen-flickering patch
Homebrew/homebrew-core pull request #26779
Opened 2018-04-18 11:19 UTC by LinusU

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

As discussed in #26114, this removes the flickering patch from wine stable (3.0). We should hold of merging until we have confirmed that this works sans patch on 10.11 and 10.12.

Please help us test this using some known affected games ❤️ 

- Age of Empires 1
- Age of Empires 2
- Black and White 1
- Midtown Madness 2

```markdown
- OS Verison: **found under  > About this mac, e.g. macOS 10.13.4 (17E199)**
- Computer: **found under  > About this mac, e.g. MacBook Pro (Retina, 13-inch, Early 2015)**
- Built wine without patch: **yes**
- Game tested: **choose from above**
- Observed flickering: **yes/no**
```

You can install this unpatched version using:

```sh
brew install --build-from-source https://raw.githubusercontent.com/LinusU/homebrew-core/df366f138aa6033993a9fea4c1f6b988c91669c3/Formula/wine.rb
```

Here is a link to a (I think legal) abandonware copy of Black and White:

https://www.myabandonware.com/game/black-white-a33

2018-04-18 13:25 UTC, ilovezfs requested changes
pending user testing

2018-04-19 11:31 UTC, ilovezfs commented
@uyjulian @adunning @yurikoles @dholm @d235j please test this pull request if you have a chance.

2018-04-19 13:41 UTC, yurikoles commented
I see black screen in Black and White 1 with this PR and without it. But Age of Empires 2 runs well.

@LinusU could you also check for latest dependencies in this formula?

2018-04-19 14:02 UTC, LinusU commented
> I see black screen in Black and White 1 [...]

@yurikoles how did you install it? I used the pre-installed zip file from the site, and then I also got the same problem. I fixed it by running the `setup.bat` file with `wine` first, I think that it hooked up the registry or something...

> could you also check for latest dependencies in this formula?

Will do 👍

2018-04-21 08:44 UTC, LinusU commented
For an unrelated reason (https://bugs.winehq.org/show_bug.cgi?id=35721) I went back and tested Wine 1.7.5 with Black and White, and the flickering is not there. This reinforces my belief that this was fixed (accidentally or not) in a release of macOS. Still don't know which one though.

2018-05-12 11:50 UTC, adunning commented
Shall we remove the patch?

2018-05-15 11:26 UTC, fxcoudert commented
@adunning I'd rather we have confirmation on macOS 10.12 and 10.11 before we do that

2018-06-05 12:20 UTC, fxcoudert commented
There is indication from upstream () that the bug was fixed in macOS > 10.13.4, but possibly not for all hardware. We are going to keep it for now.

2018-06-05 12:20 UTC, closed without merging