cglm v0.4.3 (new formula)
Homebrew/homebrew-core pull request #26792
Opened 2018-04-18 19:44 UTC by recp

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`brew audit` doesn't work for me, it gives for any formula:
```bash
==> Installing or updating 'rubocop' gem
Error: Unable to resolve dependency: user requested 'json (= 2.1.0)'
```

2018-04-23 14:20 UTC, fxcoudert requested changes

2018-04-23 15:08 UTC, recp commented on Formula/cglm.rb
> +  desc "📽 Optimized OpenGL/Graphics Math (glm) for C"
Done.

2018-04-23 15:09 UTC, recp commented on Formula/cglm.rb
> +    system "sh", "./autogen.sh"
It don't work (for me) without "sh", I tried it and I got error from brew install.

2018-04-23 15:11 UTC, recp commented on Formula/cglm.rb
> +    system "make"
Since `make install` depends on `make` (I guess), I dropped `make` line, I tested it and build works.

2018-04-23 15:18 UTC, recp commented on Formula/cglm.rb
> +    system "./test"
If you means this; the output is (cross product of +X and +Y should produce +Z in right-handed coordinate system):
```bash
Vector (float3):
	|0.0000	0.0000	1.0000|
```

Also `cglm` has its own tests. I didn't run them here, actually I don't know how. For running **cglm** tests, `cmocka` library is required.

`make check` should run tests, but I checked other brew formulas I see simple tests like this, this is why I avoided to run `make check` and put simple test here.

What should I do?

2018-04-23 16:02 UTC, recp commented on Formula/cglm.rb
> +    system "./test"
I think I understand what you said, I checked the result with assert, and dropped print.

2018-04-27 12:18 UTC, recp commented on Formula/cglm.rb
> +    system "sh", "./autogen.sh"
After making `system "sh", "./autogen.sh"` to `system "./autogen.sh"`, I'm getting permission error:

Homebrew output:
```bash
==> ./autogen.sh
Failed to execute: ./autogen.sh
```

Debug mode:
```bash
bash-3.2$ ./autogen.sh
bash: ./autogen.sh: Permission denied
```

But if I give execute permission to `./autogen.sh` file like below, it works:
```bash
system "chmod +x ./autogen.sh"
system "./autogen.sh"
```

is this (chmod +x) allowed in formula? What should I do?

2018-04-30 13:28 UTC, fxcoudert approved these changes

2018-04-30 13:28 UTC, fxcoudert commented
@BrewTestBot test this please

2018-04-30 13:28 UTC, fxcoudert commented on Formula/cglm.rb
> +    system "sh", "./autogen.sh"
Please report the issue upstream

2018-04-30 13:33 UTC, ilovezfs requested changes

2018-04-30 13:33 UTC, ilovezfs commented on Formula/cglm.rb
> +  depends_on "pkg-config" => :build
The pkg-config dependency seems to be unneeded

2018-04-30 14:52 UTC, ilovezfs commented
@recp can you please post the issue link about autogen here? thanks!

2018-04-30 14:59 UTC, recp commented
@ilovezfs I'm sorry, I couldn't understand where to report or what to do now :( 

Should I create an issue about it in https://github.com/Homebrew/homebrew-core or https://github.com/Homebrew/brew ? I'm confused about upstream?

2018-04-30 16:04 UTC, ilovezfs commented
Upstream means https://github.com/recp/cglm/issues

That's how to get the executable bit set. Tell them the autogen.sh they have checked into source control is not set to be executable.

2018-04-30 18:06 UTC, recp commented
@ilovezfs I created an issue: https://github.com/recp/cglm/issues/50

Would it enough?

2018-05-01 01:08 UTC, ilovezfs commented
Yes :)

2018-05-01 07:18 UTC, ilovezfs approved these changes

2018-05-01 16:20 UTC, closed without merging

2018-05-01 16:45 UTC, recp commented
@fxcoudert, @ilovezfs thanks!

Can I close the issue I opened in upstream https://github.com/recp/cglm/issues/50? Manual build instructions are already placed in README and in docs: http://cglm.readthedocs.io/en/latest/build.html

2018-05-02 04:34 UTC, ilovezfs commented
@recp they'll close it once they've fixed it