entt 2.5.0 (new formula)
Homebrew/homebrew-core pull request #26947
Opened 2018-04-22 11:38 UTC by Kerndog73

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`EnTT` is a header-only, tiny and easy to use framework written in modern C++.
It was originally designed entirely around an architectural pattern called ECS that is used mostly in game development.

`brew audit entt` produces no output and `brew audit --strict entt` produces the following message:

```
Error: uninitialized constant FormulaAuditor::MissingFormula
Did you mean?  MissingApplyError
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:311:in `audit_formula_name'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:809:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:802:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:802:in `audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:124:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:120:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:120:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

That doesn't look good! Anyone know why this is happening?

2018-04-22 11:44 UTC, Kerndog73 commented
Looks like the bot is having exactly the same problem. What on earth is going on with that audit command?

2018-04-22 20:45 UTC, commitay commented
@BrewTestBot test this please

2018-04-23 14:17 UTC, fxcoudert requested changes

2018-04-23 14:17 UTC, fxcoudert commented on Formula/entt.rb
> +    system "true"
Hum, no.

We need a test that exercises the some of the functionality of the app. Write a simple C code that compiles with the headers and run it. See `mpfr` for example.

2018-04-23 14:17 UTC, fxcoudert commented on Formula/entt.rb
> +    include.install "src/entt"
Can we build and install the documentation too?

2018-04-23 14:29 UTC, Kerndog73 commented
Where do I install the docs?

2018-04-23 14:47 UTC, Kerndog73 commented
@fxcoudert I've made the changes you asked for but I'd like the docs to be optional. How do I do that?

2018-04-24 06:44 UTC, Kerndog73 commented
I think this formula is all done. I've included a test. I've included the docs. I made sure that the docs are optional so that people don't have to install `doxygen` and `cmake` to use the library.

I'm happy with it!

2018-04-24 07:01 UTC, commitay commented
> the docs are optional so that people don't have to install `doxygen` and `cmake` to use the library.

These are `:build` dependencies that won't be installed unless the user builds from source.

2018-04-24 07:13 UTC, Kerndog73 commented
This is a header-only library. What does build from source mean for a header-only library?

2018-04-24 07:53 UTC, ilovezfs commented
@Kerndog73 We rarely package any header-only libraries in https://github.com/Homebrew/homebrew-core, as they're best off being vendored into the projects that needs them. Thanks for the PR, nonetheless!

2018-04-24 07:53 UTC, closed without merging