yamllint 1.11.1 (new formula)
Homebrew/homebrew-core pull request #27042
Opened 2018-04-25 01:10 UTC by apeschel

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-04-25 17:33 UTC, apeschel commented
Apologies on the original broken build -- I did run `brew audit --strict`, but CI uses `brew audit --online --new-formula yamllint` which catches a few issues the former does not. It was be useful to have the documentation updated accordingly.

2018-04-25 21:21 UTC, fxcoudert requested changes

2018-04-25 22:59 UTC, apeschel commented on Formula/yamllint.rb
> +  depends_on "python@2"
@fxcoudert Didn't notice the python3 compatibility, nice catch.

2018-04-26 00:54 UTC, apeschel commented
@fxcoudert Thanks for the review -- I've made some changes corresponding to your requests.

2018-04-30 13:08 UTC, fxcoudert commented
Thanks @apeschel for your contribution! Merged with a slightly adjusted test block.

2018-04-30 13:08 UTC, fxcoudert approved these changes

2018-04-30 13:08 UTC, closed without merging