Add xidel
Homebrew/homebrew-core pull request #27149
Opened 2018-04-26 21:02 UTC by benibela

Add xidel

Not tested since I do not have a mac

- [+] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [+] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [-] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [?] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-04-26 22:27 UTC, paul-hammant commented
I can confirm this works for me via:

```
brew install https://raw.githubusercontent.com/benibela/homebrew-core/d6dedb62d78832db389ec1fe0903f2b509ebe1cc/Formula/xidel.rb
```

2018-04-26 23:55 UTC, woodruffw requested changes

2018-04-26 23:55 UTC, woodruffw commented on Formula/xidel.rb
> +  bottle :unneeded
You can remove this line (this formula builds binaries, and as such would benefit from a bottle).

2018-04-27 10:25 UTC, bfontaine commented on Formula/xidel.rb
> +      system "bash", "build.sh"
`system "./build.sh"` should be enough.

2018-04-27 10:26 UTC, bfontaine commented on Formula/xidel.rb
> +  depends_on "bash"
Is this really necessary?

2018-04-28 17:04 UTC, woodruffw approved these changes

2018-05-02 15:56 UTC, fxcoudert commented
Thanks @benibela for the pull request!

2018-05-02 15:57 UTC, closed without merging