add plv8 formula
Homebrew/homebrew-core pull request #27337
Opened 2018-05-01 17:36 UTC by JerrySievert

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-05-01 18:39 UTC, JerrySievert commented
it appears that the test failure is due to permissions/ownership of the extensions directory for postgres

2018-05-02 09:51 UTC, fxcoudert requested changes
```
  * C: 4: col 3: Use GitHub tarballs rather than zipballs (url is https://github.com/plv8/plv8/archive/v2.3.3.zip).
  * C: 11: col 12: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 17: col 17: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 17: col 25: "Formula.factory(name)" is deprecated in favor of "Formula[name]"
  * C: 17: col 41: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 17: col 60: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * Use `system "make", "install"` instead of `system "make install"` 
  * Use `system "make", "installcheck"` instead of `system "make installcheck"` 
```

2018-05-02 09:51 UTC, fxcoudert commented on Formula/plv8.rb
> +    system "make"
`make` appears to be downloading v8 and building it. This needs to depend on our v8 formula, not rebuild it.

2018-05-02 09:51 UTC, fxcoudert commented on Formula/plv8.rb
> +    ENV.prepend 'PATH', Formula.factory('postgresql').bin, ':'
`ENV.prepend_path`

2018-05-02 10:31 UTC, JerrySievert commented
forced revert back to audited version.

please see my note re: v8, and why the Homebrew package will not work.

2018-05-02 10:31 UTC, JerrySievert commented on Formula/plv8.rb
> +  desc " V8 Engine Javascript Procedural Language add-on for PostgreSQL"
fixed due to audited version revert

2018-05-11 17:09 UTC, JerrySievert commented
any updates on this?

2018-05-11 17:29 UTC, JerrySievert commented
the v8 team has specifically stated that they no longer support building a shared library, and that it should not be built as one, nor is it supported in the `ninja` build system.

see: https://twitter.com/bmeurer/status/960584003148505088

I'm confused as to why this is an issue with `plv8`, which requires `v8` to be built, not able to use the Homebrew provided `v8`, but not an issue with `node`, which requires `v8` to be built, not able to use the Homebrew provided `v8`?

2018-05-11 17:58 UTC, JerrySievert commented
I can package the `v8` source as part of the `plv8` source, but would not want to do that until a `3.0` release.

2018-06-01 18:26 UTC, benjie commented
Not stale.

2018-06-29 19:20 UTC, closed without merging

2018-06-29 20:46 UTC, benjie commented
😔

2018-06-29 20:50 UTC, JerrySievert commented
yup, I was wondering about that.

in the mean time, `plv8` 3.0.0 is under active development against `v8` 6.8, which isn't backward compatible with 6.4, but has `BigInt` support.

still wondering how `node` can bundle, but this can't.

2018-06-29 22:19 UTC, benjie commented
Well, keep up the good work - it’s really easy to install PLv8 from your repo now so the need for brew is diminished 👍