viro 1.0.0 new formula
Homebrew/homebrew-core pull request #27339
Opened 2018-05-01 19:45 UTC by LeonardoJPerez

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-05-02 09:48 UTC, fxcoudert requested changes

2018-05-02 09:48 UTC, fxcoudert commented on Formula/viro.rb
> +  url "https://s3.amazonaws.com/mesh-homebrew/viro"
URL says “access denied”

2018-05-02 09:48 UTC, fxcoudert commented on Formula/viro.rb
> +    bin.install "viro"
Is this a single script?

2018-05-02 09:48 UTC, fxcoudert commented on Formula/viro.rb
> +    system bin/"viro", "--version"
We need a test that exercises the some of the functionality of the app.

2018-05-03 20:14 UTC, LeonardoJPerez commented on Formula/viro.rb
> +  url "https://s3.amazonaws.com/mesh-homebrew/viro"
Oops, thanks!

2018-05-03 20:15 UTC, LeonardoJPerez commented on Formula/viro.rb
> +    bin.install "viro"
Yes.

2018-05-04 10:35 UTC, fxcoudert commented
```
$ file ~/Downloads/viro 
/Users/fx/Downloads/viro: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

This looks like a Linux binary. Homebrew is for macOS software, that builds from source. I am closing the pull request for now, please open a new one once you have a formula that builds from source.

2018-05-04 10:35 UTC, closed without merging