Remove reference to dead repository
Homebrew/homebrew-core pull request #27460
Opened 2018-05-03 15:03 UTC by josegonzalez

The homebrew/homebrew-php tap is dead, so the issue template shouldn't reference it.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-05-04 06:04 UTC, SMillerDev approved these changes

2018-05-04 17:41 UTC, JCount commented
Maybe use something like:
`If it's a problem with a formula that isn't official, please file this issue at its third party tap rather than here.`

Hmmm. That's still not worded very well. 🤔

2018-05-24 11:59 UTC, fxcoudert commented
Good idea, but now conflits as the template has moved.

2018-06-21 13:11 UTC, ilovezfs requested changes
the reference moved to https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md

2018-06-21 15:03 UTC, closed without merging

2018-06-21 15:03 UTC, josegonzalez commented
Closing as I don't have time to update this :( Sorry!

2018-06-21 15:04 UTC, ilovezfs commented
No problem. Thanks for pointing it out.