cctools 895
Homebrew/homebrew-core pull request #27524
Opened 2018-05-05 22:40 UTC by al3xtjames

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR depends on https://github.com/Homebrew/formula-patches/pull/239; the placeholder patches (gists) will be replaced once it is merged.

2018-05-14 01:05 UTC, mistydemeo commented
@BrewTestBot test this please

2018-05-14 01:05 UTC, mistydemeo approved these changes

2018-05-14 02:40 UTC, mistydemeo commented
Hm, looks like the test is failing due to a missing executable:

```
        Testing cctools
/usr/bin/sandbox-exec -f /tmp/homebrew20180514-94286-1s1tnzi.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cctools.rb --verbose
==> /usr/local/Cellar/cctools/895/bin/otool -L /usr/local/Cellar/cctools/895/bin/install_name_tool
fatal error: /usr/local/Cellar/cctools/895/bin/otool: can't find or exec: /usr/local/Cellar/cctools/895/bin/llvm-objdump (No such file or directory)
fatal error: /usr/local/Cellar/cctools/895/bin/otool: internal objdump command failed
Error: cctools: failed
<0> expected but was
<1>.
```

2018-05-14 02:41 UTC, mistydemeo requested changes
Hm, looks like the test is failing due to a missing executable:

```
        Testing cctools
/usr/bin/sandbox-exec -f /tmp/homebrew20180514-94286-1s1tnzi.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cctools.rb --verbose
==> /usr/local/Cellar/cctools/895/bin/otool -L /usr/local/Cellar/cctools/895/bin/install_name_tool
fatal error: /usr/local/Cellar/cctools/895/bin/otool: can't find or exec: /usr/local/Cellar/cctools/895/bin/llvm-objdump (No such file or directory)
fatal error: /usr/local/Cellar/cctools/895/bin/otool: internal objdump command failed
Error: cctools: failed
<0> expected but was
<1>.
```

2018-05-14 02:45 UTC, al3xtjames commented
There appears to be two issues here:
 - cctools-895 always has `-DLLVM_OTOOL` defined, so it will always assume otool from LLVM is available (shoud only be done if `--with-llvm` is specified)
 - cctools-895 tries to launch `llvm-objdump` from its current path; this should probably be patched the Homebrew prefix

I'll work on patching this soon.

2018-06-04 02:34 UTC, al3xtjames commented
Apologies for the delay. Updated the commit, cctools' version of `otool` should now function (with and without LLVM).

2018-06-04 03:37 UTC, mistydemeo commented
Thanks! Looks like it worked on 10.12 and 10.13, but I'm seeing a 10.11 failure:

```
        Testing cctools
/usr/bin/sandbox-exec -f /tmp/homebrew20180604-99902-1lew18o.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cctools.rb --verbose
==> /usr/local/Cellar/cctools/895/bin/otool -L /usr/local/Cellar/cctools/895/bin/install_name_tool
fatal error: /usr/local/Cellar/cctools/895/bin/otool: can't find or exec: @@LLVM_BINDIR@@/llvm-objdump (No such file or directory)
fatal error: /usr/local/Cellar/cctools/895/bin/otool: internal objdump command failed
Error: cctools: failed
<0> expected but was
<1>.
```

2018-06-04 14:26 UTC, al3xtjames commented
Updated the `objdump` path (`/Library/Developer/CommandLineTools/usr/bin/objdump`) to fix the 10.11 failure (still works on 10.12/10.13). Is it OK to hardcode the CommandLineTools path?

2018-06-05 04:01 UTC, mistydemeo requested changes

2018-06-05 04:01 UTC, mistydemeo commented on Formula/cctools.rb
> +      url "https://gist.githubusercontent.com/al3xtjames/ac4096fa2508af7024ba410fef67b9df/raw/5d601f9508e39249220ab7cd2b4fb310087c4969/cctools-895-otool-objdump-path.diff"
How about setting this to a placeholder string, like `@@CLT_BINDIR@@`, that you can then `inreplace` within the formula? e.g.

```ruby
inreplace "otool/main.c", "@@CLT_BINDIR@@", "#{MacOS.active_developer_dir}/usr/bin"
```

2018-06-05 06:21 UTC, mistydemeo commented
I guess those tools aren't actually shipped in Xcode's SDKs. Sorry for the bad suggestion. :/ Maybe just `/usr/bin/objdump`?

2018-06-05 14:46 UTC, al3xtjames commented
IIRC `/usr/bin/objdump` was present in 10.12 and 10.13, but not 10.11, while `/Library/Developer/CommandLineTools/usr/bin/objdump` is present on all three.

2018-06-06 15:58 UTC, al3xtjames commented
Kept the` CLT_BINDIR` patch in the latest patchset, but changed the formula to replace it with `/Library/Developer/CommandLineTools/usr/bin/objdump`.

2018-06-06 16:39 UTC, al3xtjames commented
Added some more patching to fix cctools' version of `as` (needs a fixed path to `clang`).

2018-06-08 05:19 UTC, mistydemeo reviewed
Thanks so much for making that change!

Right now this has introduced a CLT dependency. That's maybe an acceptable compromise, but should get marked as `depends_on :clt` if so. Maybe we can add that dependency for 10.7 through 10.11, and depend on the versions in `/usr/bin` or `"#{MacOS::Xcode.prefix}/Toolchains/XcodeDefault.xctoolchain/usr/bin"` for 10.12+?

Sorry to add complexity!

2018-06-08 10:08 UTC, ilovezfs commented
```
depends_on :clt
```
Does that exist?

2018-06-09 17:31 UTC, al3xtjames commented
`depends_on :clt`

It looks like this was removed recently (in https://github.com/Homebrew/brew/commit/cffa5a9864e771f19231537b812b9b32a1160be0):

```
Error: Calling 'depends_on :clt' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cctools.rb:33:in `<class:Cctools>'
```

2018-07-17 18:52 UTC, mistydemeo commented
@ilovezfs Custom requirement for this one formula, maybe? Given it's a part of Apple's developer tools, it makes sense to me that this one formula will have weird angles that we don't otherwise want.

2018-07-17 23:06 UTC, ilovezfs commented
Is it also possible to build with Xcode only? If so, I think we should use `pour_bottle? do` as in the gcc formula, and in the source build case make the Xcode-only tweaks if without CLT.

2018-08-14 23:12 UTC, closed without merging