kcov 35 (new formula)
Homebrew/homebrew-core pull request #27520
Opened 2018-05-05 14:51 UTC by palfrey

Add the kcov code coverage tool

-----
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2018-05-09 10:16 UTC, fxcoudert requested changes

2018-05-09 10:16 UTC, fxcoudert commented on Formula/kcov.rb
> +  depends_on "bash" => :build
`bash` not needed.
Insert blank line before first `depends_on`

2018-05-09 10:16 UTC, fxcoudert commented on Formula/kcov.rb
> +    system "cmake", "-G", "Unix Makefiles", "-DCMAKE_INSTALL_PREFIX=#{prefix}", "."
`system "cmake", "-G", "Unix Makefiles", *std_cmake_args`

2018-05-09 10:16 UTC, fxcoudert commented on Formula/kcov.rb
> +      "@rpath/LLDB.framework/LLDB",
Alignt to the parenthesis.

2018-05-09 10:16 UTC, fxcoudert commented on Formula/kcov.rb
> +   system "#{bin}/kcov", "--version"
We need a test that exercises the some of the functionality of the app.

2018-05-30 13:25 UTC, closed without merging

2018-05-31 09:48 UTC, palfrey commented
@fxcoudert Thanks. I think I've addressed everything in #28505