Add @HowardHinnant date library
Homebrew/homebrew-core pull request #27621
Opened 2018-05-08 19:04 UTC by cdalvaro

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

This formula is for @ HowardHinnant date library
-----

2018-05-09 07:55 UTC, fxcoudert requested changes

2018-05-09 07:55 UTC, fxcoudert commented on Formula/date.rb
> +  option "without-shared", "Build a static version of library"
No options for new formulas. Please choose the “most common” feature set that users will want, and restrict to that.

2018-05-09 07:55 UTC, fxcoudert commented on Formula/date.rb
> +    system "make", "-j#{ENV.make_jobs}"
Let Homebrew handle the `-j` stuff.

2018-05-09 07:55 UTC, fxcoudert commented on Formula/date.rb
> +    system "make", "install"
`make install` is probably working without doing a separate `make`

2018-05-09 07:55 UTC, fxcoudert commented on Formula/date.rb
> +      static_assert(std::is_same<decltype(date::last), const date::last_spec>{}, "");
Is this a header-only library? If not, we need to check that it links.

2018-05-10 09:52 UTC, ilovezfs submitted a review, later dismissed
this'll need a far less generic name

2018-05-10 14:24 UTC, fxcoudert requested changes

2018-05-10 18:38 UTC, cdalvaro commented on Formula/cppdate.rb
> +    custom_cmake_args = ["-DENABLE_DATE_TESTING=OFF",
Done!

2018-05-10 18:38 UTC, cdalvaro commented on Formula/cppdate.rb
> +  desc "C++11/14/17 library for Date and Time operations based on <chrono>"
Done!

2018-05-10 18:38 UTC, cdalvaro commented on Formula/cppdate.rb
> +class Cppdate < Formula
Done!

2018-05-12 22:14 UTC, cdalvaro reviewed
All requested changes have been performed

2018-05-20 17:55 UTC, cdalvaro commented
ping @fxcoudert @ilovezfs

2018-05-22 21:03 UTC, cdalvaro reviewed
I did all requested changes:

* [x] No options for new formulas
* [x] Let Homebrew handle the `-j` stuff
* [x] Combine `make all` and `make install`
* [x] Modified the test to link against the installed library
* [x] Changed formula name to `HowardHinnant-Date`

2018-05-23 17:10 UTC, fxcoudert approved these changes

2018-05-24 08:06 UTC, fxcoudert commented
Thanks @cdalvaro for the pull request!

2018-05-24 08:06 UTC, closed without merging