Allow `--with-posix` for mingw-w64
Homebrew/homebrew-core pull request #27687
Opened 2018-05-10 06:53 UTC by angerman

Cross compiling software that uses c++11 features like `<mutex>`, ... require that libgcc has a pthreads library available, as the win32 library is not sufficient enough.

Fixes #21839, #21706

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-05-10 11:48 UTC, fxcoudert requested changes

2018-05-10 11:48 UTC, fxcoudert commented on Formula/mingw-w64.rb
> +  option "without-i686", "Compile without support for 32bit"
`without-i686` and `without-x86_64` are out of the question. We want to provide a feature-full experience (no build from source) for as many users as possible.

2018-05-10 11:50 UTC, fxcoudert commented
- What would be the downside to forcing (no option) posix threads?
- What thread option is upstream using in their own binaries?

2018-05-11 02:34 UTC, angerman commented
@fxcoudert forcing posix threads will result in needing to ship libwinpthreads alongside the application. This might or might not be favorable. 

There are no official binary distributions at http://mingw-w64.org/doku.php/download
The macports one does enable posix though: https://github.com/macports/macports-ports/blob/master/cross/x86_64-w64-mingw32-gcc/Portfile#L74

Apparently some distributions package both with `-win32` and `-posix` suffixes.

2018-05-15 02:08 UTC, angerman commented
@fxcoudert how this now?

2018-05-15 09:05 UTC, fxcoudert approved these changes

2018-05-15 09:06 UTC, merged

2018-05-15 09:06 UTC, fxcoudert commented
Thanks @angerman for the pull request!

2018-05-15 09:13 UTC, angerman commented
awesome!