new capstone requires pkg-config for build
Homebrew/homebrew-core pull request #27959
Opened 2018-05-17 04:49 UTC by stephengroat

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-05-17 14:38 UTC, stephengroat commented
@BrewTestBot test this please

2018-05-24 10:34 UTC, fxcoudert requested changes

2018-05-24 10:34 UTC, fxcoudert commented on Formula/capstone.rb
> +  depends_on "pkg-config" => :build
Only for `head` please

2018-05-24 12:50 UTC, fxcoudert approved these changes

2018-05-24 12:50 UTC, merged

2018-05-24 12:50 UTC, fxcoudert commented
Thanks @stephengroat