soundpipe 1.7.0 (new-formula)
Homebrew/homebrew-core pull request #28089
Opened 2018-05-22 03:15 UTC by gabcoh

Add a formula for the soundpipe library at
https://github.com/PaulBatchelor/soundpipe/
The library is installed just by make and make install

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-05-22 18:45 UTC, fxcoudert requested changes

2018-05-22 18:45 UTC, fxcoudert commented on Formula/soundpipe.rb
> +  depends_on "libsndfile"
Blank line before `depends_on`

2018-05-22 18:45 UTC, fxcoudert commented on Formula/soundpipe.rb
> +    system "make", "install", "PREFIX="+prefix
`PREFIX=#{prefix}`

2018-05-22 18:45 UTC, fxcoudert commented on Formula/soundpipe.rb
> +    system "cd #{prefix}/test;#{prefix}/test/run.bin"
Please check the output with `assert_match` and `shell_output`.

2018-05-22 18:45 UTC, fxcoudert commented on Formula/soundpipe.rb
> +    cp_r "test", prefix
tests and examples should be installed to `pkgshare`.

2018-05-22 18:45 UTC, fxcoudert commented on Formula/soundpipe.rb
> +    system "cd #{prefix}/test;#{prefix}/test/run.bin"
Another option would be to compile and link a simple C app, if the project ships a library.

2018-05-22 20:09 UTC, gabcoh commented
Sorry for the newbie question but how should I make these changes? Just with another commit in my branch or make a new pull request?

2018-05-23 17:14 UTC, fxcoudert approved these changes

2018-05-24 08:06 UTC, fxcoudert commented
Thanks @gabcoh for the pull request!

2018-05-24 08:06 UTC, closed without merging