bitwarden 1.0.0 (new formula)
Homebrew/homebrew-core pull request #28201
Opened 2018-05-24 00:38 UTC by kspearrin

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-05-26 20:41 UTC, DomT4 commented
Wondering if this should be called `bitwarden-cli` to make it clear it's not installing the same thing as the `bitwarden` cask.

2018-05-26 20:49 UTC, kspearrin commented
I could rename it if you think that makes more sense. Our choco package is called `bitwarden-cli` since we already have `bitwarden` for our desktop app there too.

2018-05-26 20:49 UTC, kspearrin commented on Formula/bitwarden.rb
> +    assert_equal "1.0.0\n", shell_output("#{bin}/bw -v")
Bitwarden is an online password manager that is powered by a server. You would need to register an account.

2018-05-26 21:18 UTC, kspearrin commented
Now that I think about it more, I think it would be good to be called `bitwarden-cli` to be more consistent with other packages that we distribute. Renamed.

2018-05-26 21:28 UTC, kspearrin commented on Formula/bitwarden.rb
> +    assert_equal "1.0.0\n", shell_output("#{bin}/bw -v")
Good call. Updated to assert `version.to_s + "\n"`

2018-05-26 21:47 UTC, DomT4 commented on Formula/bitwarden.rb
> +    assert_equal "1.0.0\n", shell_output("#{bin}/bw -v")
If you use `assert_match` rather than `assert_equal` it'll let you off the newline.

2018-05-27 12:15 UTC, ilovezfs commented on Formula/bitwarden-cli.rb
> +    assert_equal version.to_s + "\n", shell_output("#{bin}/bw -v")
The test needs to exercise and verify the functionality of the software. Something that saves and returns a password would be good

2018-05-27 12:16 UTC, ilovezfs requested changes
see comment on test block

2018-05-27 12:58 UTC, ilovezfs commented on Formula/bitwarden-cli.rb
> +    testingb64 = pipe_output("#{bin}/bw encode", "Testing")
add a `, 0` to assert the exit code is 0 too

2018-05-27 12:59 UTC, ilovezfs commented on Formula/bitwarden-cli.rb
> +    assert_match version.to_s, version
we don't need this test since you've added the better test

2018-05-27 13:00 UTC, ilovezfs commented on Formula/bitwarden-cli.rb
> +    assert_equal 10, password.strip.length
is it only a single newline? I'd just use `.chomp`

2018-05-27 13:02 UTC, ilovezfs commented
so probably
```
    assert_equal 10, shell_output("#{bin}/bw generate --length 10").chomp.length
    assert_match "VGVzdGluZw==", pipe_output("#{bin}/bw encode", "Testing", 0)
```

2018-05-27 13:03 UTC, ilovezfs commented on Formula/bitwarden-cli.rb
> +    assert_equal 10, password.chomp.length, 0
sorry I meant as 3rd arg on pipe_output. a 3rd arg to assert_equal is for a custom failure message

2018-05-27 13:03 UTC, kspearrin commented
@ilovezfs Done

2018-05-27 13:08 UTC, ilovezfs commented
```
    assert_equal 10, shell_output("#{bin}/bw generate --length 10").chomp.length

    output = pipe_output("#{bin}/bw encode", "Testing", 0)
    assert_equal "VGVzdGluZw==", output.chomp
```

2018-05-27 13:10 UTC, ilovezfs approved these changes

2018-05-27 13:32 UTC, closed without merging

2018-05-27 13:33 UTC, ilovezfs commented
Thanks for your first contribution to Homebrew, @kspearrin! Without people like you submitting PRs we couldn't run this project. You rock!