pgloader added AWS RedShift support and now depends on zs3.
Homebrew/homebrew-core pull request #28602
Opened 2018-06-02 22:45 UTC by richardkmichael

pgloader now depends on zs3, add it (and its dependencies as well).

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-06-03 00:30 UTC, ilovezfs requested changes
Unless the build fails without these, they're very likely to be dropped the next time the formula is updated. Can you add something in the `test do` block that verifies the relevant functionality made it into the program?

2018-06-03 01:02 UTC, richardkmichael commented
@ilovezfs 

Why will they be dropped?

There is a previous PR/commit which modifies the resource stanzas: #24183

I was wondering if there is an automated tool generating all the required resource stanzas which I should be updating and using.  I was intending to ask the author of the above PR about this later.

2018-06-03 02:06 UTC, richardkmichael commented
@ilovezfs 

Sorry, I should have pointed out, the `--HEAD` build will fail with a dependency error, which is how I discovered the problem.  So the next time pgloader is released, the stable build will break.

```
# Using current master branch `pgloader.rb` formula
$ brew install --HEAD pgloader
# ...snip
==> make pgloader-standalone BUILDAPP=buildapp
Last 15 lines from /Users/richardmichael/Library/Logs/Homebrew/pgloader/01.make:
pgloader-standalone
BUILDAPP=buildapp

buildapp    --require sb-posix --require sb-bsd-sockets --require sb-rotate-byte                        \
                       --sbcl sbcl                            \
                       --load-system pgloader               \
                       --load src/hooks.lisp                   \
                       --entry pgloader:main                   \
                       --dynamic-space-size 4096         \
                       --compress-core                    \
                       --output build/bin/pgloader
;; loading system "pgloader"
Fatal MISSING-DEPENDENCY:
  Component #:ZS3 not found, required by #<SYSTEM "pgloader">
make: *** [pgloader-standalone] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

```

2018-06-24 19:02 UTC, richardkmichael commented
@ilovezfs Marked stale... but the next stable release will fail to build, just as the `--HEAD` release does now (without these changes); i.e. when `HEAD` becomes stable.

What should I do / how to help?

(Or, close this, wait until stable fails to build, then re-open this and merge it.  Though, I guess this closed MR will be lost and someone will just reproduce the same work.)

2018-07-15 21:37 UTC, richardkmichael commented
No longer necessary since 3c0c4c3 updated the formula to pgloader 3.5.2 and quicklisp-homebrew-roundup updated the resources.

2018-07-15 21:37 UTC, closed without merging

2018-07-16 07:08 UTC, ilovezfs commented
@richardkmichael Sorry I hadn't merged this! Thanks for the PR nonetheless ❤️