folly: build using cmake + simplify use from cmake
Homebrew/homebrew-core pull request #29219
Opened 2018-06-20 00:44 UTC by paulrosania

When built via cmake, folly provides a folly-config.cmake file, which greatly simplifies linking against folly via cmake, by making cmake's `find_package` work automatically. Homebrew currently builds folly using its autoreconf flow, so the cmake config files are not installed.

This PR updates folly to build using cmake instead of autoreconf, properly installing the cmake config files and enabling automatic `find_package` use.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2018-06-20 05:14 UTC, ilovezfs requested changes
Before
```
iMac-TMP:~ joe$ ls /usr/local/Cellar/folly/2018.06.18.00/lib
libfolly.57.dylib		libfollybenchmark.dylib		libfollylogging.a
libfolly.a			libfollyinit.57.dylib		libfollylogging.dylib
libfolly.dylib			libfollyinit.a			pkgconfig
libfollybenchmark.57.dylib	libfollyinit.dylib
libfollybenchmark.a		libfollylogging.57.dylib
```
After
```
iMac-TMP:~ joe$ ls /usr/local/Cellar/folly/2018.06.18.00/lib
cmake			libfolly.a		libfollybenchmark.a
iMac-TMP:~ joe$ 
```

So we'll need to make sure that
a) the shared libraries are still built (none of the dylb were built)
b) we don't lose some of the libraries (where'd libfollyinit go? where'd libfollylogging go?)
c) the pkgconfig file is still installed
d) the revision is bumped if the libraries version number changes due to switch to cmake (almost always happens)

2018-06-20 18:15 UTC, paulrosania commented
Thanks! Will take a look.

2018-06-20 22:35 UTC, paulrosania commented
I did some digging around, and it looks like it's not going to be possible to match the previous output when building with cmake – or at least it is beyond my ability.

On (a): folly does not offer targets for shared libraries, so you need to reconfigure the entire build to *only* build shared, and the maintainers actively discourage dynamic linking due to ABI changes (https://github.com/facebook/folly/blob/master/CMakeLists.txt#L35-L40).
On (b): it seems libfollyinit / libfollylogging are deliberate exclusions which may be removed from the autoreconf build also. (See https://github.com/facebook/folly/pull/871#issuecomment-398229566)
On (c): this is the most approachable; it probably could be fixed with an upstream change.

What is the recommended approach here? Should I give up? 🙁

2018-06-24 16:40 UTC, ilovezfs commented
On (a) It's acceptable to build 2x. We do this in lots of formulae. See https://github.com/Homebrew/homebrew-core/pulls?utf8=✓&q=is%3Apr+static+is%3Aclosed+author%3Ajeroen

On (b) OK I guess we can ignore that difference.

On (c) yes that should be addressed via an upstream change.

2018-07-22 18:35 UTC, closed without merging