Update live.gnome.org URLs
Homebrew/homebrew-core pull request #29625
Opened 2018-07-01 22:18 UTC by slokhorst

This domain was retired a few years ago.

Most pages now redirect to wiki.gnome.org

2018-07-04 18:40 UTC, ilovezfs requested changes
please make this one commit per formula

e.g.
```
gobject-introspection: update homepage
```

2018-07-05 14:58 UTC, slokhorst commented
@ilovezfs done.

2018-07-05 15:05 UTC, ilovezfs approved these changes

2018-07-05 15:05 UTC, merged

2018-07-05 15:07 UTC, ilovezfs commented
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @slokhorst!