llvm: add Xcode CLT notice
Homebrew/homebrew-core pull request #29690
Opened 2018-07-03 09:06 UTC by DesWurstes

Because I didn't want to use Apple's outdated things, I didn't have Xcode CLT installed. I installed LLVM, it said "can't find stdio.h". I built LLVM, the same error. I built LLVM with --with-toolchain, the same error. Installing Xcode CLT later solved the issue.

2018-07-04 18:38 UTC, ilovezfs requested changes
Let's use the same messaging as the gcc formula

2018-07-13 01:02 UTC, cigoic commented
hi,

I encountered the same issue. Solved it via resetting Xcode: https://github.com/Homebrew/homebrew-core/issues/20791

`sudo xcode-select -r`

2018-08-03 06:29 UTC, DesWurstes commented
Done

2018-08-08 09:29 UTC, fxcoudert approved these changes

2018-08-08 10:47 UTC, merged