chakra: add options for including dynamic library and disabling LTO
Homebrew/homebrew-core pull request #29744
Opened 2018-07-04 17:44 UTC by MikeChou

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

chakra: add options for including dynamic library and disabling LTO

option "with-dylib", "Build and install 'libChakraCore.dylib' and headers for embedding"
option "without-lto", "Disable Link Time Optimization (LTO) for less building time"

Due to how chakra implement dynamic loading from its binary (only look for dylib at the same directory as the binary), so the binary has to build statically for now: first build the dynamic library if needed and then build statically to override the binary.

2018-07-04 18:14 UTC, ilovezfs requested changes
Let's skip the `without-lto` option as build time isn't really a concern given Homebrew is primarily a binary package manager. As for the `dylib`, we should just always build it.

The formula should remain optionless.

2018-07-14 08:29 UTC, MikeChou commented
@ilovezfs 

1. removed all options as requested
2. rebased to the lastest master

The branch name still has "options" in it. Should I change that as well?

2018-07-14 08:36 UTC, MikeChou commented
Jenkins seems to fail to check out the code:
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/27329/version=high_sierra/console

I have no clue

2018-07-14 08:42 UTC, ilovezfs commented
@BrewTestBot test this please

2018-07-26 07:00 UTC, MikeChou commented
@ilovezfs Any change required?

2018-08-10 11:43 UTC, fxcoudert commented
@BrewTestBot test this please

2018-08-10 12:11 UTC, fxcoudert approved these changes

2018-08-10 15:27 UTC, fxcoudert commented
Many thanks @MikeChou for the pull request!

2018-08-10 15:28 UTC, closed without merging