scummc 0.2.0 (new formula)
Homebrew/homebrew-core pull request #29894
Opened 2018-07-09 16:44 UTC by idleberg

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The latest stable release of `scummc` does not build on macOS. Since it hasn't been updated in a long time, going with `:revision` is the only way to compile it successfully.

2018-07-10 07:33 UTC, idleberg commented
Any recommendations on how to proceed. Neither of the commands provide a `--version` parameter or the likes to run a “stupid” test. Should I just leave the test for now?

2018-07-11 05:48 UTC, mistydemeo commented
> Since it hasn't been updated in a long time, going with :revision is the only way to compile it successfully.

How about requesting a new tag from the author? They might be responsive.

2018-07-11 05:49 UTC, mistydemeo requested changes

2018-07-11 05:49 UTC, mistydemeo commented on Formula/scummc.rb
> +  depends_on "gtk+" => :build
Is this statically linked against?

2018-07-11 05:49 UTC, mistydemeo commented on Formula/scummc.rb
> +    system "./configure", "--bison", "/usr/local/opt/bison/bin/bison"
Instead of hardcoding the path, you can do `"Formula["bison"].bin"/bison`.

2018-07-11 05:49 UTC, mistydemeo commented on Formula/scummc.rb
> +  depends_on "bison" => :build
Mind alphabetizing these?

2018-07-11 05:49 UTC, mistydemeo commented on Formula/scummc.rb
> +  bottle do
You can drop the bottle block.

2018-07-11 05:49 UTC, mistydemeo commented on Formula/scummc.rb
> +  sha256 "6eed5d773a2b7de912c15cbfd3409d82939e08769dd559a22c63558e541093ac"
`sha256` is unnecessary if you're using a git source.

2018-07-11 08:30 UTC, fxcoudert commented
> How about requesting a new tag from the author? They might be responsive.

And if they're not, it's probably a good sign we can't consider it for Homebrew core: https://docs.brew.sh/Acceptable-Formulae

2018-07-13 21:02 UTC, idleberg commented
> How about requesting a new tag from the author?

I did just that, let's see if he responds.

2018-07-13 21:03 UTC, idleberg commented on Formula/scummc.rb
> +  depends_on "gtk+" => :build
I'm afraid I can't answer that

2018-08-08 19:52 UTC, DomT4 commented on Formula/scummc.rb
> +  depends_on "sdl" => :build
Is this doing a static build? Asking because `sdl` being a `:build`-only dep is incredibly rare.

2018-08-08 19:55 UTC, DomT4 commented on Formula/scummc.rb
> +    system "./configure", "--bison", "#{Formula["bison"].bin}/bison"
`.opt_bin`

2018-08-08 19:55 UTC, DomT4 commented on Formula/scummc.rb
> +    # Default naming scheme: build.<HOSTNAME>.<COMPILER_VERSION>
Would really like to see upstream add a `make install` for this, personally.

2018-08-08 19:55 UTC, DomT4 commented on Formula/scummc.rb
> +  depends_on "sdl" => :build
Poking at the history I see Misty already asked and you're unsure. I suspect if we add a meaningful test here we'll quickly find out.

2018-08-31 03:09 UTC, DomT4 commented
Looks like you'll need to squash & rebase this; CI is having trouble pulling it cleanly to test.

2018-09-28 04:31 UTC, closed without merging