ldc: support LLVM 6 and use binary bootstrap
Homebrew/homebrew-core pull request #30116
Opened 2018-07-16 10:36 UTC by orip

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Based on our [private LDC homebrew formula](https://github.com/weka-io/homebrew-ldc/pull/5) and after suggestions from @JohanEngelen, one of the LDC maintainers, this PR
* Updates the formula to show support with LLVM6 (LDC 1.10.0 supports LLVM 3.7 up to 6)
* Changes to use a prebuilt binary bootstrap LDC version, similar to how the go.rb and pypy.rb formulas work.

2018-07-16 11:38 UTC, ilovezfs requested changes
Given we currently don't have a dependency on a binary bootstrap, I'm very reluctant to add one. Can you please recast this to build without introducing a binary dependency at build time? Thanks!

2018-08-10 10:25 UTC, fxcoudert commented
@orip LLVM 6 support is great, but the question remains: why is binary bootstrap needed, when it wasn't the case before?

2018-08-11 12:06 UTC, JohanEngelen commented
@fxcoudert Currently we have the follow bootstrap procedure:
- start with C++ compiler
- build LDC-LTS (source is C++-only)
- build LDC (contains D source) using LDC-LTS
In the near future, this will require an extra step, because the LTS compiler will no longer be able to build the latest LDC (the language has evolved, and those changes are not backported to LTS).
The binary bootstrap would make the process simpler, and gives more freedom of use of newer features of D to develop the latest version of the compiler. There are pros and cons ofcourse, but the dlang developers decided to go for a binary bootstrap approach. (this is also the envisioned procedure for cross-compilation: start with a cross-compiled compiler, instead of bootstrapping on the target platform)

2018-08-19 20:39 UTC, DomT4 commented
@fxcoudert How do you feel here?

I just hit the `ldc-lts` issue blocking the upgrade to using `llvm` in https://github.com/Homebrew/homebrew-core/pull/31282, so I assume going forwards we need to either decide to adopt this or essentially permanently pin `ldc` to using a versioned `llvm`.

2018-08-27 00:45 UTC, commitay commented
👍 to this rather than pinning to a versioned `llvm`.

2018-09-02 20:04 UTC, claui commented
There’s a new [0.17.6 LTS release](https://github.com/ldc-developers/ldc/releases/tag/v0.17.6), which supports LLVM 6.0 and 7.0. I’d still prefer the route this PR goes for the reasons @JohanEngelen  mentioned.

2018-09-23 20:34 UTC, claui commented
@fxcoudert With the explanation given in https://github.com/Homebrew/homebrew-core/pull/30116#issuecomment-412270995, would you be OK with switching to the binary bootstrap?

2018-10-19 09:44 UTC, fxcoudert commented
@claui works for me 👍

2018-10-19 11:43 UTC, claui commented
Rebased and bumped to 1.12.0.

@commitay according to the [upstream release notes](https://github.com/ldc-developers/ldc/releases/tag/v1.12.0), 1.12.0 supports LLVM 7, so I’ve also reverted your changes from #32693.

Holding on for a few more days so others can review the latest changes.

2018-10-19 11:47 UTC, commitay commented
The stable and head blocks aren't needed now.

2018-10-19 11:48 UTC, commitay commented
Commit subject for a version bump should be: `ldc 1.12.0`

2018-10-19 11:53 UTC, fxcoudert approved these changes

2018-10-19 11:54 UTC, fxcoudert commented
Great! Just squash everything and it's 👍

2018-10-19 11:55 UTC, commitay commented on Formula/ldc.rb
> -    url "https://github.com/ldc-developers/ldc/releases/download/v1.12.0/ldc-1.12.0-src.tar.gz"
Sorry, I meant the URLs and checksum should be moved out of the blocks.

2018-10-19 11:56 UTC, commitay commented on Formula/ldc.rb
> -  bottle do
The bottle block shouldn't be deleted.

2018-10-19 13:30 UTC, claui commented
@commitay Applied.

2018-10-19 13:32 UTC, commitay approved these changes
Thanks @claui!

2018-10-19 17:50 UTC, closed without merging

2018-10-19 17:50 UTC, fxcoudert commented
Very happy to be able to close this long-awaiting PR with a successful resolution! Thanks everyone who participated, and thanks @claui !