sqoop 1.4.7
Homebrew/homebrew-core pull request #30643
Opened 2018-07-31 13:19 UTC by chasehamrick

Sqoop formula was outdated, 1.4.6 is no longer available, updating to 1.4.7
----
- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-07-31 14:34 UTC, SMillerDev requested changes

2018-07-31 14:34 UTC, SMillerDev commented on Formula/sqoop.rb
> +  revision 1
No need to add a revision here. 1.4.7 isn't released yet 😄

2018-08-09 18:12 UTC, DomT4 commented
https://github.com/Homebrew/homebrew-core/pull/30067 is essentially doing almost the same thing, so I'll defer to @apjanke on where things stand here.

2018-08-13 15:57 UTC, closed without merging

2018-08-13 16:02 UTC, DomT4 commented
Fixed via https://github.com/Homebrew/homebrew-core/pull/30067. Thank you nonetheless for submitting a PR to Homebrew @chasehamrick; we appreciate you taking the time!