fauna-shell 0.3.0
Homebrew/homebrew-core pull request #30766
Opened 2018-08-03 14:09 UTC by alvarofauna

Adds a formula for [fauna-shell](https://www.npmjs.com/package/fauna-shell), a tool that let users operate and interact from the CLI with [FaunaDB](https://fauna.com/)

2018-08-05 12:21 UTC, fxcoudert requested changes

2018-08-05 12:42 UTC, alvarofauna commented on Formula/fauna-shell.rb
> +    system bin/"fauna --help"
this should run a test suit or make sure that the output of a command is correct?

2018-08-06 07:30 UTC, fxcoudert commented on Formula/fauna-shell.rb
> +    system bin/"fauna --help"
The later.

2018-08-06 21:31 UTC, alvarofauna commented
@fxcoudert I added tests as requested

2018-08-08 14:51 UTC, alvarofauna commented
Fixed the tests since there were unused variables

2018-08-19 09:19 UTC, fxcoudert approved these changes

2018-08-19 09:30 UTC, fxcoudert commented
Thanks @alvarofauna for the pull request, and congratulations on your first contribution to Homebrew! It is now merged

2018-08-19 09:31 UTC, closed without merging

2018-08-19 09:40 UTC, alvarofauna commented
Thanks @fxcoudert 

If I'd want to push an updated version of the formula, is that just a new PR? Basically every time we release a new version of the npm package.

2018-08-20 17:03 UTC, fxcoudert commented
@alvarofauna yes, a new PR with each new version