pcp 4.1.1 (new formula)
Homebrew/homebrew-core pull request #30796
Opened 2018-08-04 10:54 UTC by Warewolf96

- [ Yes ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ Yes ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ Yes ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ Yes ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-08-05 12:20 UTC, fxcoudert requested changes
According to github, the latest stable version is 4.1.0: https://github.com/performancecopilot/pcp/releases

2018-08-06 04:49 UTC, Warewolf96 commented on Formula/pcp.rb
> +  depends_on "pkg-config" => :build
I'll rectify this.

2018-08-06 04:55 UTC, Warewolf96 commented on Formula/pcp.rb
> +
Okay

2018-08-12 08:53 UTC, Warewolf96 commented on Formula/pcp.rb
> +    system "./configure", "--prefix=#{prefix}", "CC=clang", "CXX=clang", "--without-manager"
It gives an error msg in the log if we don't use CC, CXX as well as --without-manager. I can paste the error log here if you want.

2018-09-09 10:05 UTC, closed without merging