mingw-w64: fix build, bump versions
Homebrew/homebrew-core pull request #30801
Opened 2018-08-05 01:22 UTC by rkitover

Bump gcc to 8.2.0 and add the isl 0.20 build patch from #30639.

Bump binutils to 2.31.1.

Change the option --with-posix to --without-posix, the rationale being
that most people use this software to port unix code to windows and do
want -lpthread available, preferrably without having to build gcc twice
on their computer, also as far as I understand it doesn't hurt anything
to have it be enabled.

Set revision to 1 because version of mingw did not change.

- [ y] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ y] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ y] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ y] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-08-05 11:39 UTC, fxcoudert commented
- Analytics show that only 8% of Homebrew users install the package with `--with-posix` option, not sure this is enough to make it default.
- Homepage is not reachable because of expired certificate: https://sourceforge.net/p/mingw-w64/bugs/754/

2018-08-05 13:08 UTC, rkitover commented
I do a lot of builds for windows and I almost always need -lpthread, I don't think your analytics are going to give you any useful information in this case.

2018-08-06 07:27 UTC, fxcoudert commented
There is a clear downside to using POSIX threads: all binaries need to ship libwinpthreads.
I've dug some more into mingw and MSYS packages, and they appear to ship with POSIX by default: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gcc/PKGBUILD

2018-08-06 07:28 UTC, fxcoudert requested changes

2018-08-06 07:28 UTC, fxcoudert commented on Formula/mingw-w64.rb
> -      if build.with? "posix"
Please revert this part of the changes (lines 85–93).

2018-08-06 09:54 UTC, rkitover commented
No they don't, the library can be linked statically.

But I'll revert it if you insist.

2018-08-06 09:57 UTC, rkitover commented
Also you are forcing the user to build gcc TWICE for something they will almost definitely need if they didn't install the package just out of curiosity.

2018-08-06 11:42 UTC, fxcoudert commented
@rkitover I'm now OK with making pthreads default, now that I have seen that it is how MSYS does it.
(Regarding all (or most) “users reinstalling twice”, it is not the case, as analytics show.)

2018-08-08 08:39 UTC, fxcoudert approved these changes

2018-08-08 16:56 UTC, fxcoudert commented
Thanks @rkitover for the pull request!

2018-08-08 16:57 UTC, closed without merging