qemu 3.0.0
Homebrew/homebrew-core pull request #31180
Opened 2018-08-16 12:14 UTC by evshiron

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-08-16 15:45 UTC, DomT4 requested changes
What @SMillerDev said as well, please.

2018-08-16 15:45 UTC, DomT4 commented on Formula/qemu.rb
> +  option "with-hvf", "Enable Hypervisor.framework support (3.x)"
It this is compatible with all the other options we offer in 3.x just turn it on by default, unless there's another good reason not to.

2018-08-16 18:40 UTC, evshiron commented
The stable version no longer needs a patch to build when `--with-gtk+3` after upgrading to `3.0.0`, and the `Hypervisor.framework support` is automatically enabled if available when `./configure`, so I remove the patch and the `with-hvf` option.

2018-08-16 19:33 UTC, DomT4 commented
You can remove the `devel do` block entirely now, because it's older than `stable`.

2018-08-17 03:56 UTC, DomT4 commented
Merged in https://github.com/Homebrew/homebrew-core/commit/c7de8968b0b7e872f339812d88942181aee515ec. Thank you for your contribution to Homebrew @evshiron; we appreciate it! :smiley_cat:

2018-08-17 03:56 UTC, closed without merging