Add New formula socli 3.6
Homebrew/homebrew-core pull request #31452
Opened 2018-08-25 16:37 UTC by hanxue

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-08-26 04:01 UTC, DomT4 requested changes

2018-08-26 04:01 UTC, DomT4 commented on Formula/socli.rb
> +  resource "beautifulsoup4" do
Can we alphabetise the resources, please?

2018-08-29 18:12 UTC, hanxue commented on Formula/socli.rb
> +  resource "beautifulsoup4" do
Sure, I will force push an update

2018-08-31 04:29 UTC, DomT4 commented
Any idea why the test would be failing on just Mojave?
```
==> /usr/local/Cellar/socli/3.6/bin/socli print stack trace python
Error: socli: failed
</import\ traceback/> expected to be =~
<"">.
```

2018-09-28 05:31 UTC, closed without merging