certgraph 20180217 (new formula)
Homebrew/homebrew-core pull request #31504
Opened 2018-08-27 00:43 UTC by betrisey

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
New formula for CertGraph: https://github.com/lanrat/certgraph

2018-08-27 01:01 UTC, DomT4 requested changes

2018-08-27 01:01 UTC, DomT4 commented on Formula/certgraph.rb
> +    :tag => "20180217",
4 space indent rather than 2 space on both `:tag` and `:revision` (but nowhere else).

2018-08-27 01:01 UTC, DomT4 commented on Formula/certgraph.rb
> +      bin.install "certgraph"
You'll likely need to add a `prefix.install_metafiles` line here.

This ensures things like `README`, `LICENSE` and `CHANGELOG` where available are installed into the prefix. Normally Homebrew handles this automatically with a little magic, but when you relocate the entire contents of the `buildpath` to another directory for the install process as is common with `go`-using formulae that logic falls on its face & it needs a little manual nudging. It's a known issue.

2018-08-27 01:01 UTC, DomT4 commented on Formula/certgraph.rb
> +    system "#{bin}/certgraph", "-version"
Any chance of a test that exercises a deeper level of functionality? Thanks!

2018-08-27 01:31 UTC, betrisey commented
Thank you for the feedback! I made the changes.

2018-08-27 04:37 UTC, DomT4 commented
We're going to need upstream to pin this dependency to a commit or a tag before we can accept this:
```
Root project is "github.com/lanrat/certgraph"
 9 transitively valid internal packages
 1 external packages imported from 1 projects
(0)   ✓ select (root)
(1)	? attempt github.com/lib/pq with 1 pkgs; 3 versions to try
(1)	    try github.com/lib/pq@v1.0.0
(2)	✗   github.com/lib/pq@v1.0.0 not allowed by constraint master:
(2)	    master from (root)
(1)	    try github.com/lib/pq@master
(1)	✓ select github.com/lib/pq@master w/2 pkgs
  ✓ found solution with 2 packages from 1 projects
```

2018-09-12 19:53 UTC, betrisey commented
Hi @DomT4 
The author of cergraph released a new version. It is now using Go modules and the dependencies are pinned.

2018-09-12 20:00 UTC, betrisey commented
Hi @fxcoudert 
I saw that the old reviewer resigned today (https://github.com/Homebrew/brew/commit/da8d37ee31d63554ca6f14261c22fa57f0331c66).
Could you review it please?
Thank you

2018-10-01 21:10 UTC, closed without merging