bloaty 1.0
Homebrew/homebrew-core pull request #31555
Opened 2018-08-28 23:01 UTC by zlern2k

- [Y] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [Y] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [Y] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [Y] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Bloaty was asked for in https://github.com/Homebrew/homebrew-core/issues/11803; now that it has a release version on github, I'm submitting this formula because I need it, too.

2018-08-28 23:35 UTC, zlern2k commented
Bah. Moved bloaty into the bin directory and then forgot to re-run 'brew test' before submitting. figuring out how to update the pull request now...

2018-08-29 00:18 UTC, DomT4 requested changes

2018-08-29 00:18 UTC, DomT4 commented on Formula/bloaty.rb
> +  depends_on "cmake" => :build
New line between `sha256` and the first `depends_on` please.

2018-08-29 00:18 UTC, DomT4 commented on Formula/bloaty.rb
> +    system "make", "-j#{ENV.make_jobs}"
Drop the ` "-j#{ENV.make_jobs}"`.

2018-08-29 00:18 UTC, DomT4 commented on Formula/bloaty.rb
> +    bin.install buildpath/"bloaty"
Is there no `make install`?

2018-08-31 04:27 UTC, DomT4 commented
Merged in https://github.com/Homebrew/homebrew-core/commit/65d8212b3073522ba7717ea2c34a3fc147ef09c6. Thank you for your contribution to Homebrew @zlern2k; we appreciate it! :smiley_cat:

2018-08-31 04:27 UTC, closed without merging