Patch 1
Homebrew/homebrew-core pull request #31758
Opened 2018-09-03 20:50 UTC by hyiltiz

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-09-03 21:43 UTC, javian commented
Thank you for the contribution @hyiltiz and your first PR to Homebrew. This PR however is not going to be accepted since despite you putting the work in the AOM formula is based on a head only repository. We need to have a properly released version of the software before it can make it in to Homebrew.

2018-09-03 21:50 UTC, hyiltiz commented
As you know, some excellent software (I can name a few, but as I said, I am assuming you already know a few) simply does not have a "release" per se, and simply works as a rolling release. In fact, most companies now do, calling it SaaS. Therefore, strictly requiring a "release" tag seems mute.

2018-09-04 04:30 UTC, javian commented
Yes I'm aware =) but lets not get into a debate about that here. As described in the https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md document standalone formulas that are using head only is not acceptable. 

If you submit the ffmpeg formula with av1 as a resource it should be potentially possible to include it but someone else in the team would need to pitch in on that.

2018-09-04 10:33 UTC, fxcoudert requested changes

2018-09-04 10:33 UTC, fxcoudert commented on Formula/aom.rb
> +  head "https://aomedia.googlesource.com/aom.git"
We can't accept this. I see that there is a `v1.0.0` tag which, if it is considered “stable” by upstream, we can use as a tagged version.

2018-09-04 10:33 UTC, fxcoudert commented on Formula/aom.rb
> +    system ./aomenc
We need a test that exercises the some of the functionality of the app.

2018-09-04 10:33 UTC, fxcoudert commented on Formula/ffmpeg.rb
> +  url "https://ffmpeg.org/releases/ffmpeg-3.4.2.tar.bz2"
No decreasing version numbers!

2018-09-04 10:33 UTC, fxcoudert commented on Formula/ffmpeg.rb
> +    sha256 "e507900d3ec72618b365588223f57428654334119d34d6d61ca58210bb7c4907" => :el_capitan
Do not touch the bottle blocks please.

2018-09-04 10:33 UTC, fxcoudert commented on Formula/ffmpeg.rb
> +    args << "--disable-jack" if build.stable?
Why disabling jack?

2018-09-04 10:34 UTC, fxcoudert commented
I have left review comments on the pull request code itself. We will not be shipping this into Homebrew unless a stable release is tagged. Using it as an unversioned resource is also not acceptable.

2018-09-04 10:34 UTC, closed without merging

2018-09-04 15:10 UTC, hyiltiz commented
Maybe @duvrai might be interested to help out here.

2018-09-12 10:09 UTC, zmwangx commented
Interestingly, I was compiling FFmpeg with libaom myself just now, then I noticed this PR.

In fact, `aom.git` does have a `v1.0.0` tag, tagged in June:

```git
tag v1.0.0
Tagger:     Yaowu Xu <yaowu@google.com>
TaggerDate: Mon Jun 25 10:14:26 2018 -0700

AOMedia Codec Workgroup Approved version 1.0

commit d14c5bb4f336ef1842046089849dee4a301fbbf0 (HEAD, tag: v1.0.0)
Author:     Yaowu Xu <yaowu@google.com>
AuthorDate: Mon Jun 25 07:54:59 2018 -0700
Commit:     Yaowu Xu <yaowu@google.com>
CommitDate: Mon Jun 25 07:54:59 2018 -0700

    [NORMATIVE]Allow non-identical sequence headers

    This commit changes the reference code to allow additional sequence
    headers with different number of trailing 0 bits.

    Change-Id: Icbb1c9a834b438271456fcda9323a3212dd62784
```

Not sure if it wasn't pushed to origin at the time of your discussion.

My trivial `libaom.rb`:

```rb
class Libaom < Formula
  desc "Alliance for Open Media AV1 codec"
  homepage "https://aomedia.googlesource.com/aom/"
  url "https://aomedia.googlesource.com/aom.git",
      :tag => "v1.0.0"

  depends_on "cmake" => :build

  def install
    mkdir "build" do
      system "cmake", "..", *std_cmake_args
      system "make", "install"
    end
  end

  test do
    raise "Not implemented."
  end
end
```

2018-09-13 06:09 UTC, hyiltiz commented
Yes, there was! And that is an interesting find. 
https://aomedia.googlesource.com/aom/+/v1.0.0