[WIP] Add create-dmg
Homebrew/homebrew-core pull request #32496
Opened 2018-09-27 13:11 UTC by MartinDelille

….0.3

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Like I said in the title, this is a work in progress, this is why I don't have checked the items yet.

2018-09-27 13:17 UTC, SMillerDev requested changes
This seems like a very rough draft, might want to run it locally a couple of times before submitting a PR?

2018-09-27 13:17 UTC, SMillerDev commented on Formula/create-dmg.rb
> +# PLEASE REMOVE ALL GENERATED COMMENTS BEFORE SUBMITTING YOUR PULL REQUEST!
This still needs to be removed

2018-09-27 13:17 UTC, SMillerDev commented on Formula/create-dmg.rb
> +  # depends_on "cmake" => :build
Needs to be removed if unused

2018-09-27 13:17 UTC, SMillerDev commented on Formula/create-dmg.rb
> +    # Remove unrecognized options if warned by configure
Needs to be removed if unused

2018-09-27 13:17 UTC, SMillerDev commented on Formula/create-dmg.rb
> +    system "false"
Needs an actual test

2018-09-27 13:17 UTC, SMillerDev commented on Formula/create-dmg.rb
> +    system "./configure", "--disable-debug",
Source doesn't seem to have a configure script

2018-09-27 13:17 UTC, SMillerDev commented on Formula/create-dmg.rb
> +  homepage ""
This is needed, but a github repo is also fine.

2018-09-28 16:15 UTC, MartinDelille commented
@SMillerDev Yes but I wanted to share it with someone that know `create-dmg` better than me (I'm only a `create-dmg` user).

I was also hopping to receive a little help about creating formula for bash script. Any idea what is going wrong with `bin.install "create-dmg"`? There is not so much help on this topic!

2018-10-14 20:52 UTC, closed without merging