threedifier 1.0.3 (new formula)
Homebrew/homebrew-core pull request #32551
Opened 2018-09-29 11:47 UTC by Ylannl

add new formula for the 3dfier software

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-09-29 12:10 UTC, lembacon requested changes

2018-09-29 12:10 UTC, lembacon commented on Formula/threedifier.rb
> +  sha256 "0216cdb4bbad4f6ec8a3867742129db2b365a9f92a6cb6744bb6266be4f466f5"
A blank line after `sha256`.

2018-09-29 12:10 UTC, lembacon commented on Formula/threedifier.rb
> +    system "{bin}/3dfier", "--version"
Please add a test that exercises a deeper level of the functionality provided by this formula.

2018-09-30 10:29 UTC, fxcoudert commented on Formula/threedifier.rb
> +  homepage "https://github.com/Homebrew/homebrew-core"
Homepage should probably be https://github.com/tudelft3d/3dfier

2018-09-30 10:30 UTC, fxcoudert commented
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LASZIP_INCLUDE_DIR
   used as include directory in directory /tmp/threedifier-20180929-32481-vkt436/3dfier-1.0.3
```

2018-09-30 10:31 UTC, fxcoudert commented
Please make sure the formula builds locally and passes `brew audit --strict` before pushing to the pull request. Most of the issues can be fixed by yourself, without requiring multiple rounds of review, which give us more time to work on other pull requests.

2018-09-30 12:08 UTC, Ylannl commented
> Please make sure the formula builds locally and passes `brew audit --strict` before pushing to the pull request. Most of the issues can be fixed by yourself, without requiring multiple rounds of review, which give us more time to work on other pull requests.

I actually did this on my own system and it passed. But I'll look into the issue and fix it as well as the deeper test. Thanks!

2018-10-03 14:35 UTC, Ylannl commented
I've decided to put this formula in a separate tap, together with some other packages. Thanks again.

2018-10-03 14:35 UTC, closed without merging