bluepill 3.0.0
Homebrew/homebrew-core pull request #32602
Opened 2018-10-01 16:37 UTC by fxcoudert

Created with `brew bump-formula-pr`.

2018-10-01 17:38 UTC, bayareabear commented
Thanks!

2018-10-01 19:59 UTC, bayareabear commented
@fxcoudert, The build failed. Could you please add the following to the build:
  xcodebuild \
    -project Bluepill-cli/Bluepill-cli.xcodeproj \
    -scheme BluepillLib \
    -configuration Debug \
    -derivedDataPath "build/" | tee result.txt

Before:
  xcodebuild \
    -workspace Bluepill.xcworkspace \
    -scheme bluepill \
    -configuration Release \
    -derivedDataPath "build/" | tee result.txt 

The latter depends on the first one. This is not ideal. I am going to fix it in the next pull request. Thanks!

2018-10-02 15:32 UTC, fxcoudert commented
```
==> xcodebuild -project Bluepill-cli/Bluepill-cli.xcodeproj -scheme BluepillLib  -configuration Release SYMROOT=../
Build settings from command line:
    SYMROOT = ../

xcodebuild: error: The project named "Bluepill-cli" does not contain a scheme named "BluepillLib ". The "-list" option can be used to find the names of the schemes in the project.
```

@bayareabear

2018-10-03 03:58 UTC, bayareabear commented
Release 3.0.1 that fixed the dependency issue. You don't need to add BluepillLib build any more:
xcodebuild
-project Bluepill-cli/Bluepill-cli.xcodeproj
-scheme BluepillLib
-configuration Debug
-derivedDataPath "build/" | tee result.txt

2018-10-03 21:57 UTC, oliverhu commented
The error msg in travis doesn't seem to be reproducible locally :(

2018-10-03 22:00 UTC, oliverhu requested changes

2018-10-03 22:00 UTC, oliverhu commented on Formula/bluepill.rb
> -    xcodebuild "-workspace", "Bluepill.xcworkspace",
Please revert this portion of change when you build with bluepill 3.0.1.

2018-10-03 22:04 UTC, oliverhu commented
two more things.. 1) please revert the change in `def install ` 2) please wait for a Bluepill 3.0.2 release, the 3.0.1 release might not work for homebrew distribution

2018-10-03 22:18 UTC, fxcoudert commented
@bayareabear @oliverhu I am closing this pull request. Please open a new one when there is a version of bluepill that works fine in Homebrew.

2018-10-03 22:18 UTC, closed without merging