[New Formula] Heptio Sonobuoy
Homebrew/homebrew-core pull request #32772
Opened 2018-10-06 17:04 UTC by sc250024

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

 New formula for Heptio Sonobuoy project

2018-10-06 17:17 UTC, sc250024 commented
Since this is a new formula, I'm not sure how to add the `bottle do` block. I read the [Bottle documentation](https://github.com/Homebrew/brew/blob/master/docs/Bottles.md), but I'm not sure if I should add the block with empty values, or if the CI process takes care of this.

2018-10-06 17:24 UTC, fxcoudert requested changes

2018-10-06 17:31 UTC, sc250024 commented on Formula/sonobuoy.rb
> +    output = shell_output("#{bin}/sonobuoy gen 2>&1")
The `ark` formula has a simple example which just sets some configuration, and then retrieves that configuration values: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ark.rb#L29-L35. 

A test that would function as an example of Sonobuoy's functionality would be to examine a `.tar.gz` that was generated from a test cluster. 

```console
$ sonobuoy e2e --help
Inspect e2e test results. Optionally rerun failed tests

Usage:
  sonobuoy e2e archive.tar.gz [flags]
```

Is it common to commit an entire `.tar.gz` file for test purposes?

2018-10-06 17:35 UTC, fxcoudert commented on Formula/sonobuoy.rb
> +    output = shell_output("#{bin}/sonobuoy gen 2>&1")
We have some tests that use a `.tar.gz` resource. Look at `adplug` for example.

2018-10-06 18:00 UTC, sc250024 commented on Formula/sonobuoy.rb
> +    output = shell_output("#{bin}/sonobuoy gen 2>&1")
@fxcoudert Turns out the Sonobuoy repo has a `tar.gz` file already used for testing, so we can use that to run `sonobuoy e2e` against.

2018-10-06 18:18 UTC, sc250024 commented on Formula/sonobuoy.rb
> +    output = shell_output("#{bin}/sonobuoy gen 2>&1")
@fxcoudert I've noticed that the majority of formulas use the `stage` method here: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/resource.rb#L68-L76. Is there a method which simply downloads the tarball, but doesn't unpack it? Sonobuoy expects a tarball.

2018-10-06 19:09 UTC, fxcoudert commented on Formula/sonobuoy.rb
> +    output = shell_output("#{bin}/sonobuoy gen 2>&1")
```
    r = resource("whatever")
    r.verify_download_integrity(r.fetch)
```

Then use `r.cached_download` as the downloaded path (read-only).

2018-10-06 19:32 UTC, sc250024 commented on Formula/sonobuoy.rb
> +    output = shell_output("#{bin}/sonobuoy gen 2>&1")
Cool, thank you! It's resolved now.

2018-10-08 08:41 UTC, sc250024 commented
@fxcoudert This should be good to go now, assuming there's nothing else you want tested.

2018-10-20 18:19 UTC, sc250024 commented
@fxcoudert Is there anything else that's needed for this formula?

2018-10-20 20:07 UTC, fxcoudert approved these changes

2018-10-20 20:09 UTC, fxcoudert commented
Thanks @sc250024 for the pull request!

2018-10-20 20:09 UTC, closed without merging