mas 1.4.3
Homebrew/homebrew-core pull request #33104
Opened 2018-10-18 01:02 UTC by phatblat

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-10-19 12:17 UTC, commitay commented on Formula/mas.rb
> -    sha256 "af5be6aa9902d9cfc2aa69dbf313441a7c201463d516face721f900ceae9556b" => :sierra
The bottle block shouldn't be edited manually.

2018-10-19 12:17 UTC, commitay commented on Formula/mas.rb
> +    :shallow => true
`shallow => true` is redundant.

2018-10-19 12:17 UTC, commitay commented on Formula/mas.rb
> +    File.open(xcconfig, "w") { |file| file.write("GCC_TREAT_WARNINGS_AS_ERRORS = NO") }
```suggestion
    xcconfig.write("GCC_TREAT_WARNINGS_AS_ERRORS = NO")
```

2018-10-19 19:44 UTC, fxcoudert requested changes

2018-10-19 19:44 UTC, fxcoudert commented on Formula/mas.rb
> +    :tag => "v1.4.3",
Extra comma

2018-10-19 19:45 UTC, phatblat commented on Formula/mas.rb
> +    :tag => "v1.4.3",
Ack! Thx
```suggestion
    :tag => "v1.4.3"
```

2018-10-19 22:19 UTC, commitay commented on Formula/mas.rb
> +    :tag => "v1.4.3"
`revision` is required for stable.

```diff
diff --git a/Formula/mas.rb b/Formula/mas.rb
index ca67eaf853..b0b6159f7b 100644
--- a/Formula/mas.rb
+++ b/Formula/mas.rb
@@ -2,7 +2,8 @@ class Mas < Formula
   desc "Mac App Store command-line interface"
   homepage "https://github.com/mas-cli/mas"
   url "https://github.com/mas-cli/mas.git",
-    :tag => "v1.4.3"
+      :tag => "v1.4.3",
+      :revision => "11a0e3e14e5a83aaaba193dfb6d18aa49a82b881"
   head "https://github.com/mas-cli/mas.git"
 
   bottle do
```

2018-10-19 23:01 UTC, commitay commented on Formula/mas.rb
> +               "OBJROOT=#{buildpath.realpath}",
Why is `buildpath.realpath` needed?

2018-10-20 03:03 UTC, commitay commented
@BrewTestBot test this please

2018-10-21 00:04 UTC, phatblat commented
@fxcoudert This should be GTG now. I had to work around some linker errors with `-headerpad_max_install_names`

2018-10-21 00:14 UTC, commitay commented on Formula/mas.rb
> +    xcconfig.write("GCC_TREAT_WARNINGS_AS_ERRORS = NO\nOTHER_LDFLAGS = -headerpad_max_install_names")
```
xcconfig.write <<~EOS
  GCC_TREAT_WARNINGS_AS_ERRORS = NO
  OTHER_LDFLAGS = -headerpad_max_install_names
EOS
```

2018-10-21 00:14 UTC, phatblat commented on Formula/mas.rb
> +    xcconfig.write("GCC_TREAT_WARNINGS_AS_ERRORS = NO\nOTHER_LDFLAGS = -headerpad_max_install_names")
👍

2018-10-21 23:15 UTC, commitay approved these changes

2018-10-22 05:31 UTC, phatblat commented
Thanks for your feedback @commitay and @fxcoudert ! 🙇

2018-10-22 05:31 UTC, phatblat commented
Thanks for your feedback @commitay and @fxcoudert! 🙇

2018-10-23 12:48 UTC, fxcoudert approved these changes

2018-10-23 12:48 UTC, fxcoudert commented
Thanks @phatblat for the pull request

2018-10-23 12:49 UTC, closed without merging