Fix sqliteodbc to actually install something
Homebrew/homebrew-core pull request #33265
Opened 2018-10-22 12:32 UTC by John-Colvin

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Currently no files are installed and the tests fail (for me at least). This fixes that.

Perhaps this should detect what versions of sqlite are installed and and pass the relevant flags to `configure`, but I'm not sure what the best way to do that is.

2018-10-23 12:47 UTC, fxcoudert requested changes
Use `sqlite` as formula name.

2018-10-23 12:47 UTC, fxcoudert commented on Formula/sqliteodbc.rb
> +  depends_on "sqlite3"
`sqlite3` is an alias to `sqlite`, so this is wrong.

2018-10-23 14:38 UTC, fxcoudert commented on Formula/sqliteodbc.rb
> +  depends_on "sqlite3"
Yes, `sqlite4` is a completely different project.

2018-10-24 12:16 UTC, fxcoudert commented
```
libtool: link: clang -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libsqlite3_mod_xpath-0.9996.dylib  .libs/xpath.o   -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib -lxml2 -lz -lpthread -licucore -lm    -install_name  /usr/local/Cellar/sqliteodbc/0.9996/lib/libsqlite3_mod_xpath-0.9996.dylib  -Wl,-single_module
ld: file not found: /usr/lib/system/libsystem_darwin.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libsqlite3_mod_xpath.la] Error 1
```

2018-11-08 18:52 UTC, SMillerDev commented
@John-Colvin could you add the fix from @fxcoudert ?

2018-12-07 19:44 UTC, fxcoudert commented
Thanks @John-Colvin

2018-12-07 19:44 UTC, fxcoudert approved these changes

2018-12-07 19:45 UTC, closed without merging