redis 4.0.11
Homebrew/homebrew-core pull request #33305
Opened 2018-10-23 13:34 UTC by hyuraku

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Now(October 23th, 2018), we can install redis@5 and redis@3 by `brew install`, 
but we cannot do redis@4. 
So, I add a new formula for redis4.

2018-11-14 13:57 UTC, epistrephein commented
Commenting to prevent this from being closed.
I think having redis 4 on homebrew would be very useful for many.

2018-12-05 15:02 UTC, epistrephein commented
Commenting again to prevent closing.
Could this get evaluated by a maintainer? In case something is off I can step up and fix it if @hyuraku is not available

2018-12-12 06:36 UTC, igas requested changes

2018-12-12 06:36 UTC, igas commented on Formula/redis@4.0.rb
> +  url "http://download.redis.io/releases/redis-4.0.11.tar.gz"
https://github.com/antirez/redis/releases/tag/4.0.12 released

2018-12-12 06:36 UTC, igas commented on Formula/redis@4.0.rb
> +  option "with-jemalloc", "Select jemalloc as memory allocator when building Redis"
Please remove option. See #31510 for the rationale behind removing options from formulas.

2018-12-12 06:36 UTC, igas commented on Formula/redis@4.0.rb
> +    system "make", "install", *args
without option could be simplified to:
```
system "make", "install", "PREFIX=#{prefix}", "CC=#{ENV.cc}"
```

2018-12-12 06:36 UTC, igas commented on Formula/redis@4.0.rb
> +    args << "MALLOC=jemalloc" if build.with? "jemalloc"
don't forget to drop here

2018-12-12 06:36 UTC, igas commented on Formula/redis@4.0.rb
> +    args << "MALLOC=jemalloc" if build.with? "jemalloc"
don't forget to drop here

2018-12-12 06:36 UTC, igas commented on Formula/redis@4.0.rb
> +  plist_options :manual => "redis-server #{HOMEBREW_PREFIX}/etc/redis.conf"
I believe this one needs to be updated to opt. See [cassandra@2.1](https://github.com/Homebrew/homebrew-core/blob/e0b944b3ccb73fa1aaea99dc94b57423dd278828/Formula/cassandra%402.1.rb#L97) for example.

2018-12-20 01:37 UTC, igas approved these changes

2018-12-20 01:41 UTC, igas commented
Thank you @hyuraku!

2018-12-20 01:43 UTC, igas commented
Closed via https://github.com/Homebrew/homebrew-core/commit/d98a6feb8cf67b6a9285ed60041936dc45d7b424

2018-12-20 01:43 UTC, closed without merging