wskdeploy 0.9.9
Homebrew/homebrew-core pull request #33494
Opened 2018-10-29 23:07 UTC by pritidesai

Created with `brew bump-formula-pr`.

2018-10-30 05:36 UTC, apjanke commented
Audit failure in Jenkins.

```
Error Message
failed: brew audit wskdeploy --online
Stacktrace
        Error: 1 problem in 1 formula detected
wskdeploy:
  * Stable: version 0.9.9 is redundant with version scanned from URL
```

2018-10-30 05:37 UTC, apjanke requested changes

2018-10-30 05:37 UTC, apjanke commented on Formula/wskdeploy.rb
> +  version "0.9.9"
You can remove this `version ...` line now that the URL is one that Homebrew can parse automatically. This will fix the audit failure.

2018-11-08 19:59 UTC, pritidesai commented
yup, sorry for delay, just updated, thanks @SMillerDev

2018-11-09 09:37 UTC, fxcoudert commented
Thanks @pritidesai for your contribution!

2018-11-09 09:38 UTC, closed without merging