HTTPie 1.0.0
Homebrew/homebrew-core pull request #33649
Opened 2018-11-02 16:12 UTC by jakubroztocil

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

Got an error unrelated to this formula:

```
 $ brew audit --strict httpie
==> Installing or updating 'rubocop' gem
Error: Unable to resolve dependency: user requested 'did_you_mean (= 1.0.0)'
```

Release:

https://github.com/jakubroztocil/httpie/releases/tag/1.0.0

2018-11-02 16:51 UTC, fxcoudert requested changes

2018-11-02 16:51 UTC, fxcoudert commented on Formula/httpie.rb
> +
One extra blank line.
And please restore the bottle block, it is handled automatically.

2018-11-02 17:58 UTC, jakubroztocil commented
@fxcoudert spaced removed, bottles returned

2018-11-03 16:00 UTC, Moisan commented
```
        Error: 2 problems in 1 formula detected
httpie:
  * C: 8: col 3: `url` (line 8) should be put before `head` (line 6)
  * C: 9: col 3: `sha256` (line 9) should be put before `head` (line 6)
```

2018-11-03 16:50 UTC, jakubroztocil commented
@Moisan updated 👍🏻

2018-11-05 15:11 UTC, Moisan commented
@BrewTestBot test this please

2018-11-05 15:25 UTC, fxcoudert approved these changes

2018-11-05 15:27 UTC, closed without merging