libtiff: update patches
Homebrew/homebrew-core pull request #33918
Opened 2018-11-08 09:53 UTC by fxcoudert

lib tiff build from source is broken (https://github.com/Homebrew/homebrew-core/issues/33858) because Debian has remove the file we used for their patches. And their are now building from a git checkout, without patches.

So this PR updates our `libtiff` formula with patches from the latest Fedora package.

@Homebrew/core review welcome

2018-11-08 10:40 UTC, claui requested changes

2018-11-08 10:40 UTC, claui commented on Formula/libtiff.rb
> +  # libtiff-4.0.9-13.fc30.src.rpm
```suggestion
  # libtiff-4.0.9-13.fc30.src.rpm and whose changelog can be found at:
  # https://apps.fedoraproject.org/packages/libtiff/changelog/
```

It took me a long time to find the changelog for Fedora’s `fc30` revision; they didn’t turn up at several Google searches. The revision is also [not even included in Fedora’s Git repo](https://src.fedoraproject.org/cgit/rpms/libtiff.git) yet. So I feel the full URL of the changelog should be included via comment.

2018-11-08 10:40 UTC, claui commented on Formula/libtiff.rb
>    end
There has been a recent security issue with libtiff \([CVE-2018-18557](https://security-tracker.debian.org/tracker/CVE-2018-18557)\). The new Git snapshot used by Debian [includes a fix](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905798) for the CVE. However, Fedora [hasn’t issued a new release yet](https://apps.fedoraproject.org/packages/libtiff/changelog/) that includes the fix.

If we absolutely don’t want to base the formula on the Git snapshot, should we not find another way to obtain a patch and include it in the formula?

2018-11-08 10:49 UTC, fxcoudert commented
git snapshots are definitely against our policy. It's sad that libtiff is not releasing regularly, and that Debian is enabling them. Patch added for CVE-2018-18557

2018-11-08 11:13 UTC, claui approved these changes
Thanks @fxcoudert, and also 👍 for cherry-picking the diff from upstream directly.

2018-11-08 11:14 UTC, David070 commented
Hey I am quite new to Python and Libtiff.. I tried to install it via Brewmaster but its giving me Error_messages probably due to the deletion of the file?!
Is there another way to install it? Can you maybe help me.. 
Thank you, David :)

2018-11-08 12:04 UTC, claui commented
@David070 Care to re-post your question on [discourse.brew.sh](https://discourse.brew.sh/) in a bit more detail? This makes sure your support request will be read by the right people, and can be acted upon. Thanks!

2018-11-08 14:07 UTC, claui commented
@fxcoudert It does now 😉

2018-11-08 14:33 UTC, fxcoudert commented
@claui I like the idea, but it looks a bit hackish… maybe we can adapt the patch and host it on `formula-patches`, what do you think?

2018-11-09 08:49 UTC, fxcoudert commented
Thanks @claui for the help!

2018-11-09 08:51 UTC, closed without merging