fx 3.1.0 (new formula)
Homebrew/homebrew-core pull request #34027
Opened 2018-11-13 06:07 UTC by antonmedv

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-11-13 07:24 UTC, fxcoudert requested changes

2018-11-13 07:44 UTC, antonmedv commented on Formula/fx.rb
> +
@fxcoudert done

2018-11-13 09:27 UTC, fxcoudert approved these changes

2018-11-15 08:57 UTC, antonmedv commented
ping @lembacon, please help :)

2018-11-15 17:10 UTC, closed without merging

2018-11-15 17:11 UTC, lembacon commented
Shipped. Thanks @antonmedv for your contribution. ❤️