mesa: add head
Homebrew/homebrew-core pull request #34251
Opened 2018-11-18 12:03 UTC by yurikoles

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-11-21 10:32 UTC, fxcoudert requested changes

2018-11-21 10:32 UTC, fxcoudert commented on Formula/mesa.rb
> -
No whitespace change

2018-11-21 10:32 UTC, fxcoudert commented on Formula/mesa.rb
> +    depends_on "gettext"
Why does it need `gettext`?

2018-11-21 11:18 UTC, yurikoles commented on Formula/mesa.rb
> -
Fixed, thanks!

2018-11-21 11:19 UTC, yurikoles commented on Formula/mesa.rb
> +    depends_on "gettext"
Because it fails to build without it.

2018-11-26 09:29 UTC, fxcoudert approved these changes

2018-11-26 09:29 UTC, merged