openssl: fix compilation on older systems
Homebrew/homebrew-core pull request #34326
Opened 2018-11-20 22:17 UTC by EricFromCanada

Fixes #2766.
Also removes unused makedepend dependency.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Turns out that OpenSSL 1.0.2 does not actually use makedepend on macOS. Checking the sources, its [Configure](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/Configure#L1676-L1679) script sets `MAKEDEPPROG` in the Makefile to the compiler on systems where `__clang__` is defined, i.e. OS X 10.7 and later. (See what is defined for your compiler with `cc -dM -E -x c /dev/null 2>&1`.)

In fact, if after running Configure manually you edit the Makefile to `MAKEDEPPROG= makedepend` and then run `make depend`, you'll find it doesn't work for recent version of OpenSSL 1.0.2. For some reason, its `util/domd` script now [strips out](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/util/domd#L7-L14) the `--` arguments that separate compiler flags from makedepend's own flags, causing errors like `makedepend: error:  "no-common" is not present`. This is fixed by setting `MAKEDEPPROG` for OS X 10.5 & 10.6.

The newest compiler on OS X 10.5 is GCC 4.2, which works fine. On 10.6, `make test` will fail (#2766) because superenv is redirecting all compilation to `clang`, even though the output of `brew --env` suggests that it would use `gcc-4.2` (LLVM-GCC). The simplest fix is to use the standard env and specify the compiler for `make` only for 10.6, which avoids another issue where the compiler doesn't understand `-march=native`, even though this offends`brew audit --strict`. 

This continues work to get Homebrew working on older systems (Homebrew/install#154, Homebrew/brew#5238). CC @MikeMcQuaid as requested.

2018-11-21 08:45 UTC, MikeMcQuaid commented on Formula/openssl.rb
> +    depend_args = []
Could you add a comment above this linking to the relevant issue and explaining why it shouldn't be deleted (i.e. we need to keep 10.5 working for building portable Ruby).

2018-11-22 05:50 UTC, EricFromCanada commented
Was originally going to add this to the `curl` formula, but figured it's better suited here: added a `resource` block for a list of updated CA certificates for use by OpenSSL. This is needed on 10.5 because its list of built-in certs are by now very out of date, and on 10.6 because the `security` command for some reason produces no output when run within the formula.

2018-11-22 21:40 UTC, sjackman commented
> It's the same file used by Linuxbrew's curl, but from a different CDN given that rawgit.com is on borrowed time. @sjackman

Thanks for the heads up, Eric.

> GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served. If you're currently using RawGit, please stop using it as soon as you can.

https://rawgit.com

2018-11-22 21:43 UTC, sjackman requested changes

2018-11-22 21:43 UTC, sjackman commented on Formula/openssl.rb
> +  resource "ca-bundle" do
Shall we use the most recent certs?
https://curl.haxx.se/ca/cacert-2018-10-17.pem

2018-11-22 22:07 UTC, EricFromCanada commented
I picked the same file being used by [Tigerbrew's formula](https://github.com/mistydemeo/tigerbrew/blob/master/Library/Formula/curl-ca-bundle.rb), but it looks like that was the most recent file when it was last edited. So using the latest is probably ideal.

2018-11-22 22:08 UTC, EricFromCanada commented on Formula/openssl.rb
> +  resource "ca-bundle" do
I picked the same file being used by [Tigerbrew's formula](https://github.com/mistydemeo/tigerbrew/blob/master/Library/Formula/curl-ca-bundle.rb), but it looks like that was the most recent file when it was last edited. So using the latest is probably ideal.

2018-11-24 15:45 UTC, EricFromCanada commented on Formula/openssl.rb
> +    if MacOS.version > :snow_leopard
Is `>=` and `<=` always preferred for clarity when checking `MacOS.version`? There's 14 and 46 other occurrences of `>` and `<` currently in `homebrew-core`; might be something for the to-do list and/or style guide.

2018-11-24 15:48 UTC, MikeMcQuaid commented on Formula/openssl.rb
> +    if MacOS.version > :snow_leopard
Personally I think they are clearer but others may vary. Feel free to make up your own mind here on whatever is the most readable to someone without our encylopedic knowledge of macOS versions 😂 , I don't feel strongly.

2018-11-24 16:40 UTC, EricFromCanada commented on Formula/openssl.rb
> +    args = []
I separated them with their own comments in a group with the `args` block, which is also defined before calling `./Configure`.

2018-11-24 21:48 UTC, MikeMcQuaid approved these changes

2018-11-25 12:45 UTC, MikeMcQuaid commented
Thanks again @EricFromCanada!

2018-11-25 12:46 UTC, closed without merging

2018-11-25 17:08 UTC, sjackman commented on Formula/openssl.rb
> +    if MacOS.version > :snow_leopard
I prefer `if MacOS.version >= x` and `if MacOS.version < x`, where a feature was introduced in version `x`, and you're testing whether that feature is present or absent.