lsd 0.11.1
Homebrew/homebrew-core pull request #35541
Opened 2018-12-29 18:54 UTC by colindean

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2018-12-30 14:21 UTC, fxcoudert requested changes

2018-12-30 14:21 UTC, fxcoudert commented on Formula/lsd.rb
> +  def caveats; <<~EOS
We reserve `caveats` for Homebrew-specific information. This is generic documentation, not specific to Homebrew, so the `caveats` should be removed.

2019-01-07 11:33 UTC, fxcoudert approved these changes

2019-01-07 11:33 UTC, fxcoudert commented
@BrewTestBot test this please

2019-01-10 16:17 UTC, fxcoudert commented
@colindean I went ahead and merged, I hope you don't mind

2019-01-10 16:18 UTC, closed without merging

2019-01-10 16:19 UTC, colindean commented
Not at all! I don't think I have commit bit on this repo.

2019-01-10 16:20 UTC, fxcoudert commented
Oh, I thought the “member” badge was linked to commit rights, but it's not. Sorry.