smartmontools.rb: Update smartmontools to 7.0
Homebrew/homebrew-core pull request #35635
Opened 2019-01-02 11:18 UTC by samm-git

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

- Update to smartmontools 7.0

2019-01-02 11:26 UTC, fxcoudert requested changes

2019-01-02 13:40 UTC, samm-git commented on Formula/smartmontools.rb
> -    sha256 "abc4564708c21e53dfd57d668665e42624bc9e740befe72b6b20bb9039e29ef4" => :mojave
@fxcoudert thank you, i reverted bottle block

2019-01-03 10:08 UTC, fxcoudert approved these changes

2019-01-03 10:09 UTC, fxcoudert commented
Thanks @samm-git

2019-01-03 10:10 UTC, closed without merging