tmuxinator 0.15.0 (new formula)
Homebrew/homebrew-core pull request #35938
Opened 2019-01-12 16:20 UTC by simobasso

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
ref: https://github.com/tmuxinator/tmuxinator
ref: https://github.com/Homebrew/homebrew-core/pull/34043
ref: https://github.com/tmuxinator/tmuxinator/issues/563

2019-01-13 11:22 UTC, javian requested changes

2019-01-13 21:52 UTC, igas commented on Formula/tmuxinator.rb
> +    assert_match "tmuxinator projects:", list_output
after you created `test` project you are not checking it here.

2019-01-14 14:43 UTC, simobasso commented
Hi @javian and @igas, thanks for the reviews. I have just updated the pr with your suggestions. 🎉

2019-01-17 22:44 UTC, javian requested changes

2019-01-17 22:44 UTC, javian commented on Formula/tmuxinator.rb
> +  depends_on "tmux"
There should be an empty line here.

2019-01-17 22:44 UTC, javian commented on Formula/tmuxinator.rb
> +    system "gem", "build", "tmuxinator.gemspec"
This creates an issue that the dependencies are not versioned. If you look at the `travis.rb` formula you can see that the gems are listed as resources which the gem is then build from and something similar would be needed here to make reproducible builds. Can you arrange that ?

2019-02-14 23:26 UTC, closed without merging