cryfs: trigger bottle rebuild
Homebrew/homebrew-core pull request #35958
Opened 2019-01-13 19:33 UTC by smessmer

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This fixes https://github.com/Homebrew/homebrew-core/issues/35947

2019-01-13 19:38 UTC, freedom1400 commented
Watsa people

2019-01-15 15:14 UTC, fxcoudert commented
Can we add a test that looks at what library this is linked against?

2019-01-22 09:45 UTC, MikeMcQuaid requested changes
Nice work on the test!

2019-01-22 09:45 UTC, MikeMcQuaid commented on Formula/cryfs.rb
> +        assert_match "Mounting filesystem", pipe_output("#{bin}/cryfs -f \"#{basedir}\" \"#{mountdir}\"", "password")
- Can use `2>&1` to avoid printing error messages. 
- Can use single quotes to avoid needing to escape the `"`

2019-01-22 09:45 UTC, MikeMcQuaid commented on Formula/cryfs.rb
> +    print("Note: A permission error in the previous line is expected and still counts as successful test run\n")
Can remove this.

2019-01-27 22:12 UTC, smessmer commented on Formula/cryfs.rb
> +      Dir.mktmpdir do |mountdir|
It could be, but I think `mktmpdir` is better because it automatically cleans up after the block is exited.

2019-01-27 22:19 UTC, smessmer commented
Thanks. I addressed your comments.

Btw, there was a new upstream release 0.9.10. So instead of bumping the revision number, I switched to the new upstream release.

2019-01-28 06:33 UTC, SMillerDev commented
@Brewtestbot test this please

2019-01-28 08:06 UTC, smessmer commented
CI fails with a "directory not empty" error message. Not sure how to fix this, maybe actually a but in homebrew, see https://github.com/Homebrew/brew/issues/4989

2019-01-30 08:45 UTC, smessmer commented
ok tests seem to have passed now, thanks. Can we merge this?

2019-01-30 14:00 UTC, MikeMcQuaid commented
@smessmer Can you remove the `mktmpdir` first? Thanks!

2019-01-31 08:37 UTC, MikeMcQuaid commented
Installation failing on High Sierra with what looks like a Boost issue: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/37186/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install_cryfs/

2019-01-31 12:56 UTC, MikeMcQuaid approved these changes

2019-01-31 12:56 UTC, MikeMcQuaid commented
Reran it and it was fine 🎉.

Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @smessmer!

2019-01-31 12:56 UTC, closed without merging