GNU Solfege 3.22.2 (new formula)
Homebrew/homebrew-core pull request #35953
Opened 2019-01-13 17:12 UTC by ram-on

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Added GNU Solfege 3.22.2 formula.

2019-01-13 21:54 UTC, ram-on commented
>     * Formulae should not have optional or recommended dependencies
> 
>     * Formulae should not have optional or recommended dependencies
> 
>     * Formulae should not have optional or recommended dependencies

Hi @fxcoudert. Is the above a must have?  (Since the Formula Cookbook does not discourage the usage of `:optional` and `:recommended`...)

2019-01-14 17:01 UTC, ram-on commented
@SMillerDev timidity was added as`:recommended` since it can be replaced by mpg123 or vorbis-tools (hence the `:optional` "tag")

2019-02-07 18:19 UTC, ram-on commented
Can anyone please merge this?

2019-02-08 22:59 UTC, fxcoudert requested changes

2019-02-08 22:59 UTC, fxcoudert commented on Formula/solfege.rb
> +  depends_on "timidity"     => :recommended
Make `timidity` mandatory, remove the options below.

2019-02-08 22:59 UTC, fxcoudert commented on Formula/solfege.rb
> +    inreplace "Makefile.in", "cp --parents", "rsync -R"
Why?

2019-02-08 22:59 UTC, fxcoudert commented on Formula/solfege.rb
> +    inreplace "default.config", "/usr/bin/", "#{HOMEBREW_PREFIX}/bin/"
Shouldn't this be done already by running `configure` with `prefix`? If not, report it as a bug.

2019-02-08 22:59 UTC, fxcoudert commented on Formula/solfege.rb
> +    system "#{bin}/solfege", "--version"
We need a test that exercises the some of the functionality of the app.

2019-02-08 22:59 UTC, fxcoudert commented on Formula/solfege.rb
> +    inreplace "solfege/mainwin.py", "webbrowser.open(filename)", "webbrowser.open(\"file://\" + filename)"
Was this bug reported?

2019-03-08 23:55 UTC, closed without merging