subversion: replace deprecated scons call (follow-up to 4fc4bf16)
Homebrew/homebrew-core pull request #36113
Opened 2019-01-17 12:26 UTC by brainy

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
There was still one build warning remaining:
> Warning: Calling scons is deprecated! Use system "scons" instead.

2019-01-17 12:56 UTC, SMillerDev approved these changes

2019-01-18 12:18 UTC, fxcoudert requested changes

2019-01-18 12:18 UTC, fxcoudert commented on Formula/subversion.rb
> +  revision 1
Revision is not necessary, please remove.

2019-01-18 12:18 UTC, fxcoudert commented on Formula/subversion.rb
> +      system "scons", *args
Could you also, as three separate commits in this same PR, do the same change in `subversion@1.8`, `libswiften` and `wesnoth`?

2019-01-20 00:12 UTC, fxcoudert commented
Thanks @brainy, since `scons` call is deprecated and the tests are already failing, it makes little sense to keep it that way anyway.

2019-01-20 00:12 UTC, closed without merging