BUG:  CMake find_package(TBB) mechanisms were broken
Homebrew/homebrew-core pull request #36175
Opened 2019-01-19 15:42 UTC by hjmjohnson

Installing tbb in the homebrew prefered directory
layout caused cmake config based file management
to fail.

The bug was reported to upstream https://github.com/01org/tbb as
PR#119 to provide the flexibility needed to meet
the non-default (but intended modifiable) install location
of the TBBConfig.cmake file.

A temporary patch was added that implements the contents
of PR#119.

A set of tests was added to confirm that the desired
functionality also exists.

2019-01-21 19:28 UTC, MikeMcQuaid requested changes

2019-01-21 21:39 UTC, hjmjohnson commented
The TBB team does not use github in a standard way.  They take recommendations from github into their private repository manually, and every few months push  a tarball of the changed content to github via a new branch designation.

I think think your recommended patch solution wil be reliable over time.

2019-01-22 09:40 UTC, MikeMcQuaid commented
@hjmjohnson Thanks for explaining. I'd still rather the comment was moved and `patch do` was used (unless the patch won't apply in that case).

2019-02-14 14:58 UTC, hjmjohnson commented
This is still an issue that needs to be addressed.
 I'm working with TBB group to get a better resolution.

2019-02-16 13:55 UTC, fxcoudert commented
The fix really does not appear to be straightforward, given the extensive discussion taking place upstream. I am closing this for now, we can ship the fix when it is decided and committed (or in the next released version).

2019-02-16 13:55 UTC, closed without merging