sphinx-doc: move to Python 3
Homebrew/homebrew-core pull request #36202
Opened 2019-01-20 20:52 UTC by zmwangx

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Sphinx was originally developed to generate documentation for CPython. Say whatever you want about Apple's inertia to move to Python 3, from my perspective when the Sphinx we ship cannot build CPython documentation (#33224), something is just wrong. Python 2.7 EOL is less than a year from not, the py27-based version cannot be shipped forever, so now is as good a time as any. It's kinda ironic that `python@2` has its documentation built but the default `python` does not, due to `sphinx-doc` stuck with, guess what, python@2.

Certain formulae that depends on `"sphinx-doc" => :build` might break if their Sphinx conf is still incompatible with Python 3 (shouldn't be hard to fix at all), or they insist onto tapping into Sphinx from a python2.7 executable instead of just calling `sphinx-build`. But they really should up their game. Alternatively, a `sphinx-doc-python2` formula may be provided to keep those who are stuck in the past happy, but that's a really bad idea.

2019-01-20 23:18 UTC, Moisan commented
Audit issue with sphinx-doc:
```
  * C: 24: col 3: Formulae using virtualenvs do not need a `setuptools` resource.
```

2019-01-21 14:35 UTC, fxcoudert approved these changes

2019-01-21 14:36 UTC, fxcoudert requested changes

2019-01-21 14:36 UTC, fxcoudert commented on Formula/sphinx-doc.rb
> +  depends_on "python"
`sphinx-doc` needs a `revision 1` added after the `sha256` line.

2019-01-21 18:02 UTC, fxcoudert commented
Thanks @zmwangx

2019-01-21 18:02 UTC, fxcoudert approved these changes

2019-01-21 18:03 UTC, closed without merging