anyenv 1.0.0 (new formula)
Homebrew/homebrew-core pull request #36257
Opened 2019-01-22 04:18 UTC by riywo

Add anyenv (retry of #36183 )

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Now I transferred notable repository and there is no error from audit.

2019-01-22 08:29 UTC, fxcoudert requested changes

2019-01-22 09:08 UTC, riywo commented on Formula/anyenv.rb
> +  def caveats
It is removed in the new commit.

2019-01-22 09:08 UTC, riywo commented on Formula/anyenv.rb
> +    shell_output("eval \"$(#{bin}/anyenv init -)\" && anyenv --version")
I added more integrated tests in the latest commit.

2019-01-22 09:10 UTC, riywo commented
Thank you for the review. I've addressed two comments in the latest commit.

2019-01-22 15:46 UTC, riywo commented
@fxcoudert Why is this stuck pending?

2019-01-25 05:16 UTC, riywo commented
@fxcoudert Is there any clue to address the failure? `brew test anyenv` is passing on my local laptop.

2019-01-25 07:03 UTC, SMillerDev commented
The audit is failing, not the `brew test`

2019-01-25 15:02 UTC, riywo commented
@SMillerDev Thanks, I fixed audit errors and now it has passed.

2019-01-25 16:23 UTC, SMillerDev commented
@fxcoudert happy with these changes?

2019-01-26 17:48 UTC, riywo commented
@fxcoudert Do I still need to change anything?

2019-01-29 07:49 UTC, fxcoudert approved these changes

2019-01-29 09:14 UTC, fxcoudert commented
Thanks @riywo for the pull request

2019-01-29 09:16 UTC, closed without merging