cafeobj 1.5.9 (new formula)
Homebrew/homebrew-core pull request #36502
Opened 2019-01-29 08:19 UTC by norbusan

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
I have tried to run this on my Linuxbrew but without success:
```
$ brew audit --strict Formula/cafeobj.rb 
==> Installing or updating 'bundler' gem
Error: Unable to resolve dependency: user requested 'did_you_mean (= 1.2.1)'
```

-----

CafeOBJ has been installed via a third party tap maintained by me in several computers already, now I would like to include it into the main Brew repository. As I am maintaining CafeOBJ and have provided (mac)ports installation options as well as Debian packages, I would like to see a brew formula, too.

I would also like to add bottles, but without a Mac computer I *think* I cannot do this.

Thanks

Norbert

2019-01-29 08:19 UTC, lembacon commented on Formula/cafeobj.rb
> +  revision 1
Please remove this line.

2019-01-29 13:16 UTC, fxcoudert commented
```
  * Stable: The URL http://cafeobj.org/files/1.5.9/cafeobj-1.5.9.tar.gz should use HTTPS rather than HTTP
  * fully scope test system calls e.g. system "#{bin}/cafeobj"
  * Emacs Lisp files were linked directly to /usr/local/share/emacs/site-lisp
    This may cause conflicts with other packages.
    They should instead be installed into:
    /usr/local/opt/cafeobj/share/emacs/site-lisp/cafeobj
    
    The offending files are:
      /usr/local/opt/cafeobj/share/emacs/site-lisp/cafeobj-mode.el
```

2019-01-29 21:19 UTC, norbusan commented
Dear all,

I have fixed the following items:

> ```
>   * Stable: The URL http://cafeobj.org/files/1.5.9/cafeobj-1.5.9.tar.gz should use HTTPS rather than HTTP
>   * fully scope test system calls e.g. system "#{bin}/cafeobj"
> ```

But I think the check for this:
> ```
>   * Emacs Lisp files were linked directly to /usr/local/share/emacs/site-lisp
>     This may cause conflicts with other packages.
>     They should instead be installed into:
>     /usr/local/opt/cafeobj/share/emacs/site-lisp/cafeobj
> ```

is wrong. I tried here on my own system
```
$ ./configure --with-lisp=sbcl --prefix=/usr/local/
...
$ make
...
$ make install prefix=/foo/bar/baz/
...
```
and this installed the elisp file correctly into `/foo/bar/baz/share/emacs/cafeobj.el`.

I am a bit at loss what is the problem here?

Thanks for your comments

Norbert

2019-02-20 08:48 UTC, norbusan commented
Can someone explain me how the installation is actually carried out (which arguments of make are used, which env vars) so that I can try to reproduce this?

2019-02-20 12:29 UTC, SMillerDev commented
You could run the install with `--debug`. You can also run `brew audit` locally

2019-02-21 09:03 UTC, norbusan commented
@SMillerDev thanks, I have now fixed the recipe and all checks have passed.

2019-02-25 22:14 UTC, javian commented
@BrewTestBot test this please

2019-02-25 22:17 UTC, javian commented
Just noted that the github page has very low stats https://github.com/CafeOBJ/cafeobj - is this a blocker ?

2019-02-25 23:33 UTC, norbusan commented
> Just noted that the github page has very low stats https://github.com/CafeOBJ/cafeobj - is this a blocker ?

Just to comment on this: this project is now nearly 30 years old, was long years developed in private, then for many years on `git.cafeobj.org`, and we only recently moved to github.

In addition, as an algebraic specification language it can hardly compete with other projects ;-)

2019-02-26 06:21 UTC, SMillerDev commented
If it passes the audit that's fine by me.

2019-02-26 09:00 UTC, fxcoudert requested changes

2019-02-26 09:12 UTC, norbusan commented on Formula/cafeobj.rb
> +    system "#{bin}/cafeobj", "-batch"
Testing whether CafeOBJ can be started and initialized. This already loads the preamble of CafeOBJ. It is a basic functionality test, that returns 0 on success.

2019-02-26 09:49 UTC, fxcoudert commented on Formula/cafeobj.rb
> +    system "#{bin}/cafeobj", "-batch"
Great

2019-02-26 09:49 UTC, fxcoudert approved these changes

2019-02-26 09:52 UTC, fxcoudert commented
Thanks @norbusan for contributing this formula to Homebrew!

2019-02-26 09:52 UTC, closed without merging

2019-02-26 11:52 UTC, norbusan commented
@fxcoudert Thanks for accepting this formula, I will keep it updated!
Thanks everyone for the feedback in improving and fixing the formula.

Thanks

Norbert