ffmpeg: GNU Transport Layer Security library req. added.
Homebrew/homebrew-core pull request #36803
Opened 2019-02-07 23:38 UTC by JuPlutonic

https://github.com/Homebrew/homebrew-core/pull/36327#issuecomment-459710380
gnutls depends on gmp, libtasn1, libunistring, nettle and p11-kit those are totally about 35-36 Mb.
Trigger on videotoolbox added, because we didn't implement Core* libraries for other OSes. Tested, Ok!
 brew audit --strict - Ok!

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2019-02-07 23:40 UTC, JuPlutonic commented
RE:@JuPlutonic its actually you that need to fix the merge conflict since the ffmpeg formula has had changes made to it that conflicts with yours. Can you make the adjustments and we can try again ?

Now conflicts are clean. Last PR is closed because I deleted directory / .git.

2019-02-08 07:30 UTC, fxcoudert requested changes

2019-02-08 07:30 UTC, fxcoudert commented on Formula/ffmpeg.rb
> + bottle do
Do not touch the `bottle` block

2019-02-08 19:22 UTC, fxcoudert commented
This is not a heavy dependency, so I'm merging. Thanks @JuPlutonic  for the pull request.

2019-02-08 19:23 UTC, merged

2019-02-08 19:24 UTC, fxcoudert commented
Rebuilding bottle: https://jenkins.brew.sh/job/Homebrew%20Testing/1150/

2019-02-08 20:28 UTC, fxcoudert commented
And bottle merged: https://github.com/Homebrew/homebrew-core/commit/1087d671f307e1f0ebd7f22e7d7fa6e0029f7251