[WIP]new formula: spirv-cross 2019-01-31
Homebrew/homebrew-core pull request #36875
Opened 2019-02-10 13:51 UTC by yurikoles

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-02-11 14:42 UTC, yurikoles commented
@fxcoudert could you merge this please?

2019-02-16 12:36 UTC, fxcoudert requested changes

2019-02-16 12:36 UTC, fxcoudert commented on Formula/spirv-cross.rb
> +    cp_r "#{prefix}/samples/cpp", testpath.to_s
```suggestion
    cp_r Dir[prefix/"samples/cpp/*"], testpath
```

and then we don't have to `cd`

2019-02-16 13:46 UTC, fxcoudert approved these changes

2019-02-16 13:47 UTC, closed without merging