sha3sum 1.1.5 (new formula)
Homebrew/homebrew-core pull request #37013
Opened 2019-02-15 18:15 UTC by zbeekman

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-02-15 18:19 UTC, zbeekman commented
FYI @maandree, @danteu, @nremond, @cleishm: `libkeccak` has been added to homebrew-core and this PR will add `sha3sum`. To port these to linuxbrew I'll need to figure out which of the build and runtime dependencies listed in the respective `DEPENDENCIES` file in each repo will need to be installed through linuxbrew; probably all of them.

2019-02-15 18:52 UTC, sjackman requested changes

2019-02-15 18:52 UTC, sjackman commented on Formula/sha3sum.rb
> +    inreplace "test", "./", ""
```suggestion
    inreplace "test", "./", "#{bin}/"
```

2019-02-15 18:57 UTC, zbeekman commented on Formula/sha3sum.rb
> +    inreplace "test", "./", ""
Good call!

2019-02-15 19:00 UTC, sjackman approved these changes

2019-02-15 19:22 UTC, closed without merging

2019-02-15 21:58 UTC, nremond commented
That is really great!
Thank you

> On 15 Feb 2019, at 19:19, zbeekman <notifications@github.com> wrote:
> 
> FYI @maandree <https://github.com/maandree>, @danteu <https://github.com/danteu>, @nremond <https://github.com/nremond>, @cleishm <https://github.com/cleishm>: libkeccak has been added to homebrew-core and this PR will add sha3sum. To port these to linuxbrew I'll need to figure out which of the build and runtime dependencies listed in the respective DEPENDENCIES file in each repo will need to be installed through linuxbrew; probably all of them.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/Homebrew/homebrew-core/pull/37013#issuecomment-464148482>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAkoJiSVsucOgOC3vfYI3EzYQURTLrciks5vNvpGgaJpZM4a-LZT>.
>

2019-02-16 01:24 UTC, zbeekman commented
> To port these to linuxbrew I'll need to figure out which of the build and runtime dependencies listed in the respective `DEPENDENCIES` file in each repo will need to be installed through linuxbrew; probably all of them.

It looks like all build and runtime deps are actually included by default with linuxbrew, so the next time homebrew-core is pulled into Linuxbrew these will get picked up, and should just work™️