dcos-cli 0.7.9
Homebrew/homebrew-core pull request #37074
Opened 2019-02-18 17:43 UTC by rgo3

This update includes a language change from Python to Go.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-02-18 19:07 UTC, fxcoudert requested changes

2019-02-18 19:07 UTC, fxcoudert commented on Formula/dcos-cli.rb
> +    assert_match "dcoscli.version=0.7.9", run_output
It would be nice to have a test that exercises the some of the functionality of the app.

2019-02-18 19:07 UTC, fxcoudert commented on Formula/dcos-cli.rb
> +      system "make", "core-download"
This is downloading binaries: https://github.com/dcos/dcos-cli/blob/master/Makefile#L31
Not acceptable for Homebrew core.

2019-02-19 16:19 UTC, rgo3 commented
@fxcoudert All 0.7.x dcos-cli versions require the download of these binaries to bundle them with `go-bindata`. This will be removed in the next minor release (0.8) which will make it possible to remove these build steps in a homebrew formula. Until this release happens the version bump of `dcos-cli` on homebrew-core needs to be postponed I think. Thanks for the fast review!

2019-02-19 16:19 UTC, closed without merging