ydcv: update to 0.6.2
Homebrew/homebrew-core pull request #37120
Opened 2019-02-20 10:49 UTC by ideal

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-02-20 11:13 UTC, fxcoudert commented
```
==> /usr/local/Cellar/ydcv/0.6.2/bin/ydcv 你好
Traceback (most recent call last):
  File "/usr/local/Cellar/ydcv/0.6.2/bin/ydcv", line 96, in <module>
    _re_non_english = re.compile(r'[^\w]', re.ASCII)
AttributeError: 'module' object has no attribute 'ASCII'
Error: ydcv: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

2019-02-20 14:29 UTC, ideal commented
That is because ydcv references an attribute of `re` but it is only available in python 3.
I'll check how to fix it.

2019-02-21 18:24 UTC, fxcoudert requested changes

2019-02-21 18:24 UTC, fxcoudert commented on Formula/ydcv.rb
>    bottle :unneeded
Remove the `bottle` line

2019-02-22 01:53 UTC, ideal commented on Formula/ydcv.rb
>    bottle :unneeded
OK, removed.

2019-02-22 07:25 UTC, fxcoudert approved these changes

2019-02-22 07:26 UTC, fxcoudert commented
Thanks @ideal

2019-02-22 09:42 UTC, closed without merging