h3 3.4.2 (new formula)
Homebrew/homebrew-core pull request #37174
Opened 2019-02-22 18:08 UTC by robsalasco

H3 is a geospatial indexing system using a hexagonal grid

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-02-22 19:52 UTC, fxcoudert requested changes

2019-02-22 19:52 UTC, fxcoudert commented on Formula/h3.rb
> +    result = `echo '40.689167 -74.044444' | geoToH3 10 | md5`.chomp
```suggestion
    result = pipe_output("#{bin}/geoToH3 10", "40.689167 -74.044444")
    assert_equal "8a2a1072b59ffff", result.chomp
```

2019-02-22 19:52 UTC, fxcoudert requested changes

2019-02-22 19:52 UTC, fxcoudert commented on Formula/h3.rb
> +  depends_on "cmake" => :build
Blank line above `depends_on`

2019-02-23 08:47 UTC, fxcoudert commented
If you can squash all commits into a single one, with message `h3 3.4.2 (new formula)`, we'll be ready to ship!

2019-02-23 08:47 UTC, fxcoudert approved these changes

2019-02-23 16:23 UTC, fxcoudert commented
Many thanks @robsalasco for your contribution to Homebrew!

2019-02-23 16:24 UTC, closed without merging

2019-02-23 16:38 UTC, robsalasco commented
Thank you for your comments @fxcoudert!