GCC 8.3
Homebrew/homebrew-core pull request #37171
Opened 2019-02-22 17:15 UTC by DesWurstes

I haven't built it.

2019-02-22 17:43 UTC, fxcoudert requested changes
Changes should be squashed into a single commit, with message `gcc 8.3.0`

2019-02-22 17:43 UTC, fxcoudert commented on Formula/gcc.rb
>    stable do
Please remove the `stable do` block, and move the `url`, `mirror` and `sha256` fields above `head`.

2019-02-22 17:43 UTC, fxcoudert commented on Formula/gcc.rb
> +    rebuild 1
Do not touch this.

2019-02-22 19:48 UTC, fxcoudert approved these changes

2019-02-22 22:59 UTC, zbeekman submitted a review, later dismissed
Failing tests. `nwchem` uses ancient style Fortran, maybe gcc 8.3 legitimately broke it, or maybe it just needs a revision bump. The python failures on high-sierra are suspect. Not sure what is going on there. We should resolve the failures before we ship this.

2019-02-22 23:06 UTC, zbeekman commented
I gave `libbi` and `nwchem` a revision bump to see if that resolves the issue.

2019-02-24 16:03 UTC, fxcoudert commented
`libbi` test is preexisting, sadly. I've reported it upstream: https://github.com/lawmurray/LibBi/issues/45

We've already rev-bumped that formula twice in 1 month: https://github.com/Homebrew/homebrew-core/pull/36335 and https://github.com/Homebrew/homebrew-core/pull/36432 to get rid of this test failure. We probably need to understand what is happening.

2019-02-24 16:06 UTC, fxcoudert commented
Let's run the `libbi` test without OpenMP, which succeeds:

```
diff --git a/Formula/libbi.rb b/Formula/libbi.rb
index fd44f89ae1..f85388738a 100644
--- a/Formula/libbi.rb
+++ b/Formula/libbi.rb
@@ -137,7 +137,7 @@ class Libbi < Formula
 
   test do
     cp Dir[pkgshare/"Test.bi", pkgshare/"test.conf"], testpath
-    system "#{bin}/libbi", "sample", "@test.conf"
+    system "#{bin}/libbi", "sample", "@test.conf", "--disable-openmp"
     assert_predicate testpath/"test.nc", :exist?
   end
 end
```

2019-02-24 22:51 UTC, fxcoudert commented
Thanks @DesWurstes

2019-02-24 22:53 UTC, closed without merging

2019-02-24 23:37 UTC, JayBrown commented
Failed to build on Mojave:

```
Last 15 lines from ~/Library/Logs/Homebrew/gcc/02.make:
cc1plus: warning: -Wabi won't warn about anything [-Wabi]
cc1plus: note: -Wabi warns about differences from the most up-to-date ABI, which is also used by default
cc1plus: note: use e.g. -Wabi=11 to warn about changes from GCC 7
../../../../../libstdc++-v3/src/filesystem/path.cc:29:10: fatal error: experimental/filesystem: No such file or directory
 #include <experimental/filesystem>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[6]: *** [path.lo] Error 1
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [all-recursive] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-stage2-target-libstdc++-v3] Error 2
make[1]: *** [stage2-bubble] Error 2
make: *** [all] Error 2
```

Doctor output: `Warning: Skipping gcc: most recent version 8.3.0 not installed
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!`

2019-02-25 09:07 UTC, fxcoudert commented
@JayBrown does installing the bottle work for you?

2019-02-25 11:04 UTC, JayBrown commented
Just tested it with `brew upgrade --force-bottle gcc`, and it works. One of the reasons that brew wanted to build it from source was seemingly that it was unable to detect the Command Line Tools. I have installed Xcode, the CLT are there too, but brew doesn't seem to notice. (?)

2019-02-25 15:13 UTC, zbeekman commented
Not sure it this applies to you, but after upgrading to Mojave, I believe you need to (re)install CLT/XCode.