circleci cli: install packr as a homebrew resource
Homebrew/homebrew-core pull request #37170
Opened 2019-02-22 14:20 UTC by eric-hu

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I've been unable to run the brew testing commands locally due to `brew audit` and `brew test` having some issues installing the `json` gem. I'm hoping that opening this PR might trigger the test suite to run on CI.

I've collaborated with @zzak to take a different approach from [this PR](https://github.com/Homebrew/homebrew-core/pull/36546), but towards the same goal.

I'll try to get this tested locally in the next week.

2019-02-22 17:10 UTC, fxcoudert requested changes

2019-02-22 17:10 UTC, fxcoudert commented on Formula/circleci.rb
> +    "https://github.com/gobuffalo/packr/releases/download/v2.0.1/packr_2.0.1_darwin_amd64.tar.gz"
`url` and `sha256`

2019-02-22 17:10 UTC, fxcoudert commented on Formula/circleci.rb
> +    "https://github.com/gobuffalo/packr/releases/download/v2.0.1/packr_2.0.1_darwin_amd64.tar.gz"
But no, please do not download binaries.

2019-02-26 08:54 UTC, eric-hu commented
Thank you for your quick review @fxcoudert . I'm closing this PR as the approach I was taking wasn't as simple as I thought it would be. I'll discuss this with @zzak when he's back from vacation.

2019-02-26 08:54 UTC, closed without merging