motion 4.2.2 (new formula)
Homebrew/homebrew-core pull request #37183
Opened 2019-02-22 22:59 UTC by alebcay

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This formula was requested in #37001.

2019-02-23 13:29 UTC, fxcoudert requested changes

2019-02-23 13:29 UTC, fxcoudert commented on Formula/motion.rb
> +    assert_match "motion Version #{version}", run_output
We need a test that exercises the some of the functionality of the app.

2019-02-23 13:29 UTC, fxcoudert commented on Formula/motion.rb
> +  sha256 "c8d40976b41da8eb9f9f7128599403a312fc26b7226bf3787d75f78cb5a6cc6e"
Blank line below `sha256`

2019-02-26 05:57 UTC, poorlymac commented on Formula/motion.rb
> +    mv prefix/"etc/motion/motion-dist.conf", prefix/"etc/motion/motion.conf"
Maybe mv -n to not overwrite an existing configuration file

2019-03-26 08:06 UTC, closed without merging