autogen 5.18.16
Homebrew/homebrew-core pull request #37227
Opened 2019-02-23 23:41 UTC by alebcay

Created with `brew bump-formula-pr`.

2019-02-23 23:48 UTC, mistydemeo commented
Patch doesn't apply to this release. Can you check if it's still necessary?

2019-02-23 23:54 UTC, alebcay commented
The `configure` script now looks for `guile` 2.2 as well as the previous 2.0 and 1.8, so it seems that the patch is no longer necessary.

2019-02-24 00:01 UTC, mistydemeo commented
Thank you!

Looks like there's an issue with `mktemp` now:

```
==> make
/bin/sh config/mk-shdefs config/shdefs
+ exec
++ mktemp --suffix=.tdir -d /tmp/shdefs-XXXXXXXXX
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
+ tmp=
+ exec
config/mk-shdefs: line 134: /mk-shdef.log: Operation not permitted
make: *** [config/shdefs] Error 1
```

I think they're using GNUisms; BSD `mktemp` doesn't have double dash options and doesn't have a suffix option.

2019-02-24 00:03 UTC, mistydemeo commented
Upstream bug report: https://sourceforge.net/p/autogen/bugs/189/ It's not resolved yet. We may have to patch this.

2019-02-24 00:11 UTC, mistydemeo commented
We can fix this for the time being by adding `depends_on "coreutils => :build`, then in the install method, `inreplace %w[agen5/mk-stamps.sh build-aux/run-ag.sh config/mk-shdefs.in], "mktemp", "gmktemp"`.

2019-02-24 00:15 UTC, alebcay commented
Gotcha. Would the preferred solution be to depend on `coreutils` for build or to patch out `mktemp --suffix=.tdir ...` invocations with `mktemp ...`?

2019-02-24 00:18 UTC, mistydemeo commented
Let's use coreutils; I feel slightly more nervous about the latter, because then we're doing stuff the buildsystem wasn't tested against. Thanks!

2019-02-24 00:27 UTC, mistydemeo requested changes

2019-02-24 00:27 UTC, mistydemeo commented on Formula/autogen.rb
> +    inreplace %w[agen5/mk-stamps.sh build-aux/run-ag.sh config/mk-shdefs.in], "mktemp", "gmktemp"
Thanks a lot for this! Can you include a link to the bug report above it? e.g.

```suggestion
    # Uses GNU-specific mktemp syntax: https://sourceforge.net/p/autogen/bugs/189/
    inreplace %w[agen5/mk-stamps.sh build-aux/run-ag.sh config/mk-shdefs.in], "mktemp", "gmktemp"
```

2019-02-24 00:30 UTC, mistydemeo approved these changes

2019-02-24 00:35 UTC, mistydemeo commented
Looks like another issue:

```
16:31:31 clang -DHAVE_CONFIG_H -I. -I..  -I.. -I../autoopts  -D_THREAD_SAFE -I/usr/local/Cellar/guile/2.2.4_1/include/guile/2.2 -I/usr/local/opt/gmp/include -I/usr/local/opt/readline/include -I/usr/local/opt/bdw-gc/include -g -O2 -Wno-format-contains-nul -fno-strict-aliasing -c -o autogen-ag.o `test -f 'ag.c' || echo './'`ag.c
16:31:31 In file included from ag.c:20:
16:31:31 ./expExtract.c:48:47: error: no member named 'st_mtim' in 'struct stat'
16:31:31         if (time_is_before(outfile_time, stbf.st_mtime))
16:31:31                                          ~~~~ ^
```

2019-02-24 01:33 UTC, mistydemeo commented
Thanks! I appreciate your patience on this.

2019-02-24 01:33 UTC, closed without merging

2019-02-24 01:36 UTC, alebcay commented
No problem! Thanks for helping out and also digging up the fixes for those issues.