gnu-getopt 2.32.1 (update and change source)
Homebrew/homebrew-core pull request #37661
Opened 2019-03-06 22:38 UTC by okdana

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The current `gnu-getopt` formula is derived from the project hosted by the original developer, which is seemingly no longer maintained — it has been merged into util-linux, and needed bug fixes can be found only there. Homebrew has a `util-linux` formula, but it can't provide `getopt` because it (`getopt`) has to be keg-only. So what i've done is rework the `gnu-getopt` formula to *also* build from util-linux.

I couldn't find anything in the Formula Cookbook, nor any existing examples in the repo, where two formulae were derived from the same project, so i'm not sure if there's a policy for this. My main concern is that updates to util-linux now have to be applied in two different places, which is kind of weird for maintenance. But they're completely independent of each other, so i guess in practice it'll probably work the same as any other formulae — when someone notices that an update to `gnu-getopt` is needed, they'll make the change.

Also, `util-linux`'s bottle section doesn't include Yosemite or Mavericks, and i assumed there was a technical reason for that, so i dropped them here too.

Is this OK?

2019-03-06 23:01 UTC, okdana commented
Actually, `curl` and `curl-openssl` are kind of the same idea as this (two formulae from the same project), so i guess there's precedent after all.

2019-04-05 15:32 UTC, zbeekman requested changes
I'm in favor of merging this, after some cleanup.

@okdana: Can you please amend your commit and force push, to address my comments?

Thanks!

2019-04-05 15:32 UTC, zbeekman commented on Formula/gnu-getopt.rb
> +# that offer independent subsets of util-linux
This comment text should be removed from the formula.

You can add it in the commit message below the standard formatting

2019-04-05 15:32 UTC, zbeekman commented on Formula/gnu-getopt.rb
> -    sha256 "27938c615808c8e4ff2eacac0a4059c76dee5518a5c8bbfb304b24b70736b429" => :mavericks
Please don't edit the `bottle do` block. This gets updated manually during the CI build process. If it needs adjustment after that it is the responsibility of maintainers to take care of that.

2019-04-05 15:32 UTC, zbeekman commented on Formula/gnu-getopt.rb
> -  depends_on "gettext"
Are you certain `gettext` is not required? Have you tested building and installing locally after uninstalling `gettext`?

2019-04-05 18:34 UTC, okdana commented
Thanks. Fixed the things you mentioned and rebased.

As far as `gettext`, i removed that because the `util-linux` formula doesn't use it. I think you *can* build it against `gettext`, but it isn't required. This is what it looks like when i build from the new formula without it:

```
% brew uninstall --ignore-dependencies gettext
Uninstalling /usr/local/Cellar/gettext/0.19.8.1... (1,935 files, 16.9MB)
% brew uninstall --force gnu-getopt
Uninstalling gnu-getopt... (10 files, 153.8KB)
% brew install --build-from-source gnu-getopt
==> Downloading https://www.kernel.org/pub/linux/utils/util-linux/v2.32/util-linux-2.32.1.tar.xz
Already downloaded: /Users/dana/Library/Caches/Homebrew/downloads/6b0e8abc3964fd06808baaff231cda1875526dd2a86b757eb142f816f0bb1685--util-linux-2.32.1.tar.xz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/gnu-getopt/2.32.1
==> make getopt
==> Caveats
gnu-getopt is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have gnu-getopt first in your PATH run:
  echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.zshrc


Bash completion has been installed to:
  /usr/local/opt/gnu-getopt/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/gnu-getopt/2.32.1: 10 files, 153.7KB, built in 1 minute 8 seconds
% /usr/local/opt/gnu-getopt/bin/getopt --version
getopt from util-linux 2.32.1
```

2019-04-05 20:18 UTC, zbeekman commented
hmmm this looks like a problem with our CI infra. I don't have time to fix the CI issue, gut this is good to go, as far as I am concerned... We'll see if any other @Homebrew/maintainers have issues with this, but I vote to ship it.

2019-04-05 21:41 UTC, sjackman commented
```
Error Message

failed: brew doctor
Stacktrace

        Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.
```
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/40445/version=mojave/testReport/brew-test-bot/mojave/doctor/

CI only failed on Mojave with this `brew doctor` failure. I believe we can safely ignore this failure and merge this PR.

2019-04-05 21:43 UTC, sjackman approved these changes
`/usr/bin/getopt` is provided by `util-linux` on Ubuntu. I'm in favour of merging this PR.
See https://packages.ubuntu.com/search?searchon=contents&keywords=%2Fbin%2Fgetopt&mode=&suite=bionic&arch=amd64

2019-04-08 12:24 UTC, zbeekman commented
@okdana: yes it’s a CI issue on our end. I’ll send this through for testing again once it’s fixed.

2019-04-08 14:06 UTC, zbeekman commented
@BrewTestBot test this please

2019-04-08 19:12 UTC, zbeekman commented
@BrewTestBot test this please

2019-04-08 19:13 UTC, zbeekman approved these changes
LGTM

2019-04-08 21:13 UTC, zbeekman commented
@BrewTestBot test this please

2019-04-08 23:36 UTC, closed without merging

2019-04-08 23:37 UTC, zbeekman commented
Thanks for your contribution to Homebrew, @okdana! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!