make formula for solr@7.7
Homebrew/homebrew-core pull request #37969
Opened 2019-03-16 12:53 UTC by hyuraku

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Now(March 16th, 2019), we can install solr@8 and solr@6 by brew install,
but we cannot do solr@7.
So, I add a formula for solr@7

2019-03-16 14:19 UTC, SMillerDev commented
Are all of these still supported upstream?

2019-03-16 15:22 UTC, hyuraku commented
@SMillerDev 
[Official Solr site](http://lucene.apache.org/solr/community.html#support) says below about support
>Apache Solr is under active development with frequent feature releases on the current major version. The previous major version may still receive security- and bug fixes as point releases, thus taking the role of the LTS (Long Term Support) version. Older versions are considered EOL (End Of Life) and will not be further updated. 

I thought Solr@8 and Solr@7 are supported but Solr@6 isn't supported.

2019-03-16 15:24 UTC, SMillerDev commented
Could you make this solr@7 then and remove solr@6?

2019-03-16 15:48 UTC, hyuraku commented
@SMillerDev 
Sure, and I have a question.
Which should I remove solr@6 in this PR or in another one?

2019-03-16 17:38 UTC, SMillerDev commented
I'd say this PR.

2019-03-18 15:14 UTC, fxcoudert requested changes

2019-03-18 15:14 UTC, fxcoudert commented on Formula/solr@7.7.rb
> -  keg_only :versioned_formula
Please restore `keg_only :versioned_formula`

2019-03-18 15:41 UTC, fxcoudert approved these changes

2019-03-19 08:28 UTC, closed without merging

2019-03-19 17:26 UTC, gmkey commented
The Apache Foundation has all versions prior to solr  6.4 are unsupported. So I guess solr@5.5 is obsolete, but Solr 6.6 isn’t!. Would it be possible to reinstate Solr 6.6?

Source:
http://lucene.apache.org/solr/community.html#support

2019-03-19 17:51 UTC, fxcoudert commented
This appears inconsistent, though:

> Solr 8.0.0 is the most recent Apache Solr release

and

> The previous major version may still receive security- and bug fixes as point releases, thus taking the role of the LTS (Long Term Support) version. Older versions are considered EOL (End Of Life) and will not be further updated.

So it simply looks like the webpage has not been updated. Clarification would be welcome.