nlohmann-json: 3.6.1 (new formula)
Homebrew/homebrew-core pull request #38257
Opened 2019-03-25 08:59 UTC by JarryShaw

`nlohmann/json` is a (seems) wildly used JSON
library for C++. The formula is directly migrated
from this [Tap](https://github.com/nlohmann/homebrew-json).
See: https://github.com/nlohmann/json

2019-03-25 09:10 UTC, SMillerDev commented
Optional dependencies are not acceptable in homebrew-core. I'd suggest just using cmake support.

2019-03-25 17:34 UTC, SMillerDev commented
You can drop the caveat now that there's no options anymore. And I don't think all the explanation in the test is required. Other maintainers might disagree though.

2019-03-26 09:16 UTC, JarryShaw commented
Ah… my bad 🤦‍♂️
Imma keep the tests for now and wait for u guys to review :)

2019-03-26 09:33 UTC, SMillerDev approved these changes

2019-03-26 13:17 UTC, fxcoudert requested changes

2019-03-26 13:17 UTC, fxcoudert commented on Formula/nlohmann-json.rb
> +        // instead, you could also write (which looks very similar to the JSON above)
Let's simplify the test. Remove comments, let's keep only a few objects in the json (say `pi`, `name`, `list` and `object`). Serialise the resulting json and match the output of that program (using `shell_output` and `assert_match`), so we exercise I/O as well.

2019-03-27 15:22 UTC, JarryShaw reviewed
Simplified tests based on review per @fxcoudert .

2019-03-27 15:41 UTC, fxcoudert commented
@JarryShaw I don't think you've pushed your changes to the test, they do not appear

2019-03-27 15:51 UTC, JarryShaw commented
> @JarryShaw I don't think you've pushed your changes to the test, they do not appear

Sorry again 🤦‍♂️ not familiar with this GitHub feature

2019-04-18 11:02 UTC, fxcoudert approved these changes

2019-04-18 11:03 UTC, fxcoudert commented
Thanks @JarryShaw this is looking good!

2019-04-18 16:38 UTC, closed without merging