Virgil-cli v5.0.1
Homebrew/homebrew-core pull request #38514
Opened 2019-03-29 17:04 UTC by golubovich

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-03-30 10:14 UTC, equal-l2 commented
When submitting a new formula, append `(new formula)` to the title, for ease of review by Homebrew maintainers.

2019-03-30 11:36 UTC, SMillerDev commented
Please stop making a new pull request for each revision of the formula. Just push a new commit to the branch instead.

2019-04-04 08:03 UTC, golubovich commented
@SMillerDev , take a look, please :)

2019-04-25 08:36 UTC, golubovich commented
ping %)

2019-04-25 08:37 UTC, golubovich commented
@lembacon could you take a look, please?

2019-04-25 08:39 UTC, SMillerDev commented on Formula/virgil.rb
> +  depends_on "dep" => :build
Please leave some whitespace here for readability.
```suggestion

    depends_on "dep" => :build
```

2019-04-25 08:39 UTC, SMillerDev commented on Formula/virgil.rb
> +  def install
Same here

2019-04-25 09:31 UTC, golubovich commented
@SMillerDev , fixed )

2019-05-06 07:21 UTC, golubovich commented
@lembacon, @SMillerDev could you take a look, please?

2019-05-07 13:16 UTC, golubovich commented
ping %)

2019-05-08 09:22 UTC, golubovich commented
@lembacon, @SMillerDev Hello :) 
I've noticed that more than a month has passed but my formula isn't merged yet. There hasn't been any new comments in the review for 13 days. Is there any other things I can do to get it merged?

2019-05-28 09:30 UTC, golubovich commented
ping )

2019-05-28 09:51 UTC, SMillerDev requested changes

2019-05-28 09:51 UTC, SMillerDev commented on Formula/virgil.rb
> +    result = `virgil pure keygen`
This is not a good way to call the function. Please use `shell_output()` like the other formulae.

2019-05-28 09:51 UTC, SMillerDev commented on Formula/virgil.rb
> +    assert_true result.start_with?("SK.1.")
Please use `assert_match` here like the other formulae

2019-06-03 04:17 UTC, SMillerDev approved these changes

2019-06-03 04:18 UTC, SMillerDev commented
Thanks @golubovich!

2019-06-04 17:07 UTC, closed without merging