kim-api (new formula) & openkim-models (new formula)
Homebrew/homebrew-core pull request #38535
Opened 2019-03-30 01:29 UTC by ellio167

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-04-14 16:24 UTC, ellio167 commented
Any thoughts on accepting this?

Once accepted, the kim-api package will be added as a dependency to the next release of the `lammps` package.

2019-04-24 21:44 UTC, ellio167 commented
@fxcoudert is this something you would be willing to look at?

2019-05-14 19:05 UTC, ellio167 commented
These packages are now available as official updates in the Fedora 28, 29, and 30 releases:

https://apps.fedoraproject.org/packages/kim-api
https://apps.fedoraproject.org/packages/openkim-models

It would be great to have them available for macOS too.

2019-05-31 11:42 UTC, ellio167 commented
@smillerdev does the ‘maintainer feedback’ label mean I need to do something? Or is this a request for the homebrew maintainers to respond to this PR?

2019-05-31 11:45 UTC, SMillerDev commented
> @SMillerDev does the ‘maintainer feedback’ label mean I need to do something? Or is this a request for the homebrew maintainers to respond to this PR?

The latter, unfortunately it's just some more waiting for you.

2019-05-31 11:48 UTC, ellio167 commented
@smillerdev thanks for the reply and clarification!

2019-06-22 15:40 UTC, fxcoudert requested changes
Technically, this is good. The question is really one of notability: this seems very little-used (see stars/forks metrics on https://github.com/openkim/kim-api). I'm not sure this is suitable for Homebrew-core, but would be more appropriate for an organisation tap, at least in a first time: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

2019-06-22 15:40 UTC, fxcoudert commented on Formula/kim-api.rb
> +    system "#{bin}/kim-api-collections-management list > ./out"
```suggestion
    output = shell_output("#{bin}/kim-api-collections-management list")
    assert_match "ex_model_Ar_P_Morse_07C_w_Extensions", output
```

2019-06-22 15:40 UTC, fxcoudert commented on Formula/openkim-models.rb
> +    system "kim-api-collections-management list > ./out"
```suggestion
    output = shell_output("kim-api-collections-management list")
    assert_match "LJ_ElliottAkerson_2015_Universal__MO_959249795837_003", output
```

2019-06-22 16:15 UTC, ellio167 commented
@fxcoudert Thanks very much for your response!  I understand your concern.  Please let me make one argument for the inclusion of these packages.

LAMMPS is already included in homebrew-core and the kim-api will soon become a standard dependency of LAMMPS.  With the latest release (05 Jun 2019) binary distributions of lammps are now being linked against libkim-api.  See for just one example, https://fedora.pkgs.org/30/fedora-updates-x86_64/lammps-20190605-3.fc30.i686.rpm.html.

For this reason, I would argue that it makes sense to include these packages in homebrew-core.  If accepted, I would immediately submit a PR to the lammps formula with an update to the latest (05 Jun 2019) stable release and settings to build with the kim-api library.

If this argument is not sufficiently convincing, then we'll accept the maintainers' decision and create an organization tap.  However, this will lead us to duplicate the lammps formula within our tap and seems inefficient to me.

Thanks for your attention and for providing such a great tool.  It is very much appreciated.  I hope we can contribute to its ongoing success.

2019-06-22 16:30 UTC, fxcoudert commented
That sounds like a good reason, so let's include this.
Can you please squash things so we have a single commit per formula? Thanks.

2019-06-22 16:42 UTC, ellio167 commented
Great!!!  I've squashed.

2019-06-22 17:15 UTC, closed without merging