irssi 1.2.0
Homebrew/homebrew-core pull request #38772
Opened 2019-04-09 00:22 UTC by dylancarlson

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-04-09 05:06 UTC, SMillerDev commented
Test failing on high Sierra

2019-04-13 07:00 UTC, javian commented
We've had this formula submitted before and no one has been able to crack the issue with the test failure yet =/ Most recent ones were #36980 #35864

2019-04-13 07:08 UTC, javian requested changes

2019-04-13 07:08 UTC, javian commented on Formula/irssi.rb
> +    sha256 "8716dafbb112103d73edb9b9463eb063e59217eb7e32c3676eac05cc420ca42d" => :el_capitan
This should not be modified.

2019-04-13 07:08 UTC, javian commented on Formula/irssi.rb
> +    # inreplace "configure", "^DUIfm", "^DUIifm"
If we remove this inreplace we should take out all the comments related to it as well before merging.

2019-05-11 07:50 UTC, closed without merging