libpostal 1.0.0 (new formula)
Homebrew/homebrew-core pull request #38906
Opened 2019-04-13 16:06 UTC by jayzes

This adds a formula for the libpostal address parsing/normalization
library (https://github.com/openvenues/libpostal).

Looks like there's an open issue on libpostal for packaging in Homebrew
(https://github.com/openvenues/libpostal/issues/380), and a much older closed issue within Homebrew (https://github.com/Homebrew/homebrew-core/pull/5172) but no recent PRs that I can find.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-04-13 18:55 UTC, fxcoudert requested changes

2019-04-13 18:55 UTC, fxcoudert commented on Formula/libpostal.rb
> +    system './libpostal "Quatre vingt douze Ave des Champs-Élysées"'
Capture the output of the command with:

```
  output = shell_output(#{bin}/libpostal 'Quatre vingt douze Ave des Champs-Élysées'")
```

and then check it with `assert_match` or `assert_equal`

2019-04-16 20:20 UTC, jayzes commented
@fxcoudert I was struggling a bit with the previous test approach, so ended up going a slightly different route that better matches how most consumers will (I think) use the installed library. Care to take another look?

2019-04-17 10:50 UTC, fxcoudert commented
```
==> ./test
�[31mERR�[39m   Error loading transliteration module, dir=(null)
  �[90m at libpostal_setup_datadir (libpostal.c:1047) �[94merrno: No such file or directory�[39m
```

2019-04-19 17:40 UTC, jayzes commented
Great minds on https://github.com/Homebrew/homebrew-core/pull/39003, @robsalasco !

I've done a bit of digging - unfortunately, it seems like the data download script is broken in both the 1.0.0 and 1.1-alpha releases on github, which is the source of the test failures. HEAD seems to work normally.

I'm wondering if the best way forward for the moment is a tap? Started on that front here: https://github.com/jayzes/homebrew-libpostal

2019-04-20 11:54 UTC, fxcoudert commented
I think a tap is the right solution at the moment, once a stable version is released that works, we'll happily consider it for Homebrew core!

2019-04-20 11:54 UTC, closed without merging