Update picat to 2.6.2
Homebrew/homebrew-core pull request #38902
Opened 2019-04-13 12:24 UTC by boltomli

The build version is 2.6#2

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-04-13 14:57 UTC, fxcoudert commented
Re-releasing a new version of the software, under the same name, and erasing the original file is simply not going to work for us. If `picat` does not have stable released versions, we might have to remove it from Homebrew.

2019-04-26 14:10 UTC, zbeekman commented
@BrewTestBot test this please

2019-05-18 18:28 UTC, zbeekman commented
@BrewTestBot test this please

2019-05-18 18:29 UTC, zbeekman requested changes

2019-05-18 18:29 UTC, zbeekman commented on Formula/picat.rb
> +    assert_equal "Picat version 2.6#2", ver
Please get rid of this new "test".

The goal of tests is to not have to update them with every new upstream release.

You're welcome to add additional testing that tests the software functions correctly, just like the one below.

2019-05-25 03:50 UTC, zbeekman commented on Formula/picat.rb
> +    assert_equal "Picat version 2.6#2", ver
ping @boltomli

2019-05-25 03:50 UTC, zbeekman commented on Formula/picat.rb
> +    assert_equal "Picat version 2.6#2", ver
```suggestion
```

2019-05-25 03:50 UTC, zbeekman commented on Formula/picat.rb
> +    ver = shell_output("#{bin}/picat --version").chomp
```suggestion
```

2019-05-25 04:02 UTC, zbeekman commented
@boltomli: I made the fixes on your branch. I'm a bit puzzled why picat chose a version name of `2.6#2`. Patch versions are pretty standard, so in the future I would recommend `2.6.2` as the version name for upstream...

2019-05-25 04:12 UTC, zbeekman approved these changes

2019-05-25 04:13 UTC, zbeekman commented
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

2019-05-25 04:13 UTC, closed without merging