mOSL 2.4.0 (new formula)
Homebrew/homebrew-core pull request #39570
Opened 2019-05-07 14:48 UTC by 0xmachos

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

mOSL (macOS Lockdown) is my tool which audits/ fixes macOS security settings.

2019-05-07 15:42 UTC, zbeekman requested changes
Hi, thanks for your contribution to homebrew. Can you please resolve the inline comments, squash and force push?

Thanks!

2019-05-07 15:42 UTC, zbeekman commented on Formula/mosl.rb
> +    assert_equal version.to_s, shell_output("#{bin}/Lockdown debug | grep 'mOSL Version' | awk '{print $3}' | tr -d 'v'").chomp
We need a better test here:

1. Tests shouldn't pipe out to awk or other unix tools to do text processing
2. The test should actually test some sort of functionality or correctness of the installation

2019-05-07 15:42 UTC, zbeekman commented on Formula/mosl.rb
> +  depends_on "minisign" => :recommended
Please get rid of the `:recommended` here. We have deprecated options, and formulae should be built to be as featureful as possible to benefit as many users as possible.

```suggestion
  depends_on "minisign"
```

2019-05-07 15:44 UTC, zbeekman commented
Also, the readme states:

```
This script will only ever support the latest macOS release
```

At homebrew we need to support the latest 3 macOS releases. If this formula only supports the latest release then:

1. It may be ineligible for inclusion in Homebrew
2. It should include logic to indicate that it only supports the latest macOS release

2019-05-07 15:48 UTC, zbeekman requested changes

2019-05-07 15:48 UTC, zbeekman commented on Formula/mosl.rb
> +  sha256 "6cf2f301844085f36aa131867a4cc11d7d11a3b04b25c5d3ea35f71c39296eef"
```suggestion
  sha256 "6cf2f301844085f36aa131867a4cc11d7d11a3b04b25c5d3ea35f71c39296eef"
  
  bottle :unneeded
```

2019-05-07 15:50 UTC, zbeekman commented
Looks like a great addition, but a few things need to be addressed first. Please make sure you run `brew audit --strict --online mosl` before pushing.

2019-05-07 17:09 UTC, fxcoudert commented
I don't think a tool that has a policy to only support latest macOS is great for Homebrew core. It's probably a better fit for an external tap https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap (especially given it does not appear so widely used).

2019-05-08 09:05 UTC, 0xmachos commented
I’m happy to creat my own Tap if the only supporting the current macOS release policy makes it incompatible with core.

2019-05-08 15:16 UTC, 0xmachos commented
It might in the future, I'm looking at rewriting it but I don't have an eta for doing that.

Feel free to close this, I've setup a tap at [0xmachos/homebrew-mOSL](https://github.com/0xmachos/homebrew-mOSL) and I'll have a look at  `interesting taps`.

Thanks for your feedback.

2019-05-09 11:54 UTC, closed without merging