beanshell 2.0b4 (new formula)
Homebrew/homebrew-core pull request #39600
Opened 2019-05-08 21:31 UTC by kadwanev

- [X ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-05-22 02:05 UTC, Moisan requested changes

2019-05-22 02:05 UTC, Moisan commented on Formula/beanshell.rb
> +  url "http://www.beanshell.org/bsh-2.0b4.jar"
The latest version is `bsh-2.0b6`. Also, according to the homepage, upstream releases are now on Github so we should use the releases from https://github.com/beanshell/beanshell/releases.

2019-05-22 02:05 UTC, Moisan commented on Formula/beanshell.rb
> +    (bin/"bsh").write <<~EOS
No need to create a bash script here, instead use 
```
 bin.write_jar_script libexec/"bsh-#{version}.jar", "bsh"
```

2019-05-23 00:24 UTC, zbeekman commented
Ping @kadwanev

2019-06-21 12:11 UTC, fxcoudert commented
Given no response, closing for now.

2019-06-21 12:11 UTC, closed without merging