ssh-audit - move off of python2
Homebrew/homebrew-core pull request #39717
Opened 2019-05-12 12:48 UTC by dtrodrigues

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-05-12 21:04 UTC, fxcoudert commented
Can this possibly work with system Python? (i.e. remove the `python` dependency altogether)

2019-05-22 16:41 UTC, mjfwalsh commented
I did a Vermin check a while back and it said ssh-audit will work Python 2.4+ which has been around since Leopard, so it's fairly safe to remove. Unless you want to go with:

    depends_on "python" if MacOS.version <= :tiger

2019-05-23 01:03 UTC, zbeekman requested changes

2019-05-23 01:03 UTC, zbeekman commented on Formula/ssh-audit.rb
> +  depends_on "python"
```suggestion
```

2019-05-23 01:04 UTC, zbeekman commented on Formula/ssh-audit.rb
> +  depends_on "python"
should work with system python. Unless you *really* want to be using it with py3...

2019-05-23 01:07 UTC, dtrodrigues commented
I removed the python dependency per suggestion of @zbeekman

2019-05-23 01:14 UTC, zbeekman requested changes
Fix audit failures please

2019-05-23 01:14 UTC, zbeekman commented on Formula/ssh-audit.rb
Sorry, need to fix the audit failure too. You can try this, but `brew audit --strict --fix ssh-audit` might be a safer bet.

```suggestion
```

2019-05-23 01:44 UTC, dtrodrigues commented
It passes `brew --audit --strict` now.

2019-05-23 02:09 UTC, zbeekman commented
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

2019-05-23 02:09 UTC, closed without merging