latex2html: fix executable path
Homebrew/homebrew-core pull request #39998
Opened 2019-05-17 19:23 UTC by holymonson

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
fix https://github.com/Homebrew/homebrew-core/issues/25024

2019-05-17 19:32 UTC, fxcoudert requested changes

2019-05-17 19:32 UTC, fxcoudert commented on Formula/latex2html.rb
> +  bottle :unneeded
No, this should not hardcode a path.

2019-05-17 19:32 UTC, fxcoudert commented on Formula/latex2html.rb
> +  def caveats; <<~EOS
Again, no. This is not acceptable.

2019-05-17 19:54 UTC, holymonson commented
latex2html depands on a TeX system (TeXLive), on macOS, it's MacTex (the only one). But it's in homebrew-cask instead of homebrew-core, we can't draw the dependence in formula. And this package is pure code, no need to bottle at the very start.

Unless include mactex into brew-core, there is no way to elegantly fix it. Now latex2html is broken all the way, if it's not acceptable, please remove this formula rather then leaving a trap.

2019-05-17 20:58 UTC, fxcoudert commented
> Now latex2html is broken all the way

We welcome a fix that follows the rules of homebrew formulas.

> this package is pure code, no need to bottle at the very start

There is a `configure && make` process, and the files produced are system-dependent (which we know because the bottles on different macOS versions have different checksums). So it should be bottled.

> latex2html depands on a TeX system (TeXLive), on macOS, it's MacTex

Miktex can be installed on macOS. TeXLive can be installed in non-default paths. We need to consider these possibilities.

2019-05-18 13:58 UTC, fxcoudert commented
Confirmed by installing locally that software works fine by setting `l2hconf.pm` manually. That `latex2html` cannot work by autodetecting installed `latex` binaries when they are in `PATH` is their bug to fix, it's actually been reported but the project appears inactive: https://github.com/latex2html/latex2html/issues/22

2019-05-18 13:58 UTC, closed without merging