Update gdcm to 3.0.0
Homebrew/homebrew-core pull request #40223
Opened 2019-05-23 18:28 UTC by tfmoraes

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Updates GDCM to last upstream version (3.0.0). Also compiles with VTK support. I needed to use Ninja instead of Make, because it doesn't compile with Make. Turned off the GDCM Applications because they (seems) to no be ported to last VTK version.

2019-05-24 19:34 UTC, tfmoraes commented
If ITK was build from source the linkage test pass correctly.

2019-06-04 12:16 UTC, fxcoudert requested changes
Make the requested change, and squash everything into a single commit for `gdcm.rb`.
Then add a second commit, bumping the `revision` of `itk.rb`.

2019-06-04 12:16 UTC, fxcoudert commented on Formula/gdcm.rb
> -    sha256 "2b35bf311cd1fc39e0fc1b73e7dfe665eb252a5dfc9e5c0c9895bfd62d852b80" => :mojave
Do not touch the bottle block.

2019-06-04 12:45 UTC, tfmoraes commented on Formula/gdcm.rb
> -    sha256 "2b35bf311cd1fc39e0fc1b73e7dfe665eb252a5dfc9e5c0c9895bfd62d852b80" => :mojave
Ok

2019-06-04 12:49 UTC, tfmoraes commented
Done, @fxcoudert !

2019-06-04 17:15 UTC, fxcoudert approved these changes

2019-06-04 17:18 UTC, closed without merging