augustus: fix bug in proteinprofile on macOS
Homebrew/homebrew-core pull request #40220
Opened 2019-05-23 17:18 UTC by gaberoo

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

There is a bug in `augustus` when built on macOS with Clang that has been reported to upstream as far back as 2016 (see https://github.com/nextgenusfs/funannotate/issues/3). I ran into this when revising a formula on `brewsci/bio` (https://github.com/brewsci/homebrew-bio/pull/642).
```
 ❯ augustus --species=human --proteinprofile=profile/HsDHC.prfl example.fa
# This output was generated with AUGUSTUS (version 3.3.2).
# AUGUSTUS is a gene prediction tool written by M. Stanke (mario.stanke@uni-greifswald.de),
# O. Keller, S. König, L. Gerischer, L. Romoth and Katharina Hoff.
# Please cite: Mario Stanke, Mark Diekhans, Robert Baertsch, David Haussler (2008),
# Using native and syntenically mapped cDNA alignments to improve de novo gene finding
# Bioinformatics 24: 637-644, doi 10.1093/bioinformatics/btn013
# No extrinsic information on sequences given.
# Initialising the parameters using config directory /usr/local/Cellar/augustus/3.3.2/config/ ...

/usr/local/Cellar/augustus/3.3.2/libexec/bin/augustus: ERROR
	PP::Profile: Error parsing pattern file"profile/HsDHC.prfl", line 9.
```
As suggested by @nextgenusfs, this can be resolved by comping `augustus` with `gcc` on `macOS`.

I've also added an explicit test for this to the formula. The bug can be recreated by removing `with_env`. `fails_with :clang` cannot be used because of dependencies on `boost` in the `auxprogs`, which aren't interoperable between `clang` and `gcc`.

With the patch,
```
 ❯ brew test augustus
Testing augustus
==> /usr/local/Cellar/augustus/3.3.2/bin/augustus --species=human test.fasta
==> /usr/local/Cellar/augustus/3.3.2/bin/augustus --species=human --proteinprofile=HsDHC.prfl example.fa 2> /dev/null
```

2019-05-23 17:37 UTC, sjackman commented on Formula/augustus.rb
> +    # Clang breaks proteinprofile on macOS
Please include a link to the upstream issue.

2019-05-23 17:38 UTC, sjackman commented on Formula/augustus.rb
> +    # Then call the full make
```suggestion
```
You can remove this comment.

2019-05-23 17:38 UTC, sjackman commented on Formula/augustus.rb
> +
```suggestion
```
You can remove this blank line.

2019-05-23 17:38 UTC, sjackman requested changes
Some minor nits, but otherwise looks good to me. Thanks for this fix, Gabriel.

2019-05-24 01:07 UTC, Moisan approved these changes

2019-05-24 13:35 UTC, gaberoo commented
@sjackman, am I still missing some changes?

2019-05-24 15:28 UTC, sjackman approved these changes

2019-05-24 15:29 UTC, sjackman commented
Looks good to me. Thanks, Gabriel. Note that force pushing oddly doesn't trigger a notification, so you need to bump the issue with a comment (like you did) to get my attention for another review.

2019-05-24 15:33 UTC, closed without merging

2019-05-24 15:42 UTC, sjackman commented
Merged. Thanks again for your contribution to Homebrew/core, Gabriel! 🌟