riak 2.9.0p1
Homebrew/homebrew-core pull request #40281
Opened 2019-05-24 17:42 UTC by chenrui333

relates to https://github.com/Homebrew/homebrew-core/pull/40075

2019-05-24 22:05 UTC, chenrui333 commented
```
17:42:49 following command and follow the instructions in your editor to edit
17:42:49 your configuration file:
17:42:49 
17:42:49     git config --global --edit
17:42:49 
17:42:49 After doing this, you may fix the identity used for this commit with:
17:42:49 
17:42:49     git commit --amend --reset-author
17:42:49 
17:42:49  2 files changed, 5 insertions(+), 1 deletion(-)
17:42:49 Error: An exception occurred within a child process:
17:42:49   Utils::InreplaceError: inreplace failed
17:42:49 rebar.config.lock:
17:42:49   expected replacement of "f6ed834cd8799623ec00faaedc9ef2a55876d5d8" with "f8f763c503171602e218def94b13ea72dabb5599"
17:42:49 
```

2019-05-25 04:24 UTC, zbeekman requested changes
Some tweaks for resources... not sure how to address the main problem though.

2019-05-25 04:24 UTC, zbeekman commented on Formula/riak.rb
> +      :tag      => "2.1.0"
Can we use the `:revision` this tag points to? People sometimes overwrite tags.

2019-05-25 04:24 UTC, zbeekman commented on Formula/riak.rb
> +        :tag      => "riak_kv-2.9.0"
Again, can we use the `:revision` that this tag points to? Also, add a comment with the tag to clarify.

2019-08-20 17:23 UTC, chenrui333 commented
No idea about how to fix it, close the PR for now.

2019-08-20 17:23 UTC, closed without merging