flintrock 0.11.0
Homebrew/homebrew-core pull request #40294
Opened 2019-05-24 23:27 UTC by chenrui333

2019-05-25 04:29 UTC, zbeekman commented
The inreplace for pyaml is failing. I suspect some resources need updating too.

2019-05-25 04:31 UTC, zbeekman requested changes
Please get rid of the `inreplace` being applied to setup py for pyaml, and update resources according to https://github.com/nchammas/flintrock/blob/v0.11.0/setup.py#L52-L62

Thanks!

2019-05-27 19:14 UTC, chenrui333 commented
ack, resume

2019-05-27 19:30 UTC, chenrui333 commented
Should be good now.

2019-05-27 19:31 UTC, chenrui333 commented on Formula/flintrock.rb
> +  resource "urllib3" do
This is needed for test step.
```
==> /usr/local/Cellar/flintrock/0.11.0/bin/flintrock
Traceback (most recent call last):
  File "/usr/local/Cellar/flintrock/0.11.0/bin/flintrock", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/flintrock/0.11.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/local/Cellar/flintrock/0.11.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/flintrock/0.11.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/flintrock/0.11.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/flintrock/0.11.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/flintrock/0.11.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urllib3<1.25,>=1.20' distribution was not found and is required by botocore
```

2019-05-30 14:33 UTC, chenrui333 commented
@fxcoudert this can be merged. 😄

2019-05-31 08:03 UTC, closed without merging