keys-cli 2.2.4 (new formula)
Homebrew/homebrew-core pull request #40323
Opened 2019-05-25 14:07 UTC by legendarylarry

New formula for keys.cm environment manager cli tool

- [ x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-05-25 15:33 UTC, zbeekman requested changes
Is it possible to improve the test at all? If not, this may be sufficient, TBD.

2019-05-25 15:33 UTC, zbeekman commented on Formula/keys-cli.rb
> +    system "#{bin}/keys", "--reset"
Can this test be improved? Could we check for expected output or log files?

2019-05-25 15:36 UTC, zbeekman commented
It appears that the base repository, https://github.com/intragalactic/keys-cli, is:

1. Very new
2. Has very few stars, forks & watchers

I think this seems like a useful and innovative tool, and therefore I do not believe it should be rejected outright.

I'd love for other people, esp. @Homebrew/maintainers to weigh in with their thoughts here.

2019-05-25 15:59 UTC, vitorgalvao commented
> It appears that the base repository, https://github.com/intragalactic/keys-cli, is:
> 
> 1. Very new
> 2. Has very few stars, forks & watchers

It’s also 3. Self-submitted. Homebrew has (had?) the additional rule to not merge self-submitted formulae (logic being “if it really is useful and people want it, someone else will submit it”).

> I think this seems like a useful and innovative tool, and therefore I do not believe it should be rejected outright.

On the other hand, if it isn’t used by anyone there’s not much point in adding it. Too new tools with too few users are more prone to being abandoned, leaving a lingering dead formula around.

I do think we shouldn’t be too rigid and allow bending the rules from time to time, but I don’t see a particular reason to do so this time. [Having said that](http://youtu.be/ENHVQ2gslp8), I won’t be the one managing the formula, so take my comment as no more than opinion.

Unrelated to that and whatever way this goes, thank you for the submission, @legendarylarry (fun username). It’s with users submitting like you that Homebrew can keep going!

2019-05-25 21:53 UTC, zbeekman commented
Thanks for submitting this @legendarylarry. Unfortunately we will be unable to merge this into homebrew-core at this time. Please feel free to start your own tap and open a new PR (or better yet let a user do it) once the package has gained additional popularity & users.

Thanks!

2019-05-25 21:53 UTC, closed without merging

2019-05-26 00:44 UTC, legendarylarry commented
Hi everyone, thanks for consideration, it's true no one is using this yet (except me). I'll make sure to improve the tests next time I submit with more popularity behind me. If you too want to more easily juggle runtime environment variable sets with password-manager-style protection, check it out ;)

2019-05-26 01:28 UTC, zbeekman commented
I signed up and may test drive it for some projects! I think it’s super
cool but we do need to ensure we spend our time in such a way as to
maximize the utility of Homebrew for the greatest number of users.


On Sat, May 25, 2019 at 8:44 PM Larry Gilliam <notifications@github.com>
wrote:

> Hi everyone, thanks for consideration, it's true no one is using this yet
> (except me). I'll make sure to improve the tests next time I submit with
> more popularity behind me. If you too want to more easily juggle runtime
> environment variable sets with password-manager-style protection, check it
> out ;)
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-core/pull/40323?email_source=notifications&email_token=AACEIPBNSNECNTYJU4A35BTPXHMPZA5CNFSM4HPUVXNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWH3TSA#issuecomment-495958472>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AACEIPBK55HUVJE7QWOJJCLPXHMPZANCNFSM4HPUVXNA>
> .
>