icecream: packport free memory fix
Homebrew/homebrew-core pull request #40739
Opened 2019-06-06 05:37 UTC by timblechmann

free memory detection was not working on icecream-1.2, which caused a
memory limit for compile jobs of 100MB.
we therefore backport a fix from upstream

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

@zbeekman like this?

2019-06-06 17:48 UTC, zbeekman requested changes
Please, assuming you've already changed to the homebrew-core repo (`cd "$(brew --repo homebrew/core)"`), do the following:

1. Add the suggested comment above the `patch do` block
2. Add `revision 1` below the `sha256` line
3. Add the requested comment above the `patch do` block.
3. Run `brew rm icecream ; brew install -s icecream` to ensure it builds after 1. and 2.
4. Run `brew test icecream` after 3.
5. Run `brew audit --strict icecream` after 4.
6. `git add Formula/icecream.rb`
7. `git commit --amend --no-edit`
8. `git push --force-with-lease`

Thanks!

Note: Edited, Reason: wording.

2019-06-06 17:48 UTC, zbeekman commented on Formula/icecream.rb
> +  patch do
```suggestion
# Backport https://github.com/icecc/icecream/pull/467
# Total memory was not correctly detected on macOS, resulting in a hard limit of 100MB
# being set. Remove in next stable release.
  patch do
```

2019-06-06 17:53 UTC, zbeekman commented
@timblechmann Almost! Please see my (edited) PR review comment.

To summarize:

- There should be a `revision 1` added to cause a new binary to be built and distributed
- There needs to be a comment above the `patch do` block with a link to your upstream PR, a brief statement of why the patch is needed, and of when to remove it. I've suggested wording for that comment.
- Your commit message looks pretty good. When you make these changes we want to leave the message alone, fixup/squash that commit with the requested changes, and force-push it back up to github.

I hope you can follow, sorry if I haven't been clear. If you need help or further explanation, just ask.

Thanks.

2019-06-07 04:56 UTC, timblechmann commented
thanks a lot! i've added a second commit which fixes the services (which had not been working, as they daemonized the daemons).

furthermore: i wonder if there's a way to modify the environment? one has to set `ICECC_CLANG_REMOTE_CPP=0` to avoid compile errors. the best way would be to set it globally

2019-06-07 07:47 UTC, SMillerDev commented
During install? Or afterwards? during install it's ` ENV["ICECC_CLANG_REMOTE_CPP"] = 0`

2019-06-07 08:19 UTC, timblechmann commented
@SMillerDev during run-time (ideally we would add this to the environment of the user)

2019-06-07 08:20 UTC, SMillerDev commented
Homebrew can't/won't edit user environments. You could make a caveat suggesting the edit though.

2019-06-07 08:21 UTC, timblechmann commented
yes, sounds reasonable ... though maybe we should just patch the sources to use a sane default here

2019-06-09 21:53 UTC, zbeekman commented
@timblechmann is there an upstream issue for `ICECC_CLANG_REPOTE_CPP`? Can you link it if there is?

Same deal regarding patching applies here as it did to the previous patch: upstream needs to be at least aware, but preferably on board with patching.

2019-06-09 22:25 UTC, zbeekman commented
@timblechmann I'm going to merge this PR. If we need an additional patch for ICECC_CLANG_REMOTE_CPP then please let me know.

2019-06-09 22:36 UTC, zbeekman approved these changes
LGTM

2019-06-09 22:38 UTC, closed without merging

2019-06-10 03:52 UTC, timblechmann commented
> @timblechmann is there an upstream issue for `ICECC_CLANG_REMOTE_CPP`? Can you link it if there is?
> 
> Same deal regarding patching applies here as it did to the previous patch: upstream needs to be at least aware, but preferably on board with patching.

just filed an issue upstream: https://github.com/icecc/icecream/issues/471

let's see what they say