Add SWIG 3.0.12 as swig@3 and remove swig@3.04
Homebrew/homebrew-core pull request #40882
Opened 2019-06-11 16:32 UTC by golddranks

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
There is another PR open, ( https://github.com/Homebrew/homebrew-core/pull/39929 ) but there were some things to fix, and since I don't know when the author's going to respond, I figured that I'd sent my own. (Limiting it to Swig changes and excluding the Subversion changes present in the other PR.)

The formula is basically the same than `swig` was before SWIG 4.0.0 was introduced, expect for the removal of `head` block and addition of `keg_only :versioned_formula`.

See the rationale for the versioned formula in the discussion of https://github.com/Homebrew/homebrew-core/pull/39929 .

2019-06-11 17:20 UTC, zbeekman requested changes
@golddranks: thanks for the PR. Can you please:

- [x] Delete the `bottle do` block
- [x] Remove the `system "./autogen.sh" if build.head?` line
- [x] Add an alias (symbolic link) to https://github.com/Homebrew/homebrew-core/tree/master/Aliases `Aliases/swig@4 -> ../Formula/swig.rb`
- [x] Rebase your commits so that:
      - Deletion of swig@3.0.4 happens first with the commit message: `swig@3.04: Remove unmaintained formula`
      - Addition of `swig@3` and `swig@4` alias happens in the second commit with message header: `swig@3 3.0.12 (new formula)` followed by a blank line and any further messages you would like to add (but you could just leave it at that).

2019-06-11 17:20 UTC, zbeekman commented on Formula/swig@3.rb
> +    system "./autogen.sh" if build.head?
```suggestion
```

This needs to go: building HEAD from versioned formula is unsupported and disallowed.

2019-06-11 17:20 UTC, zbeekman commented on Formula/swig@3.rb
>    end
Please completely remove the `bottle do` block. From brew-testbot's perspective this is a new formula.

2019-06-11 17:23 UTC, zbeekman commented
@golddranks FYI, for the new formula you could just copy the one out of the old PR: https://github.com/Homebrew/homebrew-core/pull/39929/files#diff-2adb42ed307c4ae8955ba187eff99f60 That should address everything other than the alias and my comments about the commit messages and order above.

2019-06-11 17:29 UTC, golddranks commented
All right, rebased. Force-pushing now.

2019-06-11 17:48 UTC, zbeekman reviewed
LGTM

2019-06-11 17:49 UTC, zbeekman approved these changes

2019-06-11 17:50 UTC, zbeekman commented
FYI, we're having some CI issues, so this may not get merged for a few hours. Hopefully it won't be longer than that.

2019-06-11 21:01 UTC, scpeters commented
@BrewTestBot test this please

2019-06-12 05:50 UTC, golddranks commented
It still seems to fail at `pull --clean https://github.com/Homebrew/homebrew-core/pull/40882` Is this spurious or is there something wrong with the branch/some cached values? Should I re-send the PR?

2019-06-12 12:06 UTC, zbeekman commented
> Should I re-send the PR?

No, please don't. This is the symptom of our CI infra troubles. I think we need to rebuild the worker VMs again. If no re-runs this PR within a day or two, please ping us to check in.

2019-06-13 08:37 UTC, fxcoudert commented
Thank you @golddranks

2019-06-13 08:42 UTC, closed without merging