wildfly-as: add testing
Homebrew/homebrew-core pull request #40883
Opened 2019-06-11 19:08 UTC by jasontedor

This commit adds some additional testing to the wildfly-as formula.

Relates #40850

2019-06-11 19:53 UTC, zbeekman requested changes
@jasontedor: This is great! Yes, we don't have to do much testing. For client-server stuff, even checking logs or output for a thrown error due to a failed connection or authentication is often good enough. We want to ensure that the package can reasonably be expected to do what it says on the tin. More complex testing that just dumping a string to stdout helps ensure linkage is OK, etc.

As far as this goes, there should be just one `test do` block, so please combine it with the previous one.

2019-06-11 19:53 UTC, zbeekman commented on Formula/wildfly-as.rb
> +  test do
If you're going to leave the previous test in place, the `test do` block should be merged so there's just one.

2019-06-11 19:53 UTC, zbeekman commented on Formula/wildfly-as.rb
> +    ENV["JBOSS_HOME"] = opt_libexec
You can define it (only) once when combining the test-do block.

2019-06-11 19:55 UTC, zbeekman commented
Please see my review. In general: Looking great! 💯 

I'm going to let CI run through since it's already been started, but I'd prefer to combine this work with the other PR. I may just steal your work here and apply it to the other PR. Alternatively, you can bump the version from the other PR and we can merge this, if you would prefer that. Up to you.

2019-06-11 20:37 UTC, jasontedor commented
@zbeekman Thanks for your feedback. I pushed a commit with the suggestions that you made, made the process for terminating Wildfly more robust, and cherry-picked the version bump over to here.

2019-06-11 21:00 UTC, scpeters commented
@BrewTestBot test this please

2019-06-11 21:50 UTC, zbeekman commented
@jasontedor looks good to me.

Any chance you could squash the commits into one and keep the subject line (first line) of 59e49f394b2e32aad0ddc65bf0347ee6a913b912, `wildfly-as 17.0.0.Final` as the subject line of the squashed commit? You don't need any further details, but if you feel there's something important to include in the message you can add it on the 3rd line of the squashed commit message.

2019-06-11 23:42 UTC, scpeters commented
@BrewTestBot test this please

2019-06-12 11:08 UTC, jasontedor commented
@zbeekman I've squashed as requested.

2019-06-12 11:42 UTC, zbeekman commented
Well, as soon as Jenkins is back we can test and merge. Thanks again for taking this on!

2019-06-12 16:16 UTC, jasontedor commented
@BrewTestBot test this please

2019-06-12 17:07 UTC, scpeters commented
looks like just a style error remains

2019-06-12 22:31 UTC, jasontedor commented
@zbeekman It looks like this is ready now?

2019-06-13 08:34 UTC, fxcoudert approved these changes

2019-06-13 08:35 UTC, merged