Patch irrlicht for macOS Mojave and add bottle
Homebrew/homebrew-core pull request #41140
Opened 2019-06-19 22:07 UTC by kevinlul

To allow building from source, replace the user-triggered error with a warning for now, until irrlicht updates. Hopefully, the edge case of broken PNGs isn't a big enough problem to warrant an entire broken build.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-06-20 02:03 UTC, mistydemeo requested changes
Thanks for the submission! Left a couple of comments.

2019-06-20 02:03 UTC, mistydemeo commented on Formula/irrlicht.rb
> +    sha256 "88ef6a24a237c71b1342f4cd6a8dbf6d797d2460b1020cdf7f49b7ef0d2a24a2" => :mojave
Can you please remove this line? A bottle will be automatically built when we merge it. Thanks!

2019-06-20 02:03 UTC, mistydemeo commented on Formula/irrlicht.rb
> +
Looks like there's some stray whitespace here; can you remove that?

2019-06-22 14:31 UTC, fxcoudert approved these changes

2019-06-22 14:32 UTC, fxcoudert commented
Thanks @kevinlul

2019-06-22 14:34 UTC, closed without merging