Fix cql 0.7.0 build version
Homebrew/homebrew-core pull request #41285
Opened 2019-06-24 12:26 UTC by auxten

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-06-24 12:27 UTC, auxten commented
Squash Merge, pls

2019-06-24 12:51 UTC, jonchang commented
Does this need to have its `revision` bumped?

2019-06-24 13:16 UTC, SMillerDev requested changes

2019-06-24 13:16 UTC, SMillerDev commented on Formula/cql.rb
> +    ENV["CQLVERSION"] = "v0.7.0"
please use `ENV["CQLVERSION"] = "v#{version}"`

2019-06-24 13:16 UTC, SMillerDev commented on Formula/cql.rb
> +    ldflags = "-X main.version=v0.7.0 " \
same here

2019-06-24 13:43 UTC, auxten commented
@jonchang yes, #41274

2019-06-24 14:06 UTC, SMillerDev commented
Please add a revision bump then.

2019-06-24 15:19 UTC, fxcoudert commented
> Please add a revision bump then

Please add a revision bump and squash everything into a single commit, with message `cql: fix version`

2019-06-25 01:49 UTC, auxten commented
Squash done.
@SMillerDev @fxcoudert version has been bumped by some other guy in #41274

2019-06-25 05:56 UTC, SMillerDev commented
>Squash done. ...

@auxten I know. Your PR needs a line that says `revision 1` though, or the change will never get to the users.

2019-06-25 08:57 UTC, auxten commented
@SMillerDev Oh, I see. done

2019-06-25 10:46 UTC, SMillerDev approved these changes

2019-06-25 10:48 UTC, SMillerDev commented
Please fix the audit issue.

2019-06-25 15:31 UTC, auxten commented
@SMillerDev fixed, sorry for so much trouble.

2019-06-25 15:50 UTC, SMillerDev commented
Not a problem at all, I'd much rather have this then someone who doesn't do anything to improve homebrew for all it's users

2019-06-27 12:25 UTC, fxcoudert commented
Thanks @auxten

2019-06-27 12:26 UTC, closed without merging