pass-top: Fix test and add info message
Homebrew/homebrew-core pull request #41688
Opened 2019-07-07 18:32 UTC by SimplyDanny

I noticed that the test of this formula is not working locally. With two set environment variables the installed command can be found and the test succeeds. 

I also added an info message telling users which environment variables to set in order to make the command work.

2019-07-29 20:03 UTC, SMillerDev requested changes
I think this solution could better be rewritten as in `aws-elasticache` with `write_env_script`

2019-07-29 20:03 UTC, SMillerDev commented on Formula/pass-otp.rb
> +      gpg = Formula["gnupg"].opt_bin/"gpg"
this should be made a test dependency

2019-07-30 19:25 UTC, SimplyDanny commented on Formula/pass-otp.rb
> +      gpg = Formula["gnupg"].opt_bin/"gpg"
👍

2019-07-30 20:12 UTC, SimplyDanny commented
My `pass` installation was somehow outdated. Don't know how this could happen. 🤔 Anyway. It turns out the test I tried to fix runs actually fine locally. So all changes will be reverted. Nonetheless, to give this PR any meaning I at least add `gnupg` as a test dependency like you proposed. Sorry for this waste of time!

2019-07-30 20:19 UTC, SMillerDev commented
No problem, I really appreciate the effort you put in nonetheless. I much rather have 10 redundant PRs then an unmaintained project

2019-07-30 20:42 UTC, SimplyDanny commented
Thank you. I can only agree with that.

2019-08-06 20:25 UTC, SMillerDev commented
@BrewTestBot test this please

2019-08-06 20:26 UTC, SMillerDev approved these changes

2019-08-06 20:30 UTC, SMillerDev commented
Thanks @SimplyDanny! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

2019-08-07 18:35 UTC, SimplyDanny commented
Thanks a lot for these kind words! :)

2019-08-08 19:37 UTC, closed without merging