wordgrinder 0.7.2 (new formula)
Homebrew/homebrew-core pull request #41864
Opened 2019-07-11 18:26 UTC by ak2k

- [yes] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [yes] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [yes] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [yes] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [yes] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
The included test is not a great one; however, there is a test included.

2019-07-15 19:05 UTC, ak2k commented
If anyone has any guidance to offer on the likely cause of this bottling error, I would appreciate it.

2019-07-15 19:18 UTC, SMillerDev commented
The install is empty on high sierra: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/44953/

might be a fluke.

2019-07-15 19:19 UTC, SMillerDev commented
@BrewTestBot test this please

2019-07-18 15:41 UTC, fxcoudert commented
Make install is putting files in the wrong directory:

```
==> make install PREFIX=/usr/local/Cellar/wordgrinder/0.7.2
[1/3] install -m 644 bin/wordgrinder.1 /private/tmp/wordgrinder-20190717-26740-d1hm4u/wordgrinder-0.7.2/.brew_home/share/man/man1/wordgrinder.1
[2/3] install -m 644 README.wg /private/tmp/wordgrinder-20190717-26740-d1hm4u/wordgrinder-0.7.2/.brew_home/share/doc/wordgrinder/README.wg
[3/3] install -m 755 bin/wordgrinder-builtin-curses-release-stripped /private/tmp/wordgrinder-20190717-26740-d1hm4u/wordgrinder-0.7.2/.brew_home/bin/wordgrinder
 ```

2019-07-24 17:05 UTC, ak2k commented
@BrewTestBot test this please

2019-07-29 20:11 UTC, SMillerDev commented
Still the wrong directory.

2019-07-30 05:26 UTC, SMillerDev commented
@brewtestbot test this please

2019-07-31 16:34 UTC, ak2k commented
@BrewTestBot test this please

2019-08-01 21:51 UTC, ak2k commented
@BrewTestBot test this please

2019-08-13 17:16 UTC, ak2k commented
Are there any changes required prior to inclusion of this new formula?

2019-08-26 15:48 UTC, fxcoudert commented
Looks good to me. Can you please squash everything into a single commit, with message `wordgrinder 0.7.2 (new formula)`? We should then be ready to merge.

2019-09-14 09:33 UTC, fxcoudert requested changes

2019-09-14 09:33 UTC, fxcoudert commented on Formula/wordgrinder.rb
> +  depends_on "ninja"
```suggestion
  depends_on "ninja"  => :build
```

This is a build-only dependency, and should be moved above `lua`.

2019-10-03 16:58 UTC, chenrui333 commented
@ak2k Any update on this PR? :)

2019-10-10 20:13 UTC, iMichka commented
This has been open since July 11, and has not moved since 26 days. I'll close this to reduce the number of open issues in our bug tracker. Please submit the formula again, and link to this PR.

2019-10-10 20:13 UTC, closed without merging