vapor 18.0.0 (new formula)
Homebrew/homebrew-core pull request #42436
Opened 2019-07-25 18:55 UTC by tanner0101

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is a continuation of https://github.com/Homebrew/homebrew-core/pull/19895. We've updated our CLI tool to not have any cross tap dependencies and to build from source. 

I'm opening this as a draft since the new version of the tool is still in beta (release should be in a month or two). We'd like to get early feedback on whether this new formula looks correct and hopefully pre-approve this PR.

2019-07-25 19:53 UTC, MikeMcQuaid requested changes

2019-07-25 19:53 UTC, MikeMcQuaid commented on Formula/vapor.rb
> +    system "mv", ".build/debug/Executable", "vapor"
`bin.install ".build/debug/Executable", "vapor"`

2019-07-25 19:53 UTC, MikeMcQuaid commented on Formula/vapor.rb
> +  depends_on :xcode => "11"
Newline above this line.

2019-07-25 19:53 UTC, MikeMcQuaid commented on Formula/vapor.rb
> +  desc "Vapor Toolbox"
`Server-side Swift web framework`?

2019-07-25 19:53 UTC, MikeMcQuaid commented on Formula/vapor.rb
> +  end
Needs a `test do` block doing something with the `vapor` executable.

2019-09-14 08:49 UTC, fxcoudert commented
We'll consider a new PR when stable version is released, closing for now. Please take into account Mike's review.

2019-09-14 08:49 UTC, closed without merging