sdl2 2.0.10
Homebrew/homebrew-core pull request #42619
Opened 2019-07-31 18:36 UTC by illume

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-08-01 01:53 UTC, Moisan requested changes

2019-08-01 01:53 UTC, Moisan commented on Formula/sdl2.rb
>    revision 1
This line should be removed.

2019-08-13 09:30 UTC, illume commented on Formula/sdl2.rb
>    revision 1
Thanks. `revision 1` was removed.

2019-08-29 09:43 UTC, illume commented
I closed the PR, and opened it again... which seems to have caused the jenkins build to be rerun.

*fingers crossed*

2019-08-29 13:10 UTC, fxcoudert commented
Thanks @illume

2019-08-29 13:11 UTC, closed without merging