libpsl 0.14.0
Homebrew/homebrew-core pull request #4281
Opened 2016-08-28 04:59 UTC by SteelPangolin

- [√] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [√] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [√] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [√] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

[libpsl](https://github.com/rockdaboot/libpsl) provides data for, and a C interface to, the [Mozilla Public Suffix List](https://publicsuffix.org/).

2016-08-28 05:14 UTC, SteelPangolin commented
The build seems to be failing because of the upstream repo's Github star count. [Debian](https://packages.debian.org/jessie/libpsl0), [Fedora](https://admin.fedoraproject.org/pkgdb/package/rpms/libpsl/), and [FreeBSD](https://github.com/freebsd/freebsd-ports/tree/master/dns/libpsl) have packaged it, and [mainline `curl` has optional support for it](https://github.com/curl/curl/blob/master/configure.ac#L170).

2016-08-31 04:12 UTC, dunn commented on Formula/libpsl.rb
> +  depends_on :python2 => :build
We have special dependencies `:python` and `:python3`.  What version of Python 2 is required?  If it's 2.7, you can do
```ruby
depends_on :python if MacOS.version <= :snow_leopard
```
If it's just whatever Python is on the system you shouldn't need it at all.

2016-08-31 05:09 UTC, SteelPangolin commented on Formula/libpsl.rb
> +  depends_on :python2 => :build
Thanks for the tip, @dunn. The build-time script `src/psl-make-dafsa` has the shebang line `#!/usr/bin/env python2`, uses `with` but doesn't need to import it from `__future__`, and doesn't use set literals or set/dict comprehensions, so I think it'll run on either 2.6 or 2.7.

2016-08-31 15:32 UTC, dunn commented
> the shebang line `#!/usr/bin/env python2`

That might need to be patched to read `#!/usr/bin/env python`, since the macOS convention is for `python` to be Python 2 and `python3` to be Python 3, while Linux usually does `python` => Python 3 and `python2` => Python 2.

2016-09-01 04:24 UTC, SteelPangolin commented on Formula/libpsl.rb
> ++#!/usr/bin/env python
@dunn: this implements the shebang line change.

2016-09-01 05:20 UTC, dunn commented on Formula/libpsl.rb
> ++#!/usr/bin/env python
For a one-liner like that we've got a helper method you can use:
```ruby
inreplace "src/psl-make-dafsa", "#!/usr/bin/env python2", "#!/usr/bin/env python"

2016-09-01 19:45 UTC, MikeMcQuaid commented on Formula/libpsl.rb
> ++#!/usr/bin/env python
Ideally also report it to upstream so they are aware this is required to support OS X.

2016-09-01 21:09 UTC, dunn commented on Formula/libpsl.rb
> ++#!/usr/bin/env python
I thought we found that it wasn't possible to make the shebang cross-platform?  We're doing this already with 
- [`emscripten.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/emscripten.rb)
- [`git-remote-hg.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-remote-hg.rb)
- [`gst-validate.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gst-validate.rb)
- [`src.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/src.rb)
- [`yle-dl.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/yle-dl.rb)

2016-09-03 04:54 UTC, tdsmith commented on Formula/libpsl.rb
> ++#!/usr/bin/env python
Apple doesn't ship `python2` but Apple and I think everyone else *does* ship `python2.7` which should be fine since 2.6 is long since EOL'd.

2016-09-03 12:36 UTC, MikeMcQuaid commented on Formula/libpsl.rb
> ++#!/usr/bin/env python
@dunn Idealy we'd report those all upstream if those upstreams wish to support OS X.

2016-09-03 15:28 UTC, dunn commented on Formula/libpsl.rb
> ++#!/usr/bin/env python
@tdsmith Oh, I didn't know that; cool.

2016-09-17 01:47 UTC, SteelPangolin commented
Thanks for your help and patience. I've updated the PR to use the patch helper method, and opened an [upstream PR](https://github.com/rockdaboot/libpsl/pull/56) to fix the problem everywhere.

2016-09-17 03:44 UTC, zmwangx commented on Formula/libpsl.rb
> +  # A build script (psl-make-dafsa) requires Python 2.7.
Remove this comment.

2016-09-17 03:46 UTC, zmwangx commented on Formula/libpsl.rb
> +  homepage "https://github.com/rockdaboot/libpsl"
18 stars, 5 watchers, no forks. Please explain why this package is notable, or we can't accept it in core. Ref: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Acceptable-Formulae.md.

2016-09-17 03:46 UTC, zmwangx commented on Formula/libpsl.rb
> +    # OS X doesn't follow PEP-394, so change psl-make-dafsa's shebang line to use Python 2.
The inreplace is self-documenting enough, I don't think we need this comment.

2016-09-17 03:49 UTC, zmwangx requested changes
Notability seems to be a major problem. Maybe you want to explore the idea of hosting this in your own tap, which is really simple. https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

2016-09-17 12:34 UTC, MikeMcQuaid commented on Formula/libpsl.rb
> +    # OS X doesn't follow PEP-394, so change psl-make-dafsa's shebang line to use Python 2.
Would be good to use the upstream patch instead of this which also self-documents a bit more

2016-09-17 12:35 UTC, MikeMcQuaid requested changes

2016-09-26 22:43 UTC, SteelPangolin commented
Will set up a tap for this.

2016-09-26 22:43 UTC, closed without merging