pulseaudio: fix service launchdaemon plist
Homebrew/homebrew-core pull request #43245
Opened 2019-08-18 02:19 UTC by sidneys

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The previous launchd service plist was noot been updated in a long time, and thus was not functional. My changes
 1) fix the path to the `pulseaudio` binary and
 2) ensure that the `pulseaudio` service is kept alive as long as the `com.apple.audio.coreaudiod` macOS audio subsystem is available.

2019-09-12 09:40 UTC, fxcoudert requested changes

2019-09-17 18:15 UTC, sidneys commented on Formula/pulseaudio.rb
> +      <string>/Users/#{ENV["LOGNAME"]}/Library/Logs/#{name}.log</string>
Both `StandardErrorPath` and `StandardOutPath` were changed to point to `#{var}/log/#{name}.log`. Thanks.

2019-09-17 18:16 UTC, sidneys commented on Formula/pulseaudio.rb
> +        <string>#{bin}/pulseaudio</string>
Both `StandardErrorPath` and `StandardOutPath` were changed to point to `#{var}/log/#{name}.log`. Thanks.

2019-09-17 19:49 UTC, sidneys commented
Dear @fxcoudert,

The requested changes were pushed in an additional commit, looking forward to your feedback.

Cheers,
s

2019-10-19 19:29 UTC, SMillerDev commented
Thanks @sidneys! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

2019-10-19 20:35 UTC, SMillerDev commented
@sidneys can you squash all your commits into one called `pulseaudio: fix service launchdaemon plist`?

2019-10-20 13:34 UTC, merged