topshell 0.7.7
Homebrew/homebrew-core pull request #43327
Opened 2019-08-21 00:50 UTC by bensleveritt

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Adds TopShell 0.7.7, specifically built for macOS. First PR for brew, so apologies if I've missed anything.

2019-09-14 09:09 UTC, fxcoudert requested changes

2019-09-14 09:09 UTC, fxcoudert commented on Formula/topshell.rb
> +  depends_on "node@8" => :build
We prefer not to accept new formulas that do not build with the latest version of compilers and tools, as it typically indicates lack of long-term support. In this case, `node@8` depends on Python 2, which will become unsupported on 2019-12-31, and will be removed from Homebrew. Can you migrate to latest `node`?

2019-09-16 19:48 UTC, bensleveritt commented
Updated to remove the pinned version, and will use the latest, as requested.

2019-10-07 07:55 UTC, SMillerDev commented
It doesn't require node to run anything?

2019-10-07 08:09 UTC, bensleveritt commented
It uses Node to run the scripts, but it's packaged up with [pkg](https://www.npmjs.com/package/pkg), so it's a build dependency, rather than a runtime one.

2019-10-07 08:42 UTC, SMillerDev commented
so, it ships it's own version of node?

2019-10-07 08:45 UTC, bensleveritt commented
Yes, as I understand it, it bundles a node vm at during build, and will use that subsequently.

2019-10-19 19:27 UTC, SMillerDev commented
@Homebrew/core bundling it's own version of node seems weird. Do we have any rules on this?

2019-10-20 17:45 UTC, fxcoudert commented
> bundling it's own version of node

That's a strong NO. There must be a way to build with external node.

2019-10-30 01:45 UTC, chenrui333 commented
> That's a strong NO. There must be a way to build with external node.

+ 1

2019-10-30 06:37 UTC, SMillerDev commented
@bensleveritt is there a way to build without bundling node?

2019-10-30 14:48 UTC, zbeekman requested changes
> so, it ships it's own version of node?

@Homebrew/core @bensleveritt @fxcoudert @SMillerDev:

I don't think this is an accurate description of what is going on. It's using [pkg](https://www.npmjs.com/package/pkg) to create an executable with a self contained runtime from Homebrew's node. From looking at the project website, the reported size still seems reasonable (10s of MB).

If this is still undesirable, it may be possible to install it via npm without packaging it.

2019-10-30 15:03 UTC, bensleveritt commented on Formula/topshell.rb
> +  homepage "http://show.ahnfelt.net/topshell/"
Good point, fixed up

2019-10-30 15:09 UTC, bensleveritt commented
@zbeekman Yes, that's the situation. It creates a runtime bundle from Homebrew node, in much the same way an Electron-based app would. This could put it in the cask category of brews, but as it's command-line service that can be built from source, it seemed to fit with homebrew-core.

Happy to close the PR if this doesn't fit.

2019-11-11 13:15 UTC, bensleveritt commented
As I understand it, Topshell can't be installed via NPM, as it and the scripts are actually compiled with Scala. The Node VM is used to run the interpreted Scala.

https://github.com/topshell-language/topshell/wiki/FAQ

Perhaps @Ahnfelt can explain it better...

2019-12-21 17:53 UTC, iMichka commented
This work has started in august, and has not made much progress since then. We have tens of requests for new formulae per week, and we can't invest so much time in fixing each build failure: if the package does not behave nicely from the beginning, it feels it will be a lot of work to make it work, and also a lot of work to maintain in the future.

I'll close this for the time being, until a working version is submitted. You can of course still maintain the formula in a separate tap if needed.

2019-12-21 17:53 UTC, closed without merging

2019-12-23 17:08 UTC, bensleveritt commented
That's fair. I've no idea what more I needed to do to make this work, but as there's heavy sketicism for inclusion