flint 2.5.2 (new formula)
Homebrew/homebrew-core pull request #43425
Opened 2019-08-24 03:44 UTC by alebcay

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-09-07 18:15 UTC, alebcay commented
Bump on this, since it's been sitting around for a while now.

2019-09-14 18:46 UTC, fxcoudert requested changes

2019-09-14 18:46 UTC, fxcoudert commented on Formula/flint.rb
> +    ENV["DYLD_LIBRARY_PATH"] = "/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/"
This is wrong, for sure. If we need to link against libraries there, they should be specified with `-framework` during the build.

2019-11-04 05:08 UTC, fxcoudert commented
Closing due to lack of activity

2019-11-04 05:08 UTC, closed without merging