pastel 0.5.2 (new formula)
Homebrew/homebrew-core pull request #43459
Opened 2019-08-26 05:45 UTC by liamdawson

Add the pastel command-line utility, for working with colors

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Found this tool I'm looking forward to integrating in my workflow, would be awesome to have it in brew to make that easier.

https://github.com/sharkdp/pastel

2019-08-26 05:57 UTC, sharkdp commented
Thank you very much for creating this formula. `pastel` creates shell completion files for bash, zsh and fish during the build. This is not a necessity, but if you want, you could install them in the right places. For reference, here is what the Arch Linux package does: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pastel (look for `SHELL_COMPLETIONS_DIR` and `install .... completions/...` below.

2019-08-26 12:09 UTC, fxcoudert commented
Installing completion files would be nice… look at the use of `fish_completion.install`, `bash_completion.install` and `zsh_completion.install` in other formulas.

2019-08-27 01:02 UTC, liamdawson commented
I've added the shell completions now, thanks for the directions!

2019-08-29 21:01 UTC, agustif commented
I would like to install pastel via brew too

2019-08-30 00:41 UTC, kenchan0130 commented
I would say it's better to download `tar.gz` directly than build with Rust and it shouldn't increase unnecessary dependencies.

In this case, you can use https://github.com/sharkdp/pastel/releases/download/v0.5.3/pastel-v0.5.3-x86_64-apple-darwin.tar.gz.

2019-08-30 01:39 UTC, liamdawson commented
@kenchan0130 I was mirroring an [existing formula for a Rust utility](https://github.com/Homebrew/homebrew-core/blob/6ff8b8e4e13717cd5284926267598109237082fa/Formula/xsv.rb). No runtime dependencies necessary, so if it's bottled, no dependencies needed to install.

2019-08-30 01:40 UTC, liamdawson commented
@fxcoudert Any advice on other steps I should take to have this reviewed and hopefully merged? 🙂

2019-08-30 02:52 UTC, kenchan0130 commented
@liamdawson Sounds good. 
As an example, I would say it will be like https://github.com/Homebrew/homebrew-core/blob/master/Formula/nodebrew.rb.

2019-08-30 04:48 UTC, SMillerDev commented
Binary formula are forbidden in homebrew. The nodebrew formula is using the source from a tag rather than a binary distribution.

2019-09-06 00:24 UTC, 4cm4k1 commented
@SMillerDev It looks like the `url` used by @liamdawson is actually the source from a tag, so is there something else to do? I'm looking forward to installing this package.

2019-09-14 14:09 UTC, fxcoudert requested changes

2019-09-14 14:09 UTC, fxcoudert commented on Formula/pastel.rb
> +    ENV["SHELL_COMPLETIONS_DIR"] = File.join(buildpath, "completions")
```suggestion
    ENV["SHELL_COMPLETIONS_DIR"] = buildpath/"completions"
```

2019-09-14 14:09 UTC, fxcoudert commented on Formula/pastel.rb
> +    bash_completion.install "completions/pastel.bash" => "pastel.bash"
Since you're not renaming the file, I think ` => "pastel.bash"` is unnecessary
(same below)

2019-09-16 07:50 UTC, liamdawson commented
I've also bumped the version to 0.5.3, as that's out now, but I can remove that commit if it's better to introduce that version bump separately.

2019-09-16 08:04 UTC, SMillerDev commented
It's fine, can you squash the commits into one using `<formula> <version> (new formula)`?

2019-09-16 09:17 UTC, fxcoudert approved these changes

2019-09-16 09:19 UTC, SMillerDev commented
Thanks @liamdawson! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

2019-09-16 09:22 UTC, closed without merging