httpie 1.0.3
Homebrew/homebrew-core pull request #43471
Opened 2019-08-26 14:57 UTC by chenrui333

Created with `brew bump-formula-pr`.

2019-08-27 20:26 UTC, javian commented
Awaiting further updates before merging.

2019-08-29 13:07 UTC, jeffbyrnes commented
FYI, upstream changes were accepted by the httpie maintainer.

2019-08-29 13:07 UTC, chenrui333 commented
Cool, thanks!

2019-08-29 18:57 UTC, jeffbyrnes requested changes

2019-08-29 19:45 UTC, SMillerDev commented on Formula/httpie.rb
> +   end
Probably even easier to just use the url of the upstream patch. For example: https://github.com/Homebrew/homebrew-core/blob/master/Formula/upx.rb#L21-L24

2019-08-30 03:30 UTC, chenrui333 commented on Formula/httpie.rb
> +   end
Updated with using the online commit hash.

2019-08-30 04:39 UTC, SMillerDev commented
Why does it need to patch a file that generates the formula in the formula? It won't affect any usage of httpie right?

2019-08-30 08:18 UTC, javian commented
There's a script that can extract the dependencies https://pypi.python.org/pypi/homebrew-pypi-poet which are then inserted into the formula and this is what needs to be done here and all other formulae constructed this way.

2019-08-30 13:10 UTC, jeffbyrnes commented
So yeah, the patch won’t work that way, since this is a generated binary we’re installing.

So either @javian’s suggestion, or manually copying in the new reps, is what’s needed here.

@chenrui333 if you want to close this, I’m happy to take care of it instead!

2019-09-14 18:40 UTC, fxcoudert commented
@jeffbyrnes we'll take you up on that offer :)

2019-09-14 18:40 UTC, closed without merging