onnxruntime 0.5.0 (new formula)
Homebrew/homebrew-core pull request #43500
Opened 2019-08-27 05:31 UTC by ankane

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-08-27 07:49 UTC, SMillerDev requested changes

2019-08-27 07:49 UTC, SMillerDev commented on Formula/onnxruntime.rb
> +  url "https://github.com/microsoft/onnxruntime/releases/download/v0.5.0/onnxruntime-osx-x64-0.5.0.tgz"
All formulae need to be build from source, unless the binaries are cross platform. See https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

2019-08-27 09:16 UTC, SMillerDev commented on Formula/onnxruntime.rb
> +    system "python3", "tools/ci_build/build.py", "--build_dir", "build/Linux",
It might be better to refer to this as `#{bin}/python3`

2019-08-27 09:16 UTC, SMillerDev commented on Formula/onnxruntime.rb
> +    system "python3", "tools/ci_build/build.py", "--build_dir", "build/Linux",
is `build/Linux` the correct directory for a macOS build?

2019-08-27 09:16 UTC, SMillerDev commented on Formula/onnxruntime.rb
> +           "--config", "RelWithDebInfo", "--build_shared_lib", "--skip_submodule_sync"
We probably don't want debug info in the formula

2019-08-28 05:19 UTC, SMillerDev commented
I see upstream responded. We'll await their new version

2019-08-30 01:14 UTC, ankane commented
Hey @SMillerDev, thanks for all the feedback. Unfortunately, it's a bit out of my expertise to get it running on Sierra. Unless there's a way to mark the formula as High Sierra or above, let's close and revisit once support for Sierra is dropped.

2019-08-30 04:44 UTC, closed without merging

2019-10-07 21:20 UTC, ankane commented
Hey @SMillerDev, it looks like Homebrew CI has added Catalina and dropped Sierra. Is it possible to reopen this (or should I create a new PR)?