Update profanity.rb
Homebrew/homebrew-core pull request #43789
Opened 2019-09-02 21:16 UTC by Bedrovelsen

Update formula for profanity 0.7.0 as homebrew-core formula for profanity is still at 0.6.0

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
yes

- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
yes

- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?

Not working yet for path/ruby? reasons I have not been able to fix as of yet
```
Error: failed to install the 'bundler' gem.
Error: brew audit failed!
```

- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
WIP

- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
See Above 

-----

2019-09-02 22:08 UTC, Moisan requested changes
Please remove the comment regarding the previous checksum and squash your commits with the commit message 
```
profanity 0.7.0
```

2019-09-02 22:08 UTC, Moisan commented on Formula/profanity.rb
>    # checksum change reported upstream at https://github.com/profanity-im/profanity/issues/1094
Could you remove this line too?

2019-09-03 04:38 UTC, Bedrovelsen commented on Formula/profanity.rb
>    # checksum change reported upstream at https://github.com/profanity-im/profanity/issues/1094
Done in 43789

2019-09-03 05:14 UTC, SMillerDev commented
Thanks @Bedrovelsen

2019-09-03 18:50 UTC, Bedrovelsen commented
> Thanks @Bedrovelsen

You’re welcome.

2019-09-03 23:01 UTC, closed without merging