Routine update of hledger to the latest release
Homebrew/homebrew-core pull request #43792
Opened 2019-09-02 23:45 UTC by simonmichael

2019-09-03 00:59 UTC, jonchang requested changes

2019-09-03 00:59 UTC, jonchang commented on Formula/hledger.rb
please add the correct `sha256` for this file. Try: `curl -L https://hackage.haskell.org/package/hledger-1.14.2/hledger-1.14.2.tar.gz | shasum -a 256`

2019-09-03 00:59 UTC, jonchang commented on Formula/hledger.rb
> -    sha256 "60422bb49e6e62f26780cec246007cfa38dc8fcb33c6718591e7f7e72fb44c2a" => :sierra
Do not modify `bottle` blocks for version bumps.

2019-09-03 00:59 UTC, jonchang commented on Formula/hledger.rb
> -    sha256 "a1eacde5b9d531df0875b65c8239e8351749610e1e6e46c847dd02594fb6a970"
Please add the correct `sha256`

2019-09-03 00:59 UTC, jonchang commented on Formula/hledger.rb
> +    url "https://hackage.haskell.org/package/hledger-ui-1.15/hledger-ui-1.15.tar.gz"
Please add the correct `sha256`

2019-09-03 13:52 UTC, simonmichael commented
@jonchang, thanks for the tips - new commit pushed.

2019-09-05 01:11 UTC, simonmichael commented
@jonchang: ready for your merge. Thanks!

2019-09-05 02:15 UTC, jonchang approved these changes

2019-09-05 02:17 UTC, jonchang commented
Thanks for making these changes @simonmichael! Please amend the commit message to [conform to our commit message style](https://docs.brew.sh/Formula-Cookbook#commit), then rebase on master, force-push, and ping me so we can get this update merged.

2019-09-05 02:33 UTC, simonmichael commented
Thanks @jonchang - done. I appreciate the almost there tag. :-)

2019-09-05 02:41 UTC, jonchang commented
Please update the commit message to `hledger 1.15.1`

2019-09-05 04:46 UTC, simonmichael commented
Oops. Done, @jonchang.

2019-09-05 15:22 UTC, fxcoudert commented
Thanks @simonmichael for your contribution to Homebrew!

2019-09-05 15:23 UTC, closed without merging