Gecode fixes
Homebrew/homebrew-core pull request #4439
Opened 2016-09-02 09:35 UTC by liuq

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

The SHA256 signature of the source tar.gz file was wrong and it has been fixed.
Moreover, a new option "with-qt" has been added to allow the compilation of
the Qt based graphical search inspector "gist".

2016-09-02 18:17 UTC, DomT4 commented
> The SHA256 signature of the source tar.gz file was wrong and it has been fixed.

Can you find out why it changed? Thanks. It will have been correct whenever the change was merged.

> Moreover, a new option "with-qt" has been added to allow the compilation of
the Qt based graphical search inspector "gist".

Can it use Qt5? We'd prefer not to add any more `qt` dependencies because it's very likely `qt` won't work on Sierra & we aren't intending to carry another hacky patch for another year.

2016-10-01 17:37 UTC, MikeMcQuaid commented
@liuq Any news on this?

2016-10-08 07:08 UTC, liuq commented
I cannot deploy before testing with QT5 (as requested), but homebrew QT5 is currently broken.

2016-10-08 07:22 UTC, ilovezfs commented
@liuq https://github.com/Homebrew/homebrew-core/pull/5619 is sufficient to build if you have the patience for a qt5 build.

2016-10-08 16:56 UTC, MikeMcQuaid commented
We won't be adding any more `qt` dependencies so happy to make this PR Qt-less for now.

2016-10-10 07:28 UTC, liuq commented
@MikeMcQuaid In general I would agree, however the value of Gecode w.r.t the rsystems is in its (qt-based) debugging tools. I try to check with the #5619 if I can get a working qt5 environment.

2016-10-10 08:25 UTC, MikeMcQuaid commented
> I try to check with the #5619 if I can get a working qt5 environment.

Thanks!

2016-10-10 11:24 UTC, liuq commented
That's it, the current formula is qt5 compliant.

2016-10-10 14:23 UTC, Moisan commented
I wrote [upstream](http://www.gecode.org/bugs.html) to ask if the change to the source without version change was intentional.

2016-10-10 14:25 UTC, liuq commented
Yes, it is, the version is the very same but, probably, the source file on
the repository has changed (and the SHA signature accordingly).

Il giorno lun 10 ott 2016 alle 16:23 Thierry Moisan <
notifications@github.com> ha scritto:

> I wrote upstream <http://www.gecode.org/bugs.html> to ask if the change
> to the source without version change was intentional.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-core/pull/4439#issuecomment-252636001>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABEGUISf1nhaKJOYKejsI8Z6UJAhfk9Vks5qykpjgaJpZM4JziFN>
> .
>

2016-10-10 15:56 UTC, MikeMcQuaid commented
I'd rather we wait for a response first to ensure they've not been hacked.

2016-10-11 09:20 UTC, liuq commented
@MikeMcQuaid will you handle that? In case you can write to Christian Schulte cschulte@kth.se, who is one of the main gecode maintainers

2016-10-11 11:42 UTC, ilovezfs commented
@BrewTestBot test this please

2016-10-11 13:08 UTC, Moisan commented
I've got a [response from upstream](http://www.gecode.org/pipermail/bugs/2016-October/000336.html). 

> this was not intentional, but rather a side effect of updating one of the binary packages (which caused a new version of the source packages to be uploaded as well).  There has not been any change to the source code itself so it is safe to update the SHA256 to the new one.

2016-10-11 13:13 UTC, MikeMcQuaid commented
@Moisan Thanks!

2016-10-12 07:15 UTC, MikeMcQuaid requested changes

2016-10-12 07:15 UTC, MikeMcQuaid commented on Formula/gecode.rb
> +    ENV.append "CXXFLAGS", "-std=c++11"
Instead use `ENV.cxx11` and see if that's sufficient.

2016-10-12 07:15 UTC, MikeMcQuaid commented on Formula/gecode.rb
>  end
Any chance you could add a simple test e.g. ideally something more substantial than e.g. `--version` or `--help` but just use them if necesssary? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2016-10-12 08:48 UTC, liuq commented on Formula/gecode.rb
>  end
Done!

2016-10-12 09:00 UTC, MikeMcQuaid requested changes

2016-10-12 09:00 UTC, MikeMcQuaid commented on Formula/gecode.rb
> +      -I#{HOMEBREW_PREFIX}/include
`-I#{include}`

2016-10-12 09:00 UTC, MikeMcQuaid commented on Formula/gecode.rb
> +    ]
Just hard-code these args (but split them over multiple lines to avoid exceeding 80 characters).

2016-10-12 09:00 UTC, MikeMcQuaid commented on Formula/gecode.rb
> +    system "./test | grep -q \"{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}\""
Replace the above two lines with `assert_match "{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}", shell_output("./test")`

2016-10-12 09:10 UTC, liuq commented on Formula/gecode.rb
> +    system "./test | grep -q \"{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}\""
Ok, did it!

2016-10-12 16:14 UTC, MikeMcQuaid approved these changes

2016-10-12 16:16 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-10-12 16:16 UTC, closed without merging

2016-10-12 18:11 UTC, liuq commented
It's a pleasure to contribute to the community.

Il giorno mer 12 ott 2016 alle 18:16 Mike McQuaid <notifications@github.com>
ha scritto:

> Closed #4439 <https://github.com/Homebrew/homebrew-core/pull/4439> via
> c5dbfe2
> <https://github.com/Homebrew/homebrew-core/commit/c5dbfe2d11489720fd4c24fc4cfed7f3a10d17ab>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-core/pull/4439#event-821225108>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABEGUFYF763VX3TiOcSVvBpC6XDB4CwQks5qzQfsgaJpZM4JziFN>
> .
>