nginx 1.17.4
Homebrew/homebrew-core pull request #44562
Opened 2019-09-25 01:36 UTC by shigemk2

Created with `brew bump-formula-pr`.

2019-09-25 08:21 UTC, SMillerDev commented
Passenger needs a revision bump

2019-10-06 12:05 UTC, fxcoudert requested changes

2019-10-06 12:05 UTC, fxcoudert commented on Formula/nginx.rb
>    revision 1
`revision` here should be removed.
`passenger` formula needs a revision bump (in a separate commit)

2019-11-13 01:24 UTC, Moisan commented
Closing in favor of #45685 .

2019-11-13 01:24 UTC, closed without merging