rust 1.38.0
Homebrew/homebrew-core pull request #44625
Opened 2019-09-27 09:16 UTC by shigemk2

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2019-09-27 12:48 UTC, Br1ght0ne approved these changes

2019-09-30 12:20 UTC, SMillerDev commented
@brewtestbot test this please!

2019-10-03 05:12 UTC, shigemk2 commented
@BrewTestBot test this please!

2019-10-03 10:15 UTC, fxcoudert requested changes

2019-10-03 10:15 UTC, fxcoudert commented on Formula/rust.rb
>    revision 1
`revision` should be removed

2019-10-04 08:00 UTC, closed without merging