Boost: fix missing cmake files
Homebrew/homebrew-core pull request #44984
Opened 2019-10-07 21:19 UTC by henryiii

Fix #44093 by installing to a staging area, then copying unique files to python or mpi. This adds the Cmake files that are currently missing. Drops workarounds in two formulas due to this bug.

There still are warnings when using Boost's Cmake files due to an issue in upstream that should be fixed in 1.72 (I believe). It happens because we provide both MT and non-MT libraries; if we only provided one, the warnings would go away.

2019-10-08 07:47 UTC, fxcoudert commented
> Drops workarounds in two formulas

Passing `Boost_NO_BOOST_CMAKE` is a pretty straightforward workaround. The staging changes you're proposing feel like a more invasive hack.

Am I right in understanding that all this is working around an upstream bug in Boost?

2019-10-08 13:52 UTC, henryiii commented
> Passing `Boost_NO_BOOST_CMAKE` is a pretty straightforward workaround. The staging changes you're proposing feel like a more invasive hack.

Homebrew is producing broken CMake configs, forcing anyone using this formula (not just other formulas) to use this workaround. Producing proper, unbroken CMake configs is better.

> Am I right in understanding that all this is working around an upstream bug in Boost?

Not really. Upstream boost only produces CMake files when you install. Due to the way this was set up in homebrew, the extra parts (python, mpi) are never installed (to avoid re-adding the headers), and instead copied in from the build directory. Build directories are not required to be the same as the install, so I don't consider this much of a workaround, or a bug in Boost.

However, we have a new problem (as I've mentioned in the linked issue): boost-python and boost-python3 produce CMake files with the same name. This is either a bug in upstream Boost, or a big problem for us supporting both versions of Python.

2019-10-08 16:40 UTC, scpeters commented
> boost-python and boost-python3 produce CMake files with the same name

what if we made boost-python keg-only?

2019-10-08 19:33 UTC, henryiii commented
The suggestion from boost-python upstream was to make a common package that was a dependency of the two packages.

We could also require boost-python users to use the no CONFIG workaround, and only supply config files for boost-python3.

2019-10-08 19:37 UTC, scpeters commented
> We could also require boost-python users to use the no CONFIG workaround, and only supply config files for boost-python3.

👍

2019-10-08 19:43 UTC, henryiii commented
>  only supply config files for boost-python3.

We currently only supply the numpy extension with boost-python3, due to the same issue of matching names (AFAICT).

2019-10-10 04:25 UTC, henryiii commented
Are the remaining failures even related?

2019-10-10 14:22 UTC, fxcoudert requested changes
Please make sure we have one commit per formula

2019-10-10 14:22 UTC, fxcoudert commented on Formula/boost-python.rb
> +  def caviats; <<~EOS
```suggestion
  def caveats; <<~EOS
```

2019-10-10 14:22 UTC, fxcoudert commented on Formula/boost-mpi.rb
> +    (lib / "cmake").install Dir["install-mpi/lib/cmake/*mpi*"]
```suggestion
    (lib/"cmake").install Dir["install-mpi/lib/cmake/*mpi*"]
```

2019-10-10 14:22 UTC, fxcoudert commented on Formula/boost-python.rb
> +    # This causes a collision with boost-python3
Remove the commented lines

2019-10-10 14:22 UTC, fxcoudert commented on Formula/boost-python3.rb
> +    (lib / "cmake").install Dir["install-python3/lib/cmake/boost_python*"]
```suggestion
    (lib/"cmake").install Dir["install-python3/lib/cmake/boost_python*"]
```

2019-10-10 14:22 UTC, fxcoudert commented on Formula/boost-python3.rb
> +    (lib / "cmake").install Dir["install-python3/lib/cmake/boost_numpy*"]
```suggestion
    (lib/"cmake").install Dir["install-python3/lib/cmake/boost_numpy*"]
```

2019-10-10 17:18 UTC, henryiii commented
Done.

2019-10-13 19:45 UTC, fxcoudert commented
Thanks @henryiii ! Merging

2019-10-13 19:45 UTC, closed without merging