ksh-2020.0.0: Latest stable release of KornShell
Homebrew/homebrew-core pull request #45768
Opened 2019-10-24 17:52 UTC by siteshwar

New stable release of ksh primarily features:

- Switch to new and saner build system
- Hundreds of bug fixes
- Better test coverage

More details can be found at:

https://groups.google.com/d/msg/korn-shell/-tQkll8BxXU/X4ON61CHBwAJ

It is already rebased in Fedora, Debian, Gentoo, FreeBSD and several
other well known distros.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-10-25 03:01 UTC, krader1961 commented
FWIW, I've probably contributed more bug fixes and enhancements to ksh in the past couple of years than anyone else. I'd love to see this PR merged so that Homebrew users can easily obtain an updated version of the `ksh` shell. I can't speak to the correctness of this PR but am confident that something like this will provide a much improved `ksh` command to Homebrew users.

2019-10-28 01:56 UTC, Moisan requested changes
Outside of the `bottle` block, looks good to me.

2019-10-28 01:56 UTC, Moisan commented on Formula/ksh.rb
> -  end
Please do not remove the `bottle` block, our merging process will update it automatically.

2019-10-28 10:47 UTC, siteshwar commented
> Outside of the `bottle` block, looks good to me.

Fixed.

2019-11-05 14:16 UTC, chenrui333 approved these changes

2019-11-06 06:21 UTC, fxcoudert commented
The caveats are not necessary, and the `init` resource was unused.

2019-11-07 14:47 UTC, closed without merging