Update root.rb
Homebrew/homebrew-core pull request #45843
Opened 2019-10-26 09:59 UTC by cxwx

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-10-26 10:00 UTC, cxwx commented
root add fits feature

2019-10-26 15:24 UTC, Moisan requested changes

2019-10-26 15:24 UTC, Moisan commented on Formula/root.rb
> + # end
Please do not change the `bottle` block. It is automatically updated when we merge the pull request.

2019-10-27 08:42 UTC, fxcoudert commented
poke @henryiii who is our “master of ROOT”

Given that Homebrew has a `cfitsio` formula, could we rely on that instead of building one inside root?

2019-10-27 11:20 UTC, henryiii commented
We should be able to use the external package; in conda-forge we build with an external cfitsio:

https://github.com/conda-forge/root-feedstock/blob/master/recipe/meta.yaml#L82

2019-10-27 11:24 UTC, henryiii commented
Add:

```ruby
depends_on "cfitsio"
```

And revert the built-in line. I *think* root will automatically enable it if it finds it, it has lots of optional features it treats this way, but go ahead and be explicit and keep the cfitsio=ON option.

2019-11-09 14:37 UTC, closed without merging