Update to minetest.rb with bug fix
Homebrew/homebrew-core pull request #46213
Opened 2019-11-03 09:13 UTC by johnlockard

This update fixes version 5.1.0 main.cpp missing header file for irrlicht.

2019-11-08 08:41 UTC, johnlockard commented
I think this is the error.

======
2019-11-03 08:17:46.252 GMT [51641] DETAIL:  Failed system call was shmget(key=5432005, size=56, 03600).
2019-11-03 08:17:46.252 GMT [51641] HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
====

But I don't know how to raise the shared memory IDs. Does anyone know how to do this?

2019-11-21 23:24 UTC, Bo98 requested changes
The error you mentioned should now be fixed - apologies for the disruption. I can restart the CI, but there's a few concerns I have first.

2019-11-21 23:24 UTC, Bo98 commented on Formula/minetest.rb
> +    url "https://github.com/johnlockard/minetest/archive/5.1.0.tar.gz"
This doesn't look official. Why aren't you using the official repository?

If there's a particular patch that's required, you can do that separately in a `patch do` block, assuming the patch has been accepted upstream:

```ruby
patch do
  url "https://github.com/org/repo/commit/whatever.patch?full_index=1"
  sha256 "abcdef"
end
```

Very similar to the `resource do` block.

2019-11-21 23:24 UTC, Bo98 commented on Formula/minetest.rb
> +  depends_on :x11
Is this needed? We generally avoid X11 where possible.

2019-11-21 23:24 UTC, Bo98 commented on Formula/minetest.rb
> +  depends_on "spatialindex"
Can you explain a bit behind the extra dependencies. Are they optional? If so, what benefit do each bring?

2019-11-21 23:24 UTC, Bo98 commented on Formula/minetest.rb
> +    system "#{prefix}/minetest.app/Contents/MacOS/minetest", "--videomodes"
Considering this uses a `.app`, I think it is better for this formula to be moved to Homebrew Cask.

https://docs.brew.sh/Acceptable-Formulae#stuff-that-builds-an-app

2019-12-24 16:21 UTC, fxcoudert commented
Closing due to lack of response.

2019-12-24 16:21 UTC, closed without merging