Adding new formula for sdees
Homebrew/homebrew-core pull request #4636
Opened 2016-09-08 21:18 UTC by lorenzschmid

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

sdees is is wrapper for vim/nano/emacs allowing to make time-stamped entries to an encrypted document while keeping the entire document synchronized remotely. It is actively maintained on GitHub.

2016-09-08 21:26 UTC, bfontaine commented on Formula/sdees.rb
> +  url "https://github.com/schollz/sdees/releases/download/1.2.1/sdees_osx_amd64.zip"
We need to build from source.

2016-09-08 21:33 UTC, lorenzschmid commented on Formula/sdees.rb
> +  url "https://github.com/schollz/sdees/releases/download/1.2.1/sdees_osx_amd64.zip"
Sorry for that, tried to figure out if build or source release is needed. Will update this PR.

2016-10-06 08:00 UTC, bfontaine requested changes

2016-10-06 08:00 UTC, bfontaine commented on Formula/sdees.rb
> +  url "https://github.com/schollz/sdees/releases/download/1.2.1/sdees_osx_amd64.zip"
@lorenzschmid ping on this?

2016-10-06 19:28 UTC, closed without merging