llvm --HEAD must require xcode
Homebrew/homebrew-core pull request #4651
Opened 2016-09-09 03:04 UTC by yurikoles

- [*] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [*] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [*] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?

closes #4564

2016-09-09 03:31 UTC, yurikoles commented
How to specify min Xcode version?

2016-09-09 04:30 UTC, zmwangx commented
`depends_on :xcode => "7.3"`

Or whatever version you want here.

2016-09-09 04:31 UTC, zmwangx commented on Formula/llvm.rb
> +    end
```ruby
depends_on :xcode => "<version>" if build.with? "toolchain"
```

2016-09-18 15:00 UTC, yurikoles commented
How to combine Xcode version check and macOS version check? Because we need 8.0 on Sierra and up.

2016-09-18 15:21 UTC, zmwangx commented
> How to combine Xcode version check and macOS version check?

If you want to specify hard requirements:

```ruby
depends_on :xcode => "8.0"
depends_on :macos => :sierra
```

If you want a conditional in the `install` block for instance:

```ruby
if MacOS.version == :sierra && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
  # do something
end
```

2016-09-18 15:59 UTC, yurikoles commented
@zmwangx I no longer think that we need to specify Xcode version in formulae, since there is already check for Xcode version <=8.0.

2016-09-18 16:05 UTC, zmwangx commented
Sorry, this cannot be merged as is because at the very least you need to address my old comment. Other than that, we also need someone more knowledgeable about LLVM than me to decide if this is the right change (probably is) and whether we need additional tweaks.

2016-09-18 16:18 UTC, yurikoles commented
I had problems building with Xcode 7.3 on Sierra, this is why I wanted to explicitly specify Xcode version. But this problem is so common that there is now fall with error if one uses old Xcode on Sierra. So I no longer see the reason to specify Xcode version in formulae.

2016-09-18 16:19 UTC, zmwangx commented
To be clear, you need to address [this](https://github.com/Homebrew/homebrew-core/pull/4651/files#r78127572).

2016-09-18 16:46 UTC, yurikoles commented
up & rebase

2016-09-18 17:07 UTC, zmwangx commented on Formula/llvm.rb
> +    depends_on :xcode => "7.3" if build.with? "toolchain" && MacOS.version <= :el_capitan
This doesn't look right, there's no Xcode 7.3 on Yosemite and below.

2016-09-18 17:07 UTC, zmwangx requested changes

2016-09-18 17:09 UTC, yurikoles commented
I will run checks on VM.

2016-09-18 21:08 UTC, yurikoles commented
So I had tried this formula in El Capitan with Xcode 7.0 and it seems like version check doesn't work.

2016-10-15 10:55 UTC, MikeMcQuaid commented
Passing on this due to unaddressed comments.

2016-10-15 10:55 UTC, closed without merging