dart: 2.6.1 (new formula)
Homebrew/homebrew-core pull request #47442
Opened 2019-12-03 15:24 UTC by JarryShaw

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Official formula for the Dart SDK from `dart-lang/dart/dart`.

2019-12-04 02:37 UTC, jonchang requested changes
Formulae in Homebrew-core must build from source or produce cross-platform binaries. See https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae for details.

2019-12-04 08:14 UTC, SMillerDev commented on Formula/dart.rb
> +  devel do
Please don't use devel blocks

2019-12-04 08:14 UTC, SMillerDev commented on Formula/dart.rb
> +    EOS
Please use the build-in envscript option.

2019-12-04 08:14 UTC, SMillerDev commented on Formula/dart.rb
> +  end
This is standard for homebrew and shouldn't be a caveat.

2019-12-04 10:32 UTC, JarryShaw commented
This is the official formula of Dart language SDK, copied directly from [`dart-lang/dart/dart`](https://github.com/dart-lang/homebrew-dart/tree/master/dart.rb).

2019-12-04 10:40 UTC, SMillerDev commented
Taps don't need to adhere to https://docs.brew.sh/Acceptable-Formulae though, submissions to homebrew-core do.

2019-12-04 10:42 UTC, JarryShaw commented
Understood @SMillerDev ; was just adding notes about the formula's origin :)

2019-12-04 12:26 UTC, JarryShaw commented
And I suppose I need to use some help on this. Not even familiar with Dart itself.
Contributing this formula just because `dart-sass` at #47438 needs it.

2019-12-24 14:43 UTC, fxcoudert commented
We're going to close this for now, it is very far from being acceptable and will require more work from  someone who knows dart.

2019-12-24 14:43 UTC, closed without merging