Feature/add awscurl formula
Homebrew/homebrew-core pull request #47715
Opened 2019-12-11 07:09 UTC by okigan

- [ x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2019-12-11 09:58 UTC, SMillerDev commented
Please squash all of your commits into one and fix the audit and style failures

2019-12-13 21:01 UTC, okigan commented
@SMillerDev please advise on the remaining failing issues -- I think it's related to python dependencies install, but my attempts to resolve did not succeed

2019-12-19 08:45 UTC, okigan commented
Bumping this up, opening for general comment: please advise on the remaining failing issues -- I think it's related to python dependencies install, but my attempts to resolve did not succeed

2019-12-19 09:44 UTC, jonchang requested changes
The test failure looks like an upstream issue. Generally `main()` should not take arguments in a Python script, and that's likely what's causing the test failure.

Additionally, there were audit failures:

```
        Error: 2 problems in 1 formula detected
awscurl:
  * C: 14: col 1: Extra blank line detected.
  * C: 77: col 1: Extra blank line detected.
```

2019-12-19 09:44 UTC, jonchang commented on Formula/awscurl.rb
> +  # bottle block here.
Remove these comments.

2019-12-19 09:44 UTC, jonchang commented on Formula/awscurl.rb
> +    assert_match "Curl", shell_output("#{bin}/awscurl --help")
Test failures from CI:

```
==> /usr/local/Cellar/awscurl/ec83491d6b1e123af1bf100947731e113a32468d/bin/awscurl --help
Traceback (most recent call last):
  File "/usr/local/Cellar/awscurl/ec83491d6b1e123af1bf100947731e113a32468d/bin/awscurl", line 11, in <module>
    load_entry_point('awscurl==0.19', 'console_scripts', 'awscurl')()
TypeError: main() missing 1 required positional argument: 'argv'
Error: awscurl: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

2019-12-21 00:10 UTC, closed without merging

2019-12-21 02:58 UTC, chenrui333 commented
Relates to #48129