Use "HEAD" as version for --HEAD builds
Homebrew/homebrew-core pull request #4783
Opened 2016-09-13 19:57 UTC by aw1621107

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

Before, the version string would be empty, resulting in names like gcc-
and g++-, which tripped up brew when looking for a gcc install. This,
coupled with a tweak to brew to allow HEAD as a gcc version string,
should allow HEAD builds to be recognized

2016-09-13 20:20 UTC, zmwangx commented
Updated your title because it sounded generic and I was wondering from the outside (PR list) why a generic PR was made on homebrew-core instead of brew.

2016-09-13 20:34 UTC, zmwangx commented
I killed the build by the way because the change doesn't affect what is actually tested on the CI, and it's kind of pointless to reinstall all those dependents which could take a long long time.

2016-09-13 20:47 UTC, aw1621107 commented
Oops, completely forgot about the titling scheme over here. Thanks for fixing it!

2016-09-14 02:45 UTC, apjanke commented
:+1: on this.

Would be nice if the commit message was changed to use the same format as the PR title, too.

2016-09-14 13:40 UTC, aw1621107 commented
Alright, updated the commit message. Switched a few words around to keep it under the 50 character limit, but should be similar enough

2016-09-14 15:55 UTC, aw1621107 commented
And pushed the updated version. `--HEAD` builds now result in `gcc-7`, `g++-7`, etc. being installed.

2016-09-16 14:10 UTC, zmwangx commented
Why the close?

2016-09-16 14:11 UTC, aw1621107 commented
Oh, whoops. Thought this was done for some reason. Give me a second...

2016-09-27 03:21 UTC, DomT4 commented
Where was this left? Were people happy or?

2016-09-27 13:54 UTC, aw1621107 commented
Not entirely sure? The change to brew core got merged, so I think this should be ok?

2016-09-28 08:20 UTC, MikeMcQuaid commented
I'm good with this, thanks @aw1621107!

2016-09-28 08:20 UTC, MikeMcQuaid commented
Just want to see CI run once first.

2016-09-28 08:21 UTC, MikeMcQuaid commented
@BrewTestBot test this please

2016-09-28 13:59 UTC, MikeMcQuaid requested changes

2016-09-28 13:59 UTC, MikeMcQuaid commented on Formula/gcc.rb
> +      ("#{stable.version}".slice(/\d/).to_i + 1).to_s
`stable.version.to_s` instead then this is good to 🚢

2016-09-28 14:02 UTC, aw1621107 commented on Formula/gcc.rb
> +      ("#{stable.version}".slice(/\d/).to_i + 1).to_s
Shouldn't it be `(stable.version + 1).to_s?`

2016-09-28 14:02 UTC, aw1621107 commented on Formula/gcc.rb
> +      ("#{stable.version}".slice(/\d/).to_i + 1).to_s
Or `(stable.version.to_i + 1).to_s`. Still not familiar with how things work...

2016-09-28 14:03 UTC, MikeMcQuaid commented on Formula/gcc.rb
> +      ("#{stable.version}".slice(/\d/).to_i + 1).to_s
Still need the `slice` to get only the first digit.

2016-09-28 14:07 UTC, aw1621107 commented on Formula/gcc.rb
> +      ("#{stable.version}".slice(/\d/).to_i + 1).to_s
Oh, I think I see what you're getting at. Fixed, I hope

2016-09-29 14:37 UTC, MikeMcQuaid commented
@aw1621107 Why close this?

2016-09-29 14:38 UTC, aw1621107 commented
Dangit, thought it was done for some reason. My mistake.

2016-09-29 21:09 UTC, DomT4 commented
Happy here unless Mike wants a clean CI run to check we haven't borked stable or such.

2016-09-30 07:13 UTC, MikeMcQuaid commented
@DomT4 Yeh, going to do that. @zmwangx please don't abort it this time, thanks.

2016-10-15 10:56 UTC, MikeMcQuaid approved these changes

2016-10-15 10:56 UTC, merged

2016-10-15 10:56 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-12-07 16:18 UTC, ilovezfs commented
@aw1621107 @MikeMcQuaid This has broken HEAD builds of formulae that need gcc.

```
iMac-TMP:homebrew-science joe$ brew install --HEAD lightstringgraph
==> Installing lightstringgraph from homebrew/science
==> Installing dependencies for homebrew/science/lightstringgraph: beetl
==> Installing homebrew/science/lightstringgraph dependency: beetl
==> Downloading https://homebrew.bintray.com/bottles-science/beetl-0.10.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring beetl-0.10.0.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/beetl/0.10.0: 27 files, 4.7M
==> Installing homebrew/science/lightstringgraph
==> Using the sandbox
Error: No available formula with the name "gcc6" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
homebrew/versions/gcc6
To install it, run:
  brew install homebrew/versions/gcc6
```

2016-12-07 16:51 UTC, aw1621107 commented
@ilovezfs That's... interesting. If the stable version of gcc was installed, it should have exactly the same behavior as before this change. The name should also be `gcc-6`. Not sure where the hyphen went.

2016-12-07 19:21 UTC, aw1621107 commented
@MikeMcQuaid @ilovezfs I think I see what's going on. I'll have a PR shortly.