Add kube-aws 0.8.1
Homebrew/homebrew-core pull request #4797
Opened 2016-09-14 05:48 UTC by jskswamy

- [✓] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [✓] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [✓] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [✓] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

2016-09-16 02:47 UTC, dunn commented on Formula/kube-aws.rb
> +    executable="bin/kube-aws"
Could you add spaces on each side of operators? It makes things a lot more readable.

2016-09-16 02:48 UTC, dunn commented on Formula/kube-aws.rb
> +    rm_rf %w(ENV['GOPATH_VENDOR'] ENV['GOPATH_KUBE_AWS'])
I think you want `[ENV['GOPATH_VENDOR'], ENV['GOPATH_KUBE_AWS']]` here.

2016-09-16 02:49 UTC, dunn commented on Formula/kube-aws.rb
> +    system "go build -ldflags '-X github.com/coreos/coreos-kubernetes/multi-node/aws/pkg/cluster.VERSION=#{version}' -a -tags netgo -installsuffix netgo -o '#{ENV["OUTPUT_PATH"]}' ./cmd/kube-aws"
Pass each part of the string as a separate argument, like
```ruby
system "go", "build", "-ldflags" ...

2016-09-16 02:50 UTC, dunn commented on Formula/kube-aws.rb
> +    system "go build -ldflags '-X github.com/coreos/coreos-kubernetes/multi-node/aws/pkg/cluster.VERSION=#{version}' -a -tags netgo -installsuffix netgo -o '#{ENV["OUTPUT_PATH"]}' ./cmd/kube-aws"
And instead of `ENV['OUTPUT_PATH']`, you can just build it directly to `bin`.

2016-09-16 02:50 UTC, dunn commented on Formula/kube-aws.rb
> +    assert_match "kube-aws version #{version}", output
It'd be great to have a test that exercises the functionality more.

2016-09-18 06:36 UTC, jskswamy commented on Formula/kube-aws.rb
> +    executable = "bin/kube-aws"
Added space between operator for better readability

2016-09-18 06:37 UTC, jskswamy commented on Formula/kube-aws.rb
> +    rm_rf [ENV["GOPATH_VENDOR"], ENV["GOPATH_KUBE_AWS"]]
Prefer array syntax over %w syntax

2016-09-18 06:39 UTC, jskswamy commented on Formula/kube-aws.rb
> +    system "go", "build", "-ldflags", "-X github.com/coreos/coreos-kubernetes/multi-node/aws/pkg/cluster.VERSION=#{version}", "-a", "-tags", "netgo", "-installsuffix", "netgo", "-o", executable.to_s,
Prefer multiple arguments over single argument

2016-09-18 06:40 UTC, jskswamy commented on Formula/kube-aws.rb
> +    assert_equal cluster, cluster_info
Added assertion to test the generated cluster.yml file

2016-09-18 06:41 UTC, jskswamy commented on Formula/kube-aws.rb
> +    ENV["GOPATH"] = "#{ENV["GOPATH_VENDOR"]}:#{ENV["GOPATH_KUBE_AWS"]}"
Added space between operator for better readability

2016-09-22 00:52 UTC, dunn commented on Formula/kube-aws.rb
> +    ENV["GOPATH_VENDOR"] = "#{Dir.pwd}/_gopath-vendor"
You can use `buildpath` instead of `Dir.pwd`, here and in the next line.

2016-09-22 00:53 UTC, dunn commented on Formula/kube-aws.rb
> +    rm_rf [ENV["GOPATH_VENDOR"], ENV["GOPATH_KUBE_AWS"]]
Why are we deleting these then recreating them below?  What do they contain originally?

2016-09-22 00:54 UTC, dunn commented on Formula/kube-aws.rb
> +    ln "#{Dir.pwd}/vendor", "#{ENV["GOPATH_VENDOR"]}/src"
Use `ln_s` or `ln_sf` here and below.

2016-09-22 00:54 UTC, dunn commented on Formula/kube-aws.rb
> +    ln Dir.pwd.to_s, (ENV["KUBE_AWS_DIR"]).to_s
`ENV["KUBE_AWS_DIR"]` already is a string, so it doesn't need to be converted.

2016-09-22 00:55 UTC, dunn commented on Formula/kube-aws.rb
> +    system "go", "build", "-ldflags", "-X github.com/coreos/coreos-kubernetes/multi-node/aws/pkg/cluster.VERSION=#{version}", "-a", "-tags", "netgo", "-installsuffix", "netgo", "-o", executable.to_s,
Replace `executable.to_s` with `bin/"kube-aws"` and you can delete the `bin.install` line below.  Then you can remove the `executable` variable entirely.

Also, please add a line break or two here for readability.

2016-09-22 00:57 UTC, dunn commented on Formula/kube-aws.rb
> +    Dir.chdir "#{Dir.pwd}/multi-node/aws/"
Replace this with a `cd buildpath/"multi-node/aws" do` block.

2016-09-22 00:58 UTC, dunn requested changes
Sorry for the delay, but your formula is a bit complicated (probably more complicated than necessary), so I didn't get another chance to look through it until now.

2016-09-23 17:52 UTC, jskswamy commented on Formula/kube-aws.rb
> +    ENV["GOPATH_VENDOR"] = "#{buildpath}/_gopath-vendor"
Using buildpath instead of Dir.pwd

2016-09-23 17:52 UTC, jskswamy commented on Formula/kube-aws.rb
> -    Dir.chdir "#{Dir.pwd}/multi-node/aws/"
Using cd with block instead if Dir.chdir

2016-09-23 17:53 UTC, jskswamy commented on Formula/kube-aws.rb
> -    rm_rf [ENV["GOPATH_VENDOR"], ENV["GOPATH_KUBE_AWS"]]
Removed unnecessary code block

2016-09-23 17:55 UTC, jskswamy commented on Formula/kube-aws.rb
> +      bin.install executable => "kube-aws"
This is still required to avoid `Error: Empty installation`

2016-09-23 20:19 UTC, dunn commented on Formula/kube-aws.rb
> +      bin.install executable => "kube-aws"
See https://github.com/Homebrew/homebrew-core/pull/4797#discussion_r79963070; you should be able to build directly into `bin`.

2016-10-01 17:39 UTC, MikeMcQuaid commented
@jskswamy Any news on this?

2016-10-03 02:33 UTC, apjanke commented
Looks like this PR has several commits, and they're not interacting with GitHub's new "code review" mechanism well: when viewed on github.com, it doesn't look like prior change requests have been addressed.

Would you mind squashing this to a single commit and rebasing on `master`? That might tidy things up here.

2016-10-03 06:55 UTC, MikeMcQuaid commented
This was merged in https://github.com/Homebrew/homebrew-core/pull/5122.

2016-10-03 06:55 UTC, closed without merging