eventql 0.3.2 (new formula)
Homebrew/homebrew-core pull request #4846
Opened 2016-09-15 14:21 UTC by bartleusink

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

2016-09-15 14:25 UTC, zmwangx commented on Formula/eventql.rb
> +  url "http://dl.eventql.io/eventql/v0.3.2/eventql-0.3.2.tgz"
Let's try to use TLS: https://github.com/eventql/eventql/releases/download/v0.3.2/eventql-0.3.2.tgz.

2016-09-15 14:26 UTC, zmwangx commented on Formula/eventql.rb
> +
Remove the unnecessary blank line. Same below.

2016-09-15 14:27 UTC, zmwangx commented on Formula/eventql.rb
> +    system "#{bin}/evql", "--help"
```
system bin/"evql", "--help"
```

But is it possible to write a more substantial test that actually tries to do something with `evql`?

2016-09-15 14:27 UTC, zmwangx reviewed
A few comments otherwise 👍

2016-09-15 15:36 UTC, zmwangx commented on Formula/eventql.rb
> +      system "evqld", "--standalone", "--datadir", testpath, "--daemonize", "--pidfile", "pidfile"
Line too long, split into two.

2016-09-15 15:37 UTC, zmwangx commented on Formula/eventql.rb
> +                          "--prefix=#{prefix}"
Don't need a line break here, we only have 79 characters.

2016-09-15 15:39 UTC, zmwangx commented on Formula/eventql.rb
> +  depends_on "libtool" => :build
I suppose these should be `=> :build if build.head?`.

2016-09-15 15:39 UTC, zmwangx requested changes
Thanks for the fixes and the new test. A few more comments.

2016-09-15 16:02 UTC, bartleusink commented
Thanks for the feedback Zhiming!

2016-09-15 16:07 UTC, zmwangx commented on Formula/eventql.rb
> +    ENV.deparallelize
Is this necessary? Did you report the parallel make problem upstream?

2016-09-15 16:07 UTC, zmwangx reviewed
One last question (hopefully) which didn't come through last time for whatever reason.

2016-09-15 16:07 UTC, zmwangx approved these changes

2016-09-15 16:23 UTC, bartleusink commented on Formula/eventql.rb
> +    ENV.deparallelize
Without `ENV.deparallelize` I ran into this issue: https://github.com/eventql/eventql/issues/180

2016-09-15 16:34 UTC, zmwangx commented on Formula/eventql.rb
> +    ENV.deparallelize
Sure. Could you please add a comment above this line linking to the issue?

2016-09-15 17:03 UTC, zmwangx commented
FYI the test hangs locally on my machine (specifically the `evqld` command hangs, although running the command outside of `brew test` was fine). It doesn't appear to be a sandbox issue either. Were you able to run the test successfully?

2016-09-15 17:27 UTC, zmwangx commented
Indeed, test expired on the CI too.

2016-09-15 17:40 UTC, bartleusink commented
The test runs fine on my machine, but I remember the first time it triggered an OSX dialogue asking me whether I wanted `evqld` to open a port.
Could this be related to firewall settings?

2016-09-15 21:04 UTC, bartleusink commented
I've changed the way `evqld` is started, which seems to fix the hanging issue.

2016-09-15 21:05 UTC, zmwangx commented
Cool, I'm happy. Let's wait for a while to see if other maintainers have concerns.

2016-09-16 03:19 UTC, zmwangx commented on Formula/eventql.rb
> +        exec "#{bin}/evqld", "--standalone", "--datadir", testpath
`bin/"evqld"`.

2016-09-16 03:19 UTC, zmwangx commented on Formula/eventql.rb
> +      system "#{bin}/evql", "--database", "test", "-e", "SELECT 42;"
Same here.

2016-09-16 03:19 UTC, zmwangx requested changes
Sorry, this is the last, I promise.

2016-09-16 08:35 UTC, zmwangx approved these changes

2016-09-16 08:42 UTC, closed without merging

2016-09-16 08:43 UTC, zmwangx commented
Merged as 571583c. Thank you for your contribution to Homebrew!

P.S. Eventually I made another style change: grouping the head deps into a head do block. That one was my fault so I fixed it.

2016-09-16 08:44 UTC, bartleusink commented
Thanks for all your help getting this formula merged!