opensc: add pkcs11 caveats
Homebrew/homebrew-core pull request #48487
Opened 2020-01-02 22:25 UTC by liamdawson

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

As per #44786, the formula for OpenSC installs the pkcs11 driver in a way that the OpenSSH agent won't accept:

```
refusing PKCS#11 add of "/usr/local/Cellar/opensc/0.20.0/lib/opensc-pkcs11.so": provider not whitelisted
```

The OpenSC **cask** installs the driver in a manner that works. Noting this in the caveats should help for future users, as the only other advice I've seen is to copy or hard-link the library from the OpenSC formula, and that causes issues on formula updates.

The OpenSC formula skips the linking step if the cask is already installed, so formula updates should not cause issues with this method:

```
==> opensc cask is installed, skipping link.
```

2020-01-02 23:12 UTC, chenrui333 approved these changes
lgtm

2020-01-03 09:28 UTC, SMillerDev commented
I think hardcoding the commands is a bit much. Could you leave it at suggesting `unlink this formula and install the "caskname" cask.`

2020-01-04 19:49 UTC, zbeekman commented
I agree with @SMillerDev, @liamdawson could you please edit the caveat according to his suggestion with simpler language?

2020-01-04 19:53 UTC, zbeekman requested changes
Please use simpler, plain instructions in the caveat, no need for step by step commands, as requested by @SMillerDev

2020-01-04 19:53 UTC, zbeekman commented on Formula/opensc.rb
> +    the OpenSC cask:
```suggestion
    the OpenSC cask.
```

2020-01-04 19:53 UTC, zbeekman commented on Formula/opensc.rb
> +
```suggestion
```

2020-01-04 19:53 UTC, zbeekman commented on Formula/opensc.rb
> +    brew unlink opensc
```suggestion
```

2020-01-04 19:53 UTC, zbeekman commented on Formula/opensc.rb
> +    brew cask install opensc
```suggestion
```

2020-01-04 19:53 UTC, zbeekman commented on Formula/opensc.rb
> +
```suggestion
```

2020-01-04 19:53 UTC, zbeekman commented on Formula/opensc.rb
> +    (See https://github.com/Homebrew/homebrew-core/issues/44786)
```suggestion
```

I don't think anyone needs to be referred back to this issue. What do you think @SMillerDev?

2020-01-05 00:22 UTC, liamdawson commented
Squashed in the suggested changes.

2020-01-08 13:37 UTC, merged