b3sum 0.1.0 (new formula)
Homebrew/homebrew-core pull request #48917
Opened 2020-01-12 13:47 UTC by bric3

This commits adds the b3sum checsum utility based on the blake3 hash
function, see https://github.com/BLAKE3-team/BLAKE3 for more details.

> BLAKE3 is a cryptographic hash function that is:
>
> * Much faster than MD5, SHA-1, SHA-2, SHA-3, and BLAKE2.
> * Secure, unlike MD5 and SHA-1. And secure against length extension, unlike SHA-2.
> * Highly parallelizable across any number of threads and SIMD lanes, because it's a Merkle tree on the inside.
> * Capable of verified streaming and incremental updates, again because it's a Merkle tree.
> * A PRF, MAC, KDF, and XOF, as well as a regular hash.
> * One algorithm with no variants, which is fast on x86-64 and also on smaller architectures.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2020-01-12 13:57 UTC, fxcoudert requested changes

2020-01-12 13:57 UTC, fxcoudert commented on Formula/b3sum.rb
> +    system bin/"b3sum", "test.txt"
We want to test the output

2020-01-12 14:25 UTC, bric3 commented on Formula/b3sum.rb
> +    system bin/"b3sum", "test.txt"
👍  done

2020-01-31 05:45 UTC, chenrui333 approved these changes

2020-01-31 05:46 UTC, chenrui333 commented
@BrewTestBot test this please

2020-01-31 05:47 UTC, chenrui333 commented
Thanks @bric3 for your contribution to Homebrew! :tada: :first_place_medal:

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

2020-01-31 09:42 UTC, bric3 commented
@chenrui333 thanks, homebrew is awesome indeed, and it is up the community to keep it that way ;)

Many thanks for maintaining Homebrew !!  (for everyone)

2020-01-31 19:35 UTC, closed without merging