grapple 0.3.1 (new formula)
Homebrew/homebrew-core pull request #48918
Opened 2020-01-12 14:14 UTC by bric3

This formula adds a great download accelerator written in rust.
More on the repo readme https://github.com/daveallie/grapple

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2020-01-12 15:31 UTC, issyl0 requested changes

2020-01-13 09:56 UTC, bric3 commented on Formula/grapple.rb
> +    output = shell_output("#{bin}/kubeseal --version")
Hi, thanks I missed the kubeseal copy/paste.
Also thanks for the test tips !

2020-01-13 10:06 UTC, bric3 commented on Formula/grapple.rb
> +    output = shell_output("#{bin}/kubeseal --version")
Done
I used the URL that was used as an exmple there : https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

2020-02-21 08:34 UTC, bric3 commented
Can anyone chime in on this one?

2020-03-03 08:48 UTC, iMichka commented
> GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)

This looks like a low-usage tool with not much visibility. See https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

Sorry but we can't accept this formula right now.

2020-03-03 08:48 UTC, closed without merging

2020-03-03 09:07 UTC, bric3 commented
@iMichka Too bad, but I understand. Thanks for looking at the PR !