mpage 2.5.6 (new formula)
Homebrew/homebrew-core pull request #4896
Opened 2016-09-16 14:15 UTC by tchajed

2016-09-16 14:17 UTC, zmwangx commented on Formula/mpage.rb
> +  homepage "http://www.mesa.nl/pub/mpage/"
We need a homepage, and a directory listing is hardly a homepage unfortunately.

2016-09-16 14:18 UTC, zmwangx commented on Formula/mpage.rb
> +  version "2.5.6"
```
url "http://www.mesa.nl/pub/mpage/mpage-2.5.6.tgz"
```

No `version`. (This is Ruby by the way, not shell.)

2016-09-16 14:24 UTC, zmwangx commented on Formula/mpage.rb
> +    system bin/"mpage", "input.txt"
You sure this won't trigger a printer job?

2016-09-16 14:25 UTC, zmwangx commented on Formula/mpage.rb
> +    args = %W[
The Makefile is rather hilarious:

```Makefile
BINDIR=$(PREFIX)/bin
LIBDIR=$(PREFIX)/share
MANDIR=$(PREFIX)/man/man1
```

Just a comment. You should probably ask upstream to fix it.

2016-09-16 14:30 UTC, zmwangx commented on Formula/mpage.rb
> +  desc "Mpage, many to one page printing utility"
```ruby
ruby "Many to one page printing utility"
```

2016-09-16 14:31 UTC, zmwangx requested changes
Please review out [acceptable formulae criterion](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Acceptable-Formulae.md); we won't package software without a homepage. I do realize this software is packaged by Debian, though.

Also, please do not just ignore and delete our PR template. You haven't even tried the formula yourself prior to submission, which is a waste of time for everyone.

2016-09-16 14:34 UTC, zmwangx commented on Formula/mpage.rb
> +  homepage "http://www.mesa.nl/pub/mpage/"
I wonder if http://www.mesa.nl/pub/mpage/README can serve as a minimal homepage.

2016-09-16 15:24 UTC, tchajed commented on Formula/mpage.rb
> +    system bin/"mpage", "input.txt"
Yes, it outputs postscript to stdout.

2016-09-16 15:26 UTC, tchajed commented on Formula/mpage.rb
> +    args = %W[
This is definitely a dead project (the last release is from 2008). Arguably this disqualifies it from Homebrew core.

2016-09-16 15:29 UTC, tchajed commented on Formula/mpage.rb
> +  version "2.5.6"
I misinterpreted what `brew audit` wanted me to do, and I'm pretty sure I installed the formula with this syntax. In any case I've put the version in the URL and removed the call to url.

2016-09-16 15:29 UTC, tchajed commented
I actually didn't realize there was a PR template, since I created the pull request from hub, which [doesn't (yet) support GitHub pull request templates](https://github.com/Homebrew/homebrew-core/pull/4896). Rest assured the formula was tested and working locally.

2016-09-16 15:29 UTC, tchajed commented on Formula/mpage.rb
> +  desc "Mpage, many to one page printing utility"
done, thanks for catching

2016-09-16 15:30 UTC, tchajed commented on Formula/mpage.rb
> +  homepage "http://www.mesa.nl/pub/mpage/"
done

2016-09-16 16:32 UTC, zmwangx commented on Formula/mpage.rb
> +  version "2.5.6"
> I'm pretty sure I installed the formula with this syntax.

You must have had a good URL to begin with, downloaded with that URL, then switched to the bad one. Later when you run `brew install` it just picks up the downloaded file from cache and no longer checked that URL. `brew audit --new-formula` can catch that, though.

2016-09-16 16:34 UTC, zmwangx commented
> I actually didn't realize there was a PR template, since I created the pull request from hub, which doesn't (yet) support GitHub pull request templates. Rest assured the formula was tested and working locally.

Okay, please remember to use the web interface for Homebrew-related matters in the future, and follow the template rigorously. This time you submitted a non-functioning formula which you could not detect due to caching which is excusable, but if you have followed the steps `brew audit --new-formula` would have caught that.

2016-09-16 16:36 UTC, zmwangx approved these changes

2016-09-16 16:42 UTC, zmwangx commented
The formula itself looks fine now, thanks for the fixes.

As for whether it qualifies for Homebrew, I'm personally reluctant to carry stuff that's abandoned a long time ago because the burden completely falls on our shoulders when stuff breaks, but in this case the code may be simple and ancient enough to not have much of a compatibility problem going forward.

Half a vote from me for letting it in. But if anything happens to it in the future it goes straight to boneyard, no questions asked.

Other maintainers: thoughts?

2016-09-16 16:53 UTC, tchajed commented
I will make sure I use the template in the future.

However, I did indeed run both `brew audit --new-formula mpage` and `brew audit --strict --online mpage` - even without the cached file, neither detects an invalid URL. Perhaps this is a useful new feature for `brew audit`? It's certainly surprising to me that this isn't checked, given that the homepage URL is checked.

Thanks for taking the time to go through this formula!

2016-09-16 16:56 UTC, zmwangx commented
> even without the cached file, neither detects an invalid URL.

Sorry, I thought it checks `url` too, but apparently it only checks `homepage`. Really need `brew fetch --force` to detect it.

2016-09-16 16:57 UTC, zmwangx commented
Related: https://github.com/Homebrew/brew/issues/935

2016-09-16 18:13 UTC, zmwangx commented
@BrewTestBot test this please

2016-09-18 04:54 UTC, apjanke commented
Eight years since the last change and it's building fine. Sounds like good old battle-tested Unix software to me, and a low maintenance burden. I say let it in.

2016-09-18 04:57 UTC, zmwangx commented
After two days, 1.5 👍 , 0 👎 . I doubt we'll get 2 more 👎 any time soon, so in it goes.

2016-09-18 05:00 UTC, apjanke commented
:shipit:

2016-09-18 05:03 UTC, closed without merging

2016-09-18 05:11 UTC, zmwangx commented
Merged as 9b72166. Thank you for your contribution to Homebrew!