passenger: fix building on Sierra
Homebrew/homebrew-core pull request #4904
Opened 2016-09-16 20:37 UTC by CamJN

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

I found that I needed `apr` & `apu` for both Xcode & CLT builds, not sure about the upgrade situation as I'm using a VM for Sierra stuff for now so I only have a clean install to play with.

2016-09-17 13:24 UTC, zmwangx commented
@BrewTestBot Test this please.

2016-09-27 03:51 UTC, DomT4 requested changes

2016-09-27 03:51 UTC, DomT4 commented on Formula/passenger.rb
> +  if MacOS.version >= :sierra && (MacOS::Xcode.version.to_f >= 8.0 || MacOS::CLT.version.to_f >= 8.0)
Just `if MacOS.version >= :sierra`. We don't support any configuration on Sierra that doesn't involve using Xcode 8 and/or CLT 8.x.

2016-09-27 03:51 UTC, DomT4 commented on Formula/passenger.rb
> +    if MacOS.version >= :sierra && (MacOS::Xcode.version.to_f >= 8.0 || MacOS::CLT.version.to_f >= 8.0)
Same thing as above.

2016-09-27 03:51 UTC, DomT4 commented
> I found that I needed apr & apu for both Xcode & CLT builds

Any chance you can provide the failure log? Just curious more than anything.

2016-09-27 14:22 UTC, CamJN commented
Failure Logs:

[01.rake.cc.txt](https://github.com/Homebrew/homebrew-core/files/495773/01.rake.cc.txt)
[01.rake.txt](https://github.com/Homebrew/homebrew-core/files/495772/01.rake.txt)

2016-09-29 07:15 UTC, MikeMcQuaid approved these changes
Looks like @DomT4's changes addressed.

2016-09-29 07:24 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `passenger: fix build on Sierra.`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

2016-09-29 07:24 UTC, closed without merging

2016-09-29 21:02 UTC, DomT4 commented
This is proving a pain on Sierra. A lot of things hunt the Apr elements in alternative ways if they can't find or don't look for `apr-1-config` but `subversion` and now `passenger` panic without that config script. I'd love to understand what Apple thought valuable about killing the config script but retaining the other elements, but there we go.