libtorch 1.4.0
Homebrew/homebrew-core pull request #49060
Opened 2020-01-16 01:22 UTC by ankane

Created with `brew bump-formula-pr`.

2020-01-16 13:47 UTC, Moisan requested changes
Could you also upgrade the `PyYAML` resource to the latest version?

2020-01-16 18:10 UTC, ankane commented
Hey @Moisan, thanks for reviewing. Updated PyYAML.

2020-01-17 13:48 UTC, Moisan commented
Thank you @ankane !

2020-01-17 13:48 UTC, Moisan approved these changes

2020-01-17 13:49 UTC, closed without merging