libcouchbase3 3.0 (new formula)
Homebrew/homebrew-core pull request #49103
Opened 2020-01-17 01:33 UTC by avsej

This is a clone of libcouchbase.rb. Libcouchbase 3 represent new version of the library with backwards incompatible API.

We still going to maintain and release fixes for libcouchbase 2.x, this is why I don't make changes in `Formula/libcouchbase.rb`

2020-01-17 01:45 UTC, SMillerDev requested changes

2020-01-17 16:48 UTC, avsej commented on Formula/libcouchbase3.rb
> +  homepage "https://docs.couchbase.com/c-sdk/3.0/hello-world/start-using-sdk.html"
What is wrong with this home page? Why it is not normal?

2020-01-18 10:19 UTC, SMillerDev commented on Formula/libcouchbase3.rb
> +  homepage "https://docs.couchbase.com/c-sdk/3.0/hello-world/start-using-sdk.html"
This is a specific document. It's not a homepage.

2020-02-21 16:14 UTC, ingenthr commented on Formula/libcouchbase3.rb
> +  homepage "https://docs.couchbase.com/c-sdk/3.0/hello-world/start-using-sdk.html"
It's the homepage for this particular library.  We could also send them to the README on github, but the page pointed to here is the best intro for most developers.

2020-03-20 16:25 UTC, closed without merging