Update PR template to include commit message instructions
Homebrew/homebrew-core pull request #49192
Opened 2020-01-20 02:47 UTC by chenrui333

Propose to update the PR template to make the commit message instruction more accessible.

2020-01-20 05:01 UTC, EricFromCanada requested changes

2020-01-20 05:01 UTC, EricFromCanada commented on .github/PULL_REQUEST_TEMPLATE.md
> +The commit message should be `<formula>: short-description-for-the-change`
```suggestion
The commit message should be `<formula>: short-description-of-the-change`
```

2020-01-20 09:34 UTC, issyl0 commented on .github/PULL_REQUEST_TEMPLATE.md
> +# For bump the version of the formula (also highly recommend to use `brew bump-formula-pr <formula>` command)
Another suggestion:

```suggestion
# Using `brew bump-formula-pr` to bump a version of a formula is highly recommended as it does everything for you. If that command doesn't work or you choose to do the version bump manually, your commit message should look like:
```

2020-01-20 12:15 UTC, MikeMcQuaid commented
I like the intention here but it does make the PR template a _lot_ longer. I think this might be a better fit for a linked document e.g. `CONTRIBUTING.md`?

2020-01-20 15:13 UTC, chenrui333 commented
@MikeMcQuaid, not everyone likes to read the doc (myself included for some cases too :) ), so the intention is just to experiment to see if we can formalize the commit messages.

2020-01-20 15:22 UTC, chenrui333 commented
Thanks @EricFromCanada @issyl0 for the feedback, PR template updated.

2020-01-20 17:11 UTC, MikeMcQuaid requested changes
> @MikeMcQuaid, not everyone likes to read the doc (myself included for some cases too :) ), so the intention is just to experiment to see if we can formalize the commit messages.

I don't think making this document longer is likely to do that. This ends up deprioritising the existing checklist. What about a dedicated document just for commit message formats which you add to the checklist with a link?

2020-01-21 01:21 UTC, SMillerDev commented
> not everyone likes to read the doc

What makes you think they'll read this docs in that case?

2020-01-21 01:24 UTC, chenrui333 commented
I like the audit check idea! I don't quite like documentation in general though. 😄 

Yeah, the idea of doing the PR template update rather than another contributing doc is it would be the most immediate feedback.

This actually push me to think there must be some sort of `probot` to do this kind of check (while I am typing this comment).

2020-01-29 03:06 UTC, chenrui333 commented
I will work on the doc and audit ideas this weekend.

2020-02-11 12:35 UTC, MikeMcQuaid commented
Sorry, passing on this for now @chenrui333!

2020-02-11 12:35 UTC, closed without merging