openmesh version bump
Homebrew/homebrew-core pull request #4938
Opened 2016-09-18 11:14 UTC by autosquid

- [√] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [√] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [√] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

It reports the following problem which I really do not known how to remove.

```
  * python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/Cellar/open-mesh/6.2/lib/python2.7/site-packages/openmesh.so
```

I checked the cmake file: it finds python by cmake ---- will that be troublesome?

Hope someone could fix the problem based on my P.R.

-----

1. upgrade to version 6.2;
2. add python binding

2016-09-19 14:27 UTC, autosquid commented
anyone can help?

2016-09-20 07:54 UTC, MikeMcQuaid commented
CC @tdsmith for help. Also, is there docs for what to do on this error? If so, let me know so I can be more helpful with this stuff in future.

2016-09-20 07:56 UTC, tdsmith commented on Formula/open-mesh.rb
> +    system "python -c 'import openmesh;'"
`system "python", "-c", "import openmesh"` please

2016-09-20 07:56 UTC, tdsmith commented on Formula/open-mesh.rb
> +      end
Why give an option to turn the bindings off? Let's leave them enabled.

2016-09-20 07:57 UTC, tdsmith requested changes

2016-09-20 08:01 UTC, tdsmith commented
No, every solution is bespoke. :(

In general what needs to happen is:
- figure out where in the CMakelist something like PYTHON_LIBRARY is being added to LINK_LIBRARIES for the python binding target and make it stop
- add something like:

```cmake
if(APPLE)
  set_target_properties(whichever_target LINK_FLAGS "-undefined dynamic_lookup")
endif()
```

instead.

2016-09-20 08:11 UTC, MikeMcQuaid commented
@tdsmith Even that may be worth adding to some docs and linking from the audit warning? My CMake knowledge is enough that I may be able to help contributors beyond that.

2016-09-20 18:11 UTC, autosquid commented on Formula/open-mesh.rb
> +      end
maybe there are neat freaks who do not use the binding and want to keep their site-package dir clean.

2016-09-20 18:12 UTC, tdsmith commented on Formula/open-mesh.rb
> +      end
Nonetheless, let's leave it always enabled; thanks!

2016-09-20 18:18 UTC, tdsmith commented
I sent the attached patch to upstream to fix the Python linking problem; it applies against master but it's diverged a little from the 3.6 branch.

https://gist.github.com/a806cabfdbf4ff9557850512061629d3

2016-09-21 04:00 UTC, autosquid commented
@tdsmith  I known little about week dynamic linking, so my question may be a little off the point: does the week dynamic linking of python.dylib means the openmesh library when imported will use whatever is in the surrounding python environment (instead of what is pointed out in openmesh.so if non-week dynamic linking is used) ?

2016-09-21 04:04 UTC, tdsmith commented
> does the week dynamic linking of python.dylib means the openmesh library when imported will use whatever is in the surrounding python environment

Yes.

> (instead of what is pointed out in openmesh.so if non-week dynamic linking is used) ?

If they don't match, the interpreter will segfault.

2016-09-21 04:09 UTC, autosquid commented
@tdsmith  thanks for your answering!


Also, what if the linked library is just some symbolic links ? For example:

A is non-weekly linked to /usr/local/lib/B.dylib which is a symbolic link to /usr/local/Cellar/B/lib/B.1.dylib. Will A be affected if I later upgrade B (and its symbolic) to /usr/local/Cellar/B/lib/B.2.dylib?

By the way, where can I learn things like these?

2016-09-21 04:28 UTC, tdsmith commented
It depends on the install_name of /usr/local/Cellar/B/lib/B.1.dylib; dylibs "remember" their name and the linker uses the remembered name stored in the dylib (called an install_name) instead of the current filesystem location of the dylib it finds.

If the install_name is /usr/local/Cellar/B/lib/B.1.dylib, A will break when you upgrade B. If the install_name is /usr/local/Cellar/B/lib/B.dylib, A will not break when you upgrade B (assuming B.1 and B.2 are compatible).

Dunno where to learn these things except by banging your head on them for long enough, sorry :)

2016-11-10 16:37 UTC, MikeMcQuaid commented
Passing on this due to no response. We'll review another PR with comments/conflicts/CI failures addressed. Sorry and thanks anyway!

2016-11-10 16:37 UTC, closed without merging