add HEAD to distcc
Homebrew/homebrew-core pull request #4957
Opened 2016-09-18 16:25 UTC by yurikoles

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [-] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [-] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

fix style

2016-09-18 16:26 UTC, yurikoles commented
Please help me resolve issue that is also reported to upstream https://github.com/distcc/distcc/issues/197

2016-09-18 19:27 UTC, MikeMcQuaid commented on Formula/distcc.rb
> +  depends_on "autoconf" if build.head?
Add these all to a `head do` block.

2016-09-18 19:28 UTC, MikeMcQuaid commented on Formula/distcc.rb
> +    inreplace "Makefile.in", '--root="$$DESTDIR"', ""
Please keep this with the comment.

2016-09-18 19:28 UTC, MikeMcQuaid commented on Formula/distcc.rb
> +    args << "--without-libiberty" if build.head?
Was this option removed or does it not work in HEAD?

2016-09-18 19:28 UTC, MikeMcQuaid requested changes

2016-09-18 19:53 UTC, yurikoles commented on Formula/distcc.rb
> +    args << "--without-libiberty" if build.head?
This isn't working in HEAD, this library is not shipped by us in gcc and binutils, there is a number of bugs regarding this library. [Upstream recommends](https://gcc.gnu.org/onlinedocs/libiberty/Using.html) to ship it with project source code.

2016-10-06 08:00 UTC, bfontaine commented
@yurikoles Anything new here?

2016-10-15 10:59 UTC, MikeMcQuaid commented
Looks like https://github.com/distcc/distcc/issues/159 will 🚢 soon with the GitHub tarball for this version.

2016-11-10 16:42 UTC, MikeMcQuaid commented
Passing on this due to comments not being addressed. We'll review a new PR with comments addressed and CI passing. Sorry and thanks anyway!

2016-11-10 16:42 UTC, closed without merging