fix msktutil url; add test to msktutil.
Homebrew/homebrew-core pull request #4963
Opened 2016-09-18 19:50 UTC by yurikoles

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

2016-09-18 20:21 UTC, zmwangx commented on Formula/msktutil.rb
> +    system "#{sbin}/msktutil", "--version"
Usually this would be something like

```ruby
assert_match version.to_s, shell_output("#{sbin}/msktutil --version")
```

2016-09-18 20:21 UTC, zmwangx requested changes

2016-09-18 20:38 UTC, yurikoles commented on Formula/msktutil.rb
> +    system "#{sbin}/msktutil", "--version"
done

2016-09-18 21:29 UTC, yurikoles commented
I had added devel.

2016-09-18 22:04 UTC, zmwangx commented on Formula/msktutil.rb
> +  stable do
No need for `stable do` here, keep `url` and `sha256` where they used to be.

2016-09-18 22:05 UTC, zmwangx requested changes

2016-09-19 10:02 UTC, yurikoles commented on Formula/msktutil.rb
> +  stable do
done

2016-09-19 10:03 UTC, yurikoles commented
Up & rebase

2016-09-19 19:46 UTC, closed without merging

2016-09-19 19:47 UTC, zmwangx commented
I fixed a few lingering style issues and merged as 12cf50b. Thank you for your contribution to Homebrew!

2016-09-19 19:47 UTC, yurikoles commented
@zmwangx thanks!