git-town 2.0.0
Homebrew/homebrew-core pull request #4965
Opened 2016-09-18 22:09 UTC by charlierudolph

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

We renamed our commands to now all have a `town-` prefix to prevent conflicts

2016-09-18 23:17 UTC, zmwangx commented on Formula/git-town.rb
>    def caveats; <<-EOS.undent
Sorry, `caveats` are reserved for brew-specific information and do not replace your instruction manual. I think the entire caveats section should be removed.

2016-09-18 23:17 UTC, zmwangx requested changes

2016-09-18 23:50 UTC, charlierudolph commented
@zmwangx caveats section removed

2016-09-19 06:55 UTC, zmwangx approved these changes

2016-09-19 06:55 UTC, merged

2016-09-19 06:55 UTC, zmwangx commented
Merged as 933c055. Thank you for your contribution to Homebrew!