zig: use installed llvm for build
Homebrew/homebrew-core pull request #50405
Opened 2020-02-18 18:50 UTC by SeekingMeaning

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes libc not found error when building head

2020-02-19 06:47 UTC, SMillerDev commented
Did you report this issue upstream yet? Because it successfully builds without this on the last release so they have to be informed they broke something. Since its only a fix for HEAD, please encapsulate it in `if build.head?`

2020-02-21 04:23 UTC, heibor commented
I hope the compiling operations could be easy.

2020-02-21 17:02 UTC, zbeekman commented on Formula/zig.rb
> +    ENV["LD"] = Formula["llvm"].opt_bin/"ld.lld"
@SMillerDev Don't we usually set compilers with `fails_with [:clang, :gcc]` to force compiling with llvm's clang?

Also, it seems weird that there was an llvm dependency but it used to be able to be built with Apple native clang.

2020-02-21 20:30 UTC, zbeekman commented on Formula/zig.rb
> +    ENV["LD"] = Formula["llvm"].opt_bin/"ld.lld"
Ignore this comment.

2020-02-21 20:49 UTC, zbeekman requested changes
This strikes me as an upstream bug that should be reported. I don't see why this formula *needs* to build with llvm. Unless upstream says that this is the only compiler they support on macOS, then I don't think this makes any sense.

2020-02-22 14:38 UTC, SeekingMeaning commented
The error seems to be caused by the command `cc -E -Wp,-v -xc /dev/null` (see ziglang/zig#4521). Any idea why that is? Is `/usr/local/Homebrew/Library/Homebrew/shims/super/cc` not able to handle those flags?

2020-02-22 17:08 UTC, zbeekman commented
> The error seems to be caused by the command `cc -E -Wp,-v -xc /dev/null` (see [ziglang/zig#4521](https://github.com/ziglang/zig/issues/4521)). Any idea why that is? Is `/usr/local/Homebrew/Library/Homebrew/shims/super/cc` not able to handle those flags?

I commented on [ziglang/zig#4521](https://github.com/ziglang/zig/issues/4521). The error is in the upstream build system AFAICT. Those flags were requested just to diagnose why libc couldn't be found. I provided a more accurate looking output of that command (as well as some additional info) to the zig developers, as it would look/behave during the zig build. AFAICT, this is an upstream issue that they need to fix. It's possible that the dependency on `llvm` was added errantly (or removed upstream). Problems like this is why we try (but fail) not to accept pre-release or beta software into Homebrew.

2020-02-22 17:10 UTC, zbeekman commented
@SeekingMeaning can you try editing the formula to match the original formula but with the LLVM dependency removed, and then build with `brew install --HEAD --fetch-HEAD --verbose`? Maybe it should never have been added, or maybe upstream dropped the dependency on llvm?

2020-02-22 17:11 UTC, andrewrk commented
Hi, upstream here. This is a [confirmed upstream bug](https://github.com/ziglang/zig/issues/4521#issuecomment-589925358). I don't think anything needs to change on Homebrew's side. The LLVM dependency is correct.

2020-02-22 17:33 UTC, closed without merging

2020-02-22 20:01 UTC, andrewrk commented
OK there is more information available now: https://github.com/ziglang/zig/issues/4521#issuecomment-589989590

In summary, 

```
Zig attempted to find the path to native system libc headers by executing this command:
clang -E -Wp,-v -xc /dev/null
Output:
==========
clang: The build tool has reset ENV; --env=std required.

==========
Unable to link against libc: Unable to find libc installation: system C compiler exited    with failure code
```

I cannot reproduce this with `brew install --HEAD --fetch-HEAD --interactive zig`. When I do this, the entire build process completes successfully.

Is there some reason upstream cannot expect to run `$CC -E -Wp,-v -xc /dev/null` and get the expected output? It would looks like this:

```
clang -cc1 version 11.0.0 (clang-1100.0.33.17) default target x86_64-apple-darwin18.7.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/opt/llvm/include
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libxml2
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks (framework directory)
End of search list.
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 362 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/dev/null" 2
```

2020-02-22 20:05 UTC, andrewrk commented
And of course just as I send this comment, I realized there is a recent regression in environment variables not being set for a child process in certain occasions. So once again I believe this is an upstream regression.

Apologies for the noise.

2020-02-22 20:07 UTC, SMillerDev commented
I'd much rather read a bunch of noise from upstream with solutions than just having users guessing at possible fixes

2020-02-23 06:51 UTC, andrewrk commented
This was fixed upstream in https://github.com/ziglang/zig/commit/d1243bf272b591a8deba5abedb56050edf3c3d6a. No changes to the homebrew package are necessary. Thank you @SMillerDev and @zbeekman for your time.

More details for the curious: Zig has been slowly self-hosting the compiler, little bits and pieces at a time. Every once in a while there is a regression. In this case, it was the native libc detection code. Fixed now.