plplot: fix build with CMake 3.6
Homebrew/homebrew-core pull request #5072
Opened 2016-09-21 16:14 UTC by tschoonj

Patch PR is in Homebrew/formula-patches#56

I will update the url to the patch as soon as it is accepted.

2016-09-24 22:24 UTC, zmwangx commented on Formula/plplot.rb
> +  patch do
Need a comment with links to upstream patches (the SF commits should do) and brief explanation of what the patch does.

2016-09-24 22:24 UTC, zmwangx requested changes

2016-09-25 04:22 UTC, DomT4 commented
Patch was merged into patches as well, so can tweak the link safely.

2016-09-25 08:11 UTC, tschoonj commented on Formula/plplot.rb
> +  patch do
Done!

2016-09-26 07:19 UTC, tschoonj commented
As soon as this one is merged in, the formula should build properly again. 

I have asked upstream to make a new release with these patches but they seem to want to hold out until they have finalized some new features they want to include as well.

2016-09-26 07:23 UTC, alexant123 commented
How I can applying this comment manual and rebuild make instrument?

понедельник, 26 сентября 2016 г. пользователь Tom Schoonjans написал:

> As soon as this one is merged in, the formula should build properly again.
>
> I have asked upstream to make a new release with these patches but they
> seem to want to hold out until they have finalized some new features they
> want to include as well.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-core/pull/5072#issuecomment-249496629>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATpklhXB_r-SY0Ujps5YnZsU-UfIEkG-ks5qt3HugaJpZM4KC_4R>
> .
>

2016-09-26 08:09 UTC, tschoonj commented
@ilovezfs @zmwangx Could you merge this one in please? Thanks!

2016-09-26 08:24 UTC, ilovezfs commented
The job is gone so this will have to be re-queued.

2016-09-26 08:25 UTC, ilovezfs commented
@BrewTestBot test this please

2016-09-27 00:10 UTC, closed without merging

2016-09-27 00:10 UTC, DomT4 commented
Merged in https://github.com/Homebrew/homebrew-core/commit/566054cbee38362cf074cc10fffe7b12c7a38c6a. Thank you for another contribution to Homebrew Tom! 🙇