gdub: optional gradle dependency
Homebrew/homebrew-core pull request #5073
Opened 2016-09-21 16:26 UTC by gschrader

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

Typically with the gw command you're going to want the gradle wrapper to download gradle for you. I would also hazard a guess when you want to start a new project and need a global gradle install most Java developers will be using sdkman.

Thanks!

2016-09-21 17:50 UTC, gschrader commented
Of course the test passed locally for me since I had another global install of gradle 😢. I'll have to see if it can use the --with-gradle option or change the test.

2016-09-22 19:53 UTC, zmwangx commented
@emanuelez for thoughts.

2016-09-22 23:00 UTC, emanuelez approved these changes
Looks reasonable to me

2016-09-22 23:02 UTC, zmwangx commented on Formula/gdub.rb
> +  depends_on "gradle" => :optional
Just drop this dep entirely then. It's at most a runtime dep (should be `=> :run` to begin with), and people can always install it separately if they want to.

2016-09-22 23:08 UTC, zmwangx commented on Formula/gdub.rb
>    test do
Change the test to

```ruby
    assert_match "No gradlew set up for this project", pipe_output("#{bin}/gw 2>&1")
```

We don't really care that much about making sure tests run on people's machines. Working on CI is enough.

2016-09-22 23:08 UTC, zmwangx requested changes

2016-09-23 17:39 UTC, gschrader commented
I'm not sure why the build has failed, I don't think it's related to my change.

2016-09-24 22:25 UTC, zmwangx approved these changes

2016-09-24 22:25 UTC, zmwangx commented
No worries, CI failures are not your fault.

2016-09-24 22:26 UTC, merged

2016-09-24 22:26 UTC, zmwangx commented
Merged as ba321f0. Thank you for your contribution to Homebrew!