add sonar-scanner formula, replacement for sonar-runner
Homebrew/homebrew-core pull request #5111
Opened 2016-09-22 12:25 UTC by sv99

sonar-runner deprecated

WARN: sonar-runner script is deprecated. Please use sonar-scanner instead.

2016-09-26 23:23 UTC, DomT4 requested changes

2016-09-26 23:23 UTC, DomT4 commented on Formula/sonar-scanner.rb
> +  homepage "http://docs.sonarqube.org/display/SONAR/Analyzing+with+SonarQube+Scanner"
Looks like this redirects to `http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner` so we may as well use that.

2016-09-26 23:23 UTC, DomT4 commented on Formula/sonar-scanner.rb
> +      If this is your first install, you should adjust the default configuration:
Use a two space indent rather than four, thanks!

2016-09-26 23:23 UTC, DomT4 commented on Formula/sonar-scanner.rb
> +        #{libexec}/conf/sonar-scanner.properties
`opt_libexec` produces a slightly nicer output.

2016-09-26 23:23 UTC, DomT4 commented on Formula/sonar-scanner.rb
> +        SONAR_SCANNER_HOME=#{libexec}
We should env script this ideally. Something like [this](https://github.com/Homebrew/homebrew-core/blob/4fdd781d53d3fccb35a3c2be286b9849ff807adc/Formula/chapel.rb#L31).

2016-09-26 23:23 UTC, DomT4 commented on Formula/sonar-scanner.rb
> +    system "#{bin}/sonar-scanner", "-h"
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2016-09-28 05:50 UTC, sv99 commented on Formula/sonar-scanner.rb
> +    system "#{bin}/sonar-scanner", "-h"
I simply rewrite existing formula. sonar-runner - deprecated by sonarcube.

2016-09-28 06:37 UTC, sv99 commented
updated

2016-09-28 06:45 UTC, sv99 commented on Formula/sonar-scanner.rb
> +        #{libexec}/conf/sonar-scanner.properties
--version show full path to the configuration file:
```
sonar-scanner --version
...
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/2.8/libexec/conf/sonar-scanner.properties
...
```

2016-10-02 21:14 UTC, dunn commented on Formula/sonar-scanner.rb
> +    ENV["SONAR_SCANNER_HOME"] = libexec
This shouldn't be necessary, since the script in `bin` is an env wrapper.

2016-10-02 21:15 UTC, dunn commented on Formula/sonar-scanner.rb
> +    ENV["SONAR_SCANNER_HOME"] = libexec
You've already installed, so is this necessary?

2016-10-02 21:15 UTC, dunn commented on Formula/sonar-scanner.rb
> +      #{libexec}/conf/sonar-scanner.properties
Is this Homebrew-specific information? If not, please remove it!

2016-10-03 08:34 UTC, sv99 commented on Formula/sonar-scanner.rb
> +    ENV["SONAR_SCANNER_HOME"] = libexec
SONAR_SCANNER_HOME - without this variable - runtime error

2016-10-03 08:35 UTC, sv99 commented on Formula/sonar-scanner.rb
> +      #{libexec}/conf/sonar-scanner.properties
This is homebrew specific path of the global configuration file sonar-scanner.properties

2016-10-03 08:38 UTC, MikeMcQuaid commented on Formula/sonar-scanner.rb
> +    ENV["SONAR_SCANNER_HOME"] = libexec
If it's a runtime error then this won't be set at runtime.

2016-10-03 08:38 UTC, MikeMcQuaid commented on Formula/sonar-scanner.rb
> +      #{libexec}/conf/sonar-scanner.properties
Just remove the caveats then and install them into `etc.install` like other configuration files.

2016-10-03 09:06 UTC, sv99 commented on Formula/sonar-scanner.rb
> +      #{libexec}/conf/sonar-scanner.properties
sonar-scanner --version show: 
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/2.8/libexec/conf/sonar-scanner.properties

?? not to the etc.install ??

2016-10-03 09:07 UTC, sv99 commented
updated

2016-10-03 09:07 UTC, MikeMcQuaid commented on Formula/sonar-scanner.rb
> +      #{libexec}/conf/sonar-scanner.properties
Ideally we'd convince it to put the file elsewhere. If not we can `etc.install` and use a symlink so both locations still work.

2016-10-03 09:25 UTC, sv99 commented on Formula/sonar-scanner.rb
> +      #{libexec}/conf/sonar-scanner.properties
this path used in the script from SONAR_SCANNER_HOME. How can i add link -  etc.install copy script to the /usr/local/etc?

2016-10-03 11:02 UTC, dunn commented on Formula/sonar-scanner.rb
> +    ENV["SONAR_SCANNER_HOME"] = libexec
The env wrapper script should take care of that, but it's not being run in the `def install` block, so it shouldn't be necessary there.

2016-10-03 11:04 UTC, dunn commented on Formula/sonar-scanner.rb
> +      #{libexec}/conf/sonar-scanner.properties
```ruby
etc.install "conf/sonar-scanner.properties"
ln_s etc/"conf/sonar-scanner.properties", libexec/"conf/sonar-scanner.properties"

2016-10-03 15:46 UTC, MikeMcQuaid commented on Formula/sonar-scanner.rb
> +    # sonar-sanner uses this ENV to work out where to install.
Can remove this variable.

2016-10-03 15:46 UTC, MikeMcQuaid commented on Formula/sonar-scanner.rb
> +    # Remove windows files
Can remove this comment.

2016-10-03 15:46 UTC, MikeMcQuaid commented on Formula/sonar-scanner.rb
> +    # sonar-sanner uses this ENV to work out where to install.
Comment, sorry, not variable.

2016-10-03 16:02 UTC, sv99 commented on Formula/sonar-scanner.rb
> +    # Remove windows files
updated

2016-10-03 19:01 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `sonar-scanner 2.8 (new formula)`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

2016-10-03 19:01 UTC, closed without merging