sonarqube build-wrapper 4.1
Homebrew/homebrew-core pull request #5115
Opened 2016-09-22 13:44 UTC by sv99

build-wrapper for sonarqube C++ plugin

2016-09-26 23:29 UTC, DomT4 requested changes

2016-09-26 23:29 UTC, DomT4 commented on Formula/sonar-build-wrapper.rb
> +    mv bin/"build-wrapper-macosx-x86", bin/"build-wrapper"
Just:
```ruby
bin.install "build-wrapper-macosx-x86" => "build-wrapper"
```
That's a pretty generic name though. Maybe `"sonarqube-build-wrapper"` to match the formula or something?

2016-09-26 23:29 UTC, DomT4 commented on Formula/sonar-build-wrapper.rb
> +    assert_match /version 4\.1/, shell_output("#{bin}/build-wrapper -h", 10)
```ruby
assert_match version.to_s, shell_output("#{bin}/build-wrapper -h", 10)
```

2016-09-28 05:45 UTC, sv99 commented on Formula/sonar-build-wrapper.rb
> +    mv bin/"build-wrapper-macosx-x86", bin/"build-wrapper"
This is name from sonarqube distro.

2016-09-28 06:04 UTC, sv99 commented
updated
May be renaming to the Formula/sonar-build-wrapper.rb

script name used in the sonarcube documentation

This formula with sonar-scanner.rb allow checking project without installing sonar server.
I check my C++ github project, local C++ sonar server need C++ plugin with license. Open source projects on the github sonarcube checked for free.

2016-10-02 21:16 UTC, dunn commented on Formula/sonar-build-wrapper.rb
> +    mv bin/"build-wrapper-macosx-x86", bin/"build-wrapper"
It's still too generic for us; we want to avoid naming conflicts with other packages.

2016-10-03 08:00 UTC, sv99 commented
updated
leave original script name  "build-wrapper-macosx-x86"

2016-10-03 08:40 UTC, MikeMcQuaid requested changes

2016-10-03 08:40 UTC, MikeMcQuaid commented on Formula/sonar-build-wrapper.rb
> +    lib.install "libinterceptor.dylib"
We need to build binaries and libraries from source.

2016-10-03 09:17 UTC, sv99 commented on Formula/sonar-build-wrapper.rb
> +    lib.install "libinterceptor.dylib"
this script build-wrapper for C/C++ sonarqube plugin - must be downloaded from installed sonarcube server. C/C++ plugin not free, for local server need license.
For open source projects on the ginhub sonarqube.org tested for free. This formula not needed local installed sonarcube server!!

2016-10-03 09:21 UTC, MikeMcQuaid commented on Formula/sonar-build-wrapper.rb
> +    lib.install "libinterceptor.dylib"
So this is not open-source? If so, we cannot include it in Homebrew.

2016-10-03 09:27 UTC, sv99 commented on Formula/sonar-build-wrapper.rb
> +    lib.install "libinterceptor.dylib"
sonar formula??

2016-10-03 09:40 UTC, MikeMcQuaid commented on Formula/sonar-build-wrapper.rb
> +    lib.install "libinterceptor.dylib"
https://github.com/SonarSource/sonarqube ?

2016-10-03 10:05 UTC, sv99 commented on Formula/sonar-build-wrapper.rb
> +    lib.install "libinterceptor.dylib"
this is core open source version, many languages supported by plugins enabled and supported only in the enterprise version.

2016-10-03 10:09 UTC, sv99 commented on Formula/sonar-build-wrapper.rb
> +    lib.install "libinterceptor.dylib"
formula sonar-runner (i send PR for renaming to the sonar-scanner) - downloaded (not compiled)

2016-10-03 11:00 UTC, dunn commented on Formula/sonar-build-wrapper.rb
> +    lib.install "libinterceptor.dylib"
Mike means that we'll need it compiled; something like 
```ruby
ENV.java_cache
system "mvn", "clean", "install"
```
in the `def install` block.

2016-10-03 12:25 UTC, MikeMcQuaid commented on Formula/sonar-build-wrapper.rb
> +    lib.install "libinterceptor.dylib"
Can you link to the relevant repository?

2016-10-03 12:25 UTC, MikeMcQuaid commented on Formula/sonar-build-wrapper.rb
> +    lib.install "libinterceptor.dylib"
(and what @dunn said)

2016-10-03 12:51 UTC, sv99 commented on Formula/sonar-build-wrapper.rb
> +    lib.install "libinterceptor.dylib"
this wrapper not open source, but his may be used for checking open source project on the github.

Documentation on the sonarqube http://docs.sonarqube.org/pages/viewpage.action?pageId=3080359 - download from working server with installed C/C++ pluging and run. Without this formula need manual download and manual install wrapper.

2016-10-03 12:54 UTC, MikeMcQuaid commented
If the wrapper is not open-source we can't include it, sorry. Homebrew Cask may be willing to do so (but may not).

2016-10-03 12:54 UTC, closed without merging