Elasticsearch 5.0.0-beta1
Homebrew/homebrew-core pull request #5121
Opened 2016-09-22 17:17 UTC by jasontedor

This pull request upgrades the devel release for Elasticsearch from version 5.0.0-alpha5 to 5.0.0-beta1, the [latest pre-release version of the Elasticsearch 5.x series](https://www.elastic.co/blog/elasticsearch-5-0-0-beta1-released) as of 2016-09-21.

2016-09-22 23:58 UTC, zmwangx commented on Formula/elasticsearch.rb
> -    depends_on java: "1.8"
Revert all these syntax changes.

2016-09-22 23:58 UTC, zmwangx commented on Formula/elasticsearch.rb
> -    depends_on java: "1.8"
Revert all these syntax changes.

2016-09-22 23:59 UTC, zmwangx commented on Formula/elasticsearch.rb
> +    sha256 "4ff6680b2d053c74835db77dcb03e02340555cd70cae8bb73d3b1f94ddf0147d"
Add `version "5.0.0-beta1"`.

2016-09-22 23:59 UTC, zmwangx requested changes

2016-09-23 00:24 UTC, jasontedor commented on Formula/elasticsearch.rb
> +    sha256 "4ff6680b2d053c74835db77dcb03e02340555cd70cae8bb73d3b1f94ddf0147d"
Why? That fails the audit since it can be extracted from the `url`.

2016-09-23 00:27 UTC, jasontedor commented on Formula/elasticsearch.rb
> -    depends_on java: "1.8"
I pushed be29182e8cc96fcdbe43cadee50241972829d973.

2016-09-23 08:03 UTC, zmwangx commented on Formula/elasticsearch.rb
> +    sha256 "4ff6680b2d053c74835db77dcb03e02340555cd70cae8bb73d3b1f94ddf0147d"
Okay, not sure why `5.0.0-alpha5` can't be extracted but beta can.

2016-09-23 08:03 UTC, zmwangx approved these changes

2016-09-24 22:02 UTC, merged

2016-09-24 22:03 UTC, zmwangx commented
Merged as 591ee94. Thank you for your contribution to Homebrew! For future reference, our preferred format of commit subject is `foo 1.2.3-beta1 (devel)`.

2016-09-24 22:55 UTC, jasontedor commented
Thank you @zmwangx! :smile: