python: fix compiling python --universal on 10.11 with Xcode 8
Homebrew/homebrew-core pull request #5127
Opened 2016-09-22 20:52 UTC by JCount

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

The fix in https://github.com/Homebrew/homebrew-core/pull/5070 is also needed when compiling `python --universal` on 10.11 with Xcode 8.

2016-09-22 21:38 UTC, zmwangx commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
Too long a line.

2016-09-22 21:38 UTC, zmwangx requested changes

2016-09-22 21:44 UTC, JCount commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
I was wondering, but RuboCop wasn't upset. Will fix.

2016-09-22 21:49 UTC, zmwangx commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
Not everything is covered by RuboCop. We strive to stay within 80 columns (and I'm not the one that police this sort of thing the hardest), but in this case I think it's reasonable to just put build.universal? on the second line (I'm happy with 100 in a case like this, and others who police harder break the rule themselves too — see erlang.rb for instance — so it should be fine).

2016-09-22 22:01 UTC, DomT4 commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
You can probably just drop the `MacOS.version >= :sierra` part here, since that'll now be covered by the latter check.

2016-09-22 22:01 UTC, DomT4 requested changes

2016-09-22 22:03 UTC, zmwangx commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
@DomT4 Why does MacOS.version >= :sierra imply MacOS::Xcode.installed??

2016-09-22 22:05 UTC, JCount commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
Ok, thanks DomT4, that had occurred to me, but I then forgot when I was checking something else. Trying to use any other version of Xcode on Sierra is completely unsupported by `homebrew` after all.

2016-09-22 22:07 UTC, DomT4 commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
@zmwangx Oh, wait, you're right, I'm an idiot. Sorry, I thought this was strictly an Xcode problem for some reason.

2016-09-22 22:08 UTC, DomT4 commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
You could maybe do:
```ruby
if DevelopmentTools.clang_version => "8.0" && build.universal?
```
though.

2016-09-22 22:09 UTC, DomT4 commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
Or `DevelopmentTools.clang_build_version => "800"` to match the format we use elsewhere.

2016-09-22 22:12 UTC, JCount commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
needs to be `>=` though. :stuck_out_tongue_closed_eyes:

2016-09-22 22:12 UTC, DomT4 commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
Ooft. Yup. I'm trying to do about 5 things at once at the moment & apparently my brain can't cope 😆

2016-09-22 22:19 UTC, zmwangx commented on Formula/python.rb
> +  if (MacOS.version >= :sierra || MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0") && build.universal?
I guess you're quad core and need a better process scheduler.

2016-09-23 03:36 UTC, ilovezfs commented on Formula/python.rb
> +  if DevelopmentTools.clang_build_version >= 800 && build.universal?
You should reverse the order of these two conditions since the second one is less common than the first.

2016-09-23 03:48 UTC, JCount commented on Formula/python.rb
> +  if DevelopmentTools.clang_build_version >= 800 && build.universal?
Ahh, the optimization interpreted languages.

2016-09-24 21:06 UTC, merged

2016-09-24 21:06 UTC, zmwangx commented
Merged as 8ac27ee. Thank you for another contribution to Homebrew!