libsquish 1.14
Homebrew/homebrew-core pull request #5202
Opened 2016-09-25 12:03 UTC by dholm

2016-09-26 23:13 UTC, DomT4 commented on Formula/libsquish.rb
> +    (testpath/"test.cc").write <<-EOF.undent
Minor nit, but we use `EOS.undent` and `EOS` mostly elsewhere so would be nice to be consistent here.

2016-09-26 23:13 UTC, DomT4 commented on Formula/libsquish.rb
> +    #include <stdio.h>
Can you indent this by two spaces? Thanks!

2016-09-26 23:13 UTC, DomT4 commented on Formula/libsquish.rb
> +    system ENV.cxx, "-o", "test", "test.cc", "#{lib}/libsquish.a"
`lib/"libsquish.a"` is a little more compact.

2016-09-26 23:14 UTC, DomT4 commented on Formula/libsquish.rb
> +    assert_equal "153600", `./test`
```ruby
assert_equal "153600", shell_output("./test")
```

2016-09-26 23:14 UTC, DomT4 requested changes

2016-10-06 08:03 UTC, bfontaine commented
@dholm Ping on @DomT4’s comments above?

2016-10-12 19:30 UTC, dholm commented
@bfontaine Done!

2016-10-13 07:36 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-10-13 07:36 UTC, closed without merging