ipython: use python@3.8 and bump revision
Homebrew/homebrew-core pull request #52525
Opened 2020-04-03 23:14 UTC by drrlvn

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Progress #47274 by updating ipython.

2020-04-04 15:33 UTC, SMillerDev commented
I think the install block should also be changed to use python3.8 instead of just python3.

2020-04-04 15:50 UTC, drrlvn commented
> I think the install block should also be changed to use python3.8 instead of just python3.

Oops, you're right. I think (hope) it's fixed now. Sorry, this is my first contribution to brew.

2020-04-04 15:52 UTC, iMichka requested changes

2020-04-04 15:52 UTC, iMichka commented on Formula/ipython.rb
> +    xy = Language::Python.major_minor_version "python3.8"
xy = Language::Python.major_minor_version Formula["python@3.8"].opt_bin/"python3"

2020-04-04 15:52 UTC, iMichka commented on Formula/ipython.rb
> +        system "python3.8", *Language::Python.setup_install_args(libexec/"vendor")
system Formula["python@3.8"].opt_bin/"python3"

2020-04-04 15:52 UTC, iMichka commented on Formula/ipython.rb
> +    system "python3.8", *Language::Python.setup_install_args(libexec)
sytem Formula["python@3.8"].opt_bin/"python3"

2020-04-04 15:52 UTC, iMichka commented on Formula/ipython.rb
> +      system "python3.8", *Language::Python.setup_install_args(libexec/"vendor")
system Formula["python@3.8"].opt_bin/"python3"

2020-04-04 15:59 UTC, drrlvn commented
@iMichka Thanks! I pushed a commit with your suggested changes.

2020-04-16 17:14 UTC, bayandin commented
Superseded by https://github.com/Homebrew/homebrew-core/pull/52781

2020-04-16 17:14 UTC, closed without merging