hostess 0.2.1 (new formula)
Homebrew/homebrew-core pull request #5257
Opened 2016-09-26 15:57 UTC by rogeriopradoj

2016-09-26 22:57 UTC, DomT4 commented on Formula/hostess.rb
> +    (buildpath + "src/github.com/cbednarski/hostess").install Dir[buildpath/"*"]
```ruby
ENV["GOPATH"] = buildpath
dir = buildpath/"src/github.com/cbednarski/hostess"
dir.install buildpath.children

cd dir do
  system "go", "install"
end
bin.install "bin/hostess"
```

2016-09-26 22:58 UTC, DomT4 requested changes

2016-09-27 01:28 UTC, rogeriopradoj commented on Formula/hostess.rb
> +    (buildpath + "src/github.com/cbednarski/hostess").install Dir[buildpath/"*"]
Hi, @DomT4 and @zmwangx , `cd dir do` doesn't work. Here's the change that is closer to your request and works fine:

```
    ENV["GOPATH"] = buildpath
    dir = buildpath/"src/github.com/cbednarski/hostess"
    dir.install buildpath.children
    
    cd dir/"cmd/hostess" do
      system "go", "install"
    end
    bin.install "bin/hostess"
```

Should I send a new commit, or amend and force a push to this same branch/pull request?

2016-09-27 03:10 UTC, rogeriopradoj commented on Formula/hostess.rb
> +    (buildpath + "src/github.com/cbednarski/hostess").install Dir[buildpath/"*"]
New commit: 3731b53.

2016-10-01 17:34 UTC, MikeMcQuaid commented
@DomT4 👍 ?

2016-10-01 18:09 UTC, DomT4 approved these changes

2016-10-01 18:53 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-10-01 18:53 UTC, closed without merging

2016-10-02 00:18 UTC, rogeriopradoj commented
@MikeMcQuaid My pleasure!

I'm very involved with community here in São Paulo, Brazil, and I'm a big advocate of contributing with open source projects in the user groups that I join and help to organize as well (as @phpsp and @vagrantsp). Thank you for maintaining Homebrew and make your lives easier!

2016-10-02 07:17 UTC, MikeMcQuaid commented
@rogeriopradoj Thanks for the kind words!