kompose 0.1.0
Homebrew/homebrew-core pull request #5276
Opened 2016-09-27 05:36 UTC by blackstar257

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

2016-09-27 17:41 UTC, blackstar257 commented
Im not sure why the build failed. the bot doesn't show any information on the jenkins page

2016-09-28 08:16 UTC, MikeMcQuaid requested changes

2016-09-28 08:16 UTC, MikeMcQuaid commented on Formula/kompose.rb
> +class Compose2kube < Formula
The class and filename are not in sync: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8340/version=el_capitan/console

2016-09-28 08:16 UTC, MikeMcQuaid commented
> Have you built your formula locally prior to submission with brew install <formula> (where <formula> is the name of the formula you're submitting)?

This definitely will not have worked locally.

2016-10-05 16:04 UTC, blackstar257 commented on Formula/kompose.rb
> +class Compose2kube < Formula
Apologies for wasting your time.

2016-10-05 16:10 UTC, blackstar257 commented
> Have you built your formula locally prior to submission with brew install (where is the name of the formula you're submitting)?
> This definitely will not have worked locally.

Accidentally committed the wrong file the first time around. It did work fine with the version that was living in 
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kompose.rb

2016-10-05 16:12 UTC, blackstar257 commented
⇒  brew info kompose   
kompose: stable 64
Tool to move from `docker-compose` to Kubernetes
https://github.com/skippbox/kompose
/usr/local/Cellar/kompose/64 (3 files, 34.5M) *
  Built from source on 2016-10-05 at 09:11:27
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kompose.rb
⇒  kompose --version
kompose version 0.1.0 (8227684)

2016-10-07 03:17 UTC, blackstar257 commented on Formula/kompose.rb
> +class Compose2kube < Formula
I have since updated it.

2016-10-07 08:52 UTC, bfontaine submitted a review, later dismissed

2016-10-07 08:52 UTC, bfontaine commented on Formula/kompose.rb
> +  url "https://github.com/skippbox/kompose/releases/download/v0.1.0/kompose_darwin-amd64.tar.gz"
We need to build from source here.

2016-10-07 08:52 UTC, bfontaine commented on Formula/kompose.rb
> +    system "#{bin}/kompose", "--version"
Can’t we write a test that does something more substantial than e.g. `--help` or `--version`?

2016-10-19 01:38 UTC, dunn commented
ping re: the above comments 🔔

2016-10-21 19:26 UTC, blackstar257 commented
I should be able to get to this, this weekend.

2016-10-24 19:19 UTC, blackstar257 commented
Ill reopen if i get time to finish this.

2017-02-09 16:52 UTC, idcrook commented
Is there something I can help with?

`brew search kompose`

```
No formula found for "kompose".
==> Searching pull requests...
Closed pull requests:
kompose 0.1.0 (new formula) (https://github.com/Homebrew/homebrew-core/pull/5276)
```

`brew cask search kompose`

    No Cask found for "kompose".

2017-02-11 05:07 UTC, blackstar257 commented
Attempted again.

2017-02-12 04:19 UTC, blackstar257 commented
@MikeMcQuaid 
@bfontaine 

Anything that you would like changed?

2017-02-12 14:32 UTC, MikeMcQuaid approved these changes

2017-02-12 14:36 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `kompose 0.2.0 (new formula)`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

2017-02-12 14:37 UTC, closed without merging