Pyinvoke
Homebrew/homebrew-core pull request #5279
Opened 2016-09-27 07:05 UTC by mdaniel

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)? (well, yes, modulo issue 5249)

-----
This formula started life at version 0.12.2 because that was the specific version required to build another piece of software. However, 0.12 is not the latest version; that is 0.13.0 and is the one at the head of this PR. But I thought it would be useful to leave 0.12.2 in the history in case someone also wishes to build using the older version of pyinvoke

As you might suspect, I purposefully did not call the formula "invoke", however, I had mixed feelings about leaving their `inv` and `invoke` on the `$PATH`, so if you have guidance around that I'd welcome it.

2016-10-01 17:41 UTC, MikeMcQuaid commented on Formula/pyinvoke.rb
> +    virtualenv_install_with_resources
You're not using any `resource`s here? Does this have an external dependencies? CC @ilovezfs @tdsmith to check I haven't misunderstood this.

2016-10-01 22:46 UTC, mdaniel commented on Formula/pyinvoke.rb
> +    virtualenv_install_with_resources
Correct, but compare that one line (which does everything one would wish for a `setup.py` based installation) versus:

```ruby
  def install
    ENV.prepend_create_path "PYTHONPATH", "#{libexec}/lib/python2.7/site-packages"

    system "python", "setup.py", "install", "--prefix=#{libexec}"
    bin.install Dir[libexec/"bin/*"]
    bin.env_script_all_files(libexec+"bin", :PYTHONPATH => ENV["PYTHONPATH"])
  end
```

It's not me being lazy; I can copy-and-paste with the best of them, but I think it's a vast legibility improvement. I was unable to find anything in [the Formula Cookbook](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#specifying-gems-python-modules-go-projects-etc-as-dependencies) that implied one should favor the more verbose approach, so I didn't.

2016-10-02 08:43 UTC, MikeMcQuaid commented on Formula/pyinvoke.rb
> +    virtualenv_install_with_resources
Yeh, not really your issue here just interested what @tdsmith thinks re: naming etc.

2016-10-02 17:41 UTC, tdsmith commented
It looks okay to me. It's installing all zero of the resources :)

On Sun, Oct 2, 2016, 01:43 Mike McQuaid <notifications@github.com> wrote:

> *@MikeMcQuaid* commented on this pull request.
> ------------------------------
>
> In Formula/pyinvoke.rb
> <https://github.com/Homebrew/homebrew-core/pull/5279>:
>
> > @@ -0,0 +1,38 @@
> +class Pyinvoke < Formula
> +  include Language::Python::Virtualenv
> +
> +  desc "Pythonic task management & command execution"
> +  homepage "http://pyinvoke.org/"
> +  url "https://github.com/pyinvoke/invoke/archive/0.13.0.tar.gz"
> +  sha256 "4942aa901618f99afa70271d7b15fd018da0f174178fbca4048354c785e7736a"
> +
> +  head "https://github.com/pyinvoke/invoke.git"
> +
> +  depends_on :python if MacOS.version <= :snow_leopard
> +
> +  def install
> +    virtualenv_install_with_resources
>
> Yeh, not really your issue here just interested what @tdsmith
> <https://github.com/tdsmith> thinks re: naming etc.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-core/pull/5279>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKnQREynMiM-zW2HpvpzYZyyqdzh96pks5qv26mgaJpZM4KHUp8>
> .
>

2016-10-02 17:43 UTC, MikeMcQuaid commented
@tdsmith Last question: is it worth bottling things like this or better just have them `bottle :unneeded`?

2016-10-03 00:31 UTC, tdsmith commented
Doesn't hurt but pure-Python modules with no dependencies don't gain any appreciable benefits from bottling.

2016-10-03 01:36 UTC, DomT4 requested changes

2016-10-03 01:36 UTC, DomT4 commented on Formula/pyinvoke.rb
> +    mkdir_p testpath/"foo"/"bar"
`(testpath/"foo/bar").mkpath` is preferred.

2016-10-03 01:36 UTC, DomT4 commented on Formula/pyinvoke.rb
> +    mkdir_p testpath/"baz"
And `(testpath/"baz").mkpath`

2016-10-03 01:36 UTC, DomT4 commented on Formula/pyinvoke.rb
> +    assert !File.exist?(testpath/"foo"), "\"pyinvoke clean\" should have deleted \"foo\""
Doesn't need to be decided right here, but now we're enforcing Ruby 2.0 we can use things like `assert_predicate` if we like, which produces nicer error messages by default without necessarily having to explicitly write out one.

2016-10-03 01:36 UTC, DomT4 commented on Formula/pyinvoke.rb
> +
No empty line required here.

2016-10-03 02:04 UTC, mdaniel commented on Formula/pyinvoke.rb
> +    assert !File.exist?(testpath/"foo"), "\"pyinvoke clean\" should have deleted \"foo\""
How does one `assert_predicate thing, *negated* operation`? I tried the simplistic `a_p thing, !:exist?` and got a horrible explosion and I didn't see any `:missing?` on `File`

I only found [one example](https://github.com/Homebrew/homebrew-core/blob/0379d0d/Formula/conan.rb#L141) across all the `homebrew-*` Taps I have locally, and [the documentation](http://ruby-doc.org/stdlib-2.0.0/libdoc/minitest/rdoc/MiniTest/Assertions.html#assert_predicate-method) wasn't helpful.

2016-10-03 02:09 UTC, DomT4 commented on Formula/pyinvoke.rb
> +    assert !File.exist?(testpath/"foo"), "\"pyinvoke clean\" should have deleted \"foo\""
That would be `refute_predicate`. Probably worth me polling @ilovezfs and @zmwangx on this change though, I'm not around as much as I used to be so they'll end up dealing with it day to day if we decide to change.

2016-10-15 11:12 UTC, MikeMcQuaid commented
@BrewTestBot test this please

2016-10-15 13:21 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `pyinvoke 0.13.0 (new formula)`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

2016-10-15 13:21 UTC, closed without merging