add jc formula
Homebrew/homebrew-core pull request #53285
Opened 2020-04-18 00:46 UTC by kellyjonbrazil

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2020-04-18 01:01 UTC, kellyjonbrazil commented
Hmm, not sure what to do since my app is a compiled python binary.

```
$ brew audit --new-formula jc
jc:
  * C: 2: col 3: Description is too long. "name: desc" should be less than 80 characters. Length is calculated as jc + desc. (currently 116)
  * C: 2: col 119: Line is too long. [121/118]
  * C: 4: col 3: https://jc-packages.s3-us-west-1.amazonaws.com/bin/jc-1.10.5-darwin.tar.gz looks like a binary package, not a source archive; homebrew/core is source-only.
  * C: 13: col 119: Line is too long. [130/118]
  * Stable: version 1.10.5 is redundant with version scanned from URL
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      bin/jc
Error: 6 problems in 1 formula detected
```

2020-04-18 06:35 UTC, jonchang requested changes
Looks like a good start! Please run `brew audit --new-formula --strict jc` locally and ensure that it passes. In addition, please squash your commits and amend the commit message to read `jc 1.10.5 (new formula)` per our guidelines: https://docs.brew.sh/Formula-Cookbook#commit

2020-04-18 06:35 UTC, jonchang commented on Formula/jc.rb
> +  desc "This tool serializes the output of popular gnu linux command-line tools and file types to structured JSON output"
`desc` should be shorter

2020-04-18 06:35 UTC, jonchang commented on Formula/jc.rb
> +  url "https://jc-packages.s3-us-west-1.amazonaws.com/bin/jc-1.10.5-darwin.tar.gz"
Formulae should build from source in homebrew-core: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

For an example of a python app formula, run `brew cat black`

2020-04-18 06:35 UTC, jonchang commented on Formula/jc.rb
> +end
Files should end with a newline.

2020-04-19 00:13 UTC, kellyjonbrazil commented
I think I'm pretty close now (except for the commit squashing, which I'll figure out).

I used the black package method and it installed fine, but my app errors out with this message when run.  Does this mean I need to go to all of my required packages and include their required packages, and so on?

```
Traceback (most recent call last):
  File "./jc", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/jc/1.10.5/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/local/Cellar/jc/1.10.5/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/jc/1.10.5/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/jc/1.10.5/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/jc/1.10.5/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/jc/1.10.5/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ruamel.yaml.clib>=0.1.2' distribution was not found and is required by ruamel.yaml
```

2020-04-19 00:44 UTC, kellyjonbrazil commented
This seems to work now. I'm not sure if I squashed and renamed the commit correctly, though.

2020-04-19 00:56 UTC, jonchang commented
You've got a merge commit in there which our CI system can struggle with. I'll repair the branch in a second. In the future I recommend opening pull requests from branches, rather than the `master` branch of your fork.

2020-04-19 01:27 UTC, kellyjonbrazil commented
Sorry about that - I'll definitely do that next time. I think we are good to go. Just fixed the test so it's passing now.

2020-04-19 01:30 UTC, kellyjonbrazil commented
I think these errors are benign, but let me know if you think I need to make any adjustments.  The test fixtures have many file listings, so it makes sense that there might be a reference to the Homebrew shims directory. The `jc` tests are just parsing the text, so there is no real dependency.

```
$ brew audit --strict jc
jc:
  * C: 45: col 1: 1 trailing blank lines detected.
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      libexec/lib/python3.8/site-packages/tests/fixtures/osx-10.11.6/du.out
      libexec/lib/python3.8/site-packages/tests/fixtures/osx-10.11.6/du.json
      libexec/lib/python3.8/site-packages/tests/fixtures/osx-10.14.6/du.out
      libexec/lib/python3.8/site-packages/tests/fixtures/osx-10.14.6/du.json
Error: 2 problems in 1 formula detected
```

2020-04-20 23:45 UTC, kellyjonbrazil commented
All tests are passing now.

2020-04-21 00:23 UTC, kellyjonbrazil commented
I'm not sure how to squash the commits without causing a merge issue. Shall I close this PR, create a new local branch, and submit a new PR from there with a single commit so it will be clean?

2020-04-21 06:15 UTC, SMillerDev commented
Rebase your branch, squash the commits and (force) push the resulting commit.

2020-04-21 18:58 UTC, kellyjonbrazil commented
I think I've squashed as much as I can since there is a weird merge in my branch I don't know how to deal with.

2020-04-21 23:06 UTC, kellyjonbrazil commented
Ok, I think we are good now!

2020-04-22 05:13 UTC, SMillerDev commented
Thanks @kellyjonbrazil  Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

2020-04-22 09:03 UTC, closed without merging

2020-04-22 17:13 UTC, jconley commented
fyi the catalina bottle is returning 404

2020-04-22 17:24 UTC, Bo98 commented
Thanks. I’ll check up on why that happened.

2020-04-22 23:01 UTC, Bo98 commented
Should be fixed now.