mg3a: Fix --with-all option
Homebrew/homebrew-core pull request #5334
Opened 2016-09-28 14:18 UTC by rwhogg

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

Previously, it failed with the message:
Error: no implicit conversion of String into Integer

2016-09-28 21:12 UTC, zmwangx requested changes

2016-09-28 21:12 UTC, zmwangx commented on Formula/mg3a.rb
> +      mg3aopts = ["-DALL"] if build.with?("all")
Maybe `%w[-DALL]` for style consistency?

2016-09-28 21:13 UTC, zmwangx commented on Formula/mg3a.rb
> +      mg3aopts = ["-DALL"] if build.with?("all")
And

```ruby
if build.with?("all")
  mg3aopts = ["-DALL"] if build.with?("all")
```

...

The latter `if build.with?("all")` is redundant.

2016-09-28 21:15 UTC, rwhogg commented on Formula/mg3a.rb
> +      mg3aopts = ["-DALL"] if build.with?("all")
Wow, yes it is. I'll fix that too while I'm here

2016-09-29 00:43 UTC, zmwangx approved these changes

2016-09-29 00:44 UTC, merged

2016-09-29 00:44 UTC, zmwangx commented
Thanks!