tanka v0.9.2 (new formula)
Homebrew/homebrew-core pull request #53421
Opened 2020-04-19 22:20 UTC by sh0rez

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This adds [Tanka](https://tanka.dev), a Kubernetes configuration management tool build at Grafana Labs.

2020-04-19 22:23 UTC, claui requested changes
Can you improve the test so it exercises at least a tiny bit of `tk`’s functionality?

2020-04-19 22:45 UTC, sh0rez commented
@claui Sure! I've added a test that uses https://github.com/sh0rez/grafana.libsonnet (an example library for Tanka) to render some YAML. This is the advanced operation Tanka does without requiring user input, but definitely checks for functionality, such as the integrated Jsonnet compiler and the processing stages.

2020-04-20 08:46 UTC, SMillerDev commented on Formula/tanka.rb
> +    :tag => "v0.9.2"
Please specify a commit hash here as well.

2020-04-20 09:15 UTC, sh0rez commented on Formula/tanka.rb
> +    :tag => "v0.9.2"
Done, PTAL

2020-04-20 09:23 UTC, SMillerDev commented
Can you squash your commits?

2020-04-20 10:37 UTC, sh0rez commented
@smillerdev done!

2020-04-20 11:19 UTC, SMillerDev commented
Thanks @sh0rez  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

2020-04-20 11:56 UTC, closed without merging