open-mpi 2.0.1 revision 1
Homebrew/homebrew-core pull request #5359
Opened 2016-09-29 04:45 UTC by ggouaillardet

issue an user-friendly error message if the path to a Unix socket is too long.
it has been reported several times on the Open MPI mailing list that mpirun
fails to start (bind() error). the root cause is $TMPDIR can be quite long
and hence the path to a Unix socket is too long. unfortunatly, that was
not catched properly, leading to an un-understandable error message.

the patch is coming from https://github.com/open-mpi/ompi/pull/2135

Signed-off-by: ggouaillardet <gilles@rist.or.jp>

2016-09-29 07:20 UTC, MikeMcQuaid requested changes

2016-09-29 07:20 UTC, MikeMcQuaid commented on Formula/open-mpi.rb
> +  patch do
Add a newline above this line (ideally fix so `brew audit --strict` is 👍).

2016-09-29 07:20 UTC, MikeMcQuaid commented on Formula/open-mpi.rb
> +    url "https://github.com/open-mpi/ompi/pull/2135.patch"
Can you add a brief comment describing what the patch is needed for? Thanks for submitting a PR to both projects, though!

2016-09-29 08:57 UTC, ggouaillardet commented
@MikeMcQuaid i made both changes and updated the PR, and am now double checking everything is fine

2016-09-29 09:05 UTC, MikeMcQuaid requested changes

2016-09-29 09:05 UTC, MikeMcQuaid commented on Formula/open-mpi.rb
> +  revision 1
I think you can probably omit this; I don't think this issue is severe enough to force a reinstall for anyone unaffected.

2016-09-30 06:09 UTC, ggouaillardet commented on Formula/open-mpi.rb
> +  revision 1
@MikeMcQuaid done, we should be good for primetime

2016-09-30 07:26 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `open-mpi: fix handling long TMPDIRs.` and there's no need to sign off your own commits.

2016-09-30 07:33 UTC, closed without merging