Update to Liquigraph 4.0.1
Homebrew/homebrew-core pull request #53932
Opened 2020-04-28 21:16 UTC by fbiville

Requires JDK 11

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2020-04-28 22:55 UTC, bayandin requested changes
Can we use the latest OpenJDK (currently it's 13 in Homebrew)?

2020-04-28 22:55 UTC, bayandin commented on Formula/liquigraph.rb
> +  depends_on :java => "11"
```suggestion
  depends_on "openjdk@11"
```

2020-04-28 22:55 UTC, bayandin commented on Formula/liquigraph.rb
>      ENV["JAVA_HOME"] = Utils.popen_read(cmd).chomp
```suggestion
    ENV["JAVA_HOME"] = Formula["openjdk@11"].opt_prefix
```

2020-04-28 22:55 UTC, bayandin commented on Formula/liquigraph.rb
> +    (bin/"liquigraph").write_env_script libexec/"liquigraph.sh", Language::Java.java_home_env("11")
```suggestion
    (bin/"liquigraph").write_env_script libexec/"liquigraph.sh", :JAVA_HOME => Formula["openjdk@11"].opt_prefix
```

2020-04-29 13:01 UTC, fbiville commented
> Can we use the latest OpenJDK (currently it's 13 in Homebrew)?

11 is a minimum, but it should work with 13.

2020-04-29 14:31 UTC, SMillerDev reviewed
Since you mentioned it works with Java 13, this would be better

2020-04-29 14:31 UTC, SMillerDev commented on Formula/liquigraph.rb
> +  depends_on "openjdk@11"
```suggestion
  depends_on "openjdk"
```

2020-04-29 14:31 UTC, SMillerDev commented on Formula/liquigraph.rb
> +    ENV["JAVA_HOME"] = Formula["openjdk@11"].opt_prefix
```suggestion
    ENV["JAVA_HOME"] = Formula["openjdk"].opt_prefix
```

2020-04-29 14:31 UTC, SMillerDev commented on Formula/liquigraph.rb
> +    (bin/"liquigraph").write_env_script libexec/"liquigraph.sh", :JAVA_HOME => Formula["openjdk@11"].opt_prefix
```suggestion
    (bin/"liquigraph").write_env_script libexec/"liquigraph.sh", ::JAVA_HOME => "${JAVA_HOME:-#{ENV["JAVA_HOME"]}}"
```

2020-04-30 14:49 UTC, bayandin requested changes
And could you please squash all the commits into one with a message `liquigraph 4.0.1`.

Thanks!

2020-04-30 14:49 UTC, bayandin commented on Formula/liquigraph.rb
> +    (bin/"liquigraph").write_env_script libexec/"liquigraph.sh", ::JAVA_HOME => "${JAVA_HOME:-#{ENV["JAVA_HOME"]}}"
```suggestion
    (bin/"liquigraph").write_env_script libexec/"liquigraph.sh", :JAVA_HOME => "${JAVA_HOME:-#{ENV["JAVA_HOME"]}}"
```

2020-04-30 17:19 UTC, SMillerDev commented
The test is failing.

2020-05-01 12:54 UTC, fbiville commented
@SmillerDev now fixed

2020-05-01 14:21 UTC, SMillerDev commented
Thanks @fbiville  Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

2020-05-01 15:06 UTC, closed without merging