armor 0.1.1 (new formula)
Homebrew/homebrew-core pull request #5403
Opened 2016-09-30 04:54 UTC by vishr

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

Signed-off-by: Vishal Rana <vr@labstack.com>

2016-09-30 07:20 UTC, MikeMcQuaid requested changes

2016-09-30 07:20 UTC, MikeMcQuaid commented on Formula/armor.rb
> +    system "armor", "-v"
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2016-09-30 07:20 UTC, MikeMcQuaid commented on Formula/armor.rb
> +    system "armor", "-v"
Regardless `system "#{bin}/armor"` is needed

2016-09-30 13:38 UTC, vishr commented on Formula/armor.rb
> +    system "armor", "-v"
Changes done.

2016-09-30 14:29 UTC, DomT4 commented on Formula/armor.rb
> +      system "go", "build", "-o", bin/"armor", "cmd/armor/main.go"
Will need a:
```ruby
prefix.install_metafiles
```
line underneath this as well.

2016-09-30 17:28 UTC, dunn commented on Formula/armor.rb
> +    assert_match version.to_s, shell_output("#{bin}/armor -v")
I think Mike meant a more substantial test than checking the `-v` output.   Can you start the server, see if the basic functionality is working?

2016-09-30 17:31 UTC, vishr commented on Formula/armor.rb
> +    assert_match version.to_s, shell_output("#{bin}/armor -v")
My knowledge with ruby is limited, do you think we can defer this and get the formula in?

2016-09-30 17:49 UTC, dunn commented on Formula/armor.rb
> +    assert_match version.to_s, shell_output("#{bin}/armor -v")
Try looking at formulae like [`mailhog.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mailhog.rb) and [`algernon.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/algernon.rb) and [`etcd.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/etcd.rb) for some examples, and let us know if you have questions!

2016-09-30 18:21 UTC, vishr commented on Formula/armor.rb
> +    assert_match version.to_s, shell_output("#{bin}/armor -v")
@dunn Thanks for the examples, I followed one of them and updated the test.

2016-09-30 19:53 UTC, bfontaine commented on Formula/armor.rb
> +      sleep(1)
Small nit but you don’t need the parentheses here: `sleep 1`.

2016-09-30 20:15 UTC, vishr commented on Formula/armor.rb
> +      sleep(1)
@bfontaine It is fixed now.

2016-10-01 16:57 UTC, vishr commented
Whats the expected time for this to get merged? Please let me know if anymore changes are required at my end.

2016-10-02 03:14 UTC, closed without merging

2016-10-02 03:14 UTC, dunn commented
Merged, thank you!!