libtorrent-rakshasa 0.13.8 (new formula)
Homebrew/homebrew-core pull request #54572
Opened 2020-05-11 15:11 UTC by pyed

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Previous PRs:
https://github.com/Homebrew/homebrew-core/pull/369: `boneyard libtorrent/rtorrent` all tries failed to build it in macOS back in 2016.
https://github.com/Homebrew/homebrew-core/pull/32774 & https://github.com/Homebrew/homebrew-core/pull/35797 & https://github.com/Homebrew/homebrew-core/pull/37984: All failed because of issues with building on previous macOS versions, my formula depends on `Catalina` which build and work just fine with no hacks.

2020-05-11 15:29 UTC, pyed commented
I see that tests passed with macOS `10.13` and `10.14`, should I remove the `depends_on :macos => :catalina` line ? I made it a requirement based on previous failed PR attempts, but I haven't test it myself on older macOS versions.

2020-05-11 17:08 UTC, SMillerDev commented
> should I remove the depends_on :macos => :catalina line ?

Yes, all formula should build on all macOS versions.

2020-05-14 13:03 UTC, SMillerDev approved these changes
Thanks @pyed! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

2020-05-14 13:03 UTC, SMillerDev requested changes
Whoops, too soon. Can you squash your commits?

2020-05-14 13:16 UTC, pyed commented
> Whoops, too soon. Can you squash your commits?

Done!

2020-05-14 14:46 UTC, SMillerDev approved these changes

2020-05-16 20:22 UTC, closed without merging