terminal-notifier 1.7.0
Homebrew/homebrew-core pull request #5477
Opened 2016-10-01 16:40 UTC by julienXX

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

2016-10-02 00:32 UTC, zmwangx requested changes

2016-10-02 00:32 UTC, zmwangx commented on Formula/terminal-notifier.rb
>    sha256 "d71243e194d290e873eb5c5f30904e1d9406246d089e7d4d48ca275a8abfe275"
You forgot the change the checksum, which should be `cc70666e75b0e85ff43973d6d1212a8ebc7ef3cdf20d09be7a76eb7f1c9923d7`.

2016-10-03 13:43 UTC, zmwangx commented
I opened #5534 since there was no response here. Your authorship is retained.

2016-10-03 13:43 UTC, closed without merging

2016-10-03 13:45 UTC, julienXX commented
@zmwangx thanks! I'll release 1.7.1 really soon so I was waiting a bit to update the PR, sorry I should have left a comment here.