mobile-shell:  enable complete tests under 'make check'
Homebrew/homebrew-core pull request #5489
Opened 2016-10-01 20:55 UTC by cgull

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

'make check' will use tmux to run complete tests if
available, including running the executables.

This likely would have caught #5220 and #5247.

This runs the tests at build time, rendering the smoke test in the `test` block irrelevant-- what's the proper way to handle this?
(We tried to improve that before in #3880)

2016-10-02 08:33 UTC, MikeMcQuaid commented
@DomT4 thoughts on this?

2016-10-03 02:15 UTC, apjanke commented on Formula/mobile-shell.rb
> +  revision 4
Probably no need for a `revision` here. The installed binary will be the same, and that's the criteria for a `revision`.

2016-10-03 02:19 UTC, DomT4 commented on Formula/mobile-shell.rb
> +  depends_on "tmux" => :build if build.with?("test") || build.bottle?
Don't need the parens or `|| build.bottle?` here.

2016-10-03 02:24 UTC, DomT4 commented
> @DomT4 thoughts on this?

My only concern is that isn't `cellar :any`, so any users outside of `/usr/local` installing `mosh` in future are going to get a `tmux` installation dumped on them by default. There's an opt-out so not the end of the world. Overall, probably a 👍.

The existing test should remain though, smoke or otherwise they have their uses.

2016-10-03 06:54 UTC, MikeMcQuaid requested changes

2016-10-03 06:54 UTC, MikeMcQuaid commented on Formula/mobile-shell.rb
> +  depends_on "tmux" => :build if build.with?("test") || build.bottle?
As it's using the test by default.

2016-10-03 07:01 UTC, ilovezfs commented
I don't see the need to run the test by default if we're running it during bottle. Is there some reason to believe it's going to fail for the source-build users if it passed when bottling?

2016-10-19 01:35 UTC, dunn commented
@ilovezfs do you mean we should change it to `depends_on "tmux" => :build if build.bottle?`

2016-10-19 04:05 UTC, ilovezfs commented
@dunn right, and changing without-test to with-test. That pattern is used in bup, gammaray, ghc, gnuplot, liblas, leveldb, python, and protobuf. mobile-shell is the only one that gets it wrong, as Mike pointed out, by using it when the test option is default on.

2016-10-23 09:55 UTC, MikeMcQuaid approved these changes

2016-10-23 11:46 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-10-23 11:46 UTC, closed without merging