Replace references to “(Mac) OS X” with “macOS”
Homebrew/homebrew-core pull request #5501
Opened 2016-10-02 05:59 UTC by izzynavedo

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

2016-10-02 08:29 UTC, MikeMcQuaid requested changes
I've only reviewed a few places but you'll need to check them all not all changes makes sense.

2016-10-02 08:29 UTC, MikeMcQuaid commented on Formula/apcupsd.rb
> +        Note: On macOS El Capitan and above, the kernel extension currently
When referring to a specific version we should use the correct naming e.g. OS X in this case.

2016-10-02 08:29 UTC, MikeMcQuaid commented on Formula/archey.rb
> +    assert_match "Archey macOS 1", shell_output("#{bin}/archey --help")
Are you sure?

2016-10-02 08:29 UTC, MikeMcQuaid commented on Formula/ccze.rb
> +    # Allegedly from Debian & fixes compiler errors on old macOS releases.
OS X

2016-10-02 08:29 UTC, MikeMcQuaid commented on Formula/cloc.rb
> +    # These are shipped as standard with macOS/macOS' default Perl, but
Duplicated

2016-10-02 23:29 UTC, izzynavedo commented
I think I've found and corrected all the errors.

2016-10-15 11:05 UTC, MikeMcQuaid approved these changes

2016-10-15 11:16 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-10-15 11:16 UTC, closed without merging