turbogit v1.0.0 (new formula)
Homebrew/homebrew-core pull request #55208
Opened 2020-05-24 09:00 UTC by b4nst

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2020-05-24 12:42 UTC, dawidd6 commented on Formula/turbogit.rb
> +    assert_match /Version:\s+#{version}/, shell_output("#{bin}/tug version")
Could this test be more sophisticated? I mean, test the functionality of the program more than just the version.

2020-05-24 12:44 UTC, dawidd6 requested changes
Repository currently has 0 stars.

2020-05-25 09:01 UTC, SMillerDev commented
> Repository currently has 0 stars.

That should have failed the build.

2020-05-25 09:02 UTC, SMillerDev commented
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

2020-05-25 09:02 UTC, closed without merging