shibboleth: depend on apr, apr-util for Sierra
Homebrew/homebrew-core pull request #5546
Opened 2016-10-03 20:22 UTC by FranklinChen

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

Resolve https://github.com/Homebrew/homebrew-core/issues/5339

2016-10-03 20:26 UTC, ilovezfs commented
This is probably only needed at build time (`=> :build`). Also, it should probably be scoped to the systems that actually need it (e.g., `DevelopmentTools.clang_build_version >= 800).

2016-10-03 20:39 UTC, FranklinChen commented
I copied what `passenger` does for build scoping.

2016-10-04 07:12 UTC, MikeMcQuaid requested changes

2016-10-04 07:12 UTC, MikeMcQuaid commented on Formula/shibboleth-sp.rb
> +  depends_on macos: :yosemite
Keep this as it was. Apologies that this has changed recently.

2016-10-04 07:12 UTC, MikeMcQuaid commented on Formula/shibboleth-sp.rb
> +        https://wiki.shibboleth.net/confluence/display/EDS10/3.1+Configuring+the+Service+Provider
Let's leave these as they contain Homebrew-specific paths but the instructions aren't Homebrew-only.

2016-10-04 07:12 UTC, MikeMcQuaid commented on Formula/shibboleth-sp.rb
> -  plist_options :startup => true, :manual => "shibd"
Leave this as-is.

2016-10-04 19:36 UTC, DomT4 commented
> This is probably only needed at build time (=> :build). Also, it should probably be scoped to the systems that actually need it (e.g., DevelopmentTools.clang_build_version >= 800).

It won't be build-time only. That's only really the case when using the system version of `apr`, and even then it's a hack around our dependency system more than anything else. Most stuff does dynamically link to the Apr library. Someone might just want to change the requirement in `brew` now this is expanding beyond `subversion` as a problem.

`DevelopmentTools.clang_build_version >= 800` isn't strictly true IIRC; they'll still be available via the 7.x CLT on El Cap, so even if you've Xcode 8 on 10.11 as long as the CLT is installed you'll be fine. Off the top of my head though, so feel free to check.

2016-10-04 19:42 UTC, ilovezfs commented
`DevelopmentTools.clang_build_version >= 800` is what's reported if both Xcode 8 and CLT 7 are installed if that's what you're asking.

2016-10-04 19:43 UTC, DomT4 commented
Anything `:` there is fine as `:build`, kind of, that's a hack around our dep system IIRC. Anything `""` should be checked, but I'd be very surprised if they were build unless those formulae only produce static libraries/executables.

2016-10-04 19:54 UTC, ilovezfs commented
@DomT4 LOL https://github.com/Homebrew/homebrew-core/issues/5599

2016-10-04 19:57 UTC, DomT4 commented
Yeah. Probably worth giving up doing this individually and just enforce it for Sierra via the requirement.

2016-10-05 07:58 UTC, MikeMcQuaid commented
Blocked on https://github.com/Homebrew/brew/pull/1227.

2016-10-15 11:06 UTC, MikeMcQuaid requested changes

2016-10-15 11:06 UTC, MikeMcQuaid commented on Formula/shibboleth-sp.rb
> +    depends_on "apr" => :build
Make these unconditional.

2016-10-15 11:06 UTC, MikeMcQuaid commented on Formula/shibboleth-sp.rb
> +    depends_on "apr" => :build
Also, are you sure they aren't linked against?

2016-11-10 16:48 UTC, MikeMcQuaid commented
@FranklinChen Any news on the comments above? Thanks!

2016-11-10 17:00 UTC, FranklinChen commented
I'd been busy, will address this.

2016-11-28 22:12 UTC, FranklinChen commented
I updated according to comments here.

2016-12-02 08:40 UTC, MikeMcQuaid approved these changes

2016-12-02 08:40 UTC, MikeMcQuaid commented on Formula/shibboleth-sp.rb
> +        https://wiki.shibboleth.net/confluence/display/EDS10/3.1+Configuring+the+Service+Provider
Actually, they were there before so it's fine.

2016-12-02 09:08 UTC, closed without merging

2016-12-02 09:08 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-12-02 15:03 UTC, FranklinChen commented
Is this going to be merged?

2016-12-02 15:19 UTC, MikeMcQuaid commented
It was.