cpputest 4.0
Homebrew/homebrew-core pull request #55483
Opened 2020-05-30 07:23 UTC by basvodde

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

(Sorry for this. I had updated the release tag as it was missing the version update. I hadn't realized that would cause a SHA mismatch and cause a warning. Fixed asap)

2020-05-30 14:14 UTC, chenrui333 commented
relates to #55333

2020-05-30 14:14 UTC, chenrui333 submitted a review, later dismissed

2020-05-30 15:20 UTC, dawidd6 requested changes
Commit message should be named as the PR now is, cause we are not bumping the version here.

2020-05-31 06:40 UTC, basvodde commented
Changed, thanks!

2020-06-02 03:04 UTC, basvodde commented
Is there anything that I still need to do?

2020-06-02 03:21 UTC, chenrui333 approved these changes

2020-06-02 03:22 UTC, chenrui333 commented
> Is there anything that I still need to do?

lgtm, thanks!!

2020-06-02 05:37 UTC, dawidd6 approved these changes

2020-06-03 09:36 UTC, closed without merging