Fix ctail build by adding dependency on apr and apr-util
Homebrew/homebrew-core pull request #5550
Opened 2016-10-03 21:51 UTC by Moisan

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)? -- It fails as not being notable enough, however the formula was already into Homebrew.

-----

* Add dependency on `apr` and `apr-util`
* Add their path to the configure flags
* Add a test

2016-10-03 21:54 UTC, Moisan commented
This should also fix the Sierra bottle #5488 issue for ctail.

2016-10-04 07:10 UTC, MikeMcQuaid requested changes

2016-10-04 07:10 UTC, MikeMcQuaid commented on Formula/ctail.rb
> +    system "ctail", "-h"
Test is failing: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8708/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_ctail/

Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

Finally, regardless it should be `system "#{bin}/ctail", "-h"`

2016-10-04 07:10 UTC, MikeMcQuaid commented on Formula/ctail.rb
> +  depends_on "apr-util" => :build
Looks from the failing test that one or more of these are needed at runtime (i.e. no `:build`)

2016-10-04 07:10 UTC, MikeMcQuaid commented on Formula/ctail.rb
> +    system "./configure", "--prefix=#{prefix}", "--disable-debug", "--with-apr=#{Formula["apr"].bin}", "--with-apr-util=#{Formula["apr-util"].bin}"
Use `.opt_bin` for these and please wrap onto multiple lines so it's not longer than 80 characters.

2016-10-04 20:25 UTC, Moisan commented on Formula/ctail.rb
> +    system "ctail", "-h"
I don't see how to create a  more substantial test: ctail needs an ssh connection to apply tail on a remote machine. I don't know how to mock such connection.

2016-10-05 07:40 UTC, MikeMcQuaid requested changes

2016-10-05 07:40 UTC, MikeMcQuaid commented on Formula/ctail.rb
> +  depends_on "apr-util"
`depends_on :apr` should be sufficient here for all but Sierra and will work on Sierra when https://github.com/Homebrew/brew/pull/1227 is merged shortly. Sorry about the change, it's news to me too.

2016-10-05 07:40 UTC, MikeMcQuaid commented on Formula/ctail.rb
> +  depends_on "apr-util"
CC @DomT4 @ilovezfs to check my work here.

2016-10-05 16:26 UTC, Moisan commented
It worked on my machine but TestBot doesn't seem to find the `apr` files. Did I do something wrong?

2016-10-12 10:39 UTC, MikeMcQuaid approved these changes

2016-10-12 10:40 UTC, MikeMcQuaid commented
https://github.com/Homebrew/brew/pull/1227 was merged and I didn't think the `revision` was needed so I've edited the formula and will pull when 💚.

2016-10-12 11:08 UTC, MikeMcQuaid commented
We actually decided to change the https://github.com/Homebrew/brew/pull/1227 approach so I've edited again 😀

2016-10-12 11:18 UTC, merged

2016-10-12 11:19 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!