dub 1.1.0-beta.1 (devel)
Homebrew/homebrew-core pull request #5555
Opened 2016-10-03 22:33 UTC by John-Colvin

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

2016-10-04 07:08 UTC, MikeMcQuaid requested changes

2016-10-04 07:08 UTC, MikeMcQuaid commented on Formula/dub.rb
> +      tag: "v1.0.0",
Please use hash-rockets: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8713/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/style_dub/

Apologies that this changed relatively recently.

2016-10-06 17:39 UTC, John-Colvin commented on Formula/dub.rb
> +      tag: "v1.0.0",
If I do that then `brew audit --new-formula dub` fails, saying "Use the new Ruby 1.9 hash syntax."

2016-10-17 13:57 UTC, John-Colvin commented on Formula/dub.rb
> +      tag: "v1.0.0",
something weird was going on, i was stuck on homebrew `1.0.1`, all fixed now. Have updated the pr to use hash-rockets.

2016-10-17 18:04 UTC, MikeMcQuaid approved these changes

2016-10-17 18:19 UTC, merged

2016-10-17 18:19 UTC, MikeMcQuaid commented
Thanks again @John-Colvin!