sshuttle 1.0.1
Homebrew/homebrew-core pull request #55842
Opened 2020-06-05 15:23 UTC by BenjaminHCCarr

Created with `brew bump-formula-pr`.

2020-06-05 20:42 UTC, issyl0 requested changes
Thanks for this PR. Looks like `brew bump-formula-pr` missed off the `v` somehow on the tag.

2020-06-05 20:42 UTC, issyl0 commented on Formula/sshuttle.rb
> +      :tag      => "1.0.1",
```suggestion
      :tag      => "v1.0.1",
```

2020-06-08 12:32 UTC, issyl0 commented
Thanks for the update. Would you be able to squash the commits into one (`sshuttle 1.0.1`), please, then this will be mergeable.

2020-06-08 17:09 UTC, BenjaminHCCarr commented
squashed

2020-06-08 19:06 UTC, issyl0 approved these changes
Thank you!

2020-06-08 19:10 UTC, closed without merging