nmh 1.6 (new formula)
Homebrew/homebrew-core pull request #5598
Opened 2016-10-04 19:13 UTC by kenh

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

The modern version of the classic RAND MH Mail Handling system.

2016-10-04 21:46 UTC, bfontaine requested changes

2016-10-04 21:46 UTC, bfontaine commented on Formula/nmh.rb
> +  desc "Nmh, the new version of the MH mail handler"
Please don’t include the formula name in its description.

2016-10-04 21:46 UTC, bfontaine commented on Formula/nmh.rb
> +    Dir.mkdir(testpath/"Mail/inbox")
You can remove these two lines; `(testpath/"Mail/inbox/1").write` below will create the necessary directories.

2016-10-04 21:46 UTC, bfontaine commented on Formula/nmh.rb
> +    output = `#{bin}/scan -width 80`
Use `shell_output("…")` instead of `` `…` ``.

2016-10-04 22:07 UTC, kenh commented on Formula/nmh.rb
> +    output = `#{bin}/scan -width 80`
Just for my own edification; where is this documented? I freely admit I am not in any way a Ruby expert; I would just like to know what I need to read.

2016-10-05 07:57 UTC, MikeMcQuaid approved these changes

2016-10-05 07:57 UTC, bfontaine commented on Formula/nmh.rb
> +    output = `#{bin}/scan -width 80`
Unfortunately I don’t think we documented this somewhere. It’s used in a lot of formulae (see e.g. [`aardvark_shell_utils.rb`](https://github.com/Homebrew/homebrew-core/blob/cb886e6d5b8255ad8139fce2a25b1afb9ea15589/Formula/aardvark_shell_utils.rb#L27-L29), [`cgrep.rb`](https://github.com/Homebrew/homebrew-core/blob/1668cbc72bf4f5d38e7316774251f266bfc2f8f7/Formula/cgrep.rb#L34-L39), [`ppss.rb`](https://github.com/Homebrew/homebrew-core/blob/2c5572c61df26d7915af8ee796bad3dfea66ed90/Formula/ppss.rb#L14)). This is a function [defined in Homebrew](https://github.com/Homebrew/brew/blob/028d155e97014076adf4e4dbc7c888fd871de321/Library/Homebrew/formula_assertions.rb#L27) that’s an equivalent of `` `…` `` but asserts that the command ran successfully.

(note to myself or anyone reading this: document `shell_output` somewhere)

2016-10-05 07:57 UTC, bfontaine approved these changes

2016-10-05 08:00 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-10-05 08:00 UTC, closed without merging

2016-10-08 10:00 UTC, MikeMcQuaid commented on Formula/nmh.rb
> +    output = `#{bin}/scan -width 80`
We need to improve our automated tests for this (e.g. `brew audit`) but thanks for the suggestion.