git-series 0.8.10 (new formula)
Homebrew/homebrew-core pull request #5600
Opened 2016-10-04 20:27 UTC by pborzenkov

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

git series tracks changes to a patch series over time. git series also
tracks a cover letter for the patch series, formats the series for
email, and prepares pull requests.

Signed-off-by: Pavel Borzenkov <pavel.borzenkov@gmail.com>

2016-10-04 21:47 UTC, bfontaine commented on Formula/git-series.rb
> +    system bin/"git-series", "-V"
Can’t we write a test that does something more substantial than e.g. `-V`, `--version`, or `--help`?

2016-10-05 07:59 UTC, MikeMcQuaid requested changes

2016-10-05 07:59 UTC, MikeMcQuaid commented on Formula/git-series.rb
> +      EOS
Tiny nit: can you unindent this by two characters? Thanks!

2016-10-05 07:59 UTC, MikeMcQuaid commented on Formula/git-series.rb
> +    system bin/"git-series", "commit", "-a", "-m", "new feature v1"
Is it worth checking the output of any of these commands? "No" is an acceptable answer 😁

2016-10-05 08:08 UTC, pborzenkov commented on Formula/git-series.rb
> +    system bin/"git-series", "commit", "-a", "-m", "new feature v1"
@MikeMcQuaid They don't output anything particularly useful for the test, only that the series's been successfully started/commit. But this is already covered by the return code. So I believe there is no need to check the output.

2016-10-05 08:10 UTC, pborzenkov commented on Formula/git-series.rb
> +      EOS
@MikeMcQuaid Done

2016-10-05 08:16 UTC, MikeMcQuaid approved these changes

2016-10-05 08:28 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-10-05 08:28 UTC, closed without merging