pick 1.5.1
Homebrew/homebrew-core pull request #5608
Opened 2016-10-05 08:56 UTC by teoljungberg

2016-10-05 09:48 UTC, teoljungberg commented
Regarding the build failure - `make check` passed for me locally on El Capitan. Is there anything I can do and/or help with to get the build back to green?

2016-10-06 07:51 UTC, teoljungberg commented on Formula/pick.rb
> +  version "1.5.1"
Good call, done!

2016-10-08 10:09 UTC, MikeMcQuaid commented
@BrewTestBot test this please

2016-10-08 15:45 UTC, MikeMcQuaid commented
> Regarding the build failure - make check passed for me locally on El Capitan. Is there anything I can do and/or help with to get the build back to green?

@teoljungberg I'm not sure what needs to be done, I'm afraid, but it'll need to be fixed before we can 🚢 this.

2016-10-13 09:51 UTC, calleerlandsson commented
@teoljungberg In the hopes of it fixing the CI issues, I've released [v1.5.2](https://github.com/calleerlandsson/pick/releases/tag/v1.5.2). Do you want to update this PR to reference it or should we open a new one?

2016-10-13 11:01 UTC, teoljungberg commented
@calleerlandsson Thanks for letting me know. I updated this PR with the new version

2016-10-14 08:16 UTC, teoljungberg commented
@MikeMcQuaid We've fixed the test failure on CI now, I've rebased and squashed the PR.

2016-10-14 15:40 UTC, MikeMcQuaid requested changes

2016-10-14 15:40 UTC, MikeMcQuaid commented on Formula/pick.rb
> +    system "TERM=xterm make check"
Use `ENV["TERM"] = "xterm"` and leave the system as-is, thanks!

2016-10-21 11:55 UTC, teoljungberg commented on Formula/pick.rb
> +    system "TERM=xterm make check"
@MikeMcQuaid I moved it to the beginning of the `install` method.

2016-10-22 13:07 UTC, MikeMcQuaid requested changes

2016-10-22 13:07 UTC, MikeMcQuaid commented on Formula/pick.rb
> +    system "make check"
Please put this back to how it was before, thanks.

2016-10-23 20:53 UTC, teoljungberg commented on Formula/pick.rb
> +    system "make check"
Done and done.

2016-10-25 12:45 UTC, MikeMcQuaid approved these changes

2016-10-25 12:50 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-10-25 12:50 UTC, closed without merging