fontforge 20161004
Homebrew/homebrew-core pull request #5611
Opened 2016-10-05 10:17 UTC by jtanx

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

This updates the formula to remove a number of hacks that are no longer necessary. I've also switched it to use the dist tarball, which no longer requires `./bootstrap`/autotools needed in every build, only HEAD.

I've also added back the optional `--with-x11` option to optionally build the GUI (this is very handy when testing HEAD builds).

2016-10-05 10:19 UTC, jtanx commented
I've also switched libspiro and libuninameslist to be recommended, because realistically, only FontForge uses these libraries.

2016-10-08 09:55 UTC, MikeMcQuaid commented on Formula/fontforge.rb
> +  depends_on :x11 => :optional
Please remove this, we'd rather not support it.

2016-10-08 09:57 UTC, MikeMcQuaid requested changes

2016-10-08 09:57 UTC, MikeMcQuaid commented on Formula/fontforge.rb
> +  if build.head?
Make a `head do` block and put these in there along with the above `head` as a `url` instead.

2016-10-08 09:57 UTC, MikeMcQuaid commented on Formula/fontforge.rb
> +  depends_on :x11 => :optional
Please remove this, we'd rather not support it.

2016-10-08 09:57 UTC, MikeMcQuaid commented on Formula/fontforge.rb
> +  depends_on "libuninameslist" => :recommended
If these are only used by FontForge then use vendor them as a `resource` in this package rather than having them separately.

2016-10-08 09:57 UTC, MikeMcQuaid commented on Formula/fontforge.rb
> -    end
These issues all fixed?

2016-10-08 09:57 UTC, MikeMcQuaid commented on Formula/fontforge.rb
> +      brew install fontforge --with-x11
Please remove this, we'd rather not support it.

2016-10-08 10:00 UTC, MikeMcQuaid commented on Formula/fontforge.rb
> +      brew install fontforge --with-x11
He's not active on Homebrew right now.

2016-10-08 10:01 UTC, jtanx commented on Formula/fontforge.rb
> -    end
Yes

2016-10-08 10:02 UTC, jtanx commented on Formula/fontforge.rb
> +  depends_on "libuninameslist" => :recommended
They're optional and they are separate libraries. No need to force them onto people who'd rather not build with these options, but at the same time, FontForge is the primary user.

2016-10-08 10:03 UTC, jtanx commented on Formula/fontforge.rb
> +  if build.head?
I think I originally had a `head do` block but rubocop complained because I also had an `if head?` further down in the compilation step.

2016-10-08 10:05 UTC, jtanx commented on Formula/fontforge.rb
> +  depends_on :x11 => :optional
Uh, FontForge really does depend on X11. Without support for things like this, it's near impossible to get anyone on Mac to actually test new features with any reasonable sort of speed. X11 support has already been disabled by default, so there's not much in the way of having to support anything.

2016-10-08 10:06 UTC, jtanx commented on Formula/fontforge.rb
> +      brew install fontforge --with-x11
Okay. He was the one who suggested that this way was possible.

2016-10-08 10:26 UTC, jtanx commented on Formula/fontforge.rb
> +  depends_on "libuninameslist" => :recommended
I'm hesitant to do this. They *are* distinct libraries and if I understand `resouce` correctly, it's just odd that you'd shift the creation of a *separate* entity/library into the formula for a dependant library - this goes against practically every package management system out there. 

IIRC, GEGL can use libspiro, although the current formula doesn't reference this.

2016-10-08 10:45 UTC, jtanx commented on Formula/fontforge.rb
> +  if build.head?
I've made the change.

2016-10-08 14:05 UTC, DomT4 commented on Formula/fontforge.rb
> +      brew install fontforge --with-x11
If you tag me in something it'll likely get a reply, I'm just not spending much time actively looking for stuff to do.

I have no objection to the X11 dep going in as optional personally, at least until https://github.com/fontforge/fontforge/pull/2782 is resolved positively (fingers crossed) and that's available in a release. There's a decent amount of optional X11 stuff in core.

It'd be a fair claim that most people doing `brew install fontforge` want at least a GUI optionally available. The alternative if upstream is planning to keep making `.app`s is to remove this entirely in favour of the Cask.

2016-10-08 15:02 UTC, MikeMcQuaid commented on Formula/fontforge.rb
> +      brew install fontforge --with-x11
Given we're removed it previously I'd rather not re-add it until we have something that works without X11.

2016-10-14 06:09 UTC, ilovezfs commented
Newer version out if you'd like to refresh this
https://github.com/fontforge/fontforge/archive/20161012.tar.gz

2016-10-14 06:54 UTC, jtanx commented
No, I'd need to make the dist tarball first. But I have no time.

2016-10-14 06:56 UTC, ilovezfs commented
@jtanx no problem. Take your time.

2016-11-10 16:48 UTC, MikeMcQuaid commented
@jtanx Any news on this? Thanks!

2016-11-11 11:50 UTC, jtanx commented
Sorry - not much time to work on this, and I think there's an issue with compiling on Sierra too. I don't have easy access to a system to debug that. Someone else might need to work this one out, otherwise it may be a while before I get back on this.

2016-11-11 12:21 UTC, ilovezfs commented
@BrewTestBot test this please

2016-11-16 07:23 UTC, ilovezfs commented
@jtanx this PR is now conflicted because I just shipped https://github.com/Homebrew/homebrew-core/pull/6638.

I made two changes to the fontforge formula in that PR:
(1) I dropped the dependencies on zeromq and czmq because fontforge is no longer compatible with the current version of czmq due to fontforge's use of the czmq v2 API, which was retired. See https://github.com/fontforge/fontforge/issues/2950.
(2) I revision bumped the formula due to (1).

2017-01-02 06:25 UTC, closed without merging