Add formula for OSRM
Homebrew/homebrew-core pull request #5660
Opened 2016-10-07 16:29 UTC by tmcw

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

2016-10-07 23:24 UTC, mistydemeo requested changes

2016-10-07 23:24 UTC, mistydemeo commented on Formula/osrm-backend.rb
> +    system "npm install"
This test block doesn't run within the project source, so there's nothing to `npm install`.

2016-10-07 23:24 UTC, mistydemeo commented on Formula/osrm-backend.rb
> +  depends_on "boost"
Do you mind alphabetizing the non-build dependencies?

2016-10-07 23:24 UTC, mistydemeo commented on Formula/osrm-backend.rb
> +  depends_on "ccache"
Is ccache required, or just here to speed up the build?

2016-10-10 14:42 UTC, MikeMcQuaid requested changes

2016-10-10 14:42 UTC, MikeMcQuaid commented on Formula/osrm-backend.rb
> +      system "cmake", "..", "-DCMAKE_BUILD_TYPE=Release", *std_cmake_args
@daniel-j-h We should rely on it because it won't change at any time.

2016-10-10 15:20 UTC, tmcw commented on Formula/osrm-backend.rb
> +  depends_on "ccache"
👍 ccache is removed

2016-10-10 15:20 UTC, tmcw commented on Formula/osrm-backend.rb
> +  depends_on "boost"
👍  dependencies sorted

2016-10-10 15:21 UTC, tmcw commented on Formula/osrm-backend.rb
> +    system "npm install"
👍 replaced this with standalone tests that don't require node and use the built program

2016-10-10 15:21 UTC, tmcw commented on Formula/osrm-backend.rb
> +      system "cmake", "--build", ".", "--target", "install"
👍 fixed

2016-10-10 15:21 UTC, tmcw commented on Formula/osrm-backend.rb
> +    system "npm test"
👍 replaced with a functional test

2016-10-11 11:29 UTC, ilovezfs commented
@BrewTestBot test this please

2016-10-12 11:32 UTC, MikeMcQuaid approved these changes

2016-10-12 11:34 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-10-12 11:35 UTC, closed without merging