rmlint 2.4.4 (new formula)
Homebrew/homebrew-core pull request #5669
Opened 2016-10-07 20:47 UTC by tomhoover

2016-10-08 15:55 UTC, MikeMcQuaid commented
@BrewTestBot test this please

2016-10-09 11:06 UTC, MikeMcQuaid requested changes
Looking good so far 👍

2016-10-09 11:06 UTC, MikeMcQuaid commented on Formula/rmlint.rb
> +  depends_on "json-glib" => :optional # support for reading json caches
Only need these comments for `:optional` and they are better handled with e.g. `option "with-json-glob", "Add support for reading JSON caches.'`

2016-10-09 11:06 UTC, MikeMcQuaid commented on Formula/rmlint.rb
> +    bin.install "rmlint"
Is there no `make install` equivalent we can use?

2016-10-09 11:06 UTC, MikeMcQuaid commented on Formula/rmlint.rb
> +    scons "-j 4"
Remove the `-j 4`, pretty sure we set it sensibly by default and you don't know how many cores a given user machine will have.

2016-10-09 11:06 UTC, MikeMcQuaid commented on Formula/rmlint.rb
> +    system bin/"rmlint"
Nice test. Is it worth creating a dupe and verifying it deletes that?

2016-10-09 20:54 UTC, tomhoover commented on Formula/rmlint.rb
> +  depends_on "json-glib" => :optional # support for reading json caches
done

2016-10-09 20:55 UTC, tomhoover commented on Formula/rmlint.rb
> +    scons "-j 4"
done

2016-10-11 00:35 UTC, tomhoover commented
@MikeMcQuaid, everything should be ready for another look.

2016-10-11 08:23 UTC, MikeMcQuaid requested changes

2016-10-11 08:23 UTC, MikeMcQuaid commented on Formula/rmlint.rb
> +    system "(#{bin}/rmlint | grep '^# Duplicate(s):$') || false"
Final tweak. Instead do:

```ruby
assert_match(/^# Duplicate(s):$/, shell_output("#{bin}/rmlint")
```

2016-10-11 11:06 UTC, tomhoover commented on Formula/rmlint.rb
> +    system "(#{bin}/rmlint | grep '^# Duplicate(s):$') || false"
@MikeMcQuaid, final tweak incorporated.

2016-10-11 12:45 UTC, tomhoover commented on Formula/rmlint.rb
> +    system "(#{bin}/rmlint | grep '^# Duplicate(s):$') || false"
@MikeMcQuaid, nevermind--the suggested change failed the build (whereas the previous test passed). I'll take a look at it again this evening.

2016-10-11 12:58 UTC, MikeMcQuaid commented on Formula/rmlint.rb
> +    system "(#{bin}/rmlint | grep '^# Duplicate(s):$') || false"
Looking again: `assert_match(/^# Duplicate\(s\):$/, shell_output("#{bin}/rmlint").strip` may do it correctly or just the looser `assert_match "# Duplicate(s):", shell_output("#{bin}/rmlint")`

2016-10-12 00:24 UTC, tomhoover commented
@MikeMcQuaid, I didn't have access to run tests from the command line while at work today, and attempted to "loosen" the search criteria by editing the file using a browser. It was over 8 hours before the test was re-run, but it failed again. Once got back home to my computer, I was able to review the build log in detail and found the following syntax will work:

`assert_match "# Duplicate(s):", shell_output("#{bin}/rmlint")`.

This was my first attempt at authoring a homebrew formula from scratch, so the assert_match was something new to me. I'm always learning! 😄

2016-10-12 07:07 UTC, MikeMcQuaid approved these changes

2016-10-12 07:17 UTC, closed without merging

2016-10-12 07:17 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!