omake 0.10.3 (new formula)
Homebrew/homebrew-core pull request #57525
Opened 2020-07-06 04:19 UTC by pthariensflame

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Ressurected 8 years later, now that it's being [maintained again](https://github.com/ocaml-omake/omake)!  Last seen in Homebrew/homebrew-core@a2d3be19ffe6ed8150ec5f3c56aa4e24bc2a2697 where it was “graveyarded.”

2020-07-06 04:37 UTC, pthariensflame commented
Failure is due to notability requirements.  Hopefully we can bypass those since this is a resurrection rather than a truly _new_ formula.

2020-07-06 10:48 UTC, jonchang requested changes
Nice work, some suggestions to fix the test error.

2020-07-06 10:48 UTC, jonchang commented on Formula/omake.rb
> +    mkdir "test_project" do
Tests already run in their own directory so this shouldn't be necessary unless it's required by the software in question.

2020-07-06 10:48 UTC, jonchang commented on Formula/omake.rb
> +      "hello_code.c".write <<~EOF
```suggestion
      (testpath/"hello_code.c").write <<~EOF
```

(assuming the `mkdir` above is removed)

2020-07-06 10:48 UTC, jonchang commented on Formula/omake.rb
> +      "OMakefile".write <<~EOF
```suggestion
      (testpath/"OMakefile").write <<~EOF
```

2020-07-07 06:06 UTC, jonchang commented on Formula/omake.rb
> +          printf("Hello, world!\n");
```suggestion
          printf("Hello, world!\\n");
```

2020-07-08 11:36 UTC, closed without merging

2020-07-12 03:38 UTC, chenrui333 commented
> Ressurected 8 years later, now that it's being maintained again! Last seen in a2d3be1 where it was “graveyarded.”

🎉  Nice finding.