snap telemetry version 0.16.0
Homebrew/homebrew-core pull request #5767
Opened 2016-10-10 21:23 UTC by nanliu

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

2016-10-11 11:37 UTC, ilovezfs commented
@BrewTestBot test this please

2016-10-12 14:45 UTC, MikeMcQuaid commented on Formula/snap-telemetry.rb
> +  url "https://github.com/intelsdi-x/snap/archive/v0.16.1-beta.tar.gz"
This needs to be a stable version before we can accept it (i.e. not `beta`).

2016-10-12 14:45 UTC, MikeMcQuaid requested changes

2016-10-12 14:45 UTC, MikeMcQuaid commented on Formula/snap-telemetry.rb
> +    assert_match version.to_s, shell_output("#{bin}/snapctl --version")
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2016-10-12 19:45 UTC, MikeMcQuaid commented on Formula/snap-telemetry.rb
> +  url "https://github.com/intelsdi-x/snap/archive/v0.16.1-beta.tar.gz"
Yeh, let's hold off for a non-beta e.g. 1.0.0.

2016-10-21 23:03 UTC, nanliu commented on Formula/snap-telemetry.rb
> +    assert_match version.to_s, shell_output("#{bin}/snapctl --version")
I've added some additional tests below.

2016-10-21 23:04 UTC, nanliu commented
This is updated to version 0.17.0, please review again.

2016-10-21 23:38 UTC, nanliu commented
Err, not sure what the test step is hanging on jenkins. Locally it runs fine:

```
$ brew test snap-telemetry --verbose
git config --file=/usr/local/Homebrew/.git/config --replace-all homebrew.devcmdrun true
Testing snap-telemetry
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161021-7563-qbkmp8.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/snap-telemetry.rb --verbose
==> /usr/local/Cellar/snap-telemetry/0.17.0/bin/snapd --version
==> /usr/local/Cellar/snap-telemetry/0.17.0/bin/snapctl --version
==> /usr/local/Cellar/snap-telemetry/0.17.0/bin/snapctl plugin list
==> /usr/local/Cellar/snap-telemetry/0.17.0/bin/snapctl task list
==> kill 7580
```

2016-10-23 11:30 UTC, MikeMcQuaid commented on Formula/snap-telemetry.rb
> +
May need a `sleep` here.

2016-10-23 11:31 UTC, MikeMcQuaid commented on Formula/snap-telemetry.rb
> +      Process.kill("TERM", snapd_pid)
Just use `Process.kill` and put the `fork` inside this `begin` to ensure it'll always be killed if the `assert` fails.

2016-10-24 16:26 UTC, nanliu commented
Yep, seems like it needed a short sleep for the daemon to startup. It's passing Jenkins successfully now.

2016-10-27 20:13 UTC, nanliu commented
Ping? Please review again.

2016-11-02 23:45 UTC, candysmurf commented
@MikeMcQuaid, if you have time to review this PR? Tomorrow is the last day of our sprint. It would be nice it's merged. thanks!

2016-11-03 01:27 UTC, MikeMcQuaid approved these changes

2016-11-03 01:43 UTC, MikeMcQuaid commented
@BrewTestBot test this please

2016-11-03 01:51 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-03 01:51 UTC, closed without merging