libosinfo require wget during build
Homebrew/homebrew-core pull request #58285
Opened 2020-07-20 23:04 UTC by jouve

in  build-aux/download_pci_ids:
```bash
#!/bin/sh

cd $MESON_BUILD_ROOT
wget -q -O pci.ids http://pciids.sourceforge.net/v2.2/pci.ids
```

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2020-07-21 05:49 UTC, iMichka commented
It's always bad when a library uses wget to download resources behind our back. Especially when there is no checksum check (or at least I do not see one in your explanation). So anything might get downloaded and poured to users computers. 

Can we use a resource block for this instead?

2020-07-21 07:29 UTC, SMillerDev requested changes
This needs to be downloaded in a resource block with a shasum.

2020-07-21 16:52 UTC, jouve commented
@iMichka @SMillerDev  then revert this formula to < 1.7 ?

2020-07-21 16:54 UTC, SMillerDev commented
That's not a solution, we still want the latest version. It just shouldn't be downloading using wget.

2020-07-21 17:01 UTC, jouve commented
I'll ty to have a look .

In the meantime, lets keep this broken package !

2020-07-21 23:03 UTC, alebcay commented
Adjusted the change to add `resource`s instead of new formulae.

2020-07-22 07:06 UTC, SMillerDev approved these changes
Thanks @jouve and @alebcay  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

2020-07-22 08:08 UTC, closed without merging