Patch the makefile for new OSX version
Homebrew/homebrew-core pull request #5855
Opened 2016-10-13 02:25 UTC by Moisan

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

Re-applied a [previous patch](https://github.com/Homebrew/legacy-homebrew/pull/42383) that I think had been removed when bumping the version. This also fixes the Sierra bottle issue #5488 for this formula.

2016-10-13 07:26 UTC, MikeMcQuaid requested changes

2016-10-13 07:26 UTC, MikeMcQuaid commented on Formula/chuck.rb
> +  patch :DATA
Can you please submit this patch to the upstream developers of this project and add a link to the upstream patch submission and explanation of why the patch is needed in a comment in the formula file. Thanks!

2016-10-18 21:07 UTC, Moisan commented
I also contacted the [dev mailing list](https://lists.cs.princeton.edu/mailman/listinfo/chuck-dev) with the patch.

2016-10-23 09:28 UTC, MikeMcQuaid requested changes

2016-10-23 09:28 UTC, MikeMcQuaid commented on Formula/chuck.rb
> +  # patch used to include new OSX version in the version check
`macOS`

2016-10-23 09:28 UTC, MikeMcQuaid commented on Formula/chuck.rb
> +  patch :DATA
Can you please submit add a link to the upstream patch submission and explanation of why the patch is needed in a comment in the formula file. Thanks!

Additionally, although we still want this upstream, an `inreplace` with `MacOS.version` may be a more future-proof version.

2016-11-05 01:28 UTC, Moisan commented
I submitted the patch to the [chuck-dev mailing list](https://lists.cs.princeton.edu/mailman/listinfo/chuck-dev). However since I'm not a member of the mailing list, my email is still waiting moderator approval.

2016-11-06 21:20 UTC, MikeMcQuaid approved these changes

2016-11-06 21:25 UTC, closed without merging

2016-11-06 21:25 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `chuck: patch the makefile for new macOS versions.`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!