MonetDB 11.23.13
Homebrew/homebrew-core pull request #5857
Opened 2016-10-13 07:49 UTC by monetdb-team

2016-10-13 09:01 UTC, MikeMcQuaid requested changes

2016-10-13 09:01 UTC, MikeMcQuaid commented on Formula/monetdb.rb
>    revision 1
This line needs removed (see `brew audit`: https://bot.brew.sh/job/Homebrew%20Core/9303/version=any_sierra/testReport/junit/brew-test-bot/sierra/audit_monetdb/)

2016-10-19 13:53 UTC, dunn commented
@MikeMcQuaid are you happy with the changes?

2016-10-19 13:54 UTC, MikeMcQuaid approved these changes

2016-10-19 14:04 UTC, closed without merging

2016-10-19 14:04 UTC, dunn commented
Thanks, @monetdb-team. Merged as f36506cd0983ea7762a234e3145f3e9253cb9e77.