workflows: add more on-schedule workflows
Homebrew/homebrew-core pull request #58710
Opened 2020-07-27 20:49 UTC by dawidd6

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR adds 2 new workflows running on schedule:
- Action to label pull requests, only those adding new formula for now
- Action to cancel previous workflow runs, so we don't have to do it manually and waste precious runners time

2020-07-27 20:53 UTC, SMillerDev commented on .github/workflows/autolabel.yml
> +                    "label": "new formula",
Can we also do `marked for removal`

2020-07-27 20:59 UTC, dawidd6 commented on .github/workflows/autolabel.yml
> +                    "label": "new formula",
Sure, added 👍

2020-07-27 21:04 UTC, SMillerDev submitted a review, later dismissed

2020-07-28 08:04 UTC, MikeMcQuaid submitted a review, later dismissed
Very nice 👏🏻

2020-07-28 08:05 UTC, jonchang approved these changes
Let's try it out!

2020-07-28 08:06 UTC, jonchang requested changes

2020-07-28 08:06 UTC, jonchang commented on .github/workflows/autocancel.yml
> +        uses: Homebrew/action/cancel-previous-runs@master
```suggestion
        uses: Homebrew/actions/cancel-previous-runs@master
```

2020-07-28 08:06 UTC, jonchang commented on .github/workflows/autolabel.yml
> +        uses: Homebrew/action/label-pull-requests@master
```suggestion
        uses: Homebrew/actions/label-pull-requests@master
```

2020-07-28 09:11 UTC, merged