Allow compilation of the Java wrapper for libjpeg-turbo
Homebrew/homebrew-core pull request #5881
Opened 2016-10-13 20:25 UTC by agarie

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

2016-10-14 15:43 UTC, MikeMcQuaid requested changes

2016-10-14 15:43 UTC, MikeMcQuaid commented on Formula/jpeg-turbo.rb
> +      args.push "--with-java"
`args << "--with-java" if build.with? "java"`

Also, does this require Java to be installed? If so, add a `depends_on :java` above.

2016-10-15 10:06 UTC, MikeMcQuaid requested changes

2016-10-15 10:06 UTC, MikeMcQuaid commented on Formula/jpeg-turbo.rb
> +  depends_on "java" if build.with? "java"
`depends_on :java => :optional`

2016-11-10 16:50 UTC, MikeMcQuaid commented
@agarie Any news on the comments above? Thanks!

2016-12-06 16:02 UTC, ilovezfs commented
@BrewTestBot test this please

2016-12-06 16:33 UTC, ilovezfs commented
@BrewTestBot test this please

2017-03-13 14:48 UTC, closed without merging