Add Minimesos v0.10.2
Homebrew/homebrew-core pull request #5889
Opened 2016-10-14 02:09 UTC by vlal

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

2016-10-14 15:47 UTC, MikeMcQuaid commented on Formula/minimesos.rb
> +    system "minimesos", "version"
Test is failing, seems to need `depends_on "docker"`: https://bot.brew.sh/job/Homebrew%20Core/9364/version=any_sierra/testReport/junit/brew-test-bot/sierra/test_minimesos/

Also, use `system "#{bin}/minimesos"`

2016-10-14 15:49 UTC, MikeMcQuaid requested changes

2016-10-14 15:49 UTC, MikeMcQuaid commented on Formula/minimesos.rb
> +  url "https://raw.githubusercontent.com/ContainerSolutions/minimesos/0.10.2/bin/minimesos"
Would be better to use `https://github.com/ContainerSolutions/minimesos/archive/0.10.2.tar.gz` and just `bin.install "bin/minimesos"` if needed.

2016-10-15 10:07 UTC, MikeMcQuaid requested changes

2016-10-15 10:07 UTC, MikeMcQuaid commented on Formula/minimesos.rb
> +    depends_on "docker"
Please just use `depends_on "docker"`. If you wish to use your own Docker please consider adding a `:docker`/`DockerRequirement` to Homebrew/brew.

2016-10-25 13:01 UTC, MikeMcQuaid requested changes

2016-10-25 13:01 UTC, MikeMcQuaid commented on Formula/minimesos.rb
> +    system "test -e #{bin}/minimesos && true || false"
Please run the executable and `assert_match` on the version or something, thanks.

2016-10-25 18:41 UTC, vlal commented on Formula/minimesos.rb
> +    system "test -e #{bin}/minimesos && true || false"
Apologies, I ran into issues trying that, minimesos requires not only the docker client but the docker server running as well. The `depends_on "docker"` only installs the client which is useless without the server. I tried going the docker-machine virtualbox route but that required virtualbox which is in homebrew-cask and which doesn't play nice within the confines of the test environment. Lastly I tried docker-machine-xhyve but that required root permission which wasn't a viable option either. Not sure what my next steps should be, should this be in homebrew-cask or is there another option?

2016-10-31 16:40 UTC, vlal commented on Formula/minimesos.rb
> +    system "test -e #{bin}/minimesos && true || false"
@MikeMcQuaid ping?

2016-10-31 22:18 UTC, MikeMcQuaid commented on Formula/minimesos.rb
> +    system "test -e #{bin}/minimesos && true || false"
I'm on vacation so my responses may take a while. `system "#{bin}/minimesos", "version"` doesn't work?

2016-10-31 22:50 UTC, MikeMcQuaid commented on Formula/minimesos.rb
> +    system "test -e #{bin}/minimesos && true || false"
`assert_match "minimesos", shell_output("#{bin}/minimesos --help")` should work. If not, assert_match "minimesos", shell_output("#{bin}/minimesos --help 2>&1") should.

2016-11-06 21:14 UTC, MikeMcQuaid requested changes

2016-11-06 21:14 UTC, MikeMcQuaid commented on Formula/minimesos.rb
> +    assert_match "Minimesos requires Docker 1.11.0 or higher", shell_output("#{bin}/minimesos")
Test is failing: https://bot.brew.sh/job/Homebrew%20Core/10466/version=any_sierra/testReport/junit/brew-test-bot/sierra/test_minimesos/

Perhaps just `assert_match "Docker", shell_output("#{bin}/minimesos 2>&1")` is the best bet?

2016-11-07 08:17 UTC, MikeMcQuaid requested changes

2016-11-07 08:17 UTC, MikeMcQuaid commented on Formula/minimesos.rb
> +    assert_match "Docker", shell_output("#{bin}/minimesos --help 2>&1")
`assert_match "Docker", shell_output("#{bin}/minimesos --help 2>&1", 125)` and we should be home free.

2016-11-10 16:53 UTC, MikeMcQuaid approved these changes

2016-11-10 17:17 UTC, merged

2016-11-10 17:17 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `minimesos 0.10.2 (new formula)`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!