xcenv 1.1.0
Homebrew/homebrew-core pull request #5925
Opened 2016-10-15 01:12 UTC by maschall

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

2016-10-15 10:09 UTC, MikeMcQuaid requested changes

2016-10-15 10:09 UTC, MikeMcQuaid commented on Formula/xcenv.rb
> +      xcenv init
Please remove these `caveats` as this is not Homebrew-specific information. Thanks!

2016-10-15 16:04 UTC, MikeMcQuaid commented
Looks like the `post_install` is failing: https://bot.brew.sh/job/Homebrew%20Core/9475/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install___xcenv_1_1_0_el_capitan_bottle_tar_gz/

2016-10-16 01:39 UTC, maschall commented
@MikeMcQuaid thanks for the reviews, I didnt realize that formula shouldn't really have post install instructions.  So I removed the caveats like you suggested and updated the website.  Thansk agin.

2016-10-16 13:20 UTC, MikeMcQuaid approved these changes

2016-10-16 13:24 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-10-16 13:24 UTC, closed without merging