Update ooniprobe homebrew formula to 2.0.0
Homebrew/homebrew-core pull request #5950
Opened 2016-10-15 19:09 UTC by hellais

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-10-16 20:34 UTC, hellais commented
Ok, now tests are all green 🍏

2016-10-17 08:02 UTC, MikeMcQuaid requested changes

2016-10-17 08:02 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
>      EOS
A similar message will be automaticaly printed for `services` stuff and the rest of the caveats can be removed.

2016-10-17 08:02 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> +    bin.env_script_all_files(libexec/"bin", :PYTHONPATH => ENV["PYTHONPATH"], :PATH => ENV["PATH"])
Can you elaborate on why the PATH is needed?

2016-10-17 08:02 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> -
Please re-add this whitespace.

2016-10-17 08:02 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> +    ENV.prepend_create_path "PATH", "#{HOMEBREW_PREFIX}/bin"
It seems like it should be configured to do this in the plist and use `"#{HOMEBREW_PREFIX}/opt/tor/bin"`.

2016-10-17 08:02 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> +    (var/"run/ooni/initialized").write "" unless is_initialized
Need to use a directory outside `var` for this testing i.e. in `testpath`.

2016-10-17 08:08 UTC, hellais commented on Formula/ooniprobe.rb
> +    bin.env_script_all_files(libexec/"bin", :PYTHONPATH => ENV["PYTHONPATH"], :PATH => ENV["PATH"])
It's explained in the comment above. Basically without setting the PATH inside of the homebrew generated script that wraps the execution of the python script, PATH (when running the plist) doesn't contain the homebrew path of commands.

2016-10-17 08:11 UTC, hellais commented on Formula/ooniprobe.rb
> +    (var/"run/ooni/initialized").write "" unless is_initialized
OK I will think of some way to overcome this and generate a configuration file specific for testing.

2016-10-17 08:16 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> +    ENV.prepend_create_path "PATH", "#{HOMEBREW_PREFIX}/bin"
We need to figure out some solution to that, then, because we can't embed the current user's and/or Homebrew PATH inside the env script.

2016-10-17 08:16 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> +    (var/"run/ooni/initialized").write "" unless is_initialized
Thanks!

2016-10-17 08:29 UTC, hellais commented on Formula/ooniprobe.rb
> +    ENV.prepend_create_path "PATH", "#{HOMEBREW_PREFIX}/bin"
Would it be ok if I were to create a wrapper script that is used just in the context of the plist that injects the correct PATH vars?

2016-10-30 15:21 UTC, dunn commented
Just two formatting errors; you can use `brew style --fix ooniprobe` to automatically correct them:
```
C:257:  9: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
C:259:  1: Extra empty line detected at block body end.

2016-10-30 17:03 UTC, hellais commented
> Just two formatting errors; you can use brew style --fix ooniprobe to automatically correct them.

'ight. Fixed, thanks!

2016-11-06 20:55 UTC, MikeMcQuaid requested changes

2016-11-06 20:55 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
>      EOS
We'll consider a PR to Homebrew/brew to amend these messages but you need to remove them from here for now, thanks.

2016-11-08 08:53 UTC, hellais commented on Formula/ooniprobe.rb
>      EOS
Can I leave the message with information on how to access the web UI, but just drop the ones regarding the services? Is there some better way to give users post installation instructions?

2016-11-08 08:57 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
>      EOS
There instructions should be for things that every user needs to know and are Homebrew specific. Remember that in e.g. Debian no post-installation instructions are printed or deemed necessary.

2016-11-08 16:06 UTC, MikeMcQuaid commented
> Conflicting files
> Formula/ooniprobe.rb

This will need to be resolved.

2016-12-06 16:01 UTC, ilovezfs commented
@BrewTestBot test this please

2016-12-06 16:31 UTC, ilovezfs commented
@BrewTestBot test this please

2016-12-07 15:24 UTC, hellais commented
I am going to close this PR and submit another one for the recently released 2.1.0.

2016-12-07 15:35 UTC, MikeMcQuaid commented
Just push to this PR instead, thanks.

2016-12-07 16:49 UTC, hellais commented
Ah ok (sorry for the double closing).

2016-12-07 21:54 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> +       <string>#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
Why is this change needed, out of interest?

2016-12-07 21:54 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> +       <true/>
Why is this change needed, out of interest?

2016-12-07 21:54 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> -       <string>/dev/null</string>
Where are these logged now?

2016-12-08 10:46 UTC, hellais commented on Formula/ooniprobe.rb
> +       <string>#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
On my version of macOS (Sierra) it appears that the PATH does not include the `HOMEBREW_PREFIX` path when starting programs via launchd. This is to ensure the HOMEBREW_PREFIX is present in there.

2016-12-08 10:51 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> +       <string>#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
Is `ooniprobe` calling other things in the prefix? If so: do you know what? Thanks!

2016-12-08 10:51 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> +       <true/>
Cool, thanks for explaining.

2016-12-08 10:55 UTC, hellais commented on Formula/ooniprobe.rb
> -       <string>/dev/null</string>
I was under the impression that not supplying a path would make the default be to not log, but I checked and it seems like this leads to them being logged.

I will add these back.

2016-12-08 10:59 UTC, hellais commented on Formula/ooniprobe.rb
> +       <string>#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
Off the top of my head I think the only other thing it's calling in the HOMEBREW_PREFIX is `tor`.

2016-12-08 18:02 UTC, hellais commented
Why is the build still pending?

2016-12-08 18:03 UTC, hellais commented
@BrewTestBot test this please

2016-12-08 18:12 UTC, dunn commented
@BrewTestBot test this please

2016-12-08 18:12 UTC, dunn commented
(That command only works for maintainers)

2016-12-10 13:30 UTC, MikeMcQuaid requested changes

2016-12-10 13:30 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> +       <string>#{var}/log/</string>
Can you make this something specific to this formula e.g. `prefix` so it doesn't put random files in there? Thanks!

2016-12-10 13:31 UTC, MikeMcQuaid commented on Formula/ooniprobe.rb
> +       <string>#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
It may be worth adding tor's `opt_bin` in here instead but I don't have strong feelings either way.

2016-12-12 11:17 UTC, hellais commented on Formula/ooniprobe.rb
> +       <string>#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
Ok I will leave as is for the moment as this has been tested and works as expected.

2016-12-15 12:47 UTC, hellais commented
Can the CI tests be restarted? I suspect the failure is only a temporary one and may not happen on a restart.

2016-12-18 22:24 UTC, MikeMcQuaid commented
@hellais done.

2016-12-29 11:58 UTC, MikeMcQuaid approved these changes

2016-12-29 12:04 UTC, MikeMcQuaid commented
@BrewTestBot test this please

2016-12-30 07:15 UTC, dunn commented
This is weird:
```
        Error: ooniprobe contains conflicting version dependencies (openssl@1.1 openssl) so cannot be installed
```
Does it just need to be rebased?

2016-12-30 15:56 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `ooniprobe 2.1.0`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

2016-12-30 15:57 UTC, closed without merging