Fix makecert binary name
Homebrew/homebrew-core pull request #5958
Opened 2016-10-16 03:36 UTC by gwerbin

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

It's a known issue that CZMQ and Mono conflict because of the `makecert` binary. In https://github.com/zeromq/czmq/issues/1038 I was told that it won't break anything to rename `makecert` to `zmakecert`, and that in fact this change is already planned for a future release. With that in mind, I'm making this change now to mitigate my own (and hopefully others') frustration, especially since both formulas could be low-devel dependences for a variety of programs.

2016-10-17 07:55 UTC, MikeMcQuaid requested changes

2016-10-17 07:55 UTC, MikeMcQuaid commented on Formula/czmq.rb
> +      This change will eventually be incorporated into a future CZMQ release. See https://github.com/zeromq/czmq/issues/1038 for more details.
Can you wrap this message ensuring no more than 80 characters are output on a line? Thanks! I also think the second line can be a comment in the formula above and not printing as a caveat.

2016-11-10 16:53 UTC, MikeMcQuaid commented
@gwerbin Any news on the comment? Thanks!

2016-11-12 18:47 UTC, gwerbin commented
Apologies! I had almost forgotten about this.

2016-11-12 18:56 UTC, gwerbin commented
@MikeMcQuaid Looks ok?

2016-11-13 10:52 UTC, MikeMcQuaid requested changes

2016-11-13 10:52 UTC, MikeMcQuaid commented on Formula/czmq.rb
> +  end
Let's avoid the caveats, I don't think they are necessary here, thanks.

2016-11-13 10:52 UTC, MikeMcQuaid commented
A style tweak to update too: https://bot.brew.sh/job/Homebrew%20Core/11310/version=any_sierra/testReport/junit/brew-test-bot/sierra/style_czmq/

2016-11-13 16:12 UTC, MikeMcQuaid approved these changes

2016-11-13 16:48 UTC, MikeMcQuaid commented
Install failing on 10.12: https://bot.brew.sh/job/Homebrew%20Core/11340/version=any_sierra/testReport/junit/brew-test-bot/sierra/install_czmq/

2016-11-13 22:09 UTC, gwerbin commented
Strange. That look like an upstream issue. I'll ping the CZMQ folks about it.

2016-11-13 23:58 UTC, gwerbin commented
As per https://github.com/zeromq/czmq/issues/1038#issuecomment-260216805 this change is unnecessary if we bump the version to 4.0.0 or 4.0.1. Unfortunately I have no idea how bottling works so I'm going to have to pass on doing it myself.

2016-11-13 23:58 UTC, closed without merging

2016-11-14 08:04 UTC, MikeMcQuaid commented
@gwerbin You don't need to know how bottling works, it's done automatically. Just update the `url` and `sha256` and create a new PR and that's enough.

2016-11-14 12:24 UTC, ilovezfs commented
@MikeMcQuaid we actually already have a PR for the new czmq: https://github.com/Homebrew/homebrew-core/pull/6638

2016-11-15 09:10 UTC, MikeMcQuaid commented
@ilovezfs Thanks!