csound 6.15.0
Homebrew/homebrew-core pull request #59618
Opened 2020-08-13 23:26 UTC by chenrui333

Created with `brew bump-formula-pr`.

2020-08-14 02:20 UTC, Moisan requested changes

2020-08-14 02:20 UTC, Moisan commented on Formula/csound.rb
>    license "LGPL-2.1"
```suggestion
  license "LGPL-2.1-or-later"
```

2020-08-14 07:21 UTC, SMillerDev approved these changes

2020-08-14 09:38 UTC, dawidd6 approved these changes

2020-08-15 17:51 UTC, Moisan approved these changes

2020-08-15 18:13 UTC, closed without merging