gdk-pixbuf: expose additional configure flags
Homebrew/homebrew-core pull request #5981
Opened 2016-10-16 18:52 UTC by lovell

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Hello, this PR exposes a couple of gdk-pixbuf's existing and useful configure flags:

* `--disable-modules`, also exposed as the more homebrew-like `--without-modules`, to prevent the use dynamically-loaded image format modules at runtime.

* `--with-included-loaders=`, a comma separated list of image format loaders to "statically" include in the dylib, e.g. `--with-included-loaders="png,jpeg"`.

2016-10-16 18:58 UTC, bfontaine commented on Formula/gdk-pixbuf.rb
> +  deprecated_option "disable-modules" => "without-modules"
`deprecated_option` is for options that existed at some point, which is not the case here.

2016-10-16 19:10 UTC, lovell commented on Formula/gdk-pixbuf.rb
> +  deprecated_option "disable-modules" => "without-modules"
Given the underlying configure flag is named `--disable-modules`, would the expectation be to map it to `--without-modules` or expose it as-is?

2016-10-16 19:38 UTC, bfontaine commented on Formula/gdk-pixbuf.rb
> +  deprecated_option "disable-modules" => "without-modules"
We use `--with-*`/`--without-*`.

2016-10-17 13:36 UTC, MikeMcQuaid requested changes

2016-10-17 13:36 UTC, MikeMcQuaid commented on Formula/gdk-pixbuf.rb
> +      args << "--with-included-loaders=" + included_loaders
`args << "--with-included-loaders=#{included_loaders}" if included_loaders`

2016-10-19 02:17 UTC, dunn commented
The test is failing, and there are a few audit failures:
```
Error: 3 problems in 1 formula
xcbuild:
  * Non-executables were installed to "/usr/local/Cellar/xcbuild/0.1.0/bin"
    The offending files are:
      /usr/local/Cellar/xcbuild/0.1.0/bin/Library
      /usr/local/Cellar/xcbuild/0.1.0/bin/usr
  * The installation was broken.
    Broken dylib links found:
      /usr/lib/libcompression.dylib
  * C: 14: col 5: Missing space after #.

2016-10-20 11:26 UTC, lovell commented
Hello, I believe this PR has been fully updated with all the feedback, but please do let me know if not. Thanks!

2016-10-23 09:32 UTC, MikeMcQuaid approved these changes

2016-10-23 09:55 UTC, merged

2016-10-23 09:55 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!