locateme v0.2.1 (new formula)
Homebrew/homebrew-core pull request #5987
Opened 2016-10-16 23:56 UTC by beaumartinez

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I did this originally on Homebrew-Cask but it was [rejected](https://github.com/caskroom/homebrew-cask/pull/25557) there. Hope this is where it belongs.

I hope this is all OK. Pushing this just before bed! ✌️

LocateMe is a nice, succinct command line tool to get your location from the built-in Mac services. It allows you to specify the format you want it in, not like other tools, so is especially handy if you're piping it.

2016-10-17 00:24 UTC, zmwangx requested changes

2016-10-17 00:24 UTC, zmwangx commented on Formula/locateme.rb
> +    bin.install "LocateMe"
We do not allow compiled binaries. You need to build it from source.

2016-10-17 00:42 UTC, beaumartinez commented
@zmwangx Pushed a change—I've never compiled Objective-C before, so I hope the way I'm doing it is OK.

2016-10-17 07:13 UTC, MikeMcQuaid commented
@beaumartinez I was under the impression this required a signed binary to function; can you confirm if that's the case i.e. does the `brew install`d version work on your machine?

2016-10-17 07:52 UTC, jawshooah commented
@MikeMcQuaid seems to work for me:

```bash
$ brew install --verbose --debug locateme
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/locateme.rb
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161017-26111-1o817tt.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/locateme.rb --verbose --debug
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/locateme.rb
==> Downloading https://downloads.sourceforge.net/project/iharder/locateme/LocateMe-v0.2.1.zip
==> Downloading from http://heanet.dl.sourceforge.net/project/iharder/locateme/LocateMe-v0.2.1.zip
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.0.7-83-g2674bfa (Macintosh; Intel macOS 10.11.6) curl/7.43.0 http://heanet.dl.sourceforge.net/project/iharder/locateme/LocateMe-v0.2.1.zip -C 0 -o /Users/jhagins/Library/Caches/Homebrew/locateme-0.2.1.zip.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33871  100 33871    0     0  77612      0 --:--:-- --:--:-- --:--:-- 77864
==> Verifying locateme-0.2.1.zip checksum
unzip -qq /Users/jhagins/Library/Caches/Homebrew/locateme-0.2.1.zip
==> clang -framework Foundation -framework CoreLocation LocateMe.m -o LocateMe
==> Cleaning
Fixing /usr/local/Cellar/locateme/0.2.1/bin/LocateMe permissions from 755 to 555
==> Finishing up
ln -s ../Cellar/locateme/0.2.1/bin/LocateMe LocateMe
==> Summary
🍺  /usr/local/Cellar/locateme/0.2.1: 4 files, 30.3K, built in 9 seconds

$ LocateMe
<REDACTED> +/- 65.00m (speed -1.00 mps / course -1.00) @ 10/17/16, 3:48:02 AM Eastern Daylight Time
```

Though the OS does prompt me to grant the permission to access my current location the first time I run it:

<img width="456" alt="screen shot 2016-10-17 at 3 46 53 am" src="https://cloud.githubusercontent.com/assets/4551271/19429327/1b01ef3c-941d-11e6-8bcc-aad20d0ecf40.png">

2016-10-17 07:53 UTC, ilovezfs commented
Is that Sierra?

2016-10-17 07:54 UTC, jawshooah commented
@ilovezfs Ah, nope, El Capitan. Sorry, I've got 4am brain :stuck_out_tongue_closed_eyes:

2016-10-17 08:19 UTC, MikeMcQuaid requested changes

2016-10-17 08:19 UTC, MikeMcQuaid commented on Formula/locateme.rb
> +    system "LocateMe", "-h"
`system "#{bin}/LocateMe", "-h"`

2016-10-17 08:19 UTC, MikeMcQuaid commented
Confirmed working on Sierra 👍

2016-10-17 12:19 UTC, zmwangx requested changes

2016-10-17 12:19 UTC, zmwangx commented on Formula/locateme.rb
> +    bin.install "LocateMe"
Add `man1.install "LocateMe.1"` to install the man page.

2016-10-17 18:35 UTC, beaumartinez commented
Added the manpage @zmwangx .

2016-10-17 21:46 UTC, zmwangx approved these changes

2016-10-19 09:26 UTC, beaumartinez commented
@MikeMcQuaid any update on this? I've done the changes as requested.

2016-10-19 17:38 UTC, MikeMcQuaid approved these changes

2016-10-19 17:57 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-10-19 17:57 UTC, closed without merging