aurora 1.2 (new formula)
Homebrew/homebrew-core pull request #6001
Opened 2016-10-17 08:30 UTC by Luxurioust

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
aurorais a Beanstalkd queue server console. please help me to add this app to Homebrew, thanks a lot.

2016-10-17 12:55 UTC, zmwangx requested changes

2016-10-17 12:55 UTC, zmwangx commented on Formula/aurora.rb
> +    bin.install "aurora"
Need to build from source rather than download a precompiled binary.

2016-10-17 12:57 UTC, zmwangx commented
Also, repository is too new, need to wait until the 30 day threshold.

2016-10-17 13:25 UTC, MikeMcQuaid commented
I'm fine with including it early given it's popular enough.

2016-10-19 02:19 UTC, dunn commented
Here's how the test is failing:
```
==> aurora
To view beanstalk console open http://127.0.0.1:3000 in browser
Error: aurora: failed
execution expired

2016-10-19 02:20 UTC, dunn commented
I'd try to update the test to ping the server with curl then kill it, like in [`algernon.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/algernon.rb)
.

2016-11-09 03:57 UTC, Luxurioust commented
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
---

aurorais a Beanstalkd queue server console. please help me to add this app to Homebrew, thanks a lot.

2016-11-09 04:00 UTC, closed without merging