aurora-cli 0.16.0 update
Homebrew/homebrew-core pull request #6006
Opened 2016-10-17 10:45 UTC by thinker0

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-10-17 13:38 UTC, MikeMcQuaid approved these changes

2016-10-17 13:38 UTC, MikeMcQuaid commented on Formula/aurora-cli.rb
> -  depends_on :java => "1.8+"
This no longer uses Java?

2016-10-17 13:38 UTC, MikeMcQuaid commented on Formula/aurora-cli.rb
> +  patch :DATA
Can you please submit this patch to the upstream developers of this project and add a link to the upstream patch submission and explanation of why the patch is needed in a comment in the formula file. Thanks!

2016-10-17 13:39 UTC, MikeMcQuaid requested changes
Sorry, wrong change

2016-10-17 13:39 UTC, MikeMcQuaid commented on Formula/aurora-cli.rb
> +  patch :DATA
This looks like it may be done without a patch.

2016-10-17 13:55 UTC, thinker0 commented on Formula/aurora-cli.rb
> -  depends_on :java => "1.8+"
Aurora CLI only Python

2016-10-17 13:59 UTC, thinker0 commented on Formula/aurora-cli.rb
> +  patch :DATA
https://github.com/apache/aurora/commit/b272b8808c5d9832112bfd9b648e0ec8b9718414

2016-10-17 15:03 UTC, thinker0 commented on Formula/aurora-cli.rb
> +  patch :DATA
This means you must enter information.


```
thinker0-iMac:Formula thinker0$ brew reinstall aurora-cli
==> Reinstalling aurora-cli
==> Using the sandbox
==> Downloading https://www.apache.org/dyn/closer.cgi?path=/aurora/0.16.0/apache-aurora-0.16.0.tar.gz
==> Best Mirror http://mirror.apache-kr.org/aurora/0.16.0/apache-aurora-0.16.0.tar.gz
######################################################################## 100.0%
==> ./pants binary src/main/python/apache/aurora/kerberos:kaurora
Last 15 lines from /Users/thinker0/Library/Logs/Homebrew/aurora-cli/01.pants:
23:59:14 00:00     [parse]fatal: Not a git repository (or any of the parent directories): .git

               Executing tasks in goals: binary
23:59:15 00:01   [binary]
23:59:15 00:01     [binary-prep-command]
23:59:15 00:01     [python-binary-create]
23:59:15 00:01       [cache]
                   No cached artifacts for 1 target.
                   Invalidated 1 target.
23:59:20 00:06       [chroot]
FAILURE: Update --binaries-path-by-id to find binaries for Darwin x86_64 16.0.0.


23:59:20 00:06   [complete]
               FAILURE

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

```

2016-10-18 13:11 UTC, thinker0 commented
@MikeMcQuaid double check sierre Mac OS

2016-10-23 11:25 UTC, MikeMcQuaid commented
Does:
```
patch do
  url "https://github.com/apache/aurora/commit/b272b880.patch"
  sha256 ...
end
```

work instead? Additionally, please add a Ruby comment explaining why the patch is needed (not just the URL). Thanks!

2016-10-24 14:34 UTC, nijikon commented
You are awesome, thanks for your contribution! :tada:

2016-10-24 14:34 UTC, closed without merging

2016-10-24 14:39 UTC, thinker0 commented
Thanks ^^