zyre 1.2.0 (new formula)
Homebrew/homebrew-core pull request #6022
Opened 2016-10-17 20:06 UTC by colstrom

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Adds formula for current stable release of zyre, a library for
reliable group messaging over local area networks.

2016-10-19 02:15 UTC, dunn commented
The test is failing:
```
==> zpinger
dyld: lazy symbol binding failed: Symbol not found: _zsys_ipv6
  Referenced from: /usr/local/Cellar/zyre/1.2.0/lib/libzyre.1.dylib
  Expected in: flat namespace

dyld: Symbol not found: _zsys_ipv6
  Referenced from: /usr/local/Cellar/zyre/1.2.0/lib/libzyre.1.dylib
  Expected in: flat namespace

2016-10-19 08:16 UTC, mrusme commented
Ran `brew install "https://raw.githubusercontent.com/colstrom/homebrew-core/58f635f10041ae81f861604754be659d1f5faa86/Formula/zyre.rb"` locally, which succeeded. Thank you btw for this! 👍

2016-11-10 09:07 UTC, bfontaine requested changes

2016-11-10 09:07 UTC, bfontaine commented on Formula/zyre.rb
> +    system "zpinger"
Please use the full path to the executable: `system bin/"zpinger"`.

2016-11-27 01:39 UTC, woodruffw commented
Closing due to inactivity.

2016-11-27 01:39 UTC, closed without merging