black 20.8b1
Homebrew/homebrew-core pull request #60476
Opened 2020-09-01 11:19 UTC by mariosnikolaou

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2020-09-01 12:21 UTC, bayandin requested changes

2020-09-01 12:21 UTC, bayandin commented on Formula/black.rb
> +  revision 4
```suggestion
```

2020-09-01 14:39 UTC, mariosnikolaou commented on Formula/black.rb
> +  revision 4
Done.

2020-09-01 15:49 UTC, bayandin commented
Could you please also update resources and squash all the commits into a single one with message `black 20.8b1`

2020-09-01 16:57 UTC, mariosnikolaou commented
Updated resources and squashed commits. PTAL, thanks.

2020-09-01 17:41 UTC, dawidd6 approved these changes

2020-09-02 09:35 UTC, bayandin approved these changes
Thank you @mariosnikolaou!

2020-09-02 10:15 UTC, closed without merging