Bump sfk to version 1.8.1
Homebrew/homebrew-core pull request #6064
Opened 2016-10-18 21:41 UTC by Moisan

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Bump `sfk` to version 1.8.1. This also solves the Sierra bottle issue #5488 for this formula.

2016-10-23 09:34 UTC, MikeMcQuaid requested changes

2016-10-23 09:34 UTC, MikeMcQuaid commented on Formula/sfk.rb
> +    chmod 0755, "install-sh"
Cool. Can you please submit this as a bug to the upstream developers of this project and add a link to the upstream bug submission and explanation of why the chmod is needed in a comment in the formula file. Thanks!

2016-10-24 19:05 UTC, Moisan commented
Turns out, sfk [released version 1.8.1.4](https://sourceforge.net/p/swissfileknife/news/2016/10/swiss-file-knife-1814-update/) but their filenames are not updated, only the source code. Hence the sha256 failed.

2016-10-25 21:10 UTC, zmwangx commented
We should politely ask them to not do that.

2016-10-25 21:11 UTC, zmwangx commented on Formula/sfk.rb
> +    chmod 0755, "install-sh"
`install-sh` should be installed by automake. They must have messed up.

2016-10-25 21:12 UTC, zmwangx commented on Formula/sfk.rb
> +    chmod 0755, "install-sh"
Okay, it seems that the latest tarball doesn't have this problem.

2016-10-31 13:22 UTC, Moisan commented
@zmwangx [I opened a ticket upstream.](https://sourceforge.net/p/swissfileknife/bugs/45/)

2016-11-03 20:08 UTC, Moisan commented
Upstream have responded to my ticket that 1.8.1 is in fact HEAD. The latest stable release is then 1.8.0. I switched to this version in the Formula.

2016-11-06 15:19 UTC, dunn commented
Thanks! Would you mind squashing this down to a single commit?

2016-11-26 15:32 UTC, MikeMcQuaid approved these changes

2016-11-26 15:33 UTC, MikeMcQuaid commented
@BrewTestBot test this please

2016-11-26 16:12 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-26 16:12 UTC, closed without merging