apache-drill: update livecheck
Homebrew/homebrew-core pull request #60739
Opened 2020-09-07 00:44 UTC by chenrui333

Currently, the `brew livecheck` checks against Apache ftp server, but it is not an accurate tracking for the release.

This PR is to update the tracking to check against the homepage. 

---

relates to #60732

2020-09-07 00:54 UTC, nandahkrishna commented
I read @issyl0's comment in the PR you referenced, but I'm just concerned they haven't added the release note _yet_ – 1.18 released on 4 September 2020 so it may well be that they just haven't gotten around to creating the release note. Does that seem valid?

2020-09-07 01:40 UTC, samford requested changes, later dismissed
It _is_ strange that version 1.18 is available for download and has also been released on GitHub but hasn't been announced. However, I know this has happened with other formulae before as well, so it's not unheard of. There are times where the release artifacts are published but the release isn't official until there's an announcement on the first-party website (or the download links are referenced there). In those cases, we make sure to check the first-party website, so that livecheck doesn't report a new version until it's official.

It's hard to say for sure but this may be another one of those cases. I'm in favor of checking the first-party download page here and we can always modify this again if it doesn't turn out to be the correct decision.

That said, I would modify the regex to match against the tarball links on the downloads page instead, as that may be more reliable than the "Drill 1.17 was released" text.

2020-09-07 01:40 UTC, samford commented on Formula/apache-drill.rb
> +    regex(/Drill v?(\d+(?:\.\d+)+) was released/i)
```suggestion
    /href=.*?apache-drill[._-]v?(\d+(?:\.\d+)+)\.t/i
```

2020-09-07 02:52 UTC, chenrui333 commented
Yeah, I am surprised as well, but just to be cautious with this.

This actually happened with `clojure` recently too.

2020-09-07 05:37 UTC, SMillerDev commented
We _could_ just ask upstream if it's officially released and if it's going to be on the website.

2020-09-21 14:12 UTC, chenrui333 commented
go for the merge? looks like the 1.18 release still did not get announced yet.

2020-09-21 14:13 UTC, SMillerDev commented
Did we ask upstream?

2020-09-21 14:16 UTC, chenrui333 commented
not quite yet, let me do it now.

2020-09-23 15:43 UTC, nandahkrishna commented
Luckily for us, someone seems to have asked upstream about the same thing [here](http://mail-archives.apache.org/mod_mbox/drill-user/202009.mbox/%3cCANxXE_+5+2dDBSnECr2LGFD-rh63aVGCiyKk+E4=641gttD_iw@mail.gmail.com%3e). Apparently everything except the release notes are done.

2020-10-01 17:13 UTC, SMillerDev approved these changes

2020-10-02 14:15 UTC, merged

2020-10-02 14:16 UTC, chenrui333 commented
surprisingly, apache-drill still did not get a chance to write the release blog.