fly 2.3.1 (new formula)
Homebrew/homebrew-core pull request #6098
Opened 2016-10-19 20:42 UTC by a1dutch

- [Y] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [Y] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [Y] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [Y] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This pull request, enables the concourse (https://concourse.ci) fly cli

2016-10-19 20:59 UTC, bfontaine requested changes

2016-10-19 20:59 UTC, bfontaine commented on Formula/fly.rb
> +  url "https://github.com/concourse/concourse/releases/download/v2.3.1/fly_darwin_amd64"
We need to build from source.

2016-10-19 20:59 UTC, bfontaine commented on Formula/fly.rb
> +    system "#{bin}/fly", "help"
Can’t we write a test that does something more substantial than e.g. `help` or `version`?

2016-10-19 20:59 UTC, bfontaine commented on Formula/fly.rb
> +  desc "Concourse fly cli"
`"Command line interface to Concourse"` might be more descriptive.

2016-10-19 21:43 UTC, a1dutch commented on Formula/fly.rb
> +  desc "Concourse fly cli"
👍

2016-10-19 21:57 UTC, bfontaine commented on Formula/fly.rb
> +  url "https://github.com/concourse/concourse/releases/download/v2.3.1/fly_darwin_amd64"
> it doesn't have a tagged release with the source

The last one is here: https://github.com/concourse/concourse/archive/v2.3.1.tar.gz

> and also uses direnv

`direnv` is available in Homebrew Core. You can add it as a dependency.

2016-10-19 21:59 UTC, bfontaine commented on Formula/fly.rb
> +    system "#{bin}/fly", "help"
I mean a test that actually does something; not one that just prints the current version or the help.

2016-10-19 22:24 UTC, a1dutch commented on Formula/fly.rb
> +  url "https://github.com/concourse/concourse/releases/download/v2.3.1/fly_darwin_amd64"
The source for fly isn't in that archive, as its a git submodule.

2016-10-19 22:26 UTC, a1dutch commented
@bfontaine thanks for your help/time but i will just close this pull request and open one for the caskroom at a later date.

2016-10-20 07:40 UTC, MikeMcQuaid commented on Formula/fly.rb
> +  url "https://github.com/concourse/concourse/releases/download/v2.3.1/fly_darwin_amd64"
@a1dutch You can use a Git checkout with the Homebrew formula, too.

2016-10-20 07:54 UTC, a1dutch commented
I have managed to change it to build from the source, but the submodules (including fly) are building from the head and not the released version, not sure how to fix this, any ideas?

Regarding the test, only thing we can use is `fly help` or `fly --version`

2016-10-23 09:32 UTC, MikeMcQuaid requested changes

2016-10-23 09:32 UTC, MikeMcQuaid commented on Formula/fly.rb
> +  bottle :unneeded
We want a bottle for a `go` application.

2016-10-23 09:32 UTC, MikeMcQuaid commented on Formula/fly.rb
> +  depends_on "go"
`depends_on "go" => :build`

2016-10-23 09:32 UTC, MikeMcQuaid commented on Formula/fly.rb
> +    cd "src/github.com/concourse/fly" do
`cd "src/github.com/concourse/fly"` and then skip the `do`, `end` and indentation.

2016-10-23 09:32 UTC, MikeMcQuaid commented on Formula/fly.rb
> +    system "#{bin}/fly", "help"
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2016-11-10 10:02 UTC, bfontaine commented
Ping re Mike’s comments above?

2016-11-27 01:44 UTC, woodruffw commented
Closing due to inactivity.

2016-11-27 01:44 UTC, closed without merging