New Formula: Inspectrum 0.1.1
Homebrew/homebrew-core pull request #6146
Opened 2016-10-21 15:15 UTC by tduehr

- [Y ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ Y] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ Y] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ Y] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-10-23 11:27 UTC, MikeMcQuaid requested changes

2016-10-23 11:27 UTC, MikeMcQuaid commented on Formula/inspectrum.rb
> +    system "inspectrum -h"
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2016-10-24 15:30 UTC, tduehr commented on Formula/inspectrum.rb
> +    system "inspectrum -h"
not really...

`-h` does at least initialize parts of the gui...

~~~
Usage: inspectrum [options] file
spectrum viewer

Options:
  -h, --help       Displays this help.
  -r, --rate <Hz>  Set sample rate.

Arguments:
  file             File to view.
~~~

2016-11-06 18:10 UTC, MikeMcQuaid commented on Formula/inspectrum.rb
> +    system "inspectrum -h"
Ok, that's fine. Please do `system "#{bin}/inspectrum", "-h"`.

2016-11-09 11:59 UTC, MikeMcQuaid requested changes

2016-11-09 11:59 UTC, MikeMcQuaid commented on Formula/inspectrum.rb
> +  depends_on "liquid-dsp"
`Error: No available formula with the name "liquid-dsp"`

2016-11-17 17:31 UTC, tduehr commented on Formula/inspectrum.rb
> +  depends_on "liquid-dsp"
I forgot that's a tap dependency. https://github.com/dholm/homebrew-sdr/blob/master/liquid-dsp.rb

2016-11-20 10:33 UTC, MikeMcQuaid requested changes

2016-11-20 10:33 UTC, MikeMcQuaid commented on Formula/inspectrum.rb
> +  depends_on "dholm/sdr/liquid-dsp"
Sorry, we don't want homebrew/core formulae to depend on non-homebrew/core formulae so we'll need `liquid-dsp` to get included first. This was blocked on them making a new stable release: https://github.com/Homebrew/homebrew-core/pull/2664

2016-11-21 15:03 UTC, tduehr commented
Okay, I'll submit that too.

2016-11-21 15:05 UTC, MikeMcQuaid commented
@tduehr We need them to release a new stable release first. Please discuss this with upstream before opening a PR here, thanks.

2017-02-13 01:15 UTC, woodruffw commented
Closing due to inactivity/need for upstream release.

2017-02-13 01:15 UTC, closed without merging