wdc 1.0.0 (new formula)
Homebrew/homebrew-core pull request #6150
Opened 2016-10-21 17:18 UTC by designerror

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-10-21 17:50 UTC, mistydemeo submitted a review, later dismissed

2016-10-21 19:30 UTC, designerror commented on Formula/wdc.rb
> +    system "true"
I added test.

2016-10-22 12:33 UTC, designerror commented
Fixed test for `linuxbrew` on Ubuntu.

2016-10-23 11:34 UTC, MikeMcQuaid requested changes

2016-10-23 11:34 UTC, MikeMcQuaid commented on Formula/wdc.rb
> +  depends_on "curl"
Can this not use the system version?

2016-10-23 11:34 UTC, MikeMcQuaid commented on Formula/wdc.rb
> +    system ENV.cc, "test.cpp", "-L#{lib}", "-lwebdavclient", "-lpthread", "-lpugixml", "-lm", "-lcurl", "-lssl", "-lcrypto", "-lstdc++", "-std=c++11", "-o", "test"
Please split this onto multiple lines at 80 characters.

2016-10-23 16:30 UTC, designerror commented on Formula/wdc.rb
> +  depends_on "curl"
necessary for `linuxbrew`.

2016-10-23 16:32 UTC, designerror commented on Formula/wdc.rb
> +    system ENV.cc, "test.cpp", "-L#{lib}", "-lwebdavclient", "-lpthread", "-lpugixml", "-lm", "-lcurl", "-lssl", "-lcrypto", "-lstdc++", "-std=c++11", "-o", "test"
I split.

2016-10-23 16:49 UTC, designerror commented
`brew audit https://raw.githubusercontent.com/designerror/homebrew-core/master/Formula/wdc.rb --new-formula` - ok
`brew audit https://raw.githubusercontent.com/designerror/homebrew-core/master/Formula/wdc.rb --new-formula` - ok

2016-10-23 20:41 UTC, MikeMcQuaid commented on Formula/wdc.rb
> +  depends_on "curl"
Homebrew/homebrew-core doesn't support Linuxbrew so please remove it, thanks.

2016-10-24 04:10 UTC, designerror commented on Formula/wdc.rb
> +  depends_on "curl"
you are talking about `cmake` or `curl` or both ?

2016-10-24 06:39 UTC, designerror commented
I tried to fix test for `linuxbrew` on `CentOS`. But it is not work for `homebrew`. I made it back.

2016-10-24 07:09 UTC, designerror commented
I finished the refactoring of the formula.

2016-10-24 07:40 UTC, MikeMcQuaid approved these changes

2016-10-24 08:27 UTC, designerror commented
@mistydemeo, I finished the refactoring of the formula.

2016-10-25 02:57 UTC, designerror commented
@mistydemeo, I finished the refactoring of the formula.

2016-10-25 06:09 UTC, designerror commented
@mistydemeo, I added `pc` file.

2016-11-06 20:47 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-06 20:47 UTC, closed without merging

2016-11-06 20:48 UTC, MikeMcQuaid commented on Formula/wdc.rb
> +    EOS
@designerror Didn't want to block this PR being merged but a `.pc` file should really be generated and installed by your CMake buildsystem. Could you do that for a future version? Thanks!