treefrog 1.13.0 (new formula)
Homebrew/homebrew-core pull request #6209
Opened 2016-10-24 06:33 UTC by skipbit

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-10-25 13:00 UTC, MikeMcQuaid requested changes

2016-10-25 13:00 UTC, MikeMcQuaid commented on Formula/treefrog.rb
> +  url "https://github.com/treefrogframework/treefrog-framework.git", :tag => "v1.13.0", :revision => "dad8d4bbb4ae0bfb480352fde3ba5dd1321ccff8"
Please split this onto multiple lines. Also, does this use submodules? If not, just use a tarball.

2016-10-25 13:00 UTC, MikeMcQuaid commented on Formula/treefrog.rb
> +  depends_on MinimumMacOSRequirement => :el_capitan
`depends_on :macos => :el_capitan`

2016-10-25 13:00 UTC, MikeMcQuaid commented on Formula/treefrog.rb
> +  depends_on XcodeRequirement => [:build, :version => ">= 8.0"]
`depends_on :xcode => [:build, "8.0"]`

2016-10-25 13:00 UTC, MikeMcQuaid commented on Formula/treefrog.rb
> +  qtopts = []
`qt5_build_options`

2016-10-25 13:00 UTC, MikeMcQuaid commented on Formula/treefrog.rb
> +  option "with-debug", "build with debug information"
Omit this, we don't install symbols so it's unlikely this is useful.

2016-10-25 13:00 UTC, MikeMcQuaid commented on Formula/treefrog.rb
> +  option "with-gui", "build and link with QtGui module"
`with-qt5`

2016-10-25 13:00 UTC, MikeMcQuaid commented on Formula/treefrog.rb
> +  option "with-mongo", "build with MongoDB driver library"
`with-mongodb` or build by default if there's no dependency on it.

2016-10-25 13:00 UTC, MikeMcQuaid commented on Formula/treefrog.rb
> +      args << "--enable-gui-mod"
`args << "--enable-gui-mod" if build.with? "qt5"` and similarly on the others.

2016-10-25 13:00 UTC, MikeMcQuaid commented on Formula/treefrog.rb
> +    cd testpath do
Can leave this; it's done by default.

2016-10-26 01:40 UTC, skipbit commented
Thanks for review. All findings by @MikeMcQuaid are fixed.

2016-10-29 02:33 UTC, MikeMcQuaid requested changes

2016-10-29 02:33 UTC, MikeMcQuaid commented on Formula/treefrog.rb
> +  depends_on :xcode => [:build, :version => ">= 8.0"]
`depends_on :xcode => [:build, "8.0"]` (as I said before)

2016-11-09 08:31 UTC, skipbit commented
fix mistake. Please check it.

2016-11-09 11:53 UTC, MikeMcQuaid approved these changes

2016-11-09 11:54 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-09 11:54 UTC, closed without merging