add mmark formula
Homebrew/homebrew-core pull request #6235
Opened 2016-10-24 20:45 UTC by dericed

2016-10-25 15:43 UTC, bfontaine requested changes

2016-10-25 15:43 UTC, bfontaine commented on Formula/mmark.rb
> +    system "#{bin}/mmark", "-version"
Please write a test that does something more substantial than printing the version. You can create a small markdown file and process it with `mmark`.

2016-10-25 15:43 UTC, bfontaine commented on Formula/mmark.rb
> +    url "https://github.com/BurntSushi/toml.git", :revision => "443a628bc233f634a75bcbdd71fe5350789f1afa"
Please move the `:revision` on the next line to keep the text at a reasonable width:

```rb
url "https://github.com/BurntSushi/toml.git",
  :revision => "443a628bc233f634a75bcbdd71fe5350789f1afa"
```

2016-10-25 16:10 UTC, zmwangx commented on Formula/mmark.rb
> +    url "https://github.com/BurntSushi/toml.git", :revision => "443a628bc233f634a75bcbdd71fe5350789f1afa"
Actually all `go_resource` revisions are aligned to the opening quote at the moment.

2016-11-30 18:27 UTC, woodruffw commented
Closing due to inactivity.

2016-11-30 18:27 UTC, closed without merging