riak-ts 1.3.0 (new formula)
Homebrew/homebrew-core pull request #6257
Opened 2016-10-25 11:56 UTC by rrooding

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-10-25 13:57 UTC, zmwangx requested changes

2016-10-25 13:57 UTC, zmwangx commented on Formula/riak-ts.rb
> +  url "http://s3.amazonaws.com/downloads.basho.com/riak_ts/1.3/1.3.0/osx/10.8/riak-ts-1.3.0-OSX-x86_64.tar.gz"
You're downloading a binary distribution, which is not allowed. Need to install from source.

2016-10-25 13:57 UTC, zmwangx commented on Formula/riak-ts.rb
> +  version "1.3.0"
Redundant, remove this line.

2016-10-25 13:57 UTC, zmwangx commented on Formula/riak-ts.rb
> +  test do
Need to write a test.

2016-10-25 15:36 UTC, bfontaine requested changes

2016-10-25 15:36 UTC, bfontaine commented on Formula/riak-ts.rb
> +    (datadir + "ring").mkpath
You can replace this and the line above it with `(datadir/"ring").mkpath`.

2016-10-25 15:36 UTC, bfontaine commented on Formula/riak-ts.rb
> +      s.change_make_var! "RUNNER_LOG_DIR", logdir
Can’t we override these in the environment?

2016-10-25 15:36 UTC, bfontaine commented on Formula/riak-ts.rb
> +    bin.write_exec_script libexec/"bin/search-cmd"
You can factorize this:

```rb
%w[riak riak-admin riak-debug riak-shell search-cmd].each do |script|
  bin.write_exec_script libexec/"bin/#{script}"
end
```

2016-10-25 15:41 UTC, zmwangx commented on Formula/riak-ts.rb
> +    bin.write_exec_script libexec/"bin/search-cmd"
I'd hold off requesting changes in `install` before the building from source issue is addressed.

2016-10-25 15:42 UTC, rrooding commented
Thanks for the comments, I'll take another look at it tomorrow!

2016-11-30 18:27 UTC, woodruffw commented
Closing due to inactivity.

2016-11-30 18:27 UTC, closed without merging