mikutter 3.4.6 (new formula)
Homebrew/homebrew-core pull request #6258
Opened 2016-10-25 13:18 UTC by midchildan

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

mikutter is an extensible twitter client. It is also available in the official repos of Debian, Gentoo, and BSDs.

2016-10-26 13:42 UTC, dunn commented on Formula/mikutter.rb
> +    prefix.install_metafiles
If you're not changing the working directory during installation, this happens automatically.

2016-10-26 13:43 UTC, dunn commented on Formula/mikutter.rb
> +    rm_rf "vendor"
This shouldn't be necessary.

2016-10-26 13:46 UTC, dunn commented on Formula/mikutter.rb
> +      mkpath libexec/"plugin"
`#write` will create the path if necessary, so this and the rest of the `mkpath`s aren't needed: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/pathname.rb#L141

2016-10-26 13:49 UTC, dunn commented on Formula/mikutter.rb
> +  depends_on :ruby => "2.1+"
The RubyRequirement doesn't use the `+`, it should just be `"2.1"` and that means 2.1 or higher.

2016-10-26 13:53 UTC, bfontaine commented on Formula/mikutter.rb
> +    <<-EOS.undent
You should submit them to upstream instead.

2016-10-26 13:54 UTC, MikeMcQuaid commented on Formula/mikutter.rb
> +    <<-EOS.undent
> You should submit them to upstream instead.

Agreed. Upstream need to be willing to support macOS.

2016-10-26 13:54 UTC, midchildan commented on Formula/mikutter.rb
> +    prefix.install_metafiles
You mean `prefix.install_metafiles` ?

2016-10-26 13:56 UTC, bfontaine commented on Formula/mikutter.rb
> +    prefix.install_metafiles
@midchildan Yes.

2016-10-26 14:13 UTC, MikeMcQuaid commented
As a general comment: this formula is kinda a full port to macOS. I'd strongly recommend workign with upstream to get all this stuff (including e.g. icns generation) upstream and ideally get a .app bundle that they can build and support.

2016-10-26 14:24 UTC, bfontaine commented on Formula/mikutter.rb
> +            "#{HOMEBREW_PREFIX}/opt/terminal-notifier/bin/terminal-notifier",
You can’t rely on this being present because it’s only `:recommended`; not required.

2016-10-26 14:24 UTC, bfontaine commented on Formula/mikutter.rb
> +    <<-EOS.undent
You don’t have to depend on `HOMEBREW_PREFIX`; just use the binaries available in the `PATH`.

2016-10-26 14:25 UTC, bfontaine commented on Formula/mikutter.rb
> +            "#{HOMEBREW_PREFIX}/opt/terminal-notifier/bin/terminal-notifier",
Even if you could you should use `terminal-notifier` instead of its full path.

2016-10-27 06:14 UTC, midchildan commented
@MikeMcQuaid The compatibility plugin in this formula could easily be provided by upstream or elsewhere, but it is not so easy for the rest. First, mikutter depends on formulas provided by Homebrew, and you will have to include every single one of them to package it as a standalone `.app` bundle. I'm not sure the upstream will be willing to do that. Second, mikutter depends on Hombrew-specific info such as the `HOMEBREW_PREFIX`. This is necessary because apps launched from the Finder will not include Homebrew's `PATH` by default. 
But the approach I used to make an `.app` bundle is applicable to other formulas as well.  Most of the wrapper script I wrote for launching mikutter is about dealing with differences in the way macOS and other common unix systems handle locales. Specifically, many unix apps depends on `LANG` being set to a UTF-8 locale and will not work if `LANG` is unspecified. Can't we perhaps add a helper method to make a `.app` bundle to wrap unix GUI apps?

2016-10-27 06:14 UTC, midchildan commented on Formula/mikutter.rb
> +    <<-EOS.undent
I could do that, but I would still need `HOMEBREW_PREFIX` for reasons given below.

2016-10-27 18:38 UTC, midchildan commented
I opened a PR in Homebrew/brew#1383

2016-10-30 17:21 UTC, midchildan commented
Fixed formula.

2016-11-06 20:58 UTC, MikeMcQuaid requested changes

2016-11-06 20:58 UTC, MikeMcQuaid commented on Formula/mikutter.rb
> +  end
Can you add a blank line between each of these? Thanks!

2016-11-06 23:47 UTC, midchildan commented on Formula/mikutter.rb
> +  end
@MikeMcQuaid done😁

2016-11-07 08:02 UTC, MikeMcQuaid approved these changes

2016-11-07 08:21 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-07 08:21 UTC, closed without merging