adds urbit (new formula)
Homebrew/homebrew-core pull request #6273
Opened 2016-10-26 01:57 UTC by joemfb

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

formerly headonly, but now has tagged releases. fails to pass `brew audit` due to existing headonly formula (and currently-exceeded github rate-limits).

see Homebrew/homebrew-head-only#205, urbit/urbit#721

2016-10-26 03:12 UTC, zmwangx commented on Formula/urbit.rb
> +    ENV.deparallelize
This could probably be removed? https://github.com/urbit/urbit/pull/332

2016-10-26 03:17 UTC, joemfb commented on Formula/urbit.rb
> +    ENV.deparallelize
I was merely aiming for maximum safety -- I'm honestly not sure.

/cc @juped

2016-10-26 10:46 UTC, bfontaine commented
It’d be awesome if you could make a PR on the [`homebrew/head-only` tap](https://github.com/Homebrew/homebrew-head-only) to migrate the formula here. All you have to do is to remove the formula and add an entry in [`tap_migrations.json`](https://github.com/Homebrew/homebrew-head-only/blob/master/tap_migrations.json). See https://github.com/Homebrew/homebrew-head-only/pull/215 for an example.

2016-10-26 13:48 UTC, MikeMcQuaid requested changes

2016-10-26 13:48 UTC, MikeMcQuaid commented on Formula/urbit.rb
> +    Open3.popen3("#{bin}/urbit") do |_, o, e, ps|
Check and see if `assert_match "simple usage:", shell_output("#{bin}/urbit" 2>&1", 1)` works instead.

2016-10-26 15:53 UTC, joemfb commented
@bfontaine, is that in addition to, or in place of this PR?

2016-10-26 16:21 UTC, bfontaine commented
@joemfb It’s in addition to this one. One PR on the core tap (that one); one PR for the head-only tap.

2016-10-30 17:48 UTC, closed without merging

2016-10-30 17:48 UTC, bfontaine commented
Thank you for your contribution to Homebrew, @joemfb; we appreciate it! 🎉