loc 0.3.2 (new formula)
Homebrew/homebrew-core pull request #6277
Opened 2016-10-26 05:47 UTC by kevinastone

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Rust based Lines of Code counter

2016-10-26 09:28 UTC, bfontaine requested changes

2016-10-26 09:28 UTC, bfontaine commented on Formula/loc.rb
> +    system bin/"loc", "--help"
Please write a test that does something more substantial than printing the help. You may want to create a dummy file and count its lines of code.

2016-10-26 15:47 UTC, kevinastone commented
Added a sample file.

2016-10-27 15:12 UTC, kevinastone commented
ping

2016-10-27 15:36 UTC, bfontaine approved these changes

2016-10-27 15:39 UTC, bfontaine commented
@kevinastone Please don’t ping before 24-48 hours. I’ll have access to my Mac for the first time since Monday tonight; i.e. in 3-4 hours.

2016-10-27 15:42 UTC, kevinastone commented
@bfontaine it was ~24 hours.  I'll be more patient, sorry.

2016-10-27 19:47 UTC, bfontaine commented
…aaaaannnd merged! Thank you @kevinastone for your contribution to Homebrew! 🎉

2016-10-27 19:47 UTC, closed without merging