aws-vault (new formula) (migration from linuxbrew-core)
Homebrew/homebrew-core pull request #62884
Opened 2020-10-14 18:25 UTC by issyl0

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

- This is a Linux-only formula. The macOS version ships as a Cask.

2020-10-14 21:07 UTC, iMichka requested changes
Looks like it needs a license.

I am wondering if this will not conflict with the cask on Mac, and if we should give the formula another name?

2020-10-14 21:14 UTC, SMillerDev commented
It will, but it would be even nicer if it didn't have to be a cask

2020-10-14 21:15 UTC, issyl0 commented
I remember having this discussion at the time I added the Linux-only formula - something about signed binaries for keychain access?

2020-10-14 21:25 UTC, issyl0 commented
It's not necessarily a good user experience, but Homebrew at least tells you its preference for the formula while also appropriately failing to install the formula on macOS:

```
➜ brew install -s aws-vault
Warning: Treating aws-vault as a formula. For the cask, use homebrew/cask/aws-vault
aws-vault: Linux is required.
Error: An unsatisfied requirement failed this build.
```

So yeah, worth a rename I think. Or, "unsatisfied requirement" related to mismatched OSes should default to the cask?

2020-10-14 21:28 UTC, issyl0 commented
Hold on a second... how does `docker` do it? That's both a Formula and a Cask with the same name (see `brew info docker` and `brew cask info docker`.) That's worth looking into...

2020-10-14 22:57 UTC, dawidd6 commented on Formula/aws-vault.rb
> +    bin.install "aws-vault"
```suggestion
```

2020-10-14 22:57 UTC, dawidd6 commented on Formula/aws-vault.rb
> +    system "go", "build", "-ldflags=#{flags}"
```suggestion
    system "go", "build", *std_go_args, "-ldflags=#{flags}"
```

2020-10-15 10:13 UTC, MikeMcQuaid commented
> I remember having this discussion at the time I added the Linux-only formula - something about signed binaries for keychain access requiring it to be a Cask on macOS?

If this is still the blocker: I wonder if it will work with self-signing i.e. using `codesign -s`. If so, support for this was recently added to Ruby MachO and we could consider adding a DSL to do this for formulae in general (I believe GDB also requires this CC @alebcay).

Can someone test this out and see? CC @mistydemeo @woodruffw who have been previously talking about signing.

2020-10-21 07:47 UTC, SMillerDev submitted a review, later dismissed
Thanks @issyl0  ! Without your contributions it'd be impossible to keep homebrew going. You can feel good knowing that you've made the world a lot better for homebrew users around the world! 👍 🎉

2020-10-21 09:03 UTC, dawidd6 commented
@SMillerDev we just squash-and-merge PRs labelled as `linux to homebrew-core`. Without bottles.

2020-10-21 10:28 UTC, MikeMcQuaid requested changes
Can we hold off on this until we figure out the cask situation, please?

2020-10-21 10:29 UTC, issyl0 commented
> Can we hold off on this until we figure out the cask situation, please?

That's exactly why I'd not merged it myself yet. 😅 I haven't had time to test the codesigning stuff yet (and I know nothing about codesigning).

2020-10-21 10:32 UTC, MikeMcQuaid commented
It feels like the tooling shouldn't have allowed triggering a merge when @iMichka had unresolved requested changes. CC @dawidd6 @jonchang for thoughts on that.

2020-12-10 00:37 UTC, closed without merging