vifm 0.11
Homebrew/homebrew-core pull request #63061
Opened 2020-10-18 13:51 UTC by chenrui333

Created with `brew bump-formula-pr`.

2020-10-18 13:55 UTC, chenrui333 commented
license header ref (`src/vifm.c`)

```
/* vifm
 * Copyright (C) 2001 Ken Steen.
 * Copyright (C) 2011 xaizek.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
 */
```

2020-10-18 14:26 UTC, chenrui333 commented
```
Processing /private/tmp/vifm-20201018-989-4jjmvg/vifm-0.11/src/../data/vim/doc/app
  CC       viewcolumns_parser.o
make[1]: *** No rule to make target `../data/vifm-media-osx', needed by `all-am'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  CC       vifm.o
Updating build revision
make: *** [all-recursive] Error 1
```

2020-10-23 15:40 UTC, samford requested changes

2020-10-23 15:40 UTC, samford commented on Formula/vifm.rb
> +  sha256 "d6f829ed0228a8f534d63479fc988c2b4b95e6bc49d5db5e4fabff337fba3c4c"
```suggestion
  url "https://github.com/vifm/vifm/releases/download/v0.11/vifm-0.11.tar.bz2"
  sha256 "d06f7e25f1ba0936f27f3d34401cc9eaa50ccc5a5e70ad5659e5014f04691e67"
```

`vifm-osx-0.11.tar.bz2` is the macOS binary. We should be using the source archive, which is `vifm-0.11.tar.bz2`.

2020-11-03 20:55 UTC, closed without merging