swift: handle changed --build-jobs arg name in HEAD
Homebrew/homebrew-core pull request #6307
Opened 2016-10-27 00:57 UTC by apjanke

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
    - #4300 - this picks up where that one left off
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The `swift` HEAD build is currently broken because the `build-script` `--build-jobs` argument changed to `--jobs`. This fixes it.

Picks up where #4300 left off.

2016-10-27 01:00 UTC, DomT4 commented
I forgot to say anything about the Swift formula before I ran off, my apologies. Just remembered when I saw your email notification _(not directed at me)_ from another thread.

Unless was some local configuration issue this version of Swift doesn't build against Xcode 8, and at the time I couldn't get the newest stable version of Swift to build on Sierra either.

2016-10-27 01:02 UTC, apjanke commented
Ah, I was building it against Xcode 7.3.1 on my box.

No worries.

I think we should still do this PR, because it will fix some build situations which are broken by things besides Xcode 8 being installed.

2016-10-27 01:03 UTC, DomT4 commented
Not my decision to be part of any more 😉, just wanted to mention the build issue in case you wanted to skip CI or wait for CI and then try to debug the other issues, etc.

2016-10-27 01:09 UTC, apjanke commented
Cool. Thanks for the heads-up. Since this is HEAD, the CI won't actually test all of it. Maybe I screwed up in my local testing; I'll re-check that.

2016-11-06 20:49 UTC, MikeMcQuaid requested changes

2016-11-06 20:49 UTC, MikeMcQuaid commented on Formula/swift.rb
> +        "#{buildpath}/utils/build-script",
Reads a bit better to keep this as part of the `system` call, I think.

2016-11-06 20:49 UTC, MikeMcQuaid approved these changes

2016-11-06 20:50 UTC, MikeMcQuaid commented
One nit but otherwise 👍 and feel free to merge without.

2016-11-07 08:22 UTC, MikeMcQuaid commented
Fixed by https://github.com/Homebrew/homebrew-core/pull/6645

2016-11-07 08:22 UTC, closed without merging