Add ttygif formula
Homebrew/homebrew-core pull request #6334
Opened 2016-10-27 19:49 UTC by SimenB

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

First time doing this...

Issue in repo icholy/ttygif#42

/cc @icholy

2016-10-27 20:08 UTC, bfontaine requested changes

2016-10-27 20:08 UTC, bfontaine commented on Formula/ttygif.rb
> +    bin.install("ttygif")
you can drop the parentheses here.

2016-10-27 20:08 UTC, bfontaine commented on Formula/ttygif.rb
> +    system "true"
We prefer tests that run something substantial. Here you could e.g. create a minimal `ttyrec` file and convert it to a gif.

2016-10-27 20:09 UTC, icholy commented on Formula/ttygif.rb
> +    system "true"
that's not possible because it works by taking screencaptures.

2016-10-27 20:20 UTC, SimenB commented on Formula/ttygif.rb
> +    bin.install("ttygif")
Didn't know, done!

2016-10-27 20:45 UTC, bfontaine commented on Formula/ttygif.rb
> +    system "true"
You can use an existing file; you don’t have to record it during the test. See e.g. https://github.com/Homebrew/homebrew-core/blob/dae6d3ebeb1e9f269092adf6677aa0922d3680b8/Formula/ttyrec.rb#L16

2016-10-27 21:21 UTC, SimenB commented
@bfontaine added a test

2016-10-27 21:32 UTC, bfontaine commented on Formula/ttygif.rb
> +      assert_equal "Created: matrix.gif in the current directory!", shell_output("#{bin}/ttygif matrix.tty -f").strip.lines.last
You can shorten this line by using `assert_match`:

```rb
assert_match "Created: matrix.gif in the current directory!", shell_output("#{bin}/ttygif matrix.tty -f")
```

2016-10-27 21:40 UTC, SimenB commented
I made the small change, but doing `brew test ttygif` locally fails with:
![image](https://cloud.githubusercontent.com/assets/1404810/19786513/9b5cc380-9c9e-11e6-95c3-e0721f09eacd.png)

I'm not sure if it's feasible actually creating a gif unless it can somehow be done headless?

2016-10-27 22:28 UTC, icholy commented
I don't think there's a way to do it headless.

2016-10-28 06:21 UTC, bfontaine commented
In that case we’re left with a simple test like `--help` or `--version`.

2016-10-28 06:51 UTC, SimenB commented
It also fails CI because of `GitHub fork (not canonical repository)`. How do you handle that?

2016-10-28 07:48 UTC, bfontaine commented
> It also fails CI because of `GitHub fork (not canonical repository)`. How do you handle that?

You can’t; we’ll ignore that.

2016-10-28 09:15 UTC, SimenB commented
Ok! Waiting for a tagged release with `--version` or `--help` (icholy/ttygif#63) then

2016-11-08 21:20 UTC, SimenB commented
@bfontaine Updated with a test for version

2016-11-08 21:42 UTC, bfontaine approved these changes

2016-11-09 12:17 UTC, MikeMcQuaid requested changes

2016-11-09 12:17 UTC, MikeMcQuaid commented on Formula/ttygif.rb
> +    assert_match "1.4.0", shell_output("#{bin}/ttygif --version")
Looks like `TERM_PROGRAM` or `TERM` variables need set: https://bot.brew.sh/job/Homebrew%20Core/11039/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_ttygif/

2016-11-09 12:17 UTC, MikeMcQuaid commented on Formula/ttygif.rb
> +    bin.install "ttygif"
Can you request a `make install` from upstream? Thanks!

2016-11-09 12:29 UTC, SimenB commented on Formula/ttygif.rb
> +    bin.install "ttygif"
It's already there: https://github.com/icholy/ttygif/blob/master/Makefile#L19

How do I use that instead?

2016-11-09 12:29 UTC, SimenB commented on Formula/ttygif.rb
> +    assert_match "1.4.0", shell_output("#{bin}/ttygif --version")
How do I set env variables in the test?

2016-11-09 12:33 UTC, MikeMcQuaid commented on Formula/ttygif.rb
> +    bin.install "ttygif"
`system "make", "install", "PREFIX=#{prefix}"`. You can also remove the previous `system "make"` after that, too.

2016-11-11 18:09 UTC, SimenB commented
@MikeMcQuaid Updated, I think the only failure now is the fork thing

2016-11-12 10:28 UTC, MikeMcQuaid requested changes

2016-11-12 10:28 UTC, MikeMcQuaid commented on Formula/ttygif.rb
> +    ENV["TERM_PROGRAM"] = 'Something'
Double quotes here and we're good to go (https://bot.brew.sh/job/Homebrew%20Core/11244/version=any_sierra/testReport/junit/brew-test-bot/sierra/audit_ttygif___new_formula/)

2016-11-12 10:29 UTC, MikeMcQuaid requested changes

2016-11-12 10:29 UTC, MikeMcQuaid commented on Formula/ttygif.rb
> +    assert_match "1.4.0", shell_output("#{bin}/ttygif --version")
Oh, and use `version.to_s` instead of `"1.4.0"` here to avoid it breaking next version. Thanks!

2016-11-12 10:46 UTC, SimenB commented
@MikeMcQuaid Done and done! 😄

2016-11-12 11:40 UTC, MikeMcQuaid approved these changes

2016-11-12 12:16 UTC, closed without merging

2016-11-12 12:16 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `ttygif 1.4.0 (new formula)`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!