osmosis 0.45
Homebrew/homebrew-core pull request #6345
Opened 2016-10-28 07:14 UTC by fabrik42

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The audit gives a warning that no tests are defined. What's the best way to add a test for this rather simple formula?

Best,

Christian

2016-10-29 06:53 UTC, tdsmith commented
Feed it some sample data and make sure it doesn't choke, ideally! You can download a small dataset with a `resource` if there isn't one in the tarball we're downloading.

2016-11-01 14:57 UTC, fabrik42 commented
Hmm sorry, but I am still unsure how to do this. I still have a couple of questions left:

Where is the dataset supposed to come from? Should I host it myself? And how can I prove that this works? You basically want to do a very simple operation to prove that it is callable?

Thanks,
Christian

2016-11-06 15:17 UTC, dunn commented
> Where is the dataset supposed to come from? 

Anywhere reliable, where it can be expected to not disappear.

> You basically want to do a very simple operation to prove that it is callable?

Yep!

2016-11-08 13:14 UTC, fabrik42 commented
Ok, I just added the test. Instead of downloading something, I just provided a very simple fixture in the spec. I hope this is ok.

Thanks for the help!

2016-11-08 16:05 UTC, MikeMcQuaid requested changes

2016-11-08 16:05 UTC, MikeMcQuaid commented on Formula/osmosis.rb
> +    path.write <<-EOS
Use EOS.undent` and intent the below lines to be two-spaces beyond the whitespace on this line.

2016-11-08 16:05 UTC, MikeMcQuaid commented on Formula/osmosis.rb
> +    assert_equal 0, $?.exitstatus
Use `system` instead which will check the exit status.

2016-11-08 16:50 UTC, fabrik42 commented on Formula/osmosis.rb
> +    path.write <<-EOS
done!

2016-11-08 16:51 UTC, fabrik42 commented on Formula/osmosis.rb
> +    assert_equal 0, $?.exitstatus
good point!

2016-11-09 12:02 UTC, MikeMcQuaid approved these changes

2016-11-09 12:07 UTC, merged

2016-11-09 12:07 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-09 13:49 UTC, fabrik42 commented
Thanks, you're welcome! :)