S3cmd - Fixed python version (downgrade to 3.8)
Homebrew/homebrew-core pull request #63734
Opened 2020-10-30 16:48 UTC by jbojar

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
s3cmd 2.1.0 is not compatible with python 3.9. There are multiple issues on s3cmd site:

s3tools/s3cmd#1144
s3tools/s3cmd#1137
s3tools/s3cmd#1146

This PR downgrades Python dependency to version 3.8 and reverts the python dependency change made in this PR #63174.

Python dependency should not be changed to 3.9 until release of version 2.2.0 od s3cmd.

Also license is updated to `GPL-2.0-or-later` because `brew audit --strict` complained about it.

2020-10-30 17:16 UTC, fxcoudert requested changes

2020-10-30 20:05 UTC, jbojar commented on Formula/s3cmd.rb
> -  depends_on "python@3.9"
I added comment with links to issues and pull requests.

2020-10-30 21:25 UTC, fxcoudert approved these changes

2020-10-30 22:12 UTC, closed without merging

2020-10-31 12:23 UTC, jonchang commented
This is causing CI on Homebrew/brew to fail:

https://github.com/Homebrew/brew/pull/9018/checks?check_run_id=1335803423#step:19:7

```console
% brew audit fdroidserver
fdroidserver:
  * fdroidserver contains conflicting version recursive dependencies:
      python@3.9, python@3.8
    View these with `brew deps --tree fdroidserver`.
Error: 1 problem in 1 formula detected

% brew deps --tree fdroidserver
fdroidserver
├── freetype
│   └── libpng
├── jpeg
├── libtiff
│   └── jpeg
├── numpy
│   ├── openblas
│   │   └── gcc
│   │       ├── gmp
│   │       ├── isl
│   │       │   └── gmp
│   │       ├── libmpc
│   │       │   ├── gmp
│   │       │   └── mpfr
│   │       │       └── gmp
│   │       └── mpfr
│   │           └── gmp
│   └── python@3.9
│       ├── gdbm
│       ├── openssl@1.1
│       ├── readline
│       ├── sqlite
│       │   └── readline
│       └── xz
├── openssl@1.1
├── python@3.9
│   ├── gdbm
│   ├── openssl@1.1
│   ├── readline
│   ├── sqlite
│   │   └── readline
│   └── xz
├── s3cmd
│   └── python@3.8
│       ├── gdbm
│       ├── openssl@1.1
│       ├── readline
│       ├── sqlite
│       │   └── readline
│       └── xz
└── webp
    ├── jpeg
    ├── libpng
    └── libtiff
        └── jpeg
```

2020-10-31 12:33 UTC, fxcoudert commented
It passed with all green tests, so there seems to be some inconsistency in the audit

2020-10-31 13:02 UTC, alebcay commented
In any case, downgrading this probably means that we need to downgrade `fdroidserver` too since `frdoidserver` depends on `s3cmd`.

2020-10-31 13:08 UTC, fxcoudert commented
This needs to be inspected: there are some combinations that mixed linkage to python3.8 and 3.9 that can work (and it might be the case here, since `frdoidserver` was tested as part of this PR and passed).

2020-10-31 13:18 UTC, jbojar commented
As I checked fdoridserver code (https://github.com/f-droid/fdroidserver/blob/c63c4b3deb6ec6cd887188528f956b7ca0fc08c8/fdroidserver/deploy.py#L95) it uses s3cmd as a command line tool (not as a python library) - so I think it will work perfectly fine with s3cmd launched with other python version than fdroidserver itself.

I think that `brew audit` is here a bit to strict about this python version conflict.