exploitdb 2121-10-30
Homebrew/homebrew-core pull request #63757
Opened 2020-10-30 23:13 UTC by chenrui333

Created with `brew bump-formula-pr`.

2020-10-30 23:24 UTC, issyl0 requested changes, later dismissed
As much as we might all want 2020 to be over, it isn't yet. 😆

2020-10-30 23:24 UTC, issyl0 commented on Formula/exploitdb.rb
> +      tag:      "2121-10-30",
```suggestion
      tag:      "2020-10-30",
```

2020-10-30 23:24 UTC, issyl0 commented on Formula/exploitdb.rb
> +  version "2121-10-30"
```suggestion
  version "2020-10-30"
```

2020-10-30 23:30 UTC, chenrui333 commented on Formula/exploitdb.rb
> +      tag:      "2121-10-30",
haha, yeah quite a fast move :)

2020-10-31 00:45 UTC, zachauten approved these changes

2020-10-31 14:30 UTC, dtrodrigues approved these changes

2020-10-31 16:35 UTC, merged