inspircd 3.8.0
Homebrew/homebrew-core pull request #63804
Opened 2020-10-31 17:05 UTC by zachauten

Created with `brew bump-formula-pr`.

2020-10-31 18:04 UTC, fxcoudert requested changes

2020-10-31 18:04 UTC, fxcoudert commented on Formula/inspircd.rb
>    license "GPL-2.0"
```suggestion
  license "GPL-2.0-only"
```

https://github.com/inspircd/inspircd/blob/insp3/src/channels.cpp
```
 * This file is part of InspIRCd.  InspIRCd is free software: you can
 * redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation, version 2.
```

2020-11-01 17:54 UTC, chenrui333 commented
```
==> ./configure --enable-extras=m_ldapauth.cpp,m_ldapoper.cpp
Error: m_ldapauth.cpp is not an extra module!
```

2020-11-03 08:14 UTC, SMillerDev approved these changes

2020-11-03 21:15 UTC, chenrui333 approved these changes

2020-11-03 21:17 UTC, closed without merging