Metricbeat 5.0.0 (new formula)
Homebrew/homebrew-core pull request #6441
Opened 2016-10-31 12:47 UTC by ruflin

2016-10-31 14:06 UTC, bfontaine requested changes

2016-10-31 14:06 UTC, bfontaine commented on Formula/metricbeat.rb
> +  end
Please leave out the `bottle do` block; our bot will handle it.

2016-10-31 14:06 UTC, bfontaine commented on Formula/metricbeat.rb
> +    mkdir testpath/"logs"
Use `(testpath/"logs").mkpath` instead.

2016-10-31 14:06 UTC, bfontaine commented on Formula/metricbeat.rb
> +    metricbeat_pid = fork { exec bin/"metricbeat", "-c", testpath/"metricbeat.yml", "--path.data=#{testpath}/data", "--path.logs=#{testpath}/logs" }
Please break this on multiple lines.

2016-10-31 14:06 UTC, bfontaine commented on Formula/metricbeat.rb
> +    mkdir testpath/"logs"
Also why is there both a `log` file and a `logs` directory here?

2016-10-31 15:04 UTC, ruflin commented on Formula/metricbeat.rb
> +  end
removed

2016-10-31 15:05 UTC, ruflin commented on Formula/metricbeat.rb
> +    mkdir testpath/"logs"
Implementation changed to `mkpath`

I removed the log file as it is not needed. I forgot to remove it as I copied the initial code from the filebeat Formula.

2016-10-31 15:12 UTC, ruflin commented
@bfontaine Thanks for the review. I pushed a new commit with the requested changes. Let me know if you prefer that I squash it into 1 commit before merging.

2016-10-31 18:07 UTC, bfontaine commented
> Let me know if you prefer that I squash it into 1 commit before merging.

That’d be great, thanks!

2016-10-31 18:16 UTC, ruflin commented
@bfontaine rebased and squashed

2016-10-31 20:17 UTC, bfontaine approved these changes

2016-11-06 15:05 UTC, closed without merging

2016-11-06 15:05 UTC, dunn commented
Thanks for your patience! Merged as 4e805850ee83bff5f82af6413e9d52695ab8dada.

2016-11-06 20:22 UTC, ruflin commented
@dunn Thanks a lot for getting metricbeat into homebrew.