sf-pwgen 1.4
Homebrew/homebrew-core pull request #6448
Opened 2016-10-31 20:01 UTC by anders

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes crash bug on Sierra.

2016-11-01 09:39 UTC, bfontaine requested changes

2016-11-01 09:39 UTC, bfontaine commented on Formula/sf-pwgen.rb
> +  head "https://github.com/anders/pwgen", :using => :git
Please use `head "https://github.com/anders/pwgen.git"` and drop the `, :using => :git` part; it’s the default. Thanks!

2016-11-01 12:11 UTC, anders commented
Done

2016-11-01 18:41 UTC, bfontaine approved these changes

2016-11-06 15:16 UTC, dunn commented
Thanks! Merged as cf1aa86aeddc7443ac2f33c47a3be656b98a1290.

2016-11-06 15:16 UTC, closed without merging