Update suricata.rb
Homebrew/homebrew-core pull request #6459
Opened 2016-11-01 06:08 UTC by missdiog

- [yes ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ yes] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ yes] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ yes] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

update suricata to 3.1.2.
support hiredis,nss,nspr

2016-11-01 09:35 UTC, bfontaine requested changes

2016-11-01 09:35 UTC, bfontaine commented on Formula/suricata.rb
> +    revision 1
Please don’t change this line; our bot will update it. Thanks!

2016-11-06 15:10 UTC, dunn commented
@BrewTestBot test this please

2016-11-06 16:58 UTC, bfontaine approved these changes

2016-11-06 17:42 UTC, dunn commented
Still getting a checksum mismatch on the bottles; let's try again.

2016-11-06 21:25 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `suricata 3.1.2, 3.2beta1 (devel)`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

2016-11-06 21:25 UTC, closed without merging