dbmate 1.11.0
Homebrew/homebrew-core pull request #65167
Opened 2020-11-19 04:58 UTC by dbmate-releasebot

Created by https://github.com/mislav/bump-homebrew-formula-action

2020-11-19 09:39 UTC, amacneil commented
I can't see any reason why this test is failing on 10.15:

```sh
/usr/local/Cellar/dbmate/1.11.0/bin/dbmate: cannot execute binary file
```

The build is very simple:

```rb
def install
  system "go", "build", "-ldflags", "-s", "-o", bin/"dbmate", "."
end
```

It works perfectly on 10.14 and 11.0, but fails on 10.15. Any ideas?

2020-11-19 10:04 UTC, jonchang commented
Yeah, this is probably the Catalina tar bug again: https://github.com/Homebrew/brew/issues/6539

2020-11-19 10:13 UTC, amacneil commented
Interesting. I added some debugging lines, and apparently the binary is just "data":

```sh
==> ls -al /usr/local/Cellar/dbmate/1.11.0/bin/dbmate
-r-xr-xr-x  1 brew  staff  10600768 Nov 19 02:04 /usr/local/Cellar/dbmate/1.11.0/bin/dbmate
==> file /usr/local/Cellar/dbmate/1.11.0/bin/dbmate
/usr/local/Cellar/dbmate/1.11.0/bin/dbmate: data
==> /usr/local/Cellar/dbmate/1.11.0/bin/dbmate create
/usr/local/Cellar/dbmate/1.11.0/bin/dbmate: /usr/local/Cellar/dbmate/1.11.0/bin/dbmate: cannot execute binary file
Error: dbmate: failed
```

It sounds like the only workaround is for a homebrew maintainer to manually remove the Catalina bottle?

2020-11-19 19:55 UTC, amacneil commented
I believe this is ready to merge despite the CI failure on Catalina. If there is anything I can do to resolve the failure please let me know.

2020-11-20 13:38 UTC, fxcoudert requested changes
We will reenable a work-around the Catalina bug, and we can merge once that is done

2020-11-20 13:38 UTC, fxcoudert commented on Formula/dbmate.rb
> -    sha256 "40c2f2d04a9d033478fdff1a272fa0d125a1dbdd746154afe97c5c36612a36af" => :catalina
Please do not touch the bottle block

2020-11-21 08:35 UTC, amacneil commented on Formula/dbmate.rb
> -    sha256 "40c2f2d04a9d033478fdff1a272fa0d125a1dbdd746154afe97c5c36612a36af" => :catalina
Removed

2020-11-22 21:39 UTC, chenrui333 commented
looks like flakiness, rerun a bit.

2020-11-23 07:32 UTC, fxcoudert approved these changes

2020-11-23 08:33 UTC, closed without merging

2020-11-23 09:05 UTC, amacneil commented
🙏 thanks for fixing Catalina issue