Python 3.9.1 bigsur
Homebrew/homebrew-core pull request #65793
Opened 2020-11-27 15:49 UTC by jackbm633

- [*] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [*] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [*] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting? - Having some issues with this - says I need to have latest python 3.9 version.

- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)? - Yes, once the Python 3.9.1 upstream version is released

-----
Hi everyone - this is my first contribution to Homebrew so please forgive me if I make any mistakes along the way. I've been in the process of testing Brew packages on my M1 MacBook Pro, and Python 3.9 currently doesn't work. 3.9.1 is going to be the first version of Python that will support M1 out of the box, but changing the existing formula to the 3.9.1 RC doesn't work 
because Python expects a MacOS version number 10.x whereas Big Sur reports 11.x. Therefore, I have set the environment variable SYSTEM_VERSION_COMPAT to 1 and then got the version of macOS using sw_vers, which will report 10.16: Python is happy with that. This avoids the following error, which I get with both 3.9.0 and 3.9.1:

```
Last 15 lines from /Users/jbeckitt/Library/Logs/Homebrew/python@3.9/02.make:
    self.run_command(cmd_name)
  File "/private/tmp/python@3.9-20201127-62347-16hz8ht/Python-3.9.1rc1/Lib/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/private/tmp/python@3.9-20201127-62347-16hz8ht/Python-3.9.1rc1/Lib/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/private/tmp/python@3.9-20201127-62347-16hz8ht/Python-3.9.1rc1/Lib/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/private/tmp/python@3.9-20201127-62347-16hz8ht/Python-3.9.1rc1/./setup.py", line 447, in build_extensions
    self.detect_modules()
  File "/private/tmp/python@3.9-20201127-62347-16hz8ht/Python-3.9.1rc1/./setup.py", line 1784, in detect_modules
    self.detect_readline_curses()
  File "/private/tmp/python@3.9-20201127-62347-16hz8ht/Python-3.9.1rc1/./setup.py", line 1015, in detect_readline_curses
    (tuple(int(n) for n in dep_target.split('.')[0:2])
AttributeError: 'int' object has no attribute 'split'
```

2020-11-27 16:15 UTC, fxcoudert commented
> sw_vers, which will report 10.16

No, that's not what happens for me on macOS 11.1, and that would be a bug if it did.

> Python expects a MacOS version number 10.x whereas Big Sur reports 11.x

That needs to be reported and fixed, not hacked by pretending we're on another version. Also: so far we haven't seen a problem with that, so far.

2020-11-27 16:15 UTC, fxcoudert commented on Formula/python@3.9.rb
> +    sha256 "bd4ebe03f4c8371c87b2e2db46d5a8ebe0d3f2940f64d8228b901048f1dd9290" => :big_sur
Do not alter bottle blocks

2020-11-27 16:16 UTC, fxcoudert requested changes

2020-11-27 16:16 UTC, fxcoudert commented on Formula/python@3.9.rb
> -          # Set the sys.executable to use the opt_prefix. Only do this if PYTHONEXECUTABLE is not
Do not alter this

2020-11-27 16:16 UTC, fxcoudert commented on Formula/python@3.9.rb
> -
Do not alter whitespace

2020-11-27 16:30 UTC, jackbm633 commented
Okay @fxcoudert , I see what you mean. So is it an issue on my end do you reckon - something wrong with my system configuration?

2020-11-27 16:32 UTC, fxcoudert commented
> So is it an issue on my end do you reckon - something wrong with my system configuration?

I don't know, that's why it would be good to test so it can get fixed before an actual release

2020-11-27 16:38 UTC, jackbm633 commented
> > So is it an issue on my end do you reckon - something wrong with my system configuration?
> 
> I don't know, that's why it would be good to test so it can get fixed before an actual release

Just completely removed Homebrew from my system and trying with a clean installation 👍  - I will report back with results!

2020-11-27 16:45 UTC, jackbm633 commented
I'm closing this - it definitely is an issue on my end 😨. My brother who owns an M1 Mac mini compiled 3.9.0 fine with the default formula.

/sparkle Thanks @fxcoudert for your help - I'll continue with the testing effort on M1!

2020-11-27 16:45 UTC, closed without merging

2020-11-27 22:14 UTC, abarisain commented
FYI I ran into this issue today after wiping my Mac, and I didn't before.

I ran 11.1 beta when it was successful, and 11.0.1 when it failed. 
By editing the formula and setting "MACOSX_DEPLOYMENT_TARGET=11.1", 11.0, 11.0.1 or 11.1.0, the formula works.
As soon as I set it back to #{MacOS.version}, boom, it breaks since it's "11"

I haven't looked into it more, not sure what the root cause is.

2020-12-01 00:12 UTC, nisanth074 commented
Just sharing in case it helps anyone. I was able to resolve the problem in the [issue description](https://github.com/Homebrew/homebrew-core/pull/65793#issue-528681845) by installing the XCode command line tools, updating Homebrew and upgrading the `python@3.9` package

```
xcode-select --install
brew update
brew upgrade python@3.9
```

2020-12-01 07:30 UTC, fxcoudert commented
@nisanth074 @abarisain the issue is a python problem, reported in https://github.com/python/cpython/pull/23556
I proposed a fix to the Python project, and we'll be including it in the next update, under testing now: https://github.com/Homebrew/homebrew-core/pull/65953/files

2020-12-01 22:50 UTC, Fingel commented
Oddly, Ive been getting the following error _since_ the patch was merged when trying to build any wheel:

```
File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/spawn.py", line 66, in spawn
        if _cfg_target_split > [int(x) for x in cur_target.split('.')]:
    AttributeError: 'int' object has no attribute 'split'
```

Is this unrelated? Maybe the same bug manifesting in distutils or something?