coala 0.8 (new formula)
Homebrew/homebrew-core pull request #6651
Opened 2016-11-06 09:11 UTC by mr-karan

- [-] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [-] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [-] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [-] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This formula creates a package for https://coala.io

2016-11-06 16:00 UTC, dunn commented on Formula/coala.rb
> +  resource "appdirs" do
Could you add a blank line above here, and between each resource? Makes reading the formula easier.

2016-11-06 16:01 UTC, dunn commented on Formula/coala.rb
> +    system libexec/"bin/python", "-c", script
Could you make the test a little more involved?  Maybe write out a short bit of code and have coala lint it, like [`shellcheck.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/shellcheck.rb) does.

2016-11-13 12:02 UTC, mr-karan commented on Formula/coala.rb
> +    system libexec/"bin/python", "-c", script
Hey. This is the package which install `coala` without any bears. I'm going to make another package for `coala-bears` in which such a kind of test will be possible. 

Thanks!

2016-11-13 12:57 UTC, MikeMcQuaid requested changes

2016-11-13 12:57 UTC, MikeMcQuaid commented on Formula/coala.rb
> +    system libexec/"bin/python", "-c", script
It sounds like this isn't useful as an application without `coala-bears` so they should be the same package.

2017-02-13 01:15 UTC, woodruffw commented
Closing due to inactivity.

2017-02-13 01:15 UTC, closed without merging