qemu 5.2.0
Homebrew/homebrew-core pull request #66783
Opened 2020-12-12 04:50 UTC by chenrui333

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

2020-12-13 16:14 UTC, fxcoudert commented
`ERROR: Cannot find Ninja`

2020-12-14 15:35 UTC, chenrui333 commented
yeah, I tried adding ninja in my local, and still did not build :(

2020-12-28 04:16 UTC, zeha commented
you need:

```patch
+  depends_on "ninja" => :build
+  depends_on "meson" => :build
```

and

- https://github.com/zeha/qemu/commit/7f2fa31e11dd10b4436d1546a8afad52a41ab581
- (optionally) https://github.com/zeha/qemu/commit/5a1b1c113e2a630dd2a4e9c785326365979cafe6

these are not stable URLs

2020-12-29 03:24 UTC, tiiiecherle commented
Thanks for updating this.
Is virtfs enabled for this build? If not it would be nice if it could be enabled as it helps a lot sharing folders to linux guests.
I was trying UTM.app and virtfs is disabled there.
Thanks

2021-01-06 15:22 UTC, roolebo requested changes

2021-01-06 15:22 UTC, roolebo commented on Formula/qemu.rb
> +    system "ninja", "-v"
This hunk is invalid. There's a dependency on ninja but it shouldn't be used directly yet.

2021-01-09 19:25 UTC, r58Playz commented
[This](https://gist.github.com/niw/e4313b9c14e968764a52375da41b4278) may be helpful(there's an english version below)

2021-01-18 14:52 UTC, tiiiecherle commented
Does anyone have a working local build to share or are there any news how to fix this? I tried but couldn't get it to work...
Thanks for any help.

2021-01-21 20:00 UTC, ziyi-yan commented
> Does anyone have a working local build to share or are there any news how to fix this? I tried but couldn't get it to work...
> Thanks for any help.

I followed the advice from @zeha and made two patches to fix it. At least it build successfully on my machine now.

2021-01-23 14:02 UTC, zeha commented
Upstream URLs are now:

https://git.qemu.org/?p=qemu.git;a=patch;h=0dbce6efb5ff2e7113734d3a0cabbf87fc56feec
https://git.qemu.org/?p=qemu.git;a=patch;h=cb7abd8319d19000b57ae6c5c474c2635db054c6

Haven't tried applying them on top of 5.2.0 directly.

2021-01-25 07:13 UTC, carlocab approved these changes
🎉

2021-01-25 07:27 UTC, SMillerDev approved these changes

2021-01-25 07:54 UTC, closed without merging