libxslt: add Linux-only configure flag
Homebrew/homebrew-core pull request #66966
Opened 2020-12-15 19:34 UTC by SeekingMeaning

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2020-12-15 19:40 UTC, fxcoudert requested changes, later dismissed

2020-12-15 19:40 UTC, fxcoudert commented on Formula/libxslt.rb
> +    system "./configure", args
```suggestion
    system "./configure", *args
```

2020-12-15 19:49 UTC, fxcoudert commented
If we're adding linux-specific code to the formula, shouldn't the PR be run on linux CI?

2020-12-15 20:01 UTC, SeekingMeaning commented
This actually isn't be needed as I managed to build this locally without the flag, which was added 6 years ago: https://github.com/Linuxbrew/legacy-linuxbrew/pull/147

Closing this in favor of https://github.com/Homebrew/linuxbrew-core/pull/21845

2020-12-18 20:55 UTC, SeekingMeaning commented
Reopening this as `libgcrypt` could become a circular dependency without the `--without-crypto` flag

2020-12-18 21:05 UTC, iMichka commented
I think the flags was added to avoid opportunistic linkage to libgcrypt.
On the other side we have a cyclic dependency here ... wondering why libxslt needs encryption.

2020-12-21 02:12 UTC, SeekingMeaning commented
On Arch Linux, `libxslt`<sup>[1]</sup> depends on `libgcrypt`<sup>[2]</sup> but not vice versa

1. https://archlinux.org/packages/extra/x86_64/libxslt/
2. https://archlinux.org/packages/core/x86_64/libgcrypt/

2020-12-21 12:57 UTC, iMichka commented
So I would be in favour of building `libgcrypt` without `libxslt`.

2020-12-21 19:15 UTC, SeekingMeaning commented
Should we add `libgcrypt` as an explicit dependency for this formula?

2020-12-21 22:19 UTC, iMichka commented
Yes, let's enable crypto for the formula, so we do the same as arch linux.

2020-12-23 22:22 UTC, iMichka commented
This needs a revision bump as we are adding a new dependency. The rest looks good, thanks for adding an extended test.

2020-12-26 17:45 UTC, dawidd6 approved these changes

2020-12-26 18:32 UTC, closed without merging