ejabberd 20.12
Homebrew/homebrew-core pull request #67053
Opened 2020-12-17 15:04 UTC by mremond

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is an update for latest upstream ejabberd version.

I made a couple of changes to adapt to new license check and to make the upgrade more robust (do not show post install error message if vm.args file already exist.

2020-12-17 19:05 UTC, fxcoudert requested changes

2020-12-17 19:05 UTC, fxcoudert commented on Formula/ejabberd.rb
>    revision 1
Remove the `revision` line

2020-12-18 09:51 UTC, mremond commented
Thanks, this is done.

2020-12-18 09:53 UTC, fxcoudert approved these changes

2020-12-18 15:17 UTC, closed without merging