liblastfm: qt5 support and add a test
Homebrew/homebrew-core pull request #6740
Opened 2016-11-08 22:10 UTC by Moisan

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Related to #1705 and #6408.

2016-11-09 12:19 UTC, MikeMcQuaid requested changes

2016-11-09 12:19 UTC, MikeMcQuaid commented on Formula/liblastfm.rb
> +    assert_match "Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 0ms",
`0ms` needs removed here as it's failing on Sierra (and generally is likely to be flaky). Is it not enough to rely on the exit-code alone here?

2016-11-09 13:37 UTC, Moisan commented on Formula/liblastfm.rb
> +    assert_match "Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 0ms",
You're right, exit-code should be enough.

2016-11-10 10:20 UTC, MikeMcQuaid approved these changes

2016-11-10 10:23 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-10 10:24 UTC, closed without merging