Recime CLI
Homebrew/homebrew-core pull request #6745
Opened 2016-11-09 01:35 UTC by mehfuzh

- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-11-09 12:24 UTC, MikeMcQuaid requested changes

2016-11-09 12:24 UTC, MikeMcQuaid commented on Formula/recime-cli.rb
> +
Remove this empty line.

2016-11-09 12:24 UTC, MikeMcQuaid commented on Formula/recime-cli.rb
> +  end
Remove this block, we need to generate these.

2016-11-09 12:24 UTC, MikeMcQuaid commented on Formula/recime-cli.rb
> +    # system "go", "build", "-o", bin/"recime-cli", "main.go"
Remove these commented-out lines.

2016-11-09 12:24 UTC, MikeMcQuaid commented on Formula/recime-cli.rb
> +    system bin/"recime-cli", "version"
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2016-11-09 12:24 UTC, MikeMcQuaid commented on Formula/recime-cli.rb
> +  version "1.0.5"
The version seems to be `1.0` not `1.0.5`.

2016-11-09 12:24 UTC, MikeMcQuaid commented
> GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
https://bot.brew.sh/job/Homebrew%20Core/11063/version=any_sierra/testReport/junit/brew-test-bot/sierra/audit_recime_cli___new_formula/

Passing on this as a result, sorry! Please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!

2016-11-09 12:24 UTC, closed without merging

2016-11-09 17:12 UTC, mehfuzh commented
Does it mean I can't publish this formula to home-brew  with the above exception.

2016-11-10 10:14 UTC, MikeMcQuaid commented
Yes, please consider creating your own tap.