swiftformat 0.17 (new formula)
Homebrew/homebrew-core pull request #6752
Opened 2016-11-09 07:18 UTC by nicklockwood

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-11-09 07:28 UTC, bfontaine requested changes

2016-11-09 07:28 UTC, bfontaine commented on Formula/swiftformat.rb
> +    bin.install "CommandLineTool/swiftformat"
We need to build from source here.

2016-11-09 07:28 UTC, bfontaine commented on Formula/swiftformat.rb
> +    system "#{bin}/swiftformat"
Please write a test that does something more substantial than e.g. printing the help. You can write a test Swift file and call `swiftformat` on it.

2016-11-18 14:28 UTC, dunn commented
Ping re @bfontaine's comments

2016-11-22 04:23 UTC, woodruffw commented
Seems to have been superseded by #7138.

2016-11-22 04:23 UTC, closed without merging