updated emscripten to version 1.36.14, fixes #6771
Homebrew/homebrew-core pull request #6826
Opened 2016-11-11 09:45 UTC by bodokaiser

Did not test `brew install --HEAD emscripten` but it should now working using the `master` branch over `incoming` (`incoming` failed actually).

Normal install works now. Problem with `cmake` was a missing `depends_on "cmake" => ":build"`.

2016-11-11 11:19 UTC, bodokaiser commented
Please wait with merge. I may add another dependency. See https://github.com/kripken/emscripten/issues/4710

2016-11-11 12:54 UTC, MikeMcQuaid requested changes

2016-11-11 12:54 UTC, MikeMcQuaid commented on Formula/emscripten.rb
> +    url "https://github.com/kripken/emscripten/archive/#{version}.tar.gz"
This should stay as `1.36.14`

2016-11-11 12:54 UTC, MikeMcQuaid commented on Formula/emscripten.rb
> +      url "https://github.com/kripken/emscripten-fastcomp/archive/#{version}.tar.gz"
Sorry, I forgot this doesn't work as expected. You can either take the approach from `swift.rb` or (preferred) write something in the `test do` that will reproduce the failure you were seeing when the versions were mismatched. That will stop this being merged with that error.

2016-11-11 12:54 UTC, MikeMcQuaid commented on Formula/emscripten.rb
> +    depends_on "cmake" => :build
This can be removed, it's repeated below.

2016-11-12 10:30 UTC, MikeMcQuaid requested changes

2016-11-12 10:30 UTC, MikeMcQuaid commented on Formula/emscripten.rb
> +    emscripten_tag = "#{version}.tar.gz"
The `.tar.gz` shouldn't be here.

2016-11-12 14:19 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `emscripten 1.36.14`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

2016-11-12 14:22 UTC, MikeMcQuaid approved these changes

2016-11-12 14:22 UTC, closed without merging