eject 0.1.12 (new formula)
Homebrew/homebrew-core pull request #6893
Opened 2016-11-13 22:18 UTC by edwardloveall

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-11-13 22:20 UTC, edwardloveall commented on Formula/eject.rb
> +    system "#{bin}/eject"
I'm aware that this is a pretty weak test. Right now the tool only prints out usage instructions or requires a xib which would be a lot of lines to embed for a test. If you think that's reasonable or there's a better way, let me know and I'll change it.

2016-11-14 08:30 UTC, MikeMcQuaid commented on Formula/eject.rb
> +    system "#{bin}/eject"
What's the smallest possible `xib` that can be created?

2016-11-14 11:59 UTC, bfontaine commented on Formula/eject.rb
> +    mv(frameworks_path, frameworks)
You can drop the parentheses here.

2016-11-14 12:00 UTC, bfontaine commented
The [build failed](https://bot.brew.sh/job/Homebrew%20Core/11358/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_eject/) as well as the [audit](https://bot.brew.sh/job/Homebrew%20Core/11358/version=any_sierra/testReport/junit/brew-test-bot/sierra/audit_eject___new_formula/):
```
Error: 2 problems in 1 formula
eject:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
  * GitHub repository too new (<30 days old)
```

2016-11-14 13:50 UTC, edwardloveall commented on Formula/eject.rb
> +    system "#{bin}/eject"
Looks like I can create one that's 16 lines long, which doesn't seem that bad:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.XIB" version="3.0" toolsVersion="11134" systemVersion="15F34" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitCollections="YES" colorMatched="YES">
    <dependencies>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="11106"/>
        <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>
    </dependencies>
    <objects>
        <placeholder placeholderIdentifier="IBFilesOwner" id="-1" userLabel="File's Owner"/>
        <placeholder placeholderIdentifier="IBFirstResponder" id="-2" customClass="UIResponder"/>
        <view contentMode="scaleToFill" id="iN0-l3-epB">
            <rect key="frame" x="0.0" y="0.0" width="375" height="667"/>
            <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
            <color key="backgroundColor" red="1" green="1" blue="1" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>
        </view>
    </objects>
</document>
```

When run through eject, it creates the following output:

```swift

// Create Views
let view = UIView()
view.frame = CGRect(x: 0, y: 0, width: 375, height: 667)
view.autoresizingMask = [.flexibleHeight, .flexibleWidth]
view.backgroundColor = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
```

2016-11-14 15:58 UTC, edwardloveall commented on Formula/eject.rb
> +    system "#{bin}/eject"
Ok, I created a better test. Let me know what you think!

2016-11-14 16:01 UTC, edwardloveall commented
Oh, I see it's failing on the repository not being popular enough. I guess I'll do a tab instead. Sorry!

2016-11-14 16:03 UTC, MikeMcQuaid commented
@edwardloveall Leave this open, we might include it anyway.

2016-11-14 16:22 UTC, edwardloveall commented
Sure thing. I can also squash the commits if there's nothing else to change before it's merged. Let me know.

2016-11-14 20:56 UTC, bfontaine commented on Formula/eject.rb
> +    File.read("view.swift") == swift
Use `assert_equal swift, shell_output("#{bin}/eject --file view.xib")` instead.

2016-11-14 20:57 UTC, edwardloveall commented on Formula/eject.rb
> +    File.read("view.swift") == swift
Done

2016-11-15 08:47 UTC, MikeMcQuaid requested changes

2016-11-15 08:47 UTC, MikeMcQuaid commented on Formula/eject.rb
> +      file.write <<-XML
Use `EOS.undent` here and then you can indent the line below (and all others) two characters more than before `file.write`

2016-11-15 08:47 UTC, MikeMcQuaid commented on Formula/eject.rb
> +    swift = <<-SWIFT
Similarly use `EOS.undent` here.

2016-11-16 10:06 UTC, MikeMcQuaid requested changes

2016-11-16 10:06 UTC, MikeMcQuaid commented on Formula/eject.rb
> +    xib = File.open "view.xib", "a+" do |file|
Don't need the `xib` assignment here and use `(testpath/"view.xib").write` instead of the block

2016-11-16 10:06 UTC, MikeMcQuaid commented on Formula/eject.rb
> +  depends_on :xcode => :build
Failing on Yosemite so may need scoped to e.g. Xcode 8: https://bot.brew.sh/job/Homebrew%20Core/11454/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_eject/

2016-11-16 15:24 UTC, edwardloveall commented on Formula/eject.rb
> +    xib = File.open "view.xib", "a+" do |file|
👍

2016-11-17 16:52 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-17 16:52 UTC, closed without merging