Fixed apache-geode forumla to not use Java 1.9
Homebrew/homebrew-core pull request #6911
Opened 2016-11-14 17:02 UTC by jaredjstewart

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

 I encountered an error when running `brew audit --strict foo`:

```
apache-geode:
  * version should not decrease
Error: 1 problem in 1 formula
```
-----

2016-11-15 08:43 UTC, MikeMcQuaid commented
Can you elaborate a bit more here on why we need to avoid Java 1.9?

2016-11-15 16:58 UTC, jaredjstewart commented
`gfsh start locator` does not return to foreground, just lots of `…………………………….`

2016-11-16 09:44 UTC, MikeMcQuaid commented
@jaredjstewart Please file an upstream issue about this, thanks.

2016-11-16 17:06 UTC, jaredjstewart commented
@MikeMcQuaid Do you mean upstream with Apache Geode?

2016-11-16 18:08 UTC, MikeMcQuaid requested changes

2016-11-16 18:08 UTC, MikeMcQuaid commented on Formula/apache-geode.rb
> +  depends_on :java => "1.8"
Please link to `https://issues.apache.org/jira/browse/GEODE-3` and explain that it doesn't work with Java 1.9 on the line above. Thanks!

2016-11-16 18:23 UTC, jaredjstewart commented on Formula/apache-geode.rb
> +  depends_on :java => "1.8"
I just pushed another commit to include this comment.

2016-11-17 15:43 UTC, MikeMcQuaid requested changes

2016-11-17 15:43 UTC, MikeMcQuaid commented on Formula/apache-geode.rb
> +  #Geode does not work with Java 1.9 (see https://issues.apache.org/jira/browse/GEODE-3).
`brew style` warning: https://bot.brew.sh/job/Homebrew%20Core/11526/version=any_sierra/testReport/junit/brew-test-bot/sierra/style_apache_geode/

2016-11-17 15:44 UTC, MikeMcQuaid commented on Formula/apache-geode.rb
> +  #Geode does not work with Java 1.9 (see https://issues.apache.org/jira/browse/GEODE-3).
Also you can skip the trailing `.`

2016-11-18 18:03 UTC, jaredjstewart commented
I updated the PR, comment style should now be compliant:
```
$ brew style apache-geode

1 file inspected, no offenses detected
```

2016-11-24 03:03 UTC, dunn commented
Thanks, merged as a3f1f3d9af9ca1ff0d8015375bdc575e5a35c2a5!

2016-11-24 03:03 UTC, closed without merging