jasper: disable docs and explicitly enable shared library
Homebrew/homebrew-core pull request #69130
Opened 2021-01-15 22:38 UTC by danielnachun

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This disable document generation which tries to run if LaTeX is detected but is likely to fail.  I also needed to explicitly enable building the shared library on Linux.

@jonchang it seems this formula hasn't had all the Linux changes back ported to it.  I tried to backport the fixes for GLUT but the way they are implemented in the Linux formula doesn't pass `brew audit` because it uses `if OS.mac?`/`unless OS.mac?`.  Let me know if I should do anything else for this.

2021-01-15 22:45 UTC, carlocab commented
You can do
```
on_macos do
  mac_only_stuff
end
on_linux do
  linux_only_stuff
end
```
to replace the `if OS.mac?` etc calls

2021-01-16 01:47 UTC, jonchang requested changes
Thanks @danielnachun! Some suggestions to simplify this.

2021-01-16 01:47 UTC, jonchang commented on Formula/jasper.rb
> +      os_cmake_args = []
```suggestion
      args = std_cmake_args
      args << "-DJAS_ENABLE_DOC=OFF"
```

We can then remove usage of `std_cmake_args` below and simplify the formula a bit.

2021-01-16 01:47 UTC, jonchang commented on Formula/jasper.rb
> +        os_cmake_args.push "-DGLUT_glut_LIBRARY=#{glut_lib}"
```suggestion
        os_cmake_args << "-DGLUT_glut_LIBRARY=#{glut_lib}"
```
We usually prefer this style, except in the case of chained method calls.

2021-01-16 01:47 UTC, jonchang commented on Formula/jasper.rb
> +      os_cmake_args << "-DJAS_ENABLE_DOC=OFF"
```suggestion
```

2021-01-16 01:47 UTC, jonchang commented on Formula/jasper.rb
>          *std_cmake_args
```suggestion
        *args
```

2021-01-16 01:47 UTC, jonchang commented on Formula/jasper.rb
>          *std_cmake_args
```suggestion
        *args
```

2021-01-16 06:56 UTC, iMichka approved these changes

2021-01-16 07:05 UTC, jonchang approved these changes
Nice work!

2021-01-16 07:49 UTC, closed without merging