Remove npm install dependency
Homebrew/homebrew-core pull request #6936
Opened 2016-11-15 14:36 UTC by torifat

**POC**

`brew install yarn -s`

2016-11-15 14:40 UTC, MikeMcQuaid requested changes

2016-11-15 14:40 UTC, MikeMcQuaid commented on Formula/yarn.rb
> +    cp_r '.', prefix
Did you test this locally? This is 100% not going to work because there's e.g. no `libexec`.

2016-11-15 14:40 UTC, MikeMcQuaid commented
@torifat Please fill out the new PR template, thanks.

2016-11-15 14:42 UTC, torifat commented
@MikeMcQuaid Sorry, I thought you just wanted to check it as POC. That's why skipped the template. Just a moment.

2016-11-15 14:45 UTC, torifat commented on Formula/yarn.rb
> +    cp_r '.', prefix
Yes, I checked in locally.

- `brew remove yarn`
- `brew install yarn -s`
- `/usr/local/bin/yarn`

<img width="235" alt="screenshot 2016-11-15 20 44 14" src="https://cloud.githubusercontent.com/assets/208544/20309987/5de23eec-ab74-11e6-84cd-331d603fc05b.png">

2016-11-15 14:47 UTC, MikeMcQuaid commented on Formula/yarn.rb
> +    cp_r '.', prefix
What's the line after left in for? It appears to be a no-op (and I'm surprised it didn't fail).

2016-11-15 14:54 UTC, MikeMcQuaid commented on Formula/yarn.rb
> +    cp_r '.', prefix
Yep, that's why you need to `libexec.install buildpath.children`.

2016-11-15 14:55 UTC, torifat commented on Formula/yarn.rb
> +    cp_r '.', prefix
BTW, it's weird that `bin.install_symlink Dir["#{libexec}/bin/*"]` is working 😕  It shouldn't.

2016-11-15 15:09 UTC, MikeMcQuaid commented
Let's leave this open. You can push changes to this PR.

2016-11-15 16:09 UTC, torifat commented
Need to figure out a way to handle `node-gyp-bin/`. I will ping once I'm done with it.

2016-12-06 16:03 UTC, ilovezfs commented
@BrewTestBot test this please

2016-12-06 16:04 UTC, torifat commented
@ilovezfs Sorry, I couldn't manage time to work on it. Please ignore this for the time being.

2017-03-19 16:35 UTC, closed without merging

2017-03-19 16:35 UTC, MikeMcQuaid commented
Closing as this PR has stalled.