tarsnapper 0.3.0 (new formula)
Homebrew/homebrew-core pull request #6956
Opened 2016-11-16 06:06 UTC by JanAhrens

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

[tarsnapper](https://github.com/miracle2k/tarsnapper/) is a wrapper for [tarsnap](https://www.tarsnap.com).

This is my first contribution. I'm not sure if I took the right decision to have a "real" test instead of just running the program to see if it can output the "--help" output. As you can read in my comments, running the test currently requires a setup ".tarsnaprc" which in turns requires to have an account at   [tarsnap](https://www.tarsnap.com).

2016-11-16 06:26 UTC, woodruffw commented
Thanks for contributing!

> I'm not sure if I took the right decision to have a "real" test instead of just running the program to see if it can output the "--help" output. As you can read in my comments, running the test currently requires a setup ".tarsnaprc" which in turns requires to have an account at tarsnap.

In a case like this, we shouldn't count on the tester (or CI) having a tarsnap account. We normally prefer tests slightly more in depth than a `--help` or `--version`, but I think one will work here.

2016-11-16 09:52 UTC, MikeMcQuaid commented
> In a case like this, we shouldn't count on the tester (or CI) having a tarsnap account. We normally prefer tests slightly more in depth than a --help or --version, but I think one will work here.

Yep. It needs to pass on our CI: https://bot.brew.sh/job/Homebrew%20Core/11483/version=any_sierra/testReport/junit/brew-test-bot/sierra/test_tarsnapper/

2016-11-17 05:16 UTC, JanAhrens commented
Thank you both for your quick help.

> In a case like this, we shouldn't count on the tester (or CI) having a tarsnap account. 

That makes a lot of sense. TBH I didn't consider the CI system when I wrote that test case.

I documented the reason for the minimalistic test in a comment so that this branch can be squash-merged if you like.

2016-11-17 16:17 UTC, MikeMcQuaid requested changes

2016-11-17 16:17 UTC, MikeMcQuaid commented on Formula/tarsnapper.rb
> +    system bin/"tarsnapper", "--help"
Can remove these comments but thanks for them anyway. Do something with `assert_match "some string", shell_output("#{bin}/tarsnapper --help") just so we can confirm it's not :boom: and have a slightly better test.

2016-11-17 17:34 UTC, JanAhrens commented on Formula/tarsnapper.rb
> +    system bin/"tarsnapper", "--help"
Excellent point! Without an assert this test is useless. My last commit fixes this.

This is how the output looks if one remove a needed python dependency:

```
Testing tarsnapper
==> Using the sandbox
==> /usr/local/Cellar/tarsnapper/0.3.0/bin/tarsnapper --help
Traceback (most recent call last):
  File "/usr/local/Cellar/tarsnapper/0.3.0/bin/tarsnapper", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/tarsnapper/0.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/usr/local/Cellar/tarsnapper/0.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/tarsnapper/0.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/tarsnapper/0.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/tarsnapper/0.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/tarsnapper/0.3.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'six>=1.5' distribution was not found and is required by python-dateutil
Error: tarsnapper: failed
<0> expected but was
<1>.
```

2016-11-18 08:34 UTC, MikeMcQuaid approved these changes

2016-11-18 08:44 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-18 08:44 UTC, closed without merging