wu 3.10.0 (new)
Homebrew/homebrew-core pull request #7015
Opened 2016-11-17 14:58 UTC by chiefy

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-11-17 15:15 UTC, bfontaine requested changes

2016-11-17 15:15 UTC, bfontaine commented on Formula/wu.rb
> +  depends_on "go"
This depends on Go for the build only, so please use `depends_on "go" => :build`.

2016-11-17 15:15 UTC, bfontaine commented on Formula/wu.rb
> +    system "false"
You can remove this line.

2016-11-17 15:15 UTC, bfontaine commented on Formula/wu.rb
> +    ENV["GOPATH"] = testpath.realpath
You shouldn’t need this.

2016-11-17 16:04 UTC, bfontaine approved these changes

2016-11-17 16:10 UTC, MikeMcQuaid requested changes

2016-11-17 16:10 UTC, MikeMcQuaid commented on Formula/wu.rb
> +  desc "cli that retrieves weather data from Weather Underground."
`CLI`

2016-11-17 16:10 UTC, MikeMcQuaid commented on Formula/wu.rb
> +    In order for `wu` to work, you need to obtain a Weather Underground API key:
I don't think we need these caveats as none of them are Homebrew-specific information.

2016-11-17 16:35 UTC, chiefy commented on Formula/wu.rb
> +    In order for `wu` to work, you need to obtain a Weather Underground API key:
@MikeMcQuaid how else should I inform the installer that there are these requirements?

2016-11-17 16:52 UTC, MikeMcQuaid commented on Formula/wu.rb
> +    In order for `wu` to work, you need to obtain a Weather Underground API key:
You should not. They can read the instructions prominently at the top of the homepage: https://github.com/sramsay/wu

2016-11-17 17:24 UTC, chiefy commented on Formula/wu.rb
> +    In order for `wu` to work, you need to obtain a Weather Underground API key:
@MikeMcQuaid removed. Unless I missed it, might be cool to have something in the docs about what you should / shouldn't display to the user?

2016-11-17 17:36 UTC, MikeMcQuaid commented on Formula/wu.rb
> +    In order for `wu` to work, you need to obtain a Weather Underground API key:
Where would be most useful, http://www.rubydoc.info/github/Homebrew/brew/master/Formula#caveats-instance_method?

2016-11-17 17:37 UTC, MikeMcQuaid approved these changes

2016-11-18 08:31 UTC, closed without merging

2016-11-18 08:31 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!