git-remote-gcrypt 1.0.0 (new formula)
Homebrew/homebrew-core pull request #7025
Opened 2016-11-17 21:33 UTC by srl295

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-11-17 21:45 UTC, bfontaine requested changes

2016-11-17 21:45 UTC, bfontaine commented on Formula/git-remote-gcrypt.rb
> +  url "https://git.spwhitton.name/git-remote-gcrypt.git"
We need a stable release here.

2016-11-17 22:19 UTC, srl295 commented on Formula/git-remote-gcrypt.rb
> +  url "https://git.spwhitton.name/git-remote-gcrypt.git"
@bfontaine sorry… I thought the `version 1.0.0` would do that (specify the tag from the repo). Refactored and verified.

2016-11-18 08:38 UTC, MikeMcQuaid requested changes

2016-11-18 08:38 UTC, MikeMcQuaid commented on Formula/git-remote-gcrypt.rb
> +    system "#{bin}/git-remote-gcrypt"
Use `assert_match "something", shell_output("#{bin}/git-remote-gcrypt")` to match some output here.

2016-11-18 08:38 UTC, MikeMcQuaid commented on Formula/git-remote-gcrypt.rb
> +    bin.install "git-remote-gcrypt"
Use `install.sh` instead: https://git.spwhitton.name/?p=git-remote-gcrypt.git;a=blob;f=install.sh;h=d84f31ec116721915d2e054faafee67dbf3a0e27;hb=HEAD

2016-11-18 08:38 UTC, MikeMcQuaid commented on Formula/git-remote-gcrypt.rb
> +      :revision => "30b3f5e3356bba404eb630807879b8d4989f8c6e"
May be worth asking them for a tarball as that may be less expensive for them.

2016-11-18 13:32 UTC, spwhitton commented
Tarballs available from the Debian mirror network: http://ftp.debian.org/debian/pool/main/g/git-remote-gcrypt/

2016-11-18 13:32 UTC, spwhitton commented on Formula/git-remote-gcrypt.rb
> +      :revision => "30b3f5e3356bba404eb630807879b8d4989f8c6e"
Here: http://ftp.debian.org/debian/pool/main/g/git-remote-gcrypt/

2016-11-18 13:39 UTC, MikeMcQuaid commented
> Tarballs available from the Debian mirror network: http://ftp.debian.org/debian/pool/main/g/git-remote-gcrypt/

@spwhitton Would you rather we used that to save you bandwidth?

2016-11-18 15:46 UTC, spwhitton commented
Yes please :)

Though please keep the homepage pointing at my site.

-- 
Sean Whitton

2016-11-18 16:01 UTC, srl295 commented
@spwhitton @MikeMcQuaid there's also the github mirror… but `brew audit` rejected it as being "not the main fork"

2016-11-18 16:19 UTC, MikeMcQuaid commented
@srl295 The GitHub mirror would be preferable. Ignore the fork warning.
@spwhitton Would you like your fork either detached (so it doesn't show as forked from anything) or the primary node (so e.g. https://github.com/joeyh/git-remote-gcrypt shows as forked from yours)? I'm GitHub staff so can update that accordingly.

2016-11-18 21:01 UTC, spwhitton commented
On Fri, Nov 18, 2016 at 08:19:30AM -0800, Mike McQuaid wrote:
> @spwhitton Would you like your fork either detached (so it doesn't show as
> forked from anything) or the primary node (so e.g. https://github.com/joeyh/
> git-remote-gcrypt shows as forked from yours)? I'm GitHub staff so can update
> that accordingly.

Thank you for your offer to update the forking relationships.

The reason I maintain a mirror of the project on GitHub is to make it
easier for people to find it.  Detaching the repository would not serve
that purpose, as then it wouldn't show up in the list of forks.

On the other hand, making it the primary node would make it easier to
find my repository.  It would be completely clear that patches/PRs
should be submitted to me, not to @joeyh or @bluss.

I'm concerned, though, that it might imply that I was the originator of
the project.  I maintain it upstream and in Debian and Ubuntu, but I did
not come up with the idea nor did I write very much of the code.  So it
seems dishonest for my repo to be the primary node.

Have I misunderstood what it means to be the primary node?  I am not
really active on the social side of GitHub, so I might have misconstrued
it.

-- 
Sean Whitton

2016-11-20 10:12 UTC, MikeMcQuaid commented
@spwhitton Your understanding there seems to be correct. Given that @joeyh's and @bluss's forks both state they are unmaintained and @joeyh's points to yours explicitly (and I'd argue @bluss's implicitly does) it seems better to me for recognising which project is being actively developed. Ultimately, it's up to you though so if you're OK with me doing so let me know otherwise I'll leave it as is. Thanks for all your work, regardless!

2016-11-20 14:21 UTC, spwhitton commented
@MikeMcQuaid Probably best to leave it as it is for now.  Thanks again
for the offer.

-- 
Sean Whitton

2016-11-23 12:04 UTC, MikeMcQuaid commented
@spwhitton Sure, thanks.
@srl295 Sounds like there should be enough information for you to update this now. No rush.

2016-12-10 00:51 UTC, srl295 commented on Formula/git-remote-gcrypt.rb
> +    bin.install "git-remote-gcrypt"
@MikeMcQuaid thanks…  trying
> `    system "env prefix=#{prefix} DESTDIR=#{buildpath} ./install.sh"`

but it's not finding `rst2man` that way, and resulting in an empty installation.

2016-12-10 00:51 UTC, srl295 commented on Formula/git-remote-gcrypt.rb
> +    system "#{bin}/git-remote-gcrypt"
thanks, was able to do this… will push an  update

2016-12-10 16:50 UTC, bfontaine approved these changes

2017-01-09 22:12 UTC, woodruffw commented
Any update here @srl295?

2017-02-13 01:15 UTC, woodruffw commented
Closing due to inactivity.

2017-02-13 01:15 UTC, closed without merging

2017-02-18 07:38 UTC, srl295 commented
Fair enough. I'll try to get back on this.

El feb. 12, 2017 5:15 PM -0800, William Woodruff <notifications@github.com>, escribió:
>
> Closed #7025 (https://github.com/Homebrew/homebrew-core/pull/7025).
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub (https://github.com/Homebrew/homebrew-core/pull/7025#event-958903299), or mute the thread (https://github.com/notifications/unsubscribe-auth/AA0MsyYi-xs2dBUFchWoGNMjQW8RUw02ks5rb660gaJpZM4K11nh).
>
>
>