stern 1.0.1 (new formula)
Homebrew/homebrew-core pull request #7027
Opened 2016-11-17 23:09 UTC by mgoodness

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

New formula for a Kubernetes log-tailer from Wercker. The test (`stern --version`) isn't great, so I'm open to other suggestions.

2016-11-18 08:40 UTC, MikeMcQuaid requested changes

2016-11-18 08:40 UTC, MikeMcQuaid commented on Formula/stern.rb
> +    :revision => "3c8e6184b7a0a0cbc8dc78f219be0a49a007e861"
This doesn't seem to use submodules so we prefer https://github.com/wercker/stern/archive/1.0.1.tar.gz

2016-11-18 08:40 UTC, MikeMcQuaid commented on Formula/stern.rb
> +    (gopath/"src/github.com/wercker/stern").install contents
Can you symlink rather than `.install` here?

2016-11-18 20:41 UTC, mgoodness commented on Formula/stern.rb
> +    (gopath/"src/github.com/wercker/stern").install contents
Apparently not. I'm unable to pull dependencies via `govendor sync` if I symlink. Full disclosure: my golang-fu is not strong.

2016-11-20 10:37 UTC, MikeMcQuaid approved these changes

2016-11-20 10:38 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-20 10:38 UTC, closed without merging