fzf: make vim plugin available automatically
Homebrew/homebrew-core pull request #70543
Opened 2021-02-06 01:18 UTC by sj26

The fzf formula currently requires a manual installation step with vim. Other formulae such as [hub](https://github.com/Homebrew/homebrew-core/blob/master/Formula/hub.rb) avoid this by linking [their vimscript](https://github.com/github/hub/tree/master/share/vim/vimfiles) into the `share/vim/vimfiles` tree. So this adjusts the fzf formula to do the same thing.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2021-02-06 01:26 UTC, sj26 commented
I'm tempted to place the file into autoload instead, but didn't want to change too much at once.

2021-02-06 01:53 UTC, carlocab commented
Won't this break things for neovim users who are using the existing caveat for setting their `runtimepath`?

2021-02-06 01:54 UTC, sj26 commented
> Users who have the suggested configuration already after this change should continue to have a working installation after upgrading, although will have a superfluous entry on their runtime path.

2021-02-06 02:32 UTC, carlocab commented
>**neovim** users

Pretty sure **neovim** doesn't add `vim/vimfiles` subdirectories into your runtimepath.

2021-02-06 02:52 UTC, carlocab requested changes
Just checked. This definitely breaks things for neovim users.

2021-02-06 06:26 UTC, sj26 commented
Ah. What is neovim's default runtime path? Is it reasonable to expect vim plugins to work by default in neovim?

2021-02-06 10:41 UTC, carlocab commented
The plugin works in neovim with the existing installation and caveat. Indeed, vim plugins should just work in neovim.

It was the author of fzf who wrote the parts of the formula that you're changing. [1] It's probably best if we defer to them about the correct way to install this software.

[1] https://github.com/Homebrew/homebrew-core/commit/80794c96b7703f5d1f6e12c9f5d71be2e0236705

2021-02-06 13:52 UTC, clason commented
And just as a drive-by data point: I'd appreciate it if fzf was _not_ installed in (neo)vim by default. I like using it from the terminal, but there are better alternatives for neovim, and I don't want to have unused plugins possibly increasing startup time (not by a lot, granted, but it's the principle) and registering conflicting mappings.

2021-02-06 14:08 UTC, carlocab commented
>I'd appreciate it if fzf was not installed in (neo)vim by default

Same. I actually hate the idea of plugins adding themselves into my `rtp` without my having put them there. That's what my plugin manager is for. I just avoided sharing my personal opinion at first, since other users might've found this change (were it not broken) useful.

2021-02-08 04:02 UTC, sj26 commented
Righto, sounds like compatiblity is too hard. I'll symlink it into vimfiles myself.

2021-02-08 04:02 UTC, closed without merging