slimerjs: fix to use GitHub tarballs
Homebrew/homebrew-core pull request #7055
Opened 2016-11-18 19:03 UTC by umireon

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Closes #6809.

2016-11-18 19:05 UTC, umireon commented
The dependencies is also outdated.

2016-11-18 20:09 UTC, umireon commented
The probrematic XulRunner-based implementation is removed from 0.10.0.
https://docs.slimerjs.org/master/release-notes-0.10.html

2016-11-18 20:10 UTC, umireon commented on Formula/slimerjs.rb
> -  depends_on :macos => :leopard
Requiring 10.6+ is related to XulRunner and no longer necessary because XulRunner is excluded from SlimerJS.

2016-11-18 20:13 UTC, umireon commented on Formula/slimerjs.rb
> -        export SLIMERJSLAUNCHER=#{firefox_installation}/Contents/MacOS/firefox
Now SlimerJS automatically detects /Applications/Firefox.app.

2016-11-18 20:17 UTC, umireon commented on Formula/slimerjs.rb
> -      Note: If you use SlimerJS with an unstable version of Mozilla Firefox (>38.*)
This part is not Homebrew-specific. A clear explanation is on the official document.

2016-11-20 10:36 UTC, MikeMcQuaid requested changes

2016-11-20 10:36 UTC, MikeMcQuaid commented on Formula/slimerjs.rb
> +      https://docs.slimerjs.org/current/installation.html
This part isn't Homebrew-specific either so let's remove it.

2016-11-20 10:36 UTC, MikeMcQuaid commented on Formula/slimerjs.rb
> +    The configuration file is placed in:
`was installed in`

2016-11-20 10:36 UTC, MikeMcQuaid commented on Formula/slimerjs.rb
> +    if File.exist? "/Applications/Firefox.app/Contents/MacOS/firefox"
Can skip this `if`; this block primarily exists for our CI and it'll never be present there.

2016-11-20 11:08 UTC, umireon commented
Thank you for reviewing, @MikeMcQuaid 
I removed unnecessary things from this Formula.
`ENV["SLIMERJSLAUNCHER"]` was changed to be set explicitly to success both on CI and machines.

2016-11-20 12:12 UTC, MikeMcQuaid approved these changes

2016-11-20 12:12 UTC, merged

2016-11-20 12:12 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!