pike 8.0.276
Homebrew/homebrew-core pull request #7067
Opened 2016-11-19 02:09 UTC by hww3

new stable version of pike

2016-11-20 10:41 UTC, MikeMcQuaid commented
Please fill out the steps in the PR template.

Installation is failing on all platforms: https://bot.brew.sh/job/Homebrew%20Core/11716/version=any_sierra/testReport/junit/brew-test-bot/sierra/install_pike/

2016-11-20 10:41 UTC, MikeMcQuaid requested changes

2016-11-20 10:41 UTC, MikeMcQuaid commented on Formula/pike.rb
> -    if build.without? "machine-code"
If this option was removed then `option "with-machine-code", "Enables machine code"` should be removed above, too.

2016-11-21 17:54 UTC, hww3 commented
There appears to be a build problem when both X11 and the MacOS SDK are installed (as is the case on the build farm): 2 versions of GL headers. I'll get a patch committed upstream.

2016-11-21 17:54 UTC, closed without merging