calc 2.18
Homebrew/homebrew-core pull request #70708
Opened 2021-02-08 17:58 UTC by chenrui333

Created with `brew bump-formula-pr`.

2021-02-08 18:11 UTC, bayandin requested changes

2021-02-08 18:11 UTC, bayandin commented on Formula/calc.rb
> +  url "http://www.andre-simon.de/zip/ansifilter-2.18.tar.bz2"
Hmm, this URL doesn't look like `calc`

2021-02-08 19:00 UTC, chenrui333 commented on Formula/calc.rb
> +  url "http://www.andre-simon.de/zip/ansifilter-2.18.tar.bz2"
my bad.

2021-02-09 08:37 UTC, SMillerDev approved these changes

2021-02-09 11:29 UTC, bayandin approved these changes

2021-02-09 12:22 UTC, closed without merging