Addition of kops 1.4.1 Formula
Homebrew/homebrew-core pull request #7193
Opened 2016-11-23 18:18 UTC by WillPlatnick

This commit adds a formula that installs kops, a tool for Kubernetes orchestration.

2016-11-24 02:27 UTC, chrislovecnm requested changes
You are going to need to depend on kubectl as well. I believe there is already a brew for it.

2016-11-24 10:04 UTC, MikeMcQuaid requested changes

2016-11-24 10:04 UTC, MikeMcQuaid commented on Formula/kops.rb
> +    cd buildpath do
This is unnecessary; you'll be `cd`d back there after you leave the `cd kopspath do` block.

2016-11-24 10:04 UTC, MikeMcQuaid commented on Formula/kops.rb
> +      system "make"
Alternatively, `system "make", "-C", kopspath` and skip the `cd`

2016-11-24 10:04 UTC, MikeMcQuaid commented on Formula/kops.rb
> +      bin.install("bin/kops")
Is there no `make install` we can use?

2016-11-24 13:24 UTC, WillPlatnick commented on Formula/kops.rb
> +      bin.install("bin/kops")
There is not. make installs the binary into GOPATH and leaves them there.

2016-11-24 13:38 UTC, WillPlatnick commented on Formula/kops.rb
> +      system "make"
Will push fix

2016-11-24 13:38 UTC, WillPlatnick commented on Formula/kops.rb
> +    cd buildpath do
Will push fix

2016-11-24 13:51 UTC, WillPlatnick commented
@MikeMcQuaid Requested changes addressed and squashed

2016-11-25 08:32 UTC, MikeMcQuaid approved these changes

2016-11-25 08:41 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `kops 1.4.1 (new formula)`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

2016-11-25 08:42 UTC, closed without merging