Properly setting a fake CPUID for GMP
Homebrew/homebrew-core pull request #7215
Opened 2016-11-24 14:11 UTC by smtrat

GMP exports its compilation options in its header file which may contain incorrect architecture optimizations.
This patch ensures that GMP builds with -mcore2 and also exports this.

See #7054

2016-11-24 14:18 UTC, ilovezfs commented
Probably want to use `#{Hardware.oldest_cpu}` not `core2` and scope this to `if build.bottle?`. Ideally, it would also respect ` --bottle-arch=`

2016-11-24 14:25 UTC, smtrat commented
I just copied `-march=core2` from https://gist.github.com/ilovezfs/ad883542d12bf1a0bb4db08a5ec3f1e8 you referenced in #7054 and assumed that everything in brew would be configured this way.
Could you do these changes? I neither use OSX myself, nor do I know how to write ruby or how these formulas are supposed to work...

2016-11-26 13:26 UTC, MikeMcQuaid requested changes

2016-11-26 13:26 UTC, MikeMcQuaid commented on Formula/gmp.rb
> +    args << "--enable-fake-cpuid" << "GMP_CPU_TYPE=#{Hardware.oldest_cpu}" << "--enable-fat" if build.build_32_bit? || build.bottle?
```ruby
if build.build_32_bit? || build.bottle?
  args << "--enable-fat" << "--enable-fake-cpuid" << "GMP_CPU_TYPE=#{Hardware.oldest_cpu}"
end
```

Also, what is `--enable-fat` doing?

2016-11-26 13:26 UTC, MikeMcQuaid commented
Installation is failing on all platforms: https://bot.brew.sh/job/Homebrew%20Core/12014/version=any_sierra/testReport/junit/brew-test-bot/sierra/install_gmp/

2016-11-28 14:14 UTC, smtrat commented
I've noticed. `--enable-fat` seems to be required when specifying `--enable-fake-cpuid`. Afaik, `--enable-fat`build a library that contains specific instructions for all platforms and selects at runtime which to choose.

There is a file that is linked into all tests that triggers these errors when `GMP_CPU_TYPE` is not set. I can fix this by setting `GMP_CPU_TYPE=#{Hardware.oldest_cpu}` for the tests, but I'm not sure whether we want to do that: It kind of suggests that end users also have to do this when regularly using libgmp (though this would not be the case, as far as I can tell).

2016-11-28 14:35 UTC, MikeMcQuaid commented
> Afaik, --enable-fatbuild a library that contains specific instructions for all platforms and selects at runtime which to choose.

This doesn't seem to be desirable for what's a fix for a cosmetic change.

2016-11-28 15:29 UTC, smtrat commented
Maybe this would be a reasonable change anyway? According to gmp, "this means more code, but gives good performance on all x86 chips." Does not seem to bad...

2016-11-28 15:40 UTC, MikeMcQuaid commented
Are they including x86_64 in that?

2016-11-28 15:58 UTC, smtrat commented
Though I'm by no means an expert here, it seems so. `mpn/fat.c` seems to deal with this and it explicitly mentions that it was originally `x86_32 code` and has been ported to `x86_64`. Furthermore, there is a whole `mpn/x86_64` directory...

2016-12-02 08:37 UTC, MikeMcQuaid commented
Ok, seems fine then if you adjust the code as suggested above and we can get it compiling.

2016-12-02 13:12 UTC, MikeMcQuaid commented on Formula/gmp.rb
> +    system "make", "check", "GMP_CPU_TYPE=#{Hardware.oldest_cpu}"
Could this perhaps be set in both places with `ENV["GMP_CPU_TYPE"] = Hardware.oldest_cpu`?

2016-12-02 13:22 UTC, smtrat commented on Formula/gmp.rb
> +    system "make", "check", "GMP_CPU_TYPE=#{Hardware.oldest_cpu}"
I guess so. I just added this change, let's see whether it works.

2016-12-02 13:28 UTC, MikeMcQuaid approved these changes

2016-12-02 14:10 UTC, MikeMcQuaid commented
Looks like this breaks a bunch of things at runtime e.g. `gcc`: https://bot.brew.sh/job/Homebrew%20Core/12495/version=any_sierra/testReport/junit/brew-test-bot/sierra/test_gcc/

2017-01-08 07:02 UTC, ilovezfs commented
superseded by https://github.com/Homebrew/homebrew-core/pull/8597

2017-01-08 07:03 UTC, ilovezfs commented
@smtrat thanks for this PR nonetheless

2017-01-08 07:03 UTC, closed without merging