beansdb: add plist_options and a test
Homebrew/homebrew-core pull request #7218
Opened 2016-11-24 21:22 UTC by Moisan

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The plist_options part is related to issue  [#4029](https://github.com/Homebrew/homebrew-core/issues/4029).

2016-11-25 08:37 UTC, MikeMcQuaid requested changes

2016-11-25 08:37 UTC, MikeMcQuaid commented on Formula/beansdb.rb
> +  revision 1
Don't need a `revision` for this as we're not altering the package contents. `revision` is used to force an upgrade for all users so is only really needed for package contents changes (and even then only really widespread bug fixes).

2016-11-25 20:54 UTC, Moisan commented
Testbot failed on `brew doctor`.

2016-11-25 22:17 UTC, mistydemeo commented
@BrewTestBot test this please

2016-11-26 13:15 UTC, MikeMcQuaid approved these changes

2016-11-26 13:27 UTC, merged

2016-11-26 13:27 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!