clickhouse 1.1.54074 (new formula)
Homebrew/homebrew-core pull request #7222
Opened 2016-11-25 06:54 UTC by hatarist

- [v] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [v] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [v] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [v] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Here's an OS X build guide: https://github.com/yandex/ClickHouse/blob/master/doc/build_osx.md
In short, we have to recompile boost using gcc-6, hence the `HOMEBREW_CC`/`HOMEBREW_BUILD_FROM_SOURCE` overriding before `depends_on "boost"`.

2016-11-25 08:06 UTC, MikeMcQuaid requested changes

2016-11-25 08:06 UTC, MikeMcQuaid commented on Formula/clickhouse.rb
> +  ENV["HOMEBREW_BUILD_FROM_SOURCE"] = "1"
We can't do this. This and Boost need to be build using Clang.

2016-11-25 08:06 UTC, MikeMcQuaid commented on Formula/clickhouse.rb
> +  depends_on "gettext" => :build
Are none of these linked to at runtime?

2016-11-25 08:06 UTC, MikeMcQuaid commented on Formula/clickhouse.rb
> +    inreplace "libs/libcommon/src/get_revision_lib.sh", /git.*\n.*/, "echo " + version.to_s[-5..-1]
Use a Git checkout instead of patching.

2016-11-25 08:06 UTC, MikeMcQuaid commented on Formula/clickhouse.rb
> +    # Copy configuration files
Don't need this comment.

2016-11-25 08:06 UTC, MikeMcQuaid commented on Formula/clickhouse.rb
> +      s.gsub! "<!-- <max_open_files>262144</max_open_files> -->", "<max_open_files>262144</max_open_files>"
Why isn't this the default?

2016-11-25 08:06 UTC, MikeMcQuaid commented on Formula/clickhouse.rb
> +    cd "build" do
`mkdir "build" do`

2016-11-25 08:06 UTC, MikeMcQuaid commented on Formula/clickhouse.rb
> +      bin.install "#{buildpath}/build/dbms/src/Server/clickhouse" => "clickhouse-server"
Is there no `make install` we can use? If not, please request one from upstream.

2016-11-25 08:06 UTC, MikeMcQuaid commented on Formula/clickhouse.rb
> +  end
Don't need any of these caveats as they aren't Homebrew specific or different to normal.

2016-11-25 08:06 UTC, MikeMcQuaid commented on Formula/clickhouse.rb
> +    system "#{bin}/clickhouse-client", "--help"
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2016-11-25 08:23 UTC, hatarist commented on Formula/clickhouse.rb
> +    system "#{bin}/clickhouse-client", "--help"
Thanks a lot for taking your time to review!

2016-12-01 03:13 UTC, woodruffw commented
Any update here @hatarist?

2016-12-05 03:22 UTC, hatarist commented
I'm very sorry, I have little to no experience with cmake/make and it seems that the project has a lot of issues regarding build-scripts. (see [clickhouse issue #220 (ru->en translation)](https://translate.google.com/translate?depth=1&hl=en&ie=UTF8&prev=_t&rurl=translate.google.com&sl=ru&tl=en&u=https://github.com/yandex/ClickHouse/issues/220))
In short, people are blaming the poor code quality of the build-scripts. Cons are: it looks for the static libraries, it doesn't use FindOpenSSL/FindBoost, it doesn't look for termcap/libz libraries (as it's used in the project), it doesn't use cmake -D options and uses environment variables instead.

I also have no idea what to do with
> We can't do this. This and Boost need to be build using Clang.
:(

Sorry again. I guess this pull request should be closed until most of these things could be fixed?

2016-12-05 03:42 UTC, woodruffw commented
Don't worry about it! Thanks for making an effort to build this despite its build system difficulties. I'll close for now, but future PR(s) for this formula are always welcome.

Thanks again!

2016-12-05 03:42 UTC, closed without merging