libgosu 0.10.7
Homebrew/homebrew-core pull request #7223
Opened 2016-11-25 07:01 UTC by pmer

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

http://libgosu.org

Previous attempt from December 5th, 2014 at https://github.com/Homebrew/legacy-homebrew/pull/34700

Issue from previous attempt was that the upstream wasn't providing a `.dylib`. Now they are.

2016-11-25 08:38 UTC, MikeMcQuaid commented
Install is failing: https://bot.brew.sh/job/Homebrew%20Core/12010/version=any_sierra/testReport/junit/brew-test-bot/sierra/install_libgosu/

Looks like a `depends_on "pkg-config" => :build` is needed.

2016-11-25 10:17 UTC, pmer commented
@MikeMcQuaid Thanks!

2016-11-26 13:24 UTC, MikeMcQuaid requested changes

2016-11-26 13:24 UTC, MikeMcQuaid commented on Formula/libgosu.rb
> +  end
Just make this `head "https://github.com/gosu/gosu.git"`

2016-11-26 13:24 UTC, MikeMcQuaid commented on Formula/libgosu.rb
> +    cd "cmake/build" do
`mkdir "cmake/build" do`. Also, I'd favour just `build` unless this needs to be in the `cmake` directory (no worries if it does).

2016-11-26 13:24 UTC, MikeMcQuaid commented on Formula/libgosu.rb
> +    Pathname("test.cpp").write <<-EOS.undent
`(testpath/"test.cpp").write <<-EOS.undent`

2016-11-26 13:24 UTC, MikeMcQuaid commented on Formula/libgosu.rb
> +    system ENV.cxx, "test.cpp", "-L#{lib}", "-lgosu", "-I#{include}", "-std=c++11"
Would be good to also run the outputted executable.

2016-11-27 06:16 UTC, pmer commented on Formula/libgosu.rb
> +    system ENV.cxx, "test.cpp", "-L#{lib}", "-lgosu", "-I#{include}", "-std=c++11"
I've updated the test program to quit as soon as the window appears on-screen.

2016-11-27 06:18 UTC, pmer commented
@MikeMcQuaid Should be ready for another look.

2016-11-28 08:53 UTC, MikeMcQuaid approved these changes

2016-11-28 08:56 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-28 08:56 UTC, closed without merging