google-java-format 1.1 (new formula)
Homebrew/homebrew-core pull request #7230
Opened 2016-11-25 14:21 UTC by dlackty

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-11-26 13:22 UTC, MikeMcQuaid requested changes

2016-11-26 13:22 UTC, MikeMcQuaid commented on Formula/google-java-format.rb
> +    path.write "public class Foo{\n}\n"
`(testpath/"foo.java").write "public class Foo{\n}\n"`

2016-11-26 13:22 UTC, MikeMcQuaid commented on Formula/google-java-format.rb
> +    assert_match output, "public class Foo {}\n"
`assert_match "public class Foo {}", shell_output("#{bin}/google-java-format foo.java")

2016-11-27 03:45 UTC, dlackty commented
@MikeMcQuaid Updated and CI passed. Thanks for reviewing!

2016-11-28 08:52 UTC, MikeMcQuaid approved these changes

2016-11-28 08:56 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-28 08:56 UTC, closed without merging