yelp-tools: convert yelp-xsl to a resource (#7243)
Homebrew/homebrew-core pull request #7260
Opened 2016-11-26 16:06 UTC by ajdavis

yelp-tools is the only package that depends on yelp-xsl, and both
packages must have the same version. Better to make yelp-xsl a resource
of yelp-tools instead of a distinct package that can get out of sync.

Closes #7243

2016-11-26 16:08 UTC, ajdavis commented on Formula/yelp-tools.rb
> +      ENV.append_path "PKG_CONFIG_PATH", "#{prefix}/share/pkgconfig"
This syntax works, I tried this but it had no effect (ENV was the same after):
```
      ENV.append_path "PKG_CONFIG_PATH", "#{lib}/pkgconfig"
```
However, the syntax I'm using here doesn't match how other formulas do it, and "brew audit" complains:
```
yelp-tools:
  * "#{prefix}/share" should be "#{share}"
Error: 1 problem in 1 formula
```

2016-11-26 22:10 UTC, MikeMcQuaid requested changes

2016-11-26 22:10 UTC, MikeMcQuaid commented on Formula/yelp-tools.rb
> +  depends_on "gtk+3" => :run
Don't need the `:run` here.

2016-11-26 22:10 UTC, MikeMcQuaid commented on Formula/yelp-tools.rb
> +      ENV.append_path "PKG_CONFIG_PATH", "#{prefix}/share/pkgconfig"
`ENV.append_path "PKG_CONFIG_PATH", "#{share}/pkgconfig"`

2016-11-26 22:10 UTC, MikeMcQuaid commented on Formula/yelp-tools.rb
> +    assert (share/"pkgconfig/yelp-xsl.pc").exist?
Add a second argument to these for the assertion message so we have a better output if they fail. Could consider looping through these filenames and make `"#{filename} doesn't exist"` as the assertion message

2016-11-26 22:10 UTC, MikeMcQuaid commented on Formula/yelp-tools.rb
> +
`yelp_tools_version = version`

2016-11-26 22:10 UTC, MikeMcQuaid commented on Formula/yelp-tools.rb
> +    url "https://download.gnome.org/sources/yelp-xsl/3.18/yelp-xsl-3.18.0.tar.xz"
`url "https://download.gnome.org/sources/yelp-xsl/3.18/yelp-xsl-#{yelp_tools_version}.tar.xz"` or similar to avoid these getting out of sync.

2016-11-26 23:22 UTC, ajdavis commented
Thanks for the review! New patch.

2016-11-28 09:08 UTC, MikeMcQuaid approved these changes

2016-11-28 09:20 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-11-28 09:22 UTC, closed without merging

2016-11-29 07:06 UTC, tschoonj commented
Sorry for coming a bit late to the party but I have some concerns on what was done here:

Though I do not disagree with turning yelp-xsl into a resource, I do wonder why we are forcing a version here that is three stable releases behind the latest. Is there really no way to make this work with yelp-xsl 3.20.1?

2016-11-29 09:37 UTC, MikeMcQuaid commented
@tschoonj No worries. Totally fine with updating this to the latest version now we've got the approach nailed down.

2016-11-29 14:28 UTC, ajdavis commented
Update to 3.20.1 in progress, but I could use some help: https://github.com/Homebrew/homebrew-core/pull/7386