SED=/usr/bin/sed shim workaround unnecessary as of Homebrew/brew#10802
Homebrew/homebrew-core pull request #72637
Opened 2021-03-07 01:37 UTC by liyang

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] ~~Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?~~
- [ ] ~~Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?~~
- [ ] ~~Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?~~

-----

Waiting on Homebrew/brew#10802 to be merged. See also Homebrew/linuxbrew-core#22483.

I'm expecting checks to fail for now with

> Error: Files were found with references to the Homebrew shims directory.

hence this PR is still in draft. Once the above is merged I'll trigger another set of checks.

2021-03-07 01:54 UTC, carlocab commented
Thanks for your PR.

Please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings, and make sure to modify only one formula file per commit. Thus, your PR should consist of 21 separate commits.

Refer to the [documentation](https://docs.brew.sh/Formula-Cookbook#commit) for more details.

2021-03-07 03:35 UTC, liyang commented
> Please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings, and make sure to modify only one formula file per commit. Thus, your PR should consist of 21 separate commits.

Gladly! Too many projects squash commits and I've gotten used to that style despite hating it!

2021-03-07 04:31 UTC, liyang commented
> Refer to the [documentation](https://docs.brew.sh/Formula-Cookbook#commit) for more details.

Sorry I skimmed through that too quickly, as I thought was just a long HOWTO on `git`.

@carlocab None of the commit message summaries exceed 50 _characters[¹](https://github.com/Homebrew/homebrew-core/pull/72637/commits/e02a8735b94e3d2776cd00a5ce9710e479c62e92)_ now, package names inclusive. :)

2021-03-07 10:13 UTC, carlocab commented
Most of these should probably be merged without bottles. Adding a `do not merge` label to indicate that should be done manually.

2021-03-08 03:04 UTC, Rylan12 commented
I think we'll need CI to run, though, to verify that the changes don't break anything. So a normal merge is fine just no need for revision bumps. I don't think a new rebuild would be a bad thing, right?

2021-03-08 03:07 UTC, carlocab commented
In principle no, but a rebuild will discard some older bottles (i.e. some bottles for High Sierra, etc). No need to discard those bottles for what should effectively be a no-op.

2021-03-08 03:08 UTC, Rylan12 commented
Oh yeah, you're right. Good call 👍

2021-03-08 17:57 UTC, Bo98 requested changes

2021-03-08 17:57 UTC, Bo98 commented on Formula/quilt.rb
> -    end
This one was not to dodge the shim. It's so we use the one `gnu-sed` formula instead.

2021-03-22 21:20 UTC, iMichka commented
I think this can be rebased and finished, a new brew release has been made and the sed shim is now gone.

2021-04-13 07:59 UTC, carlocab commented
Ping, @liyang?

2021-05-12 00:05 UTC, closed without merging