ncurses: build without Ada on Linux
Homebrew/homebrew-core pull request #73529
Opened 2021-03-19 17:28 UTC by lexicol

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2021-03-19 17:38 UTC, carlocab commented on Formula/ncurses.rb
> +    end
I want to try to preserve `git blame` here. Can you just put
```ruby
args = []
on_linux do
  # Homebrew GCC does not support Ada
  # https://github.com/Homebrew/linuxbrew-core/pull/2841
  args << "--without-ada"
end
```
at the start of the formula and then add `*args` as the last argument in the list, so you don't need to refactor them all into an array?

2021-03-20 01:32 UTC, carlocab requested changes
See above. Thanks!

2021-03-20 13:13 UTC, lexicol commented
I wonder, would it make sense to disable Ada bindings on macOS too?

2021-03-20 15:53 UTC, carlocab commented
Sure; I guess it doesn't hurt.

2021-04-01 08:53 UTC, carlocab commented
Merged in https://github.com/Homebrew/homebrew-core/pull/74319

2021-04-01 08:53 UTC, closed without merging