icu4c.rb: Correct the SVN repository URL
Homebrew/homebrew-core pull request #7357
Opened 2016-11-28 19:04 UTC by moderndeveloperllc

This fixes #7249.

2016-11-29 05:36 UTC, woodruffw commented
```
==> /usr/local/Cellar/mdk/1.2.9_1/bin/mixasm hello
hello.mixal:12: Warnung: Operand von ALF-Pseudoinstruktion hat weniger als 5 Zeichen
hello.mixal:0: Warnung: Symbol nicht definiert: halt
(2 Warnung(en))
Error: mdk: failed
<"Program loaded. Start address: 1000\nRunning ...\nMIXAL HELLO WORLD                                                     \n... done\n"> expected but was
<"Programm geladen.  Startadresse: 1000\nArbeite ...\nMIXAL HELLO WORLD                                                     \n... fertig\n">.
```

Very strange. Looks like we're hitting some accidental internationalization somewhere, and only on the Sierra CI.

2016-11-29 05:37 UTC, woodruffw commented
@BrewTestBot test this please

2016-11-29 16:16 UTC, moderndeveloperllc commented
@woodruffw New to Homebrew PRs. Is this something I need to fix, or is this a tooling issue?

2016-11-29 16:47 UTC, woodruffw commented
I don't believe the failure's being caused by the new `head`, so it's probably a tooling/CI issue. I'll look into this.

2016-11-29 21:55 UTC, DomT4 commented
Hey it's the German test again @ilovezfs 😸

2016-11-30 17:36 UTC, woodruffw commented
@moderndeveloperllc For the time being, let's just add `ENV["LANG"] = "en_US.UTF-8"` to the top of the `test` block explaining that it's a CI discrepancy.

2016-12-01 00:19 UTC, ilovezfs commented
```
==> brew test --verbose mdk
==> FAILED
Testing mdk
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161130-89361-4zaxi.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mdk.rb --verbose
==> /usr/local/Cellar/mdk/1.2.9_1/bin/mixasm hello
hello.mixal:12: Warnung: Operand von ALF-Pseudoinstruktion hat weniger als 5 Zeichen
hello.mixal:0: Warnung: Symbol nicht definiert: halt
(2 Warnung(en))
Error: mdk: failed
<"Program loaded. Start address: 1000\nRunning ...\nMIXAL HELLO WORLD                                                     \n... done\n"> expected but was
<"Programm geladen.  Startadresse: 1000\nArbeite ...\nMIXAL HELLO WORLD                                                     \n... 
```

it's mdk not icu4c that needs the language fix

2016-12-02 08:50 UTC, MikeMcQuaid requested changes

2016-12-02 08:50 UTC, MikeMcQuaid commented on Formula/icu4c.rb
> +    # CI dependancy
Remove this comment.

2016-12-02 08:50 UTC, MikeMcQuaid commented on Formula/icu4c.rb
> +    ENV["LANG"] = "en_US.UTF-8"
If I understood @ilovezfs correctly this line isn't needed.

2016-12-02 08:50 UTC, MikeMcQuaid commented on Formula/mdk.rb
> +    # CI dependancy
Remove this comment.

2016-12-03 03:01 UTC, woodruffw commented
@moderndeveloperllc The mdk fix is probably best isolated to a separate PR (I opened #7502 for it), so you can pop that commit off.

2016-12-03 11:21 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `icu4c: correct the HEAD SVN repository URL.`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

2016-12-03 11:21 UTC, MikeMcQuaid commented
Merged in 5374bd5ab2f700f7b0f121f67d96636365bd5521

2016-12-03 11:21 UTC, closed without merging