Update zsh-completions.rb
Homebrew/homebrew-core pull request #73628
Opened 2021-03-21 18:50 UTC by pejvan

Running `compaudit` revealed two additionnal repertories with incorrect settings in my installation:

zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? ncompinit: initialization aborted
$ ~ compaudit
There are insecure directories:
/usr/local/bin
/usr/local/share

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2021-03-21 19:05 UTC, pejvan commented
Running `compaudit` revealed two additionnal repertories with incorrect settings in my installation:

```zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? ncompinit: initialization aborted
$ ~ compaudit
There are insecure directories:
/usr/local/bin
/usr/local/share```

So adding these two repertories in the tip provided to fix the first one

2021-03-22 03:43 UTC, carlocab requested changes
I don't think `chmod`ding `${HOMEBREW_PREFIX}/{bin,share}` is necessary in a standard installation of Homebrew. The fact that you needed to do so is probably a peculiarity of your setup, so I'm a bit hesitant to recommend this to everyone who installs this formula.

2021-03-22 03:43 UTC, carlocab commented
And, for future reference, please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings. Refer to the [documentation](https://docs.brew.sh/Formula-Cookbook#commit) for more details.

2021-03-22 07:16 UTC, pejvan commented
Hey @carlocab — good point about the standard installation of Homebrew. For what it's worth, I haven't tweaked anything in my install, and I would consider it very much as vanilla as possible.

2021-03-22 11:51 UTC, carlocab commented
Have you installed non-Homebrew software into `HOMEBREW_PREFIX`, though? Because that can affect the permissions of the directories in it.

2021-03-22 20:26 UTC, pejvan commented
I haven't, I actually ran the entire "uninstall" script yesterday, prior to reinstalling Brew from scratch with the install script.
It's during the installation of the zsh packages that the error occurred and hence I thought I'd fix it and submit a PR to fix it for everyone.

2021-03-27 13:49 UTC, carlocab commented
Let's leave this open for a bit and see if someone else might find these additional instructions useful.

2021-03-28 15:01 UTC, pejvan commented
Sure. Thanks.
On 27 Mar 2021, 14:50 +0100, Carlo Cabrera ***@***.***>, wrote:
> Let's leave this open for a bit and see if someone else might find these additional instructions useful.
> —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-26 00:20 UTC, closed without merging