Patching bug in Xplanet 1.3.1
Homebrew/homebrew-core pull request #7372
Opened 2016-11-29 04:45 UTC by blogabe

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Simple mistake/fix when run with `-num_times=2`

I believe based on https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md that this will be the easiest way to fix a bug in Xplanet 1.3.1

2016-11-30 17:42 UTC, woodruffw requested changes

2016-11-30 17:42 UTC, woodruffw commented on Formula/xplanet.rb
> +    inreplace "src/libdisplay/DisplayOutput.cpp", "if (stopIndex > 1)", "if (stopIndex > 0)"
I think we'll probably want to use a `patch` block here instead, as that forum link suggests that a patch is available in the SVN repo.

2016-11-30 17:49 UTC, woodruffw commented on Formula/xplanet.rb
> +    inreplace "src/libdisplay/DisplayOutput.cpp", "if (stopIndex > 1)", "if (stopIndex > 0)"
Not sure if SourceForge allows for a raw patch download, so https://sourceforge.net/p/xplanet/code/208/tree//trunk/src/libdisplay/DisplayOutput.cpp?diff=5056482efd48f8457fc7910a:207 should probably just be added to the formula-patches repo.

2016-11-30 18:30 UTC, blogabe commented on Formula/xplanet.rb
> +    inreplace "src/libdisplay/DisplayOutput.cpp", "if (stopIndex > 1)", "if (stopIndex > 0)"
Cool.  Unsure how to do that.  Can you help guide?

2016-11-30 18:38 UTC, woodruffw commented on Formula/xplanet.rb
> +    inreplace "src/libdisplay/DisplayOutput.cpp", "if (stopIndex > 1)", "if (stopIndex > 0)"
Sure!

In this case, you'll need to submit a PR to [formula-patches](https://github.com/Homebrew/formula-patches) with the patch in the URL above - name it something like `xplanet/xplanet-1.3.1-ntimes.patch`. 

Then, in this formula, add a `patch` block that looks like this (example comes from `cctools.rb`):

```ruby
patch :p0 do
    url "https://raw.githubusercontent.com/Homebrew/formula-patches/db27850/cctools/cctools-829-lto.patch"
    sha256 "8ed90e0eef2a3afc810b375f9d3873d1376e16b17f603466508793647939a868"
end
```

(Replace the `url` above with the patch you submitted).

2016-11-30 19:59 UTC, blogabe commented
Created PR https://github.com/Homebrew/formula-patches/pull/92 in formula-patches

2016-11-30 21:34 UTC, woodruffw commented on Formula/xplanet.rb
> +    inreplace "src/libdisplay/DisplayOutput.cpp", "if (stopIndex > 1)", "if (stopIndex > 0)"
Do I need the sha256 as well, and if so, is it based on the patch file or...?
Yep, and yep.

2016-11-30 22:11 UTC, blogabe commented
Thanks, @woodruffw 

I think I did it right.  Let me know if there's anything additional.  Appreciate the help and learning something new.

2016-11-30 22:47 UTC, woodruffw requested changes

2016-11-30 22:47 UTC, woodruffw commented on Formula/xplanet.rb
> +    patch :p0 do
The `patch` block needs to be outside of the `install` method :wink:

2016-11-30 22:47 UTC, woodruffw commented on Formula/xplanet.rb
> +      url "https://raw.githubusercontent.com/Homebrew/formula-patches/f952f1d719d2e1fb86784d85c28ba1c3d0f4eed4/xplanet/xplanet-1.3.1-ntimes.patch"
You can use the short-hash version here:

```
  url "https://raw.githubusercontent.com/Homebrew/formula-patches/f952f1d/xplanet/xplanet-1.3.1-ntimes.patch" 
```

2016-11-30 22:49 UTC, woodruffw commented
> I think I did it right. Let me know if there's anything additional. 

Two small things, but this is getting close to being finished :+1:

> Appreciate the help and learning something new.

Always a pleasure!

2016-12-01 01:40 UTC, blogabe commented
Hhmm... don't know why this is failing?  Error message indicated a problem with the patch file, but it looked fine in that repo.

2016-12-01 02:05 UTC, woodruffw commented
@blogabe It needs to be `patch :p2`, not `patch :p0` to align the prefix of the patch with the source tree correctly. That was my fault, fixing that should correct the build.

2016-12-01 02:53 UTC, woodruffw approved these changes

2016-12-01 02:56 UTC, closed without merging

2016-12-01 02:57 UTC, woodruffw commented
Thanks @blogabe, great work!

2016-12-02 08:49 UTC, MikeMcQuaid commented on Formula/xplanet.rb
> +    url "https://raw.githubusercontent.com/Homebrew/formula-patches/f952f1d/xplanet/xplanet-1.3.1-ntimes.patch"
@blogabe Can you please submit this patch to the upstream developers of this project and add a link to the upstream patch submission and explanation of why the patch is needed in a comment in the formula file. Thanks!

@woodruffw Just FYI for future that that's a blocker on accepting patches.

2016-12-02 13:05 UTC, woodruffw commented
@MikeMcQuaid This patch was produced by upstream: http://xplanet.sourceforge.net/FUDforum2/index.php?t=msg&th=671&start=0&S=07920715eb9a74361428ce957b99ae66

It's in their SVN: https://sourceforge.net/p/xplanet/code/208/tree//trunk/src/libdisplay/DisplayOutput.cpp?diff=5056482efd48f8457fc7910a:207

I thought there was a comment referencing that, but I guess it got squashed out while this was being worked on. Sorry, I'll add one in a bit!

2016-12-02 13:05 UTC, MikeMcQuaid commented
> I thought there was a comment referencing that, but I guess it got squashed out while this was being worked on. Sorry, I'll add one in a bit!

Great, thanks!

2016-12-02 15:39 UTC, blogabe commented
So I'm good here?

2016-12-02 15:51 UTC, MikeMcQuaid commented
Yep, thanks!