cmd/aspell-dictionaries: don't use private API
Homebrew/homebrew-core pull request #74111
Opened 2021-03-29 11:56 UTC by Bo98

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is unfortunate and I don't like using `open-uri`, but we can't be using private API in homebrew-core.

2021-03-29 12:00 UTC, Bo98 commented
Oh `Resource` is private too? This is a bit of a mess really.

2021-03-29 12:01 UTC, MikeMcQuaid commented
> but we can't be using private API in homebrew-core.

I mean: we can. If we're already using it: let's just make it a public API. That's infinitely preferable to using `open-uri` which is known to be broken.

2021-03-29 12:06 UTC, Bo98 commented
I'm fine with whatever. See also: https://github.com/Homebrew/homebrew-cask-versions/pull/10567#issuecomment-808591738

cc @reitermarkus

2021-03-29 22:36 UTC, mitchblank commented
This is similar to something I was looking at awhile ago but didn't follow up on with my aborted #70649 PR -- there are a number of formulae that download a subresource but don't want it extracted.  The normal solution seems to be use `Resource#cached_download` (which seems to be private?) to get at its underling filename, but it's not even clear to me that what they're doing is correct.  

It seems to me that it would be beneficial to have a public API for this to make it easier to use subresources for non-tarball-like files without resorting to private interfaces.  Something like:
```
  # Blah blah blah
  #
  # @api public
  def filename
    fetch unless downloaded?
    cached_download
  end
```

2021-03-29 22:45 UTC, Bo98 commented
> there are a number of formulae that download a subresource but don't want it extracted.

`using: :nounzip`?

2021-03-29 22:49 UTC, mitchblank commented
> `using: :nounzip`?

Ah, I have to admit that I wasn't aware of that; I'll have to investigate.

Doesn't seem as popular, but I'm not sure if they cover the exact same use-case
```
$ rg -lw cached_download | wc -l
      17
$ rg -lw nounzip | wc -l
       7
```
...that's probably why when I was trying to figure out how to do something similar I found `cached_download` first

2021-03-30 00:35 UTC, reitermarkus commented
> let's just make it a public API.

I'd say we need something like `@api internal`, which is basically: Public for Homebrew-internal use across all repos, private for third parties.

Regarding `SystemCommand::Result`, some cask are using the `Open3`-like API provided by it, i.e.

```ruby
stdout, stderr, status = system_command 'asdf'
```

None are using the `status`, however, since `system_command` in casks is always `must_succeed: true`.
Also, none are currently using `stderr`.

So effectively, only the first element of `SystemCommand::Result#to_ary` is currently public.

In any case, we want to make as little of `SystemCommand::Result` public as possible.

2021-03-30 00:57 UTC, Bo98 commented
> I'd say we need something like `@api internal`, which is basically: Public for Homebrew-internal use across all repos, private for third parties.

I'm very uncertain about this for _all_ repos. It would make sense for repos like Homebrew/test-bot which do some quite unique things, but I don't think it does for things like Homebrew/bundle, Homebrew/command-not-found and Homebrew/core.

A lot of our taps originated from third parties. Homebrew/bundle, Homebrew/command-not-found etc were all started outside of Homebrew before being integrated. Are we saying that what those repos are currently doing (if they use internal APIs) should not be replicated by anyone else? It feels weird to convert a former outside repo to be that way.

Homebrew/core formulae is another one. A lot of people look at Homebrew/core as an example of how to model their third party taps - this includes the more obscure parts like audit exceptions and commands. `brew extract` even takes our formulae as-is for use in third party taps.

If we struggle so hard to stick to public API, why do we expect everyone else to? Does it not indicate gaps in our public API?

2021-03-30 04:38 UTC, reitermarkus commented
> we struggle so hard to stick to public API

We struggle so hard because `@api private` is a relatively recent addition to the codebase, prior to that everything was public.

My thinking is this: If someone needs a private API for some external command, they should make an argument for said API to be made public. The same goes for our own repos, expect that we can avoid having to deprecate anything since we control all uses of an internal API.

2021-03-30 07:55 UTC, MikeMcQuaid commented
> I'm very uncertain about this for _all_ repos. It would make sense for repos like Homebrew/test-bot which do some quite unique things, but I don't think it does for things like Homebrew/bundle, Homebrew/command-not-found and Homebrew/core.

Agreed. I think `test-bot` can even use private APIs because it's so inherently coupled (and easy to fix).

> My thinking is this: If someone needs a private API for some external command, they should make an argument for said API to be made public. The same goes for our own repos, expect that we can avoid having to deprecate anything since we control all uses of an internal API.

I think others are likely to just use internal APIs regardless of what we tell them to do.

2021-03-30 20:28 UTC, reitermarkus commented
> I think others are likely to just use internal APIs regardless of what we tell them to do.

And that means if something breaks that's on them and doesn't mean we shouldn't mark our APIs as private/internal.

2021-03-31 13:51 UTC, MikeMcQuaid commented
> And that means if something breaks that's on them

It may be on them but I think it's still something we want to avoid doing when we can.

2021-03-31 13:52 UTC, MikeMcQuaid requested changes
Just to make review request go away and be explicit: I don't think we should use `open-uri` here.

2021-03-31 14:55 UTC, reitermarkus commented
> It may be on them but I think it's still something we want to avoid doing when we can.

I'd rather be more strict in this regard than condoning using private APIs. If something breaks, that's an opportunity for suggesting an new public API.

2021-04-01 08:39 UTC, MikeMcQuaid commented
I've approved https://github.com/Homebrew/brew/pull/10969 as @reitermarkus has convinced me that internal APIs are a good idea ❤️

2021-04-01 11:54 UTC, Bo98 commented
So as a stop gap solution? That's fine, if we do eventually come with public API replacement that can be used in Homebrew/core etc. Perhaps we should create `brew` issues for them.

2021-04-01 12:04 UTC, MikeMcQuaid commented
As a stop-gap I think just leave the existing code as-is and use `curl_download`?

2021-04-01 12:09 UTC, Bo98 commented
Do we want to write a file? Where to? Because that's what `curl_download` does.

2021-04-01 12:22 UTC, MikeMcQuaid commented
Sorry, I meant continue to use `curl_output`.

2021-04-01 12:23 UTC, Bo98 commented
Yes. I'm going to be annoying though and insist we create an issue to investigate a public API for this.

2021-04-01 12:23 UTC, closed without merging

2021-04-01 12:31 UTC, MikeMcQuaid commented
@bo98 I think an internal API would be sufficient in this case unless we have formulae that need it.

2021-04-01 12:32 UTC, Bo98 commented
So it's not a stop gap? I think I misunderstood the discussion.

2021-04-01 12:36 UTC, MikeMcQuaid commented
The way I understood/understand it:
- public APIs can be used in formulae, casks, wherever
- private APIs can only be used in Homebrew/brew
- internal APIs can only be used by the Homebrew org

This script fits into "internal APIs" as far as I'm concerned. Other candidates for internal APIs would be homebrew/bundle, services, test-bot, etc.

2021-04-01 12:43 UTC, Bo98 commented
I understand what an internal API is, I just feel that almost all internal APIs should have the goal of becoming public API (potentially after refactoring etc.) rather than be permanently internal. I don't really like the concept of "only Homebrew itself can do these type of things" - why isn't anyone else allowed to what Homebrew/bundle does?

2021-04-01 12:45 UTC, MikeMcQuaid commented
> why isn't anyone else allowed to what Homebrew/bundle does

Anyone can do what it does but I'd argue not anyone should call the internal methods it does (for speed, primarily). The reasoning being that we want to be able to change/break those internal APIs and not have to go through the lengthy two-major-version deprecation process.

2021-04-01 12:48 UTC, Bo98 commented
> the internal methods it does (for speed, primarily)

What are those methods and why are they fragile?

2021-04-01 12:51 UTC, MikeMcQuaid commented
> What are those methods and why are they fragile?

They expose internal implementation details in a way we don't wish to support forever.