berkeley-db: up formula version to 6.2.23, enable dbm, depend on java
Homebrew/homebrew-core pull request #7421
Opened 2016-11-30 15:27 UTC by maxim-belkin

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR does several things:
1. updates `berkeley-db` to 6.2.23.
1. updates default options to build with java and sql support
1. adds `:java` dependency
1. adds `dbm` support (needed for some formulas)

Related (and closed) PRs: #2549 and #3263

```txt
$ brew audit --strict berkeley-db
berkeley-db:
  * JARs were installed to "/usr/local/Cellar/berkeley-db/6.2.23/lib"
    Installing JARs to "lib" can cause conflicts between packages.
    For Java software, it is typically better for the formula to
    install to "libexec" and then symlink or wrap binaries into "bin".
    See "activemq", "jruby", etc. for examples.
    The offending files are:
      /usr/local/Cellar/berkeley-db/6.2.23/lib/db.jar
Error: 1 problem in 1 formula
```

2016-11-30 15:40 UTC, MikeMcQuaid requested changes

2016-11-30 15:40 UTC, MikeMcQuaid commented on Formula/berkeley-db.rb
> +  depends_on :java => [:recommended, :build]
Shouldn't build with Java by default because macOS doesn't ship with Java by default.

2016-11-30 16:01 UTC, maxim-belkin commented
Looks like there is a number of failures due to non-existent 
```
/usr/local/opt/berkeley-db/lib/libdb-6.1.dylib
```

2016-11-30 19:20 UTC, zmwangx commented
I attempted this in #2549. rpm was the only blocker back then.

2016-11-30 19:32 UTC, maxim-belkin commented
@zmwangx yes, I saw that one and referenced it in the original post

2016-11-30 19:34 UTC, zmwangx commented
Ah right. Just wanted to point it out to potentially save some research.

2016-12-08 10:05 UTC, MikeMcQuaid commented
@BrewTestBot test this please

2016-12-08 21:33 UTC, maxim-belkin commented
What's going on with downloaded files? They have the same SHA256 :)
```
=> brew fetch --retry bogofilter --build-bottle --force
==> FAILED
==> Downloading https://downloads.sourceforge.net/project/bogofilter/bogofilter-1.2.4/bogofilter-1.2.4.tar.bz2
==> Downloading from http://downloads.sourceforge.net/#!/project/bogofilter/bogofilter-1.2.4/bogofilter-1.2.4.tar.bz2
Downloaded to: /Users/brew/Library/Caches/Homebrew/bogofilter-1.2.4.tar.bz2
SHA256: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
```
and
```
==> brew fetch --retry darkice --build-bottle --force
==> FAILED
==> Downloading https://downloads.sourceforge.net/project/darkice/darkice/1.3/darkice-1.3.tar.gz
==> Downloading from http://downloads.sourceforge.net/#!/project/darkice/darkice/1.3/darkice-1.3.tar.gz
Downloaded to: /Users/brew/Library/Caches/Homebrew/darkice-1.3.tar.gz
SHA256: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
```

2016-12-08 21:34 UTC, maxim-belkin commented
And thanks for starting this test because it is blocking some of my work in Linuxbrew-land.

2016-12-08 22:36 UTC, maxim-belkin commented
@MikeMcQuaid could you please restart the build?

2016-12-08 22:56 UTC, maxim-belkin commented
my gist-logs for [rpm](https://gist.github.com/1d688342a9349ee589f44cf98f34c3fd) and [bogofilter](https://gist.github.com/753a60127e5210295f31afb9175b85fd)

2016-12-09 10:01 UTC, MikeMcQuaid approved these changes

2016-12-09 15:14 UTC, maxim-belkin commented
fixed `rpm` test locally.
I have a solution for `darkice` but it requires modifications to several source code files in `darkice` OR one header file in `libsamplerate`

2016-12-09 16:29 UTC, maxim-belkin commented
Fixed `darkice` and `rpm`'s testing section. Ready to be re-tested ( @MikeMcQuaid ) .

2016-12-09 18:43 UTC, maxim-belkin commented
Weird failure on El Capitan: the only part that failed is the development build of `moc`. Note that El Capitan uses SDK for `10.12`

```log
==> brew install --devel moc --verbose
==> FAILED
```
then:
```log
==> Installing moc
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161209-86963-1nsoq7g.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/moc.rb --verbose --devel
==> Downloading http://ftp.daper.net/pub/soft/moc/unstable/moc-2.6-alpha2.tar.xz
Already downloaded: /Users/brew/Library/Caches/Homebrew/moc-2.6-alpha2.tar.xz
==> Verifying moc-2.6-alpha2.tar.xz checksum
tar xJf /Users/brew/Library/Caches/Homebrew/moc-2.6-alpha2.tar.xz
==> ./configure --disable-debug --prefix=/usr/local/Cellar/moc/2.6-alpha2_1
...
... some output ...
...
Making install in vorbis
/bin/sh ../../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/Cellar/libogg/1.3.2/include -I/usr/local/Cellar/libvorbis/1.3.5/include -I../.. -D_THREAD_SAFE -pthread -g -O2 -Wall -W -I/usr/local/Cellar/jack/0.125.0_1/include -I/usr/local/Cellar/libsamplerate/0.1.9/include  -MT libvorbis_decoder_la-vorbis.lo -MD -MP -MF .deps/libvorbis_decoder_la-vorbis.Tpo -c -o libvorbis_decoder_la-vorbis.lo `test -f 'vorbis.c' || echo './'`vorbis.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../.. -I/usr/local/Cellar/libogg/1.3.2/include -I/usr/local/Cellar/libvorbis/1.3.5/include -I../.. -D_THREAD_SAFE -pthread -g -O2 -Wall -W -I/usr/local/Cellar/jack/0.125.0_1/include -I/usr/local/Cellar/libsamplerate/0.1.9/include -MT libvorbis_decoder_la-vorbis.lo -MD -MP -MF .deps/libvorbis_decoder_la-vorbis.Tpo -c vorbis.c  -fno-common -DPIC -o .libs/libvorbis_decoder_la-vorbis.o
In file included from vorbis.c:35:
In file included from ../../decoder.h:6:
In file included from ../../io.h:5:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/pthread.h:60:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:177:5: error: conflicting types for 'clock_gettime'
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
../../compat.h:77:5: note: previous declaration is here
int clock_gettime (int clk_id, struct timespec *ts);
    ^
1 error generated.
make[2]: *** [libvorbis_decoder_la-vorbis.lo] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

==> Formula
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/moc.rb
```

2016-12-09 18:57 UTC, ilovezfs commented
This fixes it
```
diff --git a/Formula/moc.rb b/Formula/moc.rb
index 12c9aa7..9d39a8c 100644
--- a/Formula/moc.rb
+++ b/Formula/moc.rb
@@ -45,6 +45,11 @@ class Moc < Formula
   depends_on "homebrew/dupes/ncurses" => :optional
 
   def install
+    # Fix "error: conflicting types for 'clock_gettime'"
+    if build.devel? && MacOS.version == :el_capitan && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
+      inreplace Dir["{*.c,compat.h}"], "clock_gettime", "moc_clock_gettime", false
+    end
+
     system "autoreconf", "-fvi" if build.head?
     system "./configure", "--disable-debug", "--prefix=#{prefix}"
     system "make", "install"
```
@maxim-belkin mind reporting it upstream to moc? :innocent:

2016-12-09 19:06 UTC, maxim-belkin commented
A perfect stranger ( wink-wink @zmwangx ) already reported it [here](https://moc.daper.net/node/1576)
I can implement your fix and bump up the revision of development version of moc to 2.5.3. Should I do that?

2016-12-09 19:09 UTC, ilovezfs commented
@maxim-belkin the name rings a bell.

>I can implement your fix and bump up the revision of development version of moc to 2.5.3. Should I do that?

Pretty please, with sugar on top. Also add a link to rings-a-bell's report.

2016-12-09 19:48 UTC, zmwangx commented
I've been having some back-and-force with upstream maintainer John Fitzgerald (over private email), with me explaining the clock_gettime clusterfuck and both of us trying to come up ways to fix this in upstream code base satisfactorily. For instance, I've suggested `AC_CHECK_FUNCS` or `AC_SEARCH_LIBS` (reminding him of `SDKROOT` and our `ac_cv_func_clock_gettime` and `ac_cv_search_clock_gettime`); or renaming the function and define it unconditionally for Darwin:

```diff
diff --git a/compat.c b/compat.c
index df02a1d..5b0bcc5 100644
--- a/compat.c
+++ b/compat.c
@@ -49,13 +49,13 @@ char *strcasestr (const char *haystack, const char *needle)
#endif

/* OSX doesn't provide clock_gettime(3) so fall back to gettimeofday(2). */
-#ifndef HAVE_CLOCK_GETTIME
+#if !defined HAVE_CLOCK_GETTIME || defined __APPLE__
#include <sys/time.h>
#include <assert.h>

#include "common.h"

-int clock_gettime (int clk_id ASSERT_ONLY, struct timespec *ts)
+int my_clock_gettime (int clk_id ASSERT_ONLY, struct timespec *ts)
{
	int result;
	struct timeval tv;
diff --git a/compat.h b/compat.h
index 71a011e..27c0283 100644
--- a/compat.h
+++ b/compat.h
@@ -50,10 +50,12 @@ extern "C" {
char *strcasestr (const char *haystack, const char *needle);
#endif

-#ifndef HAVE_CLOCK_GETTIME
+#if !defined HAVE_CLOCK_GETTIME || defined __APPLE__
#define CLOCK_REALTIME 0
struct timespec;
-int clock_gettime (int clk_id, struct timespec *ts);
+int my_clock_gettime (int clk_id, struct timespec *ts);
+#else
+#define my_clock_gettime clock_gettime
#endif

#ifdef __cplusplus
diff --git a/interface.c b/interface.c
index e8c3e08..976f023 100644
--- a/interface.c
+++ b/interface.c
@@ -2581,7 +2581,7 @@ static time_t rounded_time ()
	struct timespec exact_time;
	time_t curr_time;

-	if (clock_gettime (CLOCK_REALTIME, &exact_time) == -1)
+	if (my_clock_gettime (CLOCK_REALTIME, &exact_time) == -1)
		interface_fatal ("clock_gettime() failed: %s", xstrerror (errno));

	curr_time = exact_time.tv_sec;
```

He was unsatisfied with both approaches and decided that he would use a `host_os` based check (no no to me) in his latest email to me (from yesterday).

Whatever the outcome is, rest assured that upstream really wants to fix this.

2016-12-09 19:50 UTC, ilovezfs commented
@zmwangx you may want to share this with him: https://github.com/jsquyres/libfabric/commit/469779935f9995b88a6f486fe3c4c4496989af36

2016-12-09 19:53 UTC, zmwangx commented
@ilovezfs We've already discussed `AC_LINK_IFELSE` and such, I'm sure he won't be thrilled to carry that `ofi_clock_gettime.m4` in moc's codebase. However, feel like contributing to Autoconf Archive, or asking Jeff Squyres to do that?

2016-12-09 19:55 UTC, ilovezfs commented
@zmwangx considering Jeff actually decided to remove clock_gettime entirely from their codebase that somehow feels wrong lol

2016-12-09 19:56 UTC, ilovezfs commented
@zmwangx https://github.com/ofiwg/libfabric/pull/2508.

2016-12-09 19:57 UTC, zmwangx commented
@ilovezfs John considered that (there's only one clock_gettime call after all, and it's not even essential, it's only called when seeking forward/backward), but he had concerns over precision of alternate implementations.

I feel bad for all these poor Linux souls who are now forced to clean after Apple's mess.

2016-12-09 20:07 UTC, zmwangx commented
By the way, re rpm @maxim-belkin: are you sure `/var/lib/rpm/sqldb` is the correct replacement for `/var/lib/rpm/Packages`? Last time I looked at the this I thought it might be due to a subtly broken build, but I don't know enough about rpm (well, I know almost nothing) to tell either way.

2016-12-09 20:08 UTC, ilovezfs commented
@zmwangx there are two separate issues really: how to detect the evil case, and what to do about it. Assuming the former is not a problem, it seems like changing the name of the function, using a toll free bridge when the platform has the real clock_gettime, and otherwise using one of the preexisting compat implementations is pretty uncontroversial, no?

2016-12-09 20:13 UTC, zmwangx commented
@ilovezfs 

> ... pretty uncontroversial, no?

To me it's pretty uncontroversial. However, I wrote

> 3. Ignore Darwin's clock_gettime. Something like the patch attached at
  the end.

and John wrote

> Yeah, I did come up with a similar patch, but decided it got too cryptic.

A little bit of context: a while ago John discarded a lot of compat stuff and tried to make the code base as POSIX as possible. It's understandable he doesn't want something like `moc_clock_gettime` in the C code. But then you into all the problems with the heavily contended symbol `clock_gettime`.

2016-12-09 20:23 UTC, ilovezfs commented
Given the limitations of the language, a wrapper seems preferable to littering the code with #if this #else that macros.

2016-12-09 20:28 UTC, zmwangx commented
@ilovezfs You will have cpp conditionals anyway. A point can be made to limit tweaks to `compat.{c,h}` and pretend elsewhere (i.e. `interface.c`) that you have unfettered access to realtime extensions.

2016-12-09 20:35 UTC, ilovezfs commented
@zmwangx yup, which is why "It's understandable he doesn't want something like moc_clock_gettime in the C code," is not actually understandable to me.

2016-12-09 20:36 UTC, zmwangx commented
@ilovezfs Well, if you could "pretend elsewhere (i.e. interface.c) that you have unfettered access to realtime extensions", then you would just call `clock_gettime`, not `moc_clock_gettime`...

2016-12-09 21:00 UTC, ilovezfs commented
@zmwangx I see, but tough to avoid including time.h indirectly at some point, no?

2016-12-09 21:13 UTC, zmwangx commented
@ilovezfs Never mind, got the patch: https://raw.githubusercontent.com/Homebrew/patches/b7814c0/moc/moc-r2935%2Bclock_gettime-3.patch

Basically:

```
dnl OSX / MacOS doesn't provide clock_gettime(3) prior to darwin-16.0.0
dnl so fall back to gettimeofday(2).
case "$host_os" in
[*darwin[1-9].*] | [*darwin1[0-5].*])
	HAVE_CLOCK_GETTIME="no"
	;;
*darwin*)
	HAVE_CLOCK_GETTIME="yes"
	;;
*)
	AC_CHECK_LIB([rt], [clock_gettime],
		[HAVE_CLOCK_GETTIME="yes"],
		[HAVE_CLOCK_GETTIME="no"])
	;;
esac
```

```diff
diff --git a/Formula/moc.rb b/Formula/moc.rb
index 12c9aa70cd..0756bae400 100644
--- a/Formula/moc.rb
+++ b/Formula/moc.rb
@@ -11,9 +11,18 @@ class Moc < Formula
   end
 
   devel do
-    url "http://ftp.daper.net/pub/soft/moc/unstable/moc-2.6-alpha2.tar.xz"
-    sha256 "0a3a4fb11227ec58025f7177a3212aca9c9955226a2983939e8db662af13434b"
+    url "http://ftp.daper.net/pub/soft/moc/unstable/moc-2.6-alpha3.tar.xz"
+    sha256 "a27b8888984cf8dbcd758584961529ddf48c237caa9b40b67423fbfbb88323b1"
 
+    patch do
+      url "https://raw.githubusercontent.com/Homebrew/patches/b7814c0/moc/moc-r2935%2Bclock_gettime-3.patch"
+      sha256 "601b5cdf59db67f180f1aaa6cc90804c1cb69c44cdecb2e8149338782e4f21a8"
+    end
+
+    # Remove build deps when next devel release comes out
+    depends_on "autoconf" => :build
+    depends_on "automake" => :build
+    depends_on "gettext" => :build
     depends_on "popt"
   end
 
@@ -45,7 +54,8 @@ class Moc < Formula
   depends_on "homebrew/dupes/ncurses" => :optional
 
   def install
-    system "autoreconf", "-fvi" if build.head?
+    # Remove build.devel? when next devel release comes out
+    system "autoreconf", "-fvi" if build.head? || build.devel?
     system "./configure", "--disable-debug", "--prefix=#{prefix}"
     system "make", "install"
   end
```

2016-12-09 21:14 UTC, MikeMcQuaid commented
> +    # Remove build deps when next devel release comes out

Probably worth noting a specific version or even adding a `test` or this will get left indefinitely.

2016-12-09 21:16 UTC, zmwangx commented
> Probably worth noting a specific version or even adding a test or this will get left indefinitely.

My patch is only meant for testing... I think

```rb
inreplace Dir["{*.c,compat.h}"], "clock_gettime", "moc_clock_gettime", false
```

is good enough for now.

2016-12-09 21:23 UTC, zmwangx commented
By the way, the `clock_gettime` issue is subtle in moc. Even if `clock_gettime` is linked on 10.11, running `mocp` won't fail immediately; only if you actually play a song in it and try to seek forward or backward will it error out with the dreaded

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
```

Of course we can't test that.

The only reliable test that I know of is

```rb
system "/usr/bin/nm #{bin}/mocp | grep clock_gettime"
```

2016-12-09 23:03 UTC, maxim-belkin commented
build on sierra failed...

2016-12-09 23:38 UTC, zmwangx commented
> build on sierra failed...

Because the replacement needs to happen on 10.12 too (`HAVE_CLOCK_GETTIME` isn't set there thanks to looking for `clock_gettime` in the nonexistent librt). Now that there's an official patch though, let's just use that one (at the expense of having to regenerate configure).

I've opened #7734 to bump moc devel so that we don't need to keep rebuilding everything else here. Might as well rebase after #7734 is merged; berkeley-db 6.2.23 has been delayed for the better part of a year.

2016-12-10 01:22 UTC, maxim-belkin commented
OK, I'll rebase this PR and remove all the fixes for `moc` once your PR is merged.

2016-12-10 15:45 UTC, maxim-belkin commented
rebased and force-pushed

2016-12-10 18:30 UTC, maxim-belkin commented
@ilovezfs have a look at error messages on Jenkins -- I think those errors are Jenkins' problem. Can you restart the build?

2016-12-10 18:33 UTC, maxim-belkin commented
@zmwangx regarding `rpm`: I don't know but I see `sqldb`, not `Packages` when I run tests. I checked that this file is an sql database with `Packages` table in it. It could be a combination of factors that leads to `sqldb` file and not a bunch of Berkeley-DB files one of which if `Packages`

2016-12-11 11:38 UTC, ilovezfs commented
@BrewTestBot test this please

2016-12-13 12:49 UTC, maxim-belkin commented
Strange failures again. Is there something wrong with Jenkins or does it indicate a problem with formulae?

2016-12-18 21:04 UTC, MikeMcQuaid commented
Will try to rebuild.

2016-12-18 21:04 UTC, MikeMcQuaid commented
@BrewTestBot test this please

2016-12-21 17:29 UTC, maxim-belkin commented
Can someone take a look at this PR? Looks like all the checks are passed now.

2016-12-23 20:36 UTC, MikeMcQuaid approved these changes

2016-12-23 20:37 UTC, MikeMcQuaid commented
Looks good to me. @ilovezfs 👍 ?

2016-12-23 20:42 UTC, ilovezfs commented on Formula/darkice.rb
> +    ["aacPlusEncoder.cpp", "FaacEncoder.cpp", "OpusLibEncoder.cpp", "VorbisLibEncoder.cpp"].each do |f|
Has this been reported?

2016-12-23 20:46 UTC, ilovezfs commented
Does it really still need ENV.deparallelize for berkeley-db?

2016-12-23 20:47 UTC, ilovezfs commented on Formula/berkeley-db.rb
> +  option "without-sql", "Build without SQL support."
if sql and dbm don't add dependencies, why are they optional as opposed to always passed?

2016-12-23 20:48 UTC, ilovezfs commented on Formula/berkeley-db.rb
> +  depends_on :java => [:optional, :build]
is it really only a build time dep?

2016-12-26 17:04 UTC, maxim-belkin commented on Formula/darkice.rb
> +    ["aacPlusEncoder.cpp", "FaacEncoder.cpp", "OpusLibEncoder.cpp", "VorbisLibEncoder.cpp"].each do |f|
Thanks for asking. I was going to say "no", but then looked around and found [this PR](https://github.com/rafael2k/darkice/pull/120). So yes, this has been reported

2016-12-26 17:16 UTC, ilovezfs commented on Formula/darkice.rb
> +    ["aacPlusEncoder.cpp", "FaacEncoder.cpp", "OpusLibEncoder.cpp", "VorbisLibEncoder.cpp"].each do |f|
Cool. Please add the link, date, and brief description like these: https://gist.github.com/ilovezfs/62a9eb715dc044f7202cbf86caaf713b

2016-12-26 17:34 UTC, maxim-belkin commented on Formula/darkice.rb
> +    ["aacPlusEncoder.cpp", "FaacEncoder.cpp", "OpusLibEncoder.cpp", "VorbisLibEncoder.cpp"].each do |f|
within the `echo do` loop or right before it?

2016-12-26 17:43 UTC, maxim-belkin commented on Formula/berkeley-db.rb
> +  option "without-sql", "Build without SQL support."
Do you mean we should convert "without-sql" to "with-sql" OR `depends_on "sql" => :build` ? I guess the latter but want to make sure

2017-01-05 22:11 UTC, maxim-belkin commented
I've taken all suggestions into account and now formula builds with `sql` and `dbm` by default:
```configure
--enable-sql
--enable-sql_codegen
--enable-dbm
```
I don't see any additional dependencies because of this change.

`java` is `build` only dependency
parallel build (still) fails.

[Options](http://docs.oracle.com/cd/E17076_04/html/installation/build_unix_conf.html) to consider:

`--enable-sql_compat`: builds sqlite3.

I see that `sqlite` formula is keg-only because of `sqlite3` and that's why I didn't enable this option in this PR. Let me know if I should add it here.

2017-01-05 22:52 UTC, maxim-belkin commented
added `--enable-stl`

2017-01-06 14:00 UTC, maxim-belkin commented
@ilovezfs I've addressed your comments/suggestions

2017-01-06 15:16 UTC, ilovezfs approved these changes

2017-01-06 15:48 UTC, closed without merging

2017-01-06 15:52 UTC, ilovezfs commented
@maxim-belkin thanks for your contribution to Homebrew! I did some minor surgery on the PR so that it's one commit per formula and so that it uses the standard commit subjects, but preserved your commit credits for the changes to berkeleydb, darkice, and rpm.

2017-01-06 18:43 UTC, maxim-belkin commented
Cool! Thank you!