ldpl: upstream Linux fix
Homebrew/homebrew-core pull request #74412
Opened 2021-04-02 08:11 UTC by danielnachun

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2021-04-02 09:06 UTC, iMichka approved these changes

2021-04-02 09:07 UTC, iMichka requested changes
Is man-db provided by macOS?

2021-04-02 09:51 UTC, dawidd6 commented on Formula/ldpl.rb
> +    depends_on "man_db"
```suggestion
    depends_on "man-db"
```

2021-04-03 00:27 UTC, danielnachun commented
It looks `man` is provided by macOS and the `man-db` formula even prepends `g` to the `man` to avoid conflicting with the macOS version.  I don't why this isn't already in the list of formula for `uses_from_macos` but I'm going to add it.

2021-04-03 07:57 UTC, iMichka commented
It's weird that it's only needed on linux but not on Mac then. It sometimes happens, but it's quite rare. We try to keep the dependencies aligned as much as possible. Can you run a build on linux and see what fails if we remove that dependency?

2021-04-03 08:00 UTC, danielnachun commented
Oh I forgot to add that I tried that in Docker.  The `make install` fails on Linux, because it expects to find the `man` command.

2021-04-03 08:04 UTC, iMichka commented
I see. `man-db` could be made `uses_from_macos` but it is not equivalent to `man` on Mac, as the package installs way more things. So I'm fine with this change, let's keep it as-is.

2021-04-03 08:05 UTC, iMichka commented
Please change to `depends_on "man-db"`, and this should be good to go.

2021-04-03 10:58 UTC, iMichka approved these changes

2021-04-03 10:58 UTC, merged