glfw3: migrate from homebrew/versions.
Homebrew/homebrew-core pull request #7484
Opened 2016-12-02 20:14 UTC by JCount

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Also, rename to `glfw`.

Fixes https://github.com/Homebrew/homebrew-versions/issues/1318.

2016-12-03 11:22 UTC, MikeMcQuaid requested changes

2016-12-03 11:22 UTC, MikeMcQuaid commented on Formula/glfw.rb
> +  end
Can remove this as it's effectively a new formula now.

2016-12-03 11:23 UTC, MikeMcQuaid commented
You can ignore this audit failure: https://bot.brew.sh/job/Homebrew%20Core/12523/version=any_sierra/testReport/junit/brew-test-bot/sierra/audit_glfw___new_formula/

One nit and then we can ship this.

2016-12-03 19:35 UTC, JCount commented on Formula/glfw.rb
> +  end
Ok

2016-12-03 20:12 UTC, JCount commented
Should be good to go.

2016-12-04 14:24 UTC, MikeMcQuaid approved these changes

2016-12-04 14:26 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-12-04 14:26 UTC, closed without merging

2016-12-04 17:45 UTC, DomT4 commented
This could have probably used some `link_overwrite`s:

```
==> Finishing up
rm /usr/local/include/GLFW
ln -s ../../Cellar/glfw3/3.2.1/include/GLFW/glfw3.h glfw3.h
ln -s ../../Cellar/glfw3/3.2.1/include/GLFW/glfw3native.h glfw3native.h
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/GLFW/glfw3.h
Target /usr/local/include/GLFW/glfw3.h
is a symlink belonging to glfw3. You can unlink it:
  brew unlink glfw3

To force the link and overwrite all conflicting files:
  brew link --overwrite glfw

To list all files that would be deleted:
  brew link --overwrite --dry-run glfw

Possible conflicting files are:
/usr/local/include/GLFW/glfw3.h -> /usr/local/Cellar/glfw3/3.2.1/include/GLFW/glfw3.h
/usr/local/include/GLFW/glfw3native.h -> /usr/local/Cellar/glfw3/3.2.1/include/GLFW/glfw3native.h
/usr/local/lib/cmake/glfw3/glfw3Config.cmake
/usr/local/lib/cmake/glfw3/glfw3ConfigVersion.cmake
/usr/local/lib/cmake/glfw3/glfw3Targets-release.cmake
/usr/local/lib/cmake/glfw3/glfw3Targets.cmake
/usr/local/lib/cmake/glfw3/glfw3Config.cmake
/usr/local/lib/cmake/glfw3/glfw3ConfigVersion.cmake
/usr/local/lib/cmake/glfw3/glfw3Targets-release.cmake
/usr/local/lib/cmake/glfw3/glfw3Targets.cmake
/usr/local/lib/pkgconfig/glfw3.pc -> /usr/local/Cellar/glfw3/3.2.1/lib/pkgconfig/glfw3.pc
==> Summary
🍺  /usr/local/Cellar/glfw/3.2.1: 14 files, 286.5K
```

2016-12-04 17:56 UTC, JCount commented
@DomT4 for future reference, how would that be done?

2016-12-04 18:24 UTC, ilovezfs commented
That looks more like a brew bug, not a formula bug.

2016-12-04 18:27 UTC, DomT4 commented
It could probably be solved from the brew side, yes, but Homebrew has used/abused `link_overwrite` before and it'd have probably worked here too. Just wanted to flag it up anyway because it's a pain to spot, especially when 4/5 things get updated in a row.

2016-12-04 18:29 UTC, ilovezfs commented
I can't wait to see how many issues this causes to be filed.

2016-12-04 18:31 UTC, DomT4 commented
I didn't even notice it until I checked why zsh hadn't proceeded onto the second part of my `brewup && dirtypub` command, but I do upgrade verbosely so perhaps less masked for the regular use case.

2016-12-04 18:32 UTC, ilovezfs commented
>dirtypub

:laughing:

2016-12-04 18:33 UTC, DomT4 commented
Is an alias for `brew cleanup --prune=1 && brew prune` 😸