blogc 0.12.0 (new formula)
Homebrew/homebrew-core pull request #7487
Opened 2016-12-02 20:58 UTC by cniemira

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-12-03 06:26 UTC, woodruffw commented on Formula/blogc.rb
> +  url "https://github.com/blogc/blogc/releases/download/v0.12.0/blogc-#{version}.tar.bz2"
This fails since you invoke `version` after `url`. In this case, skip `version` entirely and just put `0.12.0` in the `url`.

2016-12-05 15:17 UTC, cniemira commented
Done! The version is now specified only in the URL, and no separate version param exists.

2016-12-05 16:16 UTC, bfontaine requested changes

2016-12-05 16:16 UTC, bfontaine commented on Formula/blogc.rb
> +    system "git", "clone", "https://github.com/blogc/blogc-example.git"
Use a `resource do` block instead of cloning in the test block.

2017-03-13 14:45 UTC, fxcoudert commented
No update in 3 months, closing for now, please reopen when the comments are addressed.

2017-03-13 14:45 UTC, closed without merging