bug.yml: remind users to `brew update` twice
Homebrew/homebrew-core pull request #75249
Opened 2021-04-15 16:58 UTC by carlocab

The autoupdate that happens with `brew install` doesn't switch users
properly over to GitHub Packages from Bintray for some reason, so
there's a need to do it twice to migrate properly.

See, for example https://github.com/Homebrew/brew/issues/11155, https://github.com/Homebrew/homebrew-core/issues/75243.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2021-04-15 17:13 UTC, carlocab commented
See also https://github.com/Homebrew/brew/pull/11156, and discussion there.

2021-04-15 18:10 UTC, issyl0 approved these changes

2021-04-16 10:40 UTC, MikeMcQuaid requested changes
I'd prefer we did https://github.com/Homebrew/brew/pull/11156#issuecomment-820589111 than add to the template. Ideally we'd have no reference to `brew update` here at all once that's addressed.

2021-04-20 10:29 UTC, carlocab commented
Maybe not needed anymore. Closing.

2021-04-20 10:29 UTC, closed without merging