pdksh: update urls
Homebrew/homebrew-core pull request #7538
Opened 2016-12-04 21:29 UTC by zmwangx

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://www.cs.mun.ca/~michael/pdksh/ and ftp://ftp.cs.mun.ca/pub/pdksh/ have disappeared from the Internet, presumably because maintainer Michael Rendell left his institution. A new home cannot be located.

For the time being, use an archived homepage from the WayBack Machine, add mirrors (as listed on the homepage) that are still functioning for the tarball, and vendor the official patches.

Please merge https://github.com/Homebrew/formula-patches/pull/93 which vendors the patches.

P.S. I caught this when I was validating the checksums of all patches in core. I tried to locate contact info, but the only email address listed was pdksh AT cs.mun.ca, and assuming the maintainer left the institution, the email address would be useless, too.

2016-12-04 21:32 UTC, zmwangx commented
Alternatively, we can simply boneyard this package. Debian ships a pdksh package too, but it's simply a dummy pointer to mksh. According to https://packages.debian.org/wheezy/pdksh,

> The Public Domain Korn Shell "pdksh" is a mostly complete AT&T ksh look-alike, but has been superseded by mksh. This transitional dummy package exists to fulfil the needs of existing users, dependencies and build-dependencies by providing pdksh symlinks to the legacy flavour of mksh.

2016-12-04 22:33 UTC, ilovezfs commented
6 installs in the last thirty days and 47 since the beginning of July.

2016-12-05 14:58 UTC, nijikon commented
@ilovezfs you want to kill it?

2016-12-05 15:06 UTC, ilovezfs commented
We have :green_apple: so might as well keep it for now

2016-12-06 10:03 UTC, nijikon requested changes

2016-12-06 10:03 UTC, nijikon commented on Formula/pdksh.rb
>    url "https://www.cs.mun.ca/~michael/pdksh/files/pdksh-5.2.14.tar.gz"
This url is not working, returns 403.

2016-12-06 19:29 UTC, ilovezfs commented
Actually, I've come to my senses. Let's just :gun: it

2016-12-06 19:30 UTC, ilovezfs commented
@zmwangx mind opening the :skull: PR?

2016-12-06 19:30 UTC, closed without merging

2016-12-06 19:32 UTC, zmwangx commented
https://github.com/Homebrew/homebrew-core/pull/7601