pango 1.48.4_1
Homebrew/homebrew-core pull request #75484
Opened 2021-04-19 12:13 UTC by DocEpsilon

rpath for opt_lib prefixes

- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2021-04-19 12:26 UTC, carlocab commented
CC @tschoonj

For context #75020

2021-04-19 13:05 UTC, tschoonj requested changes
I don't think we want to go down this road as there will be requests for this ~ugly hack~ change in every formula that generates GI bindings.

IMHO given the Homebrew infrastructure the best way to fix this issue is by setting `DYLD_FALLBACK_LIBRARY_PATH` to `${HOMEBREW_PREFIX}/lib` in your shell.

Alternatively, if you really need to use libraries from the GNOME stack in Python through GI, consider using **conda-forge**, which doesn't require you to set `DYLD_FALLBACK_LIBRARY_PATH ` due to their consistent use of `@rpath`.

2021-04-19 13:07 UTC, carlocab commented
I'm going to have to defer to @tschoonj on this one, @DocEpsilon. Sorry!

2021-04-19 13:12 UTC, DocEpsilon commented
Well, than there's no solution at all for arm-based Macs? As we no any by our own words @carlocab :
> In case someone else reads this issue without also reading the linked one ([Homebrew/homebrew-core#75020](https://github.com/Homebrew/homebrew-core/issues/75020)), I strongly recommend against setting `DYLD_LIBRARY_PATH` for general usage. It's a debugging tool at best, and encountering segfaults when this is set is not surprising. (Not to say that this is the cause of the segfault here.)

Setting `DYLD_LIBRARY_PATH` messes things and creates segmentation faults in many cases.

2021-04-19 13:14 UTC, carlocab commented
That's different from `DYLD_FALLBACK_LIBRARY_PATH`. Though I never brought that up because my impression is that it doesn't work.

2021-04-19 13:16 UTC, tschoonj commented
I don't have access to an ARM Mac so I cannot be certain, but I believe that `DYLD_FALLBACK_LIBRARY_PATH ` should work.

From the `dlopen` manpage:

     dlopen() searches for a compatible Mach-O file in the directories specified by a set
     of environment variables and the process's current working directory.  When set, the
     environment variables contain a colon-separated list of directory paths, which can be
     absolute or relative to the current working directory.

     When path does not contain a slash character (i.e. it is just a leaf name), dlopen()
     searches the following until it finds a compatible Mach-O file: $LD_LIBRARY_PATH,
     $DYLD_LIBRARY_PATH, current working directory, $DYLD_FALLBACK_LIBRARY_PATH.

2021-04-19 13:21 UTC, carlocab commented
Hmm, maybe passing `#{HOMEBREW_PREFIX}/lib` as an `-rpath` argument to `LDFLAGS` might work here? Or maybe `opt_lib` would be better; not sure.

2021-04-19 13:39 UTC, DocEpsilon commented
@tschoonj Would you please shortly comment on, why suggested PR  is considered a 'dirty hack'?

> I don't have access to an ARM Mac so I cannot be certain, but I believe that `DYLD_FALLBACK_LIBRARY_PATH ` should work.

I can confirm that this works in my minimal example, while falling back to bottled 1.48.4:

```
% DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib python3 gitest.py   
1.48.4
```
However, in other scenarios I get a segmentation fault as mentioned ealier:

```
% DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib pympress presentation.pdf 
zsh: segmentation fault  DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib pympress presentation.pdf
```

We can try to fix it there or follow @carlocabs suggetions?

2021-04-19 13:42 UTC, tschoonj commented
I think that any `rpath` fix should go into `gobject-introspection`, since that library ends up doing the `dlopen` calls that look for the dylibs mentioned in the `.typelib` files.

2021-04-19 13:49 UTC, carlocab commented
One thing that confuses me is that the `typelib`s that come with `gobject-introspection` refer to fully qualified library paths. For example:
```
❯ strings $(brew --prefix gobject-introspection)/lib/girepository-1.0/GLib-2.0.typelib | grep dylib
/usr/local/opt/glib/lib/libgobject-2.0.0.dylib,/usr/local/opt/glib/lib/libglib-2.0.0.dylib
```
but the ones that come with `pango` don't:
```
❯ strings $(brew --prefix pango)/lib/girepository-1.0/*.typelib | grep dylib
libpango-1.0.0.dylib
libpangocairo-1.0.0.dylib
libpangoft2-1.0.0.dylib
libpangoft2-1.0.0.dylib
libpangoft2-1.0.0.dylib
```
This makes me think it's a `pango` build system issue.

2021-04-19 13:51 UTC, tschoonj commented
@DocEpsilon Bluntly replacing `rpath` everywhere in the `build.ninja` script generated by meson might have unintended consequences, which may not immediately come to light.

And again, this may fix the problem for Pango, but won't do so for other libraries like Gtk and friends, so might lead to a barrage of pull requests in all those formulas as well.

2021-04-19 13:57 UTC, carlocab commented
We do need a slightly more permanent solution than setting environment variables though.

This Pango issue is, AFAICT, what is blocking the bottling of `pympress` (and presumably some other formulae) on ARM.

We're also shipping bottles that don't quite fully work.

Not that I know what the right solution is...

2021-04-19 14:09 UTC, DocEpsilon commented
The fix in this PR sets full paths for pango:
```
% strings $(brew --prefix pango)/lib/girepository-1.0/*.typelib | grep dylib
/opt/homebrew/opt/pango/lib/libpango-1.0.0.dylib
/opt/homebrew/opt/pango/lib/libpangocairo-1.0.0.dylib
/opt/homebrew/opt/pango/lib/libpangoft2-1.0.0.dylib
/opt/homebrew/opt/pango/lib/libpangoft2-1.0.0.dylib
/opt/homebrew/opt/pango/lib/libpangoft2-1.0.0.dylib
```

So the decision is to either go down the rabbit-hole and make this happen for "other libraries like Gtk and friends" or to make all the dependent formulae respect relative paths and set the `DYLD_FALLBACK_LIBRARY_PATH`there implicitly? 

I'd anticipate either way, quite a few PRs coming up?  Though one could argue, that  at the bottom of the dependency-tree there's not so many unintended consequences looming...

2021-04-19 14:28 UTC, tschoonj commented
> One thing that confuses me is that the `typelib`s that come with `gobject-introspection` refer to fully qualified library paths. For example:
> 
> ```
> ❯ strings $(brew --prefix gobject-introspection)/lib/girepository-1.0/GLib-2.0.typelib | grep dylib
> /usr/local/opt/glib/lib/libgobject-2.0.0.dylib,/usr/local/opt/glib/lib/libglib-2.0.0.dylib
> ```
> 
> but the ones that come with `pango` don't:
> 
> ```
> ❯ strings $(brew --prefix pango)/lib/girepository-1.0/*.typelib | grep dylib
> libpango-1.0.0.dylib
> libpangocairo-1.0.0.dylib
> libpangoft2-1.0.0.dylib
> libpangoft2-1.0.0.dylib
> libpangoft2-1.0.0.dylib
> ```
> 
> This makes me think it's a `pango` build system issue.

That is debatable.

Those GLib typelibs are not being generated by `gobject-introspection` utilities as part of the GLib build: this would be impossible since `gobject-introspection` has a build and run-time dependency on GLib.

Instead they are generated during the `gobject-introspection` build instead itself using the utilities produced earlier during that same build, and get the full paths to the already installed GLib/GIO/GModule dylibs allowing these to get introduced into the typelib files.

This is different from how meson works when building GI bindings for libraries that are part of the same build: there it is simply not possible to inject the full path into the typelibs as it would require running tests before the libraries are installed: unlike the GNU Autotools folks, meson devs do not like setting environment variables

If you have some time, feel free to read the many comments in [this PR](https://github.com/mesonbuild/meson/pull/2577), which I opened long time ago to address issues with `meson` on macOS, and with gobject-introspection.

2021-04-19 15:54 UTC, DocEpsilon commented
> No I think that your problem may be fixable with some rpath magic in the `gobject-introspection` formula, without any changes required in other formulas. I could be wrong though.

Okay. With all the question-marks here, I played the ball back to the [gi-team](https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/382#note_1086120). Let's see.

2021-04-19 17:51 UTC, tschoonj commented
Try the following:

```
install_name_tool -add_rpath @loader_path/ $(brew --prefix)/lib/libgirepository-1.0.1.dylib
```

Does your script work then without any environment variables and with a 'clean' Pango?

2021-04-19 18:59 UTC, DocEpsilon commented
That just kills:

```
% install_name_tool -add_rpath @loader_path/ $(brew --prefix)/lib/libgirepository-1.0.1.dylib | python3 gitest.py
/Library/Developer/CommandLineTools/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /opt/homebrew/lib/libgirepository-1.0.1.dylib
zsh: done       install_name_tool -add_rpath @loader_path/  | 
zsh: killed     python3 gitest.py
```

clean pango for reference:
```
% brew info pango
pango: stable 1.48.4 (bottled), HEAD
```

I've also tried to rebuild `gobject-introspection` setting rpath suggested:
```
% git diff Formula/gobject-introspection.rb
diff --git a/Formula/gobject-introspection.rb b/Formula/gobject-introspection.rb
index 7b3b30b2f0..f0d8def0e8 100644
--- a/Formula/gobject-introspection.rb
+++ b/Formula/gobject-introspection.rb
@@ -38,6 +38,7 @@ class GobjectIntrospection < Formula
       "config.set_quoted('GOBJECT_INTROSPECTION_LIBDIR', '#{HOMEBREW_PREFIX}/lib')"
 
     mkdir "build" do
+      ENV.append "LDFLAGS", "-Wl,-rpath,#{HOMEBREW_PREFIX}/lib"
       system "meson", *std_meson_args,
         "-Dpython=#{Formula["python@3.9"].opt_bin}/python3", ".."
       system "ninja", "-v"
```

No success. Using opt_lib instead won't build. 

BTW: here's the [reply](https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/382#note_1086140) from a gi dev:

> I'd recommend talking to the Meson developers, if Meson needs to use an absolute rpath instead of a relative one.
>
>As for the location of the library: gobject-introspection does some pre-processing on the shared library path on macOS. You probably want to look at [#222](https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/222) for more information.

This lead me to the elaborate commit message [here](https://gitlab.gnome.org/GNOME/gobject-introspection/-/commit/fd9125f1e011ca4e87597b4dacdac44c27adc687): 

> On macOS we ideally want to write the final absolute path of the library
> into the gir and typelib.
> [...]
> meson currently sets the install_name of libraries to "@rpath/foo.dylib"
> and adds rpaths to the executables in the build dir. Only during install does
> it change the install_name to the absolute target path in all places.

I'd say this is in support of building with rpaths to receive fully quallified paths at install?

2021-04-19 19:02 UTC, carlocab commented
You need to codesign `$(brew --prefix)/lib/libgirepository-1.0.1.dylib` after using `install_name_tool` on it.

Try doing
```
install_name_tool -add_rpath @loader_path/ $(brew --prefix)/lib/libgirepository-1.0.1.dylib
codesign -f -s - $(brew --prefix)/lib/libgirepository-1.0.1.dylib
python3 gitest.py
```

2021-04-19 19:19 UTC, DocEpsilon commented
Thanks for the correction @carlocab.

With your addition we are back at image not found:

```
% brew update 
Already up-to-date.
% brew doctor
Your system is ready to brew.
% python3 gitest.py 

** (process:43398): WARNING **: 21:16:14.130: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found
```

2021-04-19 19:25 UTC, DocEpsilon commented
That's after aboves changes. 
```
      current version 1292.60.1
compatibility version 1.0.0
Load command 17
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 205864
 datasize 888
Load command 18
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 206752
 datasize 0
Load command 19
      cmd LC_CODE_SIGNATURE
  cmdsize 16
  dataoff 239760
 datasize 20160
Load command 20
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/ (offset 12)
```

2021-04-19 19:28 UTC, carlocab commented
What about
```
install_name_tool -add_rpath "@loader_path/../lib" $(brew --prefix)/lib/libgirepository-1.0.1.dylib
```
You'll have to codesign again.

2021-04-19 19:49 UTC, DocEpsilon commented
Still a no I’m afraid.

> Am 19.04.2021 um 21:29 schrieb Carlo Cabrera ***@***.***>:
> 
> 
> What about
> 
> install_name_tool -add_rpath ***@***.***_path/../lib" $(brew --prefix)/lib/libgirepository-1.0.1.dylib
> You'll have to codesign again.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/Homebrew/homebrew-core/pull/75484#issuecomment-822727336>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACP2QG2EWSCUNEIDHW7OCATTJSAALANCNFSM43FWSGRQ>.
>

2021-04-20 08:22 UTC, tschoonj commented
One thing we could also try is patching pygobject directly.

If we inject a call to `[g_irepository_prepend_library_path](https://github.com/GNOME/gobject-introspection/blob/7a8256eb734509f4a2907fe4b5ea58b885edb5b1/girepository/gitypelib.c#L2241-L2245) ` directly into PyGObject's [main entry point](https://github.com/GNOME/pygobject/blob/128430e028e5f32a3258e8ee4bb29c32c9740f70/gi/gimodule.c#L2519-L2612), then the dylibs should be found without any further changes necessary...

2021-04-20 15:54 UTC, DocEpsilon commented
> One thing we could also try is patching pygobject directly.
> 
> If we inject a call to `[g_irepository_prepend_library_path](https://github.com/GNOME/gobject-introspection/blob/7a8256eb734509f4a2907fe4b5ea58b885edb5b1/girepository/gitypelib.c#L2241-L2245) ` directly into PyGObject's [main entry point](https://github.com/GNOME/pygobject/blob/128430e028e5f32a3258e8ee4bb29c32c9740f70/gi/gimodule.c#L2519-L2612), then the dylibs should be found without any further changes necessary...

If this can be done at build time I'm happy to try it. For that I'd need the formula patch as a diff ideally as I don't know enough about ruby, ninja or meson to do that on my own.

2021-04-20 15:57 UTC, Bo98 commented
Surely this isn't something Homebrew-specific. Is there anything that we can do that is upstreamable?

2021-04-20 16:17 UTC, tschoonj commented
It should be possible to do this in a way that would be acceptable for upstream. For example an option could be added to the meson script that would allow setting this additional directory through `g_irepository_prepend_library_path`.

2021-04-26 06:42 UTC, playgamelxh commented
ninja: build stopped: subcommand failed.

2021-04-29 02:55 UTC, carlocab commented
MacPorts carries this patch which seems like it might be relevant: https://github.com/macports/macports-ports/blob/master/gnome/gobject-introspection/files/patch-fix-rpath-gir-typelib.diff

2021-04-29 05:18 UTC, tschoonj commented
Be careful adopting MacPorts patches here as their GNOME stack is in many cases years behind the versions we offer. 

Apart from two exceptions or so, they are not using meson anywhere, which is possible because they use releases that still carry the old GNU autotools builds. These builds will inject the full path to the dylib into the gir and typelib files, so they would not be confronted by this problem at all.

From what I can tell this patch will prefix the dylib paths with their library installation prefix, and then ensure it ends up in the gir and typelib. This seems risky, as in some cases the dylib won't actually be in that folder. Also it will break meson's test framework, which is bad for our users that want to develop their own software with gobject-introspection bindings.

2021-05-01 11:55 UTC, DocEpsilon commented
Well, I've grazed the meson docs  for a means to that injection mechanism that @tschoonj  mentioned.  It's quite likely, that I'm asking the wrong question, but nowhere did I find anything that described the option to  "pass 'string' to function `g_irepository_prepend_library_path`in file `gitypelib.c`"

2021-05-01 19:33 UTC, tschoonj commented
@DocEpsilon I opened PR #76383 which may fix things for you through a gobject-introspection patch I wrote.

Please give it a try and let me know if it works, in which case I will try and get it merged in upstream.

2021-05-01 22:38 UTC, closed without merging

2021-05-01 23:11 UTC, DocEpsilon commented
Fixed in PR  #76383