jolt 0.0.24 (new formula)
Homebrew/homebrew-core pull request #7567
Opened 2016-12-05 20:49 UTC by david-w-millar

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-12-08 10:08 UTC, MikeMcQuaid requested changes

2016-12-08 10:08 UTC, MikeMcQuaid commented on Formula/jolt.rb
> +  depends_on :java
Is there a specific version you can add here? Thanks!

2016-12-10 04:32 UTC, dunn commented on Formula/jolt.rb
> +
Can add `bottle :unneeded` since we're just installing the JAR.

2016-12-10 04:33 UTC, dunn commented on Formula/jolt.rb
> +  desc "JSON to JSON transformation library and cli written in java"
Tiny nit, but should it be "CLI" and "Java" (capitalized)?

2016-12-10 04:34 UTC, dunn commented on Formula/jolt.rb
> +    system "#{bin}/jolt transform jolt_spec.json input.json > actual_output.json"
You can avoid writing to disk by using our `shell_output` method; e.g.:
```ruby
actual = shell_output("#{bin}/jolt transform jolt_spec.json input.json")

2016-12-10 04:35 UTC, dunn commented on Formula/jolt.rb
> +    system "#{bin}/jolt transform jolt_spec.json input.json > actual_output.json"
Oh, I see below that jolt expects to be passed files.  Then you can do 
```ruby
(testpath/"actual.json").write shell_output("#{bin}/jolt transform jolt_spec.json input.json")

2016-12-10 05:29 UTC, dunn commented
Looks like you pulled in some other commits.  Could you try rebasing against the current master branch?

2016-12-10 05:30 UTC, david-w-millar commented
Oh boy.  Sloppy git fu.  Should I close this and re-open?

2016-12-10 05:30 UTC, david-w-millar commented
Sure @dunn .  Sorry for that!

2016-12-10 05:43 UTC, dunn commented
You can just force-push to this branch to update the PR.

2016-12-15 18:00 UTC, woodruffw commented
Any update here @david-w-millar?

2016-12-18 03:57 UTC, david-w-millar commented
Hey @woodruffw - I'll wrap this up in the next day or so.

2016-12-23 01:27 UTC, david-w-millar commented
This pull request can be close.  This tool is no longer useful for me.  Sorry to waste your time!

2016-12-23 01:27 UTC, closed without merging