Adding service support to logstash
Homebrew/homebrew-core pull request #7571
Opened 2016-12-06 00:17 UTC by rickmark

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-12-08 10:16 UTC, MikeMcQuaid requested changes

2016-12-08 10:16 UTC, MikeMcQuaid commented on Formula/logstash.rb
> +          <string>#{var}</string>
Stick this in `prefix` or similar so it doesn't start writing random files in `var` (which is shared between formulae)

2016-12-08 10:16 UTC, MikeMcQuaid commented on Formula/logstash.rb
> +      <?xml version="1.0" encoding="UTF-8"?>
Can be undented by two characters

2016-12-08 10:16 UTC, MikeMcQuaid commented on Formula/logstash.rb
> +            <string>#{HOMEBREW_PREFIX}/bin/logstash</string>
Use `opt_bin` instead of `HOMEBREW_PREFIX`

2016-12-12 08:20 UTC, MikeMcQuaid commented on Formula/logstash.rb
> +        <string>#{var}/logstash</string>
I don't think this directory will exist by default.

2016-12-24 02:28 UTC, dunn commented on Formula/logstash.rb
> +        <string>#{var}/logstash</string>
Ping on this comment

2017-03-13 16:56 UTC, fxcoudert commented
Closing for now, please reopen once the comment is addressed.

2017-03-13 16:56 UTC, closed without merging