termius 1.0.0 (new formula)
Homebrew/homebrew-core pull request #7610
Opened 2016-12-07 05:14 UTC by EvgeneOskin

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-12-08 10:21 UTC, MikeMcQuaid requested changes
It may also be preferable to use `virtualenv_install_with_resources` in `install`.

2016-12-08 10:21 UTC, MikeMcQuaid commented on Formula/termius.rb
> +  stable do
Don't need to use `stable do` when there's just the URL and SHA256 in the block.

2016-12-08 10:21 UTC, MikeMcQuaid commented on Formula/termius.rb
> +  head do
Don't need to use `head do` when there's just the URL in the block.

2016-12-08 18:02 UTC, EvgeneOskin commented
Hi, @MikeMcQuaid. Thank you for review. It was very useful!

I've updated PR.

2016-12-09 06:00 UTC, EvgeneOskin commented
Hi @woodruffw. Thank you for your comment. I've found a bug with installation and fixed it. 

I've updated the PR.

2016-12-09 10:01 UTC, MikeMcQuaid approved these changes

2016-12-09 10:06 UTC, closed without merging

2016-12-09 10:07 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!