excel-compare 0.6.0 (new formula)
Homebrew/homebrew-core pull request #7678
Opened 2016-12-08 17:33 UTC by jawshooah

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

[ExcelCompare](https://github.com/na-ka-na/ExcelCompare) is a nifty little tool to diff Excel, OpenOffice, and LibreOffice workbooks from the command-line.

Unfortunately there wasn't much I could do in the `test do` block, as the tool only works with workbooks, which are binary files that I don't know how to create without using the respective applications.

2016-12-09 10:19 UTC, MikeMcQuaid commented
> Unfortunately there wasn't much I could do in the test do block, as the tool only works with workbooks, which are binary files that I don't know how to create without using the respective applications.

Could download one of these: https://github.com/na-ka-na/ExcelCompare/tree/master/test/resources as a `resource` block in the `test do`?

2016-12-09 12:49 UTC, jawshooah commented
Wasn't aware of that option, thanks! I'll give it a shot later today.

2016-12-10 18:22 UTC, jawshooah commented
@MikeMcQuaid I've added a nicer test per your suggestion :+1:

2016-12-11 12:51 UTC, MikeMcQuaid requested changes

2016-12-11 12:51 UTC, MikeMcQuaid commented on Formula/excel-compare.rb
> +  resource "sample_workbook" do
A `brew audit --new-formula` whine here: https://bot.brew.sh/job/Homebrew%20Core/13033/version=sierra/testReport/junit/brew-test-bot/sierra/audit_excel_compare___online___new_formula/

2016-12-11 12:51 UTC, MikeMcQuaid commented on Formula/excel-compare.rb
> +    url "https://github.com/na-ka-na/ExcelCompare/raw/0.6.0/test/resources/ss1.xlsx"
append `, :using => :nounzip` to avoid needing to do the `zip` stuff below.

2016-12-11 16:03 UTC, jawshooah commented
@MikeMcQuaid I've made the changes, all 🍏

2016-12-11 16:10 UTC, MikeMcQuaid approved these changes

2016-12-11 16:12 UTC, merged

2016-12-11 16:14 UTC, MikeMcQuaid commented
@jawshooah Just FYI I was gonna do a7f58e9f4b898966ad24408bd7d1b223fe6fbcac locally before pushing. If something is doing no e.g. `make` or compilation it can be `bottle :unneeded`.

2016-12-11 16:16 UTC, jawshooah commented
Ah, sorry about that! I took the approval as implicit permission to merge.

2016-12-11 16:18 UTC, MikeMcQuaid commented
No worries! A simple rebase locally. I kinda forgot you had merge access here 😀