kibana 5.1.1
Homebrew/homebrew-core pull request #7700
Opened 2016-12-09 11:44 UTC by ilovezfs

Created with `brew bump-formula-pr`.

2016-12-09 19:47 UTC, nijikon commented
@ilovezfs Can't we actually use node from brew here?

2016-12-09 20:28 UTC, ilovezfs commented
@nijikon looking back to https://github.com/Homebrew/legacy-homebrew/pull/46593 we'd probably want to consult @jasontedor on that.

2016-12-09 20:41 UTC, jasontedor requested changes
Thanks @ilovezfs, I left a comment about the Node version.

2016-12-09 20:41 UTC, jasontedor commented on Formula/kibana.rb
> +    url "https://nodejs.org/dist/v7.2.1/node-v7.2.1.tar.xz" # N.B. includes vendored dependencies
This should be v6.9.0, that's what this version of Kibana is tested against.

2016-12-09 20:41 UTC, jasontedor commented on Formula/kibana.rb
> +    mirror "https://npm.taobao.org/mirrors/node/latest-v7.x/node-v7.2.1.tar.xz"
Why do we need the mirror?

2016-12-09 20:44 UTC, jasontedor commented
> Can't we actually use node from brew here?

Elastic tests and supports against Node v6.9.0, not Node latest.

2016-12-09 20:44 UTC, ilovezfs commented on Formula/kibana.rb
> +    mirror "https://npm.taobao.org/mirrors/node/latest-v7.x/node-v7.2.1.tar.xz"
We probably don't, but https://bot.brew.sh/job/Homebrew%20Core/12921/version=any_sierra/console and on 10.11 and 10.10 too. Most likely a one time fluke but I didn't want to end up with a CI dud again the second time through.

2016-12-09 20:44 UTC, jasontedor commented
Thanks for the ping @ilovezfs, I left a review.

2016-12-09 20:46 UTC, ilovezfs commented
@jasontedor thanks for your help!

2016-12-09 21:08 UTC, MikeMcQuaid commented
We have `node@6` that we could/should probably use for this now.

2016-12-10 05:57 UTC, ilovezfs commented
I think we should not depend on those.

2016-12-10 07:49 UTC, jasontedor commented
I agree with @ilovezfs. The problem is if node@6 advances before Kibana has been tested against the advancement.

2016-12-10 07:50 UTC, closed without merging

2016-12-10 07:50 UTC, ilovezfs commented
:rocket:

2016-12-10 07:56 UTC, jasontedor commented
Thanks @ilovezfs.

2016-12-10 07:57 UTC, ilovezfs commented
@jasontedor you're welcome! Thanks again for your help and your review here.