spim 9.1.17
Homebrew/homebrew-core pull request #7702
Opened 2016-12-09 11:48 UTC by eagleflo

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Formula does not pass `brew audit --strict` because it doesn't have a `test do` block. I added `make test` to the install phase. (I was unable to make `make test` work inside a `test do` block.)

2016-12-09 16:12 UTC, woodruffw commented
`make test` won't work outside of the building tree/sandbox, unfortunately.

This could probably made more complex, but something like shelling out to `echo print_symbols | spim` and then checking for `__start` would be a good `test`, IMO.

2016-12-12 01:45 UTC, eagleflo commented
Added a `test do` block.

2016-12-12 08:21 UTC, MikeMcQuaid requested changes

2016-12-12 08:21 UTC, MikeMcQuaid commented on Formula/spim.rb
> +    assert_match /__start/, shell_output("echo print_symbols | #{bin}/spim")
`assert_match "__start", pipe_output("#{bin}/spim", "print_symbols")`

2016-12-12 19:43 UTC, woodruffw commented
Thanks @eagleflo!

2016-12-12 19:43 UTC, closed without merging