bnd 3.3.0 (new formula)
Homebrew/homebrew-core pull request #7710
Opened 2016-12-09 14:10 UTC by njbartlett

Bnd is a popular Java tool for building, testing and
running OSGi Bundles. It is the engine behind a number
of other tools such as the Bndtools IDE (based on Eclipse)
along with various Maven plugins such as maven-bundle-plugin.
This formula enables bnd to be used as a standalone command-
line tool.

2016-12-09 16:15 UTC, woodruffw commented on Formula/bnd.rb
> +    assert_match /^#{version}/, shell_output("#{bin}/bnd version")
This is a good start, but something more complex than a simple `version`/`help` test is usually preferred. Is that possible with `bnd`?

2016-12-09 16:18 UTC, bjhargrave commented on Formula/bnd.rb
> +    assert_match /^#{version}/, shell_output("#{bin}/bnd version")
What would you suggest? Bnd is already tested in its own build. There is no Bnd workspace known to the test to run larger tests upon.

2016-12-09 16:30 UTC, woodruffw commented on Formula/bnd.rb
> +    assert_match /^#{version}/, shell_output("#{bin}/bnd version")
I'm not familiar with the tool, but perhaps constructing a simple workspace in the `test` sandbox and feeding it to `bnd`?

2016-12-09 17:01 UTC, njbartlett commented
Its complicated because bnd works on binary artifacts: compiled java and
jars. I guess we would have to compile some simple java sources in the test
sandbox and then run against those.

Obviously the test cannot be comprehensive... Is it just intended as a
smoke test?

On 9 Dec 2016 4:30 p.m., "William Woodruff" <notifications@github.com>
wrote:

*@woodruffw* commented on this pull request.
------------------------------

In Formula/bnd.rb <https://github.com/Homebrew/homebrew-core/pull/7710>:

> +  url "https://search.maven.org/remotecontent?filepath=biz/aQute/bnd/biz.aQute.bnd/3.3.0/biz.aQute.bnd-3.3.0.jar"
+  sha256 "b6b68dfcd0f5ba767a202bf35eb3eb964c63e679e8217dd514dac807e6cedee8"
+
+  bottle :unneeded
+
+  def install
+    prefix.install "biz.aQute.bnd-#{version}.jar"
+
+    (bin/"bnd").write <<-EOS.undent
+      #!/bin/bash
+      exec java -jar #{prefix}/biz.aQute.bnd-#{version}.jar "$@"
+    EOS
+  end
+
+  test do
+    assert_match /^#{version}/, shell_output("#{bin}/bnd version")

I'm not familiar with the tool, but perhaps constructing a simple workspace
in the test sandbox and feeding it to bnd?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Homebrew/homebrew-core/pull/7710>, or mute the thread
<https://github.com/notifications/unsubscribe-auth/AAAY3hu5vu9P5DsN1zhGUDn9Cu2Jf_HCks5rGYIygaJpZM4LI-W_>
.

2016-12-09 17:10 UTC, woodruffw commented
> Is it just intended as a smoke test?

Yep, just to make sure nothing explodes on first run.

Building a `jar` just to test might be overkill -- could it be run on its own jar (i.e., `biz.aQute.bnd-3.3.0.jar`)? If not, we can ignore my nit about `test`.

2016-12-09 17:50 UTC, njbartlett commented
@woodruffw Thank you for your feedback, I have amended the test to perform a bnd resolution, which is one of the operations bnd performs on non-binary files.

2016-12-09 18:02 UTC, woodruffw commented
Thanks!

2016-12-09 18:16 UTC, bjhargrave commented
> could it be run on its own jar (i.e., biz.aQute.bnd-3.3.0.jar)?

You could just do `bnd print biz.aQute.bnd-3.3.0.jar` and sniff the output.

2016-12-09 18:20 UTC, woodruffw commented
> You could just do bnd print biz.aQute.bnd-3.3.0.jar and sniff the output.

@njbartlett's added test should be sufficient, but this is good to know for future tests.

I'll let this sit for a bit to give the other maintainers a change to review, but after that I don't see any blocks on merging this.

2016-12-10 04:27 UTC, dunn commented on Formula/bnd.rb
> +    (bin/"bnd").write <<-EOS.undent
We have a `#write_jar_script` helper method that should work here: 
```ruby
bin.write_jar_script prefix/"biz.aQute.bnd-#{version}.jar", "bnd"

2016-12-10 08:50 UTC, njbartlett commented
@dunn Thank you I have made the suggested change.

2016-12-10 13:38 UTC, MikeMcQuaid requested changes

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +    assert_match /launch.bndrun( )+ok/, output
Could simplify to `/launch.bndrun\s+ok/`

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +    assert_match /org.apache.felix.gogo.runtime( )+baad835c6fa65afc1695cc92a9e1afe2967e546cae94d59fa9e49b557052b2b1( )+file:.*org.apache.felix.gogo.runtime-1.0.0.jar/, output
Could simplify to `/org.apache.felix.gogo.runtime.*org.apache.felix.gogo.runtime-1.0.0.jar/` (or better still using a variable)

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +
Can remove this empty line.

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +    prefix.install "biz.aQute.bnd-#{version}.jar"
Install to `libexec`

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +    # Simple version output check...
Can remove this comment (and perhaps this test)

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +    # First write the index...
can remove the second line of this comment

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +            <attribute name="url" value="org.apache.felix.gogo.runtime-1.0.0.jar"/>
May want to consider making some of these valuables variables rather than hard-coding in two places.

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +    # Next write the bndrun
Can remove this comment

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +      -runrequires: osgi.identity;filter:='(osgi.identity=org.apache.felix.gogo.runtime)'
again, could be a variable

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +    # Run resolve
Can remove this comment

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +    # Check first line of output: "# launch.bndrun    ok"
Can remove this comment

2016-12-10 13:38 UTC, MikeMcQuaid commented on Formula/bnd.rb
> +    # Check second line of output: "<bundle> <sha256> <url>"
Can remove this comment

2016-12-12 20:51 UTC, njbartlett commented
Changes requested by @MikeMcQuaid have been pushed.

2016-12-14 05:17 UTC, woodruffw commented
Thanks @njbartlett. This LGTM, will wait a bit to see if anybody else has comments before merging.

2016-12-15 17:57 UTC, closed without merging

2016-12-15 17:58 UTC, woodruffw commented
Thanks for contributing, @njbartlett and @bjhargrave!

2016-12-15 18:00 UTC, njbartlett commented
Awesome, thanks @woodruffw  and @MikeMcQuaid!