Add jid 0.6.2 (New Formula)
Homebrew/homebrew-core pull request #7751
Opened 2016-12-10 08:13 UTC by ikeisuke

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
jid
https://github.com/simeji/jid

2016-12-10 09:20 UTC, neutric commented on Formula/jid.rb
> +  desc "jid"
Thanks for your contribution! A more comprehensive description of what jid does would be welcome.

2016-12-10 09:32 UTC, neutric commented on Formula/jid.rb
> +    assert_match "jid version v#{version}", shell_output("#{bin}/jid --version")
A more complex test than a simple version string comparison is preferable.

2016-12-10 09:34 UTC, neutric commented on Formula/jid.rb
> +    assert_match "jid version v#{version}", shell_output("#{bin}/jid --version")
A more complex test than a simple version string comparison is preferable.

2016-12-10 09:44 UTC, ikeisuke commented on Formula/jid.rb
> +  desc "jid"
Hi, @neutric. Thank you for review.
I've updated description.

2016-12-10 13:33 UTC, MikeMcQuaid requested changes

2016-12-10 13:33 UTC, MikeMcQuaid commented on Formula/jid.rb
> +    assert_match "jid version v#{version}", shell_output("#{bin}/jid --version")
No, we'd rather use `assert_match` and `(testpath/"test.json").write` with some sample JSON for a better test.

2016-12-10 13:33 UTC, MikeMcQuaid commented on Formula/jid.rb
> +    url "#{homepage}/releases/download/#{version}/jid_darwin_amd64.zip"
This needs to be build from source instead.

2016-12-11 08:31 UTC, ikeisuke commented on Formula/jid.rb
> +    url "#{homepage}/releases/download/#{version}/jid_darwin_amd64.zip"
Hi @MikeMcQuaid . Thank you for review.
I've updated PR.

2016-12-11 12:52 UTC, MikeMcQuaid requested changes

2016-12-11 12:52 UTC, MikeMcQuaid commented on Formula/jid.rb
> +  desc "jid"
Not seeing an updated description.

2016-12-11 12:52 UTC, MikeMcQuaid commented on Formula/jid.rb
> +  version "0.6.2"
Remove this.

2016-12-11 12:52 UTC, MikeMcQuaid commented on Formula/jid.rb
> +  url "#{homepage}/archive/#{version}.zip"
Hardcode this, don't use variables.

2016-12-11 12:52 UTC, MikeMcQuaid commented on Formula/jid.rb
> +    assert_match "jid version v#{version}", shell_output("#{bin}/jid --version")
Still need a better test.

2016-12-11 13:14 UTC, ikeisuke commented
@MikeMcQuaid thank you for review.

I've updated desc, removed version and change to hardcode url.

I'm considering a method of test code implementation.
I think that it is difficult to write a complex test unless update jid.

2016-12-11 13:17 UTC, MikeMcQuaid approved these changes

2016-12-11 13:17 UTC, MikeMcQuaid commented on Formula/jid.rb
> +    assert_match "jid version v#{version}", shell_output("#{bin}/jid --version")
Actually, this is fine 👍

2016-12-11 13:17 UTC, MikeMcQuaid requested changes

2016-12-11 13:17 UTC, MikeMcQuaid commented on Formula/jid.rb
> +  url "https://github.com/simeji/jid/archive/0.6.2.zip"
`https://github.com/simeji/jid/archive/0.6.2.tar.gz`

2016-12-11 16:09 UTC, MikeMcQuaid approved these changes

2016-12-11 16:15 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `jid 0.6.2 (new formula)`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

2016-12-11 16:16 UTC, closed without merging

2016-12-12 07:41 UTC, neutric commented
Thanks guys!

2016-12-12 13:50 UTC, ikeisuke commented
@neutric, @MikeMcQuaid 
Thanks again for your help and your review here.