Update libbpg
Homebrew/homebrew-core pull request #7752
Opened 2016-12-10 14:23 UTC by bilhackmac

2016-12-10 14:52 UTC, MikeMcQuaid commented on Formula/libbpg.rb
> +    share.install Dir["html/bpgdec*.js"]
How are these useful in `share`? I'm trying to figure out how they'd be used?

2016-12-10 15:24 UTC, bilhackmac commented on Formula/libbpg.rb
> +    share.install Dir["html/bpgdec*.js"]
I don't really know where to put these files. They must be copied to a web site to enable viewing bpg images in your browsers.

2016-12-10 16:18 UTC, MikeMcQuaid requested changes

2016-12-10 16:18 UTC, MikeMcQuaid commented on Formula/libbpg.rb
> +    share.install Dir["html/bpgdec*.js"]
Cool. Just use `pkgshare` instead of `share`.

2016-12-11 20:27 UTC, bilhackmac commented
Update done

2016-12-12 08:23 UTC, MikeMcQuaid approved these changes

2016-12-12 08:40 UTC, nijikon commented
You are awesome, thanks for your contribution! :tada:

2016-12-12 08:41 UTC, closed without merging