pulseaudio: fix source build
Homebrew/homebrew-core pull request #7779
Opened 2016-12-11 23:32 UTC by jpauwels

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

As requested in https://github.com/Linuxbrew/homebrew-core/pull/1347

2016-12-12 08:22 UTC, MikeMcQuaid requested changes

2016-12-12 08:22 UTC, MikeMcQuaid commented on Formula/pulseaudio.rb
> +    args << "--disable-x11" # if build.without? "x11" # add when upstream fixed
Remove the comment here, thanks.

2016-12-12 08:22 UTC, MikeMcQuaid commented on Formula/pulseaudio.rb
> +  # add when upstream fixed: depends_on :x11 => :optional
Remove the comment here, thanks.

2016-12-16 13:00 UTC, nijikon commented
You are awesome, thanks for your contribution! :tada:

2016-12-16 13:01 UTC, closed without merging