thumbor 6.2.0 (new formula)
Homebrew/homebrew-core pull request #7780
Opened 2016-12-12 00:35 UTC by kyrios

2016-12-12 08:21 UTC, MikeMcQuaid requested changes

2016-12-12 08:21 UTC, MikeMcQuaid commented on Formula/thumbor.rb
> +  depends_on "homebrew/python/pillow"
Can't do cross-tap dependencies in Homebrew/core I'm afraid.

2016-12-12 08:21 UTC, MikeMcQuaid commented on Formula/thumbor.rb
> +  depends_on "homebrew/dupes/zlib"
This ships with macOS.

2016-12-14 20:44 UTC, woodruffw commented
Any update here @kyrios?

2016-12-14 20:45 UTC, kyrios commented
Sorry. I’m a little confused by the answers and didn’t have time yet to google what they mean :)


> On 14 Dec 2016, at 21:44, William Woodruff <notifications@github.com> wrote:
> 
> Any update here @kyrios <https://github.com/kyrios>?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/Homebrew/homebrew-core/pull/7780#issuecomment-267151003>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAOsgHoEFwTHY2tSoGeCv3NhOFqjpPigks5rIFUcgaJpZM4LKF7M>.
>

2016-12-18 22:23 UTC, MikeMcQuaid commented
Passing on this but homebrew/science may accept it.

2016-12-18 22:23 UTC, closed without merging