kube-linter: update build
Homebrew/homebrew-core pull request #79172
Opened 2021-06-12 01:03 UTC by nandahkrishna

This should fix the build on ARM.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Running `make build` builds binaries for Darwin, Linux and Windows and I could not find any method to build only for a single OS. This fails when trying to build Windows ARM64 binaries, while the Darwin build step is actually successful.

This PR updates the build to use `go build` instead with the necessary arguments. Upstream does not seem to have explicit instructions for this (they only mention `make build`), so I put this together from their various build scripts.

2021-06-12 07:28 UTC, carlocab commented on Formula/kube-linter.rb
> +    system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/kube-linter"
We can probably use a tarball instead of a Git clone now that we're doing `go build` instead of `make`.

2021-06-12 16:35 UTC, dawidd6 requested changes
Could you add a version test too? So we can detect if it's set properly.

2021-06-12 17:22 UTC, nandahkrishna commented
Thanks, I added the test. Note that when using `make build`, we used to get the Gt tag in the version output for binaries installed from Homebrew, however the official binaries they upload to GitHub Releases do not have the tag included as part of the version.

With the change in the build step introduced in this PR, the Homebrew-built binaries will give the same version output as those distributed by upstream.

2021-06-12 17:34 UTC, carlocab approved these changes

2021-06-12 18:32 UTC, dawidd6 approved these changes

2021-06-12 19:08 UTC, closed without merging

2021-06-13 01:39 UTC, chenrui333 reviewed
💯