tmuxinator-completion: don't install zsh completion
Homebrew/homebrew-core pull request #79247
Opened 2021-06-13 07:10 UTC by yurikoles

zsh-completions package has it from [July 2012](https://github.com/zsh-users/zsh-completions/commit/1f97a6ad01cba9983bcc0a30a21b5938b51a1e76)

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2021-06-13 07:17 UTC, yurikoles commented
There is linking error / file conflict without this change.

Another option is to add zsh-completions to `conflicts_with`, but I think more general formula has more priority.

I see same problem with `vagrant-completion`. If maintainers accept this PR, I will file a PR for it.

2021-06-13 11:11 UTC, SMillerDev commented
Would people be able to use `zsh-completions` with the default macOS ZSH?

2021-06-13 14:44 UTC, yurikoles commented
`zsh-completions` doesn't differ from any other completions, they even being installed in the same location causing conflicts.

But I double-checked anyway to confirm that they are working with shell set to `/bin/zsh`

2021-06-14 11:03 UTC, MikeMcQuaid requested changes
We should always install upstream Bash/ZSH completion and never assume users will have `zsh-completion` or `bash-completion` installed. If that causes conflicts: we should fix those conflicts instead.

2021-06-14 12:09 UTC, MikeMcQuaid reviewed
This is an improvement but it'd be nice to actually fix the `zsh-completions` formula to put conflicting completions into a different subdirectory that needs to be manually included? Same for bash-completions and other formulae if possible. I'm fine with this as-is for now, though, thanks @yurikoles!

2021-06-14 12:09 UTC, MikeMcQuaid approved these changes

2021-06-14 12:09 UTC, MikeMcQuaid requested changes
Actually sorry one more thing

2021-06-14 12:09 UTC, MikeMcQuaid commented on Formula/tmuxinator-completion.rb
> +  revision 1
Don't need a `revision` here

2021-06-14 12:16 UTC, MikeMcQuaid approved these changes, later dismissed

2021-06-14 13:02 UTC, nandahkrishna approved these changes

2021-06-14 13:02 UTC, nandahkrishna commented
(Just squashed the commits here as `autosquash` wouldn't have handled it properly.)

2021-06-14 14:13 UTC, closed without merging

2021-06-14 15:55 UTC, cho-m commented
On side note, this is collateral of #76425

It isn't too unusual for `zsh-completions` to occasionally have a conflicting completion script, whether due to official project deciding to add a completions script, or if official variant is poorly maintained.

If we want to keep new behavior of `zsh-completions` installing into default site-functions directory, then we need a way to test for (new) conflicts, and have a way to upgrade formulae with automatic conflict correction (this behavior is not well defined based on some comments from `imath`/`openexr`).

2021-06-15 11:50 UTC, MikeMcQuaid commented
Thanks @cho-m. I think we should consider undoing this behaviour change. CC @carlocab @Homebrew/core for thoughts.

2021-06-15 12:39 UTC, carlocab commented
I'm fine with undoing #76425.

2021-06-15 13:17 UTC, carlocab commented
#79372