amr-client 159 (new formula)
Homebrew/homebrew-core pull request #7957
Opened 2016-12-17 00:28 UTC by Freydal

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I created Formula for Ask Mr. Robot's Simulation client.  This was mostly a learning experience and I am not affiliated with AMR.

2016-12-18 15:36 UTC, mistydemeo requested changes

2016-12-18 15:36 UTC, mistydemeo commented on Formula/amr-client.rb
> +
Remove this blank line, please.

2016-12-18 15:36 UTC, mistydemeo commented on Formula/amr-client.rb
> +  url "https://static2.askmrrobot.com/amrbeta/client/AskMrRobotClient-159-osx.10.11-x64.zip"
Is this software open source?

2016-12-18 15:36 UTC, mistydemeo commented on Formula/amr-client.rb
> +    system "true"
This would need a real test of its functionality.

2016-12-19 15:54 UTC, Freydal commented on Formula/amr-client.rb
> +  url "https://static2.askmrrobot.com/amrbeta/client/AskMrRobotClient-159-osx.10.11-x64.zip"
No.

2016-12-23 21:16 UTC, Freydal commented on Formula/amr-client.rb
> +
I removed this line in an amend commit. This review seems to still trigger off blank lines I believe to be desired.  I tricked it to go away by removing all blank lines but it came back after I reverted those changes.

2016-12-24 18:50 UTC, mistydemeo commented on Formula/amr-client.rb
> +  url "https://static2.askmrrobot.com/amrbeta/client/AskMrRobotClient-159-osx.10.11-x64.zip"
We don't accept closed-source software; you may want to consider hosting this in your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md). Thanks!

2016-12-24 18:50 UTC, closed without merging