libswiftnav 0.21
Homebrew/homebrew-core pull request #7958
Opened 2016-12-17 00:32 UTC by elfchief

2016-12-24 02:30 UTC, dunn commented on Formula/libswiftnav.rb
> +    (testpath/"test.cpp").write <<-EOS.undent
I don't see anything being done with this test file?

2016-12-26 04:26 UTC, woodruffw commented
Any update here @elfchief?

2016-12-26 18:45 UTC, elfchief commented
Ah, right you are. Will fix.

2016-12-27 22:00 UTC, elfchief commented
Ok, actual functioning test now. Sorry about that!

2016-12-29 12:07 UTC, MikeMcQuaid requested changes

2016-12-29 12:07 UTC, MikeMcQuaid commented on Formula/libswiftnav.rb
> +EOS
Indent this by four spaces.

2016-12-30 14:01 UTC, MikeMcQuaid approved these changes

2016-12-30 14:17 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `libswiftnav 0.21 (new formula)`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

2016-12-30 14:18 UTC, closed without merging