gnuradio 3.7.10.1; restored optional components
Homebrew/homebrew-core pull request #7976
Opened 2016-12-18 00:20 UTC by kolen

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

- Bumped version to 3.7.10.1
- Restored optional components removed in 2a6d326a61507caf279352b86f3ef1116c3a8a1f (#6817): python, gnuradio-companion and GUIs
  
  Everything python-related was removed in 2a6d326a61507caf279352b86f3ef1116c3a8a1f, seemingly by mistake, when trying to remove pyQt (gnuradio formula of that version installed everything if enabling python). I restored these components (except pyQt which requires Qt 4.x which no longer builds on latest mac os)

  I set most components as `:recommended` because I think primary use case of gnuradio is to run interactive DSP workflows with gnuradio-companion and WX UI components. If not building gnuradio-companion, it's usable only as c++/python lib (which is sometimes useful too).

  I didn't made it possible to build it entirely without python — why if python is always available in MacOS?
- Removed building custom version cmake, gnuradio builds ok with latest cmake now.
- Added some basic tests 
- Changed homepage to current homepage
- Added `head`

Formula contains patch from gnuradio/gnuradio#1146 to make it properly link against python (``-undefined dynamic_lookup``).

2016-12-18 15:33 UTC, mistydemeo commented
Looks like the test is failing; it can't import numpy.

2016-12-18 15:57 UTC, kolen commented
Seems that it was using numpy manually installed on my system with pip instead of numpy installed into ``vendor/.../site-packages`` (despite using sandbox in tests, not sure how sandbox works). Retrying with numpy from homebrew.

2016-12-18 16:41 UTC, tdsmith commented
There is no good way to handle numpy for the gnuradio bindings. :( As a matter of policy we can't depend on Homebrew's numpy package in core.

The problem is that, as you noticed, installing the numpy distribution to a hidden path isn't good enough because it needs to be present in sys.path when gnuradio is imported. A way to make sure numpy is present while avoiding linking conflicts with a system-installed numpy is to install numpy to a private prefix (e.g. `libexec/numpy`) and then do something like:

`(lib/"python2.7/site-packages/homebrew-gnuradio-numpy.pth").write libexec/"numpy/python2.7/site-packages"`

to put the vendored numpy at the end of the global sys.path.

Alas, this approach doesn't work with system Python, because Apple ships a random old bad version of numpy that appears in sys.path before any of our packages will. If we try and override it, we'll end up overriding the installed numpy version in all cases, which will frustrate numpy users.

It seems like some options are:

* accept that this doesn't work with system Python and add a dependency on "python" so that CI works
* make the Python bindings optional and have them depend on a NumpyRequirement to force users to install their own numpy
* ?

2016-12-18 16:44 UTC, tdsmith commented on Formula/gnuradio.rb
> +  depends_on "wxpython" => :recommended
This uses two different windowing toolkits?

2016-12-18 16:55 UTC, kolen commented on Formula/gnuradio.rb
> +  url "http://gnuradio.org/releases/gnuradio/gnuradio-3.7.10.1.tar.gz"
`https://gnuradio.org/releases/gnuradio/gnuradio-3.7.10.1.tar.gz` redirects to `http://gnuradio.org/releases/gnuradio/gnuradio-3.7.10.1.tar.gz`.

2016-12-18 22:54 UTC, MikeMcQuaid requested changes

2016-12-18 22:54 UTC, MikeMcQuaid commented on Formula/gnuradio.rb
> +  option "with-documentation", "Build with documentation"
Instead call this `with-doxygen` and make it `[:build, :optional]` and, if necessary, add a `deprecated_option`.

2016-12-18 22:54 UTC, MikeMcQuaid commented on Formula/gnuradio.rb
> +  depends_on "wxpython" => :recommended
Please make these `:optional`. We default to non-GUI by default mostly now.

2016-12-19 05:07 UTC, ilovezfs commented
I'd prefer we not do this. https://github.com/gnuradio/gnuradio/issues/1090 is already and the works, and I've already re-written this formula for Qt 5 compatibility locally pending resolution of that issue.

2016-12-25 20:25 UTC, MikeMcQuaid commented
@ilovezfs Seems reasonable to me.

2017-01-15 01:07 UTC, kolen commented
Looks like Mac OS 10.12.2 has numpy `1.8.0rc1`, gnuradio [lists `1.1.0` as minimum](http://gnuradio.org/doc/doxygen/build_guide.html), so maybe it's suitable. It works for me for basic tasks in gnuradio-companion. Added `NumpyRequirement` which checks its version. Made GUI and python optional.

I'm not sure if dependencies between dependencies should be indicated some way (if `--with-pygtk` is specified `--with-python` must be also specified, currently if building with pygtk but without python pygtk components will not be built silently).

2017-01-15 01:08 UTC, kolen commented on Formula/gnuradio.rb
> +  url "http://gnuradio.org/releases/gnuradio/gnuradio-3.7.10.1.tar.gz"
Changed to TLS anyway, it works and maybe some day their server will serve file directly on SSL.

2017-01-18 09:28 UTC, MikeMcQuaid commented
> There is no good way to handle numpy for the gnuradio bindings. :( As a matter of policy we can't depend on Homebrew's numpy package in core.

@tdsmith Let's import `numpy` to homebrew/core instead.

2017-01-22 12:10 UTC, kolen commented on Formula/gnuradio.rb
> +  depends_on "wxpython" => :recommended
I disabled both GUI libraries by default.

But it doesn't make sense to pick only one. Gnuradio-companion, the main gnuradio GUI, visual signal flow editor, uses GTK, however GUI blocks (for example that display spectrogram or allow to change parameters as GUI slider) use either WXWidgets or Qt (seems that most blocks use wx). I think most users who need gnuradio-companion need all three toolkits or at least gtk + wx.

2017-01-22 12:11 UTC, kolen commented on Formula/gnuradio.rb
> +  option "with-documentation", "Build with documentation"
Changed.

2017-01-22 12:11 UTC, kolen commented on Formula/gnuradio.rb
> +  depends_on "wxpython" => :recommended
Changed.

2017-01-25 14:31 UTC, MikeMcQuaid commented
> @tdsmith Let's import numpy to homebrew/core instead.

I did this.

2017-01-29 14:19 UTC, kolen commented
- Updated to use `numpy` from homebrew-core
- Set config file locations to ``/usr/local/etc/gnuradio/conf.d/`` (I'm not sure if either previous version of gnuradio used `/usr/local/etc` by default or there was no linting for it yet)

There's some problem with Jenkins, tried to push 2 times, my build appeared in the queue then disappeared. Trying again (Expected build number: 1​55​58).

2017-01-30 09:07 UTC, MikeMcQuaid commented
@BrewTestBot test this please

2017-01-31 08:52 UTC, nijikon commented
Is there anything else that prevents this from being merged?

2017-01-31 08:58 UTC, ilovezfs submitted a review, later dismissed

2017-01-31 08:58 UTC, ilovezfs commented on Formula/gnuradio.rb
> +  depends_on :python => :recommended
This should be
```
depends_on :python => :recommended if MacOS.version <= :snow_leopard
```
and then have a
```
option "without-python", "Build without python support"
```
above.

2017-01-31 09:04 UTC, ilovezfs commented on Formula/gnuradio.rb
> +  depends_on "jack" => :optional
what is the point of removing these features? Anyone that needs them would now need to build from source.

2017-01-31 09:05 UTC, ilovezfs commented on Formula/gnuradio.rb
> +      enabled_components << "grc" if build.with? "pygtk"
we shouldn't be nesting if's like this

2017-01-31 09:05 UTC, ilovezfs commented on Formula/gnuradio.rb
> +      Dir.chdir(testpath) do
we just use `cd` for these

2017-02-04 18:06 UTC, kolen commented on Formula/gnuradio.rb
> +  depends_on "jack" => :optional
Based on [this discussion](https://github.com/Homebrew/homebrew-core/pull/7976#discussion_r92953220)

2017-02-04 18:33 UTC, kolen commented on Formula/gnuradio.rb
> +      enabled_components << "grc" if build.with? "pygtk"
But then if I build with ``--without-python --with-pygtk`` it will still build with python. In my case it skips python. What is right way?

2017-02-06 21:45 UTC, EvanKrall commented
Thanks for working on this, @kolen.

2017-02-13 16:37 UTC, ilovezfs commented
Please ignore any of my above remarks.

2017-03-06 17:44 UTC, kolen commented
Is it ready for merge?

2017-03-13 00:49 UTC, fxcoudert commented
@BrewTestBot test this please

2017-03-13 16:50 UTC, fxcoudert commented
Looks decent to merge for me. A newer PR will be needed for the latest version (3.7.11) but that can come later.

@MikeMcQuaid you were the last reviewer, any objection?

2017-03-14 08:10 UTC, MikeMcQuaid approved these changes

2017-03-14 08:45 UTC, closed without merging

2017-03-14 08:46 UTC, fxcoudert commented
Thanks @kolen and all who participated!