qscintilla2 2.13.0
Homebrew/homebrew-core pull request #80101
Opened 2021-06-26 16:52 UTC by chenrui333

Created with `brew bump-formula-pr`.

2021-06-26 17:45 UTC, carlocab requested changes
This is a pre-release: https://www.riverbankcomputing.com/software/qscintilla/download

2021-06-26 18:00 UTC, chenrui333 commented
You are right. 🤦  Closing the PR for now.

2021-08-30 02:39 UTC, chenrui333 commented
Now it is no longer pre-release, gonna reopen this PR.

2021-08-30 15:59 UTC, carlocab approved these changes

2021-08-30 16:13 UTC, closed without merging