dcd 0.9.0-alpha5 (devel)
Homebrew/homebrew-core pull request #8025
Opened 2016-12-19 16:22 UTC by John-Colvin

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-12-22 23:14 UTC, apjanke commented on Formula/dcd.rb
> +    if build.stable?
This appears to change the `stable` installation by removing the `experimental_allocator` stuff. If that's the case, this PR should probably include a revision bump.

2016-12-25 20:58 UTC, MikeMcQuaid commented on Formula/dcd.rb
> +    if build.stable?
Yeh, agreed 👍

2016-12-25 20:59 UTC, MikeMcQuaid requested changes
Yeh, agreed 👍

2016-12-29 12:07 UTC, MikeMcQuaid approved these changes

2016-12-29 12:08 UTC, merged

2016-12-29 12:08 UTC, MikeMcQuaid commented
Thanks again @John-Colvin and for explaining.