Add plist_options and test for logrotate
Homebrew/homebrew-core pull request #8069
Opened 2016-12-20 19:25 UTC by GauthamGoli

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-12-21 00:06 UTC, ilovezfs commented
@BrewTestBot test this please

2016-12-25 20:50 UTC, MikeMcQuaid requested changes
Thanks! Looking good so far but I've got a few comments.

2016-12-25 20:50 UTC, MikeMcQuaid commented on Formula/logrotate.rb
> +    # Rotate the log file and check if the new file's size is 0 bytes
Can remove all the comments above, they are good but pretty self-explanatory. Thanks!

2016-12-25 20:50 UTC, MikeMcQuaid commented on Formula/logrotate.rb
> +    system "#{sbin}/logrotate", "-s", "#{testpath}/logstatus", "#{testpath}/testlogrotate.conf"
Can probably get away without specifying the `#{testpath}/`s here.

2016-12-25 20:50 UTC, MikeMcQuaid commented on Formula/logrotate.rb
> +    assert(File.size?("#{testpath}/test.log").nil?)
can you add a second argument here that says something like `"File is not zero length!"` so on failure there's a better error message

2016-12-29 14:04 UTC, GauthamGoli commented on Formula/logrotate.rb
> +    assert(File.size?("#{testpath}/test.log").nil?)
I have made the changes accordingly. Thanks for the review!

2016-12-29 14:45 UTC, MikeMcQuaid approved these changes

2016-12-29 14:52 UTC, merged

2016-12-29 14:52 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `logrotate: add plist_options and test`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!