dbt 0.5.4 (new formula)
Homebrew/homebrew-core pull request #8076
Opened 2016-12-21 00:40 UTC by cmcarthur

Adds a new formula for dbt (data build tool).

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`brew audit --new-formula dbt` returns two problems:

```
dbt:
  * Stable: version 0.5.4 is redundant with version scanned from URL
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
Error: 2 problems in 1 formula
```

The version is taken straight from a tag on Github. To me, that seems like the ideal URL / version combo, let me know if / how you'd like me to resolve that.

On the second issue, this is mostly used by non-technical users so Github forks / stars are not their go-to engagement mechanism :) Please let me know if that's a dealbreaker.

2016-12-22 03:02 UTC, woodruffw commented
We use forks/stars to get a good feel for how popular a potential package is. More specialized programs tend to collect dust and leave us with a greater maintenance workload despite being downloaded relatively rarely. We then end up periodically removing unmaintained/low-frequency packages and ruining those rare users' days.

IMO we should pass on this in favor of upstream hosting their own tap, at least until it becomes more popular. I'll leave some comments, in either case.

2016-12-22 03:04 UTC, woodruffw commented on Formula/dbt.rb
> +    system "#{bin}/dbt", "help"
```
==> /usr/local/Cellar/dbt/0.5.4/bin/dbt help
usage: dbt: data build tool [-h] [--version]
                            {init,clean,compile,debug,deps,archive,run,seed,test}
                            ...
dbt: data build tool: error: invalid choice: 'help' (choose from 'init', 'clean', 'compile', 'debug', 'deps', 'archive', 'run', 'seed', 'test')
Error: dbt: failed
```

2016-12-22 03:09 UTC, cmcarthur commented
@woodruffw thanks for the comments. I've pushed commits to fix these issues, let me know if you'd like me to amend into one commit and so on.

2016-12-22 03:12 UTC, woodruffw commented
I think you need to rebase -- it looks like you pulled some history onto this branch by accident.

2016-12-22 04:03 UTC, cmcarthur commented
@woodruffw done

2016-12-25 20:55 UTC, MikeMcQuaid requested changes

2016-12-25 20:55 UTC, MikeMcQuaid commented on Formula/dbt.rb
> +  depends_on :python3
Should perhaps be `"python3"`; worth testing locally to see if that works.

2016-12-25 20:55 UTC, MikeMcQuaid commented on Formula/dbt.rb
> +  depends_on :postgresql
Should be `"postgresql"`

2016-12-25 20:55 UTC, MikeMcQuaid commented on Formula/dbt.rb
> +    system "#{bin}/dbt", "-h"
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2016-12-27 16:23 UTC, cmcarthur commented
@MikeMcQuaid I stringified the `depends_on` entries, and added a more sophisticated test. Tested with ```
brew uninstall dbt
brew install --build-from-source dbt
brew test dbt
```

2016-12-29 11:59 UTC, MikeMcQuaid approved these changes

2016-12-29 12:05 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-12-29 12:05 UTC, closed without merging