lasso 2.5.1 (new formula)
Homebrew/homebrew-core pull request #8130
Opened 2016-12-22 13:08 UTC by protomouse

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

[Lasso](http://lasso.entrouvert.org) implements SAML 2.0 and related protocols.

**Note**: the core C library comes with a bunch of language bindings. I gave up trying to get them to install properly, and thus they are all disabled.

2016-12-22 17:40 UTC, bfontaine commented on Formula/lasso.rb
> +                   "-I/usr/include/libxml2",
Shouldn’t that use `Formula["libxml2"].include`?

2016-12-25 20:56 UTC, MikeMcQuaid requested changes

2016-12-25 20:56 UTC, MikeMcQuaid commented on Formula/lasso.rb
> +  depends_on "libxml2"
Can this use the system `libxml2`?

2016-12-25 20:56 UTC, MikeMcQuaid commented on Formula/lasso.rb
> +                   "-I/usr/include/libxml2",
Yes but ideally it'll just use the system version.

2016-12-28 12:05 UTC, protomouse commented on Formula/lasso.rb
> +  depends_on "libxml2"
Yep. Also libxslt.

2016-12-28 12:17 UTC, ilovezfs commented on Formula/lasso.rb
> +                   "-I/usr/include/libxml2",
Without the CLT,
```
robotunicorn # ls /usr/include                                              [~]
ls: /usr/include: No such file or directory
```
so I think we'd need to vendor the header if it needs it to use the system version, no?

2016-12-28 12:19 UTC, ilovezfs commented on Formula/lasso.rb
> +                   "-I/usr/include/libxml2",
Ah it's in the SDK too, so I think we want

```
"-I#{MacOS.sdk_path}/usr/include/libxml2"
```

```
"-I#{MacOS.sdk_path}/usr/include/libxslt"
```
unless it's already working without adding anything.

2016-12-30 13:57 UTC, MikeMcQuaid approved these changes

2016-12-30 14:18 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-12-30 14:18 UTC, closed without merging