gst-plugins-bad.rb fixed for Mavericks
Homebrew/homebrew-core pull request #8142
Opened 2016-12-23 01:17 UTC by tomoprime

apple media now working for Mavericks

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-12-23 08:11 UTC, ilovezfs commented
Do you know when/where (i.e., in which commit) this was fixed upstream?

2016-12-23 10:38 UTC, tomoprime commented
It was working in 10.1.2 commit 5c4e9f2. I haven't looked beyond that.

2016-12-25 21:00 UTC, MikeMcQuaid requested changes

2016-12-25 21:00 UTC, MikeMcQuaid commented on Formula/gst-plugins-bad.rb
> +    # end
Rather than commenting this out please remove all these lines (including your new comment). Thanks!

2016-12-25 22:31 UTC, MikeMcQuaid approved these changes

2016-12-29 12:02 UTC, merged

2016-12-29 12:02 UTC, MikeMcQuaid commented
Thanks for your first  contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `gst-plugins-bad: apple media fixed on 10.9`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!