uptimed:add plist_options and update test
Homebrew/homebrew-core pull request #8234
Opened 2016-12-26 16:54 UTC by GauthamGoli

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-12-29 11:51 UTC, MikeMcQuaid requested changes
Thanks for the PR! A few comments here.

2016-12-29 11:51 UTC, MikeMcQuaid commented on Formula/uptimed.rb
> +    system "#{opt_sbin}/uptimed", "-t", "0"
Use just `sbin` here.

2016-12-29 11:51 UTC, MikeMcQuaid commented on Formula/uptimed.rb
> +    sleep(2.0)
`sleep 2`

2016-12-29 11:51 UTC, MikeMcQuaid commented on Formula/uptimed.rb
> +    assert(shell_output("#{bin}/uprecords -s | awk '/->/ {print $3}'").to_i>=0, "Uptime returned is invalid")
Use `assert_match` instead of `awk` here.

2016-12-30 14:01 UTC, MikeMcQuaid approved these changes

2016-12-30 14:13 UTC, merged

2016-12-30 14:13 UTC, MikeMcQuaid commented
Thanks again @GauthamGoli!

2016-12-30 14:21 UTC, GauthamGoli commented
Thanks for the code review!