crystal-icr 0.2.13 (new formula)
Homebrew/homebrew-core pull request #8246
Opened 2016-12-27 14:01 UTC by damireh

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests]
(https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Trying to revive what was started here https://github.com/Homebrew/homebrew-core/pull/1579

2016-12-29 11:58 UTC, MikeMcQuaid requested changes
One nit otherwise 👍

2016-12-29 11:58 UTC, MikeMcQuaid commented on Formula/crystal-icr.rb
> +    assert_equal "icr version #{version}\n", shell_output("#{bin/"icr"} -v").lines.first
Use `assert_match` and skip the `lines.first`.

2016-12-30 10:54 UTC, damireh commented on Formula/crystal-icr.rb
> +    assert_equal "icr version #{version}\n", shell_output("#{bin/"icr"} -v").lines.first
done

2016-12-30 14:19 UTC, MikeMcQuaid approved these changes

2016-12-30 14:19 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-12-30 14:20 UTC, closed without merging