tcl-tk: remove sqlite extension on Linux
Homebrew/homebrew-core pull request #82698
Opened 2021-08-04 22:05 UTC by cho-m

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Conflict in #81888 where both `tcl-tk` and `sqlite-analyzer` create a `sqlite3_analyzer` executable.

Need to check on bottled files before merging, so added `do not merge` label.

Also disabled in:
- Arch Linux https://github.com/archlinux/svntogit-packages/blob/packages/tcl/trunk/PKGBUILD#L15-L19
    ```
    prepare() {
      cd tcl${pkgver}
      # we build the tcl sqlite interface in sqlite-tcl package
      rm -rf pkgs/sqlite3*
    }
    ```
- MacPorts https://github.com/macports/macports-ports/blob/master/lang/tcl/Portfile#L39-L42
    ```
    pre-configure {
        # sqlite3 package is provided by sqlite3-tcl
        delete [glob ${worksrcpath}/../pkgs/sqlite*]
    }
    ```

Can probably leave in macOS as keg_only there. 

Alternatively, can follow Arch and MacPorts and provide `sqlite-tcl` formula built from latest SQLite source code.

2021-08-05 03:32 UTC, iMichka commented
This will need a rev-bump I guess, to ship new bottles?

2021-08-05 04:02 UTC, cho-m commented
> This will need a rev-bump I guess, to ship new bottles to our users.

Wasn't sure how we were dealing with Linux-specific changes.

Though, I am still deciding if this change should be done on macOS too. And perhaps split off a `sqlite-tcl` formula for anyone who wanted Sqlite TCL extensions beyond the tools like `sqlite-analyzer`.

Not sure what is best way to handle here. MacPorts uses subports for some of these:
- `tcl` is a Port and has removed Sqlite part
- `sqlite` is a Port with main database
- `sqlite-tcl` is a SubPort
- `sqlite-tools` is a SubPort with `sqlite-analyzer` and `sqldiff` (while we split these into separate formulae).

2021-11-08 08:25 UTC, SMillerDev submitted a review, later dismissed

2021-11-12 18:08 UTC, iMichka requested changes
This feels a little bit weird now:
On Linux you should now install `sqlite_analyzer` to use sqlite_analyzer, with the newest `tcl-tk` version.
On macOS you need to install `tcl-tk` to get and older version of `sqlite3_analyzer` but with the newest version of `tcl-tk`. If you want the newest version of `sqlite_analyzer` you can install `sqlite_analyzer`, but you'll be stuck with an outdated system `tcl-tk`.

I think I would rather always delete `sqlite3_analyzer` from the `tcl-tk` formula (for macOS and Linux), and add a plain `depends_on "tcl-tk"` in the the `sqlite_analyzer`, so that is uses the newest `tcl-tk` on both Mac and Linux.

2021-12-30 23:19 UTC, iMichka commented
Any feedback on my comment above? I can implement it in this PR if you want.

2021-12-31 09:59 UTC, SMillerDev commented
Always deleting it sounds good, but could we use `uses_from_macos "tcl-tk"` instead?

2021-12-31 11:23 UTC, iMichka commented
Yes, we can. I made the necessary change. Re-running CI to see how this goes.

2021-12-31 14:47 UTC, carlocab commented on Formula/tcl-tk.rb
> +    rm bin/"sqlite3_analyzer"
This should be documented in a caveat as in other formulae (e.g. as in `git`)

2022-01-01 19:32 UTC, iMichka commented
I added the caveats. Rebuilding without testing the reverse deps, the only failure is known (persona-server, #91964)

2022-01-01 19:41 UTC, SMillerDev approved these changes

2022-01-01 22:16 UTC, iMichka approved these changes

2022-01-01 23:09 UTC, closed without merging