global: --with-universal-ctags
Homebrew/homebrew-core pull request #8309
Opened 2016-12-30 06:27 UTC by ivanbrennan

GNU Global offers support for Exuberant Ctags and Universal Ctags as plug-in parsers, but the current `global` formula only exposes the Exuberant Ctags option.

This is problematic, as Universal Ctags is the actively maintained/developed implementation. The [Global documentation](https://www.gnu.org/software/global/manual/global.html#Plug_002din) describes how to configure Universal Ctags and makes no mention of Exuberant Ctags.

Expose `--with-universal-ctags` option to remedy this.

To install:

    $ brew tap universal-ctags/universal-ctags
    $ brew install --HEAD universal-ctags
    $ brew install global --with-universal-ctags

To use:

    $ export GTAGSCONF=/usr/local/share/gtags/gtags.conf
    $ export GTAGSLABEL=new-ctags
    $ gtags                         # gtags invokes Universal Ctags internally

References:
  https://www.gnu.org/software/global/manual/global.html#Plug_002din
  https://github.com/universal-ctags/homebrew-universal-ctags

2016-12-30 12:53 UTC, ivanbrennan commented
Tests are currently failing because the formula can't find the `universal-ctags` formula (I ran tests locally, but only after running `brew tap universal-ctags/universal-ctags`.

I'm looking into either auto-tapping or providing an informative error in such cases -- not sure which is the preferred behavior.

2016-12-30 13:47 UTC, ivanbrennan commented
I updated the `depends_on` call to correctly reference the tapped `universal-ctags` formula:
```diff
 -  depends_on "universal-ctags" => :optional
 +  depends_on "universal-ctags/universal-ctags/universal-ctags" => :optional
```

2016-12-30 13:53 UTC, MikeMcQuaid requested changes

2016-12-30 13:53 UTC, MikeMcQuaid commented on Formula/global.rb
> +  depends_on "universal-ctags/universal-ctags/universal-ctags" => :optional
We don't want homebrew/core formulae depending on non-Homebrew organisation taps as options. Could this be submitted to homebrew/core?

2016-12-30 13:53 UTC, MikeMcQuaid commented on Formula/global.rb
> +  revision 1
Don't need this unless you modify the non-option installation.

2016-12-30 13:53 UTC, MikeMcQuaid commented on Formula/global.rb
> +    if build.with? "universal-ctags"
Probably not worth adding this; these tests are only for CI and thus will never be run with options so this code will never be run.

2016-12-30 13:53 UTC, ivanbrennan commented on Formula/global.rb
> +  revision 1
I wasn't sure whether exposing a new option warranted/required adding a `revision`. I'm starting to suspect not, but I'll leave this for now to get some outside feedback.

2016-12-30 14:04 UTC, MikeMcQuaid commented on Formula/global.rb
> +  revision 1
It definitely doesn't so you can remove it, thanks. A `revision` will force a reinstall and, in some cases, rebuild for everyone using this.

2016-12-30 15:17 UTC, ivanbrennan commented on Formula/global.rb
> +  depends_on "universal-ctags/universal-ctags/universal-ctags" => :optional
@MikeMcQuaid The [universal-ctags tap](https://github.com/universal-ctags/homebrew-universal-ctags) mentions,

> When Universal Ctags has a tagged release, this formula should be moved to the official Homebrew repository. This repo should then be deleted.

Indeed, [universal ctags](https://github.com/universal-ctags/ctags) still has no tagged release. I'll check with the maintainers on the status of that. Is a tagged release a prerequisite for submitting to homebrew/core?

2016-12-30 15:46 UTC, MikeMcQuaid commented on Formula/global.rb
> +  depends_on "universal-ctags/universal-ctags/universal-ctags" => :optional
It is, yep.

2017-01-07 19:49 UTC, dunn commented
Do you have any idea when a stable release is expected?

2017-01-07 20:20 UTC, ivanbrennan commented
@dunn I found multiple universal ctags issues discussing their plans for a release, but it all seems up in the air at the moment. For reference:
https://github.com/universal-ctags/ctags/issues/1038
https://github.com/universal-ctags/ctags/issues/664
https://github.com/universal-ctags/ctags/issues/658
https://github.com/universal-ctags/ctags/issues/909
https://github.com/universal-ctags/ctags/issues/662
https://github.com/universal-ctags/ctags/issues/652

Apologies for the barrage of links, maybe too much information, but that's what I found.

2017-01-07 23:17 UTC, dunn commented
Thanks!  If there's no definite ETA, you can still leave this PR open, but we're gonna want that stable release before merging.

2017-01-08 00:57 UTC, ivanbrennan commented
Sounds good. Thanks @dunn

2017-03-19 16:40 UTC, MikeMcQuaid commented
Closing until we've got a stable release.

2017-03-19 16:40 UTC, closed without merging