mps-youtube 0.2.7.1 (new formula)
Homebrew/homebrew-core pull request #8310
Opened 2016-12-30 06:42 UTC by tonynater

Adds a new formula for mps-youtube, a terminal based YouTube player
and downloader.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2016-12-30 14:12 UTC, MikeMcQuaid requested changes

2016-12-30 14:12 UTC, MikeMcQuaid commented on Formula/mps-youtube.rb
> +    "/pafy-0.5.2.tar.gz"
Just leave this on one line, thanks.

2016-12-30 14:12 UTC, MikeMcQuaid commented on Formula/mps-youtube.rb
> +    system "#{bin}/mpsyt", "/helloworld,", "q"
It's maybe worth trying to download something small here instead?

2016-12-30 14:12 UTC, MikeMcQuaid commented on Formula/mps-youtube.rb
> +  depends_on :python3
Can you see if this works with `"python3"`? Thanks!

2016-12-30 17:53 UTC, tonynater commented on Formula/mps-youtube.rb
> +  depends_on :python3
Works.

2016-12-30 17:54 UTC, tonynater commented on Formula/mps-youtube.rb
> +    "/pafy-0.5.2.tar.gz"
Fixed. For future reference, is there a limit of line width?

2016-12-30 17:54 UTC, tonynater commented on Formula/mps-youtube.rb
> +    system "#{bin}/mpsyt", "/helloworld,", "q"
Changed so it downloads a song.

2016-12-31 17:07 UTC, MikeMcQuaid approved these changes

2016-12-31 17:14 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-12-31 17:15 UTC, closed without merging