mu: fix HEAD build failure due to miss a dependency
Homebrew/homebrew-core pull request #8328
Opened 2016-12-30 13:27 UTC by junkw

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
`mu` at HEAD depends on `autoconf-archive`, so I added it as a build dependency.

See https://github.com/djcb/mu/issues/975

2016-12-30 14:13 UTC, MikeMcQuaid requested changes

2016-12-30 14:13 UTC, MikeMcQuaid commented on Formula/mu.rb
> +  depends_on "autoconf-archive" => :build if build.head?
Create a `head do` block and put the `url "https://github.com/djcb/mu.git"` and `depends_on "autoconf-archive" => :build` in there.

2016-12-30 16:31 UTC, junkw commented on Formula/mu.rb
> +  depends_on "autoconf-archive" => :build if build.head?
Thanks for your review.

2016-12-30 17:17 UTC, MikeMcQuaid approved these changes

2016-12-30 17:17 UTC, merged

2016-12-30 17:17 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2016-12-31 02:09 UTC, junkw commented
Thanks for your review again and the merge