gnome-autoar 0.1.1 (new formula)
Homebrew/homebrew-core pull request #8330
Opened 2016-12-30 15:29 UTC by matthiasclasen

This commit adds a formula for GNOME autoar, which is
a convenience library providing GIO-style async wrappers
around libarchive.

2016-12-30 15:59 UTC, MikeMcQuaid requested changes

2016-12-30 15:59 UTC, MikeMcQuaid commented on Formula/gnome-autoar.rb
> +    system "false"
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2016-12-30 16:01 UTC, MikeMcQuaid commented
Please fill out the pull request template as requested. There's a bunch of audit failures: https://bot.brew.sh/job/Homebrew%20Core/13867/version=sierra/testReport/junit/brew-test-bot/sierra/audit_gnome_autoar___online___new_formula/

Maintainers note: we can waive the notability requirement here because it's from the GNOME project. CC @tschoonj who may be interested.

2016-12-30 19:20 UTC, tschoonj commented
Hi @matthiasclasen,

Last week I created a Formula for this package, as a dependency for GNOME recipes, but since I couldn't get that one to compile, I forgot about the whole thing.

Am I correct in assuming that todays recipes 0.4.2 release now supports macOS as well? And that you plan on creating a formula for that one too when this one gets merged in?

Anyway, let me help you a bit here: I will commit a proper test in a bit...

2016-12-31 13:30 UTC, matthiasclasen commented
Thanks for your help, tschoonj !

And yes, recipes 0.4.2 should be buildable on OS X with --disable-autoar. Once this formula is in, getting it to build with the dependencies should just be a matter of fixing some more compiler warnings.

2016-12-31 17:09 UTC, MikeMcQuaid approved these changes

2017-01-01 18:24 UTC, closed without merging