yt-dlp 2021.08.10 (new formula)
Homebrew/homebrew-core pull request #84049
Opened 2021-08-26 17:12 UTC by herrriehm

yt-dlp is a fork of youtube-dl. As such, this formula is heavily based on youtube-dl's formula.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Unfortunately, I cannot quite get `brew install --build-from-source yt-dlp` to not fail. But I don’t know why. Can anybody help me?

2021-08-27 02:40 UTC, ctsrc requested changes

2021-08-28 05:45 UTC, herrriehm commented on Formula/yt-dlp.rb
> +end
@ctsrc thank you very much for your help!

2021-08-28 11:07 UTC, herrriehm commented on Formula/yt-dlp.rb
> +  sha256 "15bd1028840e9230f7b89ee928914b119858b9011c7083c6cb0c5a60d525f1e6"
thanks for your help @cho-m! I added the changes of @ctsrc and got the formula working.

2021-08-30 06:06 UTC, chenrui333 approved these changes

2021-08-30 06:08 UTC, chenrui333 commented
@herrriehm, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

2021-08-30 06:08 UTC, closed without merging

2021-08-30 14:30 UTC, nao20010128nao commented
Just curiosity, how long does it take to reflect yt-dlp releases into core's yt-dlp formulae?

2021-08-30 15:44 UTC, ctsrc commented
@nao20010128nao my experience is that pull requests for updated releases are merged quickly. I see that you guys over on yt-dlp started maintaining a homebrew tap. I think that it would be better to submit pull requests for updating the formula here in homebrew core instead. This way it’s one less step for users.

2021-09-02 08:23 UTC, ctsrc commented
@nao20010128nao now that a couple of updated yt-dlp releases have been submitted and merged, you can see they are quite quick :)

See #84432 and #84438