statik 0.10.4 (new formula)
Homebrew/homebrew-core pull request #8413
Opened 2017-01-02 17:57 UTC by thanethomson

This commit adds Statik (https://getstatik.com) as a new formula for
Homebrew. Statik is a Python-based static web site generator aimed at
developers, and allows for the creation of almost any kind of static web
site (not at all limited to blogs). See the wiki for more details:
https://github.com/thanethomson/statik/wiki

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-02 17:58 UTC, MikeMcQuaid commented on Formula/statik.rb
> +    system bin/"statik", "--version"
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2017-01-02 18:30 UTC, thanethomson commented
I've now added a more detailed unit test for installation - it tests the actual functionality of Statik.

2017-01-02 18:48 UTC, thanethomson commented on Formula/statik.rb
> +    system bin/"statik", "--version"
Done 😀

2017-01-03 13:18 UTC, MikeMcQuaid requested changes
Almost there, some tiny nits remaining.

2017-01-03 13:18 UTC, MikeMcQuaid commented on Formula/statik.rb
> +    (testpath/"models/Post.yml").write <<-EOS.undent
The ones on a single line you can probably just do `.write("title: String")`?

2017-01-03 13:18 UTC, MikeMcQuaid commented on Formula/statik.rb
> +    assert File.exist? testpath/"public/index.html"
Add a second argument to the asserts to describe what the failing assertion means e.g. `, "index.html was not created!"`

2017-01-03 13:48 UTC, thanethomson commented on Formula/statik.rb
> +    (testpath/"models/Post.yml").write <<-EOS.undent
Done

2017-01-03 13:48 UTC, thanethomson commented on Formula/statik.rb
> +    assert File.exist? testpath/"public/index.html"
And done 😀

2017-01-05 07:16 UTC, thanethomson commented
Changes made 😀

2017-01-07 13:39 UTC, MikeMcQuaid approved these changes

2017-01-07 13:54 UTC, closed without merging

2017-01-07 14:06 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!