stathat 0.2.0 (new formula)
Homebrew/homebrew-core pull request #8464
Opened 2017-01-04 04:34 UTC by patrickxb

Installs stathat command, a command-line interface to
the stathat.com service.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-04 11:31 UTC, bfontaine requested changes

2017-01-04 11:31 UTC, bfontaine commented on Formula/stathat.rb
> +    bin.install "stathat"
Use `system "go", "build", "-o", bin/"stathat", ...` to avoid this step.

2017-01-04 11:31 UTC, bfontaine commented on Formula/stathat.rb
> +    ENV["GOBIN"] = buildpath
Do we really need to set `GOBIN` here?

2017-01-04 11:31 UTC, bfontaine commented on Formula/stathat.rb
> +    system "#{bin}/stathat", "version"
Can’t we write a test that does something more than just printing the version?

2017-01-06 02:06 UTC, patrickxb commented on Formula/stathat.rb
> +    ENV["GOBIN"] = buildpath
removed

2017-01-06 02:06 UTC, patrickxb commented on Formula/stathat.rb
> +    bin.install "stathat"
Ok, thanks!

2017-01-06 02:07 UTC, patrickxb commented on Formula/stathat.rb
> +    system "#{bin}/stathat", "version"
I'll work on a better test, but most everything else requires a configured account.

What would you prefer?  Something that hit the stathat.com servers?

2017-01-06 09:43 UTC, bfontaine commented on Formula/stathat.rb
> +    system "#{bin}/stathat", "version"
Can we hit `stathat.com` without an account?

2017-01-07 01:46 UTC, woodruffw commented on Formula/stathat.rb
> +    system "go", "build", "-o" bin/"stathat", "-a", "github.com/stathat/cmd/stathat"
Missing a comma between `"-o"` and `bin/"stathat"` (causing a syntax error)

2017-01-07 01:46 UTC, woodruffw commented on Formula/stathat.rb
> +    system "#{bin}/stathat", "version"
Any chance of a more in-depth test here?

2017-03-10 23:08 UTC, bfontaine commented
Ping?

2017-03-13 08:24 UTC, fxcoudert commented
Closing for now, please reopen when fixed.

2017-03-13 08:24 UTC, closed without merging

2017-05-26 03:51 UTC, patrickxb commented
How do I reopen this?  I added a `ping` command to `cmd/stathat`.  Thanks!

2017-05-26 03:55 UTC, woodruffw commented
@patrickxb I can't reopen it for some reason -- let's go ahead and create a new PR :smile:

2017-05-26 04:19 UTC, patrickxb commented
Ok, thanks...will do!