samba: apply "Fixes the Grouplimit of 16 users os OS X." patch
Homebrew/homebrew-core pull request #84673
Opened 2021-09-04 19:00 UTC by AkihiroSuda

This patch fixes `get_user_groups: failed to get the unix group list` error that occurs when the user belongs to more than 16 groups.

The patch is from https://github.com/Homebrew/legacy-homebrew/pull/10311/files .
Discussed in https://bugzilla.samba.org/show_bug.cgi?id=8773 .

This patch is required for running Samba on GitHub Actions with the default macOS 10.15 runner, which assigns 18 groups for the "runner" user.

```console
$ groups
staff wheel everyone localaccounts _appserverusr admin _appserveradm _lpadmin _webdeveloper com.apple.access_ssh com.apple.sharepoint.group.1 _appstore _lpoperator _developer _analyticsusers com.apple.access_ftp com.apple.access_screensharing com.apple.access_remote_ae
```

The custom GHA runners used in the Homebrew project are not affected.

Other than applying this patch, there is no known workaround to avoid the error.

Note that just dropping the supplemental groups of the `samba-dot-org-smbd` process (with a helper tool that calls `setgroup(2)` syscall) does not seem to work as a workaround, because `samba-dot-org-smbd` calls `getgrouplist(3)`which talks to `opendirectoryd(8)` to obtain the group list, regardless to the current groups of the `samba-dot-org-smbd` process.
https://github.com/samba-team/samba/blob/samba-4.14.7/source3/lib/system_smbd.c#L185

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2021-09-04 19:55 UTC, carlocab requested changes
It looks like upstream have rejected this patch, so I don't think we should be carrying this in the formula, unfortunately.

2021-09-04 19:59 UTC, AkihiroSuda commented
> It looks like upstream have rejected this patch, so I don't think we should be carrying this in the formula, unfortunately.

Is there any workaround?

2021-09-04 20:05 UTC, AkihiroSuda commented
Also, the next version of Lima is likely to depend on this 
https://github.com/lima-vm/lima/pull/188

2021-09-04 20:12 UTC, carlocab commented
The only workaround is to find a patch that upstream will accept.

2021-09-07 16:33 UTC, AkihiroSuda commented
A new patch was submitted to the upstream today: https://gitlab.com/samba-team/samba/-/merge_requests/2156 (Thanks @arichardson!)

Let me close this PR for now and see how the upstream MR goes.

2021-09-07 16:33 UTC, closed without merging

2021-09-10 16:08 UTC, arichardson commented
@carlocab @AkihiroSuda the upstream samba MR was merged as https://gitlab.com/samba-team/samba/-/commit/2c18a982537ea1a62e4d802c9ae0ef06b36158dc, so hopefully applying the new diff is acceptable?

2021-09-10 16:10 UTC, AkihiroSuda commented
Can we just get the commit cherry-picked into the 4.15 upstream?

2021-09-11 06:20 UTC, carlocab commented
> Can we just get the commit cherry-picked into the 4.15 upstream?

This would be ideal. If that isn't done we can carry a backport of https://gitlab.com/samba-team/samba/-/commit/2c18a982537ea1a62e4d802c9ae0ef06b36158dc here.

2021-09-13 10:14 UTC, arichardson commented
Seems like it's been merged into the [v4-15-test branch](https://gitlab.com/samba-team/samba/-/commits/v4-15-test/) so it should be part of 4.15. Can we carry it locally until the formula is updated to 4.15?

2021-09-21 08:12 UTC, AkihiroSuda commented
Opened PR for Samba 4.15 https://github.com/Homebrew/homebrew-core/pull/85648