ydk 0.5.2 (new formula)
Homebrew/homebrew-core pull request #8527
Opened 2017-01-05 18:09 UTC by ylil93

alpha release

- [x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-07 01:36 UTC, woodruffw commented
Possibly a PCRE dependency?

```
CMake Error at /usr/local/Cellar/cmake/3.7.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PCRE (missing: PCRE_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindPCRE.cmake:25 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:132 (find_package)
```

Lots of boost warnings as well, although they don't appear to be fatal for the time being...

2017-01-07 01:36 UTC, woodruffw requested changes

2017-01-07 01:36 UTC, woodruffw commented on Formula/ydk.rb
> +    system "brew", "ls", "--versions", "ydk"
We need a better test than this, something that invokes `ydk` itself in a non-trivial way (i.e., no `--help` or `--version`).

2017-01-11 18:39 UTC, ylil93 commented on Formula/ydk.rb
> +    system "brew", "ls", "--versions", "ydk"
Thanks for the feed back.
Updated the dependencies and test sections.

2017-01-11 20:05 UTC, ylil93 commented
I noticed that after updating PCRE as a dependency, the Jenkins build is still failing - any suggestions on this?

2017-01-13 21:39 UTC, woodruffw commented
Just some minor `audit` problems now:

```
Error: 6 problems in 1 formula
ydk:
  * Use "#{ENV.cxx}" instead of hard-coding "g++"
  * C: 35: col 96: Trailing whitespace detected.
  * C: 36: col 91: Trailing whitespace detected.
  * C: 37: col 92: Trailing whitespace detected.
  * C: 38: col 95: Trailing whitespace detected.
  * C: 39: col 92: Trailing whitespace detected.
```

2017-01-19 00:36 UTC, ylil93 commented
changes made 👌

2017-01-20 21:21 UTC, abhikeshav commented
@woodruffw The requested changes have been made and looks like the CI has passed as well. Can this be merged?

Thanks!

2017-01-21 13:12 UTC, woodruffw commented on Formula/ydk.rb
> +  homepage "https://github.com/abhikeshav/ydk-cpp/blob/master/README.md"
Just `https://github.com/abhikeshav/ydk-cpp`, please.

2017-01-21 13:13 UTC, woodruffw commented on Formula/ydk.rb
> +    system ENV.cxx, "-std=c++11", "-Wall", "-Wextra", "-g", "-O0", "test.cpp", "-otest", "-lboost_log_setup-mt", "-lboost_log-mt", "-lboost_thread-mt", "-lboost_date_time-mt", "-lboost_system-mt", "-
Break this into multiple lines.

2017-01-21 13:18 UTC, woodruffw commented
@abhikeshav I'm a little bit confused by `ydk-cpp`'s ownership. Is packaging this fork intentional, or did @ylil93 intend to package @CiscoDevNet's?

We'll likely require the parent fork here if they control the name (and if that's what people expect).

2017-01-22 01:17 UTC, abhikeshav commented
Thanks for your reply. Yes. @Ciscodevnet is the intended owner

2017-01-22 03:09 UTC, woodruffw commented
The `url` needs to be updated to their copy of the repo, then.

2017-01-23 18:02 UTC, ylil93 commented
changes made

2017-01-25 14:46 UTC, MikeMcQuaid requested changes

2017-01-25 14:46 UTC, MikeMcQuaid commented on Formula/ydk.rb
> +  depends_on :x11 => :optional
Let's remove this, we're trying to reduce options and particularly X11 ones, thanks.

2017-01-25 14:46 UTC, MikeMcQuaid commented on Formula/ydk.rb
> +    cd "core/ydk" do
`mkdir "code/ydk/build" do` should do this more simply

2017-01-31 20:41 UTC, ylil93 commented
Thanks for taking the time to review our formula, but we've decided to host our own tap instead, so you can close this request now.

Thanks again for all the input.

2017-01-31 21:58 UTC, closed without merging