workflows/tests: run tap_syntax using both macOS and Linux dep graphs
Homebrew/homebrew-core pull request #85798
Opened 2021-09-23 14:37 UTC by Bo98

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Some audits depend on whether `on_macos` and `on_linux` blocks are evaluated so we need to perform audits twice - once with `HOMEBREW_SIMULATE_MACOS_ON_LINUX` and once without.

This is not as efficient as it could be - it duplicates `brew style` which is only needed to be performed once. This is however run in parallel, which will help. What we should probably do is adjust brew test-bot so it runs the audits twice within there, adjusting `HOMEBREW_SIMULATE_MACOS_ON_LINUX` between them.

I'm opening this PR however so we can fix the problems it raises first, instead of updating test-bot and breaking things.

2021-09-23 14:39 UTC, SMillerDev approved these changes

2021-09-23 14:45 UTC, dawidd6 requested changes
`needs.tap_syntax.outputs...` lines need to be adjusted now.

2021-09-23 14:46 UTC, Bo98 commented
I'm actually surprised this passed. I fully expected it to flag the libzip & php OpenSSL mixup.

2021-09-23 14:49 UTC, Bo98 commented
Oh: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_auditor.rb#L286-L288

That needs to go really.

2021-09-23 15:01 UTC, MikeMcQuaid commented
> Some audits depend on whether `on_macos` and `on_linux` blocks are evaluated so we need to perform audits twice - once with `HOMEBREW_SIMULATE_MACOS_ON_LINUX` and once without.

I'd suggest we fix this instead. There's no reason we can't examine or evaluate the contents of these blocks. Seems preferable to running things twice and slowing everything down (even if in parallel).

2021-09-23 15:04 UTC, Bo98 commented
> There's no reason we can't examine or evaluate the contents of these blocks. Seems preferable to running things twice and slowing everything down (even if in parallel).

Do you mean evaluate both `on_macos` and `on_linux` in one go? Sounds like it might cause problems if two dependencies were to conflict.

Note that only `audit_deps` would need to run twice. A second `brew audit --only=deps` is what I suggest we do in `brew test-bot` (when all problems it raises is fixed).

2021-09-27 01:50 UTC, Bo98 commented
> Note that only `audit_deps` would need to run twice. A second `brew audit --only=deps` is what I'm suggesting we do in `brew test-bot` (when all problems it raises is fixed) - not the strategy of this PR.

Here's a representation of what I mean: Homebrew/homebrew-test-bot#666.

Though it can't be merged until all existing problems are addressed, and test-bot CI doesn't check for that.

2021-09-27 11:25 UTC, MikeMcQuaid commented
> Do you mean evaluate both `on_macos` and `on_linux` in one go? Sounds like it might cause problems if two dependencies on different platforms were to conflict.

Yes. We're going to need something like this for formulae.brew.sh's dependencies to be correctly generated.

I'd suggest something along the line of doing a `instance_eval` or `class_eval` of the `on_macos` block which just stores the `depends_on` results in a `Hash` or `Dependency` objects or similar that we can use in `Formula#to_hash` for formulae.brew.sh and access these data structures directly in `audit_deps` rather than just looking at e.g. `Formula.dependencies`. 

Make sense? Thoughts?

2021-09-27 23:06 UTC, Bo98 commented
> Yes. We're going to need something like this for formulae.brew.sh's dependencies to be correctly generated.
> 
> I'd suggest something along the line of doing a `instance_eval` or `class_eval` of the `on_macos` block which just stores the `depends_on` results in a `Hash` or `Dependency` objects or similar that we can use in `Formula#to_hash` for formulae.brew.sh and access these data structures directly in `audit_deps` rather than just looking at e.g. `Formula.dependencies`.
> 
> Make sense? Thoughts?

As long as the macOS and Linux dep trees remain separate - yes, that makes sense to me!

2021-09-28 12:16 UTC, MikeMcQuaid reviewed
Pending discussed changes

2021-10-29 00:56 UTC, closed without merging