aircrack-ng: Add devel
Homebrew/homebrew-core pull request #8620
Opened 2017-01-08 16:48 UTC by equal-l2

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-08 17:06 UTC, equal-l2 commented
Hmm, airodump-ng-oui-update on devel seems not to work.
This will need a patch...

Is it impossible to put multiple patches in END block?

2017-01-08 17:08 UTC, equal-l2 commented
Well, I've noticed there is homebrew-patch.
I'll make a PR there for a patch.

2017-01-09 14:01 UTC, MikeMcQuaid requested changes

2017-01-09 14:01 UTC, MikeMcQuaid commented on Formula/aircrack-ng.rb
> +    patch :DATA
Can you please submit this patch to the upstream developers of this project and add a link to the upstream patch submission and explanation of why the patch is needed in a comment in the formula file. I realise you didn't create it but if you could submit it that'd be great. Thanks!

2017-01-09 14:01 UTC, MikeMcQuaid commented on Formula/aircrack-ng.rb
> +        "http://standards-oui.ieee.org/oui.txt"
Can you please submit this patch to the upstream developers of this project and add a link to the upstream patch submission and explanation of why the patch is needed in a comment in the formula file. I realise you didn't create it but if you could submit it that'd be great. Thanks!

2017-01-09 14:01 UTC, MikeMcQuaid commented on Formula/aircrack-ng.rb
> +      url "https://github.com/equal-l2/formula-patches/raw/aircrack-ng/aircrack-ng/aircrack-ng-devel.patch"
Can you please submit this patch to the upstream developers of this project and add a link to the upstream patch submission and explanation of why the patch is needed in a comment in the formula file. Thanks!

2017-01-11 09:10 UTC, nijikon commented
@equal-l2 ping

2017-01-28 14:57 UTC, closed without merging