open-mesh: Fix missing smoother files
Homebrew/homebrew-core pull request #8644
Opened 2017-01-09 11:02 UTC by M-Mueller

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Because of a typo in the cmake files, some files required for the Smoother were not installed, e.g. `#include <OpenMesh/Tools/Smoother/SmootherT.hh>` did not compile.

2017-01-09 14:05 UTC, MikeMcQuaid requested changes

2017-01-09 14:05 UTC, MikeMcQuaid commented on Formula/open-mesh.rb
> +    url "https://graphics.rwth-aachen.de:9000/OpenMesh/OpenMesh/commit/c5cfef87427a793268f9e012856872bbed958d92.diff"
Can you please submit this patch to the upstream developers of this project and add a link to the upstream patch submission (if this is not an upstream commit, it's not clear) and regardless add an explanation of why the patch is needed in a comment in the formula file. Thanks!

2017-01-09 14:28 UTC, M-Mueller commented
I added the comment. The patch is from the upstream repo and integrated in OpenMesh 6.0. I think the project was moved from svn to git, maybe the url in the formula should be updated as well?

2017-01-14 04:47 UTC, dunn commented
> I think the project was moved from svn to git, maybe the url in the formula should be updated as well?

Yes, please.  Thanks!

2017-01-18 10:08 UTC, MikeMcQuaid approved these changes

2017-01-18 10:15 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-01-18 10:16 UTC, closed without merging

2017-01-18 10:46 UTC, M-Mueller commented
Thank you too, for making contributing so easy!