tidy-viewer 0.0.20
Homebrew/homebrew-core pull request #86452
Opened 2021-10-04 21:08 UTC by alexhallam

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2021-10-31 20:56 UTC, iMichka commented on Formula/tidy-viewer.rb
> +  test do
Add a newline between the install and test bloc

2021-10-31 20:56 UTC, iMichka commented
```
  * Formula tidy-viewer contains non-standard SPDX licenses: ["UNLICENSE"].
    For a list of valid licenses check: https://spdx.org/licenses/
```

2021-10-31 20:57 UTC, iMichka commented
Can we compile this from source?

2021-11-01 08:21 UTC, SMillerDev requested changes
Please see https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

2021-11-01 11:57 UTC, closed without merging