kube-aws 0.9.1
Homebrew/homebrew-core pull request #8646
Opened 2017-01-09 12:35 UTC by ArchiFleKs

Created with `brew bump-formula-pr`.

2017-01-09 14:46 UTC, ArchiFleKs commented
Sorry about all this, it is my first time, it should be good now :/

2017-01-14 04:54 UTC, dunn commented
A few more things flagged by the CI bot: https://bot.brew.sh/job/Homebrew%20Core/14430/#showFailuresLink

2017-01-15 15:27 UTC, ArchiFleKs commented
Hi, i'll try to fix that, I'm having some trouble with HEAD and devel and some changes upstream

2017-01-16 17:15 UTC, ArchiFleKs commented
Should be all good now :)

2017-01-18 09:39 UTC, MikeMcQuaid requested changes

2017-01-18 09:39 UTC, MikeMcQuaid commented on Formula/kube-aws.rb
> +  end
Add newline below here.

2017-01-18 09:39 UTC, MikeMcQuaid commented on Formula/kube-aws.rb
> +    ln_s buildpath/".", kube_aws_dir
`ln_s buildpath, kube_aws_dir`

2017-01-18 09:39 UTC, MikeMcQuaid commented on Formula/kube-aws.rb
> +        system "go", "generate", "./config"
The `cd` and `go generate` can be put outside the `if/`else`

2017-01-18 09:39 UTC, MikeMcQuaid commented on Formula/kube-aws.rb
> +      assert_equal cluster, cluster_yaml
Similarly a bunch of the above can be put outside the `if/else`. Can you also share the parts of the hash where possible? Thanks!

2017-01-18 10:41 UTC, ArchiFleKs commented
@MikeMcQuaid : Thanks, I made the changes. What do you mean by parts of the hash ?

2017-01-23 08:02 UTC, MikeMcQuaid requested changes

2017-01-23 08:02 UTC, MikeMcQuaid commented on Formula/kube-aws.rb
> +      if build.devel? || build.head?
Flip the `if`/`else` and do `if build.stable?` ... `else`. Don't do `unless` ...`else`. Thanks!

2017-01-23 08:02 UTC, MikeMcQuaid commented on Formula/kube-aws.rb
> -                "availabilityZone" => "zone", "kmsKeyArn" => "arn" }
```ruby
cluster = { "clusterName" => "test-cluster", "externalDNSName" => "dns",
                  "keyName" => "key", "region" => "west",
                  "availabilityZone" => "zone", "kmsKeyArn" => "arn" }
cluster["controller"] = nil unless build.stable?
```

and then you can remove the `if`/`else`

2017-01-23 08:02 UTC, MikeMcQuaid commented on Formula/kube-aws.rb
> -
Leave this empty line.

2017-01-25 14:39 UTC, MikeMcQuaid commented
@BrewTestBot test this please

2017-01-25 14:39 UTC, MikeMcQuaid approved these changes

2017-01-26 08:17 UTC, ilovezfs commented
@BrewTestBot test this please

2017-01-26 09:16 UTC, nijikon commented
You are awesome, thanks for your contribution! :tada:

2017-01-26 09:16 UTC, closed without merging