source-to-image 1.1.3 (new formula)
Homebrew/homebrew-core pull request #8729
Opened 2017-01-11 11:26 UTC by neckhair

This adds the formula for Openshift's source-to-image tool.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-11 13:03 UTC, bfontaine requested changes

2017-01-11 13:03 UTC, bfontaine commented on Formula/source-to-image.rb
> +  url "https://github.com/openshift/source-to-image/releases/download/v1.1.3/source-to-image-v1.1.3-ddb10f1-darwin-amd64.tar.gz"
We need to build from source here.

2017-01-11 13:03 UTC, bfontaine commented on Formula/source-to-image.rb
> +    system "#{bin}/s2i", "-h"
Can’t we write a test that does something more substantial than e.g. `-v` or `-h`?

2017-01-13 07:49 UTC, neckhair commented on Formula/source-to-image.rb
> +  url "https://github.com/openshift/source-to-image/releases/download/v1.1.3/source-to-image-v1.1.3-ddb10f1-darwin-amd64.tar.gz"
As source-to-image is in Go the user will need that on his machine to build it. Could you explain, please, why we can't just download the already built binary?

2017-01-16 08:59 UTC, bfontaine commented on Formula/source-to-image.rb
> +    assert_match(/Dockerfile/, shell_output("ls").chomp)
You may want to use `assert (testpath/"Dockerfile").exist?` instead of parsing `ls`’s output.

2017-01-16 13:04 UTC, bfontaine commented on Formula/source-to-image.rb
> +  url "https://github.com/openshift/source-to-image/releases/download/v1.1.3/source-to-image-v1.1.3-ddb10f1-darwin-amd64.tar.gz"
We want to have full control over what we build; we provide pre-built binaries ("bottles") so users who don’t want to build from source won’t have to install Go.

See https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#we-dont-like-binary-formulae

2017-01-16 14:05 UTC, neckhair commented
@bfontaine Read some more documentation for building formulas. I'm building it now from source and implemented your suggestions for the test.

2017-01-16 14:07 UTC, bfontaine approved these changes

2017-01-18 09:37 UTC, MikeMcQuaid commented on Formula/source-to-image.rb
> +    assert (testpath/"Dockerfile").exist?
Can you add a second argument here `, "Dockerfile does not exist!"` as the default message is pretty terrible. Thanks!

2017-01-20 09:09 UTC, neckhair commented
@MikeMcQuaid Done.

2017-01-23 04:29 UTC, dunn commented
Thank you! Merged as 091598078999e215e0999a933170c021e6e53958.

2017-01-23 04:29 UTC, closed without merging