luaver 1.0.0-p1
Homebrew/homebrew-core pull request #8747
Opened 2017-01-11 19:41 UTC by jdonaldson

This commit cleans up the luaver installation process.

luaver is not a proper binary, rather it is a set of shell functions
that are typically sourced from a ~/.bashrc

The first change is to not install the sourced file to /usr/local/bin,
but rather to /usr/local/share, and then provide instructions for
sourcing in the caveats.

The next change is to use a git-style installation, rather than a
release download.  This will make it easier to manage versions via tags,
and osx-specific patches via revisions.

I've bumped the version here with a patch (-p1), which will include the
latest os-specific fix, which was added directly after the 1.0 version.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-11 19:46 UTC, jdonaldson commented
CC @umireon

2017-01-11 19:47 UTC, jdonaldson commented
second push fixed some audit nits.

2017-01-12 10:12 UTC, nijikon commented
Why do we install to `share`?

2017-01-12 17:36 UTC, jdonaldson commented
I had seen other brew packages install to `share` if they were intended to be sourced rather than executed directly. [git-bash-prompt](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bash-git-prompt.rb) comes to mind.

I'm open to putting this somewhere else, I just figured /usr/local/bin was not appropriate.  Let me know if there's a better place.

2017-01-14 05:05 UTC, dunn commented
`pkgshare` would be better, thanks!

2017-01-18 09:16 UTC, MikeMcQuaid requested changes

2017-01-18 09:16 UTC, MikeMcQuaid commented on Formula/luaver.rb
> +      :revision => "61861f2a966645a663971cd4e26d2a6104d075f6"
We need to use a tag.

2017-01-18 09:16 UTC, MikeMcQuaid commented on Formula/luaver.rb
> +    share.install "luaver"
`pkgshare`, as mentioned.

2017-01-18 09:16 UTC, MikeMcQuaid commented on Formula/luaver.rb
> -
Leave this space.

2017-01-18 09:24 UTC, umireon commented
We should wait for a new release that will happen soon, or simply remove the `git-style installation'.
I think the other changes are reasonable.

2017-01-18 09:45 UTC, MikeMcQuaid commented
> We should wait for a new release that will happen soon

Yep 👍

2017-01-18 15:05 UTC, jdonaldson commented
In that case, I'll close, and interested parties can use this PR for future reference.

2017-01-18 15:05 UTC, closed without merging