Add back the old imagemagick under the name imagemagick@6
Homebrew/homebrew-core pull request #8756
Opened 2017-01-12 05:50 UTC by crazymykl

This is necessary since `rmagick` does not work with ImageMagick 7.0.x.

Apologies if I'm not following protocol 100%, it was not super clear how new versions of existing formulae should be formatted.

I bought back the formula for the last 6.9.x ImageMagick nearly verbatim, only changing the class name.

2017-01-12 06:14 UTC, ilovezfs commented
I do not think sufficient need for this formula has been demonstrated, especially given that there are no dependents in Homebrew itself that need it. The formula will be broken in terms of the ability of build systems to detect it via pkg-config unless it's made keg only or is marked as conflicting with the main imagemagick formula, which will then interfere with the installation of formulae that depend on imagemagick. My recommendation is that you host this in your own tap for the time being.

2017-01-12 06:26 UTC, ledermann commented
This gist allows installing 6.9.7-3:
https://gist.github.com/ledermann/0825a492abd2d465fc589be2f4e3bff1

2017-01-12 06:27 UTC, ilovezfs commented
@ledermann you should host that in your own tap. This is not an appropriate venue for posting personal formulae files.

2017-01-12 06:28 UTC, zmwangx commented
> My recommendation is that you host this in your own tap for the time being.

The problem with that, in the case of IM, is that it is updated frequently, and whenever an update is issued the old tarball is removed from the server. That's why we brew mirror the tarballs.

But indeed, a formula like this wouldn't work very well. The best compromise is to mark it as keg only, and deal with the hassle of having to specify the opt paths (`PATH`, `LDFLAGS`, `CPPFLAGS`, `PKG_CONFIG_PATH`) where necessary (which isn't always possible in obscure build systems), or force link it if you don't need any revdeps.

At the very least it comes down to

> I do not think sufficient need for this formula has been demonstrated.

2017-01-12 06:29 UTC, ilovezfs commented
>The problem with that, in the case of IM, is that it is updated frequently, and whenever an update is issued the old tarball is removed from the server. 

Perhaps "someone" should convince upstream to knock that behavior off.

2017-01-12 06:31 UTC, zmwangx commented
> Perhaps "someone" should convince upstream to knock that behavior off.

That "someone" might need to foot the bill (which might be negligible; I've no idea).

2017-01-12 06:35 UTC, ilovezfs commented
Is there something deficient about the _orig tarballs on all Debian mirrors? https://mirrors.ocf.berkeley.edu/debian/pool/main/i/imagemagick/

2017-01-12 06:41 UTC, zmwangx commented
Not sure whether dfsg stripping causes problems, I assume not. Two issues:

1. Only a handful of versions are available, most are skipped;
1. Debian removes old tarballs on a regular basis, too.

2017-01-12 06:44 UTC, ilovezfs commented
>Only a handful of versions are available, most are skipped;

Is there some benefit the plethora of updates is providing?

>Debian removes old tarballs on a regular basis, too.

I guess this is one of the reasons `brew update` and the Internet exist.

2017-01-12 06:45 UTC, zmwangx commented
> Is there some benefit the plethora of updates is providing?

2017-01-12 06:47 UTC, zmwangx commented
> Is there some benefit the plethora of updates is providing?

Probably not until you have a CVE.

> I guess this is one of the reasons brew update and the Internet exist.

Well, we're talking about user-hosted taps here... Not really our problem, but still.

2017-01-12 06:47 UTC, ilovezfs commented
User-hosted taps get updated by brew update.

2017-01-12 06:48 UTC, zmwangx commented
It depends on said user updating the formula diligently :)

2017-01-12 06:48 UTC, ilovezfs commented
>It depends on said user updating the formula diligently 

Indeed.

2017-01-12 13:27 UTC, crazymykl commented
Again, the `rmagick` gem, by far the most common reason I have seen ImageMagick installed on macOS, does not build with major version 7. It is unlikely that a version that builds against both 6 and 7 will be forthcoming.,

`rmagick` has [almost 8 million downloads](https://rubygems.org/gems/rmagick/versions/2.15.4).

2017-01-12 13:28 UTC, ilovezfs commented
perhaps we've just given them a reason to add support for 7

2017-01-12 13:32 UTC, crazymykl commented
There's also the question of deployment. A lot of apps are ultimately hosted on OSes which won't have a package for ImageMagick@7 for year, or possibly ever (e. g. CentOS).

Flipping the question: what exists that only builds against ImageMagick@7? Maybe 7 should be made keg-only until it is better supported in the wild than version 6.

2017-01-12 13:33 UTC, ilovezfs commented
It handles all of the Homebrew dependents. There's no reason to make it keg_only.

2017-01-12 13:33 UTC, zmwangx commented
> by far the most common reason I have seen ImageMagick installed on macOS

Experience varies, but I'm pretty sure IM on macOS is more often used as standalone tools. Most of those 8 million downloads could well be on Linux web servers, and I'm pretty sure PHP bindings for IM are more prevalent than the Ruby binding on servers.

> what exists that only builds against ImageMagick@7?

Homebrew ships cutting edge software. That's the nature of the project.

2017-01-12 20:09 UTC, crazymykl commented
I have made a tap, for whoever finds this after googling rmagick homebrew imagemagick 7.

`brew install crazymykl/homebrew-custom/imagemagick@6`

2017-01-14 20:08 UTC, jacquerie commented
Thanks, @crazymykl! I'm using your tap because [Wand 0.4.4](http://docs.wand-py.org/en/0.4.4/) appears to support only ImageMagick@6. With ImageMagick@7 I was getting:
```
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  brew install freetype imagemagick
```
(typing this for the benefit of people searching for the error above).

2017-01-16 08:56 UTC, MikeMcQuaid commented
I talked with @ilovezfs and my understanding of the conversation was that we (or at least I) am happy to accept this as long as it's keg-only.

2017-01-16 15:46 UTC, crazymykl commented on Formula/imagemagick.rb
> +      rmagick 2.x does not work with ImageMagick 7, and some invokations of
Not 100% thrilled with the verbiage here.

2017-01-16 19:48 UTC, crazymykl commented
Updated. Let me know if there's more to do.

2017-01-16 21:08 UTC, MikeMcQuaid requested changes

2017-01-16 21:08 UTC, MikeMcQuaid commented on Formula/imagemagick.rb
> +      `convert` may have changed syntax.
Let's omit this; there's more than just `rmagick` and this isn't in keeping with other formulae updates.

2017-01-16 21:08 UTC, MikeMcQuaid commented on Formula/imagemagick@6.rb
> +  end
Remove the bottle block, it'll get re-added when we pull.

2017-01-16 21:08 UTC, MikeMcQuaid commented on Formula/imagemagick@6.rb
> +  end
Probably just worth removing these caveats (or adjusting them to point to `opt_lib` )

2017-01-16 21:08 UTC, MikeMcQuaid commented on Formula/imagemagick@6.rb
> +  depends_on :x11 => :optional
Let's remove this option.

2017-01-16 22:36 UTC, crazymykl commented
I did the thing.

2017-01-17 10:12 UTC, MikeMcQuaid approved these changes

2017-01-17 10:18 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-01-17 10:19 UTC, closed without merging

2017-01-17 10:31 UTC, MikeMcQuaid commented
@crazymykl You may want to now remove your tap and/or add the according `tap_migrations.json` line.