emscripten 2.0.32
Homebrew/homebrew-core pull request #87624
Opened 2021-10-20 03:44 UTC by chenrui333

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

2021-10-20 08:12 UTC, SMillerDev submitted a review, later dismissed

2021-10-20 08:25 UTC, carlocab requested changes
Their latest release is `2.0.32` here: https://github.com/emscripten-core/emsdk/blob/main/emscripten-releases-tags.json

Do we want to double check with them that they didn't make a typo when tagging a release to avoid any problems with them retagging this later?

2021-10-21 07:29 UTC, carlocab approved these changes

2021-10-21 07:29 UTC, SMillerDev approved these changes

2021-10-21 18:05 UTC, closed without merging