ruby*: import from homebrew/versions
Homebrew/homebrew-core pull request #8767
Opened 2017-01-12 09:44 UTC by hashar

Import ruby versions from homebrew/versions. They are all coinstallable
since https://github.com/Homebrew/homebrew-versions/pull/1509

The naming scheme is adjusted, add ruby-versions names translations to
formula_renames.json

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-12 09:46 UTC, hashar commented
This is not the current versions of the formulae on homebrew-versions but a pull request I have sent there to make the rubies versions to install with a suffix by default [homebrew-versions #1509](https://github.com/Homebrew/homebrew-versions/pull/1509).

@MikeMcQuaid [proposed to migrate the ruby formulae](https://github.com/Homebrew/homebrew-versions/pull/1509#issuecomment-272016412) from homebrew-versions to homebrew-core hence this pull request (  ).

We would want to hold merging this #8767 until homebred-version PR is merged in.

2017-01-12 09:48 UTC, hashar commented
That is a single commit copy pasting the formulae.  Not sure how to import the commit history, might not be so easy to handle :(

2017-01-12 10:04 UTC, nijikon commented
I would really appreciate if each version would be a separate commit also this should be ruby@18, ruby@19 etc, check node for example.

2017-01-12 11:22 UTC, hashar commented
(I have fixed up a few brew audit issues, class names were missing `AT`).

> I would really appreciate if each version would be a separate commit

Not sure there is much point but I will split the commit in several bits once I get the test results.

> This should be ruby@18, ruby@19 etc, check node for example.

If I remember correctly, before 2.0, ruby would break compatibility between "patch" versions. Thus 1.8.0 and 1.8.7 are not quite the same rubies. Ditto for  ruby 1.9.3 which is back compat with 1.9.1 but not with 1.9.0.  So we want to keep the three bits version numbering scheme.  That also aligns with what is in homebrew-versions.

2017-01-12 11:36 UTC, ilovezfs requested changes

2017-01-12 11:36 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +  if provided_by_osx && (build.without? "suffix")
I do not think we should do conditional keg_only like this. There's already a DSL such as ` keg_only :provided_pre_mountain_lion`. Why do they need to be keg_only when provided by macOS? The main ruby formula isn't.

2017-01-12 12:03 UTC, nijikon requested changes

2017-01-12 12:03 UTC, nijikon commented on Formula/ruby@1.8.7.rb
> +class RubyAT187 < Formula
ruby@1.8

2017-01-12 12:03 UTC, nijikon commented on Formula/ruby@1.9.3.rb
> +class RubyAT193 < Formula
ruby@1.9

2017-01-12 12:53 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +  option "without-suffix", "Do not suffix commands with '187' (will become keg-only)"
This is contrary to the behavior of other such options.

2017-01-12 12:54 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +  depends_on :x11 if build.with? "tcltk"
Since this has been deprecated, do we really still need it in the older rubies?

2017-01-12 12:54 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +    inreplace "mkconfig.rb", "    if /^prefix$/ =~ name\n",
this seems like it should be a patch in formula-patches

2017-01-12 12:55 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +    if build.universal?
do we really want universal options on what are basically new formulae?

2017-01-12 12:56 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +    inreplace "instruby.rb" do |s|
this also seems like it could go in a patch

2017-01-12 12:57 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +    config_file = lib/"ruby/#{abi_version}/rubygems/defaults/operating_system.rb"
Can abi_version not be hard coded on versioned formulae?

2017-01-12 12:58 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +    config_file.unlink if config_file.exist?
I think I'd prefer `rm`

2017-01-12 12:58 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +    config_file.unlink if config_file.exist?
Also rm_f would eliminate the need for the exist check

2017-01-12 12:58 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +    mkdir_p rubygems_bindir
tend to use `mkpath` for these

2017-01-12 12:59 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +  def abi_version
probably doesn't need to be a function for the versioned formulae

2017-01-12 13:00 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +    assert_equal "hello\n", hello_text
would be better to use `chomp` here

2017-01-12 13:00 UTC, nijikon commented on Formula/ruby@1.8.7.rb
> +  depends_on :x11 if build.with? "tcltk"
Purge that

2017-01-12 13:00 UTC, nijikon commented on Formula/ruby@1.8.7.rb
> +    if build.universal?
Purge that

2017-01-12 13:01 UTC, nijikon commented on Formula/ruby@1.8.7.rb
> +    config_file.unlink if config_file.exist?
rm_f

2017-01-12 13:04 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +  depends_on "openssl"
is there an option to use secure transport?

2017-01-12 13:05 UTC, ilovezfs commented on Formula/ruby@1.9.3.rb
> +  revision 4
they're new formulae so they do not need revisions

2017-01-12 13:05 UTC, ilovezfs commented on Formula/ruby@2.0.rb
> +  revision 1
no need for revisions on new formulae

2017-01-12 13:06 UTC, ilovezfs commented on Formula/ruby@2.0.rb
> +    sha256 "5e1529fbbff248b8064c00433a1cd7ee5acd0f98c0e840bf0a127c5b7384a870" => :sierra
the old bottle blocks are invalid so should be removed

2017-01-12 13:07 UTC, ilovezfs commented on Formula/ruby@2.2.rb
> +  revision 2
ditto

2017-01-12 13:07 UTC, ilovezfs commented on Formula/ruby@1.8.7.rb
> +  revision 2
ditto

2017-01-12 14:10 UTC, nijikon commented
Actually, why we want to add those? We provide the latest version which we use in our formulas. If somebody needs an older version he/she should install that via rvm or some other software.

2017-01-12 21:06 UTC, hashar commented on Formula/ruby@1.8.7.rb
> +  if provided_by_osx && (build.without? "suffix")
I have marked a given ruby version as keg-only only if the same version is provided by Apple. Leopard (10.5) has ruby 1.8.6, Mavericks (10.9) has ruby 2.0.0.

I wasn't aware of the provided_pre shortcut. Note the comparison is strict so should be `:provided_pre_mavericks`.    That could be done if we drop Leopard entirely which comes with ruby 1.8.6.

For reference from opensource.apple.com:

| Ver | Name | Ruby version
|--|--|--
| 10.12 | sierra | 2.0.0-p648
| 10.11 | el_capitan | 2.0.0-p648
| 10.10 | yosemite | 2.0.0-p481
| 10.9 | mavericks | 2.0.0-p481
| 10.8 | mountain_lion | 1.8.7-p357
| 10.7 | lion | 1.8.7-p357
| 10.6 | snow_leopard | 1.8.7-p174
| 10.5 | leopard | 1.8.6-p287

2017-01-12 21:08 UTC, hashar commented on Formula/ruby@1.8.7.rb
> +class RubyAT187 < Formula
From a previous comment https://github.com/Homebrew/homebrew-core/pull/8767#issuecomment-272139269

That should be the equivalent of an ABI version.  Turns out on previous comment I was wrong for ruby 1.8 and we could use `ruby@1.8` and `class RubyAT18` indeed.

2017-01-12 21:10 UTC, hashar commented on Formula/ruby@1.9.3.rb
> +class RubyAT193 < Formula
From a previous comment https://github.com/Homebrew/homebrew-core/pull/8767#issuecomment-272139269

Given you are the second person to find it misleading, and that ruby 1.9.0 is long gone. I guess we can just go with `ruby@1.8` and `class RubyAT19`.  It is less pure, but that should be good enough for nowadays usage.

2017-01-12 21:17 UTC, hashar commented on Formula/ruby@1.8.7.rb
> +  option "without-suffix", "Do not suffix commands with '187' (will become keg-only)"
The point of my patch is supporting installation of multiple rubies on the same machine, each having a different suffix.  So you can have `/usr/local/bin/ruby187` and `/usr/local/bin/ruby21` alongside.

I thought one might want to install `ruby2.3` and have it installed as `/usr/local/bin/ruby`.  A use case is one dealing with legacy softwares that do not work on ruby2.4 but yet still have to be maintained and the user willing to have that 2.3 as `ruby`.

For Wikimedia, they have that specific use case. They use Debian Jessie with ruby2.1  and a server configuration management system Puppet at 3.7 which does not work with ruby 2.4.  Hence for developers they want to have their `ruby` to be ruby 2.1 (and not 2.0 from Apple or 2.4 from Homebrew). 

Hope that clarify the intent behind `option "without-suffix"`.

2017-01-12 21:32 UTC, hashar commented on Formula/ruby@1.8.7.rb
> +    inreplace "mkconfig.rb", "    if /^prefix$/ =~ name\n",
That patches comes from https://github.com/Homebrew/homebrew-versions/commit/656096eac302fd0ae8d49d56b73f0346811f3b72 by @UniqMartin 

The hotfix is only on ruby 1.8.7, is it really worth porting it to a formula-patches?  If so, I would rather do that in a follow up patch.

2017-01-12 21:39 UTC, hashar commented on Formula/ruby@1.8.7.rb
> +    config_file = lib/"ruby/#{abi_version}/rubygems/defaults/operating_system.rb"
I have dig in the git log, the original intent in homebrew-version is to have each specific formula to be mostly similar.  So you have bits of codes that are essentially the same, and one can just change a few methods to vary per version.

One can try a `diff ruby187.rb ruby193.rb` or `diff ruby20.rb ruby22.rb`.  With the use of a variable the diff is rather small.

homebrew-php has a nice shared abstraction that is reused by formulae. Maybe we can head to ward that later on.

2017-01-12 21:44 UTC, hashar commented on Formula/ruby@1.8.7.rb
> +    config_file.unlink if config_file.exist?
If that matters `rm_f` ignores any error, but that probably does not matter.

2017-01-12 21:46 UTC, hashar commented on Formula/ruby@1.8.7.rb
> +    mkdir_p rubygems_bindir
Given one is an alias of the other, does it really matter?   Maybe the preference for `mkpath` should be enforced via `brew style`.

2017-01-12 21:47 UTC, hashar commented on Formula/ruby@1.9.3.rb
> +  revision 4
Not so new since they have been introduced in homebrew-versions. We could even bump those revisions for each of them?

2017-01-12 21:52 UTC, hashar commented
> Actually, why we want to add those? We provide the latest version which we use in our formulas. If somebody needs an older version he/she should install that via rvm or some other software.

For the same reason there are several node versions when one could uses nvm?   In my experience with end users, it is much easier to just `brew install ruby@2.3`.  See my rationale above on https://github.com/Homebrew/homebrew-core/pull/8767#discussion_r95886521

2017-01-12 21:55 UTC, hashar commented
Thanks for the reviews everyone. I have read and acknowledge all of them, I haven't updated the code though because it is late here and that gives you an opportunity to follow up/clarify where needed :-}

2017-01-16 21:41 UTC, MikeMcQuaid requested changes

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +class RubyAT187 < Formula
Let's just use RubyAT18, yeh.

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +  revision 2
To be explicit in this comment: can remove this `revision`.

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +  end
Remove this `bottle`

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +  option "without-suffix", "Do not suffix commands with '187' (will become keg-only)"
Let's pick one: either install these as `ruby` and make them keg-only or install them with a suffix. Let's remove the option regardless. For Wikimedia it sounds like they may want `rbenv` instead.

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +  if provided_by_osx && (build.without? "suffix")
I agree, this should not be conditional.

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +  depends_on :x11 if build.with? "tcltk"
Yep, lets remove this option.

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +    inreplace "mkconfig.rb", "    if /^prefix$/ =~ name\n",
I think the hot fix is fine in this case.

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +    if build.universal?
Yep, let's remove it.

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +    inreplace "instruby.rb" do |s|
For the sake of just porting this from homebrew/versions I think it's fine as-is.

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +    config_file.unlink if config_file.exist?
Yeh, agreed on `rm_f`

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +    mkdir_p rubygems_bindir
Doesn't really matter but may as well cleanup while you're here, thanks.

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.8.7.rb
> +  def abi_version
I don't have strong feelings here either way.

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.9.3.rb
> +class RubyAT193 < Formula
Yeh, agreed on nowadays usage 👍

2017-01-16 21:41 UTC, MikeMcQuaid commented on Formula/ruby@1.9.3.rb
> +  revision 4
Can just remove them as they will be considered new on migration.

2017-01-16 21:43 UTC, MikeMcQuaid commented
> Thanks for the reviews everyone. I have read and acknowledge all of them, I haven't updated the code though because it is late here and that gives you an opportunity to follow up/clarify where needed :-}

@hashar No worries, should be pretty much complete now, thanks!

2017-01-23 03:44 UTC, dunn commented
This needs rebasing, please!

2017-01-23 07:11 UTC, hashar commented
@dunn I will follow up eventually :}

2017-02-28 00:15 UTC, swrobel commented
@hashar any plans to get back to this or is it worth considering a new PR?

2017-03-12 10:18 UTC, ilovezfs commented
@MikeMcQuaid so are we closing this given that these are covered by https://github.com/Homebrew/homebrew-core/pull/10862 ?

2017-03-12 12:42 UTC, MikeMcQuaid commented
Yes, thanks anyway @hashar!

2017-03-12 12:42 UTC, closed without merging