dillo 3.0.5 (new formula)
Homebrew/homebrew-core pull request #8822
Opened 2017-01-13 21:33 UTC by tsutsu

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-14 08:12 UTC, woodruffw commented on Formula/dillo.rb
> +    system "#{bin}/dillo", "--version"
Can we get a more detailed test than just `--version`?

2017-01-18 09:17 UTC, MikeMcQuaid requested changes

2017-01-18 09:17 UTC, MikeMcQuaid commented on Formula/dillo.rb
> +  patch :DATA
Please link to the HEAD commit/PR as a comment, thanks.

2017-01-20 04:17 UTC, stephengroat commented on Formula/dillo.rb
> +    system "make", "install"
what about adding in a `system "make", "test"`?

2017-01-20 08:24 UTC, MikeMcQuaid commented on Formula/dillo.rb
> +    system "make", "install"
Like elsewhere: if it passes locally for you on macOS and takes <1m then it seems OK.

2017-03-13 08:26 UTC, fxcoudert commented
Closing for now, please reopen when the comments are addressed.

2017-03-13 08:26 UTC, closed without merging