pev: fix checksum
Homebrew/homebrew-core pull request #88460
Opened 2021-10-31 18:17 UTC by n-thumann

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Related to #88329.
[According](https://github.com/merces/pev/issues/157#issuecomment-762504018) to the author the tarball was updated a few days after (18.01.2021) the initial release (12.01.2021) using the same filename. The changes don't affect the binary itself (no rebuild needed).

2021-10-31 22:23 UTC, iMichka approved these changes

2021-10-31 22:25 UTC, iMichka requested changes
```
21-10-31T20:03:58.3693360Z   * Libraries were compiled with a flat namespace.
2021-10-31T20:03:58.3696080Z     This can cause linker errors due to name collisions, and
2021-10-31T20:03:58.3697810Z     is often due to a bug in detecting the macOS version.
2021-10-31T20:03:58.3699530Z       /usr/local/Cellar/pev/0.81/lib/libpe.1.0.dylib
2021-10-31T20:03:58.3701550Z       /usr/local/Cellar/pev/0.81/lib/pev/plugins/csv_plugin.dylib
2021-10-31T20:03:58.3702810Z       /usr/local/Cellar/pev/0.81/lib/pev/plugins/html_plugin.dylib
2021-10-31T20:03:58.3703680Z       /usr/local/Cellar/pev/0.81/lib/pev/plugins/json_plugin.dylib
2021-10-31T20:03:58.3704690Z       /usr/local/Cellar/pev/0.81/lib/pev/plugins/text_plugin.dylib
2021-10-31T20:03:58.3705560Z       /usr/local/Cellar/pev/0.81/lib/pev/plugins/xml_plugin.dylib
```

Can we try to fix this?

2021-11-01 10:18 UTC, carlocab commented
The audit failure is generic though. In particular, it happens on Catalina too, so this is likely not due to the macOS version detection bug.

Upstream should fix this anyway, but I think fixing this is out of scope for this PR.

2021-11-03 18:16 UTC, iMichka approved these changes
Agreed, let's not mix scopes, merging as-is. Thanks all!

2021-11-03 18:16 UTC, merged

2021-11-03 18:19 UTC, carlocab commented
Thanks, @n-thumann!