temporal_tables 1.1.0 (new formula)
Homebrew/homebrew-core pull request #8848
Opened 2017-01-14 12:07 UTC by lifepillar

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

temporal_tables is a PostgreSQL extension to add support for transaction time tables. Compatible with PostgreSQL 9.6.

2017-01-18 09:20 UTC, MikeMcQuaid commented on formula/temporal_tables.rb
> +  depends_on :postgresql
This should probably be `depends_on "postgresql"` or `which("pg_config")` below.

2017-01-18 09:37 UTC, lifepillar commented on formula/temporal_tables.rb
> +  depends_on :postgresql
Fixed, thanks. Please note that there are several other formulas in core that use `:postgresql`:

```
Formula/check_postgres.rb:17:  depends_on :postgresql
Formula/ephemeralpg.rb:15:  depends_on :postgresql
Formula/eralchemy.rb:20:  depends_on :postgresql => :optional
Formula/freediameter.rb:25:    depends_on :postgresql
Formula/gearman.rb:26:  depends_on :postgresql => :optional
Formula/kitchen-sync.rb:21:  depends_on :postgresql => :optional
Formula/libpqxx.rb:16:  depends_on :postgresql
Formula/libzdb.rb:16:  depends_on :postgresql => :recommended
Formula/osm2pgrouting.rb:21:  depends_on :postgresql
Formula/osm2pgsql.rb:16:  depends_on :postgresql
Formula/pdns.rb:32:  depends_on :postgresql => :optional
Formula/pex.rb:15:  depends_on :postgresql
Formula/pg_top.rb:15:  depends_on :postgresql
Formula/pgcli.rb:16:  depends_on :postgresql
Formula/pgloader.rb:17:  depends_on :postgresql => :recommended
Formula/pgpool-ii.rb:14:  depends_on :postgresql
Formula/psqlodbc.rb:23:  depends_on :postgresql
Formula/pure-ftpd.rb:18:  depends_on :postgresql => :optional
Formula/qt5.rb:35:  depends_on :postgresql => :optional
Formula/sphinx.rb:25:  depends_on :postgresql => :optional
Formula/sysbench.rb:20:  depends_on :postgresql => :optional
Formula/urweb.rb:19:  depends_on :postgresql => :optional
Formula/zabbix.rb:20:    depends_on :postgresql if build.without? "mysql"
```

2017-01-18 09:48 UTC, MikeMcQuaid commented on formula/temporal_tables.rb
> +  depends_on :postgresql
It's fine to use it it's just you were assuming the `postgresql` formula would be used.

2017-01-18 10:00 UTC, lifepillar commented on formula/temporal_tables.rb
> +  depends_on :postgresql
Ok, thanks for the clarification!

2017-01-23 04:01 UTC, dunn commented
@BrewTestBot test this please

2017-01-25 15:09 UTC, MikeMcQuaid approved these changes

2017-01-26 18:22 UTC, MikeMcQuaid requested changes
This needs to be in a directory named `Formula`.

2017-01-26 22:17 UTC, dunn commented
Aha, so that's why the bottle wasn't being created.

2017-01-27 06:03 UTC, lifepillar commented
No idea how that happened. I see both `Formula` and `formula` in my fork on GitHub, but in my local checkout I only have `Formula`. And if I fetch or push, it's all up to date. I'll squash one more commit, and try to force push.

2017-01-27 06:15 UTC, lifepillar commented
Apparently, at some point I had staged with `git add formula` instead of `git add Formula`… Likely some weird interactions among macOS case-insensitive file system, Bash case-insensitive completion and Git's  … “gitness”.

2017-01-28 21:55 UTC, dunn commented
Thanks for your patience! Merged as 30fa5a0d446982d0dc63e3e64334e448e270e714.

2017-01-28 21:56 UTC, closed without merging