kahip: fixes the building issue when metis is present
Homebrew/homebrew-core pull request #88786
Opened 2021-11-04 16:12 UTC by BrushXue

Fixes the building issue when when metis is present https://github.com/Homebrew/homebrew-core/issues/88730
Adding metis dependency so the building result is consistent.
No longer requires gcc.
Bump to v3.12.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2021-11-04 22:55 UTC, carlocab requested changes
I don’t think we want to add a dependency just to fix build failure when `metis` is present. We should do it because it adds functionality that most users would find useful.

We also build with GCC  to avoid issues with `open-mpi` having been built with GCC, so we don’t want to change the compiler.

2021-11-04 23:46 UTC, BrushXue commented
> I don’t think we want to add a dependency just to fix build failure when `metis` is present. We should do it because it adds functionality that most users would find useful.

If the user only installs the binary, the bug will never be triggered. So it's fine to leave it.

> We also build with GCC to avoid issues with `open-mpi` having been built with GCC, so we don’t want to change the compiler.

I agree with this part that the compiler should be the same as openmpi to avoid strange issues. However why is openmpi compiled with gcc? I've used many HPC systems and they all provide a clang version of openmpi.

2021-11-05 00:06 UTC, carlocab commented
> If the user only installs the binary, the bug will never be triggered. So it's fine to leave it.

No, it's not fine. We don't expect users to build formulae in Homebrew/core from source, nor do we want to install things that users don't use/need. So if the only purpose of the `metis` dependency is to avoid triggering a bug when building from source, then that's a very hard no to adding this dependency.

> I agree with this part that the compiler should be the same as openmpi to avoid strange issues. However why is openmpi compiled with gcc? I've used many HPC systems and they all provide a clang (or AOCC) version of openmpi.

I was mistaken -- `open-mpi` uses GCC only for `gfortran`. The C/C++ code is compiled with Clang. We can use Clang as the C/C++ compiler, but we should check that `kahip` does not need `gfortran`.

2021-11-05 00:23 UTC, BrushXue commented
There's no fortran code in kahip. I think the reason that the previous formulae use gcc was because back in 2017 it doesn't support clang https://github.com/KaHIP/KaHIP/issues/5 Now it can be compiled without any issue so there's no need to use gcc.

2021-11-05 00:25 UTC, carlocab commented
The GCC change is fine then. We still don't want to add a `metis` dependency.

2021-11-05 00:28 UTC, BrushXue commented
Another way to permanently resolve the potential metis issue is to remove the `-DUSEMETIS` option during compilation. https://github.com/KaHIP/KaHIP/blob/3c7aebe782b4203b9b012244af5610f7d6073619/CMakeLists.txt#L79

2021-11-05 08:55 UTC, SMillerDev commented
There is no metis issue for any usecase we support in Hombrew/Core. This only happens if you compile from source, which is unsupported.

2021-11-05 09:37 UTC, carlocab commented
What happens if you pass `-DLIB_METIS=OFF` to `cmake`?

2021-11-05 14:33 UTC, BrushXue commented
For the gcc part I saw this: https://github.com/Homebrew/homebrew-core/pull/38401#discussion_r274862336
Let me test if openmp works now.

2021-11-05 15:19 UTC, BrushXue commented
I already have `libomp` installed from homebrew for other packages.
Currently in `01.cmake`
```
-- Found OpenMP_C: -Xclang -fopenmp (found version "5.0")
-- Found OpenMP_CXX: -Xclang -fopenmp (found version "5.0")
-- Found OpenMP: TRUE (found version "5.0")
-- OpenMP support detected
```
In `02.make.cc` I can see `/opt/homebrew/lib/libomp.dylib` is found.
Is the `-Xpreprocessor -fopenmp -lomp` hack still required now? The current build doesn't have it.
To switch from `gcc` to `clang`, At least `libomp` needs to be added as a dependency. Is that OK for you?

2021-11-08 18:55 UTC, BrushXue commented
I'm closing this PR as I'm not 100% sure if openmp support 100% works with clang (I don't use openmp at all). Please bump to v3.12 anyway.

2021-11-08 18:55 UTC, closed without merging