Master
Homebrew/homebrew-core pull request #88928
Opened 2021-11-07 12:27 UTC by sschwetz

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2021-11-07 18:06 UTC, carlocab requested changes
Please don't bump the `revision`s for license-only changes.

2021-11-07 18:06 UTC, carlocab commented on Formula/adplug.rb
> +  revision 1
```suggestion
```

2021-11-07 18:06 UTC, carlocab commented on Formula/advancecomp.rb
> +  revision 2
```suggestion
  revision 1
```

2021-11-07 18:06 UTC, carlocab commented on Formula/advancemame.rb
> +  revision 1
```suggestion
```

2021-11-07 18:06 UTC, carlocab commented on Formula/aha.rb
> +  revision 1
```suggestion
```

2021-11-07 18:06 UTC, carlocab commented on Formula/advancescan.rb
> +  revision 1
```suggestion
```

2021-11-07 18:06 UTC, carlocab commented on Formula/advancemenu.rb
> +  revision 1
```suggestion
```

2021-11-08 04:33 UTC, carlocab commented
Thanks for the PR, @sschwetz. Do you have references for these being `*-only` rather than `*-or-later`, or vice-versa? These are usually a little tricky to determine.

It would make this a lot easier to review if you split this PR up so that each of your PRs modifies only 1-3 formulae each.

2021-11-08 05:24 UTC, sschwetz commented
I  went through the code repositories / websites and looked for licensing terms. For sites that specifically mentioned that they were licence version x or later than they got the or-later. Any other repos v3 with no information about moving to newer  licences were marked as  -only.

For GPL-2 I marked as -only if they did not specify V3 due to the issues that are seen with V3

I will seperate further pulls into smaller batches

2021-12-06 07:37 UTC, closed without merging

2021-12-06 07:52 UTC, carlocab commented
Sorry, this requires a bit of time to review because it modifies a lot of formulae. I'll have a look again at this soon.