sqsh 2.5.16.1
Homebrew/homebrew-core pull request #8943
Opened 2017-01-15 20:21 UTC by meissnem

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
`sqsh` was placed in the boneyard on 9/16/2016 because it failed to build. This change fixes the build failure.

I'm unsure of the proper way to reinstate a formula from the boneyard. If this request is accepted, do I create a pull-request against homebrew-boneyard to remove `sqsh` there?

2017-01-18 07:59 UTC, woodruffw commented
One minor audit failure:

```
Error: 1 problem in 1 formula
sqsh:
  * New formulae should not use `deprecated_option`.
```

2017-01-18 10:04 UTC, MikeMcQuaid requested changes

2017-01-18 10:04 UTC, MikeMcQuaid commented on Formula/sqsh.rb
> +  depends_on :x11 => :optional
Remove this option and the `deprecated_option` above.

2017-01-18 10:04 UTC, MikeMcQuaid commented on Formula/sqsh.rb
> +  patch :DATA
What date and what email? I'm tempted to say we wait for a new release before we re-add this.

2017-01-18 10:04 UTC, MikeMcQuaid commented on Formula/sqsh.rb
> +    end
Remove all this.

2017-03-13 08:27 UTC, fxcoudert commented
Closing for now, please reopen when the comments are addressed (and a new release is out).

2017-03-13 08:27 UTC, closed without merging

2017-06-19 18:15 UTC, developish commented
@meissnem can you address those comment and reopen? I'd find it valuable.

2017-06-19 21:47 UTC, woodruffw commented
@developish We probably won't un-boneyard this in either case, since upstream hasn't made a release in ~3 years and we don't want to end up fielding support for their software.

If you'd like to use this, I'd suggest adding it to a [personal tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) with the patch and changes above.