opencv 4.5.4
Homebrew/homebrew-core pull request #89948
Opened 2021-11-25 05:24 UTC by cclauss

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

2021-11-25 07:42 UTC, carlocab reviewed
```
  libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
```
Deleting `openalpr` to deal with the system not being able to allocate memory seems like the wrong thing to do here.

2021-11-25 10:13 UTC, cclauss commented
Please add the [`python-3.10-migration` label](https://github.com/Homebrew/homebrew-core/labels/python-3.10-migration) to this PR because this `openalpr` problem blocks:
* #89948 (this PR)
* #85282
* #87287

2021-11-27 12:26 UTC, cclauss commented
@matthill Do you have any insight into these failures we gt when trying to test against:
https://upload.wikimedia.org/wikipedia/commons/b/b0/California_2018_license_plate_%28USA%29.jpg
```
==> brew test --retry --verbose openalpr
==> FAILED
Full test openalpr output
  ==> Testing openalpr
  cp -p /Users/brew/Library/Caches/Homebrew/downloads/195774c820111f890a628e11f0544ab624568a4435ed3e29408b0a5e3c18a70d--California_2018_license_plate_(USA).jpg /private/tmp/openalpr--testdata-20211125-79036-1lrsu4r/California_2018_license_plate_(USA).jpg
  ==> /opt/homebrew/Cellar/openalpr/2.3.0_2/bin/alpr plate.jpg
  libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
  
  Error: openalpr: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected: 0
    Actual: nil
```

2021-11-27 12:59 UTC, bayandin commented
> @matthill @bayandin Do you have any insight into these failures we get when trying to test against: https://upload.wikimedia.org/wikipedia/commons/b/b0/California_2018_license_plate_%28USA%29.jpg
> 
> ```
> ==> brew test --retry --verbose openalpr
> ==> FAILED
> Full test openalpr output
>   ==> Testing openalpr
>   cp -p /Users/brew/Library/Caches/Homebrew/downloads/195774c820111f890a628e11f0544ab624568a4435ed3e29408b0a5e3c18a70d--California_2018_license_plate_(USA).jpg /private/tmp/openalpr--testdata-20211125-79036-1lrsu4r/California_2018_license_plate_(USA).jpg
>   ==> /opt/homebrew/Cellar/openalpr/2.3.0_2/bin/alpr plate.jpg
>   libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
>   
>   Error: openalpr: failed
>   An exception occurred within a child process:
>     Minitest::Assertion: Expected: 0
>     Actual: nil
> ```

If I understand it correctly, `openalpr` can't allocate enough memory for processing that image. You could try to use a smaller file: https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/California_2018_license_plate_%28USA%29.jpg/320px-California_2018_license_plate_%28USA%29.jpg

2021-11-27 16:26 UTC, cclauss commented
This PR now reverts b005c357c3846dd6f380e4e2e61d305f007429fd

2021-11-27 18:37 UTC, carlocab requested changes

2021-11-27 18:37 UTC, carlocab commented on Formula/openalpr.rb
> +    sha256 mojave:   "64dd8cef3f2fe311304e0fffae5ed50dd37123d6611aae751ba272be956bf334"
Please don't touch the bottle block.

2021-11-28 19:12 UTC, closed without merging