riak 2.2.0
Homebrew/homebrew-core pull request #9011
Opened 2017-01-17 22:37 UTC by schrepfler

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
The build process audit did throw this warning but the riak binary does return a version correctly so I don't have enough info what's the best way to proceed.

```
==> Installing or updating 'rubocop' gem
Fetching: rubocop-0.45.0.gem (100%)
Successfully installed rubocop-0.45.0
1 gem installed
riak:
  * A `test do` test block should be added
  * object files were linked against system openssl
    These object files were linked against the deprecated system OpenSSL or
    the system's private LibreSSL.
    Adding `depends_on "openssl"` to the formula may help.
      /usr/local/Cellar/riak/2.2.0/libexec/lib/crypto-3.1/priv/lib/crypto.so
  * The installation was broken.
    Broken dylib links found:
      /Users/buildbot/masters/riak/riak-build-osx-108-64/build/distdir/riak-2.2.0/deps/eleveldb/c_src/system/lib/libsnappy.1.dylib
Error: 3 problems in 1 formula
```

-----

2017-01-18 09:13 UTC, schrepfler commented
Declaring explicitly openssl did not help (but I guess it didn't hurt either.) Not sure we can fix the last error though.

2017-01-18 10:09 UTC, MikeMcQuaid commented
@schrepfler Can you report this to the upstream project? Thanks!

2017-01-18 20:31 UTC, schrepfler commented
As I don't think this recipe is in any sense worse than the previous version, I'd suggest we merge it anyways. The binary distribution is what basho ships so I don't think we can retroactively fix this version. I've sent a DM to a person in the basho team, hopefully it will be picked up in the next release.

2017-01-19 12:55 UTC, schrepfler commented
Any thoughts?

2017-01-19 15:26 UTC, MikeMcQuaid commented
We've been verbally told this would be fixed for a while. We can't ship this version but we can block this version from shipping until we have at least an upstream bug report. Is that something you could do? Thanks!

2017-01-20 12:20 UTC, schrepfler commented
Bug created upstream.

2017-01-28 21:54 UTC, schrepfler commented
Can this now be merged as I don't fully understand why would this be a problem. This is using the officially distributed binary which if I understand correctly has a broken symlink to an internal library. However if this is not really breaking functionally the package or pollutes system libraries why would it be blocked from joining the recipes? I've also reported the issue upstream so we can also hope to get it fixed in some future release.

2017-01-29 16:59 UTC, MikeMcQuaid commented
> * object files were linked against system openssl
>     These object files were linked against the deprecated system OpenSSL or
>     the system's private LibreSSL.
>     Adding `depends_on "openssl"` to the formula may help.
>       /usr/local/Cellar/riak/2.2.0/libexec/lib/crypto-3.1/priv/lib/crypto.so

@schrepfler Thanks for filing the issue. Can you file an additional issue for the OpenSSL problem? Thanks!

2017-01-29 16:59 UTC, MikeMcQuaid requested changes

2017-01-29 16:59 UTC, MikeMcQuaid commented on Formula/riak.rb
> +  depends_on "openssl"
Please remove this until it's used.

2017-01-29 18:29 UTC, schrepfler commented on Formula/riak.rb
> +  depends_on "openssl"
@angrycub can we get a bug raised against the basho bug tracker wrt using the system openssl and post it here?

2017-01-29 20:52 UTC, schrepfler commented on Formula/riak.rb
> +  depends_on "openssl"
@MikeMcQuaid removing openssl dependency.

2017-01-29 20:58 UTC, angrycub commented on Formula/riak.rb
> +  depends_on "openssl"
@mikemcquaid.  https://github.com/basho/riak/issues/888 Is the upstream issue that is tracking the OpenSSL linkage issue.   The broken dylib issue is https://github.com/basho/eleveldb/issues/236.

2017-01-30 10:28 UTC, MikeMcQuaid commented on Formula/riak.rb
> +  depends_on "openssl"
@angrycub Thanks!

2017-01-30 10:29 UTC, MikeMcQuaid commented
@schrepfler As a user of this formula: could you consider trying to add a test? Even one using `--version` or `--help` or similar would be better than nothing. Thanks!

2017-01-30 22:46 UTC, schrepfler commented
Test added.

2017-02-01 15:29 UTC, MikeMcQuaid approved these changes

2017-02-01 15:29 UTC, merged

2017-02-01 15:29 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew (and patience)! Without people like you submitting PRs we couldn't run this project. You rock!

2017-02-01 19:44 UTC, schrepfler commented
No problem 😀🙏🏻