mariadb 10.1.21
Homebrew/homebrew-core pull request #9044
Opened 2017-01-18 20:04 UTC by makigumo

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-19 03:05 UTC, woodruffw requested changes

2017-01-19 03:05 UTC, woodruffw commented on Formula/mariadb.rb
> -  option :universal
If we're removing universal builds, this needs to be removed too:

```ruby
# Make universal for binding to universal applications
if build.universal?
      ENV.universal_binary
      args << "-DCMAKE_OSX_ARCHITECTURES=#{Hardware::CPU.universal_archs.as_cmake_arch_flags}"
end
```

2017-01-23 05:37 UTC, makigumo commented on Formula/mariadb.rb
> -  option :universal
Yes, you are right. I updated the PR accordingly. Thx for your keen eyes.

2017-01-23 05:41 UTC, woodruffw approved these changes

2017-01-23 05:43 UTC, woodruffw commented
Thanks @makigumo!

2017-01-23 05:43 UTC, closed without merging