mingw-w64-binutils i686 and x86_64 builds
Homebrew/homebrew-core pull request #9047
Opened 2017-01-18 23:41 UTC by stephengroat

To be compatible with i686 only mingw builds, this change makes
seperate i686 and x86_64 binutils builds for mingw-w64. It also
gives the option to disable multilib

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-19 01:57 UTC, dunn commented on Formula/mingw-w64-binutils.rb
> +    archs.push("i686-w64-mingw32") if build.with?("i686")
We usually use `archs << "i686-w64-mingw32'` etc.; it'd be nice to maintain the convention.

2017-01-19 02:29 UTC, stephengroat commented on Formula/mingw-w64-binutils.rb
> +    archs.push("i686-w64-mingw32") if build.with?("i686")
no problem, i'll fix this on all prs i have open!

2017-01-19 08:17 UTC, fxcoudert commented
Given that binutils build perfectly fine as multilib (i.e. with both i386 and x86_64 targets), why do we want to provide the option of building without one or the other?

Also, why do 2 separate builds of the two archs?

2017-01-19 08:19 UTC, ilovezfs commented
Universal and 32-bit-only builds are both deprecated going forward, so this should only really have a 64 bit build.

2017-01-19 08:21 UTC, fxcoudert commented
@ilovezfs I think there is a misunderstanding: this is a cross-compiler, so when discussing i386 and x86_64 we're not discussing the host (i.e. the macOS machine, for which the build is 64-bit only), but the target (i.e. the Windows machine for which code is generated by the cross-compiler).

2017-01-19 08:24 UTC, MikeMcQuaid commented
> this is a cross-compiler, so when discussing i386 and x86_64 we're not discussing the host (i.e. the macOS machine, for which the build is 64-bit only), but the target (i.e. the Windows machine for which code is generated by the cross-compiler).

That seems fine then, thanks 👍 



> Given that binutils build perfectly fine as multilib (i.e. with both i386 and x86_64 targets), why do we want to provide the option of building without one or the other?
> 
> Also, why do 2 separate builds of the two archs?

I agree. Again, please explain the justification for this PR more @stephengroat.

2017-01-19 16:16 UTC, stephengroat commented
Since multilib builds currently don't work with `mingw-w64` gcc builds, currently to build `i686` binaries you need the `i686` tools (the `mingw-w64` gcc compilation process fails if you use `x86_64` multilib binutils when trying to compile `i686` gcc)

2017-01-19 17:07 UTC, MikeMcQuaid commented
> Since multilib builds currently don't work with mingw-w64 gcc builds, currently to build i686 binaries you need the i686 tools (the mingw-w64 gcc compilation process fails if you use x86_64 multilib binutils when trying to compile i686 gcc)

What do you do if you need to build 32-bit and 64-bit binaries?

2017-01-19 17:32 UTC, stephengroat commented
Currently, have both `i686` tools and `x86_64` tools. I just wanted to create the option to disable either build in case you want to build from source, since each build is about 20 minutes.

Default builds both toolchains

2017-01-19 17:34 UTC, MikeMcQuaid commented
Most users will consume this as a binary package. Let's just remove the non-default options, thanks.

2017-01-19 17:37 UTC, stephengroat commented
can i leave the `without--multilib` option? otherwise, it's impossible to have a non-multilib `x86_64` compiler. `mingw-w64` can be finicky, so have the control to get a non-multilib package sometimes helps

2017-01-19 17:44 UTC, MikeMcQuaid commented
Then we can make non-multilib the default.

2017-01-19 18:45 UTC, stephengroat commented
done

2017-01-20 08:22 UTC, MikeMcQuaid requested changes

2017-01-20 08:22 UTC, MikeMcQuaid commented on Formula/mingw-w64-binutils.rb
> +  option "with-multilib", "Compile x86_64 mingw target with multilib support"
Don't want this option, thanks.

2017-01-20 08:22 UTC, MikeMcQuaid commented
I think this formula should probably just be removed and installed as part of https://github.com/Homebrew/homebrew-core/pull/9037 as I can't see a use for it alone. CC @woodruffw for thoughts.

2017-01-20 08:39 UTC, fxcoudert commented
The case I can see for providing two separate packages for binutils and compiler is that this could allow several compilers, either other than GCC or other versions of GCC, without recompiling/reinstalling binutils every time.

2017-01-20 08:55 UTC, MikeMcQuaid commented
> The case I can see for providing two separate packages for binutils and compiler is that this could allow several compilers, either other than GCC or other versions of GCC, without recompiling/reinstalling binutils every time.

When we have separate compilers we should consider it. When we have one compiler we should not. 

I don't see us providing multiple versions of MinGW.

2017-01-27 16:49 UTC, stephengroat commented
since focus is on #9037, closing this

2017-01-27 16:49 UTC, closed without merging