Added wb32-dfu-updater_cli.rb
Homebrew/homebrew-core pull request #90764
Opened 2021-12-09 08:37 UTC by wb-Joy

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2021-12-09 09:05 UTC, SMillerDev commented on Formula/wb32-dfu-updater_cli.rb
> +  revision 1
This should be left out by default
```suggestion

```

2021-12-09 09:05 UTC, SMillerDev commented on Formula/wb32-dfu-updater_cli.rb
> +class DfuUtil < Formula
```suggestion
class Wb32DfuUpdaterCli < Formula

```

2021-12-09 09:14 UTC, wb-Joy commented on Formula/wb32-dfu-updater_cli.rb
> +    system bin/"wb32-dfu-updater_cli", "-V"
Testing this tool requires hardware support, without hardware can only test the version output.

2021-12-09 09:52 UTC, carlocab commented on Formula/wb32-dfu-updater_cli.rb
> +    end
```suggestion
    system "cmake", "-S", "source/wb32-dfu-updater_cli", "-B", "build", *std_cmake_args
    system "cmake", "--build", "build"
    system "cmake", "--install", "build"
```

2021-12-09 10:01 UTC, carlocab commented on Formula/wb32-dfu-updater_cli.rb
> +    system bin/"wb32-dfu-updater_cli", "-V"
Can we try to use it with non-existent hardware and check we get the expected error/failure message?

2021-12-09 10:04 UTC, wb-Joy commented on Formula/wb32-dfu-updater_cli.rb
> +    system bin/"wb32-dfu-updater_cli", "-V"
An MCU with USB is required and specific firmware is also required.

2021-12-09 10:04 UTC, wb-Joy commented on Formula/wb32-dfu-updater_cli.rb
> +    system bin/"wb32-dfu-updater_cli", "-V"
This software is used for keyboard firmware upgrade.

2021-12-09 10:21 UTC, SMillerDev commented on Formula/wb32-dfu-updater_cli.rb
> +    system bin/"wb32-dfu-updater_cli", "-V"
And if you give it data that it doesn't work with? It gives an error right?

2021-12-09 10:36 UTC, wb-Joy commented on Formula/wb32-dfu-updater_cli.rb
> +    system bin/"wb32-dfu-updater_cli", "-V"
It will give a hint of the correct parameters.

2021-12-09 10:40 UTC, wb-Joy commented on Formula/wb32-dfu-updater_cli.rb
> +    system bin/"wb32-dfu-updater_cli", "-V"
I am an MCU developer, this is my first time developing desktop-level software, I don't understand why there are errors in the test.

2021-12-11 01:55 UTC, Bo98 commented
The default permissions seem unusual:

```
---x------ 1 bo admin 29324 Dec 11 01:51 /usr/local/Cellar/wb32-dfu-updater_cli/0.0.2/bin/wb32-dfu-updater_cli
```

`brew` can't even read the file which is why there's errors.

2021-12-31 02:42 UTC, wb-Joy commented
All the checks have passed, so can the PR be merged?

2022-01-04 09:05 UTC, SMillerDev requested changes
The test still needs to be improved.

It's also self-submitted software, which we generally advise against.

2022-01-04 09:23 UTC, wb-Joy commented
> 
I don't quite understand, I have seen that the test of dfu-util is the same as mine, only printing their version number.
![image](https://user-images.githubusercontent.com/89234190/148037249-02e89f8a-aaaf-4b21-ae29-1a39beacde4a.png)

2022-01-04 09:32 UTC, SMillerDev commented
> I don't quite understand, I have seen that the test of dfu-util is the same as mine, only printing their version number.

Just because old code is bad does not mean that new code must be bad too.

2022-01-04 09:44 UTC, wb-Joy commented
> > I don't quite understand, I have seen that the test of dfu-util is the same as mine, only printing their version number.
> 
> Just because old code is bad does not mean that new code must be bad too.

I added an entry that shows an item of devices. It can only do so much without a hardware connection.

2022-01-04 09:51 UTC, wb-Joy commented
When connecting a hardware device, you can run the -D command to download the firmware or run the -U command to read the firmware. The Windows version msys2 is passed.

2022-01-04 11:27 UTC, carlocab commented on Formula/wb32-dfu-updater_cli.rb
> +    args << "-DLIBUSB_LIBRARIES=#{libusb.opt_lib}/#{shared_library("libusb-1.0")}"
```suggestion
    args << "-DLIBUSB_LIBRARIES=#{libusb.opt_lib/shared_library("libusb-1.0")}"
```
Interpolating twice isn't necessary here.

2022-01-04 11:27 UTC, carlocab commented on Formula/wb32-dfu-updater_cli.rb
> +    end
```suggestion
    system "cmake", "-S", ".", "-B", "build", *args
    system "cmake", "--build", "build"
    system "cmake", "--install", "build"
```
Let's follow the template from `brew create --cmake`.

2022-01-04 11:27 UTC, carlocab commented on Formula/wb32-dfu-updater_cli.rb
> +                        ----------------------------------------\n"
```suggestion
    printing_message = <<~EOS
      wb32-dfu-updater ver: #{version}
      libusb version #{Formula["libusb"].version} (11584)
      ----------------------------------------
    EOS
```
Not quite sure where the `11584` comes from, but I don't think that's something we want to keep static here.

2022-01-18 15:51 UTC, carlocab reviewed
Apologies for the delay, and thanks so much for your work here.

Your repository doesn't quite meet our notability requirements, and we usually don't like self-submitted stuff because that's a poor indicator of whether any of our users will actually use this formula.

If one of your users resubmits this when your repository is slightly more notable (e.g. stars/forks, or is packaged by some other package managers/distros), we'd be happy to reconsider.

2022-01-18 15:51 UTC, carlocab commented on Formula/wb32-dfu-updater_cli.rb
> +    assert_match printing_message, shell_output(bin/"wb32-dfu-updater_cli --list")
```suggestion
    assert_match printing_message, shell_output("#{bin}/wb32-dfu-updater_cli --list")
```

2022-01-18 15:51 UTC, carlocab commented on Formula/wb32-dfu-updater_cli.rb
> +      libusb version #{Formula["libusb"].version} (11584)
Where does `11584` come from?

2022-01-18 15:51 UTC, closed without merging

2022-01-19 07:56 UTC, wb-Joy commented on Formula/wb32-dfu-updater_cli.rb
> +      libusb version #{Formula["libusb"].version} (11584)
> Where does `11584` come from?

version nano.