docker-swarm 1.2.6
Homebrew/homebrew-core pull request #9093
Opened 2017-01-20 07:07 UTC by adrianchia

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-20 14:40 UTC, woodruffw commented
Use the release tarball, please: https://github.com/docker/swarm/archive/v1.2.6.tar.gz

2017-01-20 14:41 UTC, woodruffw requested changes

2017-01-20 14:41 UTC, woodruffw commented on Formula/docker-swarm.rb
> +  url "https://github.com/docker/swarm.git",
Use the release tarball, please: https://github.com/docker/swarm/archive/v1.2.6.tar.gz

We prefer not to clone when possible.

2017-01-21 13:54 UTC, woodruffw approved these changes

2017-01-22 09:18 UTC, nijikon commented
You are awesome, thanks for your contribution! :tada:

2017-01-22 09:19 UTC, closed without merging