maclaunch 0.2 (new formula)
Homebrew/homebrew-core pull request #9104
Opened 2017-01-20 14:34 UTC by HazCod

I wrote a little bash script that allows you to list, enable and disable any launch agents/daemons.

2017-01-20 14:40 UTC, bfontaine requested changes

2017-01-20 14:40 UTC, bfontaine commented on Formula/maclaunch.rb
> +    bin.install "maclaunch"
Use `bin.install "maclaunch.sh" => "maclaunch"`.

2017-01-20 14:40 UTC, bfontaine commented on Formula/maclaunch.rb
> +    # just run the command to test the install
Please remove this comment.

2017-01-20 14:41 UTC, bfontaine commented
Given that it’s a self-submission of a new project we’re going to pass on this for now. You can maintain the formula in your own tap and re-submit it here once it’s popular. Sorry!

https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

2017-01-20 14:41 UTC, closed without merging

2017-01-23 08:43 UTC, HazCod commented
@bfontaine ; just a question, how many repo stars do you require typically? 
Since I mentioned this on reddit, perception was positive.

2017-01-23 09:01 UTC, MikeMcQuaid commented
@HazCod It's not criticism of your project but just that you should wait for someone from your community to submit this when it's more established.