vmdktool 1.4 (new formula)
Homebrew/homebrew-core pull request #9109
Opened 2017-01-20 18:20 UTC by glennmatthews

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2017-01-21 14:03 UTC, woodruffw requested changes

2017-01-21 14:03 UTC, woodruffw commented on Formula/vmdktool.rb
> +    bin.mkpath
Don't worry about these `mkpath`s. Homebrew will handle them.

2017-01-21 14:03 UTC, woodruffw commented on Formula/vmdktool.rb
> +    inreplace "Makefile", "man/man8", "share/man/man8"
Has upstream been alerted of this?

2017-01-21 14:43 UTC, ilovezfs commented on Formula/vmdktool.rb
> +    # Yes, it's a bad test, but vmdktool only does conversions of existing disk images
You can do this
```
    system "dd", "if=/dev/zero", "of=raw", "bs=512", "count=20480"
    system "#{bin}/vmdktool", "-v", "vd", "raw"
    assert_match "RDONLY 20480 SPARSE", pipe_output("strings", File.read("vd"))
```

2017-01-21 14:56 UTC, ilovezfs commented on Formula/vmdktool.rb
> +    # Yes, it's a bad test, but vmdktool only does conversions of existing disk images
or even just
```
    system "dd", "if=/dev/zero", "of=raw", "bs=512", "count=20480"
    system "#{bin}/vmdktool", "-v", "vd", "raw"
    assert_match "RDONLY 20480 SPARSE", shell_output("#{bin}/vmdktool -i vd")
```

2017-01-23 13:47 UTC, glennmatthews commented on Formula/vmdktool.rb
> +    inreplace "Makefile", "man/man8", "share/man/man8"
No, but will do. Thanks.

2017-01-23 16:11 UTC, glennmatthews commented on Formula/vmdktool.rb
> +    # Yes, it's a bad test, but vmdktool only does conversions of existing disk images
Great suggestion! For my use cases I'm not generally creating new images, but this is a great way to validate this. Will do.

2017-01-23 16:23 UTC, glennmatthews commented on Formula/vmdktool.rb
> +    bin.mkpath
Hm, what am I missing? If I remove these, I get:

```
==> make CFLAGS='-D_GNU_SOURCE -g -O -pipe'
==> make install PREFIX=/usr/local/Cellar/vmdktool/1.4
Last 15 lines from /Users/glmatthe/Library/Logs/Homebrew/vmdktool/02.make:
2017-01-23 11:22:09 -0500

make
install
PREFIX=/usr/local/Cellar/vmdktool/1.4

install -s vmdktool /usr/local/Cellar/vmdktool/1.4/bin/
install: /usr/local/Cellar/vmdktool/1.4/bin/: No such file or directory
make: *** [install] Error 71
```

2017-01-23 17:00 UTC, woodruffw commented on Formula/vmdktool.rb
> +    bin.mkpath
Sorry, ignore me. I didn't realize this was prefixed inside the cellar; you'll need those `mkpath`s after all.

2017-01-25 14:48 UTC, MikeMcQuaid requested changes

2017-01-25 14:48 UTC, MikeMcQuaid commented on Formula/vmdktool.rb
> +    inreplace "Makefile", "man/man8", "share/man/man8"
@glennmatthews After creating an issue please add a link to the upstream issue and explanation of why the patch is needed in a comment in the formula file. Also, please do this for the `mkpath`s above too. Thanks!

2017-01-25 15:13 UTC, glennmatthews commented
Hi @MikeMcQuaid - I'm not aware of any public issue tracker for vmdktool. For past bug reports I've emailed the maintainer directly (brian@awfulhak.org) and he's been quite responsive. I emailed him about the MANDIR issue yesterday but haven't seen a response yet. 

Is the issue with the `mkpath`s that the Makefile isn't doing the appropriate `mkdir`s when doing a `make install`? Or what other fix would be desired here?

2017-01-25 15:16 UTC, MikeMcQuaid commented
> Hi @MikeMcQuaid - I'm not aware of any public issue tracker for vmdktool. For past bug reports I've emailed the maintainer directly (brian@awfulhak.org) and he's been quite responsive. I emailed him about the MANDIR issue yesterday but haven't seen a response yet.

That's fine, in that case we just want to note what date they were emailed and a summary of the email and/or their response.

> Is the issue with the mkpaths that the Makefile isn't doing the appropriate mkdirs when doing a make install? Or what other fix would be desired here?

Indeed, do `mkdir` or ideally `mkdir -p` before assuming a directly exists.

2017-01-31 21:37 UTC, glennmatthews commented
Updated diffs with improved test as requested by @ilovezfs and comment about contact with upstream maintainer as requested by @MikeMcQuaid. Thanks!

2017-01-31 21:59 UTC, woodruffw approved these changes

2017-02-07 15:20 UTC, glennmatthews commented
@MikeMcQuaid any remaining concerns I need to address?

2017-02-08 08:19 UTC, MikeMcQuaid approved these changes

2017-02-08 08:21 UTC, ilovezfs approved these changes

2017-02-08 08:24 UTC, ilovezfs commented
@BrewTestBot test this please

2017-02-10 15:56 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-02-10 15:57 UTC, closed without merging