wine 2.0
Homebrew/homebrew-core pull request #9238
Opened 2017-01-24 21:48 UTC by uyjulian

2017-01-24 23:02 UTC, apetresc commented on Formula/wine.rb
> -      sha256 "59f1831a1b49c1b7a4c6e6af7e3f89f0bc60bec0bead645a615b251d37d232ac"
Should this patch actually be removed, or just replaced with https://bugs.winehq.org/attachment.cgi?id=55968 ?

2017-01-25 03:37 UTC, apetresc commented
The `-devel` target needs to be updated so it's not behind the new `-stable`. Though there isn't a devel release yet, so maybe just remove it for now.

2017-01-25 15:01 UTC, MikeMcQuaid requested changes

2017-01-25 15:01 UTC, MikeMcQuaid commented on Formula/wine.rb
> +  end
If these patches aren't getting merged upstream we should strongly consider removing them. Any information on why upstream won't merge them?

2017-01-25 15:23 UTC, apetresc commented
@MikeMcQuaid [This comment](https://bugs.winehq.org/show_bug.cgi?id=34166#c4) explains it in some detail. Basically, they consider it a bug in Apple's OpenGL implementation, so they view hacking around it in Wine itself as some sort of moral compromise they're not willing to make, even though it does resolve the issue.

2017-01-26 12:52 UTC, MikeMcQuaid commented
@apetresc We need to get some resolution here, we can't just carry these unmerged patches forever. I've commented in https://bugs.winehq.org/show_bug.cgi?id=14939 and https://bugs.winehq.org/show_bug.cgi?id=34166 and let's hold off on this merge until there's more news.

2017-02-01 17:09 UTC, xrisk commented
Hi, any updates on this? Wine 2.0 patch is kinda important...

2017-02-01 17:14 UTC, apetresc commented
@xrisk: It looks like Mike is still going back-and-forth with the Wine developers in those two tickets, with responses as recently as this morning. So, it's still being figured out. As expected, they're resisting merging the patches upstream (for some seemingly good reasons, too).

2017-02-08 18:56 UTC, MikeMcQuaid approved these changes

2017-02-08 18:59 UTC, MikeMcQuaid commented
@uyjulian Can you rebase this on `master`? Thanks!

2017-02-09 08:07 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew (and patience)! Without people like you submitting PRs we couldn't run this project. You rock!

2017-02-09 08:08 UTC, closed without merging

2017-02-11 00:35 UTC, alexchandel commented
Just a heads up, it looks like there are newer versions of both patches than the ones we currently apply.

Also, the patch for https://bugs.winehq.org/show_bug.cgi?id=14939 was purportedly committed, so we may need to stop applying it to `HEAD` and `devel` builds soon.