grumpy --HEAD (new formula)
Homebrew/homebrew-core pull request #9299
Opened 2017-01-26 19:31 UTC by cclauss

Google Grumpy is a Python to Go source code transcompiler and runtime.

This should fix https://github.com/Homebrew/homebrew-core/issues/9213

The export of the correct GOPATH and PYTHONPATH are essential to the proper function of these tools.

`Audit --strict` seems to want me to learn the Ruby programming language in order to work with Go and Python.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-26 19:56 UTC, cblecker requested changes
The reason `brew audit --strict` is suggesting Ruby changes to you is because Homebrew Formulas are written in Ruby. I've suggested some changes to conform with conventions.

Documentation around writing Formulas is available:
http://www.rubydoc.info/github/Homebrew/brew/master/Formula
https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

2017-01-26 19:56 UTC, cblecker commented on Formula/grumpy.rb
> +    system "echo", "export PYTHONPATH=#{prefix}/Library/Python/2.7/site-packages"
All these `system "echo"` commands should be listed as caveats: http://www.rubydoc.info/github/Homebrew/brew/master/Formula#caveats-instance_method

2017-01-26 19:56 UTC, cblecker commented on Formula/grumpy.rb
> +    system "cp", "#{prefix}/usr/bin/grumprun", "#{bin}"
These copies can be changed to `bin.install`
http://www.rubydoc.info/github/Homebrew/brew/master/Formula:bin

2017-01-26 19:56 UTC, cblecker commented on Formula/grumpy.rb
> +  depends_on "go" => :build
Is go a build-only dependency, or do you actually need go installed to run the application too?

2017-01-26 19:56 UTC, cblecker commented on Formula/grumpy.rb
> +    system "PYTHONPATH=#{prefix}/Library/Python/2.7/site-packages"
These environment variables can be set with the ENV ruby function:
`ENV["GOPATH"] = #{prefix}/usr/lib/go`

2017-01-26 23:21 UTC, cblecker commented on Formula/grumpy.rb
> +    ENV["PYTHONPATH"] = #{prefix}/Library/Python/2.7/site-packages
Sorry, I did mention this the first time, but the right side of these lines need to be quoted:
```
    ENV["GOPATH"] = "#{prefix}/usr/lib/go"
    ENV["PYTHONPATH"] = "#{prefix}/Library/Python/2.7/site-packages"
```

2017-01-26 23:33 UTC, cclauss commented on Formula/grumpy.rb
> +    ENV["PYTHONPATH"] = #{prefix}/Library/Python/2.7/site-packages
I was wondering about that but the test did not fail when they were not quoted...  Changing now.

2017-01-27 02:04 UTC, ilovezfs commented
We don't accept head-only formulae so this will need to be based on a specific version designated as stable by upstream to be considered for inclusion.

2017-02-08 19:21 UTC, dunn commented
Happy to revisit this when there's a stable release.

2017-02-08 19:21 UTC, closed without merging