chakra 1.4.0 (new formula)
Homebrew/homebrew-core pull request #9323
Opened 2017-01-27 09:01 UTC by mathiasbynens

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is a WIP formula for [Chakra (ChakraCore)](https://github.com/Microsoft/ChakraCore). I think it’s close to being finished, however, I need some help with this issue: https://github.com/Microsoft/ChakraCore/issues/2417 Long story short, the build command succeeds in my regular environment, but fails at the linking step when run inside of Homebrew’s sandbox. Any idea why?

Ref. https://github.com/Microsoft/ChakraCore/issues/2278

2017-01-27 13:25 UTC, mathiasbynens commented
@obastemur [mentioned](https://github.com/Microsoft/ChakraCore/issues/2417#issuecomment-275652850) the issue could be this:

> IIRC Homebrew pushes for recent libc++ for osx 10.9+..
> 
> While installing with homebrew, you should use `--env=std` argument with brew install ... command. The rest should be just fine.

In that case, how can I force Homebrew to default to old libc++ for this formula, i.e. act as if `--env=std` was always supplied?

2017-01-27 14:12 UTC, MikeMcQuaid commented on Formula/chakra.rb
> +    prefix.install "BuildLinux/Release/ch" => "chakra"
Why `BuildLinux`?

2017-01-27 14:19 UTC, ilovezfs commented on Formula/chakra.rb
> +    prefix.install "BuildLinux/Release/ch" => "chakra"
It's hard coded: https://ci.dot.net/job/Microsoft_ChakraCore/job/master/job/osx_osx_release_static/lastBuild/console

2017-01-27 14:23 UTC, ilovezfs commented
The problem is not the c++ library, it's the optimization. Adding `ENV.O3` to the install method should fix it for you.

2017-01-27 14:25 UTC, MikeMcQuaid commented on Formula/chakra.rb
> +    prefix.install "BuildLinux/Release/ch" => "chakra"
Gentle nudge that upstream might want to consider renaming at some point 😉

2017-01-27 14:25 UTC, MikeMcQuaid commented on Formula/chakra.rb
> +      icu = "--icu=#{icu4c.opt_include}"
I'd populate an `args` array here instead as that's more typical formula form and inline `icu4c` as you're only using that variable once

2017-01-27 14:26 UTC, ilovezfs commented
This has a case insensitive file system bug, which can be fixed with
```
inreplace "pal/src/locale/unicode.cpp", "corefoundation", "CoreFoundation"
```

2017-01-27 14:28 UTC, ilovezfs commented on Formula/chakra.rb
> +    system "./build.sh", "--static", "--test-build", icu
should be a release build, not a test build

2017-01-27 14:33 UTC, ilovezfs commented on Formula/chakra.rb
> +    prefix.install "BuildLinux/Release/ch" => "chakra"
This should be `bin.install` not `prefix.install`

2017-01-27 15:08 UTC, ilovezfs commented
I suggest the following:

```
class Chakra < Formula
  desc "The core part of the Chakra Javascript engine that powers Microsoft Edge"
  homepage "https://github.com/Microsoft/ChakraCore"
  url "https://github.com/Microsoft/ChakraCore/archive/v1.4.0.tar.gz"
  sha256 "f6b4a3bce9e69bb3ea619a82805460906ef53d4f9da98b51e554dd48d6cdfdb3"

  depends_on "cmake" => :build
  depends_on "icu4c" => :optional

  def install
    ENV.O3

    # Fix build failure on case-sensitive file systems
    inreplace "pal/src/locale/unicode.cpp", "corefoundation", "CoreFoundation"

    args = ["--static"]
    if build.with? "icu4c"
      args << "--icu=#{Formula["icu4c"].opt_include}"
    else
      args << "--no-icu"
    end
    system "./build.sh", *args

    bin.install "BuildLinux/Release/ch" => "chakra"
  end

  test do
    (testpath/"test.js").write("print('Hello world!');\n")
    assert_equal "Hello world!", shell_output("#{bin}/chakra test.js").chomp
  end
end
```

2017-01-27 15:15 UTC, mathiasbynens commented on Formula/chakra.rb
> +      icu = "--icu=#{icu4c.opt_include}"
What would inlining look like exactly? Would `"--icu=#{Formula['icu4c'].opt_include}"` work? (I’m not a Ruby programmer 😊)

2017-01-27 15:16 UTC, mathiasbynens commented on Formula/chakra.rb
> +    system "./build.sh", "--static", "--test-build", icu
The test build enables command-line flags so most of the time people will want a test build. I’ll make this an option then

2017-01-27 15:17 UTC, mathiasbynens commented on Formula/chakra.rb
> +      icu = "--icu=#{icu4c.opt_include}"
Ah never mind, @ilovezfs already shows this below:

```
"--icu=#{Formula["icu4c"].opt_include}"
```

2017-01-27 15:20 UTC, obastemur commented on Formula/chakra.rb
> +    prefix.install "BuildLinux/Release/ch" => "chakra"
``--target`` argument is added to set custom path and will be part of release 2.0. We also don't like `BuildLinux` naming. I have to admit, we've been lazy on changing it..

BTW; `BuildLinux/Release/ch` is a wrong path for `test-build`. It should be `BuildLinux/Test/ch`

2017-01-27 15:29 UTC, mathiasbynens commented
Thanks for the helpful reviews, @ilovezfs and @MikeMcQuaid! ♥ I’ve updated the PR.

2017-01-27 15:32 UTC, ilovezfs commented
@MikeMcQuaid are we permitting the use of libstdc++ in new formulae these days?

2017-01-27 17:21 UTC, MikeMcQuaid commented
@ilovezfs not intentionally but in this case we probably wouldn't have noticed and there's no obvious hacks happening. 
@mathiasbynens Why is `libc++` not supported, any ideas?

2017-01-27 18:57 UTC, mathiasbynens commented
> @mathiasbynens Why is `libc++` not supported, any ideas?

I have no idea — maybe @obastemur does? (Note: I am not affiliated with Microsoft or the ChakraCore team.)

2017-01-28 13:52 UTC, obastemur commented
> @mathiasbynens Why is libc++ not supported, any ideas?

https://github.com/Microsoft/ChakraCore/issues/2417#issuecomment-275849276

2017-01-29 16:42 UTC, MikeMcQuaid commented
Will wait until @ilovezfs's conversation there has concluded and leave it up to him whether we merge this given the stdlib situation.

2017-01-30 14:20 UTC, ilovezfs commented
-Os issue is fixed. You can drop the ENV.O3, by adding this patch from upstream:

```
  patch do
    url "https://github.com/obastemur/ChakraCore/commit/54874cfbe139daad5ae821c5e2710b6764632bd4.patch"
    sha256 "8f08b9708e43b9f3324187573455f3a1c01fe6861e39f7f909a60aced314c0ae"
  end
```

However, the deployment target/mmacosx-version-min and C++ issues remain unresolved: https://github.com/Microsoft/ChakraCore/issues/2417#issuecomment-276072593

2017-01-30 14:30 UTC, mathiasbynens commented
Patch updated!

2017-01-31 08:37 UTC, mathiasbynens commented
The build now fails on Yosemite:

```
[100%] Linking CXX executable ch
Undefined symbols for architecture x86_64:
  "Js::JavascriptString::ConcatDestructive(Js::JavascriptString*)", referenced from:
      Js::JavascriptMath::AddLeftDead(void*, void*, Js::ScriptContext*, Js::JavascriptNumber*) in libChakra.Jsrt.a(JavascriptMathOperators.cpp.o)
      Js::JavascriptMath::Add_FullHelper(void*, void*, Js::ScriptContext*, Js::JavascriptNumber*, bool) in libChakra.Jsrt.a(JavascriptMathOperators.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/ch/ch] Error 1
make[1]: *** [bin/ch/CMakeFiles/ch.dir/all] Error 2
make: *** [all] Error 2
See error details above. Exit code was 2
```

cc @obastemur

2017-01-31 13:01 UTC, obastemur commented
@mathiasbynens it works on master.

we will have our first official cross-platform release soon, we may target that instead of 1.4.0? In the meantime, I will make sure we have this scenario covered in our CI. So, we wouldn't break it going forward.

2017-01-31 13:08 UTC, mathiasbynens commented
Can’t wait for that release!

2017-02-01 15:23 UTC, MikeMcQuaid requested changes

2017-02-01 15:23 UTC, MikeMcQuaid commented on Formula/chakra.rb
> +    # Fixed in master https://github.com/obastemur/ChakraCore/commit/cda81f4
Can we backport this commit as a patch so it gets removed on the next release?

2017-02-01 15:23 UTC, MikeMcQuaid commented on Formula/chakra.rb
> +    inreplace "pal/src/locale/unicode.cpp", "corefoundation", "CoreFoundation"
Similarly here.

2017-02-01 16:03 UTC, ilovezfs commented on Formula/chakra.rb
> +    # Fixed in master https://github.com/obastemur/ChakraCore/commit/cda81f4
Nope. It causes the build to fail on Yosemite.

2017-02-01 16:04 UTC, ilovezfs commented on Formula/chakra.rb
> +    inreplace "pal/src/locale/unicode.cpp", "corefoundation", "CoreFoundation"
Yes, this one could be applied as a patch.

2017-02-03 15:11 UTC, MikeMcQuaid approved these changes

2017-02-03 15:14 UTC, closed without merging

2017-02-03 15:15 UTC, ilovezfs commented
@mathiasbynens Thanks for the new formula! :new:

2017-02-03 16:40 UTC, mathiasbynens commented
Thanks for the help! 👍