lua@5.3: import from homebrew/versions.
Homebrew/homebrew-core pull request #9381
Opened 2017-01-28 15:58 UTC by lembacon

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-29 16:44 UTC, MikeMcQuaid requested changes

2017-01-29 16:44 UTC, MikeMcQuaid commented on Formula/lua@5.3.rb
> +  option "with-default-names", "Don't version-suffix the Lua installation. Conflicts with Homebrew's Lua"
Let's remove this option, thanks.

2017-01-29 16:44 UTC, MikeMcQuaid commented on Formula/lua@5.3.rb
> +  patch :DATA
Reckon there's any way we can use `inreplace` or otherwise avoid this patch?

2017-01-29 16:44 UTC, MikeMcQuaid commented
@lembacon Nice work! Would also be great to rename `lua51` accordingly, too, and make a PR in homebrew/versions to migrate this formula there too.

2017-01-29 17:25 UTC, lembacon commented on Formula/lua@5.3.rb
> +  patch :DATA
@MikeMcQuaid This patch hack can be found in formulae for lua 5.1, 5.2 & 5.3. Perhaps let's just leave this for a future pull request?

2017-01-29 17:30 UTC, lembacon commented
@MikeMcQuaid 

- `--with-default-names` has been removed from `lua@5.3`.
- `lua51` has been renamed to `lua@5.1`, `--universal` has been removed and some minor cleanups have been applied in order to match `lua@5.3`.
- A pull request Homebrew/homebrew-versions#1515 has been submitted to migrate `lua53`.

2017-01-29 17:55 UTC, lembacon commented
- `--universal` has been removed from `lua`.
- Formulae that depend on `lua51` have been updated to depend on `lua@5.1` with revision bumps.

2017-01-29 21:26 UTC, DomT4 commented
FWIW, I'd done most of this locally already, but the new `luarocks` update which needs to be applied seems to have "issues" with accepting suffixed `lua` executables. But at some point that will need doing. Not a blocker here, just an FYI.

2017-01-29 21:28 UTC, DomT4 commented on Formula/radare2.rb
> +    revision 1
This is in the wrong place. Applies to the whole formula, so needs to live outside any `stable`, etc block.

2017-01-30 00:46 UTC, lembacon commented
The misplaced `revision` in `radare2.rb` has been fixed. 🙈

2017-01-30 09:48 UTC, MikeMcQuaid commented on Formula/lua@5.3.rb
> +  patch :DATA
Sure thing. If you're ever able to look at that it'd be ❤️

2017-01-30 10:25 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-01-30 10:25 UTC, MikeMcQuaid approved these changes

2017-01-30 10:25 UTC, closed without merging