Pipenv 3.2.10 (new formula)
Homebrew/homebrew-core pull request #9431
Opened 2017-01-30 04:36 UTC by iraquitan

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Add new homebrew formula for the pipenv project by @kennethreitz

2017-01-30 09:03 UTC, MikeMcQuaid requested changes

2017-01-30 09:03 UTC, MikeMcQuaid commented on Formula/pipenv.rb
> +  depends_on :python if MacOS.version <= :lion
Why `:lion`?

2017-01-30 09:03 UTC, MikeMcQuaid commented on Formula/pipenv.rb
> +  desc "Sacred Marriage of Pipfile, Pip, & Virtualenv by @kennethreitz"
Don't need `kennethreitz` in here. A better description would be good, not clear what this means.

2017-01-30 09:03 UTC, MikeMcQuaid commented on Formula/pipenv.rb
> +  include Language::Python::Virtualenv
Newline after this.

2017-01-30 09:03 UTC, MikeMcQuaid commented on Formula/pipenv.rb
> +  end
Can remove these as they aren't Homebrew specific.

2017-01-30 09:03 UTC, MikeMcQuaid commented on Formula/pipenv.rb
> +    assert_match "Commands", shell_output("#{bin}/pipenv --help")
Can remove this check.

2017-01-30 09:03 UTC, MikeMcQuaid commented on Formula/pipenv.rb
> +    # Create a new project using Python 3
Can remove all these comments. They are self-explanatory from the code.

2017-01-30 09:03 UTC, MikeMcQuaid commented on Formula/pipenv.rb
> +    assert_equal "1\n", shell_output("cat Pipfile | grep -ci requests")
Use `assert_match` rather than `| grep`

2017-01-30 09:03 UTC, MikeMcQuaid commented on Formula/pipenv.rb
> +    assert_equal "1\n", shell_output("ls | grep -ci Pipfile.lock")
Use `File.exist?` rather than `ls | grep`

2017-01-30 09:03 UTC, MikeMcQuaid commented
Test is failing: https://bot.brew.sh/job/Homebrew%20Core/15574/version=sierra/testReport/junit/brew-test-bot/sierra/test_pipenv/

Happy to wave the newness audit on this.

2017-01-31 12:40 UTC, robsonpeixoto commented on Formula/pipenv.rb
> +  url "https://github.com/kennethreitz/pipenv/archive/v3.2.10.tar.gz"
Please, upgrade to 3.2.11. `sha256 "4dc7dcea983f0ecd8f3ca16e9249280271558bdffd0cc1bdca3bdf322f365d4e"`

2017-02-01 06:53 UTC, iraquitan commented
@MikeMcQuaid Any help on why it is failing on testbot ?

2017-02-01 08:34 UTC, tdsmith commented
Does it work for you locally? We're nesting virtualenvs here; I don't know how graceful that is.

2017-02-01 08:38 UTC, tdsmith commented on Formula/pipenv.rb
> +  desc "Experimental virtualenv, and package manager for Python"
I'm still not sure what this means.

2017-02-01 08:38 UTC, tdsmith commented on Formula/pipenv.rb
> +  end
I'd get rid of this caveat as well.

2017-02-01 08:38 UTC, tdsmith commented on Formula/pipenv.rb
> +      system "_PIPENV_COMPLETE=source-zsh #{bin}/pipenv > completions/_pipenv"
`bin` can have spaces in it; these should probably be quoted (or, better, don't invoke a shell for this).

2017-02-01 19:37 UTC, iraquitan commented on Formula/pipenv.rb
> +  desc "Experimental virtualenv, and package manager for Python"
I'll describe better

2017-02-01 20:07 UTC, iraquitan commented
@tdsmith Yes, it works locally. I performed the steps in testbot and worked. I'll try the new release that uses pew to manage virtualenvs.

2017-02-01 20:21 UTC, tdsmith commented
Just checking -- when I say "locally" I mean running `brew test pipenv`. I can help troubleshoot later today if this is still snagging.

2017-03-16 23:53 UTC, nikolay commented
Any luck?

2017-04-11 22:21 UTC, bfontaine commented
Ping?

2017-04-30 20:14 UTC, JCount commented
Closing per inactivity. Thank you for your work nonetheless @iraquitan. If you end up deciding to work on this again, feel free to open a new PR.

2017-04-30 20:14 UTC, closed without merging

2017-07-12 17:02 UTC, tilgovi commented
If I picked this up, would that be welcome?

2017-07-13 20:18 UTC, MikeMcQuaid commented
@tilgovi If it would be useful to you: yes, definitely, thanks!