updated bit version
Homebrew/homebrew-core pull request #9449
Opened 2017-01-30 16:26 UTC by amitgilad3

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-01-30 17:44 UTC, woodruffw commented on Formula/bit.rb
> +  url "http://104.154.76.155:8081/artifactory/bit-brew/stable/bit/0.1.7/bit-0.1.7-brew.tar.gz"
This probably isn't an acceptable URL. Is there an official release on the project's domain (i.e., `bitsrc.io`)?

2017-01-30 17:45 UTC, woodruffw commented on Formula/bit.rb
> -  bottle do
You don't need to remove this; `test-bot` will automatically rewrite these lines.

2017-01-31 09:13 UTC, nijikon requested changes

2017-01-31 09:13 UTC, nijikon commented on Formula/bit.rb
> +  url "http://104.154.76.155:8081/artifactory/bit-brew/stable/bit/0.1.7/bit-0.1.7-brew.tar.gz"
Yup, this will not do, sorry.

2017-01-31 19:24 UTC, amitgilad3 commented on Formula/bit.rb
> +  url "http://104.154.76.155:8081/artifactory/bit-brew/stable/bit/0.1.7/bit-0.1.7-brew.tar.gz"
sorry , will fix and push new file

2017-01-31 19:24 UTC, closed without merging