jing-trang V20151127 (new formula)
Homebrew/homebrew-core pull request #9454
Opened 2017-01-30 17:10 UTC by gambl

The new formula is a replacement for two formula that had recently
gone stale, jing and trang - and now live in the boneyard. 
The jing-trang library provides Relax-NG schema validation and translation support.
PRs #4799 and #5382 detail how the previous formulas
had been migrated to the boneyard. The project had previously been
hosted on googlecode as two separate downloads. The project then
moved to github but with issues building the latest tagged release.
A newer release has been tagged that successfully builds. The reason
for combining into one Formula is that the library and its jars are
now distributed together via the single github repo.

- [y] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [y] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [y] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [y] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-01 15:04 UTC, MikeMcQuaid requested changes

2017-02-01 15:04 UTC, MikeMcQuaid commented on Formula/jing-trang.rb
> +    namespace core = "http://www.bbc.co.uk/ontologies/coreconcepts/"
Indent this by two characters more.

2017-02-01 15:04 UTC, MikeMcQuaid commented on Formula/jing-trang.rb
> +    <?xml version="1.0" encoding="UTF-8"?>
Indent this by two characters more.

2017-02-01 15:04 UTC, MikeMcQuaid commented on Formula/jing-trang.rb
> +<response xmlns:core="http://www.bbc.co.uk/ontologies/coreconcepts/">
Indent this by two characters more than the previous line.

2017-02-01 15:04 UTC, MikeMcQuaid commented on Formula/jing-trang.rb
> +    system bin/"trang", "-I", "rnc", "-O", "rng", "test.rnc", "test.rng"
Does this produce any output or anything? Is failure indicated by exit code? Thanks!

2017-02-01 17:09 UTC, gambl commented on Formula/jing-trang.rb
> +    system bin/"trang", "-I", "rnc", "-O", "rng", "test.rnc", "test.rng"
Hi - there shouldn't be any output to stdout on success. You're correct that a failure is indicated by a non-zero exitcode. I could test the expected output in the test.rng file - which is a conversion of a schema from one format to another. However I assumed the goal of the test was to assert whether the installation was successful, as apposed to the actual functionality of the tool. If that is the case then I think simply asserting that there is a non-zero exit code should be sufficient.

2017-02-10 17:14 UTC, MikeMcQuaid commented on Formula/jing-trang.rb
> +    system bin/"trang", "-I", "rnc", "-O", "rng", "test.rnc", "test.rng"
Cool, that's fine 👍

2017-02-12 15:48 UTC, dunn commented
Ping on Mike's other comments.

2017-02-13 09:40 UTC, gambl reviewed
These changes are fine. I can't approve these changes however - do you want me to re-submit the pull request?

2017-02-13 16:53 UTC, dunn commented
Just add the changes an another commit, or amend and force-push.

2017-03-25 14:39 UTC, fxcoudert commented
Given lack of response, closing this pull request for now. Please reopen once the requested changes have been made.

2017-03-25 14:39 UTC, closed without merging