grafana-agent 0.23.0
Homebrew/homebrew-core pull request #94880
Opened 2022-02-10 17:12 UTC by rlankfo

Created with `brew bump-formula-pr`.

2022-02-10 18:33 UTC, iMichka requested changes
One comment, the 3 top lines need to be removed, and this should be good to go.

2022-02-10 21:41 UTC, rlankfo commented on Formula/grafana-agent.rb
> +
```suggestion
```

2022-02-10 22:28 UTC, iMichka approved these changes

2022-02-10 23:08 UTC, closed without merging

2022-02-12 09:09 UTC, terorie commented
Hey, sorry if this is off-topic here but I'd like to say thank you to you all @smillerdev @iMichka for delivering a tireless maintenance effort completely for free and making Homebrew the open-source behemoth that it is. Your work empowers millions of developers worldwide, it doesn't get enough praise. 🚀