i386-elf-gdb 11.2
Homebrew/homebrew-core pull request #95162
Opened 2022-02-15 14:06 UTC by Porkepix

Created with `brew bump-formula-pr`.

2022-02-15 22:23 UTC, iMichka requested changes
@Porkepix can you please remove the patch? Looks like it's not needed anymore.

2022-02-15 22:49 UTC, Porkepix commented
Done. I tried to read at the link, but couldn't figure out from the interface if the patch ended up in the codebase or not…

2022-02-17 08:30 UTC, SMillerDev approved these changes, later dismissed

2022-02-17 16:14 UTC, iMichka submitted a review, later dismissed

2022-02-17 16:15 UTC, iMichka commented
Once this is merged, can some handle the comment in that formula?
`# Please add to synced_versions_formulae.json once version synced with gdb`

I think this is the case now and we can remove the comment + update synced_versions_formulae

2022-02-19 01:26 UTC, cho-m approved these changes

2022-02-19 01:29 UTC, closed without merging