vttest 20220215
Homebrew/homebrew-core pull request #95243
Opened 2022-02-16 15:52 UTC by Porkepix

Created with `brew bump-formula-pr`.

2022-02-16 19:05 UTC, chenrui333 commented
flaky run on linux, give another shot

2022-02-17 08:32 UTC, SMillerDev commented
I guess the connections need to be done with Homebrew curl since all are failing on Linux

2022-02-17 23:09 UTC, issyl0 requested changes

2022-02-17 23:09 UTC, issyl0 commented on Formula/vttest.rb
> +  url "https://invisible-mirror.net/archives/vttest/vttest-20220215.tgz"
```suggestion
  url "https://invisible-mirror.net/archives/vttest/vttest-20220215.tgz", using: :homebrew_curl
```

2022-02-17 23:34 UTC, issyl0 approved these changes
Thanks @Porkepix and @SMillerDev!

2022-02-18 00:14 UTC, closed without merging