ivykis 0.41 (new formula)
Homebrew/homebrew-core pull request #9530
Opened 2017-02-01 14:37 UTC by MrAnno

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-01 21:21 UTC, woodruffw requested changes

2017-02-01 21:21 UTC, woodruffw commented on Formula/ivykis.rb
> +  url "https://github.com/buytenh/ivykis/archive/v0.41.tar.gz"
Let's fetch it from here instead: https://sourceforge.net/projects/libivykis/files/0.41/

2017-02-01 21:21 UTC, woodruffw commented on Formula/ivykis.rb
> +  homepage "http://libivykis.sourceforge.net"
That page leads to this, which looks like the real homepage: https://sourceforge.net/projects/libivykis/

2017-02-01 21:22 UTC, woodruffw commented
Debian et al. provide this, so I think we can ignore the notability warning here. It'll also disappear once the `url` link is moved to sourceforge.

2017-02-01 22:01 UTC, MrAnno commented
Thanks for the review.

I've updated the PR based on your notes. I had some issues with the sha256 sum because of the SourceForge mirrors, that was the reason I switched to the GitHub URL.

2017-02-01 22:07 UTC, woodruffw commented
No problem!

> I had some issues with the sha256 sum because of the SourceForge mirrors, that was the reason I switched to the GitHub URL.

Could you elaborate? Was the `sha256` varying across mirrors?

2017-02-01 22:40 UTC, MrAnno commented
> Could you elaborate? Was the sha256 varying across mirrors?

Sorry, I was wrong. All the available SourceForge mirrors have the same checksum, I just mixed up the GitHub and the SourceForge tarball, so I entered a wrong sha256 value.

2017-02-02 06:10 UTC, woodruffw approved these changes

2017-02-05 17:58 UTC, woodruffw commented
Thanks @MrAnno, and congratulations on your first contribution/formula! :tada:

2017-02-05 17:58 UTC, closed without merging