workflows/tests: always test dependents unless requested otherwise
Homebrew/homebrew-core pull request #95440
Opened 2022-02-19 13:08 UTC by carlocab

Skipping testing dependents makes it that much harder to identify
formulae that need revision bumps.

See, for example, #91224, where the need to rebuild `gnuradio` could've
been identified days, if not weeks, earlier if we did not skip dependent
tests when one of the tested formulae fails.

Note that this will still skip the testing of dependents of failed
formulae, because these are passed in the `--skipped-or-failed-formulae`
flag.

Related discussion: #82220

2022-02-19 13:15 UTC, carlocab commented
Actually, `gnuradio` was rev bumped in an earlier version of https://github.com/Homebrew/homebrew-core/pull/91224. The rev bump was just misplaced during a rebase.

2022-02-21 09:02 UTC, MikeMcQuaid commented
Sorry, I'd like to push back on this as I don't agree. I really don't think it's worth us testing dependents when the original build is failing. Yes, this may have sped up the merge of that PR but it will cause our entire CI pipeline to be slowed down when we repeatedly test dependents when there are failures meaning we're not going to merge the PR.

The actual thing that needs fixed here, in my opinion, is making it easier to rerun builds when we're just revision-bumping dependents by doing some caching.

Alternatively, I think we could differentiate failures of formulae that are only being revision bumped vs. those that have meaningful (e.g. version) changes.

2022-02-21 09:13 UTC, MikeMcQuaid requested changes
Giving a 👎🏻 for now so GitHub doesn't nag me for review.

2022-02-21 09:17 UTC, carlocab commented
Perhaps I wasn't being clear: my main motivation here is not at all speeding up merges, but almost entirely motivated by avoiding delays to our entire CI pipeline. I think skipping the testing of dependents is a much bigger cause of slowdown here.

2022-02-21 12:15 UTC, MikeMcQuaid commented
> Always testing dependents means spotting failures that need to be fixed earlier, and spotting failures that need to be fixed earlier means fewer re-runs of CI.

Fewer reruns but each rerun will take longer, right?

---

In this case: what was failing in the original PR which caused the dependents to be skipped?

2022-02-21 14:07 UTC, carlocab commented
> Fewer reruns but each rerun will take longer, right?

Yes, but even saving just a single formulae-only rerun (~17 hours) more than offsets the extra time taken by testing dependents (~3 hours) multiple times over.

This means that had the necessary rev bump for a failed dependent been identified at the same time as the fixes for the failed formulae, we'd save at least 14 hours of CI time for that PR. The real time saved is likely a multiple of that: the process of iterating over finding failed formulae, fixing them, then finding failed dependents and then fixing them too only to reveal new failed formulae occurred multiple times in that PR.

> In this case: what was failing in the original PR which caused the dependents to be skipped?

It varies. In the final run, it was a combination of a formula [missing an upstream patch](https://github.com/Homebrew/homebrew-core/pull/95358), another with a [dependency that needed a `conflicts_with`](https://github.com/Homebrew/homebrew-core/pull/95354), and another that just [needed a newer compiler](https://github.com/Homebrew/homebrew-core/pull/95378). In an earlier run, tests failed because a formula couldn't [download a vendored dependency](https://github.com/Homebrew/homebrew-core/pull/95248), and another because of [a poorly configured `install` target](https://github.com/Homebrew/homebrew-core/pull/95254).

2022-02-21 15:20 UTC, MikeMcQuaid commented
> > I still think we should be catching these issues before we test dependents and that this isn't the right fix, given that.
> 
> I'm not convinced. Why should the failure of `foo` have any bearing on whether the dependents of `bar` are tested? Waiting for `foo` to be fixed before we even test the dependents of `bar` wastes a lot of CI and maintainer time.

I don't agree it wastes CI time. 

In the case that `foo` and `bar` aren't dependencies of the other: they should probably be getting updated in separate PRs.

> If `boost` itself fails, then `boost`'s dependents will not be tested even if this PR is merged because `boost` will be in `@skipped_or_failed_formulae`. In fact, if `boost` fails, all other rev bumps will fail (modulo weird corner cases), which means none of their dependents will be tested too.

Sorry, I don't really think I understand the case here. Can you be more specific about the examples here? If you don't care about testing `boost`'s dependents or the `revision` bumps: what are you trying to test here?

In your defence: I think I may be missing something here.

2022-02-22 03:54 UTC, carlocab commented
> I don't agree it wastes CI time.

Could you elaborate on why you disagree?

> In the case that `foo` and `bar` aren't dependencies of the other: they should probably be getting updated in separate PRs.

It's not that simple. It can be the case that `foo` and `bar` are not dependencies of each other, but cannot be updated in separate PRs. This is the case, for example, when `foo` and `bar` share a common (possibly recursive) dependency (e.g. `boost`).

> Sorry, I don't really think I understand the case here. Can you be more specific about the examples here? If you don't care about testing `boost`'s dependents or the `revision` bumps: what are you trying to test here?

I don't quite follow what there is to be more specific about, sorry. I am primarily but not exclusively interested in testing `boost`'s dependents. But my point is that if `boost` doesn't build, or fails `brew linkage` or `brew test`, then unconditionally running the `--only-formulae-dependents` step in the workflow will not result in testing `boost`'s dependents, which is consistent with the original intent.

If we think that other failures (e.g. `audit` or `livecheck`) should also prevent dependent testing, then we can and should fix that in `test-bot` instead. However, I think we had previously been inclined to make some of those failures into warnings instead, so I suspect that is a direction we don't want to move in.

> In your defence: I think I may be missing something here.

I'm actually beginning to wonder if I'm missing something here. However, what I do know, or at least have good reason to believe, is that I spend much more time than anyone else monitoring (admittedly non-systematically -- it would be nice if we had tooling that does this better) the state of our CI queue. I'm also of the sincere belief that making this change to this workflow would improve CI throughput.

I would argue that this should be enough for us to consider at least trying this change out: if it proves to actually slow down CI, we can always revert it later. Given the work I've personally put into trying to improve CI congestion, I like to think I'll be the first one to do so if it's needed.

2022-02-22 07:56 UTC, SMillerDev approved these changes
Seeing how the hdf5 PR is now exposing new broken linkage with every CI run that this would likely to reveal in run 1, I'm in favor.

2022-02-22 08:44 UTC, MikeMcQuaid commented
> > I don't agree it wastes CI time.
> 
> Could you elaborate on why you disagree?

Well, neither of us are bringing concrete measurements to the discussion so, to me, the current behaviour avoids running unnecessary tests more than it skips necessary tests.

> I don't quite follow what there is to be more specific about, sorry. I am primarily but not exclusively interested in testing `boost`'s dependents. But my point is that if `boost` doesn't build, or fails `brew linkage` or `brew test`, then unconditionally running the `--only-formulae-dependents` step in the workflow will not result in testing `boost`'s dependents, which is consistent with the original intent.

I'm wondering: if the PR is about bumping `boost` and it's not testing `boost`'s dependents: what is it testing? Looking at the linked PR: it's testing the old version of `boost@1.76` and dependents, right? 

Is there a reason the `boost@1.76` extraction was not or could not have been pulled into another PR (either just the newly created formula and/or the `revision` bump of the formulae with changing dependencies)?

> If we think that other failures (e.g. `audit` or `livecheck`) should also prevent dependent testing, then we can and should fix that in `test-bot` instead. However, I think we had previously been inclined to make some of those failures into warnings instead, so I suspect that is a direction we don't want to move in.

Yes, I'm fine with these remaining as warnings, provided they are consistently being fixed before merge.

> I'm actually beginning to wonder if I'm missing something here. However, what I do know, or at least have good reason to believe, is that I spend much more time than anyone else monitoring (admittedly non-systematically -- it would be nice if we had tooling that does this better) the state of our CI queue. I'm also of the sincere belief that making this change to this workflow would improve CI throughput.

Given this, I'll ✅ it.

Similarly, I've probably spent more time than anyone else trying to improve our CI process overall and negotiate our consistently growing capacity requests with the companies that provide this to us.

We _have_ to continue moving towards making our CI builds as fail quicker when they can't be merged, investigating caching, parallelising our CI jobs and splitting huge PRs into multiple, smaller PRs. Otherwise as the project continually grows we're going to eventually hit limits that we cannot just beg or throw money at to get better.

Unfortunately, I personally see this PR as a step in the wrong direction, here, when I think there's (admittedly far more involved) changes in our process that could have avoided the issues mentioned above.

> I would argue that this should be enough for us to consider at least trying this change out: if it proves to actually slow down CI, we can always revert it later. Given the work I've personally put into trying to improve CI congestion, I like to think I'll be the first one to do so if it's needed.

Given we don't have measurements either way: I think it's basically impossible to prove anything.

2022-02-22 08:44 UTC, MikeMcQuaid approved these changes

2022-02-28 02:35 UTC, carlocab commented
Thanks, @MikeMcQuaid.

2022-02-28 02:35 UTC, merged