mediaconch-17.01.1 (Maintenance Release)
Homebrew/homebrew-core pull request #9581
Opened 2017-02-02 19:40 UTC by g-maxime

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-02 20:33 UTC, JCount requested changes

2017-02-02 20:33 UTC, JCount commented on Formula/mediaconch.rb
> +  sha256 "6decdd96e71800fe2a0c22971a57a9ac65df0267fe30e4fb497ae441657f8ead"
The `sha256` seems to be incorrect. The correct one seems to be `a935084cd3fcd066de23e33a88a33cf36f447c88335f7518854495f5b8651f75`

2017-02-02 21:54 UTC, g-maxime commented on Formula/mediaconch.rb
> +  sha256 "6decdd96e71800fe2a0c22971a57a9ac65df0267fe30e4fb497ae441657f8ead"
Thanks

2017-02-02 22:00 UTC, JCount commented on Formula/mediaconch.rb
> +  sha256 "6decdd96e71800fe2a0c22971a57a9ac65df0267fe30e4fb497ae441657f8ead"
No problem.

2017-02-02 23:56 UTC, JCount approved these changes

2017-02-03 00:03 UTC, closed without merging

2017-02-03 00:04 UTC, JCount commented
Thank you for your contribution, @g-maxime!