boost: Split boost-mpi into separate formula
Homebrew/homebrew-core pull request #9598
Opened 2017-02-03 11:34 UTC by mkuron

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This pull requests moves the building of Boost::MPI into a separate formula, _boost-mpi_. Previously, it was available as an option of the _boost_ formula, _boost --with-mpi_. Having it as a separate formula has two advantages: Boost will not need to be rebuilt in its entirety when Boost::MPI is installed, and Boost::MPI will be available as a bottle, thus speeding up installation. Furthermore, _boost-python_ has always been a separate formula.

2017-02-03 14:19 UTC, mkuron commented
The only test that failed on the test bot are related to the ncmpcpp, which I didn't touch. The test succeeds for me locally, and #8660 also mentions it failing on the bot, so it's probably fine.

2017-02-10 20:48 UTC, MikeMcQuaid requested changes

2017-02-10 20:48 UTC, MikeMcQuaid commented on Formula/boost-mpi.rb
> +  end
Remove this; bottles will be added when we pull.

2017-02-10 20:48 UTC, MikeMcQuaid commented
@ilovezfs Thoughts on this?

2017-02-11 10:14 UTC, ilovezfs commented
Is there a downside to just making it the default instead?

2017-02-11 10:19 UTC, mkuron commented
Making it the default would mean that boost depends on openmpi. Many people and a lot of C++ software use boost, but most of them don't need openmpi. Furthermore, openmpi depends on a Fortran compiler, which most people definitely don't need.

2017-02-11 10:50 UTC, ilovezfs commented
And won't this PR then mean that the boost bottle will have been built with clang but the boost-mpi bottle will have been built with gcc?

2017-02-11 12:57 UTC, mkuron commented
No, why should it? It is built in the same way as the boost-python bottle.

2017-02-11 12:57 UTC, ilovezfs commented
It needs gfortran6 from gcc no?

2017-02-11 12:59 UTC, mkuron commented
openmpi needs gfortran, but only to build its Fortran bindings. These are obviously not used by boost, which is C++.

2017-02-11 13:16 UTC, ilovezfs commented
Any reason for not providing the same options?
```
   option "without-single", "Disable building single-threading variant"
   option "without-static", "Disable building static library variant"
```

Also on any thoughts on whether the icu4c module could/should be similarly split out?

2017-02-11 13:21 UTC, mkuron commented
No reason for not providing these options. boost-python doesn't provide them either, but I can add them to both if you want that for consistency.

Regarding icu4c: that's not a separate boost module. It's only a different backend for Boost::Regex.

2017-02-11 13:26 UTC, ilovezfs commented
>No reason for not providing these options. boost-python doesn't provide them either, but I can add them to both if you want that for consistency.

Only asking because the analytics show some people combining the mpi option with --without-single. But it probably is fine to have all 4 since it shouldn't materially increase build-time for just one module.

>Regarding icu4c: that's not a separate boost module. It's only a different backend for Boost::Regex.

Ah OK. So then I revise my question:
Also any thoughts on whether the Boost::Regex module could/should be similarly split out?

2017-02-11 14:33 UTC, mkuron commented
> Only asking because the analytics show some people combining the mpi option with --without-single. But it probably is fine to have all 4 since it shouldn't materially increase build-time for just one module.

Exactly. While single vs. single+double doubles the build time, static vs static+dynamic only takes a few seconds extra because only linking happens twice. boost-mpi builds really quickly anyway, so doubling the compile time is no big deal. The complete boost, on the other hand, takes significant time to compile.

> Also any thoughts on whether the Boost::Regex module could/should be similarly split out?

Boost::Regex is built by default in the boost formula. We could create two formulae, boost-regex and boost-regex-icu4c, that declare conflicts on each other. However, many formulae have optional dependencies on icu4c and `--with-icu4c` options and none have separate formulae with and without icu4c. So until somebody comes up with a compelling reason to create separate boost-regex and boost-regex-icu4c formulae, I'd leave Boost::Regex in the main boost formula. The more sensible thing would probably be to make `--with-icu4c` the default -- but having never used Boost::Regex, that is not for me to decide. If somebody needs that change and can argue their case, they can submit another pull request.

2017-02-11 14:36 UTC, ilovezfs approved these changes

2017-02-12 15:11 UTC, MikeMcQuaid approved these changes

2017-02-12 15:28 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-02-12 15:29 UTC, closed without merging