Rename SpiderMonkey binary
Homebrew/homebrew-core pull request #9606
Opened 2017-02-03 17:04 UTC by mathiasbynens

Use `spidermonkey` instead of `js` which is overly generic and conflicts with Narwhal.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-04 10:03 UTC, mathiasbynens commented
This formula installs a heavily outdated version of SpiderMonkey, so I’m closing this in favor of #9607.

2017-02-12 15:14 UTC, dunn commented
Could you bump the `revision` as well? Thanks!

2017-02-12 23:11 UTC, dunn commented
Oops, and of course the test needs to be updated as well https://github.com/Homebrew/homebrew-core/pull/9606/files#diff-ebc76220009094fc28e2d1b512d549d1R50

2017-02-13 16:54 UTC, dunn commented on Formula/spidermonkey.rb
> +      bin.install "shell/spidermonkey" => "spidermonkey"
```
Error: No such file or directory - shell/spidermonkey
```
Please test changes locally first.

2017-02-26 20:28 UTC, fxcoudert requested changes

2017-02-26 20:28 UTC, fxcoudert commented on Formula/spidermonkey.rb
We might want to add a caveat to tell users how the binary is named.

2017-02-26 20:28 UTC, fxcoudert commented on Formula/spidermonkey.rb
> -  conflicts_with "narwhal", :because => "both install a js binary"
This needs a commit to `narwhal.rb` to remove `spider monkey` as a conflict.

2017-03-23 13:22 UTC, fxcoudert commented
Closing for now, please reopen once updated.

2017-03-23 13:22 UTC, closed without merging