libxml2: fix #9661 - update Debian patch link to new version
Homebrew/homebrew-core pull request #9663
Opened 2017-02-05 11:56 UTC by dusek

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

`brew audit --strict libxml2` does not pass due to code that is not by me - it says:

```
libxml2:
  * macOS has been 64-bit only since 10.6 so universal options are deprecated.
```

I did not update anything related to whether the formula is available on 32-bit or 64-bit platform, that code has been there already before this PR.

2017-02-05 15:18 UTC, ilovezfs requested changes
Please also add the new patch, which is the reason there is a new tarball.

2017-02-05 17:34 UTC, follower commented
FYI the new patch is named `patches/0008-Fix-attribute-decoding-during-XML-schema-validation.patch` and the content appears to be identical to the patch included from <https://bugzilla.gnome.org/show_bug.cgi?id=766834>.

This means that with the `0008` patch added the formula will fail to apply the patch from Gnome.

I assume the solution is to remove the application of the Gnome patch in addition to adding the `0008` patch.

2017-02-05 17:35 UTC, ilovezfs commented
indeed

2017-02-05 17:36 UTC, dusek commented
I am having look at this right now, should post updated PR in a few moments...

2017-02-05 17:37 UTC, ilovezfs commented
thanks @dusek

2017-02-05 17:42 UTC, follower commented
Spoiler alert: It appears to build happily with that change. 

But since you're updating the PR I won't provide an alternate. :)

2017-02-05 17:54 UTC, dusek commented
Just pushed the updated version, after rebasing on latest master, and after doing a build and the tests and `audit` again.

Thanks @follower for the info about the patch.

I verified that the patch from Gnome and Debian are identical in the content (only slight differences in patch metadata, but these do not matter anyway).

Pushed the new change in a new, second commit as that is what I think is logical, but can squash them into a single commit if requested.

2017-02-06 11:44 UTC, nijikon commented
You are awesome, thanks for your contribution! :tada:

2017-02-06 11:45 UTC, ilovezfs approved these changes

2017-02-06 11:45 UTC, closed without merging