mingw-w64 5.0.1 (new formula)
Homebrew/homebrew-core pull request #9726
Opened 2017-02-07 12:40 UTC by fxcoudert

This is intended to be a clean PR for mingw-w64 integration into homebrew-core. I have incorporated and fixed all comments (hopefully) from the previous PR at https://github.com/Homebrew/homebrew-core/pull/9037

The layout chosen, following discussion in the previous PR, is the following:

- Inside `/usr/local/Cellar/mingw-w64/5.0.1`, we have two directories with 32- and 64-bit toolchains, named `toolchain-i686` and `toolchain-x86_64` respectively. Inside these directories, the layout is completely standard (for cross-compilers).
- In `/usr/local/Cellar/mingw-w64/5.0.1/bin`, we symlink all binutils and cross-compiler binaries, with their standard cross-compiler names, such as `x86_64-w64-mingw32-g++`, `i686-w64-mingw32-as`, etc. They get symlinked into `/usr/local/bin` as usual.
- All headers and libraries remain hidden inside our toolchains directories, so they don't conflict with native compiler files in `/usr/local/lib` and `/usr/local/include`.
-  The cross-compilers have no trouble finding their libraries (`libgcc_s.a` among others) because I removed `--enable-version-specific-runtime-libs`: since we have everything neatly in place in separate directories, no need for that option (which is apparently not that well suited for cross-compilers).
- The multilib option is commented out, but all the necessary parts are in place. I will file a GCC bug about it when I figure out exactly why it fails.
- I have tried to streamline/simplify the formula as much as possible.

I welcome all comments and reviews, and hope we can work to get this merged!

-----

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

2017-02-11 16:46 UTC, fxcoudert commented
@MikeMcQuaid you had reviewed the previous PR, can you comment/review/approve?

2017-02-11 17:42 UTC, MikeMcQuaid requested changes

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +      # Build binutils
Can drop this comment.

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +    bin.mkdir
What needs this?

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +      installdir = "#{prefix}/toolchain-#{arch}"
`toolchain_arch_dir` or similar would be ideal and then can drop comment too

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +    ["i686", "x86_64"]
`.freeze`

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +      # Build the mingw-w64 headers
Can drop this comment

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +      # Create a mingw symlink, expected by some tools
e.g. which tools (add inline)

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +      EOS
Move the EOS back two characters.

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +      int main() { puts("Hello world!"); MessageBox(NULL, TEXT("Hello GUI!"), TEXT("HelloMsg"), 0); return 0; }
Indent this line to be <=80 characters

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +    compiler = { ".c" => "gcc", ".cc" => "g++", ".f90" => "gfortran" }.freeze
I'd just hardcode the usage of this Hash; it's harder to follow as-is

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +        # Compile a test program in each language
Can kill this comment

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +    # We match the output of `objdump` in English
Can kill this comment

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +        # Check the format of the executable produced
Can kill this comment

2017-02-11 17:42 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +  # option "without-multilib", "Build 64-bit compiler with multilib support"
Probably worth removing this comment/option and all references to it until it's working.

2017-02-11 17:43 UTC, MikeMcQuaid commented
A bunch of comments but this seems almost ready to 🚢, nice work.

2017-02-11 17:53 UTC, fxcoudert commented on Formula/mingw-w64.rb
> +    bin.mkdir
Needed so we can symlink binaries from both toolchains later on (at the end of the loop). I moved it up so we only mkdir the directory once.

2017-02-11 17:54 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +    bin.mkdir
It's a no-op if done multiple times so probably worth moving it down just to be clearer as to why

2017-02-11 18:26 UTC, fxcoudert commented on Formula/mingw-w64.rb
> +    bin.mkdir
Well, apparently not such as no-op… `Errno::EEXIST: File exists - /usr/local/Cellar/mingw-w64/5.0.1/bin`

I am retesting with `mkdir_p` which should fix that.

2017-02-11 18:46 UTC, MikeMcQuaid commented on Formula/mingw-w64.rb
> +    bin.mkdir
Use `bin.mkpath`

2017-02-11 18:55 UTC, fxcoudert commented
@MikeMcQuaid I've made all the changes (except I used `mkdir_p bin` instead of `bin.mkpath` as I didn't know the later existed… I hope it's minor enough, I can't rebuild and test right now)

2017-02-12 14:29 UTC, MikeMcQuaid approved these changes

2017-02-12 14:36 UTC, MikeMcQuaid commented
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-02-12 14:37 UTC, closed without merging