bluepill 0.2.2 (new formula)
Homebrew/homebrew-core pull request #9779
Opened 2017-02-09 05:07 UTC by khoiln

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Bluepill is a reliable iOS testing tool that runs UI tests using multiple simulators on a single machine.

Somehow `brew audit` hung on my machine, however I have download the `.rubocop.yml` config from the master repo and run it manually with `rubocop -c .rubocop.yml bluepill.rb` to make sure it passes all the validation. 

Reviews are much appreciated.

2017-02-09 05:48 UTC, rakkesh commented on Formula/bluepill.rb
> +  desc "Bluepill is a reliable iOS testing tool that runs UI tests using multiple simulators on a single machine"
Description needs to be limited to 80 characters. You may leave out the obvious stuff, e.g.,
"iOS testing tool that runs UI tests using multiple simulators on a machine" or
"Reliable iOS UI testing tool that can run multiple simulators on a machine".

2017-02-09 05:49 UTC, rakkesh commented on Formula/bluepill.rb
> +    bin.install("bluepill")
Is there no build step here? `Homebrew` prefers to build from source code instead of distributing binaries.

2017-02-09 05:51 UTC, khoiln commented on Formula/bluepill.rb
> +    bin.install("bluepill")
I'll update it accordingly

2017-02-09 06:10 UTC, khoiln commented
@rakkesh Thanks for the review, I've updated the install method to build from source. I'm not sure how could we leverage the pre-build install package though. How do I add this to the formula?

I'm literally lost in the documentation, a point to the correct doc would be awesome.

2017-02-09 06:42 UTC, rakkesh commented
> I'm not sure how could we leverage the pre-build install package though.

Is there a need for pre-built package here?

You could refer to the `Formula` related documentation here - https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md.

2017-02-09 07:32 UTC, rakkesh commented
@khoiln The installation for this formula seems to be empty. 
```
The installation seems to be empty. Please ensure the prefix
    is set correctly and expected files are installed.
    The prefix configure/make argument may be case-sensitive.
```
Could please verify this on your machine again.

I have updated the formula with some minor changes - use release tarball, and `depends_on :xcode => :build`.

```rb
class Bluepill < Formula
  desc "iOS testing tool that runs UI tests using multiple simulators"
  homepage "https://github.com/linkedin/bluepill"
  url "https://github.com/linkedin/bluepill/archive/v0.2.2.tar.gz"
  sha256 "51498393b0a59619a3adc624439abf116225d5d2666f7aae9390c2e4f8e88475"
  head "https://github.com/linkedin/bluepill.git"

  depends_on :xcode => :build

  def install
    system "./scripts/bluepill.sh", "build"
    bin.install("./build/Build/Products/Release/bluepill")
  end

  test do
    system bin/"bluepill", "-h"
  end
end
```

2017-02-09 07:34 UTC, khoiln commented
Thanks again @rakkesh,

It actually works on my machine without any problem

`./scripts/bluepill.sh` does actually exist in the tarball. 

I'm trying to debug the problem but still can't figure it out. Maybe you could help out?

2017-02-09 08:33 UTC, rakkesh commented
```
$ brew install bluepill -svd  ## -v => verbose, -d => debug
```
If there is an error, you get an option to drop into a shell. If there is no error, then try inserting a `raise` somewhere relevant in `def install`. When in the shell, check for the existence of `./build/Build/Products/Release/bluepill`, which seems to be missing.

2017-02-12 14:58 UTC, MikeMcQuaid requested changes

2017-02-12 14:58 UTC, MikeMcQuaid commented on Formula/bluepill.rb
> +    :revision => "d35f56c1b8f62cfc6a4fdb5ec11c252d31451978"
Does this use submodules? If not, use the tarball.

2017-02-12 14:58 UTC, MikeMcQuaid commented on Formula/bluepill.rb
> +    bin.install("./build/Build/Products/Release/bluepill")
Remove the parentheses.

2017-02-12 14:58 UTC, MikeMcQuaid commented on Formula/bluepill.rb
> +    system bin/"bluepill", "-h"
Use `assert_match` and `shell_output` to verify the output.

2017-02-18 22:08 UTC, dunn commented
Any progress here?

2017-02-24 12:46 UTC, khoiln commented
I still couldn't figure out what's wrong with this brew

2017-02-24 14:55 UTC, ilovezfs commented
It's a sandbox issue. The build is fine with --no-sandbox.

2017-02-24 15:49 UTC, ilovezfs submitted a review, later dismissed
Please use the tarball with checksum instead of the tag. Also, I've suggested an install method which should work.

2017-02-24 15:49 UTC, ilovezfs commented on Formula/bluepill.rb
> +    :revision => "d35f56c1b8f62cfc6a4fdb5ec11c252d31451978"
``` 
  url "https://github.com/linkedin/bluepill/archive/v0.2.2.tar.gz"
  sha256 "51498393b0a59619a3adc624439abf116225d5d2666f7aae9390c2e4f8e88475"
```

2017-02-24 15:49 UTC, ilovezfs commented on Formula/bluepill.rb
> +    system "./scripts/bluepill.sh", "build"
```
    xcodebuild "-workspace", "Bluepill.xcworkspace",
               "-scheme", "bluepill",
               "-configuration", "Release",
               "SYMROOT=../",
               "DSTROOT=../dstroot"
    bin.install "dstroot/usr/local/bin/bluepill"
```

2017-02-24 16:18 UTC, khoiln commented
I;ve updated the formula accordingly

2017-02-24 16:21 UTC, ilovezfs commented on Formula/bluepill.rb
> +    system bin/"bluepill", "-h"
@khoiln looks like this bit still needs to be addressed.

2017-02-25 07:34 UTC, khoiln commented on Formula/bluepill.rb
> +    system bin/"bluepill", "-h"
@ilovezfs Yep, it's been updated thank you all

2017-03-12 10:11 UTC, fxcoudert commented
@BrewTestBot test this please

2017-03-12 21:47 UTC, fxcoudert commented
Thanks @khoiln for your contribution to Homebrew!

2017-03-12 21:47 UTC, closed without merging