elasticsearch 2.3
Homebrew/homebrew-core pull request #9814
Opened 2017-02-09 21:20 UTC by maxpsq

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-10 21:17 UTC, MikeMcQuaid requested changes

2017-02-10 21:17 UTC, MikeMcQuaid commented on Formula/elasticsearch@2.3.rb
> +  revision 1
Can remove this for new formulae.

2017-02-10 21:17 UTC, MikeMcQuaid commented
Is this version still supported by upstream?

2017-02-10 21:46 UTC, maxpsq commented on Formula/elasticsearch@2.3.rb
> +  revision 1
I don't get what can be removed...

2017-02-10 23:22 UTC, JCount commented on Formula/elasticsearch@2.3.rb
> +  revision 1
The revision line can be removed.

2017-02-10 23:57 UTC, maxpsq commented
Yes, this version is still supported.

2017-02-12 15:07 UTC, MikeMcQuaid approved these changes

2017-02-12 15:07 UTC, merged

2017-02-12 15:07 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!