mysql-connector-c++: add license
Homebrew/homebrew-core pull request #98315
Opened 2022-04-01 05:27 UTC by chenrui333

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

<details>
<summary>license ref</summary>

```
/*
 * Copyright (c) 2018, 2019, Oracle and/or its affiliates. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2.0, as
 * published by the Free Software Foundation.
 *
 * This program is also distributed with certain software (including
 * but not limited to OpenSSL) that is licensed under separate terms,
 * as designated in a particular file or component or in included license
 * documentation.  The authors of MySQL hereby grant you an
 * additional permission to link the program and your derivative works
 * with the separately licensed software that they have included with
 * MySQL.
 *
 * Without limiting anything contained in the foregoing, this file,
 * which is part of MySQL Connector/C++, is also subject to the
 * Universal FOSS Exception, version 1.0, a copy of which can be found at
 * http://oss.oracle.com/licenses/universal-foss-exception.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License, version 2.0, for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA
 */
```

</details>

2022-04-01 11:28 UTC, SMillerDev requested changes

2022-04-01 11:28 UTC, SMillerDev commented on Formula/mysql-connector-c++.rb
> +  license "GPL-2.0-only" => { with: "openvpn-openssl-exception" }
Doesn't seem true http://oss.oracle.com/licenses/universal-foss-exception

2022-04-01 12:35 UTC, carlocab commented on Formula/mysql-connector-c++.rb
> +  license "GPL-2.0-only" => { with: "openvpn-openssl-exception" }
```suggestion
  license "GPL-2.0-only" => { with: "Universal-FOSS-exception-1.0" }
```

2022-04-02 08:59 UTC, carlocab approved these changes

2022-04-02 09:05 UTC, SMillerDev approved these changes

2022-04-02 10:05 UTC, closed without merging