ansible@2.8: fix build on Monterey
Homebrew/homebrew-core pull request #98441
Opened 2022-04-02 22:14 UTC by cho-m

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-04-03 20:01 UTC, iMichka requested changes
I think we should bump the revision to ship the updated resource for everyone.

2022-04-06 19:55 UTC, EricFromCanada commented
If you don't mind, I've added a commit that also fixes its build on Sierra. At some point between versions 4.5.0 and 4.6.3, `lxml` was updated to not cause the "file not found: /usr/lib/system/libsystem_darwin.dylib" error on Sierra and earlier.

2022-04-06 21:10 UTC, iMichka approved these changes

2022-04-06 22:04 UTC, closed without merging

2022-04-06 23:23 UTC, cho-m commented
I think the CI-no-bottles ended up leaving old bottle block. Will need to trigger rebuild