Update: CompCert C version 3.0
Homebrew/homebrew-core pull request #9875
Opened 2017-02-11 23:47 UTC by beurdouche

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-12 08:33 UTC, beurdouche commented
? @ilovezfs

2017-02-12 08:41 UTC, ilovezfs commented
@beurdouche sorry for not commenting right away. So ... a couple things. First, we never put `revision 0`. The counting of revisions does start from 0, but we only add an explicit revision when it's >= 1.

Second, are you sure we can flat out replace the ia32-macosx with x86_64-macosx, and don't need to build both or make one optional and the other default? I saw in the Changelog that it said:

>The x86 port of CompCert was extended to produce x86-64 bit code in
  addition to the original x86-32 bit (IA32) code.  (This is the first
  instantiation of the new support for 64-bit targets described
  above.) Support for x86-64 is currently available for Linux and MacOS X.
  (Run the configure script with 'x86_64-linux' or 'x86_64-macosx'.)
  This is an early port: several ABI incompatibilities remain.

(http://compcert.inria.fr/release/Changelog)

2017-02-12 08:59 UTC, beurdouche commented
@ilovezfs no worries. 
After thinking a bit more about it, I think you are right. It might be more reasonable to keep `ia32-macosx` as the default for this release and offer the option for building `x86_64`.
I'll discuss with Xavier Leroy (the author) to make sure that we can switch default and option in a future release.
Also I just noticed a bug in the version number (hasn't been incremented to 3.0.0) and reported it upstream. Maybe we can do a patch just to fix the VERSION file ?
WDYT ?

2017-02-12 09:04 UTC, ilovezfs commented
Yup. All sounds correct to me. If the version number does get patched upstream right away, but a new tarball isn't published, then it would be best to apply the commit as a patch, but if not an `inreplace` will work.

2017-02-16 15:52 UTC, beurdouche commented
Ok, the version problem has been fixed and the release has been re-tagged upstream, so no patch necessary.

Remains: 
[] updating the script with the new tarball/hash
[] creating the option to build with ia32 or x86_64

I'll try to do that tomorrow except if someone manages to do it before..

2017-02-16 15:54 UTC, ilovezfs commented
@beurdouche did you get a chance to talk with Xavier?

2017-02-17 08:29 UTC, beurdouche commented
@ilovezfs Ok I discussed with Xavier by email. He suggested to separate Compcert32 (more stable) and Compcert64 (more experimental) for now, so I proceeded by adding an option to compile `x86_64` if the user chooses it. Please note that while it seems to work properly I am not super familiar with options for Homebrew and, in particular, naming conventions. The PR is currently ready to be merged from my perspective, please don't hesitate to make adjustments where you see fit ;)

2017-02-17 08:34 UTC, beurdouche commented
Ps: just squashed the commits

2017-02-20 12:03 UTC, MikeMcQuaid requested changes

2017-02-20 12:03 UTC, MikeMcQuaid commented on Formula/compcert.rb
> +    if build.without? "config-x86_64"
Use `build.with?` instead; it's a little easier to follow.

2017-02-20 12:03 UTC, MikeMcQuaid commented
> Compcert64 (more experimental) for now, so I proceeded by adding an option to compile x86_64 if the user chooses it.

Maybe it's worth removing the option unless you personally use it?

2017-02-20 12:14 UTC, ilovezfs commented
The option is the cool new toy.

2017-02-20 12:45 UTC, beurdouche commented
@MikeMcQuaid @ilovezfs, I actually suspect that the option will be very used, yes :)
JustChanged the code to use `build.with ?` instead, thank you for the suggestion.

2017-02-20 12:58 UTC, MikeMcQuaid commented
> @MikeMcQuaid @ilovezfs, I actually suspect that the option will be very used, yes :)

@beurdouche Will you personally be using it or not?

2017-02-20 12:59 UTC, beurdouche commented
@MikeMcQuaid Yes, I am using it, as well as half of the lab.

2017-02-20 13:46 UTC, ilovezfs commented
@BrewTestBot test this please

2017-02-20 14:24 UTC, MikeMcQuaid commented
@beurdouche In that case I might be in favour for saying it should just be the default?

2017-02-20 14:26 UTC, ilovezfs commented
@MikeMcQuaid upstream has basically explicitly said that it's not considered stable yet and there are API incompatibilities.

2017-02-20 14:34 UTC, beurdouche commented
@MikeMcQuaid we discussed it but we think it is too early. We will probably change the default in 3.1 or 3.2 after another discussion with the authors.

2017-02-20 21:32 UTC, MikeMcQuaid approved these changes

2017-02-21 01:01 UTC, ilovezfs commented
@BrewTestBot test this please

2017-02-21 17:58 UTC, beurdouche commented
@BrewTestBot test this please

2017-02-21 18:42 UTC, beurdouche commented
@ilovezfs Good to go ;)

2017-02-21 18:56 UTC, MikeMcQuaid commented
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-02-21 18:57 UTC, closed without merging

2017-02-21 19:02 UTC, beurdouche commented
@ilovezfs @MikeMcQuaid Thanks a lot to both of you ! ;)