Add wsk (OpenWhisk CLI binary) formula
Homebrew/homebrew-core pull request #9879
Opened 2017-02-12 04:56 UTC by shaftoe

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)? **Unfortunately seems almost impossible to follow them strictly, I first tried as a `Cask` but I've been asked to try here instead because even if it's distributed as a binary, it's maintained as an Open Source project**
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting? **Same caveat as point 1**
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-12 15:15 UTC, MikeMcQuaid requested changes

2017-02-12 15:15 UTC, MikeMcQuaid commented on Formula/wsk.rb
> +  url "https://openwhisk.ng.bluemix.net/cli/go/download/mac/amd64/OpenWhisk_CLI-mac.zip"
This needs to be built from source from a versioned source.

2017-02-12 15:15 UTC, MikeMcQuaid commented on Formula/wsk.rb
> +  end
Remove these caveats.

2017-02-12 15:15 UTC, MikeMcQuaid commented on Formula/wsk.rb
> +    system "true"
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2017-02-12 15:15 UTC, MikeMcQuaid commented
> if it's distributed as a binary, it's maintained as an Open Source project

We need to build it from source. If it's open source this should be possible.

2017-02-13 02:59 UTC, shaftoe commented on Formula/wsk.rb
> +    system "true"
I thought about that, but there's no `--version` or similar available from the CLI tool. Actually, there seems to be no official version at all for the OpenWhisk project: no Git tags, no (CHANGELOG|VERSION) file. Invoking the binary alone prints help to stdout and returns 0, I guess it's better then nothing

2017-02-13 03:06 UTC, shaftoe commented on Formula/wsk.rb
> +  url "https://openwhisk.ng.bluemix.net/cli/go/download/mac/amd64/OpenWhisk_CLI-mac.zip"
The only version available is the commit id for the master branch, there are no tags nor other versions available in the project, or at least I can't find any. I guess the only option is https://github.com/openwhisk/openwhisk/archive/master.zip

2017-02-13 03:15 UTC, shaftoe commented
@MikeMcQuaid ok, I'll try to make it, but this will force the user to install Java + Gradle + Docker... feels very overkill for having only a small binary installed as suggested by the official documentation. Wouldn't this be a better fit as a Cask?

2017-02-13 03:53 UTC, shaftoe commented
I've spent some time trying to make it install via Brew, but failed (I managed to compile it from CLI though). It's failing with this message:
```
==> gradle :tools:cli:distDocker

FAILURE: Build failed with an exception.

* What went wrong:
Failed to load native library 'libnative-platform.dylib' for Mac OS X x86_64.
```

I'm sorry but I have to give up, I've got not enough time nor will to invest in this, I'll try again to submit the request to Cask. Thanks for your time!

2017-02-13 03:53 UTC, closed without merging

2017-02-13 13:02 UTC, markusthoemmes commented
It's not dependend on Java, Gradle or Docker I think. It should be compilable using plain Go just fine.