grpc: add formula for v1.1.2
Homebrew/homebrew-core pull request #9942
Opened 2017-02-13 22:30 UTC by stanley-cheung

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes grpc/homebrew-grpc#97

2017-02-15 16:29 UTC, MikeMcQuaid requested changes

2017-02-15 16:29 UTC, MikeMcQuaid commented on Formula/grpc.rb
> +  end
Remove this, we'll be building our own bottles.

2017-02-15 16:29 UTC, MikeMcQuaid commented on Formula/grpc.rb
> +    # TODO(mxyan): find a better solution
Create a `resource` and `stage` that into the directory instead.

2017-02-15 16:29 UTC, MikeMcQuaid commented on Formula/grpc.rb
> +  option "with-plugins", "Also install gRPC protoc plugins."
Let's remove the option and install these by default.

2017-02-15 16:29 UTC, MikeMcQuaid commented on Formula/grpc.rb
> +      # Link the Objective-C plugin to the name protoc expects.
Why doesn't `grpc` name this correctly? Can you submit an issue upstream? Thanks!

2017-02-15 16:29 UTC, MikeMcQuaid commented on Formula/grpc.rb
> +    system Formula["pkg-config"].bin/"pkg-config", "--libs", "grpc"
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Thanks!

2017-02-15 19:09 UTC, stanley-cheung commented on Formula/grpc.rb
> +  end
Removed

2017-02-15 19:10 UTC, stanley-cheung commented on Formula/grpc.rb
> +  option "with-plugins", "Also install gRPC protoc plugins."
Removed

2017-02-15 19:10 UTC, stanley-cheung commented on Formula/grpc.rb
> +    # TODO(mxyan): find a better solution
I removed this for now and will try to fix it on our side

2017-02-15 19:10 UTC, stanley-cheung commented on Formula/grpc.rb
> +      # Link the Objective-C plugin to the name protoc expects.
Will fix this on our side

2017-02-15 19:10 UTC, stanley-cheung commented on Formula/grpc.rb
> +    system Formula["pkg-config"].bin/"pkg-config", "--libs", "grpc"
Done. Thanks for the pointer!

2017-02-18 22:47 UTC, dunn commented
I'm having trouble merging this; could you rebase it against the current master?

2017-02-19 00:48 UTC, stanley-cheung commented
@dunn Done. Just rebased off the latest master. Thanks.

2017-02-19 02:35 UTC, dunn commented
Thanks! Merged as cf4337c63afe4e2949478fa9d211ca53e9589c4a.

2017-02-19 02:35 UTC, closed without merging