autobump: track more formulae
Homebrew/homebrew-core pull request #99474
Opened 2022-04-17 02:52 UTC by chenrui333

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

2022-04-18 01:01 UTC, samford requested changes
I've gone through the added formulae in this PR and identified the ones that can't be added at this point (review comments below). For future reference, these are: `hpack`, `rover`, `scalapack`, and `triangle`.

I've also identified formulae that need (or would benefit from) `livecheck` block changes and opened a few related PRs. The `livecheck` PRs should be merged before this PR.

2022-04-18 08:11 UTC, MikeMcQuaid reviewed
Thanks for adding more of these @chenrui333 and checking them over @samford!

2022-04-18 19:34 UTC, samford commented on .github/workflows/autobump.yml
> +    triangle
Repology split this into a separate `triangle-art` entry, so this is fine now:

```
==> triangle
Current formula version:  1.2.5
Latest livecheck version: 1.2.5
Latest Repology version:  present only in Homebrew
```

2022-04-21 00:28 UTC, samford commented on .github/workflows/autobump.yml
> +    hpack
This has been resolved on Repology, so it's fine now.

```
==> hpack is up to date!
Current formula version:  0.34.7
Latest livecheck version: 0.34.7
Latest Repology version:  0.34.7
```

2022-04-21 00:29 UTC, samford commented on .github/workflows/autobump.yml
> +    rover
This has been resolved on Repology, so it's fine now (the newer livecheck version is correct).

```
==> rover
Current formula version:  0.5.0
Latest livecheck version: 0.5.1
Latest Repology version:  0.5.0
```

2022-04-24 03:01 UTC, samford approved these changes

2022-04-25 08:07 UTC, MikeMcQuaid approved these changes

2022-04-25 08:07 UTC, merged