luajit: deprecate; luajit-openresty: swap linkage
Homebrew/homebrew-core pull request #99580
Opened 2022-04-19 04:34 UTC by cho-m

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Potential PR to close #68013. Not sure if this is best choice.

Was considering deprecating `luajit` and swaping keg status with `luajit-openresty`. And later on adding to `formula_renames.json` to migrate `luajit` to `luajit-openresty`. 

Alternatives:
- Can directly rename (though may impact users expecting older `luajit`)
- Can consider some other deletion/migration process.
- Can just keep as is.

Currently, there is 0 usage of `luajit` in `homebrew-core` with most/all being migrated to `luajit-openresty`. At this point, it seems better to link the maintained `luajit-openresty` formula rather than old `luajit`.

2022-04-19 08:39 UTC, SMillerDev approved these changes

2022-04-19 17:34 UTC, carlocab commented
Have thoughts here, but a bit busy at the moment. Will pop back in later this week.

2022-04-21 19:04 UTC, danielnachun commented
While we're at it, can we also change
```ruby
lib.install_symlink lib/"libluajit-5.1.dylib" => "libluajit.dylib"
```
to
```ruby
lib.install_symlink lib/shared_library("libluajit-5.1") => shared_library("libluajit")
```

2022-06-27 22:09 UTC, cho-m commented
@carlocab, did you want to consider a different approach?

---

> ```ruby
> lib.install_symlink lib/shared_library("libluajit-5.1") => shared_library("libluajit")
> ```

@danielnachun I feel we should do this in separate PR with revision bump.

2022-06-27 22:24 UTC, carlocab commented
Oops, yes, this slipped my mind, sorry. Will get back to you later today.

2022-06-28 18:08 UTC, carlocab requested changes
I don't think we should deprecate `luajit`. Instead, we should consider building this formula from Git, even if it's from commits that are not tagged.

I know we don't like building without tags, but I think we ought to make an exception here.

1. It's what [nearly everyone else](https://repology.org/project/luajit/versions) is doing. Notably, Debian, Fedora, and Ubuntu all package a version built from a recent-ish commit.
2. If we look at the [analytics](https://formulae.brew.sh/formula/luajit#default), there are twice as many `--HEAD` installs as there are installs of the stable version, so there's a strong indication of which version our users are looking for.

(2) above is especially noteworthy: 2/3 of its users install using `--HEAD`, but we get essentially zero support requests over it (and we do get issues about `--HEAD` installs every now and then). It's also what the [maintainer recommends](https://github.com/LuaJIT/LuaJIT/issues/648#issuecomment-752404043), which, in my view, is a sign that a build from Git is good for production and won't impact our support burden (or, at least, no worse than many other formulae we ship). This isn't very different from `vim`, except that Vim's maintainer does everyone the courtesy of always tagging `HEAD`.

This does leave open how we choose to update the formula if we do this. I have some ideas about how to do so, but I wanted to hear thoughts on whether this is something we can/will do first.

CC @Homebrew/core for thoughts.

2022-06-29 12:34 UTC, MikeMcQuaid commented
> Instead, we should consider building this formula from Git, even if it's from commits that are not tagged.

I read this and thought: 👎🏻. I read your reasoning and thought: 👍🏻. Pragmatism like this and being willing to violate our own rules when they don't make sense for our users I'm very 👍🏻 on. That said, I want to make sure that we ensure our documentation makes clear this is a (very) exceptional case.

> This does leave open how we choose to update the formula if we do this. I have some ideas about how to do so, but I wanted to hear thoughts on whether this is something we can/will do first.

Update once a month to the latest commit on the latest stable branch?

2022-06-30 05:04 UTC, carlocab commented
Opened #104765.

2022-07-03 00:52 UTC, cho-m commented
Closing in favor of #104765

2022-07-03 00:52 UTC, closed without merging