globjects 1.0.0 (new formula)
Homebrew/homebrew-core pull request #9960
Opened 2017-02-14 10:41 UTC by andrew-kennedy

just adding the globjects library to homebrew.

2017-02-14 10:49 UTC, bfontaine requested changes

2017-02-14 10:49 UTC, bfontaine commented on Formula/globjects.rb
> +    args << "-Dglbinding_DIR=" + Formula["glbinding"].prefix
You don’t need to build an array here; just add `"-Dglbinding_DIR=#{Formula["glbinding"].opt_prefix}"` to the arguments list below.

2017-02-14 10:49 UTC, bfontaine commented on Formula/globjects.rb
> +  needs :cxx11
Please leave an empty line after that one.

2017-02-14 10:59 UTC, bfontaine approved these changes

2017-02-14 11:04 UTC, andrew-kennedy commented
Tests are succeeding on my machine but failing on TestBot build, probably due to glm dependencies auto resolving. Will try to modify test cases to correctly resolve the includes

2017-02-15 16:43 UTC, MikeMcQuaid commented
Merged in a9228978237503e118fc1d730a7e221ab147c0a4.

Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-02-18 22:12 UTC, closed without merging