ktmpl 0.5.0 (new formula)
Homebrew/homebrew-core pull request #9977
Opened 2017-02-14 19:46 UTC by jimmycuadra

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

[ktmpl](https://github.com/InQuicker/ktmpl) is a tool for processing [Kubernetes](http://kubernetes.io/) manifest templates. It is a very simple client-side implementation of the [Templates + Parameterization proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/templates.md).

2017-02-15 16:23 UTC, MikeMcQuaid requested changes

2017-02-15 16:23 UTC, MikeMcQuaid commented on Formula/ktmpl.rb
> +
Remove this blank link, thanks.

2017-02-15 16:23 UTC, MikeMcQuaid commented on Formula/ktmpl.rb
> +    assert_match "ktmpl #{version}", shell_output("#{bin}/ktmpl --version")
Can this test be modified to do something more substantial than e.g. `--version` or `--help`? See `cmake.rb` for an example of an application formula with a good test and `tinyxml2.rb` for an example of a library formula with a good test. Consider generating a template. Thanks!

2017-02-16 00:13 UTC, jimmycuadra commented on Formula/ktmpl.rb
> +    assert_match "ktmpl #{version}", shell_output("#{bin}/ktmpl --version")
Done!

2017-02-18 22:47 UTC, dunn commented on Formula/ktmpl.rb
> +    system "cargo", "build", "--release"
Just to be safe, `Formula["rust"].opt_bin/"cargo"`

2017-02-20 12:19 UTC, MikeMcQuaid commented on Formula/ktmpl.rb
> +    system "cargo", "build", "--release"
@dunn I think I'm fine as-is; superenv will adjust the PATH accordingly anyway.

2017-02-20 12:20 UTC, MikeMcQuaid approved these changes

2017-02-20 12:39 UTC, MikeMcQuaid commented
Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

2017-02-20 12:39 UTC, closed without merging