postgres: fix caveats for fresh install
Homebrew/homebrew-core pull request #9978
Opened 2017-02-14 20:33 UTC by jmgarnier

Add script to create postgres role for fresh install

See http://lifelofranco.com/work/2016/10/31/rails-app.html

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

2017-02-15 14:13 UTC, jmgarnier commented
I guess  both commits should be squashed if this will be merged some day

2017-02-15 14:29 UTC, MikeMcQuaid requested changes
You only need to do this if you've previously run `createuser -s -r postgres`, right? I've never personally had to do this locally so it doesn't seem to be universally applicable so I'm currently 👎 on including this.

2017-02-15 15:50 UTC, jmgarnier commented
Thanks @MikeMcQuaid  I am not an expert Postgres user but it seems I am not the first to be hit by this missing step - no Superuser is created by homebrew - when `brew install postgresql` the 1st time. See http://stackoverflow.com/a/35308200/575950

Until I created this role, I could not run `psql` and run migrations on a fresh Phoenix project:
![image](https://cloud.githubusercontent.com/assets/8051/22982248/d7d0a51e-f39e-11e6-9a08-a43dba8ae4ed.png)

Is there a point doing more research to come up with a clearer message?

2017-02-15 15:53 UTC, MikeMcQuaid commented
Did you run `createuser -s -r postgres`?

2017-02-15 17:12 UTC, jmgarnier commented
I ran the equivalent, that I copy pasted from the blog post
```sql
CREATE ROLE postgres LOGIN
SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
```

Looking at https://www.postgresql.org/docs/9.6/static/sql-createrole.html user = role. 
Your version is shorter.  But I prefer explicit long parameters. What do you think if I amend my PR with the following SQL:
```sql
createuser --superuser --createrole postgres
```

2017-02-20 10:57 UTC, MikeMcQuaid commented
Passing on this for now but we'll consider it in future if this seems to be a more widespread problem rather than specific to that blog post. Thanks anyway!

2017-02-20 10:57 UTC, closed without merging

2017-02-20 11:11 UTC, jmgarnier commented
It was not specific to that blog post. I was setting a fresh phoenix app and I had to setup `postgres`. 

Anyway, If I ever need to make a fresh install of posgres with homebrew, I'll remember now and know where to look :)

Thanks for taking the time to review

2017-02-20 11:21 UTC, jmgarnier commented
Anyway, I can see why you got confused, I was not very clear.

I will open another PR with a clearer goal - help first time install - and hopefully it will help someone some day 😃

2017-02-20 11:22 UTC, MikeMcQuaid commented
@jmgarnier I think we can pass on a PR for now, thanks. I and many other users seem to have no need for this on a first time install. It may be specific to Phoenix but that's not relevant to Homebrew.

2017-02-20 11:27 UTC, jmgarnier commented
Fair enough, no PR then 😸  . 

For my own sake, I will ask some friends with more experience, I really need to understand how things work. I will come back with another PR if it's relevant to a broader scope than just "Phoenix".

Thanks again. I will make sure my next contributions are more straight forward.