tomcat@7 7.0.75
Homebrew/homebrew-core pull request #9992
Opened 2017-02-15 09:57 UTC by alanorth

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
New upstream release. Changelog: https://tomcat.apache.org/tomcat-7.0-doc/changelog.html#Tomcat_7.0.75_(violetagg)

2017-02-15 16:18 UTC, MikeMcQuaid requested changes

2017-02-15 16:18 UTC, MikeMcQuaid commented on Formula/tomcat@7.rb
> +    url "https://www.apache.org/dyn/closer.cgi?path=/tomcat/tomcat-7/v7.0.75/bin/apache-tomcat-7.0.73-fulldocs.tar.gz"
The second `7.0.73` needs fixed.

2017-02-15 16:18 UTC, MikeMcQuaid commented on Formula/tomcat@7.rb
> +    url "https://www.apache.org/dyn/closer.cgi?path=/tomcat/tomcat-7/v7.0.75/bin/apache-tomcat-7.0.73-fulldocs.tar.gz"
https://bot.brew.sh/job/Homebrew%20Core/16491/version=sierra/testReport/junit/brew-test-bot/sierra/fetch_tomcat_7/

2017-02-15 16:48 UTC, alanorth commented on Formula/tomcat@7.rb
> +    url "https://www.apache.org/dyn/closer.cgi?path=/tomcat/tomcat-7/v7.0.75/bin/apache-tomcat-7.0.73-fulldocs.tar.gz"
Ah, yes. Fixed.

2017-02-18 09:54 UTC, nijikon commented
You are awesome, thanks for your contribution! :tada:

2017-02-18 09:55 UTC, closed without merging